<?php
/**
 * Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine <himself@claus-justus-heine.de>
 * @copyright 2020-2026 Claus-Justus Heine
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB\Controller;

use InvalidArgumentException;

use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute as CoreAttributes;
use OCP\IRequest;

use OCA\CAFEVDB\Service\ConfigService;
use OCA\CAFEVDB\Service\DTO\EventMatrixEvent;
use OCA\CAFEVDB\Service\EventsService;

/** AJAX end-points to manage events linked to projects */
class ProjectEventsController extends Controller
{
  use \OCA\CAFEVDB\Traits\ConfigTrait;
  use \OCA\CAFEVDB\Toolkit\Traits\DateTimeTrait;

  // phpcs:disable Squiz.Commenting.FunctionComment.Missing
  public function __construct(
    ?string $appName,
    IRequest $request,
    private EventsService $eventsService,
    protected ConfigService $configService,
  ) {
    parent::__construct($appName, $request);
    $this->l = $this->l10N();
  }
  // phpcs:enable

  /**
   * Provide a value for an input element (select option, input) which codes
   * all neccessary info to uniquely identify the event and call the repective
   * calendar app url to initiate the editor.
   *
   * @param EventMatrixEvent $event Event-data as generated by EventsService::eventMatrix().
   *
   * @return array
   *
   * @note Still used by EmailForm\Composer
   *
   * @bug This should not be located in this file.
   */
  public static function makeInputValue(EventMatrixEvent $event):array
  {
    $calendarObject = [
      'timeRange' => $event->start->format('Y-m-d'),
      'objectId' => base64_encode($event->urlPath),
      'recurrenceId' => $event->recurrenceId ?? $event->start->getTimestamp(),
    ];
    $calendarObjectData = json_encode($calendarObject, JSON_FORCE_OBJECT);

    return [
      'calendarId' => $event->calendarId,
      'uri' => $event->uri,
      'recurrenceId' => $event->recurrenceId ?? 0,
      'calendarObject' => $calendarObjectData, // this is needed in order to connect the calendar app.
    ];
  }

  /**
   * @param int $projectId
   *
   * @param string $projectName
   *
   * @param array $selectedEvents
   *
   * @param array $calendarIds
   *
   * @return Http\Response
   */
  #[CoreAttributes\NoAdminRequired]
  #[CoreAttributes\FrontpageRoute(verb: 'POST', url: '/projects/events/download')]
  public function download(
    int $projectId,
    string $projectName,
    array $selectedEvents = [],
    array $calendarIds = [],
  ): Http\DataDownloadResponse {

    if ($projectId <= 0 || empty($projectName)) {
      throw new InvalidArgumentException(
        $this->l->t(
          'Project-id AND -name have to be specified (%s / %s).', [
            empty($projectId) ? '?' : $projectId,
            empty($projectName) ? '?' : $projectName,
          ],
        ),
      );
    }

    $exports = []; // array marking selected events
    foreach ($selectedEvents as $eventIdentifier) {
      $eventIdentifier = json_decode($eventIdentifier, true);
      $flatIdentifier = EventsService::makeFlatIdentifier($eventIdentifier);
      $exports[$flatIdentifier] = $eventIdentifier;
    }

    if (empty($exports)) {
      foreach ($calendarIds as $eventUri => $calendarId) {
        $exports[] = [ 'calendarId' => $calendarId, 'uri' => $eventUri ];
      }
    }

    $fileName = $projectName . '-' . $this->timeStamp() . '.ics';

    return new Http\DataDownloadResponse(
      $this->eventsService->exportEvents($exports, $projectName),
      $fileName,
      'text/calendar',
    );
  }
}
