<?php
/**
 * Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine <himself@claus-justus-heine.de>
 * @copyright 2020-2025 Claus-Justus Heine
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB\Controller;

use DateTimeZone;
use InvalidArgumentException;
use Throwable;

use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\IRequest;

use OCA\CAFEVDB\Database\Doctrine\ORM\Entities;
use OCA\CAFEVDB\Exceptions;
use OCA\CAFEVDB\Service\CalDavService;
use OCA\CAFEVDB\Service\ConfigService;
use OCA\CAFEVDB\Service\EventsService;
use OCA\CAFEVDB\Service\ToolTipsService;

/** AJAX end-points to manage events linked to projects */
class ProjectEventsController extends Controller
{
  use \OCA\CAFEVDB\Toolkit\Traits\ResponseTrait;
  use \OCA\CAFEVDB\Traits\ConfigTrait;
  use \OCA\CAFEVDB\Toolkit\Traits\DateTimeTrait;

  // phpcs:disable Squiz.Commenting.FunctionComment.Missing
  public function __construct(
    ?string $appName,
    IRequest $request,
    private CalDavService $calDavService,
    private EventsService $eventsService,
    protected ConfigService $configService,
  ) {
    parent::__construct($appName, $request);
    $this->l = $this->l10N();
  }
  // phpcs:enable

  /**
   * Generate data for connecting to the NC calendar app as of NC >= v30.
   *
   * @param array $event Event data as generated by EventsService::eventMatrix().
   *
   * @return array
   * ```
   * [
   *   'single' => [ 'timeRange' =>, 'objectId' =>, 'recurrenceId' =>, ],
   *   'series' => [ 'timeRange' =>, 'objectId' =>, 'recurrenceId' =>, ],
   * ]
   * ```
   * "series" refers to the start event of an event series.
   */
  public static function makeCalendarAppData(array $event): array
  {
    $startStamp = [
      'single' => $event['start']->getTimestamp(),
      'series' => $event['seriesStart']->getTimestamp(),
    ];
    $calendarObjectId = base64_encode($event['urlPath']);
    $calendarObject = [
      'single' => [
        'timeRange' => $event['start']->format('Y-m-d'),
        'objectId' => $calendarObjectId,
        'recurrenceId' => empty($event['recurrenceId']) ? $startStamp['single'] : $event['recurrenceId'],
      ],
      'series' => [
        'timeRange' => $event['seriesStart']->format('Y-m-d'),
        'objectId' => $calendarObjectId,
        'recurrenceId' => $startStamp['series'],
      ],
    ];

    return $calendarObject;
  }

  /**
   * Provide a value for an input element (select option, input) which codes
   * all neccessary info to uniquely identify the event and call the repective
   * calendar app url to initiate the editor.
   *
   * @param array $event Event-data as generated by EventsService::eventMatrix().
   *
   * @return array
   *
   * @note Still used by EmailForm\Composer
   */
  public static function makeInputValue(array $event):array
  {
    $calendarObject = self::makeCalendarAppData($event);
    $calendarObjectData = json_encode($calendarObject['single'], JSON_FORCE_OBJECT);

    return [
      'calendarId' => $event['calendarId'],
      'uri' => $event['uri'],
      'recurrenceId' => $event['recurrenceId'] ?? 0,
      'calendarObject' => $calendarObjectData, // this is needed in order to connect the calendar app.
    ];
  }

  /**
   * @param string $topic
   *
   * @return Http\Response
   *
   * @NoAdminRequired
   */
  public function download(string $topic):Http\Response
  {
    $projectId = $this->request['projectId'];
    $projectName = $this->request['projectName'];

    if (empty($projectId) || empty($projectName)) {
      throw new InvalidArgumentException(
        $this->l->t(
          'Project-id AND -name have to be specified (%s / %s).', [
            empty($projectId) ? '?' : $projectId,
            empty($projectName) ? '?' : $projectName,
          ],
        ),
      );
    }

    $selectedEvents = array_unique($this->request->getParam('eventSelect', []));
    $calendarIds = array_unique($this->request->getParam('calendarId', []));

    $exports = []; // array marking selected events
    foreach ($selectedEvents as $eventIdentifier) {
      $eventIdentifier = json_decode($eventIdentifier, true);
      $flatIdentifier = EventsService::makeFlatIdentifier($eventIdentifier);
      $exports[$flatIdentifier] = $eventIdentifier;
    }

    if (empty($exports)) {
      foreach ($calendarIds as $eventUri => $calendarId) {
        $exports[] = [ 'calendarId' => $calendarId, 'uri' => $eventUri ];
      }
    }

    $fileName = $projectName.'-'.$this->timeStamp().'.ics';

    return $this->dataDownloadResponse(
      $this->eventsService->exportEvents($exports, $projectName),
      $fileName,
      'text/calendar');
  }
}
