CamerataDB: OpenSSLAsymmetricCryptor Class Reference
OpenSSLAsymmetricCryptor Class Reference
Asymmetric encryption using the OpenSSL extension of PHP.
Public Member Functions
__construct (mixed $privKey=null, string $password=null)
setPrivateKey (mixed $privKey, ?string $password=null)
{
Parameters
mixed $privKey
null | string $password Maybe ignored depending on the implementation, i.e. the key may have to be unlocked or decrypted before passing it to the cryptor.
Returns
AsymmetricCryptorInterface $this
}
setPublicKey (mixed $pubKey)
{
Parameters
mixed $pubKey
Returns
AsymmetricCryptorInterface $this
}
getPublicKey ()
{
Returns
mixed Return the currently used public key.
}
encrypt (?string $decryptedData)
{
Parameters
null | string $data
Returns
null|string
}
decrypt (?string $encryptedData)
{
Parameters
null | string $data
Returns
null|string
}
sign ($data)
{}
verify ($data, string $signature)
{}
canEncrypt ()
{
Returns
bool
}
canDecrypt ()
{
Returns
bool
}
canSign ()
{
Returns
bool
}
canVerify ()
{
Returns
bool
}
sign (?string $data)
verify (?string $data, string $signature)
Private Attributes
const SIGNING_ALGORITHM = OPENSSL_ALGO_SHA512
$privKey = null
$pubKey = null
Detailed Description
Asymmetric encryption using the OpenSSL extension of PHP.
Definition at line 30 of file OpenSSLAsymmetricCryptor.php.
Constructor & Destructor Documentation
__construct()
__construct (mixed $privKey = null, string $password = null)
Parameters
mixed $privKey
string $password
Definition at line 43 of file OpenSSLAsymmetricCryptor.php.
References OpenSSLAsymmetricCryptor\setPrivateKey().
Member Function Documentation
canDecrypt()
canDecrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 134 of file OpenSSLAsymmetricCryptor.php.
Referenced by OpenSSLAsymmetricCryptor\canSign().
canEncrypt()
canEncrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 128 of file OpenSSLAsymmetricCryptor.php.
Referenced by OpenSSLAsymmetricCryptor\canVerify().
canSign()
canSign ()
{
Returns
bool
}
Implements AsymmetricCryptorInterface.
Definition at line 141 of file OpenSSLAsymmetricCryptor.php.
References OpenSSLAsymmetricCryptor\canDecrypt().
canVerify()
canVerify ()
{
Returns
bool
}
Implements AsymmetricCryptorInterface.
Definition at line 147 of file OpenSSLAsymmetricCryptor.php.
References OpenSSLAsymmetricCryptor\canEncrypt().
decrypt()
decrypt (?string $encryptedData)
{
Parameters
null | string $data
Returns
null|string
}
Implements ICryptor.
Definition at line 88 of file OpenSSLAsymmetricCryptor.php.
encrypt()
encrypt (?string $decryptedData)
{
Parameters
null | string $data
Returns
null|string
}
Implements ICryptor.
Definition at line 77 of file OpenSSLAsymmetricCryptor.php.
getPublicKey()
getPublicKey ()
{
Returns
mixed Return the currently used public key.
}
Implements AsymmetricCryptorInterface.
Definition at line 71 of file OpenSSLAsymmetricCryptor.php.
setPrivateKey()
setPrivateKey (mixed $privKey, ?string $password = null)
{
Parameters
mixed $privKey
null | string $password Maybe ignored depending on the implementation, i.e. the key may have to be unlocked or decrypted before passing it to the cryptor.
Returns
AsymmetricCryptorInterface $this
}
Implements AsymmetricCryptorInterface.
Definition at line 51 of file OpenSSLAsymmetricCryptor.php.
References OpenSSLAsymmetricCryptor\setPublicKey().
Referenced by OpenSSLAsymmetricCryptor\__construct().
setPublicKey()
setPublicKey (mixed $pubKey)
{
Parameters
mixed $pubKey
Returns
AsymmetricCryptorInterface $this
}
Implements AsymmetricCryptorInterface.
Definition at line 64 of file OpenSSLAsymmetricCryptor.php.
Referenced by OpenSSLAsymmetricCryptor\setPrivateKey().
sign() [1/2]
sign ($data)
{}
Definition at line 104 of file OpenSSLAsymmetricCryptor.php.
sign() [2/2]
sign (?string $data) inherited
Parameters
null | string $data
Returns
string
verify() [1/2]
verify ($data, string $signature)
{}
Definition at line 114 of file OpenSSLAsymmetricCryptor.php.
verify() [2/2]
verify (?string $data, string $signature) inherited
Parameters
null | string $data
string $signature
Returns
string
Field Documentation
$privKey
$privKey = null private
Definition at line 34 of file OpenSSLAsymmetricCryptor.php.
$pubKey
$pubKey = null private
Definition at line 36 of file OpenSSLAsymmetricCryptor.php.
SIGNING_ALGORITHM
const SIGNING_ALGORITHM = OPENSSL_ALGO_SHA512 private
Definition at line 32 of file OpenSSLAsymmetricCryptor.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Crypto/OpenSSLAsymmetricCryptor.php