CamerataDB: Composer Class Reference
Composer Class Reference
This is the mass-email composer class.
Public Member Functions
__construct (ConfigService $configService, RequestParameterService $parameterService, EventsService $eventsService, RecipientsFilter $recipientsFilter, EntityManager $entityManager, ProjectParticipantFieldsService $participantFieldsService, ProgressStatusService $progressStatusService, SimpleSharingService $simpleSharingService, OrganizationalRolesService $organizationRolesService, AppStorage $appStorage, UserStorage $userStorage,)
{}
getRecipientsFilter ()
The email composer never goes without its recipients filter.
discloseRecipients ()
Whether recipients are disclosed (send via Cc:) or undisclosed (send via Bcc:).
sendMessages ()
Send out the messages with self::doSendMessages(), after checking them with self::preComposeValidation().
validateFreeFormAddresses (string $header, string $freeForm)
Validate a comma separated list of email address from the Cc: or Bcc: input.
validateTemplate (string $template=null)
Validates the given template, i.e.
setDefaultTemplate ()
Install a default email text if no tempalte is given.
storeTemplate (string $templateName, ?string $subject=null, ?string $contents=null)
Take the text supplied by $contents and store it in the DB EmailTemplates table with tag $templateName.
deleteTemplate (string $templateName)
loadTemplate (string $templateIdentifier)
deleteDraft (?int $draftId=null)
Delete the given or current message draft.
saveAttachment (array &$fileRecord)
Handle file uploads.
formData ()
catchAllEmail ()
toStringArray ()
Compose one "readable", flat array of recipients, meant only for display.
toString ()
Compose one "readable", comma separated list of recipients, meant only for display.
storedEmails ()
Export an option array suitable to load stored email messages, currently templates and message drafts.
sentEmails ()
Return a list of previously sent emails related to the current project.
currentEmailTemplate ()
messageDraftId ()
inReplyTo ()
subjectTag ()
fromName ()
fromAddress ()
messageText ()
blindCarbonCopy ()
carbonCopy ()
subject ()
fileAttachments ()
Return the file attachment data.
fileAttachmentOptions ()
A helper function to generate suitable select options for PageNavigation::selectOptions().
eventAttachments ()
Return the calendar attachment data.
eventAttachmentOptions (mixed $projectId, array $attachedEvents)
A helper function to generate suitable select options for PageNavigation::selectOptions().
executionStatus ()
errorStatus ()
statusDiagnostics ()
Data Fields
const MSG_ID_AT = '_at_'
const POST_TAG = 'emailComposer'
const DIAGNOSTICS_STAGE = 'stage'
const DIAGNOSTICS_CAPTION = 'caption'
const DIAGNOSTICS_TOTAL_COUNT = 'TotalCount'
const DIAGNOSTICS_TOTAL_PAYLOAD = 'TotalPayload'
const DIAGNOSTICS_FAILED_COUNT = 'FailedCount'
const DIAGNOSTICS_FAILED_RECIPIENTS = 'FailedRecipients'
const DIAGNOSTICS_MAILER_EXCEPTIONS = 'MailerExceptions'
const DIAGNOSTICS_DUPLICATES = 'Duplicates'
const DIAGNOSTICS_COPY_TO_SENT = 'CopyToSent'
const DIAGNOSTICS_TEMPLATE_VALIDATION = 'TemplateValidation'
const DIAGNOSTICS_ADDRESS_VALIDATION = 'AddressValidation'
const DIAGNOSTICS_SUBJECT_VALIDATION = 'SubjectValidation'
const DIAGNOSTICS_FROM_VALIDATION = 'FromValidation'
const DIAGNOSTICS_ATTACHMENT_VALIDATION = 'AttachmentValidation'
const DIAGNOSTICS_MESSAGE = 'Message'
const DIAGNOSTICS_EXTERNAL_LINK_VALIDATION = 'ExternalLinkValidation'
const DIAGNOSTICS_SHARE_LINK_VALIDATION = 'ShareLinkValidation'
const DIAGNOSTICS_PRIVACY_NOTICE_VALIDATION = 'PrivacyNoticeValidation'
const DIAGNOSTICS_STAGE_PREVIEW = 'preview'
const DIAGNOSTICS_STAGE_SEND = 'send'
const DEFAULT_TEMPLATE_NAME = 'Default'
const DEFAULT_TEMPLATE
const GLOBAL_NAMESPACE = 'GLOBAL'
const MEMBER_NAMESPACE = 'MEMBER'
const MEMBER_VARIABLES
const EMAIL_PREVIEW_SELECTOR = '.ui-dialog.emailform #emailformdialog div#emailformwrapper form#cafevdb-email-form div#emailformdebug div#cafevdb-email-preview .email-body.reset-css'
const DEFAULT_HTML_STYLES
const PARTICIPANT_MONETARY_FIELDS_CSS_CLASS
Private Member Functions
cgiValue (string $key, $default=null)
Fetch a CGI-variable out of the form-select name-space.
hasSubstitutionNamespace (string $nameSpace, ?string $message=null)
Return true if this email needs per-namespace substitutions.
replaceFormVariables (string $nameSpace, mixed $data=null, ?string $message=null, ?array &$failures=null)
Replace all variables of the given namespace in $this->messageContents.
finalizeSubstitutions (?string $message=null)
Cleanup edge-cases.
head (string $text, int $lines=64, string $separators="/\n/")
Extract the first few line of a text-buffer.
getOutboundService (bool $authenticate=false)
Construct the PHPMailer instance.
addFileAttachment (PHPMailer $phpMailer, string $messageId, string $data, string $fileName, string $transferEncoding, string $mimeType,)
Add the given file attachment, replacing it by a download-link if too large.
recordMessageDiagnostics (string $mimeMsg)
Record diagnostic output from the actual message composition for the status page.
copyToSentFolder (string $mimeMessage)
Take the supplied message and copy it to the "Sent" folder.
preComposeValidation (array $recipients)
Pre-message construction validation.
setSubjectTag (?int $recipientsSet=null)
Compute the subject tag, depending on whether we are in project mode or not.
setCatchAll ()
Set the catch-all email address.
dateSubstitution (array $arg, string $nameSpace, mixed $data=null)
Generic data substitution function which is used to substitute data-variables during mail-merge.
streetAddress ()
bankAccount ()
fetchExecutiveBoard ()
Fetch the pre-names of the members of the organizing committee in order to construct an up-to-date greeting.
normalizeTemplateName (string $templateName)
Normalize the given template-name: CamelCase, not spaces, no dashes.
fetchTemplatesList ()
fetchDraftsList ()
fetchSentEmailsList ()
detachTemporaryFiles (int $draftId)
Detach temporaries from a draft, i.e.
rememberTemporaryFile (string $tmpFile, mixed $origin)
Remember a temporary file.
forgetTemporaryFile (string $tmpFile)
Forget a temporary file, i.e.
blankTemplateAttachments ()
Return non-personalized document templates for use in mass-email.
activePersonalAttachments ()
formatExceptionMessage (\Throwable $throwable)
Compose a "readable" message from a thrown exception.
Static Private Member Functions
static emitHtmlBodyStyle (string $style, ?string $cssPrefix=null)
static outBoxSubFolderFromMessageId (string $messageId)
Generate a directory name for the stripped attachments in the cloud file space.
static messageIdFromOutBoxSubFolder (string $outBoxSubFolderPath)
Reconstruct the message id from the given outbox folder name.
Private Attributes
const PROGRESS_CHUNK_SIZE = 4096
const PROGRESS_THROTTLE_SECONDS = 2
const PERSONAL_ATTACHMENT_PARENTS_STRIP = 5
const ATTACHMENT_PREVIEW_CACHE_TTL = 4 * 60 * 60
const HEADER_TAG = 'X-CAFEVDB'
const HEADER_MARKER = [ self::HEADER_TAG => 'YES', ]
const HEADER_MARKER_RECIPIENT = [ self::HEADER_TAG . '-' . 'DESTINATION' => 'Recipient', ]
const HEADER_MARKER_SENT = [ self::HEADER_TAG . '-' . 'DESTINATION' => 'Self', ]
const DO_NOT_REPLY_SENDER = 'do-not-reply'
$recipients
The list of recipients.
$onLookers
Cc: and Bcc: recipients.
$cgiData
$submitted
$projectId
$projectName
$project
$bulkTransaction
$bulkTransactionId
$paymentSign = 1.0
$constructionMode
$catchAllEmail
The fixed From: email address.
$catchAllName
The default From: name.
$initialTemplate
$templateName
$inReplyToId
Message id of a to-be-replied message.
$referencing
Further related message ids.
$draftId
The ID of the current message draft, or -1.
$messageTag
$messageContents
$executionStatus
$diagnostics
$parameterService
$recipientsFilter
$eventsService
$participantFieldsService
$progressStatusService
$simpleSharingService
$organizationalRolesService
$appStorage
$userStorage
$progressToken
$substitutions
$templateFileAttachments = null
Template file-attachment without personalization, i.e.
$personalFileAttachments = null
Personal file-attachments stemming form ProjectParticipantField entities.
$globalFileAttachments = null
"Global" file attachments from upload or the cloud file-system.
$implicitFileAttachments = null
Potential personal file-attachments deduced from parsing the personal substitutions.
Detailed Description
This is the mass-email composer class.
We try to be somewhat careful to have useful error reporting, and avoid sending garbled messages or duplicates.
Bug:
This is a mixture between a controller and service class and needs to be cleaned up.
Definition at line 83 of file Composer.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, RequestParameterService $parameterService, EventsService $eventsService, RecipientsFilter $recipientsFilter, EntityManager $entityManager, ProjectParticipantFieldsService $participantFieldsService, ProgressStatusService $progressStatusService, SimpleSharingService $simpleSharingService, OrganizationalRolesService $organizationRolesService, AppStorage $appStorage, UserStorage $userStorage)
{}
Definition at line 488 of file Composer.php.
References Composer\setCatchAll().
Member Function Documentation
activePersonalAttachments()
activePersonalAttachments () private
Returns
int The number of currently selected personal attachments.
Definition at line 5325 of file Composer.php.
addFileAttachment()
addFileAttachment (PHPMailer $phpMailer, string $messageId, string $data, string $fileName, string $transferEncoding, string $mimeType) private
Add the given file attachment, replacing it by a download-link if too large.
Parameters
PHPMailer $phpMailer
string $messageId The message id is used to construct the folder on the server where stripped attachments can be downlaoded from.
string $data The data to be attached.
string $fileName The file-name to be presented to the recipient.
string $transferEncoding
string $mimeType
Returns
void
Definition at line 2371 of file Composer.php.
bankAccount()
bankAccount () private
Returns
string The formatted bank account of the orchestra.
Definition at line 4095 of file Composer.php.
blankTemplateAttachments()
blankTemplateAttachments () private
Return non-personalized document templates for use in mass-email.
Rationale: personalizing templates takes too much time for mass-email. Also, attaching personalized attachments means that each recipients has to be addressed by its own private email. So for mass-email we just want the unfilled PDF forms.
Returns
array
Definition at line 5133 of file Composer.php.
blindCarbonCopy()
blindCarbonCopy ()
Returns
string Export BCC.
Definition at line 4992 of file Composer.php.
carbonCopy()
carbonCopy ()
Returns
string Export CC.
Definition at line 4998 of file Composer.php.
catchAllEmail()
catchAllEmail ()
Returns
string The current catch-all email.
Definition at line 4882 of file Composer.php.
cgiValue()
cgiValue (string $key, $default = null) private
Fetch a CGI-variable out of the form-select name-space.
Parameters
string $key The key to query.
null | mixed $default
Returns
mixed
Definition at line 686 of file Composer.php.
copyToSentFolder()
copyToSentFolder (string $mimeMessage) private
Take the supplied message and copy it to the "Sent" folder.
Parameters
string $mimeMessage The raw undecoded mime message.
Returns
bool Execution status.
Definition at line 2908 of file Composer.php.
currentEmailTemplate()
currentEmailTemplate ()
Returns
string The currently selected template name.
Definition at line 4948 of file Composer.php.
dateSubstitution()
dateSubstitution (array $arg, string $nameSpace, mixed $data = null) private
Generic data substitution function which is used to substitute data-variables during mail-merge.
Parameters
array $arg Arguments taken from the message template.
string $nameSpace Namespace of the substitution, i.e. GLOBAL or MEMBER.
mixed $data Further generic $data for forwarding the substitued date string to other substitution handlers.
Returns
string
Definition at line 3884 of file Composer.php.
deleteDraft()
deleteDraft (?int $draftId = null)
Delete the given or current message draft.
Parameters
null | int $draftId
Returns
bool
Definition at line 4544 of file Composer.php.
deleteTemplate()
deleteTemplate (string $templateName)
Parameters
string $templateName Delete the named email template.
Returns
void
Definition at line 4245 of file Composer.php.
detachTemporaryFiles()
detachTemporaryFiles (int $draftId) private
Detach temporaries from a draft, i.e.
after deleting the draft.
Parameters
int $draftId
Returns
bool
Definition at line 4667 of file Composer.php.
discloseRecipients()
discloseRecipients ()
Whether recipients are disclosed (send via Cc:) or undisclosed (send via Bcc:).
If not in project mode recipients are never disclosed, unless there is only a single recipient, which is then addressed via To.
Returns
bool
Definition at line 1652 of file Composer.php.
emitHtmlBodyStyle()
static emitHtmlBodyStyle (string $style, ?string $cssPrefix = null) static private
Parameters
string $style A style template.
null | string $cssPrefix A prefix to substitute into $style.
Returns
string
Definition at line 1698 of file Composer.php.
errorStatus()
errorStatus ()
Returns
bool The negated dispatch status.
Definition at line 5533 of file Composer.php.
eventAttachmentOptions()
eventAttachmentOptions (mixed $projectId, array $attachedEvents)
A helper function to generate suitable select options for PageNavigation::selectOptions().
Parameters
mixed $projectId Id of the active project. If <= 0 an empty array is returned.
array $attachedEvents Flat array of attached events.
Returns
array
Definition at line 5492 of file Composer.php.
eventAttachments()
eventAttachments ()
Return the calendar attachment data.
Returns
array
[ URI => CAL_ID, ... ]
Definition at line 5468 of file Composer.php.
executionStatus()
executionStatus ()
Returns
bool The dispatch status
Definition at line 5527 of file Composer.php.
fetchDraftsList()
fetchDraftsList () private
Returns
An associative matrix with all currently stored draft messages. In order to load the draft we only need the id. The list of drafts is used to generate a select menu where some fancy title is displayed and the option value is the unique draft id.
Definition at line 4390 of file Composer.php.
fetchExecutiveBoard()
fetchExecutiveBoard () private
Fetch the pre-names of the members of the organizing committee in order to construct an up-to-date greeting.
Returns
string
Definition at line 4113 of file Composer.php.
fetchSentEmailsList()
fetchSentEmailsList () private
Returns
array|Collection The array or collection of sent-email related to the current project, or all sent-email which have been sent without project context.
Definition at line 4399 of file Composer.php.
fetchTemplatesList()
fetchTemplatesList () private
Returns
array A flat array with all known template names.
Definition at line 4379 of file Composer.php.
fileAttachmentOptions()
fileAttachmentOptions ()
A helper function to generate suitable select options for PageNavigation::selectOptions().
Returns
array
Definition at line 5402 of file Composer.php.
fileAttachments()
fileAttachments ()
Return the file attachment data.
Returns
array
[
  [
    'value' => 'tmp_name',
    'status' => STATUS,
    'tmp_name' => NAME_AS_STORED_ON_THE_SERVER,
    'name' => NAME,
    ...
  ],
    ...
]
Definition at line 5355 of file Composer.php.
finalizeSubstitutions()
finalizeSubstitutions (?string $message = null) private
Cleanup edge-cases.
ATM this only replaces left-over '$$' occurences with a single $.
Parameters
null | string $message Email mesasge body.
Returns
string
Definition at line 1636 of file Composer.php.
forgetTemporaryFile()
forgetTemporaryFile (string $tmpFile) private
Forget a temporary file, i.e.
purge it from the data-base.
Parameters
string $tmpFile The name of the temporary file.
Returns
bool The execution status.
Definition at line 4735 of file Composer.php.
formatExceptionMessage()
formatExceptionMessage (\Throwable $throwable) private
Compose a "readable" message from a thrown exception.
Parameters
\\Throwable $throwable The caught exception.
Returns
string
Definition at line 5551 of file Composer.php.
formData()
formData ()
Returns
array General form data for hidden input elements.
Definition at line 4871 of file Composer.php.
fromAddress()
fromAddress ()
Returns
string The current From: addres. This is fixed and cannot be changed.
Definition at line 4980 of file Composer.php.
fromName()
fromName ()
Returns
string The From: name. This is modifiable. The From: email address, however, is fixed in order to prevent abuse.
Definition at line 4974 of file Composer.php.
getOutboundService()
getOutboundService (bool $authenticate = false) private
Construct the PHPMailer instance.
Parameters
bool $authenticate If true install the SMTP authentication. If false the mailer will probably not be able to send messages (safe-guard).
Returns
PHPMailer
Definition at line 2292 of file Composer.php.
getRecipientsFilter()
getRecipientsFilter ()
The email composer never goes without its recipients filter.
Returns
RecipientsFilter
Definition at line 672 of file Composer.php.
hasSubstitutionNamespace()
hasSubstitutionNamespace (string $nameSpace, ?string $message = null) private
Return true if this email needs per-namespace substitutions.
Substitutions have the form
${NAMESPACE::VARIABLE}
For example ${MEMBER::FIRST_NAME}.
Parameters
string $nameSpace The name space of the variable.
null | string $message The composed email message body.
Returns
bool|int
Definition at line 1550 of file Composer.php.
head()
head (string $text, int $lines = 64, string $separators = "/\n/") private
Extract the first few line of a text-buffer.
Parameters
string $text The text to compute the "head" of.
int $lines The number of lines to return at most.
string $separators Regexp for preg_split. The default is just "/\\\\n/". Note that this is enough for \\n and \\r\\n as the text is afterwars imploded again with \n separator.
Returns
string
Definition at line 1887 of file Composer.php.
inReplyTo()
inReplyTo ()
Returns
null|string The currently replied-to message id
Definition at line 4960 of file Composer.php.
loadTemplate()
loadTemplate (string $templateIdentifier)
Parameters
string $templateIdentifier Load the given template.
Returns
bool The execution status.
Definition at line 4260 of file Composer.php.
messageDraftId()
messageDraftId ()
Returns
null|int The currently selected draft id.
Definition at line 4954 of file Composer.php.
messageIdFromOutBoxSubFolder()
static messageIdFromOutBoxSubFolder (string $outBoxSubFolderPath) static private
Reconstruct the message id from the given outbox folder name.
Parameters
string $outBoxSubFolderPath
Returns
string
Definition at line 2346 of file Composer.php.
messageText()
messageText ()
Returns
string In principle the most important stuff: the message text.
Definition at line 4986 of file Composer.php.
normalizeTemplateName()
normalizeTemplateName (string $templateName) private
Normalize the given template-name: CamelCase, not spaces, no dashes.
Parameters
string $templateName The name of the template.
Returns
array<int, string> First element is the normalized version, second element a translation of the normalized version, if it differs from the non-translated version.
Definition at line 4287 of file Composer.php.
outBoxSubFolderFromMessageId()
static outBoxSubFolderFromMessageId (string $messageId) static private
Generate a directory name for the stripped attachments in the cloud file space.
Parameters
string $messageId The message id of the email.
Returns
string
Definition at line 2334 of file Composer.php.
preComposeValidation()
preComposeValidation (array $recipients) private
Pre-message construction validation.
Collect all data and perform some checks on it. As a side-effect $this->executionStatus is set.
Parameters
null | array $recipients The set of recipients to check.
Cc, valid email addresses
Bcc, valid email addresses
subject, must not be empty
message-text, variable substitutions
sender name, must not be empty
file attachments, temporary local copy must exist
events, must exist
Returns
bool The result of the validation.
Definition at line 3530 of file Composer.php.
recordMessageDiagnostics()
recordMessageDiagnostics (string $mimeMsg) private
Record diagnostic output from the actual message composition for the status page.
Parameters
string $mimeMsg The undecoded sent mime-message.
Returns
void
Definition at line 2867 of file Composer.php.
rememberTemporaryFile()
rememberTemporaryFile (string $tmpFile, mixed $origin) private
Remember a temporary file.
Files attached to message drafts are remembered across sessions, temporaries not attached to message drafts are cleaned at logout and when closing the email form.
Parameters
string $tmpFile The name for the temporary file.
string | AttachmentOrigin $origin The attachment origin.
Returns
bool The execution status.
Definition at line 4699 of file Composer.php.
replaceFormVariables()
replaceFormVariables (string $nameSpace, mixed $data = null, ?string $message = null, ?array & $failures = null) private
Replace all variables of the given namespace in $this->messageContents.
Parameters
string $nameSpace The variable prefix, e.g. MEMBER or one of its translations.
mixed $data Context dependent data, likely Entities\Musician.
null | string $message
null | array $failures Optional failure array. If null then the method will throw an exception on errror.
Returns
string Substituted message
Exceptions
Exceptions
\SubstitutionException
Definition at line 1576 of file Composer.php.
saveAttachment()
saveAttachment (array & $fileRecord)
Handle file uploads.
In order for upload to survive we have to move them to an alternate location. And clean up afterwards, of course. We store the generated temporaries in the user config-space in order to (latest) remove them on logout/login.
Parameters
array $fileRecord Typically $_FILES['fileAttach'], but maybe any file record.
Returns
bool|array Copy of $fileRecord with changed temporary file which survives script-reload, or false on error.
Definition at line 4765 of file Composer.php.
sendMessages()
sendMessages ()
Send out the messages with self::doSendMessages(), after checking them with self::preComposeValidation().
If successful a possibly pending "draft" message is deleted.
Returns
bool Success (true) or failure (false).
Definition at line 1670 of file Composer.php.
sentEmails()
sentEmails ()
Return a list of previously sent emails related to the current project.
Returns
array|Collection
Definition at line 4942 of file Composer.php.
Referenced by EmailFormController\sentEmailOptions().
setCatchAll()
setCatchAll () private
Set the catch-all email address.
If in "construction mode" then emails are only send to the configured 'emailtestaddress' in the app config-space.
Returns
void
Definition at line 3856 of file Composer.php.
Referenced by Composer\__construct().
setDefaultTemplate()
setDefaultTemplate ()
Install a default email text if no tempalte is given.
Returns
void
Definition at line 3832 of file Composer.php.
setSubjectTag()
setSubjectTag (?int $recipientsSet = null) private
Compute the subject tag, depending on whether we are in project mode or not.
Parameters
null | int $recipientsSet If set assume the given recipients set.
Returns
void
See also
RecipientsFilter::getUserBase()
Definition at line 3669 of file Composer.php.
statusDiagnostics()
statusDiagnostics ()
Returns
array Possible diagnostics or not. Depending on operation.
Definition at line 5539 of file Composer.php.
storedEmails()
storedEmails ()
Export an option array suitable to load stored email messages, currently templates and message drafts.
Returns
array
Definition at line 4926 of file Composer.php.
Referenced by EmailFormController\storedEmailOptions().
storeTemplate()
storeTemplate (string $templateName, ?string $subject = null, ?string $contents = null)
Take the text supplied by $contents and store it in the DB EmailTemplates table with tag $templateName.
An existing template with the same tag will be replaced.
Parameters
string $templateName The name of the template.
null | string $subject Subject, if null then subject().
null | string $contents Message body, if null then messageText().
Returns
void
Definition at line 4218 of file Composer.php.
streetAddress()
streetAddress () private
Returns
string The formatted street-address of the orchester.
Definition at line 4083 of file Composer.php.
subject()
subject ()
Returns
string Export Subject.
Definition at line 5004 of file Composer.php.
subjectTag()
subjectTag ()
Returns
string The subject tag depending on whether we ar in "project-mode" or not.
Definition at line 4966 of file Composer.php.
toString()
toString ()
Compose one "readable", comma separated list of recipients, meant only for display.
The real recipients list is composed somewhere else.
Returns
string
Definition at line 4915 of file Composer.php.
toStringArray()
toStringArray ()
Compose one "readable", flat array of recipients, meant only for display.
The real recipients list is composed somewhere else.
Returns
array
Definition at line 4894 of file Composer.php.
validateFreeFormAddresses()
validateFreeFormAddresses (string $header, string $freeForm)
Validate a comma separated list of email address from the Cc: or Bcc: input.
Parameters
string $header For error diagnostics, either CC or BCC.
string $freeForm the value from the input field.
Returns
bool|array \false in case of error, otherwise a borken down list of recipients [ [ 'name' => '"Doe, John"', 'email' => 'john@.nosp@m.doe..nosp@m.org', ], ... ]
Definition at line 3705 of file Composer.php.
validateTemplate()
validateTemplate (string $template = null)
Validates the given template, i.e.
searches for unknown substitutions. This function is invoked right before sending stuff out and before storing drafts. In order to do so we substitute each known variable by a dummy value and then make sure that no variable tag ${...} remains.
Parameters
null | string $template A message body template, i.e. the message body with potential ${SUBSTITION} things.
Returns
bool Execution status.
Definition at line 3767 of file Composer.php.
Field Documentation
$appStorage
AppStorage $appStorage private
Definition at line 446 of file Composer.php.
$bulkTransaction
Entities SepaBulkTransaction $bulkTransaction private
Definition at line 395 of file Composer.php.
$bulkTransactionId
int $bulkTransactionId private
Definition at line 398 of file Composer.php.
$catchAllEmail
$catchAllEmail private
The fixed From: email address.
Definition at line 406 of file Composer.php.
$catchAllName
$catchAllName private
The default From: name.
Definition at line 407 of file Composer.php.
$cgiData
array $cgiData private
Definition at line 380 of file Composer.php.
$constructionMode
bool $constructionMode private
Definition at line 404 of file Composer.php.
$diagnostics
$diagnostics private
Definition at line 422 of file Composer.php.
$draftId
$draftId private
The ID of the current message draft, or -1.
Definition at line 415 of file Composer.php.
$eventsService
EventsService $eventsService private
Definition at line 431 of file Composer.php.
$executionStatus
$executionStatus private
Definition at line 421 of file Composer.php.
$globalFileAttachments
array $globalFileAttachments = null private
"Global" file attachments from upload or the cloud file-system.
Definition at line 477 of file Composer.php.
$implicitFileAttachments
array $implicitFileAttachments = null private
Potential personal file-attachments deduced from parsing the personal substitutions.
Definition at line 485 of file Composer.php.
$initialTemplate
$initialTemplate private
Definition at line 409 of file Composer.php.
$inReplyToId
$inReplyToId private
Message id of a to-be-replied message.
Definition at line 412 of file Composer.php.
$messageContents
$messageContents private
Definition at line 419 of file Composer.php.
$messageTag
$messageTag private
Definition at line 417 of file Composer.php.
$onLookers
$onLookers private
Cc: and Bcc: recipients.
Definition at line 377 of file Composer.php.
$organizationalRolesService
OrganizationalRolesService $organizationalRolesService private
Definition at line 443 of file Composer.php.
$parameterService
RequestParameterService $parameterService private
Definition at line 425 of file Composer.php.
$participantFieldsService
ProjectParticipantFieldsService $participantFieldsService private
Definition at line 434 of file Composer.php.
$paymentSign
float $paymentSign = 1.0 private
Definition at line 401 of file Composer.php.
$personalFileAttachments
array $personalFileAttachments = null private
Personal file-attachments stemming form ProjectParticipantField entities.
Definition at line 470 of file Composer.php.
$progressStatusService
ProgressStatusService $progressStatusService private
Definition at line 437 of file Composer.php.
$progressToken
int $progressToken private
Definition at line 452 of file Composer.php.
$project
Entities Project $project private
Definition at line 392 of file Composer.php.
$projectId
int $projectId private
Definition at line 386 of file Composer.php.
$projectName
string $projectName private
Definition at line 389 of file Composer.php.
$recipients
$recipients private
The list of recipients.
Definition at line 376 of file Composer.php.
$recipientsFilter
RecipientsFilter $recipientsFilter private
Definition at line 428 of file Composer.php.
$referencing
$referencing private
Further related message ids.
Definition at line 413 of file Composer.php.
$simpleSharingService
SimpleSharingService $simpleSharingService private
Definition at line 440 of file Composer.php.
$submitted
bool $submitted private
Definition at line 383 of file Composer.php.
$substitutions
array $substitutions private
Definition at line 455 of file Composer.php.
$templateFileAttachments
array $templateFileAttachments = null private
Template file-attachment without personalization, i.e.
blank PDF forms.
Definition at line 462 of file Composer.php.
$templateName
$templateName private
Definition at line 410 of file Composer.php.
$userStorage
UserStorage $userStorage private
Definition at line 449 of file Composer.php.
ATTACHMENT_PREVIEW_CACHE_TTL
const ATTACHMENT_PREVIEW_CACHE_TTL = 4 * 60 * 60 private
Definition at line 98 of file Composer.php.
DEFAULT_HTML_STYLES
const DEFAULT_HTML_STYLES
Definition at line 261 of file Composer.php.
DEFAULT_TEMPLATE
const DEFAULT_TEMPLATE
Initial value:
= 'Liebe Musiker,
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
<p>
Mit den besten Gren,
<p>
Euer Camerata Vorstand (${GLOBAL::ORGANIZER})
<p>
P.s.:
Sie erhalten diese Email, weil Sie schon einmal mit dem Orchester
Camerata Academica Freiburg musiziert haben. Wenn wir Sie aus unserer Datenbank
lschen sollen, teilen Sie uns das bitte kurz mit, indem Sie entsprechend
auf diese Email antworten. Wir entschuldigen uns in diesem Fall fr die
Strung.'
Definition at line 146 of file Composer.php.
DEFAULT_TEMPLATE_NAME
const DEFAULT_TEMPLATE_NAME = 'Default'
Definition at line 144 of file Composer.php.
DIAGNOSTICS_ADDRESS_VALIDATION
const DIAGNOSTICS_ADDRESS_VALIDATION = 'AddressValidation'
Definition at line 116 of file Composer.php.
DIAGNOSTICS_ATTACHMENT_VALIDATION
const DIAGNOSTICS_ATTACHMENT_VALIDATION = 'AttachmentValidation'
Definition at line 119 of file Composer.php.
DIAGNOSTICS_CAPTION
const DIAGNOSTICS_CAPTION = 'caption'
Definition at line 107 of file Composer.php.
DIAGNOSTICS_COPY_TO_SENT
const DIAGNOSTICS_COPY_TO_SENT = 'CopyToSent'
Definition at line 114 of file Composer.php.
DIAGNOSTICS_DUPLICATES
const DIAGNOSTICS_DUPLICATES = 'Duplicates'
Definition at line 113 of file Composer.php.
DIAGNOSTICS_EXTERNAL_LINK_VALIDATION
const DIAGNOSTICS_EXTERNAL_LINK_VALIDATION = 'ExternalLinkValidation'
Definition at line 121 of file Composer.php.
DIAGNOSTICS_FAILED_COUNT
const DIAGNOSTICS_FAILED_COUNT = 'FailedCount'
Definition at line 110 of file Composer.php.
DIAGNOSTICS_FAILED_RECIPIENTS
const DIAGNOSTICS_FAILED_RECIPIENTS = 'FailedRecipients'
Definition at line 111 of file Composer.php.
DIAGNOSTICS_FROM_VALIDATION
const DIAGNOSTICS_FROM_VALIDATION = 'FromValidation'
Definition at line 118 of file Composer.php.
DIAGNOSTICS_MAILER_EXCEPTIONS
const DIAGNOSTICS_MAILER_EXCEPTIONS = 'MailerExceptions'
Definition at line 112 of file Composer.php.
DIAGNOSTICS_MESSAGE
const DIAGNOSTICS_MESSAGE = 'Message'
Definition at line 120 of file Composer.php.
DIAGNOSTICS_PRIVACY_NOTICE_VALIDATION
const DIAGNOSTICS_PRIVACY_NOTICE_VALIDATION = 'PrivacyNoticeValidation'
Definition at line 123 of file Composer.php.
DIAGNOSTICS_SHARE_LINK_VALIDATION
const DIAGNOSTICS_SHARE_LINK_VALIDATION = 'ShareLinkValidation'
Definition at line 122 of file Composer.php.
DIAGNOSTICS_STAGE
const DIAGNOSTICS_STAGE = 'stage'
Definition at line 106 of file Composer.php.
DIAGNOSTICS_STAGE_PREVIEW
const DIAGNOSTICS_STAGE_PREVIEW = 'preview'
Definition at line 125 of file Composer.php.
DIAGNOSTICS_STAGE_SEND
const DIAGNOSTICS_STAGE_SEND = 'send'
Definition at line 126 of file Composer.php.
DIAGNOSTICS_SUBJECT_VALIDATION
const DIAGNOSTICS_SUBJECT_VALIDATION = 'SubjectValidation'
Definition at line 117 of file Composer.php.
DIAGNOSTICS_TEMPLATE_VALIDATION
const DIAGNOSTICS_TEMPLATE_VALIDATION = 'TemplateValidation'
Definition at line 115 of file Composer.php.
DIAGNOSTICS_TOTAL_COUNT
const DIAGNOSTICS_TOTAL_COUNT = 'TotalCount'
Definition at line 108 of file Composer.php.
DIAGNOSTICS_TOTAL_PAYLOAD
const DIAGNOSTICS_TOTAL_PAYLOAD = 'TotalPayload'
Definition at line 109 of file Composer.php.
DO_NOT_REPLY_SENDER
const DO_NOT_REPLY_SENDER = 'do-not-reply' private
Definition at line 104 of file Composer.php.
EMAIL_PREVIEW_SELECTOR
const EMAIL_PREVIEW_SELECTOR = '.ui-dialog.emailform #emailformdialog div#emailformwrapper form#cafevdb-email-form div#emailformdebug div#cafevdb-email-preview .email-body.reset-css'
Definition at line 260 of file Composer.php.
GLOBAL_NAMESPACE
const GLOBAL_NAMESPACE = 'GLOBAL'
Definition at line 161 of file Composer.php.
HEADER_MARKER
const HEADER_MARKER = [ self::HEADER_TAG => 'YES', ] private
Definition at line 101 of file Composer.php.
HEADER_MARKER_RECIPIENT
const HEADER_MARKER_RECIPIENT = [ self::HEADER_TAG . '-' . 'DESTINATION' => 'Recipient', ] private
Definition at line 102 of file Composer.php.
HEADER_MARKER_SENT
const HEADER_MARKER_SENT = [ self::HEADER_TAG . '-' . 'DESTINATION' => 'Self', ] private
Definition at line 103 of file Composer.php.
HEADER_TAG
const HEADER_TAG = 'X-CAFEVDB' private
Definition at line 100 of file Composer.php.
MEMBER_NAMESPACE
const MEMBER_NAMESPACE = 'MEMBER'
Definition at line 162 of file Composer.php.
MEMBER_VARIABLES
const MEMBER_VARIABLES
Definition at line 163 of file Composer.php.
MSG_ID_AT
const MSG_ID_AT = '_at_'
Definition at line 90 of file Composer.php.
PARTICIPANT_MONETARY_FIELDS_CSS_CLASS
const PARTICIPANT_MONETARY_FIELDS_CSS_CLASS
Initial value:
= [
    'header' => 'monetary-fields',
    'fieldHeader' => 'field-header',
    'row' => 'field-option',
    'footer' => 'footer totalsum',
  ]
Definition at line 369 of file Composer.php.
PERSONAL_ATTACHMENT_PARENTS_STRIP
const PERSONAL_ATTACHMENT_PARENTS_STRIP = 5 private
Definition at line 97 of file Composer.php.
POST_TAG
const POST_TAG = 'emailComposer'
Definition at line 95 of file Composer.php.
PROGRESS_CHUNK_SIZE
const PROGRESS_CHUNK_SIZE = 4096 private
Definition at line 92 of file Composer.php.
PROGRESS_THROTTLE_SECONDS
const PROGRESS_THROTTLE_SECONDS = 2 private
Definition at line 93 of file Composer.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/EmailForm/Composer.php