CamerataDB: GoogleMailSanitizer Class Reference
GoogleMailSanitizer Class Reference
See that we always have both, some@.nosp@m.gmai.nosp@m.l.com as well as some@.nosp@m.goog.nosp@m.lemai.nosp@m.l.co.nosp@m.m.
Public Member Functions
__construct (EntityManager $entityManager, ILogger $logger=null,)
{
Parameters
EntityManager $entityManager The entity-manger for the entire mess.
ILogger $logger A cloud logger instance.
}
setEntity (mixed $entity)
{{
Parameters
mixed $entity Set the entity to be validated.
Returns
void
}}
validate ()
{{
Returns
bool Return \true if the entity is ok to the judgement of this sanitizer, \false otherwise. Of course, the entity may fail the validations carried out by other sanitizers ...
}Default implementation which reports validation failure such that the calling code always executes the sanitizer.}
sanitizePersist (bool $flush=false)
{{Call sanitize(SANITIZE_PERSIST, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}}
getEntity (mixed $entity)
{
Parameters
mixed $entity
Returns
mixed Get the entity to be validated.
}
getValidationMessages ()
{
Returns
array Validation messages, indexed by verbosity level.
}
sanitizeRemove (bool $flush=false)
{Call sanitize(SANITIZE_REMOVE, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
sanitizeUpdate (bool $flush=false)
{Call sanitize(SANITIZE_UPDATE, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
sanitize (string $lifeCycle, bool $flush=false)
{
Parameters
string $lifeCycle Either of SANITIZE_PERSIST, SANITIZE_UPDATE or SANITIZE_REMOVE. The sanitizer implementation need not implement all sanitizers.
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
Static Public Member Functions
static getDescription ()
{
Returns
string Short description of the sanitizer.
}
static getEntityClass ()
{
Returns
string The full class name of the entity the sanitizer is dedicated to.
}
static getName ()
{
Returns
string Name of the sanitizer.
}
Data Fields
const NAME = 'googlemail-gmail'
const GOOGLEMAIL_DOMAIN = '@googlemail.com'
const GMAIL_DOMAIN = '@gmail.com'
const VERBOSITY_QUIET = OutputInterface::VERBOSITY_QUIET
const VERBOSITY_NORMAL = OutputInterface::VERBOSITY_NORMAL
const VERBOSITY_VERBOSE = OutputInterface::VERBOSITY_VERBOSE
const VERBOSITY_VERY_VERBOSE = OutputInterface::VERBOSITY_VERY_VERBOSE
const VERBOSITY_DEBUG = OutputInterface::VERBOSITY_DEBUG
Protected Member Functions
addMessage (string $message, int $level=self::VERBOSITY_NORMAL)
resetMessages ()
Protected Attributes
$validated = null
$entity
$messages = []
Private Member Functions
otherAddress ()
Detailed Description
See that we always have both, some@.nosp@m.gmai.nosp@m.l.com as well as some@.nosp@m.goog.nosp@m.lemai.nosp@m.l.co.nosp@m.m.
Definition at line 37 of file GoogleMailSanitizer.php.
Constructor & Destructor Documentation
__construct()
__construct (EntityManager $entityManager, ILogger $logger = null)
{
Parameters
EntityManager $entityManager The entity-manger for the entire mess.
ILogger $logger A cloud logger instance.
}
Reimplemented from AbstractSanitizer.
Definition at line 51 of file GoogleMailSanitizer.php.
Member Function Documentation
addMessage()
addMessage (string $message, int $level = self::VERBOSITY_NORMAL) protected inherited
Parameters
string $message The message to remember.
int $level One of the verbosity levels.
Returns
void
Definition at line 97 of file AbstractSanitizer.php.
Referenced by GoogleMailSanitizer\validate().
getDescription()
static getDescription () static
{
Returns
string Short description of the sanitizer.
}
Implements ISanitizer.
Definition at line 62 of file GoogleMailSanitizer.php.
getEntity()
getEntity (mixed $entity) inherited
{
Parameters
mixed $entity
Returns
mixed Get the entity to be validated.
}
Implements ISanitizer.
Definition at line 73 of file AbstractSanitizer.php.
getEntityClass()
static getEntityClass () static
{
Returns
string The full class name of the entity the sanitizer is dedicated to.
}
Implements ISanitizer.
Definition at line 68 of file GoogleMailSanitizer.php.
getName()
static getName () static inherited
{
Returns
string Name of the sanitizer.
}
Implements ISanitizer.
Definition at line 79 of file AbstractSanitizer.php.
getValidationMessages()
getValidationMessages () inherited
{
Returns
array Validation messages, indexed by verbosity level.
}
Implements ISanitizer.
Definition at line 85 of file AbstractSanitizer.php.
otherAddress()
otherAddress () private
Returns
null|string Return the respective alternate Google mail address.
Definition at line 83 of file GoogleMailSanitizer.php.
Referenced by GoogleMailSanitizer\sanitizePersist(), and GoogleMailSanitizer\validate().
resetMessages()
resetMessages () protected inherited
Returns
void
Definition at line 121 of file AbstractSanitizer.php.
sanitize()
sanitize (string $lifeCycle, bool $flush = false) inherited
{
Parameters
string $lifeCycle Either of SANITIZE_PERSIST, SANITIZE_UPDATE or SANITIZE_REMOVE. The sanitizer implementation need not implement all sanitizers.
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
Implements ISanitizer.
Definition at line 170 of file AbstractSanitizer.php.
sanitizePersist()
sanitizePersist (bool $flush = false)
{{Call sanitize(SANITIZE_PERSIST, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}}
Reimplemented from AbstractSanitizer.
Definition at line 135 of file GoogleMailSanitizer.php.
References GoogleMailSanitizer\otherAddress(), and GoogleMailSanitizer\validate().
sanitizeRemove()
sanitizeRemove (bool $flush = false) inherited
{Call sanitize(SANITIZE_REMOVE, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
Implements ISanitizer.
Definition at line 138 of file AbstractSanitizer.php.
sanitizeUpdate()
sanitizeUpdate (bool $flush = false) inherited
{Call sanitize(SANITIZE_UPDATE, $flush).
Parameters
bool $flush Whether to call flush after sanitizing.
Returns
void
Exceptions
Exceptions
\SanitizerException}
Implements ISanitizer.
Definition at line 156 of file AbstractSanitizer.php.
References AbstractSanitizer\sanitizePersist().
setEntity()
setEntity (mixed $entity)
{{
Parameters
mixed $entity Set the entity to be validated.
Returns
void
}}
Reimplemented from AbstractSanitizer.
Definition at line 74 of file GoogleMailSanitizer.php.
validate()
validate ()
{{
Returns
bool Return \true if the entity is ok to the judgement of this sanitizer, \false otherwise. Of course, the entity may fail the validations carried out by other sanitizers ...
}Default implementation which reports validation failure such that the calling code always executes the sanitizer.}
Returns
bool Return \false if either of the other Google email addresses is missing if the other one is present.
Reimplemented from AbstractSanitizer.
Definition at line 101 of file GoogleMailSanitizer.php.
References AbstractSanitizer\addMessage(), and GoogleMailSanitizer\otherAddress().
Referenced by GoogleMailSanitizer\sanitizePersist().
Field Documentation
$entity
Entities MusicianEmailAddress $entity protected
Definition at line 48 of file GoogleMailSanitizer.php.
$messages
array $messages = [] protected inherited
Definition at line 50 of file AbstractSanitizer.php.
$validated
bool $validated = null protected
Definition at line 45 of file GoogleMailSanitizer.php.
GMAIL_DOMAIN
const GMAIL_DOMAIN = '@gmail.com'
Definition at line 42 of file GoogleMailSanitizer.php.
GOOGLEMAIL_DOMAIN
const GOOGLEMAIL_DOMAIN = '@googlemail.com'
Definition at line 41 of file GoogleMailSanitizer.php.
NAME
const NAME = 'googlemail-gmail'
Definition at line 39 of file GoogleMailSanitizer.php.
VERBOSITY_DEBUG
const VERBOSITY_DEBUG = OutputInterface::VERBOSITY_DEBUG inherited
Definition at line 44 of file ISanitizer.php.
VERBOSITY_NORMAL
const VERBOSITY_NORMAL = OutputInterface::VERBOSITY_NORMAL inherited
Definition at line 41 of file ISanitizer.php.
VERBOSITY_QUIET
const VERBOSITY_QUIET = OutputInterface::VERBOSITY_QUIET inherited
Definition at line 40 of file ISanitizer.php.
VERBOSITY_VERBOSE
const VERBOSITY_VERBOSE = OutputInterface::VERBOSITY_VERBOSE inherited
Definition at line 42 of file ISanitizer.php.
VERBOSITY_VERY_VERBOSE
const VERBOSITY_VERY_VERBOSE = OutputInterface::VERBOSITY_VERY_VERBOSE inherited
Definition at line 43 of file ISanitizer.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Maintenance/Sanitizers/GoogleMailSanitizer.php