CamerataDB: ArchiveService Class Reference
ArchiveService Class Reference
Wrapper around the actual archive backend class in order to interface with the virtual storage and actual archive extraction controllers.
Public Member Functions
__construct (ILogger $logger, ?IL10N $l=null,)
setL10N (IL10N $l10n)
Set the localization to use.
setSizeLimit (?int $sizeLimit)
Set the size limit for the uncompressed size of the archives.
getSizeLimit ()
Return the currently configured size-limit.
canOpen (File $fileNode)
Check whether the given file can be opened.
close ()
Close, i.e.
open (File $fileNode, ?int $sizeLimit=null, ?string $password=null)
getArchiveInfo ()
getCommonDirectoryPrefix ()
Return the name of the top-level folder for the case that there is only a single folder at folder nesting level 0.
getFiles ()
getFileContent (string $fileName)
getFileStream (string $fileName)
Static Public Member Functions
static getArchiveFolderName (string $archiveFileName)
Return a proposal for the extraction destination.
Protected Member Functions
t (string $formatString, mixed $parameters=null)
Guard against undefined $this->l.
Static Private Member Functions
static getLocalPath (File $fileNode)
Return the local operating system path of the given file-node.
Private Attributes
$sizeLimit = null
$archiver
$fileNode
$archiveFiles
Detailed Description
Wrapper around the actual archive backend class in order to interface with the virtual storage and actual archive extraction controllers.
Definition at line 43 of file ArchiveService.php.
Constructor & Destructor Documentation
__construct()
__construct (ILogger $logger, ?IL10N $l = null)
Definition at line 147 of file ArchiveService.php.
Member Function Documentation
canOpen()
canOpen (File $fileNode)
Check whether the given file can be opened.
Parameters
File $fileNode
Returns
bool
Definition at line 234 of file ArchiveService.php.
Referenced by ArchiveService\open().
close()
close ()
Close, i.e.
unconfigure. This method is error agnostic, it simply unsets the initial state variables.
Returns
void
Definition at line 245 of file ArchiveService.php.
getArchiveFolderName()
static getArchiveFolderName (string $archiveFileName) static
Return a proposal for the extraction destination.
Currently, this simply strips double extensions like FOO.tag.N -> FOO.
Parameters
string $archiveFileName
Returns
string
Definition at line 334 of file ArchiveService.php.
Referenced by ArchiveService\getArchiveInfo().
getArchiveInfo()
getArchiveInfo ()
Returns
array Archive information, meta-data.
Definition at line 296 of file ArchiveService.php.
References ArchiveService\getArchiveFolderName(), OCA\CAFEVDB\Toolkit\Traits\getClassBaseName(), ArchiveService\getCommonDirectoryPrefix(), and ArchiveService\t().
Referenced by ArchiveService\open().
getCommonDirectoryPrefix()
getCommonDirectoryPrefix ()
Return the name of the top-level folder for the case that there is only a single folder at folder nesting level 0.
Returns
null|string
Definition at line 355 of file ArchiveService.php.
References OCA\CAFEVDB\Toolkit\Traits\getCommonPath(), and ArchiveService\getFiles().
Referenced by ArchiveService\getArchiveInfo().
getFileContent()
getFileContent (string $fileName)
Parameters
string $fileName
Returns
null|string
Definition at line 385 of file ArchiveService.php.
References ArchiveService\t().
getFiles()
getFiles ()
Returns
array<string, ArchiveEntry>
Definition at line 363 of file ArchiveService.php.
References ArchiveService\t().
Referenced by ArchiveService\getCommonDirectoryPrefix().
getFileStream()
getFileStream (string $fileName)
Parameters
string $fileName
Returns
null|resource
Definition at line 399 of file ArchiveService.php.
References ArchiveService\t().
getLocalPath()
static getLocalPath (File $fileNode) static private
Return the local operating system path of the given file-node.
Parameters
File $fileNode
Returns
string
Definition at line 222 of file ArchiveService.php.
getSizeLimit()
getSizeLimit ()
Return the currently configured size-limit.
Returns
null|int
Definition at line 210 of file ArchiveService.php.
open()
open (File $fileNode, ?int $sizeLimit = null, ?string $password = null)
Parameters
File $fileNode
null | int $sizeLimit
null | string $password
Returns
null|ArchiveService
Definition at line 261 of file ArchiveService.php.
References ArchiveService\canOpen(), ArchiveService\getArchiveInfo(), ArchiveBackend\open(), and ArchiveService\t().
setL10N()
setL10N (IL10N $l10n)
Set the localization to use.
Parameters
IL10N $l10n
Returns
ArchiveService $this.
Todo:
Maybe generate a dummy support app instead.
Definition at line 167 of file ArchiveService.php.
setSizeLimit()
setSizeLimit (?int $sizeLimit)
Set the size limit for the uncompressed size of the archives.
Archives with larger uncompressed size will not be handled.
Parameters
null | int $sizeLimit Size-limit. Pass null to disable.
Returns
ArchiveService Return $this for chaining.
Definition at line 199 of file ArchiveService.php.
t()
t (string $formatString, mixed $parameters = null) protected
Guard against undefined $this->l.
Parameters
string $formatString
mixed $parameters
Returns
string
Definition at line 183 of file ArchiveService.php.
Referenced by ArchiveService\getArchiveInfo(), ArchiveService\getFileContent(), ArchiveService\getFiles(), ArchiveService\getFileStream(), and ArchiveService\open().
Field Documentation
$archiveFiles
array $archiveFiles private
Definition at line 144 of file ArchiveService.php.
$archiver
ArchiveBackend $archiver private
Definition at line 138 of file ArchiveService.php.
$fileNode
File $fileNode private
Definition at line 141 of file ArchiveService.php.
$sizeLimit
null int $sizeLimit = null private
Definition at line 135 of file ArchiveService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Toolkit/Service/ArchiveService.php