CamerataDB: ToolTipsService Class Reference
ToolTipsService Class Reference
Tool-tips management with translations.
Public Member Functions
__construct (IAppContainer $appContainer, IL10N $l, ILogger $logger,)
{}
debug (?bool $debug=null)
Enable debug-messages.
getLastKey ()
Get the argument of ToolTipsService::fetch($key) of the most recent call.
getFailedKeys ()
Return the array of failed tooltip-searches after the last successful call.
toolTips ()
Return all tooltips contained in this class.
count ()
{}
offsetExists (mixed $offset)
{}
offsetGet (mixed $offset)
{}
offsetSet (mixed $offset, mixed $value)
{}
offsetUnset (mixed $offset)
{}
fetch (string $key, bool $escape=true)
Return a translated tool-tip for the given key.
Data Fields
const SUBKEY_PREFIXES = [ 'pme' ]
const SUB_KEY_SEP = ':'
Private Member Functions
preProcessKey (string $key)
Pre-process the given $key.
makeToolTips ()
Generate the tooltips-data.
Private Attributes
$l
$toolTipsData
$debug = false
$lastKey = null
$lastToolTip = null
$failedKeys = []
Detailed Description
Tool-tips management with translations.
Definition at line 36 of file ToolTipsService.php.
Constructor & Destructor Documentation
__construct()
__construct (IAppContainer $appContainer, IL10N $l, ILogger $logger)
{}
Definition at line 62 of file ToolTipsService.php.
References ToolTipsService\debug().
Member Function Documentation
count()
count ()
{}
Definition at line 131 of file ToolTipsService.php.
References ToolTipsService\makeToolTips().
Referenced by ToolTipsService\fetch().
debug()
debug (?bool $debug = null)
Enable debug-messages.
Parameters
null | bool $debug If null, just return the setting, otherwise enable or disabled debug-mode.
Returns
bool The current debug-mode enabled setting.
Definition at line 90 of file ToolTipsService.php.
References ToolTipsService\debug().
Referenced by ToolTipsService\__construct(), ToolTipsService\debug(), and ToolTipsService\fetch().
fetch()
fetch (string $key, bool $escape = true)
Return a translated tool-tip for the given key.
Parameters
string $key The tool-tip key to look up.
bool $escape Escape HTML entities.
Returns
null|string
Definition at line 198 of file ToolTipsService.php.
References ToolTipsService\count(), ToolTipsService\debug(), and ToolTipsService\makeToolTips().
Referenced by ToolTipsService\offsetExists(), and ToolTipsService\offsetGet().
getFailedKeys()
getFailedKeys ()
Return the array of failed tooltip-searches after the last successful call.
Returns
array
Definition at line 114 of file ToolTipsService.php.
getLastKey()
getLastKey ()
Get the argument of ToolTipsService::fetch($key) of the most recent call.
Returns
null|string
Definition at line 103 of file ToolTipsService.php.
makeToolTips()
makeToolTips () private
Generate the tooltips-data.
This is primarily not static because the translation function is not static.
Returns
void
Definition at line 249 of file ToolTipsService.php.
Referenced by ToolTipsService\count(), ToolTipsService\fetch(), and ToolTipsService\toolTips().
offsetExists()
offsetExists (mixed $offset)
{}
Definition at line 138 of file ToolTipsService.php.
References ToolTipsService\fetch().
offsetGet()
offsetGet (mixed $offset)
{}
Definition at line 144 of file ToolTipsService.php.
References ToolTipsService\fetch().
offsetSet()
offsetSet (mixed $offset, mixed $value)
{}
Definition at line 150 of file ToolTipsService.php.
offsetUnset()
offsetUnset (mixed $offset)
{}
Definition at line 156 of file ToolTipsService.php.
preProcessKey()
preProcessKey (string $key) private
Pre-process the given $key.
If a key starts with a known prefix, but has a '-' as separator, then replace all dashes by our standard separator.
Parameters
string $key The key to process.
Returns
string
Definition at line 169 of file ToolTipsService.php.
toolTips()
toolTips ()
Return all tooltips contained in this class.
Returns
array
Definition at line 124 of file ToolTipsService.php.
References ToolTipsService\makeToolTips().
Field Documentation
$debug
bool $debug = false private
Definition at line 50 of file ToolTipsService.php.
$failedKeys
array $failedKeys = [] private
Definition at line 59 of file ToolTipsService.php.
$l
IL10N $l private
Definition at line 44 of file ToolTipsService.php.
$lastKey
string $lastKey = null private
Definition at line 53 of file ToolTipsService.php.
$lastToolTip
string $lastToolTip = null private
Definition at line 56 of file ToolTipsService.php.
$toolTipsData
array $toolTipsData private
Definition at line 47 of file ToolTipsService.php.
SUB_KEY_SEP
const SUB_KEY_SEP = ':'
Definition at line 41 of file ToolTipsService.php.
SUBKEY_PREFIXES
const SUBKEY_PREFIXES = [ 'pme' ]
Definition at line 40 of file ToolTipsService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/ToolTipsService.php