CamerataDB: AbstractFileSystemUndoable Class Reference
AbstractFileSystemUndoable Class Reference
Base for file-system related IUndoable implementations.
Public Member Functions
initialize (IAppContainer $appContainer)
{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}
do ()
Do something.
undo ()
Undo that what was done by do().
reset ()
Reset initial state.
Protected Member Functions
renamedName (string $path)
Create a new unique name for renaming.
Static Protected Member Functions
static normalizePath (string $path)
Remove multipled slashes.
Protected Attributes
$l
$timeFactory
$userStorage
$appContainer
Detailed Description
Base for file-system related IUndoable implementations.
Definition at line 35 of file AbstractFileSystemUndoable.php.
Member Function Documentation
do()
do () inherited
Do something.
Returns
void
Implemented in GenericUndoable, UndoableFileRename, and UndoableFileReplace.
initialize()
initialize (IAppContainer $appContainer)
{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}
Reimplemented from AbstractUndoable.
Reimplemented in UndoableFileReplace, UndoableFileSystemNodeRemove, UndoableFolderCreate, and UndoableTextFileUpdate.
Definition at line 49 of file AbstractFileSystemUndoable.php.
normalizePath()
static normalizePath (string $path) static protected
Remove multipled slashes.
Parameters
string $path
Returns
string
Definition at line 65 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFileRename\do(), and UndoableFileReplace\do().
renamedName()
renamedName (string $path) protected
Create a new unique name for renaming.
Parameters
string $path
Returns
string
Definition at line 79 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFolderCreate\reset(), UndoableTextFileUpdate\reset(), UndoableFolderCreate\undo(), and UndoableTextFileUpdate\undo().
reset()
reset () inherited
Reset initial state.
Returns
void
Implemented in GenericUndoable, UndoableFileRename, UndoableFileReplace, UndoableFileSystemNodeRemove, UndoableFolderCreate, UndoableFolderRename, and UndoableTextFileUpdate.
undo()
undo () inherited
Undo that what was done by do().
Returns
void
Implemented in GenericUndoable, UndoableFileRename, UndoableFileReplace, UndoableFileSystemNodeRemove, UndoableFolderCreate, UndoableFolderRename, and UndoableTextFileUpdate.
Field Documentation
$appContainer
IAppContainer $appContainer protected inherited
Definition at line 33 of file AbstractUndoable.php.
$l
IL10N $l protected
Definition at line 40 of file AbstractFileSystemUndoable.php.
$timeFactory
ITimeFactory $timeFactory protected
Definition at line 43 of file AbstractFileSystemUndoable.php.
$userStorage
UserStorage $userStorage protected
Definition at line 46 of file AbstractFileSystemUndoable.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/AbstractFileSystemUndoable.php