CamerataDB: PeriodicReceivablesGenerator Class Reference
PeriodicReceivablesGenerator Class Reference
Always generate a new payment request.
Public Member Functions
__construct (protected ConfigService $configService, private ToolTipsService $toolTipsService, EntityManager $entityManager, ProgressStatusService $progressStatusService, ?\DateInterval $interval=null,)
bind (Entities\ProjectParticipantField $serviceFeeField, ?IProgressStatus $progressStatus=null)
{Bind this instance to the given entity.The idea is to have a constructor which allowes for dependency injection. This, however, means that the DB entities must not be passed through the constructor.
Parameters
Entities\\ProjectParticipantField $serviceFeeField
null | IProgressStatus $progressStatus Optional progress status class in order to give feedback during long running updates.
Returns
void
}
updateParticipant (Entities\ProjectParticipant $participant, ?Entities\ProjectParticipantFieldDataOption $receivable, string $updateStrategy=self::UPDATE_STRATEGY_EXCEPTION,)
{Update the amount to invoice for the bound service-fee field.
Parameters
Entities\\ProjectParticipant $participant The musician to update the service claim for.
null | Entities\\ProjectParticipantFieldDataOption $receivable The option to update/recompute. If null all options have to be updated.
string $updateStrategy
Returns
array<string, int>
[
  'added' => #ADDED,
  'removed' => #REMOVED,
  'changed' => #CHANGED,
  'skipped' => #SKIPPED,
  'notices' => [ MSG1, MSG2, ... ],
]
where the numbers reflect the respective actions performed on the field-data for the participant.
}
dueDate (?Entities\ProjectParticipantFieldDataOption $receivable=null)
{Fetch the due-date for the given receivable or the maximum of all due-dates.
Parameters
null | Entities\\ProjectParticipantFieldDataOption $receivable
Returns
DateTimeInterface
}
generateReceivables ()
Update the list of receivables for the bound service-fee field, for example by generating fields up to the current date.
updateReceivable (Entities\ProjectParticipantFieldDataOption $receivable, ?Entities\ProjectParticipant $participant=null, string $updateStrategy=self::UPDATE_STRATEGY_EXCEPTION,)
Update the amount to invoice for bound service-fee field.
updateAll (string $updateStrategy=self::UPDATE_STRATEGY_EXCEPTION)
Compute the amounts to invoice for all relevant musicians and existing receivables.
Static Public Member Functions
static slug ()
{A unique short slug which can be used to identify the generator.
Returns
string
}
static uiFlags ()
{Flags controlling the intended user interaction in the per-musician view.
Returns
int
}
static updateStrategyChoices ()
{An array of possible conflict resolutions for conflicting data-items.
Returns
array
}
static operationLabels (?string $slug=null)
{Return an array of button-labels (or just one label), indexed by operation slug.If a label is literal false the corresponding UI element can be hidden, if true a default element will be used. For labelled control elements a string can be returned.
Parameters
null | string $slug Must be either null or one of the elements of self::SLUGS. If null all labels will be return, otherwise just the requested one. If $slug is a string but is not contained in self::OPERATION_SLUGS then null is returned.
Returns
null|string|arra
}
Data Fields
const UPDATE_STRATEGIES
const OPERATION_OPTION_REGENERATE = 'option-regenerate'
const OPERATION_OPTION_REGENERATE_ALL = 'option-regenerate-all'
const OPERATION_GENERATOR_REGENERATE = 'generator-regenerate'
const OPERATION_GENERATOR_RUN = 'generator-run'
const OPERATION_SLUGS
Protected Member Functions
updateOne (Entities\ProjectParticipantFieldDataOption $receivable, Entities\ProjectParticipant $participant, string $updateStrategy=self::UPDATE_STRATEGY_EXCEPTION,)
Update just the given receivable and participant.
Static Protected Member Functions
static translationDummy ()
Inject some translations of constants into the machinery.
Protected Attributes
$amount
$serviceFeeField
$progressStatus
$progressData
Private Attributes
$timeZone
$intervalSeconds
Detailed Description
Always generate a new payment request.
This is just a dummy nonsense proof-of-concept implementation. It will always generate new receivables, and calling updateReceivable() will also always just change the amount to pay.
Definition at line 49 of file PeriodicReceivablesGenerator.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ConfigService $configService, private ToolTipsService $toolTipsService, EntityManager $entityManager, ProgressStatusService $progressStatusService, ?\DateInterval $interval = null)
Definition at line 64 of file PeriodicReceivablesGenerator.php.
Member Function Documentation
bind()
bind (Entities\ProjectParticipantField $serviceFeeField, ?IProgressStatus $progressStatus = null) inherited
{Bind this instance to the given entity.The idea is to have a constructor which allowes for dependency injection. This, however, means that the DB entities must not be passed through the constructor.
Parameters
Entities\\ProjectParticipantField $serviceFeeField
null | IProgressStatus $progressStatus Optional progress status class in order to give feedback during long running updates.
Returns
void
}
Implements IRecurringReceivablesGenerator.
Definition at line 112 of file AbstractReceivablesGenerator.php.
References DoNothingProgressStatus\update().
dueDate()
dueDate (?Entities\ProjectParticipantFieldDataOption $receivable = null) inherited
{Fetch the due-date for the given receivable or the maximum of all due-dates.
Parameters
null | Entities\\ProjectParticipantFieldDataOption $receivable
Returns
DateTimeInterface
}
Implements IRecurringReceivablesGenerator.
Reimplemented in InstrumentInsuranceReceivablesGenerator.
Definition at line 343 of file AbstractReceivablesGenerator.php.
generateReceivables()
generateReceivables () inherited
Update the list of receivables for the bound service-fee field, for example by generating fields up to the current date.
The link to the actual Entities\ProjectParticipantField entity is established by a prior call to $this->bind($serviceFeeField). The generated receivables may not yet have been persisted.
Returns
Collection Collection of Entities\ProjectParticipantFieldDataOption entities covering all relevant receivables.
Implemented in DoNothingReceivablesGenerator.
operationLabels()
static operationLabels (?string $slug = null) static inherited
{Return an array of button-labels (or just one label), indexed by operation slug.If a label is literal false the corresponding UI element can be hidden, if true a default element will be used. For labelled control elements a string can be returned.
Parameters
null | string $slug Must be either null or one of the elements of self::SLUGS. If null all labels will be return, otherwise just the requested one. If $slug is a string but is not contained in self::OPERATION_SLUGS then null is returned.
Returns
null|string|arra
}
Implements IRecurringReceivablesGenerator.
Reimplemented in ManuallyGeneratedReceivablesGenerator.
Definition at line 91 of file AbstractReceivablesGenerator.php.
slug()
static slug () static
{A unique short slug which can be used to identify the generator.
Returns
string
}
Implements IRecurringReceivablesGenerator.
Definition at line 88 of file PeriodicReceivablesGenerator.php.
translationDummy()
static translationDummy () static protected inherited
Inject some translations of constants into the machinery.
Returns
void
Definition at line 71 of file AbstractReceivablesGenerator.php.
uiFlags()
static uiFlags () static inherited
{Flags controlling the intended user interaction in the per-musician view.
Returns
int
}
Implements IRecurringReceivablesGenerator.
Reimplemented in ManuallyGeneratedReceivablesGenerator.
Definition at line 79 of file AbstractReceivablesGenerator.php.
updateAll()
updateAll (string $updateStrategy = self::UPDATE_STRATEGY_EXCEPTION) inherited
Compute the amounts to invoice for all relevant musicians and existing receivables.
New receivables are not added.
Parameters
string $updateStrategy
Returns
array<string, int>
[
  'added' => #ADDED,
  'removed' => #REMOVED,
  'changed' => #CHANGED,
  'skipped' => #SKIPPED,
  'notices' => [ MSG1, MSG2, ... ],
]
where the number reflect the respective actions performed on the field-data for all participants.
updateOne()
updateOne (Entities\ProjectParticipantFieldDataOption $receivable, Entities\ProjectParticipant $participant, string $updateStrategy = self::UPDATE_STRATEGY_EXCEPTION) abstract protected inherited
Update just the given receivable and participant.
Parameters
Entities\\ProjectParticipantFieldDataOption $receivable The option to update/recompute.
Entities\\ProjectParticipant $participant The musician to update the service fee claim for.
string $updateStrategy
Returns
array<string, int>
[ 'added' => #ADDED, 'removed' => #REMOVED, 'changed' => #CHANGED ]
where of course each component is either 0 or 1.
Exceptions
RuntimeException Depending on $updateStrategy.
Reimplemented in DoNothingReceivablesGenerator, and ManuallyGeneratedReceivablesGenerator.
References AbstractReceivablesGenerator\updateOne().
Referenced by AbstractReceivablesGenerator\updateOne().
updateParticipant()
updateParticipant (Entities\ProjectParticipant $participant, ?Entities\ProjectParticipantFieldDataOption $receivable, string $updateStrategy = self::UPDATE_STRATEGY_EXCEPTION) inherited
{Update the amount to invoice for the bound service-fee field.
Parameters
Entities\\ProjectParticipant $participant The musician to update the service claim for.
null | Entities\\ProjectParticipantFieldDataOption $receivable The option to update/recompute. If null all options have to be updated.
string $updateStrategy
Returns
array<string, int>
[
  'added' => #ADDED,
  'removed' => #REMOVED,
  'changed' => #CHANGED,
  'skipped' => #SKIPPED,
  'notices' => [ MSG1, MSG2, ... ],
]
where the numbers reflect the respective actions performed on the field-data for the participant.
}
Implements IRecurringReceivablesGenerator.
Definition at line 267 of file AbstractReceivablesGenerator.php.
updateReceivable()
updateReceivable (Entities\ProjectParticipantFieldDataOption $receivable, ?Entities\ProjectParticipant $participant = null, string $updateStrategy = self::UPDATE_STRATEGY_EXCEPTION) inherited
Update the amount to invoice for bound service-fee field.
Parameters
Entities\\ProjectParticipantFieldDataOption $receivable The option to update/recompute.
null | Entities\\ProjectParticipant $participant The musician to update the service claim for. If null, the values for all affected musicians have to be recomputed.
string $updateStrategy
Returns
array<string, int>
[
  'added' => #ADDED,
  'removed' => #REMOVED,
  'changed' => #CHANGED,
  'skipped' => #SKIPPED,
  'notices' => [ MSG1, MSG2, ... ],
]
where the numbers reflect the respective actions performed on the field-data for the given option.
updateStrategyChoices()
static updateStrategyChoices () static inherited
{An array of possible conflict resolutions for conflicting data-items.
Returns
array
}
Implements IRecurringReceivablesGenerator.
Reimplemented in ManuallyGeneratedReceivablesGenerator.
Definition at line 85 of file AbstractReceivablesGenerator.php.
Field Documentation
$amount
float $amount protected
Definition at line 55 of file PeriodicReceivablesGenerator.php.
$intervalSeconds
int $intervalSeconds private
Definition at line 61 of file PeriodicReceivablesGenerator.php.
$progressData
array $progressData protected inherited
Definition at line 50 of file AbstractReceivablesGenerator.php.
$progressStatus
IProgressStatus $progressStatus protected inherited
Definition at line 47 of file AbstractReceivablesGenerator.php.
$serviceFeeField
Entities ProjectParticipantField $serviceFeeField protected inherited
Definition at line 44 of file AbstractReceivablesGenerator.php.
$timeZone
DateTimeZone $timeZone private
Definition at line 58 of file PeriodicReceivablesGenerator.php.
OPERATION_GENERATOR_REGENERATE
const OPERATION_GENERATOR_REGENERATE = 'generator-regenerate' inherited
Definition at line 82 of file IRecurringReceivablesGenerator.php.
OPERATION_GENERATOR_RUN
const OPERATION_GENERATOR_RUN = 'generator-run' inherited
Definition at line 83 of file IRecurringReceivablesGenerator.php.
OPERATION_OPTION_REGENERATE
const OPERATION_OPTION_REGENERATE = 'option-regenerate' inherited
Definition at line 80 of file IRecurringReceivablesGenerator.php.
OPERATION_OPTION_REGENERATE_ALL
const OPERATION_OPTION_REGENERATE_ALL = 'option-regenerate-all' inherited
Definition at line 81 of file IRecurringReceivablesGenerator.php.
OPERATION_SLUGS
const OPERATION_SLUGS inherited
Initial value:
= [
    self::OPERATION_OPTION_REGENERATE,
    self::OPERATION_OPTION_REGENERATE_ALL,
    self::OPERATION_GENERATOR_RUN,
    self::OPERATION_GENERATOR_REGENERATE,
  ]
Definition at line 85 of file IRecurringReceivablesGenerator.php.
UPDATE_STRATEGIES
const UPDATE_STRATEGIES inherited
Initial value:
= [
    self::UPDATE_STRATEGY_REPLACE,
    self::UPDATE_STRATEGY_SKIP,
    self::UPDATE_STRATEGY_EXCEPTION,
  ]
Definition at line 74 of file IRecurringReceivablesGenerator.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/Finance/PeriodicReceivablesGenerator.php