CamerataDB: AddressBookProvider Class Reference
AddressBookProvider Class Reference
Kind of factory for our musicians address book.
Public Member Functions
__construct (ConfigService $configService, ContactsService $contactsService, MusicianCardBackend $cardBackend,)
getAppId ()
Provides the appId of the plugin.
fetchAllForAddressBookHome (string $principalUri)
Fetches all address books for a given principal uri.
hasAddressBookInAddressBookHome (string $principalUri, string $uri)
Checks whether plugin has an address book for a given principalUri and URI.
getAddressBookInAddressBookHome (string $principalUri, string $uri)
Fetches an address book for a given principalUri and URI Returns null if address book does not exist.
getContactsAddressBook ()
Return a cloud-address-book suitable for registration with the \OCP\IContactsManager.
Private Member Functions
addressBookUri ()
Private Attributes
$cardBackend
$contactsService
Static Private Attributes
static $addressBook = null
static $contactsAddressBook = null
Detailed Description
Kind of factory for our musicians address book.
Definition at line 38 of file AddressBookProvider.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ContactsService $contactsService, MusicianCardBackend $cardBackend)
Definition at line 55 of file AddressBookProvider.php.
Member Function Documentation
addressBookUri()
addressBookUri () private
Returns
string
Definition at line 132 of file AddressBookProvider.php.
Referenced by AddressBookProvider\fetchAllForAddressBookHome(), and AddressBookProvider\getAddressBookInAddressBookHome().
fetchAllForAddressBookHome()
fetchAllForAddressBookHome (string $principalUri)
Fetches all address books for a given principal uri.
Parameters
string $principalUri E.g. principals/users/user1.
Returns
ExternalAddressBook[] Array of all address books
Definition at line 84 of file AddressBookProvider.php.
References AddressBookProvider\addressBookUri(), and AddressBookProvider\getAddressBookInAddressBookHome().
getAddressBookInAddressBookHome()
getAddressBookInAddressBookHome (string $principalUri, string $uri)
Fetches an address book for a given principalUri and URI Returns null if address book does not exist.
Parameters
string $principalUri E.g. principals/users/user1.
string $uri E.g. personal.
Returns
ExternalAddressBook|null address book if it exists, null otherwise.
Definition at line 117 of file AddressBookProvider.php.
References AddressBookProvider\addressBookUri().
Referenced by AddressBookProvider\fetchAllForAddressBookHome().
getAppId()
getAppId ()
Provides the appId of the plugin.
Returns
string AppId
Definition at line 72 of file AddressBookProvider.php.
getContactsAddressBook()
getContactsAddressBook ()
Return a cloud-address-book suitable for registration with the \OCP\IContactsManager.
Returns
null|ContactsAddressBook
Definition at line 143 of file AddressBookProvider.php.
hasAddressBookInAddressBookHome()
hasAddressBookInAddressBookHome (string $principalUri, string $uri)
Checks whether plugin has an address book for a given principalUri and URI.
This returns true if the current user belongs to the orchestra group.
Parameters
string $principalUri E.g. principals/users/user1.
string $uri E.g. personal.
Returns
bool True if address book for principalUri and URI exists, false otherwise.
Definition at line 101 of file AddressBookProvider.php.
Field Documentation
$addressBook
AddressBook $addressBook = null static private
Definition at line 43 of file AddressBookProvider.php.
$cardBackend
MusicianCardBackend $cardBackend private
Definition at line 49 of file AddressBookProvider.php.
$contactsAddressBook
ContactsAddressBook $contactsAddressBook = null static private
Definition at line 46 of file AddressBookProvider.php.
$contactsService
ContactsService $contactsService private
Definition at line 52 of file AddressBookProvider.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/AddressBook/AddressBookProvider.php