CamerataDB: UndoableFileReplace Class Reference
UndoableFileReplace Class Reference
Replace one file by another, maintaining an undo history in the cloud.
Public Member Functions
__construct (mixed $name, string $content, mixed $oldName=null, bool $gracefully=false)
initialize (IAppContainer $appContainer)
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
do ()
{Do something.
Returns
void
}
undo ()
{Undo that what was done by do().
Returns
void
}
reset ()
{Reset initial state.
Returns
void
}
Protected Member Functions
renamedName (string $path)
Create a new unique name for renaming.
Static Protected Member Functions
static normalizePath (string $path)
Remove multipled slashes.
Protected Attributes
$name
$content
$oldName
$gracefully
$restoreOldName
$restoreSameName
$doneInterval
$l
$timeFactory
$userStorage
$appContainer
Detailed Description
Replace one file by another, maintaining an undo history in the cloud.
Both files may have different names.
@SuppressWarnings(PHPMD.ShortMethodName)
Definition at line 40 of file UndoableFileReplace.php.
Constructor & Destructor Documentation
__construct()
__construct (mixed $name, string $content, mixed $oldName = null, bool $gracefully = false)
Parameters
string | callable $name The name of the new file.
string $content The content to place into the file system with name $name.
null | string | callable $oldName A name of an old file to replace.
bool $gracefully
Definition at line 72 of file UndoableFileReplace.php.
References UndoableFileReplace\reset().
Member Function Documentation
do()
do ()
{Do something.
Returns
void
}
Implements IUndoable.
Definition at line 88 of file UndoableFileReplace.php.
References AbstractFileSystemUndoable\normalizePath().
initialize()
initialize (IAppContainer $appContainer)
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
Reimplemented from AbstractFileSystemUndoable.
Definition at line 82 of file UndoableFileReplace.php.
normalizePath()
static normalizePath (string $path) static protected inherited
Remove multipled slashes.
Parameters
string $path
Returns
string
Definition at line 65 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFileRename\do(), and UndoableFileReplace\do().
renamedName()
renamedName (string $path) protected inherited
Create a new unique name for renaming.
Parameters
string $path
Returns
string
Definition at line 79 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFolderCreate\reset(), UndoableTextFileUpdate\reset(), UndoableFolderCreate\undo(), and UndoableTextFileUpdate\undo().
reset()
reset ()
{Reset initial state.
Returns
void
}
Implements IUndoable.
Definition at line 140 of file UndoableFileReplace.php.
Referenced by UndoableFileReplace\__construct().
undo()
undo ()
{Undo that what was done by do().
Returns
void
}
Implements IUndoable.
Definition at line 129 of file UndoableFileReplace.php.
Field Documentation
$appContainer
IAppContainer $appContainer protected inherited
Definition at line 33 of file AbstractUndoable.php.
$content
string $content protected
Definition at line 46 of file UndoableFileReplace.php.
$doneInterval
array< int, int > $doneInterval protected
Definition at line 61 of file UndoableFileReplace.php.
$gracefully
bool $gracefully protected
Definition at line 52 of file UndoableFileReplace.php.
$l
IL10N $l protected inherited
Definition at line 40 of file AbstractFileSystemUndoable.php.
$name
string callable $name protected
Definition at line 43 of file UndoableFileReplace.php.
$oldName
string $oldName protected
Definition at line 49 of file UndoableFileReplace.php.
$restoreOldName
bool $restoreOldName protected
Definition at line 55 of file UndoableFileReplace.php.
$restoreSameName
bool $restoreSameName protected
Definition at line 58 of file UndoableFileReplace.php.
$timeFactory
ITimeFactory $timeFactory protected inherited
Definition at line 43 of file AbstractFileSystemUndoable.php.
$userStorage
UserStorage $userStorage protected inherited
Definition at line 46 of file AbstractFileSystemUndoable.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/UndoableFileReplace.php