CamerataDB: BiDirectionalL10N Class Reference
BiDirectionalL10N Class Reference
Simple bidectional translations fetch from a CSV file.
Public Member Functions
__construct (string $appName, ILogger $logger, IL10N $l10n, string $keyLang='en',)
setL10N (IL10N $l10n)
t (string $phrase)
Attempt a translation.
backTranslate (string $translation)
Attempt an un-translation.
mergeCSV (string $fileName)
Protected Member Functions
loadLanguageData ()
Static Protected Member Functions
static parseCSV (string $fileName, string $targetLang, string $keyLang='en')
Protected Attributes
$l10n
$targetLang
$keyLang
$translations
Private Attributes
const FORWARD = 'forward'
const REVERSE = 'reverse'
Detailed Description
Simple bidectional translations fetch from a CSV file.
@SuppressWarnings(PHPMD.ShortMethodName)
Definition at line 37 of file BiDirectionalL10N.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, ILogger $logger, IL10N $l10n, string $keyLang = 'en')
Definition at line 57 of file BiDirectionalL10N.php.
Member Function Documentation
backTranslate()
backTranslate (string $translation)
Attempt an un-translation.
If it fails, return the original string.
Parameters
string $translation
Returns
null|string
Definition at line 112 of file BiDirectionalL10N.php.
References BiDirectionalL10N\loadLanguageData().
loadLanguageData()
loadLanguageData () protected
Returns
void
Definition at line 134 of file BiDirectionalL10N.php.
References BiDirectionalL10N\mergeCSV().
Referenced by BiDirectionalL10N\backTranslate(), and BiDirectionalL10N\t().
mergeCSV()
mergeCSV (string $fileName)
Parameters
string $fileName
Returns
void
Definition at line 149 of file BiDirectionalL10N.php.
References BiDirectionalL10N\parseCSV().
Referenced by BiDirectionalL10N\loadLanguageData().
parseCSV()
static parseCSV (string $fileName, string $targetLang, string $keyLang = 'en') static protected
Parameters
string $fileName
string $targetLang
string $keyLang
Returns
null|array
Definition at line 164 of file BiDirectionalL10N.php.
Referenced by BiDirectionalL10N\mergeCSV().
setL10N()
setL10N (IL10N $l10n)
Parameters
IL10N $l10n
Returns
void
Definition at line 75 of file BiDirectionalL10N.php.
t()
t (string $phrase)
Attempt a translation.
If it fails, return the original string.
Parameters
string $phrase
Returns
string
Definition at line 89 of file BiDirectionalL10N.php.
References BiDirectionalL10N\loadLanguageData().
Field Documentation
$keyLang
string $keyLang protected
Definition at line 51 of file BiDirectionalL10N.php.
$l10n
IL10N $l10n protected
Definition at line 45 of file BiDirectionalL10N.php.
$targetLang
string $targetLang protected
Definition at line 48 of file BiDirectionalL10N.php.
$translations
$translations protected
Definition at line 54 of file BiDirectionalL10N.php.
FORWARD
const FORWARD = 'forward' private
Definition at line 41 of file BiDirectionalL10N.php.
REVERSE
const REVERSE = 'reverse' private
Definition at line 42 of file BiDirectionalL10N.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/L10N/BiDirectionalL10N.php