CamerataDB: PageController Class Reference
PageController Class Reference
Main UI entry point providing the front pages.
Public Member Functions
__construct (?string $appName, IRequest $request, ISession $session, IAppContainer $appContainer, AssetService $assetService, ConfigService $configService, HistoryService $historyService, OrganizationalRolesService $organizationalRolesService, RequestParameterService $parameterService, ToolTipsService $toolTipsService, PageNavigation $pageNavigation, IInitialStateService $initialStateService, ConfigCheckService $configCheckService, \OCP\IURLGenerator $urlGenerator,)
index ()
Load the main page of the App.
post (mixed $a, mixed $b, mixed $c, mixed $d, mixed $e, mixed $f, mixed $g)
history (int $level=0, string $renderAs='blank')
Load a page at the specified offset from the history.
remember (string $renderAs='user')
Load a page and remembers the request parameters in the history.
debug ()
notFound (mixed $a, mixed $b, mixed $c, mixed $d, mixed $e, mixed $f, mixed $g)
Data Fields
const DEFAULT_TEMPLATE = 'projects'
const HOME_TEMPLATE = 'home'
const HISTORY_ACTION_LOAD = 'load'
const HISTORY_ACTION_PUSH = 'push'
Protected Attributes
$l
$toolTipsService
Private Member Functions
shouldLoadHistory (int $level=0)
getTemplate (?string $template, string $renderAs)
Private Attributes
$session
$historyService
$parameterService
$configCheckService
$organizationalRolesService
$urlGenerator
$appContainer
$pageNavigation
$assetService
$configCheck
Result of ConfigCheckService.
Detailed Description
Main UI entry point providing the front pages.
Definition at line 59 of file PageController.php.
Constructor & Destructor Documentation
__construct()
__construct (?string $appName, IRequest $request, ISession $session, IAppContainer $appContainer, AssetService $assetService, ConfigService $configService, HistoryService $historyService, OrganizationalRolesService $organizationalRolesService, RequestParameterService $parameterService, ToolTipsService $toolTipsService, PageNavigation $pageNavigation, IInitialStateService $initialStateService, ConfigCheckService $configCheckService, \OCP\IURLGenerator $urlGenerator)
Definition at line 110 of file PageController.php.
Member Function Documentation
debug()
debug ()
Returns
Http\Response
@NoAdminRequired @NoCSRFRequired @UseSession
Definition at line 304 of file PageController.php.
getTemplate()
getTemplate (?string $template, string $renderAs) private
Parameters
null | string $template
string $renderAs
Returns
string
Definition at line 475 of file PageController.php.
history()
history (int $level = 0, string $renderAs = 'blank')
Load a page at the specified offset from the history.
Returns an error if the entry cannot be found in the history.
Parameters
int $level
string $renderAs
Returns
Http\Response
@NoAdminRequired @UseSession
Definition at line 250 of file PageController.php.
Referenced by PageController\index().
index()
index ()
Load the main page of the App.
Returns
Http\Response
@NoAdminRequired @NoGroupMemberRequired @NoCSRFRequired @UseSession
Definition at line 158 of file PageController.php.
References PageController\history(), PageController\remember(), and PageController\shouldLoadHistory().
notFound()
notFound (mixed $a, mixed $b, mixed $c, mixed $d, mixed $e, mixed $f, mixed $g)
Parameters
mixed $a
mixed $b
mixed $c
mixed $d
mixed $e
mixed $f
mixed $g
Returns
Http\Response
@NoAdminRequired
Definition at line 511 of file PageController.php.
post()
post (mixed $a, mixed $b, mixed $c, mixed $d, mixed $e, mixed $f, mixed $g)
Parameters
mixed $a
mixed $b
mixed $c
mixed $d
mixed $e
mixed $f
mixed $g
Returns
Http\Response
@NoAdminRequired @NoGroupMemberRequired @NoCSRFRequired
Definition at line 224 of file PageController.php.
remember()
remember (string $renderAs = 'user')
Load a page and remembers the request parameters in the history.
Parameters
string $renderAs
Returns
Http\Response
@NoAdminRequired @UseSession
Definition at line 284 of file PageController.php.
Referenced by PageController\index().
shouldLoadHistory()
shouldLoadHistory (int $level = 0) private
Parameters
int $level
Returns
bool
Definition at line 178 of file PageController.php.
Referenced by PageController\index().
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 95 of file PageController.php.
$assetService
AssetService $assetService private
Definition at line 101 of file PageController.php.
$configCheck
array $configCheck private
Result of ConfigCheckService.
Definition at line 107 of file PageController.php.
$configCheckService
ConfigCheckService $configCheckService private
Definition at line 86 of file PageController.php.
$historyService
HistoryService $historyService private
Definition at line 77 of file PageController.php.
$l
IL10N $l protected
Definition at line 74 of file PageController.php.
$organizationalRolesService
OCA CAFEVDB Service OrganizationalRolesService $organizationalRolesService private
Definition at line 89 of file PageController.php.
$pageNavigation
OCA CAFEVDB PageRenderer Util Navigation $pageNavigation private
Definition at line 98 of file PageController.php.
$parameterService
RequestParameterService $parameterService private
Definition at line 80 of file PageController.php.
$session
ISession $session private
Definition at line 71 of file PageController.php.
$toolTipsService
ToolTipsService $toolTipsService protected
Definition at line 83 of file PageController.php.
$urlGenerator
OCP IURLGenerator $urlGenerator private
Definition at line 92 of file PageController.php.
DEFAULT_TEMPLATE
const DEFAULT_TEMPLATE = 'projects'
Definition at line 64 of file PageController.php.
HISTORY_ACTION_LOAD
const HISTORY_ACTION_LOAD = 'load'
Definition at line 67 of file PageController.php.
HISTORY_ACTION_PUSH
const HISTORY_ACTION_PUSH = 'push'
Definition at line 68 of file PageController.php.
HOME_TEMPLATE
const HOME_TEMPLATE = 'home'
Definition at line 65 of file PageController.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Controller/PageController.php