CamerataDB: CryptoController Class Reference
CryptoController Class Reference
Encryption/Decryption AJAX end-points.
Public Member Functions
__construct (string $appName, IRequest $request, ILogger $logger, IAppContainer $appContainer, EntityManager $entityManager,)
unseal (string $sealedData, ?string $metaData)
Unseal the given data provided the currently logged in user is part of the seal context.
batchUnseal (array $sealedData, ?string $metaData)
Unseal the given data provided the currently logged in user is part of the seal context.
Data Fields
const META_DATA_IBAN = 'iban'
Protected Attributes
$encryptionTransformer
$appContainer
$financeService
Private Member Functions
getUnsealedData (string $sealedData, ?string $metaData)
Unseal the given data provided the currently logged in user is part of the seal context.
getIBANMetaData (string $iban)
Detailed Description
Encryption/Decryption AJAX end-points.
Definition at line 37 of file CryptoController.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, IRequest $request, ILogger $logger, IAppContainer $appContainer, EntityManager $entityManager)
Definition at line 54 of file CryptoController.php.
Member Function Documentation
batchUnseal()
batchUnseal (array $sealedData, ?string $metaData)
Unseal the given data provided the currently logged in user is part of the seal context.
Parameters
array $sealedData
null | string $metaData
Returns
Http\DataResponse
@NoAdminRequired
Definition at line 98 of file CryptoController.php.
References CryptoController\getUnsealedData().
getIBANMetaData()
getIBANMetaData (string $iban) private
Parameters
string $iban
Returns
null|array
Definition at line 146 of file CryptoController.php.
Referenced by CryptoController\getUnsealedData().
getUnsealedData()
getUnsealedData (string $sealedData, ?string $metaData) private
Unseal the given data provided the currently logged in user is part of the seal context.
Parameters
string $sealedData
null | string $metaData
Returns
array
Definition at line 119 of file CryptoController.php.
References CryptoController\getIBANMetaData().
Referenced by CryptoController\batchUnseal(), and CryptoController\unseal().
unseal()
unseal (string $sealedData, ?string $metaData)
Unseal the given data provided the currently logged in user is part of the seal context.
Parameters
string $sealedData
null | string $metaData
Returns
Http\DataResponse
@NoAdminRequired
Definition at line 81 of file CryptoController.php.
References CryptoController\getUnsealedData().
Field Documentation
$appContainer
IAppContainer $appContainer protected
Definition at line 48 of file CryptoController.php.
$encryptionTransformer
Transformable Transformer TransformerInterface $encryptionTransformer protected
Definition at line 45 of file CryptoController.php.
$financeService
FinanceService $financeService protected
Definition at line 51 of file CryptoController.php.
META_DATA_IBAN
const META_DATA_IBAN = 'iban'
Definition at line 42 of file CryptoController.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Controller/CryptoController.php