CamerataDB: EmptyDirectoryNode Class Reference
EmptyDirectoryNode Class Reference
This is a placeholder which appears as top-level directory if the storage does not hold any entries.
Public Member Functions
__construct (protected string $name, protected DateTimeInterface $updated, protected ?string $storageId=null, protected ?DatabaseStorageFolder $parent=null,)
getName ()
setName (string $name)
getParent ()
getMimeType ()
getStorage ()
getStorageId ()
getUpdated ()
setUpdated (DateTimeInterface $updated)
Detailed Description
This is a placeholder which appears as top-level directory if the storage does not hold any entries.
Definition at line 37 of file EmptyDirectoryNode.php.
Constructor & Destructor Documentation
__construct()
__construct (protected string $name, protected DateTimeInterface $updated, protected ?string $storageId = null, protected ?DatabaseStorageFolder $parent = null)
Parameters
string $name
null | DateTimeInterface $updated
null | string $storageId
null | DatabaseStorageFolder $parent
Definition at line 48 of file EmptyDirectoryNode.php.
Member Function Documentation
getMimeType()
getMimeType ()
Returns
string
Definition at line 87 of file EmptyDirectoryNode.php.
getName()
getName ()
Returns
string
Definition at line 59 of file EmptyDirectoryNode.php.
getParent()
getParent ()
Returns
string
Definition at line 79 of file EmptyDirectoryNode.php.
getStorage()
getStorage ()
Returns
EmptyDirectoryNode
Definition at line 95 of file EmptyDirectoryNode.php.
References EmptyDirectoryNode\getStorage().
Referenced by ReadMeFactory\generateReadMe(), and EmptyDirectoryNode\getStorage().
getStorageId()
getStorageId ()
Returns
string
Definition at line 103 of file EmptyDirectoryNode.php.
getUpdated()
getUpdated ()
Returns
DateTimeInterface
Definition at line 111 of file EmptyDirectoryNode.php.
Referenced by InMemoryFileNode\__construct().
setName()
setName (string $name)
Parameters
string $name
Returns
InMemoryFileNode
Definition at line 69 of file EmptyDirectoryNode.php.
setUpdated()
setUpdated (DateTimeInterface $updated)
Parameters
DateTimeInterface $updated
Returns
InMemoryFileNode $this.
Definition at line 121 of file EmptyDirectoryNode.php.
Referenced by InMemoryFileNode\__construct().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Storage/Database/EmptyDirectoryNode.php