CamerataDB: OpenDocumentFiller Class Reference
OpenDocumentFiller Class Reference
Autofill for Libre-/Openoffice documents.
Public Member Functions
__construct (ConfigService $configService, UserStorage $userStorage, TemplateService $templateService, OpenDocumentFillerBackend $backend, AnyToPdf $anyToPdf,)
ffill (File $templateFile, array $templateData=[], array $blocks=[], bool $asPdf=false)
Fill the given template file which must exist in the cloud file-system with the given template-data.
fill (string $templateFileName, array $templateData=[], array $blocks=[], bool $asPdf=false)
Fill the given template file which must exist in the cloud file-system with the given template-data.
fillData (array $templateData)
Return the data which would be filled into the template.
Private Member Functions
fillInternal (File $templateFile, string $templateFileName, array $templateData, array $blocks, bool $asPdf)
Private Attributes
$backend
$userStorage
$templateService
$anyToPdf
$cache = []
A cache of documents filled in this run.
Detailed Description
Autofill for Libre-/Openoffice documents.
Definition at line 44 of file OpenDocumentFiller.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, UserStorage $userStorage, TemplateService $templateService, OpenDocumentFillerBackend $backend, AnyToPdf $anyToPdf)
Definition at line 68 of file OpenDocumentFiller.php.
Member Function Documentation
ffill()
ffill (File $templateFile, array $templateData = [], array $blocks = [], bool $asPdf = false)
Fill the given template file which must exist in the cloud file-system with the given template-data.
Parameters
File $templateFile Name of the template file in the user-storage of the current user.
array $templateData The template-data to substitute.
array $blocks Block definitions where NAME => 'A.B.C' defines a pointer into $templateData['A']['B']['C'] available under the name NAME.
bool $asPdf
Returns
array ``` [ FILE_DATA, MIME_TYPE, FILE_NAME ] ```.
Definition at line 113 of file OpenDocumentFiller.php.
References OpenDocumentFiller\fillInternal().
fill()
fill (string $templateFileName, array $templateData = [], array $blocks = [], bool $asPdf = false)
Fill the given template file which must exist in the cloud file-system with the given template-data.
Parameters
string $templateFileName Name of the template file in the user-storage of the current user.
array $templateData The template-data to substitute.
array $blocks Block definitions where NAME => 'A.B.C' defines a pointer into $templateData['A']['B']['C'] available under the name NAME.
bool $asPdf
Returns
array ``` [ FILE_DATA, MIME_TYPE, FILE_NAME ] ```.
Definition at line 140 of file OpenDocumentFiller.php.
References OpenDocumentFiller\fillInternal().
fillData()
fillData (array $templateData)
Return the data which would be filled into the template.
This is a merge of the $templateData with a couple of orchestra things.
Parameters
array $templateData The given template data to augment.
Returns
array A merge of $templateData with global information like orchestra address, logs etc.
Definition at line 287 of file OpenDocumentFiller.php.
Referenced by OpenDocumentFiller\fillInternal().
fillInternal()
fillInternal (File $templateFile, string $templateFileName, array $templateData, array $blocks, bool $asPdf) private
Parameters
File $templateFile Name of the template file in the user-storage of the current user.
string $templateFileName
array $templateData The template-data to substitute.
array $blocks Block definitions where NAME => 'A.B.C' defines a pointer into $templateData['A']['B']['C'] available under the name NAME.
bool $asPdf
Returns
array ``` [ FILE_DATA, MIME_TYPE, FILE_NAME ] ```.
Definition at line 169 of file OpenDocumentFiller.php.
References OpenDocumentFiller\fillData().
Referenced by OpenDocumentFiller\ffill(), and OpenDocumentFiller\fill().
Field Documentation
$anyToPdf
AnyToPdf $anyToPdf private
Definition at line 58 of file OpenDocumentFiller.php.
$backend
OpenDocumentFillerBackend $backend private
Definition at line 49 of file OpenDocumentFiller.php.
$cache
array $cache = [] private
A cache of documents filled in this run.
Just for the current session.
Definition at line 65 of file OpenDocumentFiller.php.
$templateService
TemplateService $templateService private
Definition at line 55 of file OpenDocumentFiller.php.
$userStorage
UserStorage $userStorage private
Definition at line 52 of file OpenDocumentFiller.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Documents/OpenDocumentFiller.php