CamerataDB: MimeTypeService Class Reference
MimeTypeService Class Reference
Tweak the Nextcloud server to support all MIME-types needed by this app.
Public Member Functions
__construct (private IMimeTypeDetector $mimeTypeDetector, protected LoggerInterface $logger,)
setAppPath (string $appPath)
Configure the base directory containing the data files below $appPath/config/nextcloud/.
registerMimeTypeMappings ()
Register the needed extension to MIME-type mappings with the Nextcloud server.
getSupportedArchiveMimeTypes ()
Data Fields
const MIME_TYPE_MAPPING_DATA_FILE = 'config/nextcloud/mimetypemapping.json'
const MIME_TYPE_ALIASES_DATA_FILE = 'config/nextcloud/mimetypealiases.json'
Private Member Functions
getMimeTypeMapping ()
Private Attributes
$supportedMimeTypes = null
$mimeTypeMapping = null
$appPath
Detailed Description
Tweak the Nextcloud server to support all MIME-types needed by this app.
Definition at line 35 of file MimeTypeService.php.
Constructor & Destructor Documentation
__construct()
__construct (private IMimeTypeDetector $mimeTypeDetector, protected LoggerInterface $logger)
Definition at line 52 of file MimeTypeService.php.
Member Function Documentation
getMimeTypeMapping()
getMimeTypeMapping () private
Returns
array Slurp in and cache the extension to mime-type mapping.
Definition at line 135 of file MimeTypeService.php.
References OCA\CAFEVDB\Toolkit\Traits\logException(), and OCA\CAFEVDB\Toolkit\Traits\logInfo().
Referenced by MimeTypeService\getSupportedArchiveMimeTypes(), and MimeTypeService\registerMimeTypeMappings().
getSupportedArchiveMimeTypes()
getSupportedArchiveMimeTypes ()
Returns
array<string, string> An array EXT => MIME of the supported archive MIME-types. That is, the cloud must know the mime type and the archive backend must support it in order to have an extension and mime-type added to the list.
Definition at line 106 of file MimeTypeService.php.
References MimeTypeService\getMimeTypeMapping(), OCA\CAFEVDB\Toolkit\Traits\logError(), OCA\CAFEVDB\Toolkit\Traits\logInfo(), and OCA\CAFEVDB\Toolkit\Traits\logWarn().
registerMimeTypeMappings()
registerMimeTypeMappings ()
Register the needed extension to MIME-type mappings with the Nextcloud server.
Returns
void
Bug
This function uses internal APIs.
Definition at line 84 of file MimeTypeService.php.
References MimeTypeService\getMimeTypeMapping().
setAppPath()
setAppPath (string $appPath)
Configure the base directory containing the data files below $appPath/config/nextcloud/.
So this is actually just the configuration prefix directory, typically the base-dir of the consuming app.
Parameters
string $appPath
Returns
MimeTypeService $this for chaining.
Definition at line 68 of file MimeTypeService.php.
Field Documentation
$appPath
string $appPath private
Definition at line 49 of file MimeTypeService.php.
$mimeTypeMapping
array< string, string > $mimeTypeMapping = null private
Definition at line 46 of file MimeTypeService.php.
$supportedMimeTypes
array $supportedMimeTypes = null private
Definition at line 43 of file MimeTypeService.php.
MIME_TYPE_ALIASES_DATA_FILE
const MIME_TYPE_ALIASES_DATA_FILE = 'config/nextcloud/mimetypealiases.json'
Definition at line 40 of file MimeTypeService.php.
MIME_TYPE_MAPPING_DATA_FILE
const MIME_TYPE_MAPPING_DATA_FILE = 'config/nextcloud/mimetypemapping.json'
Definition at line 39 of file MimeTypeService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Toolkit/Service/MimeTypeService.php