CamerataDB: RecipientsFilter Class Reference
RecipientsFilter Class Reference
Wrap the email filter form into a class to make things a little less crowded.
Public Member Functions
__construct (ConfigService $configService, ISession $session, RequestParameterService $parameterService, EntityManager $entityManager, PHPMyEdit $pme,)
{}
bind (RequestParameterService $parameterService)
setUserBase (int $userBase)
Programmatically set the user base, e.g.
formData ()
filterHistory ()
memberStatusFilter ()
getUserBase ()
basicRecipientsSet ()
recipientsFromProject ()
recipientsFromProjectAll ()
recipientsFromProjectPreliminary ()
recipientsFromProjectConfirmed ()
recipientsExceptProject ()
announcementsMailingList ()
projectMailingList ()
instrumentsFilter ()
emailRecipientsChoices ()
missingEmailAddresses ()
initialState ()
reloadState ()
snapshotState ()
selectedRecipients (?int $userBase=null)
setSelectedRecipients (array $recipients)
Set the given array of musician ids as selected recipients.
frozenRecipients ()
getProject ()
substituteAnnouncementsMailingList (array &$selectedRecipients)
Substitute the recipients by the announcements mailing list if possible.
Static Public Member Functions
static getUserBaseDescriptions (IL10N $l)
Data Fields
const POST_TAG = 'emailRecipients'
const MEMBER_STATUS_OPEN = 'open'
const BASIC_RECIPIENTS_SET_KEY = 'basicRecipientsSet'
const FROM_PROJECT_CONFIRMED_KEY = 'fromProjectConfirmed'
const FROM_PROJECT_PRELIMINARY_KEY = 'fromProjectPreliminary'
const EXCEPT_PROJECT_KEY = 'exceptProject'
const ANNOUNCEMENTS_MAILING_LIST_KEY = ConfigService::ANNOUNCEMENTS_MAILING_LIST_FQDN_NAME
const PROJECT_MAILING_LIST_KEY = 'projectMailingList'
const MUSICIANS_FROM_PROJECT_PRELIMINARY = (1 << 0)
const MUSICIANS_FROM_PROJECT_CONFIRMED = (1 << 1)
const MUSICIANS_FROM_PROJECT = self::MUSICIANS_FROM_PROJECT_CONFIRMED|self::MUSICIANS_FROM_PROJECT_PRELIMINARY
const MUSICIANS_EXCEPT_PROJECT = (1 << 2)
const ANNOUNCEMENTS_MAILING_LIST = (1 << 3)
const PROJECT_MAILING_LIST = (1 << 4)
const MAILING_LIST = self::ANNOUNCEMENTS_MAILING_LIST|self::PROJECT_MAILING_LIST
const UNDETERMINED_MUSICIANS = 0
const ALL_MUSICIANS = self::MUSICIANS_FROM_PROJECT | self::MUSICIANS_EXCEPT_PROJECT
const DATABASE_MUSICIANS = self::ALL_MUSICIANS
Protected Attributes
$pme
$musiciansRepository
Private Member Functions
execute ()
Parse the CGI stuff and compute the list of selected musicians, either for the initial form setup as during the interaction with the user.
cgiValue (string $key, mixed $default=null)
Fetch a CGI-variable out of the form-select name-space.
setDefaultHistory ()
Compose a default history record for the initial state.
storeHistory ()
Store the history to somewhere, probably the session-data.
loadHistory ()
Load the history from the session data.
validateHistory (mixed $history)
Validate the given history records, return false on error.
validateHistoryRecord (mixed $record)
Validate one history entry.
validateHistoryRecords (array $history)
Validate all history records.
pushHistory (bool $fastMode=false)
Push the current filter selection onto the undo-history stack.
applyHistory (int $offset)
remapEmailRecords ()
This function is called at the very start.
getMusiciansFromDB ()
Fetch the list of musicians for the given context (project/global).
getInstrumentsFromDb ()
Fetch the list of instruments (either only for project or all)
fetchInstrumentsFilter ()
Fetch the instruments filter from the CGI parameters.
defaultByStatus ()
getMemberStatusNames ()
Fill $this->memberStatusNames with values.
initMemberStatusFilter ()
Get the current filter.
memberStatusBlackList ()
defaultUserBase ()
The default user base.
determineUserBase ()
Decode the check-boxes which select the set of users we consider basically.
Private Attributes
const MAX_HISTORY_SIZE = 100
const SESSION_HISTORY_KEY = 'filterHistory'
const HISTORY_KEYS
const MUSICIAN_KEY
$projectId
< recipient set flag values by key
$project
project corresponding to $projectId or null.
$instrumentsFilter
$userBase
$memberFilter
$emailRecs
$emailKey
array $mailingListInfo = []
The mailing-list information as returned from the lists-server, cached for the running request.
$bulkTransaction
$bulkTransactionId
$instruments
$instrumentGroups
$brokenEMails
$eMails
$eMailsDpy
$frozen
$memberStatusNames
$cgiData
$submitted
$reload
$snapshot
$jsonFlags
$filterHistory
$historyPosition
$historySize
$session
$parameterService
Detailed Description
Wrap the email filter form into a class to make things a little less crowded.
This is actually not to filter emails, but rather to select specific groups of musicians (depending on instrument and project).
Definition at line 51 of file RecipientsFilter.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ISession $session, RequestParameterService $parameterService, EntityManager $entityManager, PHPMyEdit $pme)
{}
Definition at line 181 of file RecipientsFilter.php.
References RecipientsFilter\bind().
Member Function Documentation
announcementsMailingList()
announcementsMailingList ()
Returns
Whether only to use the announcements mailing list.
Definition at line 1086 of file RecipientsFilter.php.
Referenced by RecipientsFilter\substituteAnnouncementsMailingList().
applyHistory()
applyHistory (int $offset) private
Parameters
int $offset Relative move inside the history. The function will throw an exception if emailform-debuggin is enabled and the requested action would leave the history stack.
Returns
void
Definition at line 523 of file RecipientsFilter.php.
References RecipientsFilter\filterHistory().
Referenced by RecipientsFilter\execute().
basicRecipientsSet()
basicRecipientsSet ()
Returns
array The user basic set for the email form template
Definition at line 1044 of file RecipientsFilter.php.
Referenced by RecipientsFilter\setDefaultHistory().
bind()
bind (RequestParameterService $parameterService)
Parameters
RequestParameterService $parameterService Bind self to the given request parameters.
Returns
void
Definition at line 207 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), RecipientsFilter\execute(), and RequestParameterService\getParam().
Referenced by RecipientsFilter\__construct().
cgiValue()
cgiValue (string $key, mixed $default = null) private
Fetch a CGI-variable out of the form-select name-space.
Parameters
string $key The pareter key to query.
mixed $default The default value.
Returns
mixed
Definition at line 329 of file RecipientsFilter.php.
Referenced by RecipientsFilter\bind(), RecipientsFilter\determineUserBase(), RecipientsFilter\emailRecipientsChoices(), RecipientsFilter\execute(), RecipientsFilter\fetchInstrumentsFilter(), RecipientsFilter\initMemberStatusFilter(), RecipientsFilter\instrumentsFilter(), RecipientsFilter\memberStatusFilter(), RecipientsFilter\pushHistory(), and RecipientsFilter\selectedRecipients().
defaultByStatus()
defaultByStatus () private
Returns
array The default by-member-status filter as positive list.
Definition at line 785 of file RecipientsFilter.php.
Referenced by RecipientsFilter\initMemberStatusFilter(), RecipientsFilter\memberStatusFilter(), RecipientsFilter\setDefaultHistory(), and RecipientsFilter\substituteAnnouncementsMailingList().
defaultUserBase()
defaultUserBase () private
The default user base.
Simple, but just keep the scheme in sync with the other two filters and provide a default....() function.
Returns
int Or-combined flag values.
Definition at line 845 of file RecipientsFilter.php.
References RecipientsFilter\frozenRecipients().
Referenced by RecipientsFilter\determineUserBase().
determineUserBase()
determineUserBase () private
Decode the check-boxes which select the set of users we consider basically.
Returns
void
Definition at line 900 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), and RecipientsFilter\defaultUserBase().
Referenced by RecipientsFilter\execute(), and RecipientsFilter\setUserBase().
emailRecipientsChoices()
emailRecipientsChoices ()
Returns
array The option descriptions for the recipient select box.
Definition at line 1124 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue().
Referenced by RecipientsFilter\substituteAnnouncementsMailingList().
execute()
execute () private
Parse the CGI stuff and compute the list of selected musicians, either for the initial form setup as during the interaction with the user.
Returns
void
Definition at line 260 of file RecipientsFilter.php.
References RecipientsFilter\applyHistory(), RecipientsFilter\cgiValue(), RecipientsFilter\determineUserBase(), RecipientsFilter\fetchInstrumentsFilter(), RecipientsFilter\getMemberStatusNames(), RecipientsFilter\getMusiciansFromDB(), RecipientsFilter\initMemberStatusFilter(), RecipientsFilter\loadHistory(), RecipientsFilter\pushHistory(), RecipientsFilter\remapEmailRecords(), RecipientsFilter\setDefaultHistory(), and RecipientsFilter\storeHistory().
Referenced by RecipientsFilter\bind().
fetchInstrumentsFilter()
fetchInstrumentsFilter () private
Fetch the instruments filter from the CGI parameters.
Returns
void
Definition at line 771 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), and RecipientsFilter\instrumentsFilter().
Referenced by RecipientsFilter\execute().
filterHistory()
filterHistory ()
Returns
array The current filter history and the filter position as JSON encoded string.
Definition at line 1003 of file RecipientsFilter.php.
References RecipientsFilter\filterHistory().
Referenced by RecipientsFilter\applyHistory(), RecipientsFilter\filterHistory(), RecipientsFilter\loadHistory(), RecipientsFilter\pushHistory(), and RecipientsFilter\setDefaultHistory().
formData()
formData ()
Returns
array An array of values we want to maintain on form-submit, intentionally for wrapping into hidden input fields.
Definition at line 989 of file RecipientsFilter.php.
frozenRecipients()
frozenRecipients ()
Returns
bool \true if the list of recipients is frozen, i.e. restricted to the pre-selected recipients.
Definition at line 1246 of file RecipientsFilter.php.
Referenced by RecipientsFilter\defaultUserBase().
getInstrumentsFromDb()
getInstrumentsFromDb () private
Fetch the list of instruments (either only for project or all)
Also: construct the filter by instrument.
Returns
void
Definition at line 746 of file RecipientsFilter.php.
getMemberStatusNames()
getMemberStatusNames () private
Fill $this->memberStatusNames with values.
Returns
void
Definition at line 806 of file RecipientsFilter.php.
Referenced by RecipientsFilter\execute().
getMusiciansFromDB()
getMusiciansFromDB () private
Fetch the list of musicians for the given context (project/global).
Returns
void
Definition at line 677 of file RecipientsFilter.php.
References RecipientsFilter\$projectId.
Referenced by RecipientsFilter\execute().
getProject()
getProject ()
Returns
null|Entities\Project Return the associated project entity if in project mode
Definition at line 1252 of file RecipientsFilter.php.
References RecipientsFilter\$project.
getUserBase()
getUserBase ()
Returns
int The currently set user-base.
See also
basicRecipientsSet()
Definition at line 1038 of file RecipientsFilter.php.
getUserBaseDescriptions()
static getUserBaseDescriptions (IL10N $l) static
Parameters
IL10N $l
Returns
array Translated descriptions of the user base options.
Definition at line 934 of file RecipientsFilter.php.
initialState()
initialState ()
Returns
bool Return true if in initial state.
Definition at line 1161 of file RecipientsFilter.php.
initMemberStatusFilter()
initMemberStatusFilter () private
Get the current filter.
Default value, after form submission, initial setting otherwise.
Returns
void
Definition at line 822 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), and RecipientsFilter\defaultByStatus().
Referenced by RecipientsFilter\execute().
instrumentsFilter()
instrumentsFilter ()
Returns
array The values for the instruments filter.
Definition at line 1100 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue().
Referenced by RecipientsFilter\fetchInstrumentsFilter(), and RecipientsFilter\substituteAnnouncementsMailingList().
loadHistory()
loadHistory () private
Load the history from the session data.
Returns
bool Execution status.
Definition at line 390 of file RecipientsFilter.php.
References RecipientsFilter\filterHistory(), RecipientsFilter\setDefaultHistory(), and RecipientsFilter\validateHistory().
Referenced by RecipientsFilter\execute().
memberStatusBlackList()
memberStatusBlackList () private
Returns
array Form a SQL filter expression for the member status.
Definition at line 831 of file RecipientsFilter.php.
memberStatusFilter()
memberStatusFilter ()
Returns
The current value of the member status filter or its initial value.
Definition at line 1015 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), and RecipientsFilter\defaultByStatus().
missingEmailAddresses()
missingEmailAddresses ()
Returns
array A list of musicians without email address, if any.
Definition at line 1149 of file RecipientsFilter.php.
projectMailingList()
projectMailingList ()
Returns
Whether only to use the respective project mailing list.
Definition at line 1092 of file RecipientsFilter.php.
pushHistory()
pushHistory (bool $fastMode = false) private
Push the current filter selection onto the undo-history stack.
Do nothing for dummy commits, i.e. only a changed filter will be pushed onto the stack.
Parameters
bool $fastMode If true omit normalization attempts.
Returns
void
Definition at line 471 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue(), and RecipientsFilter\filterHistory().
Referenced by RecipientsFilter\execute().
recipientsExceptProject()
recipientsExceptProject ()
Returns
Whether only to select from non-participants.
Definition at line 1080 of file RecipientsFilter.php.
recipientsFromProject()
recipientsFromProject ()
Returns
Whether recipients from the project are selected.
Definition at line 1056 of file RecipientsFilter.php.
recipientsFromProjectAll()
recipientsFromProjectAll ()
Returns
Whether all recipients from the project are selected.
Definition at line 1062 of file RecipientsFilter.php.
recipientsFromProjectConfirmed()
recipientsFromProjectConfirmed ()
Returns
Whether only to select from the confirmed participants.
Definition at line 1074 of file RecipientsFilter.php.
recipientsFromProjectPreliminary()
recipientsFromProjectPreliminary ()
Returns
Whether only to select from the preliminary participants.
Definition at line 1068 of file RecipientsFilter.php.
reloadState()
reloadState ()
Returns
bool Return true if in reload state
Definition at line 1167 of file RecipientsFilter.php.
remapEmailRecords()
remapEmailRecords () private
This function is called at the very start.
For special purpose emails this function forms the list of recipients.
Returns
void
Definition at line 554 of file RecipientsFilter.php.
Referenced by RecipientsFilter\execute().
selectedRecipients()
selectedRecipients (?int $userBase = null)
Parameters
null | int $userBase Optional different user base. If unset $this->userBase is used.
Returns
The list of selected recipients. To have this method is in principle the goal of all the mess above ...
Definition at line 1185 of file RecipientsFilter.php.
References RecipientsFilter\cgiValue().
Referenced by RecipientsFilter\substituteAnnouncementsMailingList().
setDefaultHistory()
setDefaultHistory () private
Compose a default history record for the initial state.
Returns
void
Definition at line 347 of file RecipientsFilter.php.
References RecipientsFilter\basicRecipientsSet(), RecipientsFilter\defaultByStatus(), and RecipientsFilter\filterHistory().
Referenced by RecipientsFilter\execute(), and RecipientsFilter\loadHistory().
setSelectedRecipients()
setSelectedRecipients (array $recipients)
Set the given array of musician ids as selected recipients.
Parameters
array $recipients Replacement recipients.
Returns
void
Definition at line 1236 of file RecipientsFilter.php.
setUserBase()
setUserBase (int $userBase)
Programmatically set the user base, e.g.
to force sending to the mailing list.
Parameters
int $userBase User-base flags.
Returns
void
Definition at line 872 of file RecipientsFilter.php.
References RecipientsFilter\determineUserBase().
snapshotState()
snapshotState ()
Returns
\true when doing a mere history snapshot.
Definition at line 1173 of file RecipientsFilter.php.
storeHistory()
storeHistory () private
Store the history to somewhere, probably the session-data.
Returns
void
Definition at line 375 of file RecipientsFilter.php.
Referenced by RecipientsFilter\execute().
substituteAnnouncementsMailingList()
substituteAnnouncementsMailingList (array & $selectedRecipients)
Substitute the recipients by the announcements mailing list if possible.
The composer does this if the email does not contain personal substitutions.
Parameters
array $selectedRecipients Recipients-set in the form returned by RecipientsFilter::selectedRecipients().
Returns
bool \true if the recipients list has been altered, \false if it has been left as is.
Definition at line 1310 of file RecipientsFilter.php.
References RecipientsFilter\announcementsMailingList(), RecipientsFilter\defaultByStatus(), RecipientsFilter\emailRecipientsChoices(), RecipientsFilter\instrumentsFilter(), and RecipientsFilter\selectedRecipients().
validateHistory()
validateHistory (mixed $history) private
Validate the given history records, return false on error.
Parameters
bool | array $history The history to validate.
Returns
bool Validation result.
Definition at line 411 of file RecipientsFilter.php.
References RecipientsFilter\validateHistoryRecords().
Referenced by RecipientsFilter\loadHistory().
validateHistoryRecord()
validateHistoryRecord (mixed $record) private
Validate one history entry.
Parameters
mixed $record The history record. Intentionally an array.
Returns
bool Validation result.
Definition at line 430 of file RecipientsFilter.php.
Referenced by RecipientsFilter\validateHistoryRecords().
validateHistoryRecords()
validateHistoryRecords (array $history) private
Validate all history records.
Parameters
array $history The filter history.
Returns
bool Validation result.
Definition at line 452 of file RecipientsFilter.php.
References RecipientsFilter\validateHistoryRecord().
Referenced by RecipientsFilter\validateHistory().
Field Documentation
$brokenEMails
$brokenEMails private
Definition at line 150 of file RecipientsFilter.php.
$bulkTransaction
Entities SepaBulkTransaction $bulkTransaction private
Definition at line 142 of file RecipientsFilter.php.
$bulkTransactionId
int $bulkTransactionId private
Definition at line 145 of file RecipientsFilter.php.
$cgiData
$cgiData private
Definition at line 158 of file RecipientsFilter.php.
$emailKey
$emailKey private
Definition at line 131 of file RecipientsFilter.php.
$emailRecs
$emailRecs private
Definition at line 130 of file RecipientsFilter.php.
$eMails
$eMails private
Definition at line 151 of file RecipientsFilter.php.
$eMailsDpy
$eMailsDpy private
Definition at line 152 of file RecipientsFilter.php.
$filterHistory
$filterHistory private
Definition at line 164 of file RecipientsFilter.php.
$frozen
$frozen private
Definition at line 153 of file RecipientsFilter.php.
$historyPosition
$historyPosition private
Definition at line 165 of file RecipientsFilter.php.
$historySize
$historySize private
Definition at line 166 of file RecipientsFilter.php.
$instrumentGroups
$instrumentGroups private
Definition at line 148 of file RecipientsFilter.php.
$instruments
$instruments private
Definition at line 147 of file RecipientsFilter.php.
$instrumentsFilter
$instrumentsFilter private
Definition at line 126 of file RecipientsFilter.php.
$jsonFlags
$jsonFlags private
Definition at line 163 of file RecipientsFilter.php.
$mailingListInfo
array $mailingListInfo = [] private
The mailing-list information as returned from the lists-server, cached for the running request.
Definition at line 139 of file RecipientsFilter.php.
$memberFilter
$memberFilter private
Definition at line 129 of file RecipientsFilter.php.
$memberStatusNames
$memberStatusNames private
Definition at line 156 of file RecipientsFilter.php.
$musiciansRepository
Repositories MusiciansRepository $musiciansRepository protected
Definition at line 178 of file RecipientsFilter.php.
$parameterService
RequestParameterService $parameterService private
Definition at line 172 of file RecipientsFilter.php.
$pme
PHPMyEdit $pme protected
Definition at line 175 of file RecipientsFilter.php.
$project
Entities Project $project private
project corresponding to $projectId or null.
Definition at line 124 of file RecipientsFilter.php.
Referenced by RecipientsFilter\getProject().
$projectId
int $projectId private
< recipient set flag values by key
project-id, no project if <= 0
Definition at line 117 of file RecipientsFilter.php.
Referenced by RecipientsFilter\getMusiciansFromDB().
$reload
$reload private
Definition at line 160 of file RecipientsFilter.php.
$session
ISession $session private
Definition at line 169 of file RecipientsFilter.php.
$snapshot
$snapshot private
Definition at line 161 of file RecipientsFilter.php.
$submitted
$submitted private
Definition at line 159 of file RecipientsFilter.php.
$userBase
$userBase private
Definition at line 127 of file RecipientsFilter.php.
ALL_MUSICIANS
const ALL_MUSICIANS = self::MUSICIANS_FROM_PROJECT | self::MUSICIANS_EXCEPT_PROJECT
Definition at line 76 of file RecipientsFilter.php.
ANNOUNCEMENTS_MAILING_LIST
const ANNOUNCEMENTS_MAILING_LIST = (1 << 3)
Definition at line 72 of file RecipientsFilter.php.
ANNOUNCEMENTS_MAILING_LIST_KEY
const ANNOUNCEMENTS_MAILING_LIST_KEY = ConfigService::ANNOUNCEMENTS_MAILING_LIST_FQDN_NAME
Definition at line 65 of file RecipientsFilter.php.
BASIC_RECIPIENTS_SET_KEY
const BASIC_RECIPIENTS_SET_KEY = 'basicRecipientsSet'
Definition at line 61 of file RecipientsFilter.php.
DATABASE_MUSICIANS
const DATABASE_MUSICIANS = self::ALL_MUSICIANS
Definition at line 77 of file RecipientsFilter.php.
EXCEPT_PROJECT_KEY
const EXCEPT_PROJECT_KEY = 'exceptProject'
Definition at line 64 of file RecipientsFilter.php.
FROM_PROJECT_CONFIRMED_KEY
const FROM_PROJECT_CONFIRMED_KEY = 'fromProjectConfirmed'
Definition at line 62 of file RecipientsFilter.php.
FROM_PROJECT_PRELIMINARY_KEY
const FROM_PROJECT_PRELIMINARY_KEY = 'fromProjectPreliminary'
Definition at line 63 of file RecipientsFilter.php.
HISTORY_KEYS
const HISTORY_KEYS private
Initial value:
= [
    self::BASIC_RECIPIENTS_SET_KEY,
    'memberStatusFilter',
    'instrumentsFilter',
    'selectedRecipients'
  ]
Definition at line 99 of file RecipientsFilter.php.
MAILING_LIST
const MAILING_LIST = self::ANNOUNCEMENTS_MAILING_LIST|self::PROJECT_MAILING_LIST
Definition at line 74 of file RecipientsFilter.php.
MAX_HISTORY_SIZE
const MAX_HISTORY_SIZE = 100 private
Definition at line 97 of file RecipientsFilter.php.
MEMBER_STATUS_OPEN
const MEMBER_STATUS_OPEN = 'open'
Definition at line 59 of file RecipientsFilter.php.
MUSICIAN_KEY
const MUSICIAN_KEY private
Initial value:
= [
    'Musicians' => 'id',
    'ProjectParticipants' => 'musician_id',
    'InstrumentInsurances' => 'bill_to_party_id',
  ]
Definition at line 107 of file RecipientsFilter.php.
MUSICIANS_EXCEPT_PROJECT
const MUSICIANS_EXCEPT_PROJECT = (1 << 2)
Definition at line 71 of file RecipientsFilter.php.
MUSICIANS_FROM_PROJECT
const MUSICIANS_FROM_PROJECT = self::MUSICIANS_FROM_PROJECT_CONFIRMED|self::MUSICIANS_FROM_PROJECT_PRELIMINARY
Definition at line 70 of file RecipientsFilter.php.
MUSICIANS_FROM_PROJECT_CONFIRMED
const MUSICIANS_FROM_PROJECT_CONFIRMED = (1 << 1)
Definition at line 69 of file RecipientsFilter.php.
MUSICIANS_FROM_PROJECT_PRELIMINARY
const MUSICIANS_FROM_PROJECT_PRELIMINARY = (1 << 0)
Definition at line 68 of file RecipientsFilter.php.
POST_TAG
const POST_TAG = 'emailRecipients'
Definition at line 57 of file RecipientsFilter.php.
PROJECT_MAILING_LIST
const PROJECT_MAILING_LIST = (1 << 4)
Definition at line 73 of file RecipientsFilter.php.
PROJECT_MAILING_LIST_KEY
const PROJECT_MAILING_LIST_KEY = 'projectMailingList'
Definition at line 66 of file RecipientsFilter.php.
SESSION_HISTORY_KEY
const SESSION_HISTORY_KEY = 'filterHistory' private
Definition at line 98 of file RecipientsFilter.php.
UNDETERMINED_MUSICIANS
const UNDETERMINED_MUSICIANS = 0
Definition at line 75 of file RecipientsFilter.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/EmailForm/RecipientsFilter.php