CamerataDB: Util Class Reference
Util Class Reference
General static utility routines.
Static Public Member Functions
static fileExtensionFromMimeType (string $mimeType)
static arrayMergeRecursive (array ... $arrays)
Merge $arrays recursively where later arguments in the list override the values of previous arguments and numeric keys are just appended.
static arrayMapAssoc (callable $callback, array $a)
Array-map including keys.
static normalizeSpaces (?string $name, string $singleSpace=' ', bool $stripLinebreaks=false)
Normalize spaces and commas after and before spaces.
static removeSpaces (?string $name)
Remove all whitespace.
static htmlEscape (?string $string, mixed $ent=null, bool $doubleEncode=false)
Wrapper around htmlspecialchars(); avoid double encoding, standard options, UTF-8 for stone-age PHP versions.
static htmlToMarkDown (?string $html)
Convert the given HTML string to markdown.
static arraySliceKeys (mixed $array, mixed $keys=null)
static explode (string $delim, ?string $string, int $flags=self::OMIT_EMPTY_FIELDS|self::ESCAPED, string $escape='\\')
A preg_explode() wrapper with some extra features.
static implode (string $delim, array $array, int $flags=self::ESCAPED, string $escape='\\')
Counter-part to self::explode().
static escapeDelimiter ($value, string $delim, string $escape='\\')
Escape delimiters in the given value.
static unescapeDelimiter ($value, string $delim, string $escape='\\')
Un-escape delimiters in the given value.
static explodeIndexed (?string $data, mixed $default=null, string $delimiter=',', string $keyDelimiter=':', string $escapeChar='\\')
Explode a string of the form.
static explodeIndexedMulti (?string $data, mixed $default=null, string $delimiter=',', string $keyDelimiter=':')
Explode a string of the form.
static implodeIndexedMulti (?array $data, string $delimiter=',', string $keyDelimiter=':')
Undo self::explodeIndexedMulti().
static maxUploadSize (string $target='temporary')
Return the maximum upload file size.
static humanFileSize (int $bytes, ?string $locale=null, bool $binary=true, int $digits=2)
Locale-aware "human readable" file-size.
static strftime (string $format, ?int $timestamp=null, ?string $tz=null, ?string $locale=null)
Format the right way (tm).
static dashesToCamelCase (?string $string, bool $capitalizeFirstCharacter=false, string $dashes='_-')
Take any dashed or "underscored" lower-case string and convert to camel-case.
static camelCaseToDashes (string $string, string $separator='-')
Take an camel-case string and convert to lower-case with dashes or underscores between the words.
static shortenCamelCaseString (string $string, int $limit, int $minLen=2)
Shorten the given string by iteratively reducing the size of its camel-case components until it fits into the given length.
static hexDump (string $string, ?array $options=null)
Dumps a string into a traditional hex dump for programmers, in a format similar to the output of the BSD command hexdump -C file.
static unsetValue (array &$hayStack, mixed $value)
Unset all array elements with value $value.
static dateTime ($arg1="now", $arg2=null, $arg3=null)
Quick and dirty convenience function which combines "constructors" into a single function.
static transposeArray (array $files)
Turn a php $_FILES array of the form.
static fileUploadError (int $code, IL10N $l)
Decode an file-upload error into some "readable" error string.
Data Fields
const OMIT_EMPTY_FIELDS = 1
const TRIM = 2
const ESCAPED = 4
const FILE_EXTENSIONS_BY_MIME_TYPE
Static Private Member Functions
static arrayMergeTwoRecursive (array $dest, array $override)
Inner work-horse for arrayMergeRecursive.
Static Private Attributes
static $markDownConverter
Detailed Description
General static utility routines.
Definition at line 37 of file Util.php.
Member Function Documentation
arrayMapAssoc()
static arrayMapAssoc (callable $callback, array $a) static
Array-map including keys.
Parameters
callable $callback
array $a
Returns
array
Definition at line 131 of file Util.php.
Referenced by ProjectParticipantFields\render().
arrayMergeRecursive()
static arrayMergeRecursive (array ... $arrays) static
Merge $arrays recursively where later arguments in the list override the values of previous arguments and numeric keys are just appended.
Parameters
array ...$arrays
Returns
array
Definition at line 86 of file Util.php.
References Util\arrayMergeTwoRecursive().
Referenced by PMETableViewBase\makeJoinTableField(), InstrumentFamilies\render(), InstrumentInsurances\render(), Instruments\render(), InsuranceBrokers\render(), InsuranceRates\render(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), ProjectParticipants\render(), and SepaBulkTransactions\render().
arrayMergeTwoRecursive()
static arrayMergeTwoRecursive (array $dest, array $override) static private
Inner work-horse for arrayMergeRecursive.
Parameters
array $dest
array $override
Returns
array
Definition at line 108 of file Util.php.
References Util\arrayMergeTwoRecursive().
Referenced by Util\arrayMergeRecursive(), and Util\arrayMergeTwoRecursive().
arraySliceKeys()
static arraySliceKeys (mixed $array, mixed $keys = null) static
Parameters
mixed $array
mixed $keys
Returns
array
Definition at line 231 of file Util.php.
Referenced by PMETableViewBase\debugPrintValues().
camelCaseToDashes()
static camelCaseToDashes (string $string, string $separator = '-') static
Take an camel-case string and convert to lower-case with dashes or underscores between the words.
First letter may or may not be upper case.
Parameters
string $string String to work on.
string $separator Separator to use, defaults to '-'.
Returns
string
Definition at line 580 of file Util.php.
Referenced by Util\shortenCamelCaseString().
dashesToCamelCase()
static dashesToCamelCase (?string $string, bool $capitalizeFirstCharacter = false, string $dashes = '_-') static
Take any dashed or "underscored" lower-case string and convert to camel-case.
Parameters
null | string $string The string to convert.
bool $capitalizeFirstCharacter Self explaining.
string $dashes Characters to replace.
Returns
null|string Return null if $string is null, otherwise the result of the substitutions.
Definition at line 555 of file Util.php.
Referenced by Util\shortenCamelCaseString().
dateTime()
static dateTime ($arg1 = "now", $arg2 = null, $arg3 = null) static
Quick and dirty convenience function which combines "constructors" into a single function.
In particular the case wherer $arg1 is already a date-time object is handled gracefully by either pass-through to the return value or converting it to a \DateTimeImmutable.
Parameters
string | \\DateTimeImmutable | \\DateTime | \\DateTimeInterface $arg1
null | string | \\DateTimeZone $arg2
null | string | \\DateTimeZone $arg3
Returns
DateTimeImmutable TBD.
Definition at line 709 of file Util.php.
escapeDelimiter()
static escapeDelimiter ($value, string $delim, string $escape = '\\') static
Escape delimiters in the given value.
Parameters
string | array $value
string $delim
string $escape
Returns
string|array
Definition at line 317 of file Util.php.
Referenced by Util\implode().
explode()
static explode (string $delim, ?string $string, int $flags = self::OMIT_EMPTY_FIELDS|self::ESCAPED, string $escape = '\\') static
A preg_explode() wrapper with some extra features.
Parameters
string $delim The delimiter string.
null | string $string The string to split.
int $flags Default is self::OMIT_EMPTY_FIELDS|self::ESCAPED
self::OMIT_EMPTY_FIELDS Omit empty fields from the output array
self::TRIM Trim white-space around the delimiter
self::ESCAPED Ignore escaped delimiters and replace escaped delimiters in the output array.. See paramterer $escape.
string $escape The escape character when self::ESCAPED is set.
Returns
array
Definition at line 263 of file Util.php.
References Util\explode(), and Util\unescapeDelimiter().
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), Util\explode(), Util\explodeIndexed(), Util\explodeIndexedMulti(), PMETableViewBase\extractInstrumentRanking(), Util\fileExtensionFromMimeType(), ProjectInstrumentationNumbers\render(), and Util\shortenCamelCaseString().
explodeIndexed()
static explodeIndexed (?string $data, mixed $default = null, string $delimiter = ',', string $keyDelimiter = ':', string $escapeChar = '\\') static
Explode a string of the form.
A:B,C:D,...
into an array of the shape
[
  A => B,
  C => D,
  D => $default,
  ...
]
Only the first $keyDelimiter is taken into account. This means that it is not necessary to explode the key-delimiter.
Parameters
null | string $data
mixed $default
string $delimiter
string $keyDelimiter
string $escapeChar
Returns
array
Definition at line 374 of file Util.php.
References Util\explode().
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), and PMETableViewBase\beforeUpdateDoUpdateAll().
explodeIndexedMulti()
static explodeIndexedMulti (?string $data, mixed $default = null, string $delimiter = ',', string $keyDelimiter = ':') static
Explode a string of the form.
A:B,C:D,E,C:F...
into an array of the shape
[
  A => [ B ],
  C => [ D, F ],
  E => [ $default ],
  ...
]
Parameters
null | string $data
mixed $default
string $delimiter
string $keyDelimiter
Returns
array
Definition at line 416 of file Util.php.
References Util\explode().
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), and PMETableViewBase\beforeUpdateDoUpdateAll().
fileExtensionFromMimeType()
static fileExtensionFromMimeType (string $mimeType) static
Parameters
string $mimeType
Returns
null|string
Definition at line 63 of file Util.php.
References Util\explode().
fileUploadError()
static fileUploadError (int $code, IL10N $l) static
Decode an file-upload error into some "readable" error string.
Parameters
int $code
IL10N $l
Returns
string
Definition at line 789 of file Util.php.
hexDump()
static hexDump (string $string, ?array $options = null) static
Dumps a string into a traditional hex dump for programmers, in a format similar to the output of the BSD command hexdump -C file.
The default result is a string. Supported options:
  line_sep        - line seperator char, default = "\\n"
  bytes_per_line  - default = 16
  pad_char        - character to replace non-readble characters with, default = '.'
Parameters
string $string
null | array $options
Returns
mixed
Definition at line 637 of file Util.php.
References Util\implode().
htmlEscape()
static htmlEscape (?string $string, mixed $ent = null, bool $doubleEncode = false) static
Wrapper around htmlspecialchars(); avoid double encoding, standard options, UTF-8 for stone-age PHP versions.
Parameters
string $string
mixed $ent
bool $doubleEncode
Returns
string
Definition at line 191 of file Util.php.
htmlToMarkDown()
static htmlToMarkDown (?string $html) static
Convert the given HTML string to markdown.
Return null if it is empty.
Parameters
null | string $html Input HTML or null.
Returns
null|string Output markdown or null.
Definition at line 212 of file Util.php.
humanFileSize()
static humanFileSize (int $bytes, ?string $locale = null, bool $binary = true, int $digits = 2) static
Locale-aware "human readable" file-size.
Parameters
int $bytes The raw value in bytes.
null | string $locale Defaults to 'en_US_POSIX'.
bool $binary Use MiB etc. if true, other decimal system.
int $digits
Returns
string
Definition at line 490 of file Util.php.
implode()
static implode (string $delim, array $array, int $flags = self::ESCAPED, string $escape = '\\') static
Counter-part to self::explode().
Parameters
string $delim The delimiter string.
array $array
int $flags Default is self::OMIT_EMPTY_FIELDS|self::ESCAPED
self::OMIT_EMPTY_FIELDS Omit empty fields from the output array
self::TRIM Trim white-space around the delimiter
self::ESCAPED Ignore escaped delimiters and replace escaped delimiters in the output array.. See paramterer $escape.
string $escape The escape character when self::ESCAPED is set.
Returns
string
Definition at line 298 of file Util.php.
References Util\escapeDelimiter(), and Util\implode().
Referenced by Util\hexDump(), Util\implode(), Util\implodeIndexedMulti(), and Util\shortenCamelCaseString().
implodeIndexedMulti()
static implodeIndexedMulti (?array $data, string $delimiter = ',', string $keyDelimiter = ':') static
Undo self::explodeIndexedMulti().
Parameters
null | array $data
string $delimiter
string $keyDelimiter
Returns
string
Definition at line 440 of file Util.php.
References Util\implode().
maxUploadSize()
static maxUploadSize (string $target = 'temporary') static
Return the maximum upload file size.
Parameters
string $target Defaults to 'temporary'. If 'cloud' takes the free space in the cloud FS for the current user into account.
Returns
int
Definition at line 463 of file Util.php.
normalizeSpaces()
static normalizeSpaces (?string $name, string $singleSpace = ' ', bool $stripLinebreaks = false) static
Normalize spaces and commas after and before spaces.
Parameters
null | string $name
string $singleSpace
bool $stripLinebreaks
Returns
null|string
Definition at line 147 of file Util.php.
Referenced by PMETableViewBase\beforeAnythingTrimAnything(), and Util\removeSpaces().
removeSpaces()
static removeSpaces (?string $name) static
Remove all whitespace.
Parameters
null | string $name
Returns
null|string
Definition at line 171 of file Util.php.
References Util\normalizeSpaces().
Referenced by PMETableViewBase\beforeUpdateDoUpdateAll(), and PMETableViewBase\extractInstrumentRanking().
shortenCamelCaseString()
static shortenCamelCaseString (string $string, int $limit, int $minLen = 2) static
Shorten the given string by iteratively reducing the size of its camel-case components until it fits into the given length.
Parameters
string $string The string to shorten.
integer $limit The target length.
integer $minLen Defaults to 2. Components smaller than this will not be shortened. This also means that the target-length may not be reached.
Returns
string
Definition at line 598 of file Util.php.
References Util\camelCaseToDashes(), Util\dashesToCamelCase(), Util\explode(), and Util\implode().
strftime()
static strftime (string $format, ?int $timestamp = null, ?string $tz = null, ?string $locale = null) static
Format the right way (tm).
Parameters
string $format
null | int $timestamp
null | string $tz
null | string $locale
Returns
string|false
Definition at line 524 of file Util.php.
References Util\strftime().
Referenced by Util\strftime().
transposeArray()
static transposeArray (array $files) static
Turn a php $_FILES array of the form.
[
  KEY => [
    IDX => VALUE,
  ],
]
into
[
  IDX => [
    KEY => VALUE,
  ],
]
Parameters
array $files
Returns
array
Definition at line 766 of file Util.php.
unescapeDelimiter()
static unescapeDelimiter ($value, string $delim, string $escape = '\\') static
Un-escape delimiters in the given value.
Parameters
string | array $value
string $delim
string $escape
Returns
string|array
Definition at line 336 of file Util.php.
Referenced by Util\explode().
unsetValue()
static unsetValue (array & $hayStack, mixed $value) static
Unset all array elements with value $value.
Parameters
array $hayStack The array to modify.
mixed $value The value to remove.
Returns
int The number of array slots that have been unset. As the values need not be unique this can be any non-negative integer.
Definition at line 684 of file Util.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), and PMETableViewBase\unsetRequestValue().
Field Documentation
$markDownConverter
$markDownConverter static private
Definition at line 43 of file Util.php.
ESCAPED
const ESCAPED = 4
Definition at line 47 of file Util.php.
FILE_EXTENSIONS_BY_MIME_TYPE
const FILE_EXTENSIONS_BY_MIME_TYPE
Initial value:
= [
    'image/png' => 'png',
    'image/jpeg' => 'jpg',
    'image/gif' => 'gif',
    'image/vnd.microsoft.icon' => 'ico',
    'image/svg+xml' => 'svg',
    'application/pdf' => 'pdf',
  ]
Definition at line 49 of file Util.php.
OMIT_EMPTY_FIELDS
const OMIT_EMPTY_FIELDS = 1
Definition at line 45 of file Util.php.
TRIM
const TRIM = 2
Definition at line 46 of file Util.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/Util.php