CamerataDB: ConfigService Class Reference
ConfigService Class Reference
Configuration do-it-all class.
Public Member Functions
__construct (protected string $appName, protected IAppContainer $appContainer, protected ILogger $logger, protected IL10N $l,)
{}
getAppContainer ()
getTimeFactory ()
getAppConfig ()
getCloudConfig ()
getAppName ()
appPrefix (string $id, string $join='-')
getIcon ()
getUserSession ()
getUserManager ()
getGroupManager ()
getSubAdminManager ()
getUrlGenerator ()
getUser (?string $userId=null)
getUserId ()
setUserId (string $userId)
Install a new user id.
setUser (?IUser $user)
Install a new user.
getL10n ()
getAppL10n ()
getGroupId ()
getGroup (?string $groupId=null)
groupExists ($groupId=null)
inGroup (?string $userId=null, ?string $groupId=null)
isSubAdminOfGroup ($userId=null, $groupId=null)
getGroupSubAdmins (?string $groupId=null)
Return all the sub-admins of the given or the configured orchestra group.
getSubAdminGroupId ()
Return the id of the dedicated admin-group which contains all sub-admins.
getSubAdminGroup ()
Return the dedicated admin-group if it exists.
inSubAdminGroup (?string $userId=null)
Check if the currently logged in or given user-id belongs to the dedicated sub-admin group.
getUserValue (string $key, mixed $default=null, ?string $userId=null)
setUserValue (string $key, mixed $value, ?string $userId=null)
getAppValue (string $key, mixed $default=null)
A short-cut, redirecting to the stock functions for the app.
setAppValue (string $key, mixed $value)
A short-cut, redirecting to the stock functions for the app.
deleteAppValue (string $key)
A short-cut, redirecting to the stock functions for the app.
getEncryptionService ()
setUserEncryptionKey (string $key)
getUserEncryptionKey ()
setAppEncryptionKey (string $key)
getAppEncryptionKey ()
encrypt (?string $value)
decrypt (?string $value)
verifyHash ($value, $hash)
computeHash (string $value)
encryptionKeyValid (?string $encryptionKey)
Check the validity of the encryption key.
getConfigValue (string $key, mixed $default=null, bool $ignoreLock=false)
Get a possibly encrypted config value.
setConfigValue (string $key, mixed $value, bool $ignoreLock=false)
deleteConfigValue (string $key)
Delete the value for the given key.
getAppKeys ()
decryptConfigValues ()
Fetch all config values and decrypt them.
encryptConfigValues (array $override=[])
Flush all configuration values to the database, possibly encrypting them.T his is only meant for use during re-cryption of config value when changing the encryption key.
generateRandomBytes (int $length=30)
Would rather belong to the EncryptionService.
sudo (string $uid, callable $callback)
Fake execution with other user-id.
dateTimeFormatter ()
getDateTimeZone (mixed $timeStamp=false)
Get the current timezone.
getLocale (?string $lang=null)
Return the locale as string, e.g.
getAppLocale ()
Get the configured app locale.
getLanguage (?string $locale=null)
Return the language part of the current or given locale.
getAppLanguage ()
localeCountryNames (?string $displayLocale=null)
localeLanguageNames ($locale=null)
findAvailableLanguages (string $app='core')
findAvailableLocales ()
transliterate (string $string, ?string $locale=null)
Transliterate the given string to the given or default locale.
currencySymbol ($locale=null)
currencyIsoCode ($locale=null)
moneyValue (mixed $value, ?string $locale=null)
Convert $value to a currency value in the given or the user's locale.
floatValue (mixed $value, int $decimals=4, ?string $locale=null)
Convert a float value in the given or default locale.
formatTimeStamp ($date=null, ?string $format=null, ?DateTimeZone $timeZone=null)
Format the given date according to $format and $timeZone to a human readable time-stamp, providing defaults for $format and using the default time-zone if none is specified.
timeStamp (?string $format=null, ?DateTimeZone $timeZone=null)
Call ConfigService::formatTimeStamp() with the current date and time.
Data Fields
const DEBUG_GENERAL = (1 << 0)
const DEBUG_QUERY = (1 << 1)
const DEBUG_CSP = (1 << 2)
const DEBUG_L10N = (1 << 3)
const DEBUG_REQUEST = (1 << 4)
const DEBUG_TOOLTIPS = (1 << 5)
const DEBUG_EMAILFORM = (1 << 6)
const DEBUG_GEOCODING = (1 << 7)
const DEBUG_ALL = self::DEBUG_GENERAL|self::DEBUG_QUERY|self::DEBUG_CSP|self::DEBUG_L10N|self::DEBUG_REQUEST|self::DEBUG_TOOLTIPS|self::DEBUG_EMAILFORM|self::DEBUG_GEOCODING
const DEBUG_NONE = 0
const DEFAULT_LOCALE = 'en_US'
const APP_LOGO = 'logo-greyf.svg'
const SHAREOWNER_KEY = 'shareowner'
const SHAREOWNER_FOLDER_SERVICE_KEY = 'shareowner_folder'
const SHAREOWNER_CALENDAR_SERVICE_KEY = 'shareowner_calendar'
const SHAREOWNER_ADDRESSBOOK_SERVICE_KEY = 'shareowner_addressbook'
const SHARED_FOLDER = 'sharedfolder'
const PROJECTS_FOLDER = 'projectsfolder'
const PROJECT_PARTICIPANTS_FOLDER = 'projectparticipantsfolder'
const PROJECT_POSTERS_FOLDER = 'projectpostersfolder'
const PROJECT_PUBLIC_DOWNLOADS_FOLDER = 'projectpublicdownloadsfolder'
const FINANCE_FOLDER = 'financefolder'
const BALANCES_FOLDER = 'balancesfolder'
const TRANSACTIONS_FOLDER = 'transactionsfolder'
const DOCUMENT_TEMPLATES_FOLDER = 'documenttemplatesfolder'
const POSTBOX_FOLDER = 'postboxfolder'
const OUTBOX_FOLDER = 'outboxfolder'
const PROJECT_SKELETON_FOLDER = 'skeleton'
const PROJECT_PARTICIPANTS_SKELETON_FOLDER = 'forename.surname'
const PROJECT_MANAGEMENT_SKELETON_FOLDER = 'management'
const TAX_OFFICE_IN_TRAY_FOLDER = 'taxOfficeInTrayFolder'
const TAX_EXEMPTION_NOTICE_TEMPLATE = 'taxExcemptionNoticeTemplate'
const CMS_CATEGORIES
const CMS_MODULES
const CMS_TEMPLATES
const WYSIWYG_EDITORS
const CONCERTS_CALENDAR_URI = 'concerts'
const REHEARSALS_CALENDAR_URI = 'rehearsals'
const OTHER_CALENDAR_URI = 'other'
const MANAGEMENT_CALENDAR_URI = 'management'
const FINANCE_CALENDAR_URI = 'finance'
const CALENDARS
const BANK_ACCOUNT_OWNER = 'bankAccountOwner'
const BANK_ACCOUNT_IBAN = 'bankAccountIBAN'
const BANK_ACCOUNT_BLZ = 'bankAccountBLZ'
const BANK_ACCOUNT_BIC = 'bankAccountBIC'
const BANK_ACCOUNT_NAME = 'bankAccountBankName'
const BANK_ACCOUNT_CREDITOR_IDENTIFIER = 'bankAccountCreditorIdentifier'
const BANK_ACCOUNT_BANK_HOLIDAYS = 'bankAccountBankHolidays'
const BANK_ACCOUNT_CONFIG_KEYS
const DOCUMENT_TYPE_CONSTANT = 'constant'
const DOCUMENT_TYPE_TEMPLATE = 'template'
const DOCUMENT_TEMPLATE_LOGO = 'logo'
const DOCUMENT_TEMPLATE_SEAL = 'seal'
const DOCUMENT_TEMPLATE_INSTRUMENT_INSURANCE_RECORD = 'instrumentInsuranceRecord'
const DOCUMENT_TEMPLATE_PROJECT_DEBIT_NOTE_MANDATE = 'projectDebitNoteMandateForm'
const DOCUMENT_TEMPLATE_GENERAL_DEBIT_NOTE_MANDATE = 'generalDebitNoteMandateForm'
const DOCUMENT_TEMPLATE_MEMBER_DATA_UPDATE = 'memberDataUpdateForm'
Protected Attributes
$encryptionCache = []
< Config-key for the announcements mailing list
AppL10N $appL10n
$appLocale
$appLanguage
Private Member Functions
getL10NFactory ()
getSecureRandom ()
Private Attributes
$user
Will be overridden by sudo().
$localeCountryNames = []
IL10NFactory $l10NFactory
IURLGenerator $urlGenerator
ISecureRandom $secureRandom
IUserManager $userManager
IGroupManager $groupManager
ISubAdmin $subAdminManager
EncryptionService $encryptionService
IConfig $cloudConfig
Detailed Description
Configuration do-it-all class.
Todo
This is called on boot without user, determine why.
Bug
This class is too big.
Definition at line 60 of file ConfigService.php.
Constructor & Destructor Documentation
__construct()
__construct (protected string $appName, protected IAppContainer $appContainer, protected ILogger $logger, protected IL10N $l)
{}
@SuppressWarnings(PHPMD.Superglobals)
Definition at line 341 of file ConfigService.php.
Member Function Documentation
appPrefix()
appPrefix (string $id, string $join = '-')
Parameters
string $id Given something.
string $join Default '-'.
Returns
string The $id prefixed by the app-name, joined with a dash.
Definition at line 402 of file ConfigService.php.
computeHash()
computeHash (string $value)
Parameters
string $value The value to hash.
Returns
string The hash of $value.
Definition at line 792 of file ConfigService.php.
References ConfigService\getEncryptionService().
currencyIsoCode()
currencyIsoCode ($locale = null)
Parameters
null | string $locale Locale to use, use app-locale if null.
Returns
string The currency 3-letter ISO code for the given or the app's locale.
Definition at line 1208 of file ConfigService.php.
References ConfigService\getAppLocale().
Referenced by ConfigService\moneyValue().
currencySymbol()
currencySymbol ($locale = null)
Parameters
null | string $locale Locale to use, use app-locale if null.
Returns
The currency symbol for the given or the app's locale.
Definition at line 1194 of file ConfigService.php.
References ConfigService\getAppLocale().
dateTimeFormatter()
dateTimeFormatter ()
Returns
IDateTimeFormatter
Definition at line 995 of file ConfigService.php.
decrypt()
decrypt (?string $value)
Parameters
null | string $value Value to decrypt.
Returns
null|string Decrypted value.
Definition at line 769 of file ConfigService.php.
References ConfigService\getEncryptionService().
decryptConfigValues()
decryptConfigValues ()
Fetch all config values and decrypt them.
This is only meant for use during re-cryption of config value when changing the encryption key. Hence we enforce "ignoreLock: true".
Returns
array Configuration values.
Definition at line 895 of file ConfigService.php.
References ConfigService\$encryptionCache, ConfigService\getAppKeys(), and ConfigService\getConfigValue().
deleteAppValue()
deleteAppValue (string $key)
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
Returns
void
Definition at line 704 of file ConfigService.php.
References ConfigService\getCloudConfig().
Referenced by ConfigService\deleteConfigValue().
deleteConfigValue()
deleteConfigValue (string $key)
Delete the value for the given key.
Parameters
string $key Config key.
Returns
void
Definition at line 871 of file ConfigService.php.
References ConfigService\deleteAppValue().
encrypt()
encrypt (?string $value)
Parameters
null | string $value Value to encrypt.
Returns
null|string Encrypted value.
Definition at line 759 of file ConfigService.php.
References ConfigService\getEncryptionService().
encryptConfigValues()
encryptConfigValues (array $override = [])
Flush all configuration values to the database, possibly encrypting them.T his is only meant for use during re-cryption of config value when changing the encryption key.
Hence we enforce "ignoreLock: true".
Parameters
array $override Values which override the configured values.
Returns
void
Definition at line 912 of file ConfigService.php.
References ConfigService\getAppKeys(), ConfigService\getConfigValue(), and ConfigService\setConfigValue().
encryptionKeyValid()
encryptionKeyValid (?string $encryptionKey)
Check the validity of the encryption key.
In order to do so we fetch an encrypted representation of the key from the OC config space and try to decrypt that key with the given key. If the decrypted key matches our key, then we accept the key.
Parameters
null | string $encryptionKey Key to check.
Returns
bool
Exceptions
Exceptions
\EncryptionKeyException
See also
EncryptionService::encryptionKeyValid()
Definition at line 811 of file ConfigService.php.
References ConfigService\getEncryptionService().
findAvailableLanguages()
findAvailableLanguages (string $app = 'core')
Parameters
string $app The app with the translations.
Returns
array
See also
IL10NFactory::findAvailableLanguages()
Definition at line 1152 of file ConfigService.php.
References ConfigService\getL10NFactory().
Referenced by ConfigService\localeLanguageNames().
findAvailableLocales()
findAvailableLocales ()
Returns
array
See also
IL10NFactory::findAvailableLocales()
Definition at line 1162 of file ConfigService.php.
References ConfigService\getL10NFactory().
floatValue()
floatValue (mixed $value, int $decimals = 4, ?string $locale = null)
Convert a float value in the given or default locale.
Parameters
mixed $value Value to format.
int $decimals Number of decimal places.
null | string $locale Locale to use, use user-locale if null.
Returns
string
Definition at line 1250 of file ConfigService.php.
References ConfigService\getLocale().
formatTimeStamp()
formatTimeStamp ($date = null, ?string $format = null, ?DateTimeZone $timeZone = null)
Format the given date according to $format and $timeZone to a human readable time-stamp, providing defaults for $format and using the default time-zone if none is specified.
Parameters
null | int | \\DateTimeInterface $date
null | string $format
null | \\DateTimeZone $timeZone
Returns
string
Definition at line 1273 of file ConfigService.php.
References ConfigService\getDateTimeZone().
Referenced by ConfigService\timeStamp().
generateRandomBytes()
generateRandomBytes (int $length = 30)
Would rather belong to the EncryptionService.
Parameters
int $length Length of random string.
Returns
string
Definition at line 946 of file ConfigService.php.
References ConfigService\getSecureRandom().
getAppConfig()
getAppConfig ()
Returns
IConfig
Definition at line 378 of file ConfigService.php.
References ConfigService\getCloudConfig().
getAppContainer()
getAppContainer ()
Returns
IAppContainer
Definition at line 350 of file ConfigService.php.
getAppEncryptionKey()
getAppEncryptionKey ()
Returns
null|string
Definition at line 749 of file ConfigService.php.
References ConfigService\getEncryptionService().
getAppKeys()
getAppKeys ()
Returns
array All config keys for the app.
Definition at line 878 of file ConfigService.php.
References ConfigService\getAppKeys(), and ConfigService\getCloudConfig().
Referenced by ConfigService\decryptConfigValues(), ConfigService\encryptConfigValues(), and ConfigService\getAppKeys().
getAppL10n()
getAppL10n ()
Returns
IL10N
Definition at line 510 of file ConfigService.php.
getAppLanguage()
getAppLanguage ()
Returns
string The language part of the current or given locale.
Definition at line 1074 of file ConfigService.php.
getAppLocale()
getAppLocale ()
Get the configured app locale.
Used to implement consistent currency symbols and some "localized" folder names.
Returns
string
Definition at line 1046 of file ConfigService.php.
Referenced by ConfigService\currencyIsoCode(), ConfigService\currencySymbol(), and ConfigService\transliterate().
getAppName()
getAppName ()
Returns
string
Definition at line 390 of file ConfigService.php.
getAppValue()
getAppValue (string $key, mixed $default = null)
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $default Default value.
Returns
mixed
Definition at line 678 of file ConfigService.php.
References ConfigService\getCloudConfig().
Referenced by ConfigService\getGroupId().
getCloudConfig()
getCloudConfig ()
Returns
IConfig
Definition at line 384 of file ConfigService.php.
Referenced by ConfigService\deleteAppValue(), ConfigService\getAppConfig(), ConfigService\getAppKeys(), ConfigService\getAppValue(), ConfigService\getUserValue(), ConfigService\setAppValue(), and ConfigService\setUserValue().
getConfigValue()
getConfigValue (string $key, mixed $default = null, bool $ignoreLock = false)
Get a possibly encrypted config value.
Parameters
string $key
mixed $default
bool $ignoreLock Only to be used while changing the encryption key.
Returns
mixed
Exceptions
Exceptions
\ConfigLockedException
Definition at line 829 of file ConfigService.php.
References ConfigService\getEncryptionService().
Referenced by ConfigService\decryptConfigValues(), ConfigService\encryptConfigValues(), and FileNodeListener\matchDocumentTemplates().
getDateTimeZone()
getDateTimeZone (mixed $timeStamp = false)
Get the current timezone.
Parameters
bool | int $timeStamp
Returns
DateTimeZone
Definition at line 1007 of file ConfigService.php.
Referenced by ConfigService\formatTimeStamp().
getEncryptionService()
getEncryptionService ()
Returns
EncryptionService
Definition at line 717 of file ConfigService.php.
Referenced by ConfigService\computeHash(), ConfigService\decrypt(), ConfigService\encrypt(), ConfigService\encryptionKeyValid(), ConfigService\getAppEncryptionKey(), ConfigService\getConfigValue(), ConfigService\getUserEncryptionKey(), ConfigService\setAppEncryptionKey(), ConfigService\setConfigValue(), ConfigService\setUserEncryptionKey(), and ConfigService\verifyHash().
getGroup()
getGroup (?string $groupId = null)
Parameters
null | string $groupId
Returns
null|IGroup The group for the given id or the orchetra group.
Definition at line 529 of file ConfigService.php.
References ConfigService\getGroupId(), and ConfigService\getGroupManager().
Referenced by ConfigService\getGroupSubAdmins(), ConfigService\getSubAdminGroup(), and ConfigService\isSubAdminOfGroup().
getGroupId()
getGroupId ()
Returns
string The orchestra orga-group id.
Definition at line 519 of file ConfigService.php.
References ConfigService\getAppValue().
Referenced by ConfigService\getGroup(), ConfigService\getSubAdminGroupId(), ConfigService\groupExists(), and ConfigService\inGroup().
getGroupManager()
getGroupManager ()
Returns
IGroupManager
Definition at line 427 of file ConfigService.php.
Referenced by ConfigService\getGroup(), ConfigService\groupExists(), ConfigService\inGroup(), ConfigService\inSubAdminGroup(), and ConfigService\isSubAdminOfGroup().
getGroupSubAdmins()
getGroupSubAdmins (?string $groupId = null)
Return all the sub-admins of the given or the configured orchestra group.
Parameters
null | string $groupId then Use orchestra group if null.
Returns
array
Definition at line 588 of file ConfigService.php.
References ConfigService\getGroup(), and ConfigService\getSubAdminManager().
getIcon()
getIcon ()
Returns
string Image web-path to the app-icon.
Definition at line 408 of file ConfigService.php.
References ConfigService\getUrlGenerator().
getL10n()
getL10n ()
Returns
IL10N
Definition at line 504 of file ConfigService.php.
getL10NFactory()
getL10NFactory () private
Returns
IL10NFactory
Definition at line 358 of file ConfigService.php.
Referenced by ConfigService\findAvailableLanguages(), ConfigService\findAvailableLocales(), and ConfigService\localeLanguageNames().
getLanguage()
getLanguage (?string $locale = null)
Return the language part of the current or given locale.
Parameters
null | string $locale The locale to use, if null the current user's locale.
Returns
string
Definition at line 1062 of file ConfigService.php.
References ConfigService\getLocale().
getLocale()
getLocale (?string $lang = null)
Return the locale as string, e.g.
de_DE.UTF-8.
Parameters
string | null $lang
Returns
string
Definition at line 1019 of file ConfigService.php.
Referenced by ConfigService\floatValue(), ConfigService\getLanguage(), ConfigService\localeCountryNames(), ConfigService\localeLanguageNames(), and ConfigService\moneyValue().
getSecureRandom()
getSecureRandom () private
Returns
ISecureRandom
Definition at line 366 of file ConfigService.php.
Referenced by ConfigService\generateRandomBytes().
getSubAdminGroup()
getSubAdminGroup ()
Return the dedicated admin-group if it exists.
Returns
null|IGroup
Definition at line 609 of file ConfigService.php.
References ConfigService\getGroup(), and ConfigService\getSubAdminGroupId().
getSubAdminGroupId()
getSubAdminGroupId ()
Return the id of the dedicated admin-group which contains all sub-admins.
Returns
string
Definition at line 599 of file ConfigService.php.
References ConfigService\getGroupId().
Referenced by ConfigService\getSubAdminGroup(), and ConfigService\inSubAdminGroup().
getSubAdminManager()
getSubAdminManager ()
Returns
ISubAdmin
Definition at line 433 of file ConfigService.php.
Referenced by ConfigService\getGroupSubAdmins(), and ConfigService\isSubAdminOfGroup().
getTimeFactory()
getTimeFactory ()
Returns
ITimeFactory
Definition at line 372 of file ConfigService.php.
getUrlGenerator()
getUrlGenerator ()
Returns
IURLGenerator
Definition at line 439 of file ConfigService.php.
Referenced by ConfigService\getIcon().
getUser()
getUser (?string $userId = null)
Parameters
null | string $userId
Get the currently active user.
Returns
null|IUser
Definition at line 451 of file ConfigService.php.
References ConfigService\$user, ConfigService\getUserManager(), ConfigService\getUserSession(), and ConfigService\setUserId().
Referenced by ConfigService\getUserId(), ConfigService\setUser(), and ConfigService\setUserId().
getUserEncryptionKey()
getUserEncryptionKey ()
Returns
null|string
Definition at line 733 of file ConfigService.php.
References ConfigService\getEncryptionService().
getUserId()
getUserId ()
Returns
string
Definition at line 467 of file ConfigService.php.
References ConfigService\$user, and ConfigService\getUser().
Referenced by ConfigService\getUserValue(), ConfigService\inGroup(), ConfigService\inSubAdminGroup(), and ConfigService\setUserValue().
getUserManager()
getUserManager ()
Returns
IUserManager
Definition at line 421 of file ConfigService.php.
Referenced by ConfigService\getUser(), and ConfigService\isSubAdminOfGroup().
getUserSession()
getUserSession ()
Returns
IUserSession
Definition at line 415 of file ConfigService.php.
Referenced by ConfigService\getUser(), and ConfigService\setUser().
getUserValue()
getUserValue (string $key, mixed $default = null, ?string $userId = null)
Parameters
string $key Config key.
mixed $default Default value.
null | string $userId Use the current user if null.
Returns
mixed
Definition at line 648 of file ConfigService.php.
References ConfigService\getCloudConfig(), and ConfigService\getUserId().
groupExists()
groupExists ($groupId = null)
Parameters
null | string $groupId Use the orchestra group if null.
Returns
bool
Definition at line 540 of file ConfigService.php.
References ConfigService\getGroupId(), and ConfigService\getGroupManager().
inGroup()
inGroup (?string $userId = null, ?string $groupId = null)
Parameters
null | string $userId Use the current user if null.
null | string $groupId then Use orchestra group if null.
Returns
bool
Definition at line 553 of file ConfigService.php.
References ConfigService\getGroupId(), ConfigService\getGroupManager(), and ConfigService\getUserId().
inSubAdminGroup()
inSubAdminGroup (?string $userId = null)
Check if the currently logged in or given user-id belongs to the dedicated sub-admin group.
Parameters
null | string $userId
Returns
bool
Definition at line 622 of file ConfigService.php.
References ConfigService\getGroupManager(), ConfigService\getSubAdminGroupId(), and ConfigService\getUserId().
isSubAdminOfGroup()
isSubAdminOfGroup ($userId = null, $groupId = null)
Parameters
null | string $userId Use the current user if null.
null | string $groupId then Use orchestra group if null.
Returns
bool
Definition at line 570 of file ConfigService.php.
References ConfigService\$user, ConfigService\getGroup(), ConfigService\getGroupManager(), ConfigService\getSubAdminManager(), and ConfigService\getUserManager().
localeCountryNames()
localeCountryNames (?string $displayLocale = null)
Parameters
null | string $displayLocale Locale to use, if null the current user's locale.
Returns
array An array of supported country-codes and names.
Definition at line 1087 of file ConfigService.php.
References ConfigService\getLocale(), and ConfigService\localeCountryNames().
Referenced by ConfigService\localeCountryNames().
localeLanguageNames()
localeLanguageNames ($locale = null)
Parameters
null | string $locale Locale to use, if null the current user's locale.
Returns
array An array of supported languages indexed by language code.
Definition at line 1114 of file ConfigService.php.
References ConfigService\findAvailableLanguages(), ConfigService\getL10NFactory(), and ConfigService\getLocale().
moneyValue()
moneyValue (mixed $value, ?string $locale = null)
Convert $value to a currency value in the given or the user's locale.
The currency symbol, however, always refers to the fixed app locale as we really do not want to implement stock-exchange things.
Parameters
mixed $value Value to format.
null | string $locale Locale to use, use user-locale if null.
Returns
string
Definition at line 1228 of file ConfigService.php.
References ConfigService\currencyIsoCode(), and ConfigService\getLocale().
setAppEncryptionKey()
setAppEncryptionKey (string $key)
Parameters
string $key Encryption key to set.
Returns
void
Definition at line 743 of file ConfigService.php.
References ConfigService\getEncryptionService().
setAppValue()
setAppValue (string $key, mixed $value)
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $value Value to set.
Returns
mixed
Definition at line 692 of file ConfigService.php.
References ConfigService\getCloudConfig().
setConfigValue()
setConfigValue (string $key, mixed $value, bool $ignoreLock = false)
Parameters
string $key
mixed $value
bool $ignoreLock Default false. Ignore the configuration lock. The lock is set while changing the encryption key.
Returns
bool Success or not.
Exceptions
Exceptions
\ConfigLockedException
Definition at line 854 of file ConfigService.php.
References ConfigService\getEncryptionService(), and ConfigService\setConfigValue().
Referenced by ConfigService\encryptConfigValues(), and ConfigService\setConfigValue().
setUser()
setUser (?IUser $user)
Install a new user.
Parameters
null | IUser $user
Returns
null|IUser old user.
Definition at line 492 of file ConfigService.php.
References ConfigService\$user, ConfigService\getUser(), and ConfigService\getUserSession().
Referenced by ConfigService\setUserId(), and ConfigService\sudo().
setUserEncryptionKey()
setUserEncryptionKey (string $key)
Parameters
string $key Encryption key to set.
Returns
void
Definition at line 727 of file ConfigService.php.
References ConfigService\getEncryptionService().
setUserId()
setUserId (string $userId)
Install a new user id.
Parameters
string $userId The user id to install.
Returns
null|IUser old user.
Definition at line 480 of file ConfigService.php.
References ConfigService\getUser(), and ConfigService\setUser().
Referenced by ConfigService\getUser(), and ConfigService\sudo().
setUserValue()
setUserValue (string $key, mixed $value, ?string $userId = null)
Parameters
string $key Config key.
mixed $value Value to set.
null | string $userId Use the current user if null.
Returns
mixed
Definition at line 663 of file ConfigService.php.
References ConfigService\getCloudConfig(), and ConfigService\getUserId().
sudo()
sudo (string $uid, callable $callback)
Fake execution with other user-id.
Note that this function will catch any exception thrown while executing the callback-function and in case an exeption has been called will re-throw the exception.
Parameters
string $uid The "fake" uid.
callable $callback function.
Returns
mixed Whatever the callback-functoni returns.
Definition at line 970 of file ConfigService.php.
References ConfigService\setUser(), and ConfigService\setUserId().
timeStamp()
timeStamp (?string $format = null, ?DateTimeZone $timeZone = null)
Call ConfigService::formatTimeStamp() with the current date and time.
Parameters
null | string $format
null | \\DateTimeZone $timeZone
Returns
string
Definition at line 1299 of file ConfigService.php.
References ConfigService\formatTimeStamp().
transliterate()
transliterate (string $string, ?string $locale = null)
Transliterate the given string to the given or default locale.
Parameters
string $string The string to work on.
null | string $locale Locale to use, use app-locale if null.
Returns
string
Todo
We should define a user-independent locale based on the location of the orchestra.
Definition at line 1179 of file ConfigService.php.
References ConfigService\getAppLocale().
verifyHash()
verifyHash ($value, $hash)
Parameters
null | string $value Value to verify.
null | string $hash Hash to verify against.
Returns
bool \true if either hash or value are empty or if the hash could be verified.
Definition at line 782 of file ConfigService.php.
References ConfigService\getEncryptionService().
Field Documentation
$appL10n
IL10N $appL10n protected
Definition at line 299 of file ConfigService.php.
$appLanguage
string $appLanguage protected
Definition at line 305 of file ConfigService.php.
$appLocale
string $appLocale protected
Definition at line 302 of file ConfigService.php.
$cloudConfig
IConfig $cloudConfig private
Definition at line 334 of file ConfigService.php.
$encryptionCache
array $encryptionCache = [] protected
< Config-key for the announcements mailing list
Cache encrypted config values in order to speed up things.
Definition at line 282 of file ConfigService.php.
Referenced by ConfigService\decryptConfigValues().
$encryptionService
EncryptionService $encryptionService private
Definition at line 331 of file ConfigService.php.
$groupManager
IGroupManager $groupManager private
Definition at line 325 of file ConfigService.php.
$l10NFactory
IL10NFactory $l10NFactory private
Definition at line 313 of file ConfigService.php.
$localeCountryNames
$localeCountryNames = [] private
Definition at line 310 of file ConfigService.php.
$secureRandom
ISecureRandom $secureRandom private
Definition at line 319 of file ConfigService.php.
$subAdminManager
ISubAdmin $subAdminManager private
Definition at line 328 of file ConfigService.php.
$urlGenerator
IURLGenerator $urlGenerator private
Definition at line 316 of file ConfigService.php.
$user
IUser $user private
Will be overridden by sudo().
Definition at line 296 of file ConfigService.php.
Referenced by ConfigService\getUser(), ConfigService\getUserId(), ConfigService\isSubAdminOfGroup(), and ConfigService\setUser().
$userManager
IUserManager $userManager private
Definition at line 322 of file ConfigService.php.
APP_LOGO
const APP_LOGO = 'logo-greyf.svg'
Definition at line 84 of file ConfigService.php.
BALANCES_FOLDER
const BALANCES_FOLDER = 'balancesfolder'
Definition at line 102 of file ConfigService.php.
BANK_ACCOUNT_BANK_HOLIDAYS
const BANK_ACCOUNT_BANK_HOLIDAYS = 'bankAccountBankHolidays'
Definition at line 150 of file ConfigService.php.
BANK_ACCOUNT_BIC
const BANK_ACCOUNT_BIC = 'bankAccountBIC'
Definition at line 147 of file ConfigService.php.
BANK_ACCOUNT_BLZ
const BANK_ACCOUNT_BLZ = 'bankAccountBLZ'
Definition at line 146 of file ConfigService.php.
BANK_ACCOUNT_CONFIG_KEYS
const BANK_ACCOUNT_CONFIG_KEYS
Initial value:
= [
    self::BANK_ACCOUNT_OWNER,
    self::BANK_ACCOUNT_IBAN,
    self::BANK_ACCOUNT_BLZ,
    self::BANK_ACCOUNT_BIC,
    self::BANK_ACCOUNT_NAME,
    self::BANK_ACCOUNT_CREDITOR_IDENTIFIER,
    self::BANK_ACCOUNT_BANK_HOLIDAYS
  ]
Definition at line 152 of file ConfigService.php.
BANK_ACCOUNT_CREDITOR_IDENTIFIER
const BANK_ACCOUNT_CREDITOR_IDENTIFIER = 'bankAccountCreditorIdentifier'
Definition at line 149 of file ConfigService.php.
BANK_ACCOUNT_IBAN
const BANK_ACCOUNT_IBAN = 'bankAccountIBAN'
Definition at line 145 of file ConfigService.php.
BANK_ACCOUNT_NAME
const BANK_ACCOUNT_NAME = 'bankAccountBankName'
Definition at line 148 of file ConfigService.php.
BANK_ACCOUNT_OWNER
const BANK_ACCOUNT_OWNER = 'bankAccountOwner'
Definition at line 144 of file ConfigService.php.
CALENDARS
const CALENDARS
Initial value:
= [
    self::CONCERTS_CALENDAR_URI => [ 'uri' => self::CONCERTS_CALENDAR_URI, 'public' => true ],
    self::REHEARSALS_CALENDAR_URI => [ 'uri' => self::REHEARSALS_CALENDAR_URI, 'public' => true ],
    self::OTHER_CALENDAR_URI => [ 'uri' => self::OTHER_CALENDAR_URI, 'public' => true ],
    self::MANAGEMENT_CALENDAR_URI => [ 'uri' => self::MANAGEMENT_CALENDAR_URI, 'public' => false ],
    self::FINANCE_CALENDAR_URI => [ 'uri' => self::FINANCE_CALENDAR_URI, 'public' => false ],
  ]
Definition at line 136 of file ConfigService.php.
CMS_CATEGORIES
const CMS_CATEGORIES
Initial value:
= [
    'preview',
    'archive',
    'rehearsals',
    'trashbin',
  ]
Definition at line 113 of file ConfigService.php.
CMS_MODULES
const CMS_MODULES
Initial value:
= [
    'concert',
    'rehearsals',
  ]
Definition at line 119 of file ConfigService.php.
CMS_TEMPLATES
const CMS_TEMPLATES
Initial value:
= [
    'sub-page',
  ]
Definition at line 123 of file ConfigService.php.
CONCERTS_CALENDAR_URI
const CONCERTS_CALENDAR_URI = 'concerts'
Definition at line 131 of file ConfigService.php.
DEBUG_ALL
const DEBUG_ALL = self::DEBUG_GENERAL|self::DEBUG_QUERY|self::DEBUG_CSP|self::DEBUG_L10N|self::DEBUG_REQUEST|self::DEBUG_TOOLTIPS|self::DEBUG_EMAILFORM|self::DEBUG_GEOCODING
Definition at line 79 of file ConfigService.php.
DEBUG_CSP
const DEBUG_CSP = (1 << 2)
Definition at line 73 of file ConfigService.php.
DEBUG_EMAILFORM
const DEBUG_EMAILFORM = (1 << 6)
Definition at line 77 of file ConfigService.php.
DEBUG_GENERAL
const DEBUG_GENERAL = (1 << 0)
Definition at line 71 of file ConfigService.php.
DEBUG_GEOCODING
const DEBUG_GEOCODING = (1 << 7)
Definition at line 78 of file ConfigService.php.
DEBUG_L10N
const DEBUG_L10N = (1 << 3)
Definition at line 74 of file ConfigService.php.
DEBUG_NONE
const DEBUG_NONE = 0
Definition at line 80 of file ConfigService.php.
DEBUG_QUERY
const DEBUG_QUERY = (1 << 1)
Definition at line 72 of file ConfigService.php.
DEBUG_REQUEST
const DEBUG_REQUEST = (1 << 4)
Definition at line 75 of file ConfigService.php.
DEBUG_TOOLTIPS
const DEBUG_TOOLTIPS = (1 << 5)
Definition at line 76 of file ConfigService.php.
DEFAULT_LOCALE
const DEFAULT_LOCALE = 'en_US'
Definition at line 82 of file ConfigService.php.
DOCUMENT_TEMPLATE_GENERAL_DEBIT_NOTE_MANDATE
const DOCUMENT_TEMPLATE_GENERAL_DEBIT_NOTE_MANDATE = 'generalDebitNoteMandateForm'
Definition at line 169 of file ConfigService.php.
DOCUMENT_TEMPLATE_INSTRUMENT_INSURANCE_RECORD
const DOCUMENT_TEMPLATE_INSTRUMENT_INSURANCE_RECORD = 'instrumentInsuranceRecord'
Definition at line 167 of file ConfigService.php.
DOCUMENT_TEMPLATE_LOGO
const DOCUMENT_TEMPLATE_LOGO = 'logo'
Definition at line 165 of file ConfigService.php.
DOCUMENT_TEMPLATE_MEMBER_DATA_UPDATE
const DOCUMENT_TEMPLATE_MEMBER_DATA_UPDATE = 'memberDataUpdateForm'
Definition at line 170 of file ConfigService.php.
DOCUMENT_TEMPLATE_PROJECT_DEBIT_NOTE_MANDATE
const DOCUMENT_TEMPLATE_PROJECT_DEBIT_NOTE_MANDATE = 'projectDebitNoteMandateForm'
Definition at line 168 of file ConfigService.php.
DOCUMENT_TEMPLATE_SEAL
const DOCUMENT_TEMPLATE_SEAL = 'seal'
Definition at line 166 of file ConfigService.php.
DOCUMENT_TEMPLATES_FOLDER
const DOCUMENT_TEMPLATES_FOLDER = 'documenttemplatesfolder'
Definition at line 104 of file ConfigService.php.
DOCUMENT_TYPE_CONSTANT
const DOCUMENT_TYPE_CONSTANT = 'constant'
Definition at line 162 of file ConfigService.php.
DOCUMENT_TYPE_TEMPLATE
const DOCUMENT_TYPE_TEMPLATE = 'template'
Definition at line 163 of file ConfigService.php.
FINANCE_CALENDAR_URI
const FINANCE_CALENDAR_URI = 'finance'
Definition at line 135 of file ConfigService.php.
FINANCE_FOLDER
const FINANCE_FOLDER = 'financefolder'
Definition at line 101 of file ConfigService.php.
MANAGEMENT_CALENDAR_URI
const MANAGEMENT_CALENDAR_URI = 'management'
Definition at line 134 of file ConfigService.php.
OTHER_CALENDAR_URI
const OTHER_CALENDAR_URI = 'other'
Definition at line 133 of file ConfigService.php.
OUTBOX_FOLDER
const OUTBOX_FOLDER = 'outboxfolder'
Definition at line 106 of file ConfigService.php.
POSTBOX_FOLDER
const POSTBOX_FOLDER = 'postboxfolder'
Definition at line 105 of file ConfigService.php.
PROJECT_MANAGEMENT_SKELETON_FOLDER
const PROJECT_MANAGEMENT_SKELETON_FOLDER = 'management'
Definition at line 109 of file ConfigService.php.
PROJECT_PARTICIPANTS_FOLDER
const PROJECT_PARTICIPANTS_FOLDER = 'projectparticipantsfolder'
Definition at line 98 of file ConfigService.php.
PROJECT_PARTICIPANTS_SKELETON_FOLDER
const PROJECT_PARTICIPANTS_SKELETON_FOLDER = 'forename.surname'
Definition at line 108 of file ConfigService.php.
PROJECT_POSTERS_FOLDER
const PROJECT_POSTERS_FOLDER = 'projectpostersfolder'
Definition at line 99 of file ConfigService.php.
PROJECT_PUBLIC_DOWNLOADS_FOLDER
const PROJECT_PUBLIC_DOWNLOADS_FOLDER = 'projectpublicdownloadsfolder'
Definition at line 100 of file ConfigService.php.
PROJECT_SKELETON_FOLDER
const PROJECT_SKELETON_FOLDER = 'skeleton'
Definition at line 107 of file ConfigService.php.
PROJECTS_FOLDER
const PROJECTS_FOLDER = 'projectsfolder'
Definition at line 97 of file ConfigService.php.
REHEARSALS_CALENDAR_URI
const REHEARSALS_CALENDAR_URI = 'rehearsals'
Definition at line 132 of file ConfigService.php.
SHARED_FOLDER
const SHARED_FOLDER = 'sharedfolder'
Definition at line 96 of file ConfigService.php.
SHAREOWNER_ADDRESSBOOK_SERVICE_KEY
const SHAREOWNER_ADDRESSBOOK_SERVICE_KEY = 'shareowner_addressbook'
Definition at line 94 of file ConfigService.php.
SHAREOWNER_CALENDAR_SERVICE_KEY
const SHAREOWNER_CALENDAR_SERVICE_KEY = 'shareowner_calendar'
Definition at line 93 of file ConfigService.php.
SHAREOWNER_FOLDER_SERVICE_KEY
const SHAREOWNER_FOLDER_SERVICE_KEY = 'shareowner_folder'
Definition at line 92 of file ConfigService.php.
SHAREOWNER_KEY
const SHAREOWNER_KEY = 'shareowner'
Definition at line 91 of file ConfigService.php.
TAX_EXEMPTION_NOTICE_TEMPLATE
const TAX_EXEMPTION_NOTICE_TEMPLATE = 'taxExcemptionNoticeTemplate'
Definition at line 111 of file ConfigService.php.
TAX_OFFICE_IN_TRAY_FOLDER
const TAX_OFFICE_IN_TRAY_FOLDER = 'taxOfficeInTrayFolder'
Definition at line 110 of file ConfigService.php.
TRANSACTIONS_FOLDER
const TRANSACTIONS_FOLDER = 'transactionsfolder'
Definition at line 103 of file ConfigService.php.
WYSIWYG_EDITORS
const WYSIWYG_EDITORS
Initial value:
= [
    'tinymce' => [ 'name' => 'TinyMCE', 'enabled' => true],
    'ckeditor' => [ 'name' => 'CKEditor', 'enabled' => true],
  ]
Definition at line 126 of file ConfigService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/ConfigService.php