CamerataDB: ProjectBalanceSupportingDocumentsStorage Class Reference
ProjectBalanceSupportingDocumentsStorage Class Reference
Storage implementation for data-base storage, including access to encrypted entities.
Public Member Functions
getShortId ()
{
Returns
string The shot storage id without the base prefix.
}
isUpdatable ($path)
{{}}
getId ()
{}
fileFromFileName (string $name)
Fetch the file entity corresponding to file-name.
isReadable ($path)
{}
isSharable ($path)
{}
filemtime ($path)
{}
hasUpdated ($path, $time)
{}
filesize ($path)
{}
rmdir ($path)
{}
test ()
{}
stat ($path)
{}
file_exists ($path)
{}
unlink ($path)
{}
opendir ($path)
{}
mkdir ($path)
{}
is_dir ($path)
{}
is_file ($path)
{}
filetype ($path)
{}
fopen ($path, $mode)
{}
touch ($path, $mtime=null)
{}
rename ($path1, $path2)
{}
Static Public Member Functions
static checkDependencies ()
{}
Data Fields
const PATH_SEPARATOR = '/'
Protected Member Functions
findFiles (string $dirName, bool $ignored=false)
{}
getStorageModificationDateTime ()
{Return the overall modification time of the entire storage.
Returns
null|DateTimeInterface
}
getRootFolder (bool $create=true)
{}
getDirectoryModificationTime (string $dirName)
getStorageModificationTime ()
Get the overall modification time of the entire storage as Unix time-stamp.
buildPath (?string $path)
Static Protected Member Functions
static normalizeDirectoryName (string $dirName)
Attach self::PATH_SEPARATOR to the dirname if it is not the root directory.
static pathInfo (string $path, int $flags=PATHINFO_ALL)
Slightly modified pathinfo() function which also normalized directories before computing the components.
Protected Attributes
$filesRepository
$files = []
$storageEntity = null
$rootFolder = null
Private Member Functions
setFileNameCache (string $name, Entities\DatabaseStorageDirEntry $node)
Insert a "cache" entry.
unsetFileNameCache (string $name)
Remove a "cache" entry.
isContainerDirectory (string $path)
Return the sequence number if the given path refers to a document container directory, otherwise return null.
isYearDirectory (string $path)
Return the year if the basename of the path is a 4-digit number, interpreted as year.
Private Attributes
$projectService
$project
Detailed Description
Storage implementation for data-base storage, including access to encrypted entities.
Definition at line 51 of file ProjectBalanceSupportingDocumentsStorage.php.
Member Function Documentation
buildPath()
buildPath (?string $path) protected inherited
Parameters
null | string $path The path to work on.
Returns
string
Definition at line 268 of file Storage.php.
Referenced by Storage\fileFromFileName(), ProjectBalanceSupportingDocumentsStorage\setFileNameCache(), and ProjectBalanceSupportingDocumentsStorage\unsetFileNameCache().
checkDependencies()
static checkDependencies () static inherited
{}
Definition at line 311 of file Storage.php.
file_exists()
file_exists ($path) inherited
{}
Definition at line 450 of file Storage.php.
References Storage\fileFromFileName(), and Storage\is_dir().
Referenced by Storage\fopen(), Storage\isReadable(), and ProjectBalanceSupportingDocumentsStorage\isUpdatable().
fileFromFileName()
fileFromFileName (string $name) inherited
Fetch the file entity corresponding to file-name.
If the entry is a directory, return the directory name.
Parameters
string $name The path-name to work on.
Returns
null|Entities\DatabaseStorageDirEntry|DirectoryNode
Definition at line 324 of file Storage.php.
References Storage\buildPath(), and Storage\pathInfo().
Referenced by Storage\file_exists(), Storage\filemtime(), Storage\filesize(), Storage\getDirectoryModificationTime(), ProjectBalanceSupportingDocumentsStorage\getRootFolder(), Storage\is_dir(), Storage\stat(), and Storage\unlink().
filemtime()
filemtime ($path) inherited
{}
Definition at line 369 of file Storage.php.
References Storage\fileFromFileName(), Storage\getDirectoryModificationTime(), Storage\getStorageModificationTime(), and Storage\is_dir().
Referenced by Storage\hasUpdated().
filesize()
filesize ($path) inherited
{}
Definition at line 406 of file Storage.php.
References Storage\fileFromFileName(), and Storage\is_dir().
Referenced by Storage\is_file().
filetype()
filetype ($path) inherited
{}
Definition at line 521 of file Storage.php.
References Storage\is_dir(), and Storage\is_file().
findFiles()
findFiles (string $dirName, bool $ignored = false) protected
{}
Definition at line 139 of file ProjectBalanceSupportingDocumentsStorage.php.
fopen()
fopen ($path, $mode) inherited
{}
Definition at line 533 of file Storage.php.
References Storage\file_exists(), Storage\fopen(), Storage\isUpdatable(), Storage\touch(), and Storage\unlink().
Referenced by Storage\fopen().
getDirectoryModificationTime()
getDirectoryModificationTime (string $dirName) protected inherited
Parameters
string $dirName The directory to work on.
Returns
DateTimeInterface
Definition at line 217 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\filemtime().
getId()
getId () inherited
{}
Definition at line 252 of file Storage.php.
References Storage\getShortId().
Referenced by Factory\getProjectParticipantsStorage().
getRootFolder()
getRootFolder (bool $create = true) protected
{}
Definition at line 222 of file ProjectBalanceSupportingDocumentsStorage.php.
References Storage\fileFromFileName().
getShortId()
getShortId ()
{
Returns
string The shot storage id without the base prefix.
}
Reimplemented from Storage.
Definition at line 151 of file ProjectBalanceSupportingDocumentsStorage.php.
getStorageModificationDateTime()
getStorageModificationDateTime () protected
{Return the overall modification time of the entire storage.
Returns
null|DateTimeInterface
}
Reimplemented from Storage.
Definition at line 145 of file ProjectBalanceSupportingDocumentsStorage.php.
getStorageModificationTime()
getStorageModificationTime () protected inherited
Get the overall modification time of the entire storage as Unix time-stamp.
Returns
int
Definition at line 246 of file Storage.php.
References Storage\getStorageModificationDateTime().
Referenced by Storage\filemtime().
hasUpdated()
hasUpdated ($path, $time) inherited
{}
Parameters
string $path Directory-entry to check.
int $time The value of storage_mtime from the row of the filescache table for $path.
This function controls cache invalidation. We return \true if either the file is still there and its mtime is larger then the supplied storage_mtime of the $time argument, or if the file has vanished in which case it should be removed from the filescache table.
Definition at line 399 of file Storage.php.
References Storage\filemtime().
is_dir()
is_dir ($path) inherited
{}
Definition at line 499 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\file_exists(), Storage\filemtime(), Storage\filesize(), Storage\filetype(), and Storage\opendir().
is_file()
is_file ($path) inherited
{}
Definition at line 515 of file Storage.php.
References Storage\filesize().
Referenced by Storage\filetype().
isContainerDirectory()
isContainerDirectory (string $path) private
Return the sequence number if the given path refers to a document container directory, otherwise return null.
Parameters
string $path File-system path.
Returns
null|int
Definition at line 175 of file ProjectBalanceSupportingDocumentsStorage.php.
isReadable()
isReadable ($path) inherited
{}
Definition at line 346 of file Storage.php.
References Storage\file_exists().
isSharable()
isSharable ($path) inherited
{}
Definition at line 361 of file Storage.php.
isUpdatable()
isUpdatable ($path)
{{}}
Reimplemented from Storage.
Definition at line 161 of file ProjectBalanceSupportingDocumentsStorage.php.
References Storage\file_exists().
isYearDirectory()
isYearDirectory (string $path) private
Return the year if the basename of the path is a 4-digit number, interpreted as year.
Always return null for temporary and template projects.
Parameters
string $path File-system path.
Returns
null|int
Definition at line 205 of file ProjectBalanceSupportingDocumentsStorage.php.
mkdir()
mkdir ($path) inherited
{}
Definition at line 493 of file Storage.php.
normalizeDirectoryName()
static normalizeDirectoryName (string $dirName) static protected inherited
Attach self::PATH_SEPARATOR to the dirname if it is not the root directory.
Parameters
string $dirName The directory name to work on.
Returns
string
Definition at line 280 of file Storage.php.
Referenced by Storage\pathInfo().
opendir()
opendir ($path) inherited
{}
Definition at line 481 of file Storage.php.
References Storage\is_dir().
pathInfo()
static pathInfo (string $path, int $flags = PATHINFO_ALL) static protected inherited
Slightly modified pathinfo() function which also normalized directories before computing the components.
Parameters
string $path The path to work on.
int $flags As for the upstream pathinfo() function.
Returns
string|array
Definition at line 299 of file Storage.php.
References Storage\normalizeDirectoryName().
Referenced by Storage\fileFromFileName(), ProjectBalanceSupportingDocumentsStorage\setFileNameCache(), and ProjectBalanceSupportingDocumentsStorage\unsetFileNameCache().
rename()
rename ($path1, $path2) inherited
{}
Definition at line 648 of file Storage.php.
rmdir()
rmdir ($path) inherited
{}
Definition at line 419 of file Storage.php.
setFileNameCache()
setFileNameCache (string $name, Entities\DatabaseStorageDirEntry $node) private
Insert a "cache" entry.
Parameters
string $name Path-name.
Entities\\DatabaseStorageDirEntry $node File-system node.
Returns
void
Definition at line 99 of file ProjectBalanceSupportingDocumentsStorage.php.
References Storage\buildPath(), and Storage\pathInfo().
stat()
stat ($path) inherited
{}
Definition at line 437 of file Storage.php.
References Storage\fileFromFileName().
test()
test () inherited
{}
Definition at line 425 of file Storage.php.
touch()
touch ($path, $mtime = null) inherited
{}
Definition at line 642 of file Storage.php.
Referenced by Storage\fopen().
unlink()
unlink ($path) inherited
{}
Definition at line 468 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\fopen().
unsetFileNameCache()
unsetFileNameCache (string $name) private
Remove a "cache" entry.
Parameters
string $name Path-name.
Returns
void
Definition at line 119 of file ProjectBalanceSupportingDocumentsStorage.php.
References Storage\buildPath(), and Storage\pathInfo().
Field Documentation
$files
array $files = [] protected inherited
Definition at line 75 of file Storage.php.
$filesRepository
OCA CAFEVDB Wrapped Doctrine ORM EntityRepository $filesRepository protected inherited
Definition at line 72 of file Storage.php.
$project
Entities Project $project private
Definition at line 59 of file ProjectBalanceSupportingDocumentsStorage.php.
$projectService
ProjectService $projectService private
Definition at line 56 of file ProjectBalanceSupportingDocumentsStorage.php.
$rootFolder
null Entities DatabaseStorageFolder $rootFolder = null protected inherited
Definition at line 81 of file Storage.php.
$storageEntity
null Entities DatabaseStorage $storageEntity = null protected inherited
Definition at line 78 of file Storage.php.
PATH_SEPARATOR
const PATH_SEPARATOR = '/' inherited
Definition at line 69 of file Storage.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Storage/Database/ProjectBalanceSupportingDocumentsStorage.php