CamerataDB: CardDavService Class Reference
CardDavService Class Reference
Public Member Functions
__construct (ConfigService $configService, \OCP\Contacts\IManager $addressBookManager, CardDavBackend $cardDavBackend,)
createAddressBook (string $uri, ?string $displayName=null, ?string $userId=null)
Get or create a addressBook.
deleteAddressBook (int $id)
Delete the addressBook with the given id.
groupShareAddressBook (int $addressBookId, string $groupId, bool $readOnly=false)
displayName (int $addressBookId, string $displayName)
addressBookByName (string $displayName)
Get a addressBook with the given display name.
addressBookById (int $id)
Get a addressBook with the given its id.
Private Member Functions
refreshAddressBookManager ()
Force OCP\Contacts\IManager to be refreshed.
Private Attributes
$cardDavBackend
$addressBookManager
$contactsUserId
Detailed Description
Todo:
: replace the stuff below by more persistent APIs. As it shows (Sep. 2020) the only option would be http calls to the dav service. Even the perhaps-forthcoming writable addressBook API does not allow the creation of addressBooks or altering shring options. missing: move/delete addressBook
Definition at line 43 of file CardDavService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, \OCP\Contacts\IManager $addressBookManager, CardDavBackend $cardDavBackend)
Definition at line 57 of file CardDavService.php.
Member Function Documentation
addressBookById()
addressBookById (int $id)
Get a addressBook with the given its id.
Parameters
int $id
Returns
null|IAddressBook
Definition at line 200 of file CardDavService.php.
References CardDavService\refreshAddressBookManager().
addressBookByName()
addressBookByName (string $displayName)
Get a addressBook with the given display name.
Parameters
string $displayName
Returns
null|IAddressBook
Definition at line 180 of file CardDavService.php.
References CardDavService\refreshAddressBookManager().
createAddressBook()
createAddressBook (string $uri, ?string $displayName = null, ?string $userId = null)
Get or create a addressBook.
Parameters
string $uri Relative URI.
null | string $displayName Display-name of the addressBook.
null | string $userId part of the principal name.
Returns
int AddressBook id.
Definition at line 80 of file CardDavService.php.
References CardDavService\refreshAddressBookManager().
deleteAddressBook()
deleteAddressBook (int $id)
Delete the addressBook with the given id.
Parameters
int $id
Returns
void
Definition at line 112 of file CardDavService.php.
References CardDavService\refreshAddressBookManager().
displayName()
displayName (int $addressBookId, string $displayName)
Parameters
int $addressBookId
string $displayName
Returns
bool
Definition at line 160 of file CardDavService.php.
groupShareAddressBook()
groupShareAddressBook (int $addressBookId, string $groupId, bool $readOnly = false)
Parameters
int $addressBookId
string $groupId
bool $readOnly
Returns
bool
Definition at line 127 of file CardDavService.php.
refreshAddressBookManager()
refreshAddressBookManager () private
Force OCP\Contacts\IManager to be refreshed.
Bug:
This function uses internal APIs.
Returns
void
Definition at line 220 of file CardDavService.php.
Referenced by CardDavService\addressBookById(), CardDavService\addressBookByName(), CardDavService\createAddressBook(), and CardDavService\deleteAddressBook().
Field Documentation
$addressBookManager
OCP AddressBook IManager $addressBookManager private
Definition at line 51 of file CardDavService.php.
$cardDavBackend
CardDavBackend $cardDavBackend private
Definition at line 48 of file CardDavService.php.
$contactsUserId
int $contactsUserId private
Definition at line 54 of file CardDavService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/CardDavService.php