CamerataDB: Application Class Reference
Application Class Reference
{}
Public Member Functions
__construct (array $urlParams=[])
{}
__destruct ()
{}
boot (IBootContext $context)
{}
register (IRegistrationContext $context)
{}
Static Public Member Functions
static get (string $service)
Static query of a service through the app container.
Protected Attributes
$appName
Static Protected Attributes
static $appContainer
Detailed Description
{}
Definition at line 113 of file Application.php.
Constructor & Destructor Documentation
__construct()
__construct (array $urlParams = [])
{}
Definition at line 124 of file Application.php.
__destruct()
__destruct ()
{}
Definition at line 131 of file Application.php.
Member Function Documentation
boot()
boot (IBootContext $context)
{}
Called later than "register".
Definition at line 156 of file Application.php.
References AuthorizationService\authorized().
get()
static get (string $service) static
Static query of a service through the app container.
Parameters
string $service
Returns
mixed
Definition at line 143 of file Application.php.
Referenced by OCA\CAFEVDB\Storage\Database\getAppL10n().
register()
register (IRegistrationContext $context)
{}
Called earlier than boot, so anything initialized in the "boot()" method must not be used here.
Definition at line 221 of file Application.php.
References Registration\register().
Field Documentation
$appContainer
IAppContainer $appContainer static protected
Definition at line 118 of file Application.php.
$appName
string $appName protected
Definition at line 121 of file Application.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/AppInfo/Application.php