CamerataDB: EventsService Class Reference
EventsService Class Reference
Events and tasks handling.
Public Member Functions
__construct (protected IUserSession $userSession, protected ConfigService $configService, protected EntityManager $entityManager, private ProjectService $projectService, private CalDavService $calDavService, private VCalendarService $vCalendarService,)
{}
onCalendarObjectCreated (CalendarObjectCreatedEvent|CalendarObjectRestoredEvent $event,)
onCalendarObjectUpdated (CalendarObjectUpdatedEvent $event)
onCalendarObjectMoved (CalendarObjectMovedEvent $event)
onCalendarObjectDeleted (CalendarObjectDeletedEvent|CalendarObjectMovedToTrashEvent $event,)
onCalendarDeleted (CalendarDeletedEvent|CalendarMovedToTrashEvent $event)
onCalendarUpdated (CalendarUpdatedEvent $event)
onProjectDeleted (BeforeProjectDeletedEvent $event)
onProjectUpdated (PreProjectUpdatedEvent $event)
getEventData (Entities\ProjectEvent $projectEvent)
Augment the database entity by calendar data.
fetchEvent (mixed $projectOrId, string $eventURI, ?int $recurrenceId)
Fetch one specific event and convert start and end to DateTime, also determine allDay.
getProjectEvent (mixed $projectOrId, string $eventURI, ?int $recurrenceId)
Fetch one specific event and just return the database entity.
briefEventDate (array $eventObject, ?string $timezone=null, ?string $locale=null)
Form a brief event date in the given locale.
longEventDate (array $eventObject, ?string $timezone=null, ?string $locale=null)
Form a "brief long" event date in the given locale.
eventMatrix (array $projectEvents, array $calendarIds)
Convert the given flat event-list (as returned by self::events()) into a matrix grouped as specified by the array $calendarIds in the given order.
projectEventData (int $projectId, mixed $calendarIds=null, ?string $timezone=null, ?string $locale=null)
Return event data for given project id and calendar id.
exportEvents (array $events, string $projectName, bool $hideParticipants=false)
Export the given events in ICAL format.
defaultCalendars (bool $public=false)
getProjectRegistrationCategory (bool $translate=true)
A category marking a calendar event which models the project registration period in the calendar.
getRecordAbsenceCategory (bool $translate=true)
Category marking an event which should produce a "record absence" field in the project instrumentation table.
unregister (int|Entities\Project $projectOrId, string $eventURI, mixed $recurrenceId=null, bool $flush=true)
Unconditionally unregister the given event with the given project.
newTask (array $taskData)
Inject a new task into the given calendar.
newEvent (array $eventData)
Inject a new event into the given calendar.
updateCalendarEntry (array $object, array $changeSet=[])
Update the calendar entry contained in $object, i.e.
setCalendarTaskStatus (array $event, ?string $status=null, ?int $percentComplete=null, ?DateTimeImmutable $dateCompleted=null,)
updateCalendarEvent (array $event, array $changeSet=[])
Update the event entry contained in $event, modify it and write it back to the server.
updateCalendarTask (array $task, array $changeSet=[])
Update the task entry contained in $event, modify it and write it back to the server.
findCalendarEntry (mixed $calId, string $objectIdentifier)
Find a calendar object by its URI or UID.
findProjectRegistrationEvent (string|Entities\Project $project)
Find the project registration event if it exists and generate the same array structure as returned by findCalendarEntry().
isProjectRegistrationEvent (mixed $eventData)
Check whether the given object referes to a project registration event.
ensureProjectRegistrationEvent (Entities\Project $project)
Ensure that the "other" calendar contains a project registration event if and only if the registration start date is set in the project entity.
flushDatabase ()
Flush the database.
Static Public Member Functions
static makeFlatIdentifier (array $eventIdentifier)
static absenceFieldsDefault (string $calendarUri)
Decide whether events in the given calendar should by default generate absence fields.
Data Fields
const VALARM_FROM_START = VCalendarService::VALARM_FROM_START
const VALARM_FROM_END = VCalendarService::VALARM_FROM_END
const TASK_IN_PROCESS = VCalendarService::VTODO_STATUS_IN_PROCESS
const TASK_COMPLETED = VCalendarService::VTODO_STATUS_COMPLETED
const TASK_NEEDS_ACTION = VCalendarService::VTODO_STATUS_NEEDS_ACTION
const PROJECT_REGISTRATION_CATEGORY = 'project registration'
const RECORD_ABSENCE_CATEGORY = 'record absence'
Private Member Functions
eventProjects (string $eventURI)
projectEvents ($projectOrId)
getVEventSiblings (int $calendarId, VCalendar $vCalendar)
Use the EventIterator to generate all siblings of a recurring event.
fillEventDataFromVObject (VEvent $vObject, array &$event=[])
Convert the given VEvent object to a simpler flat array structure.
eventTimes (array$eventObject, ?string $timezone=null, ?string $locale=null)
Form start and end date and time in given timezone and locale.
eventData (array $eventObject, ?string $timezone=null, ?string $locale=null)
Form an array with the most relevant event data.
getCalendarId (string $uri)
deleteCalendarId (string $uri)
Delete the configured calendar id.
getCalendarDisplayName (string $uri)
Return the configured calendar display name.
setCalendarDisplayName (string $uri, string $displayName)
Set the configured calendar display name.
Private Attributes
$eventSiblings
Cache the siblings of recurring events by calendar-id, event-uid, sequence, recurrence-id.
$projectEventSiblings
Cache the siblings of recurring events by project-id, calendar-uri, recurrence-id, event-uid.
$projectRegistrationEvents
Cached project registration events by project name.
Detailed Description
Events and tasks handling.
Definition at line 75 of file EventsService.php.
Constructor & Destructor Documentation
__construct()
__construct (protected IUserSession $userSession, protected ConfigService $configService, protected EntityManager $entityManager, private ProjectService $projectService, private CalDavService $calDavService, private VCalendarService $vCalendarService)
{}
Definition at line 112 of file EventsService.php.
Member Function Documentation
absenceFieldsDefault()
static absenceFieldsDefault (string $calendarUri) static
Decide whether events in the given calendar should by default generate absence fields.
Parameters
string $calendarUri
Returns
bool
Definition at line 1209 of file EventsService.php.
briefEventDate()
briefEventDate (array $eventObject, ?string $timezone = null, ?string $locale = null)
Form a brief event date in the given locale.
Parameters
array $eventObject The corresponding event object from fetchEvent() or events().
null | string $timezone Explicit time zone to use, otherwise fetched from user-settings.
null | string $locale Explicit language setting to use, otherwise fetched from user-settings.
Returns
string
Definition at line 765 of file EventsService.php.
defaultCalendars()
defaultCalendars (bool $public = false)
Parameters
bool $public Hide non-public calendars.
Returns
array The IDs of the default calendars.
See also
ConfigService::CALENDARS
Definition at line 1072 of file EventsService.php.
deleteCalendarId()
deleteCalendarId (string $uri) private
Delete the configured calendar id.
Parameters
string $uri Calendar tag.
Returns
void
Definition at line 1101 of file EventsService.php.
ensureProjectRegistrationEvent()
ensureProjectRegistrationEvent (Entities\Project $project)
Ensure that the "other" calendar contains a project registration event if and only if the registration start date is set in the project entity.
Existing events will be modified to reflect to current settings and moved to the "other" calendar if necessary.
Parameters
Entities\\Project $project
Returns
bool Retrun \true if the registration event exists, \false otherwise.
Definition at line 2615 of file EventsService.php.
eventData()
eventData (array $eventObject, ?string $timezone = null, ?string $locale = null) private
Form an array with the most relevant event data.
Parameters
array $eventObject The corresponding event object from fetchEvent() or events().
null | string $timezone Explicit time zone to use, otherwise fetched from user-settings.
null | string $locale Explicit language setting to use, otherwise fetched from user-settings.
Returns
array
[
  'times' => $this->eventTimes($eventObject, $timezone, $locale),
  'summary' => $eventObject['summary'],
  'location' => $eventObject['location'],
  'description' => $eventObject['description'],
]
Definition at line 893 of file EventsService.php.
eventMatrix()
eventMatrix (array $projectEvents, array $calendarIds)
Convert the given flat event-list (as returned by self::events()) into a matrix grouped as specified by the array $calendarIds in the given order.
The result is an associative array where the keys are the displaynames of the calenders; the last row will contain events which do not belong to any id mentioned in $calendarIds and be tagged by the key 'other'.
Parameters
array $projectEvents List returned by self::events().
array $calendarIds Array with calendar sorting order, giving the ids of the wanted calendars in the wanted order.
Returns
array Associative array with calendarnames as keys.
Definition at line 831 of file EventsService.php.
eventProjects()
eventProjects (string $eventURI) private
Parameters
string $eventURI CalDAV URI.
Returns
Entities\ProjectEvent[]
Definition at line 399 of file EventsService.php.
eventTimes()
eventTimes (array$eventObject , ?string $timezone = null, ?string $locale = null) private
Form start and end date and time in given timezone and locale.
Parameters
array $eventObject The corresponding event object from fetchEvent() or events().
null | string $timezone Explicit time zone to use, otherwise fetched from user-settings.
null | string $locale Explicit language setting to use, otherwise fetched from user-settings.
Returns
array
[ 'start' => array('date' => ..., 'time' => ..., 'allday' => ...), 'end' => ... ]
Todo
Perhaps convert to DateTime class instead of using strftime().
Definition at line 707 of file EventsService.php.
exportEvents()
exportEvents (array $events, string $projectName, bool $hideParticipants = false)
Export the given events in ICAL format.
The events need not belong to the same calendar.
Parameters
array $events An array of event identifiers in the form
[
  [ 'calendarId' => ID, 'uri' => EVENT_URI, 'recurrenceID' => RECUR_ID ],
  ...
]
where the recurrence-id may be missing or empty in which case the entire event is exported. If recurrence-ids are specified, then the function checks if $events contains all siblings and in this case simply exports the entire event. If siblings are missing, then only a collection of the requested events is exported.
string $projectName Short project tag, will form part of the name of the calendar.
bool $hideParticipants Switch in order to hide participants. For example email attachment sendc @all most likely should not contain the list of attendees.
Returns
A string with the ICAL data.
Definition at line 995 of file EventsService.php.
fetchEvent()
fetchEvent (mixed $projectOrId, string $eventURI, ?int $recurrenceId)
Fetch one specific event and convert start and end to DateTime, also determine allDay.
Parameters
int | Entities\\Project $projectOrId
string $eventURI CalDAV URI.
null | int $recurrenceId If non null find this instance. Otherwise just pick one event instance if behind the URI we have an event series.
Returns
null|array
See also
makeEvent()
Definition at line 601 of file EventsService.php.
fillEventDataFromVObject()
fillEventDataFromVObject (VEvent $vObject, array & $event = []) private
Convert the given VEvent object to a simpler flat array structure.
Parameters
VEvent $vObject
array $event Output array to fill.
Returns
array Just return $event, with the following data filled in:
[
  ...
  'start' => \\DateTime,
  'end' => \\DateTime,
  'allday' => BOOL
  'summary' => SUMMARY,
  'description' => DESCRTION,
  'location' => LOCATION,
  ...
]
Definition at line 543 of file EventsService.php.
findCalendarEntry()
findCalendarEntry (mixed $calId, string $objectIdentifier)
Find a calendar object by its URI or UID.
Parameters
mixed $calId
string $objectIdentifier Either the URI or the UID of the object. If the identifier ends with '.ics' it is assumed to be an URI, other a UID.
Returns
array|null
See also
CalDavService::getCalendarObject()
Definition at line 2521 of file EventsService.php.
findProjectRegistrationEvent()
findProjectRegistrationEvent (string|Entities\Project $project)
Find the project registration event if it exists and generate the same array structure as returned by findCalendarEntry().
Parameters
string | Entities\\Project $project Either the project name or the project entity.
Returns
null|array
Definition at line 2537 of file EventsService.php.
flushDatabase()
flushDatabase ()
Flush the database.
This is a companion to the various public methods which have a boolean $flush parameter.
Returns
void
Definition at line 2723 of file EventsService.php.
getCalendarDisplayName()
getCalendarDisplayName (string $uri) private
Return the configured calendar display name.
Parameters
string $uri Calendar tag.
Returns
string
Definition at line 1113 of file EventsService.php.
getCalendarId()
getCalendarId (string $uri) private
Parameters
string $uri Calendar tag.
Returns
null|string Return the configured calendar id.
Definition at line 1089 of file EventsService.php.
getEventData()
getEventData (Entities\ProjectEvent $projectEvent)
Augment the database entity by calendar data.
Parameters
Entities\\ProjectEvent $projectEvent Database entity.
Returns
array|null Returns null if the calendar object cannot be found, otherwise an array
[
  'projectid' => PROJECT_ID,
  'uri' => EVENT_URI,
  'uid' => EVENT_UID,
  'calendarid' => CALENDAR_ID,
  'start' => \\DateTime,
  'end' => \\DateTime,
  'allday' => BOOL
  'summary' => SUMMARY,
  'description' => DESCRTION,
  'location' => LOCATION,
]
Definition at line 484 of file EventsService.php.
getProjectEvent()
getProjectEvent (mixed $projectOrId, string $eventURI, ?int $recurrenceId)
Fetch one specific event and just return the database entity.
Parameters
int | Entities\\Project $projectOrId
string $eventURI CalDAV URI.
null | int $recurrenceId If non null find this instance. Otherwise return all matching entries for the given event-URI.
Returns
null|Entities\ProjectEvent|array<int, Entities\ProjectEvent>
Definition at line 625 of file EventsService.php.
getProjectRegistrationCategory()
getProjectRegistrationCategory (bool $translate = true)
A category marking a calendar event which models the project registration period in the calendar.
Parameters
bool $translate Translate the category name with the app's IL10N instance.
Returns
string
Definition at line 1141 of file EventsService.php.
getRecordAbsenceCategory()
getRecordAbsenceCategory (bool $translate = true)
Category marking an event which should produce a "record absence" field in the project instrumentation table.
Parameters
bool $translate Translate the category name with the app's IL10N instance.
Returns
string
Definition at line 1155 of file EventsService.php.
getVEventSiblings()
getVEventSiblings (int $calendarId, VCalendar $vCalendar) private
Use the EventIterator to generate all siblings of a recurring event.
For non-recurring events return a single element array containing just this VEvent instance.
Parameters
int $calendarId
VCalendar $vCalendar
Returns
array<int, VEvent>
Definition at line 425 of file EventsService.php.
isProjectRegistrationEvent()
isProjectRegistrationEvent (mixed $eventData)
Check whether the given object referes to a project registration event.
Parameters
mixed $eventData
Returns
bool
Definition at line 2576 of file EventsService.php.
longEventDate()
longEventDate (array $eventObject, ?string $timezone = null, ?string $locale = null)
Form a "brief long" event date in the given locale.
Parameters
array $eventObject The corresponding event object from fetchEvent() or events().
null | string $timezone Explicit time zone to use, otherwise fetched from user-settings.
null | string $locale Explicit language setting to use, otherwise fetched from user-settings.
Returns
string
Definition at line 794 of file EventsService.php.
makeFlatIdentifier()
static makeFlatIdentifier (array $eventIdentifier) static
Parameters
array $eventIdentifier Array with at least the keys "calendarId", "uri" and "recurrenceId", e.g. an item in the array returned by self::events().
Returns
string
Definition at line 680 of file EventsService.php.
newEvent()
newEvent (array $eventData)
Inject a new event into the given calendar.
Parameters
array $eventData Passed on to VCalendarService::createVCalendarFromRequest()
One example, in order to create a simple non-repeating event:
[
  'summary' => TITLE,
  'from' => dd-mm-yyyy,
  'to' => dd-mm-yyyy,
  'allday' => on (or unset),
  'location' => WHERE (may be empty),
  'categories' => <list, comma separated>,
  'description' => TEXT,
  'repeat' => 'doesnotrepeat',
  'calendar' => CALID
]
We also support adding a reminder: 'alarm' => unset or interval in seconds (i.e. time-stamp diff). The function may throw errors.
Returns
array|null event-uri, event-uid or null on error.
[ 'uri' => EVENT_URI, 'uid' => EVENT_UID, 'event' => EVENT_OBJECT ]
Definition at line 2183 of file EventsService.php.
newTask()
newTask (array $taskData)
Inject a new task into the given calendar.
This function calls $request is a post-array. One example, in order to create a simple task:
Parameters
array $taskData Passed on to VCalendarService::createVCalendarFromRequest()
[
  'description' => $title, // required
  'related' => other VObject's UID // optional
  'due' => date('d-m-Y', $timeStamp), // required
  'start' => date('d-m-Y'), // optional
  'location' => 'Cyber-Space', // optional
  'categories' => $categories, // optional
  'description' => $description, // optional
  'calendar' => $calendarId, // required
  'starred' => true, // optional
  'alarm' => $alarm, // optional
]
We also support adding a reminder: 'alarm' => ALARMSPEC. ALARMSPEC can be
null, 0 no alarm
int The alarm interval in seconds
[ RELATED => int ] where RELATED is either START or END. Negative values reach in the past relative to RELATED.
Returns
array task-uri, task-uid on success, null on error.
[ 'uri' => TASK_URI, 'uid' => TASK_UID, 'task' => TASK_OBJECT ]
Definition at line 2132 of file EventsService.php.
onCalendarDeleted()
onCalendarDeleted (CalendarDeletedEvent|CalendarMovedToTrashEvent $event)
Parameters
CalendarDeletedEvent | CalendarMovedToTrashEvent $event Event object.
Returns
void
Definition at line 282 of file EventsService.php.
onCalendarObjectCreated()
onCalendarObjectCreated (CalendarObjectCreatedEvent|CalendarObjectRestoredEvent $event)
Parameters
CalendarObjectCreatedEvent | CalendarObjectRestoredEvent $event $event->getObjectData() wiell yield something like
[
  'uri'           => $row['uri'],
  'lastmodified'  => $row['lastmodified'],
  'etag'          => '"' . $row['etag'] . '"',
  'calendarid'    => $row['calendarid'],
  'size'          => (int)$row['size'],
  'calendardata'  => $this->readBlob($row['calendardata']),
  'component'     => strtolower($row['componenttype']),
  'classification'=> (int)$row['classification']
];
.
Returns
void
Definition at line 142 of file EventsService.php.
onCalendarObjectDeleted()
onCalendarObjectDeleted (CalendarObjectDeletedEvent|CalendarObjectMovedToTrashEvent $event)
Parameters
CalendarObjectDeletedEvent | CalendarObjectMovedToTrashEvent $event Calendar event.
Returns
void
Definition at line 235 of file EventsService.php.
onCalendarObjectMoved()
onCalendarObjectMoved (CalendarObjectMovedEvent $event)
Parameters
CalendarObjectMovedEvent $event Event object.
Returns
void
Definition at line 184 of file EventsService.php.
References VCalendarService\getVCalendar().
onCalendarObjectUpdated()
onCalendarObjectUpdated (CalendarObjectUpdatedEvent $event)
Parameters
CalendarObjectUpdatedEvent $event Event object.
Returns
void
Definition at line 163 of file EventsService.php.
onCalendarUpdated()
onCalendarUpdated (CalendarUpdatedEvent $event)
Parameters
CalendarUpdatedEvent $event Event object.
Returns
void
Definition at line 313 of file EventsService.php.
onProjectDeleted()
onProjectDeleted (BeforeProjectDeletedEvent $event)
Parameters
BeforeProjectDeletedEvent $event Event object.
Returns
void
Definition at line 340 of file EventsService.php.
onProjectUpdated()
onProjectUpdated (PreProjectUpdatedEvent $event)
Parameters
PreProjectUpdatedEvent $event Event object.
Returns
void
Definition at line 367 of file EventsService.php.
References ProjectUpdatedEvent\getNewData(), ProjectUpdatedEvent\getOldData(), and ProjectUpdatedEvent\getProjectId().
projectEventData()
projectEventData (int $projectId, mixed $calendarIds = null, ?string $timezone = null, ?string $locale = null)
Return event data for given project id and calendar id.
Used in an API call from Redaxo.
Parameters
int $projectId
null | string | array $calendarIds null to get the events from all calendars or the 'uri' component from OCA\CAFEVDB\Service\ConfigService::CALENDARS.
null | string $timezone
null | string $locale
Returns
array
[
  [ 'events' => EVENT_DATA1 ],
  [ 'events' => EVENT_DATA2 ],
  ...
]
Definition at line 935 of file EventsService.php.
projectEvents()
projectEvents ($projectOrId) private
Parameters
int | Entities\\Project $projectOrId Database entity or its id.
Returns
Entities\ProjectEvent[]
Definition at line 409 of file EventsService.php.
setCalendarDisplayName()
setCalendarDisplayName (string $uri, string $displayName) private
Set the configured calendar display name.
Parameters
string $uri Calendar tag.
string $displayName Value to set.
Returns
bool
Definition at line 1127 of file EventsService.php.
setCalendarTaskStatus()
setCalendarTaskStatus (array $event, ?string $status = null, ?int $percentComplete = null, ?DateTimeImmutable $dateCompleted = null)
Parameters
array $event Event object to modify, previously obtained by findCalendarEntry().
null | string $status Status to set.
null | int $percentComplete Percent completed to set.
null | DateTimeImmutable $dateCompleted The date of completion, if non-null percent completed is set to 100 and the status also to COMPLETED.
Returns
void
Definition at line 2333 of file EventsService.php.
unregister()
unregister (int|Entities\Project $projectOrId, string $eventURI, mixed $recurrenceId = null, bool $flush = true)
Unconditionally unregister the given event with the given project.
Parameters
int | Entities\\Project $projectOrId The project key.
string $eventURI The event key (external key).
null | string | array $recurrenceId If not null only unregister this particular instance or instances
bool $flush
Returns
bool true if the event has been removed, false if it was not registered.
Definition at line 1832 of file EventsService.php.
updateCalendarEntry()
updateCalendarEntry (array $object, array $changeSet = [])
Update the calendar entry contained in $object, i.e.
write it back to the server.
Parameters
array $object Modified event object, previously obtained by findCalendarEntry().
array $changeSet Array of changes to apply.
Returns
void
See also
CalDavService::updateCalendarObject()
Definition at line 2304 of file EventsService.php.
updateCalendarEvent()
updateCalendarEvent (array $event, array $changeSet = [])
Update the event entry contained in $event, modify it and write it back to the server.
Parameters
array $event To be modified event object according to $changeSet.
array $changeSet Array of changes to apply.
Returns
void
See also
CalDavService::updateCalendarObject()
Definition at line 2406 of file EventsService.php.
updateCalendarTask()
updateCalendarTask (array $task, array $changeSet = [])
Update the task entry contained in $event, modify it and write it back to the server.
Parameters
array $task To be modified event object according to $changeSet.
array $changeSet Array of changes to apply.
Returns
void
See also
CalDavService::updateCalendarObject()
Definition at line 2481 of file EventsService.php.
Field Documentation
$eventSiblings
array $eventSiblings private
Cache the siblings of recurring events by calendar-id, event-uid, sequence, recurrence-id.
This cache contains calendar VEvent instances.
Definition at line 96 of file EventsService.php.
$projectEventSiblings
array $projectEventSiblings private
Cache the siblings of recurring events by project-id, calendar-uri, recurrence-id, event-uid.
This cache contains ProjectEvent entities.
Definition at line 103 of file EventsService.php.
$projectRegistrationEvents
array $projectRegistrationEvents private
Cached project registration events by project name.
Definition at line 109 of file EventsService.php.
PROJECT_REGISTRATION_CATEGORY
const PROJECT_REGISTRATION_CATEGORY = 'project registration'
Definition at line 88 of file EventsService.php.
RECORD_ABSENCE_CATEGORY
const RECORD_ABSENCE_CATEGORY = 'record absence'
Definition at line 89 of file EventsService.php.
TASK_COMPLETED
const TASK_COMPLETED = VCalendarService::VTODO_STATUS_COMPLETED
Definition at line 85 of file EventsService.php.
TASK_IN_PROCESS
const TASK_IN_PROCESS = VCalendarService::VTODO_STATUS_IN_PROCESS
Definition at line 84 of file EventsService.php.
TASK_NEEDS_ACTION
const TASK_NEEDS_ACTION = VCalendarService::VTODO_STATUS_NEEDS_ACTION
Definition at line 86 of file EventsService.php.
VALARM_FROM_END
const VALARM_FROM_END = VCalendarService::VALARM_FROM_END
Definition at line 82 of file EventsService.php.
VALARM_FROM_START
const VALARM_FROM_START = VCalendarService::VALARM_FROM_START
Definition at line 81 of file EventsService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/EventsService.php