CamerataDB: Util Class Reference
Util Class Reference
Some mostly static convenience stuff.
Static Public Member Functions
static criteria ()
Convenience function to generate Collections\Criteria.
static criteriaExpr ()
Convenience function to generate Collections\ExpressionBuilder.
static criteriaWhere (array $arrayCriteria)
Convenience function.
Detailed Description
Some mostly static convenience stuff.
Definition at line 32 of file Util.php.
Member Function Documentation
criteria()
static criteria () static
Convenience function to generate Collections\Criteria.
Returns
Collections\Criteria
Definition at line 39 of file Util.php.
Referenced by OCA\CAFEVDB\Traits\criteria(), and Util\criteriaWhere().
criteriaExpr()
static criteriaExpr () static
Convenience function to generate Collections\ExpressionBuilder.
Returns
Collections\ExpressionBuilder
Definition at line 49 of file Util.php.
Referenced by OCA\CAFEVDB\Traits\criteriaExpr(), and Util\criteriaWhere().
criteriaWhere()
static criteriaWhere (array $arrayCriteria) static
Convenience function.
Convert an array of criteria as accepted by Doctrine\ORM\EntityRepository::findBy() to an instance of Collections\Criteria.
Parameters
array $arrayCriteria Array of FIELD => VALUE pairs. FIELD support a negation operation '!'. If VALUE is an array it is interpreted as a list of acceptable values. Otherwise equality is tested. Criteria can be prefixed by '|' and '&' to indicate the boolean junctor with the other criteria. Grouping is possible by using '(' and ')'. The final closing paren may be omitted. Example: ``` [ '!fieldId' => 13, // search for field_id != 13 '&(|optionValue' => '' // with option_value the empty string ... or 'optionValue' => null // option_value is NULL ')' => IGNORED_VALUE // close the OR-group ], ```.
Returns
Collections\Criteria
Todo:
This could be made more elaborate like OCA\CAFEVDB\Database\Doctrine\ORM\Traits\FindLikeTrait::findBy().
Teach OCA\CAFEVDB\Database\Doctrine\ORM\Traits\FindLikeTrait::findBy() to use grouping with parens.
Definition at line 81 of file Util.php.
References Util\criteria(), and Util\criteriaExpr().
Referenced by OCA\CAFEVDB\Traits\criteriaWhere(), DatabaseStorageFolder\getEntryByName(), DatabaseStorageFolder\getFileByName(), DatabaseStorageFolder\getFolderByName(), ProjectParticipantField\getMusicianFieldData(), ProjectParticipantFieldDataOption\getMusicianFieldData(), and ProjectParticipantField\getOptionByLabel().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/Util.php