CamerataDB: InstrumentsRepository Class Reference
InstrumentsRepository Class Reference
Repository for instruments.
Public Member Functions
findByName (string $name)
Find an instrument by its name.
findAll ()
Sort by configured sorting column and omit disabled entries.
describeAll (bool $useEntities=false)
Prepare ofor grouping select options by instrument family.
getEntityManager ()
Public export of parent function.
Detailed Description
Repository for instruments.
Definition at line 30 of file InstrumentsRepository.php.
Member Function Documentation
describeAll()
describeAll (bool $useEntities = false)
Prepare ofor grouping select options by instrument family.
Parameters
bool $useEntities Use full entites instead of mere names in the look-up tables.
Returns
array<string, array<string|int, string>>
[
  'families' => array(FAMILIES),
  'byId' => array(ID => NAME),
  'byName' => array(NAME => NAME),
  'nameGroups' => array(NAME => FAMILY),
  'idGroups' => array(ID => FAMILY)
]
Todo
Does such a function belong into the entity repository? OTOH ...
Definition at line 76 of file InstrumentsRepository.php.
References InstrumentsRepository\findAll().
findAll()
findAll ()
Sort by configured sorting column and omit disabled entries.
Returns
array<int, Entities\Instrument>
Definition at line 51 of file InstrumentsRepository.php.
Referenced by InstrumentsRepository\describeAll().
findByName()
findByName (string $name)
Find an instrument by its name.
Parameters
string $name
Returns
Entities\Instrument
Definition at line 41 of file InstrumentsRepository.php.
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), SepaBulkTransactionsRepository\isCalendarObjectUsed(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/InstrumentsRepository.php