CamerataDB: ProjectParticipantsController Class Reference
ProjectParticipantsController Class Reference
AJAX end-points for project participants.
Public Member Functions
__construct ($appName, IRequest $request, private RequestParameterService $parameterService, protected ConfigService $configService, protected EntityManager $entityManager, private PHPMyEdit $pme, private ProjectService $projectService, private ProjectParticipantFieldsService $participantFieldsService, private StorageFactory $storageFactory,)
{}
addMusicians (int $projectId, ?int $musicianId=null)
Static Public Member Functions
static mailingListDeliveryStatus (MailingListsService $listsService, string $listId, string $email)
Fetch the delivery states for the given email.
Data Fields
const LIST_ACTION_SUBSCRIBE = 'subscribe'
const LIST_ACTION_UNSUBSCRIBE = 'unsubscribe'
const LIST_ACTION_ENABLE_DELIVERY = 'enable-delivery'
const LIST_ACTION_DISABLE_DELIVERY = 'disable-delivery'
const LIST_ACTION_RELOAD_SUBSCRIPTION = 'reload-subscription'
const LIST_SUBSCRIPTION_DELIVERY_ENABLED = 'delivery-enabled'
const LIST_SUBSCRIPTION_DELIVERY_DISABLED = 'delivery-disabled'
const LIST_SUBSCRIPTION_DISABLED_BY_USER = 'disabled-by-user'
const LIST_SUBSCRIPTION_DISABLED_BY_BOUNCES = 'disabled-by-bounces'
const LIST_SUBSCRIPTION_DISABLED_BY_MODERATOR = 'disabled-by-moderator'
const LIST_SUBSCRIPTION_MODE_DIGEST = 'mode-digest'
const FILE_ACTION_DELETE = 'delete'
const FILE_ACTION_UPLOAD = 'upload'
Detailed Description
AJAX end-points for project participants.
Definition at line 57 of file ProjectParticipantsController.php.
Constructor & Destructor Documentation
__construct()
__construct ($appName, IRequest $request, private RequestParameterService $parameterService, protected ConfigService $configService, protected EntityManager $entityManager, private PHPMyEdit $pme, private ProjectService $projectService, private ProjectParticipantFieldsService $participantFieldsService, private StorageFactory $storageFactory)
{}
Definition at line 82 of file ProjectParticipantsController.php.
Member Function Documentation
addMusicians()
addMusicians (int $projectId, ?int $musicianId = null)
Parameters
int $projectId The numeric project id.
null | int $musicianId The musician id to add. If empty, then the legacy PME "mrecs" parameter is fetched from the request.
Returns
Response
@NoAdminRequired
Definition at line 109 of file ProjectParticipantsController.php.
mailingListDeliveryStatus()
static mailingListDeliveryStatus (MailingListsService $listsService, string $listId, string $email) static
Fetch the delivery states for the given email.
Delivery may be disabled by the list-member in which case the email-form has to send its messages separately to this member if needed.
Parameters
MailingListsService $listsService Mailing lists management class.
string $listId The list id to work on.
string $email The email address of the list-member.
Returns
array
[
  'subscriptionStatus' => STATUS,
  'summary' => DISPLAY_STATUS, // for UI
  'statusTags' => STATUS_TAGS, // mode-digest etc.
];
Definition at line 1101 of file ProjectParticipantsController.php.
References MailingListsService\getSubscription(), MailingListsService\getSubscriptionPreferences(), and MailingListsService\getSubscriptionStatus().
Field Documentation
FILE_ACTION_DELETE
const FILE_ACTION_DELETE = 'delete'
Definition at line 78 of file ProjectParticipantsController.php.
FILE_ACTION_UPLOAD
const FILE_ACTION_UPLOAD = 'upload'
Definition at line 79 of file ProjectParticipantsController.php.
LIST_ACTION_DISABLE_DELIVERY
const LIST_ACTION_DISABLE_DELIVERY = 'disable-delivery'
Definition at line 68 of file ProjectParticipantsController.php.
LIST_ACTION_ENABLE_DELIVERY
const LIST_ACTION_ENABLE_DELIVERY = 'enable-delivery'
Definition at line 67 of file ProjectParticipantsController.php.
LIST_ACTION_RELOAD_SUBSCRIPTION
const LIST_ACTION_RELOAD_SUBSCRIPTION = 'reload-subscription'
Definition at line 69 of file ProjectParticipantsController.php.
LIST_ACTION_SUBSCRIBE
const LIST_ACTION_SUBSCRIBE = 'subscribe'
Definition at line 65 of file ProjectParticipantsController.php.
LIST_ACTION_UNSUBSCRIBE
const LIST_ACTION_UNSUBSCRIBE = 'unsubscribe'
Definition at line 66 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_DELIVERY_DISABLED
const LIST_SUBSCRIPTION_DELIVERY_DISABLED = 'delivery-disabled'
Definition at line 72 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_DELIVERY_ENABLED
const LIST_SUBSCRIPTION_DELIVERY_ENABLED = 'delivery-enabled'
Definition at line 71 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_DISABLED_BY_BOUNCES
const LIST_SUBSCRIPTION_DISABLED_BY_BOUNCES = 'disabled-by-bounces'
Definition at line 74 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_DISABLED_BY_MODERATOR
const LIST_SUBSCRIPTION_DISABLED_BY_MODERATOR = 'disabled-by-moderator'
Definition at line 75 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_DISABLED_BY_USER
const LIST_SUBSCRIPTION_DISABLED_BY_USER = 'disabled-by-user'
Definition at line 73 of file ProjectParticipantsController.php.
LIST_SUBSCRIPTION_MODE_DIGEST
const LIST_SUBSCRIPTION_MODE_DIGEST = 'mode-digest'
Definition at line 76 of file ProjectParticipantsController.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Controller/ProjectParticipantsController.php