CamerataDB: PostProjectUpdatedEvent Class Reference
PostProjectUpdatedEvent Class Reference
Dispatched after flushing entities to the data-base, but before the final commit.
Public Member Functions
getProjectId ()
getOldData ()
getNewData ()
Private Attributes
$projectId
$oldData
$newData
Detailed Description
Dispatched after flushing entities to the data-base, but before the final commit.
Definition at line 33 of file PostProjectUpdatedEvent.php.
Member Function Documentation
getNewData()
getNewData () inherited
Returns
array Get new project data.
Definition at line 82 of file ProjectUpdatedEvent.php.
References ProjectUpdatedEvent\$newData.
Referenced by EventsService\onProjectUpdated().
getOldData()
getOldData () inherited
Returns
array Get old project data.
Definition at line 76 of file ProjectUpdatedEvent.php.
References ProjectUpdatedEvent\$oldData.
Referenced by EventsService\onProjectUpdated().
getProjectId()
getProjectId () inherited
Returns
int Get project id.
Definition at line 70 of file ProjectUpdatedEvent.php.
Referenced by EventsService\onProjectUpdated().
Field Documentation
$newData
array $newData private inherited
[ 'id' => PROJECT_ID, 'name' => NAME, 'year' => YEAR, 'type' => TYPE ]
Definition at line 52 of file ProjectUpdatedEvent.php.
Referenced by ProjectUpdatedEvent\__construct(), and ProjectUpdatedEvent\getNewData().
$oldData
array $oldData private inherited
[ 'id' => PROJECT_ID, 'name' => NAME, 'year' => YEAR, 'type' => TYPE ]
Definition at line 44 of file ProjectUpdatedEvent.php.
Referenced by ProjectUpdatedEvent\__construct(), and ProjectUpdatedEvent\getOldData().
$projectId
int $projectId private inherited
Definition at line 36 of file ProjectUpdatedEvent.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Events/PostProjectUpdatedEvent.php