CamerataDB: UndoableRunQueue Class Reference
UndoableRunQueue Class Reference
Implement a stack of actions with undo-actions.
Public Member Functions
__construct (protected IAppContainer $appContainer, protected ILogger $logger, protected IL10N $l,)
{}
register (Closure|IUndoable $action, ?Closure $undo=null)
Register the given action in the run-queue.
clearActionQueue ()
Clears the action queue and the undo stack.
executeActions (bool $gracefully=false)
Run all registered actions.
executeUndo ()
Run all undo-actions on the undo stack.
getRunQueueExceptions ()
Get the list of thrown exceptions during the most recent execution of the run-queue.
getRunQueueException ()
Return only the first – if any – thrown exception during execution of the run-queue.
getUndoExceptions ()
Get the list of thrown exceptions during the most recent execution of the undo-queue.
size ()
active ()
executionCount ()
reset ()
Reset the queue in order to be executed again.
Protected Attributes
$actionQueue = []
$undoStack = null
$runQueueExceptions = []
$undoExceptions = []
$executing = false
Detailed Description
Implement a stack of actions with undo-actions.
Definition at line 39 of file UndoableRunQueue.php.
Constructor & Destructor Documentation
__construct()
__construct (protected IAppContainer $appContainer, protected ILogger $logger, protected IL10N $l)
{}
Definition at line 59 of file UndoableRunQueue.php.
Member Function Documentation
active()
active ()
Returns
bool Whether the queue has been run.
Definition at line 223 of file UndoableRunQueue.php.
clearActionQueue()
clearActionQueue ()
Clears the action queue and the undo stack.
Returns
void
Definition at line 97 of file UndoableRunQueue.php.
executeActions()
executeActions (bool $gracefully = false)
Run all registered actions.
Parameters
bool $gracefully Just log caught execptions, then retry with the next action.
Returns
bool \true if no exception has been caught, \false otherwise. Unless $gracefully was \true the function will throw an exception on error.
Exceptions
UndoableRunQueueException
Definition at line 117 of file UndoableRunQueue.php.
executeUndo()
executeUndo ()
Run all undo-actions on the undo stack.
The run-queue will continue even if exceptions occur during undo. At completion the undo-queue is empty.
Returns
void
Definition at line 157 of file UndoableRunQueue.php.
executionCount()
executionCount ()
Returns
null|int The number of successfully executed actions, or null if the queue has not yet been executed.
Definition at line 232 of file UndoableRunQueue.php.
getRunQueueException()
getRunQueueException ()
Return only the first – if any – thrown exception during execution of the run-queue.
There will be at most one exception if UndoableRunQueue::executeAction() had been executed with the $gracefully parameter set to \false.
Returns
null|Throwable
Definition at line 198 of file UndoableRunQueue.php.
References UndoableRunQueue\reset().
getRunQueueExceptions()
getRunQueueExceptions ()
Get the list of thrown exceptions during the most recent execution of the run-queue.
It can contain more than one exception if UndoableRunQueue::executeAction() had been executed with the $gracefully parameter set to \true, otherwise it will contain at most one exception.
Returns
array<int, Throwable>
Definition at line 185 of file UndoableRunQueue.php.
getUndoExceptions()
getUndoExceptions ()
Get the list of thrown exceptions during the most recent execution of the undo-queue.
Returns
array<int, Throwable>
Definition at line 211 of file UndoableRunQueue.php.
register()
register (Closure|IUndoable $action, ?Closure $undo = null)
Register the given action in the run-queue.
Parameters
Closure | IUndoable $action The action to be registered.
null | Closure $undo The undo action if $action is a mere Closure.
Returns
UndoableRunQueue
Exceptions
InvalidArgumentException If $action is neither a Closure nor an IUndoable.
Definition at line 78 of file UndoableRunQueue.php.
References IUndoable\initialize().
reset()
reset ()
Reset the queue in order to be executed again.
Returns
void
Definition at line 242 of file UndoableRunQueue.php.
Referenced by UndoableRunQueue\getRunQueueException().
size()
size ()
Returns
int The total number of registered actions.
Definition at line 217 of file UndoableRunQueue.php.
Field Documentation
$actionQueue
array $actionQueue = [] protected
Definition at line 44 of file UndoableRunQueue.php.
$executing
bool $executing = false protected
Definition at line 56 of file UndoableRunQueue.php.
$runQueueExceptions
array< int, Throwable > $runQueueExceptions = [] protected
Definition at line 50 of file UndoableRunQueue.php.
$undoExceptions
array< int, Throwable > $undoExceptions = [] protected
Definition at line 53 of file UndoableRunQueue.php.
$undoStack
array null $undoStack = null protected
Definition at line 47 of file UndoableRunQueue.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Common/UndoableRunQueue.php