CamerataDB: ToolTipsDataService Class Reference
ToolTipsDataService Class Reference
Data provider for the ToolTipsService in order to make loading of that class and constructing it more light weight.
Static Public Member Functions
static get ()
Return the array of all tooltips.
Static Private Member Functions
static t (string $text, mixed $parameters=[])
Just a shim which injects the content of the data-array into the to-be-translated strings.
Static Private Attributes
static $toolTipsData = null
Detailed Description
Data provider for the ToolTipsService in order to make loading of that class and constructing it more light weight.
Definition at line 36 of file ToolTipsDataService.php.
Member Function Documentation
get()
static get () static
Return the array of all tooltips.
Returns
array
Definition at line 77 of file ToolTipsDataService.php.
Referenced by ToolTipsService\count(), ToolTipsService\fetch(), and ToolTipsService\toolTips().
t()
static t (string $text, mixed $parameters = []) static private
Just a shim which injects the content of the data-array into the to-be-translated strings.
The actual translation will happen in the using classes.
Parameters
string $text
mixed $parameters
Returns
string
@SuppressWarnings(PHPMD.ShortMethodName)
Definition at line 51 of file ToolTipsDataService.php.
Field Documentation
$toolTipsData
$toolTipsData = null static private
Definition at line 70 of file ToolTipsDataService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/ToolTipsDataService.php