CamerataDB: ProjectPayments Class Reference
ProjectPayments Class Reference
Table generator for Instruments table.
Public Member Functions
__construct (ConfigService $configService, RequestParameterService $requestParameters, EntityManager $entityManager, PHPMyEdit $phpMyEdit, ToolTipsService $toolTipsService, PageNavigation $pageNavigation, private ProjectService $projectService, private ProjectParticipantFieldsService $participantFieldsService, private FinanceService $financeService, private UserStorage $userStorage, private DatabaseStorageUtil $databaseStorageUtil,)
{}
shortTitle ()
{
Returns
string Short title for heading.
}
beforeDeleteDoDeleteSubPayments (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Sub-payment aware delete.
beforeUpdateSanitizeFields (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, array &$changed, array &$newValues)
beforeInsertSanitizeFields (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, array &$changed, array &$newValues)
Remap the input values in order to satisfy the data-model:
isCompositeRowTag (?string $rowTag)
compositeRowOnly (mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme,)
Print only the values for the composite row.
componentRowOnly (mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme,)
Print only the values for the component row.
template ()
defaultOrdering ()
Determine if we have the default ordering of rows.
navigation (bool $enable)
Set table-navigation enable/disable.
execute (array $opts=[])
Run underlying table-manager (phpMyEdit for now).
export ($cellFilter=false, $lineCallback=false, string $css='noescape')
Quick and dirty general export.
getProjectName ()
getProjectId ()
cssClass ()
headerText ()
operation ()
addOperation ()
changeOperation ()
copyOperation ()
viewOperation ()
deleteOperation ()
listOperation ()
beforeAnythingTrimAnything (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
The phpMyEdit instance calls the triggers (callbacks) with the following arguments:
extractInstrumentRanking (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
The ranking of the mussician's instruments is implicitly stored in the order of the instrument ids.
beforeUpdateDoUpdateAll (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Before update-trigger which ideally should update all data such that nothing remains to do for phpMyEdit.
beforeInsertDoInsertAll (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Before insert-trigger which ideally should insert all data such that nothing remains to be done for phpMyEdit.
beforeDeleteSimplyDoDelete (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
This trigger simply deletes the given entity and prevents the legacy PHPMyEdit class to do the deletion in order to benefit from ORM.
preTrigger (PHPMyEdit &$pme, string $op, string $step)
The PHPMyEdit instance calls the trigger (callback) with the following arguments:
ensureUserIdSlug (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Possibly regenerate the user-id slug.
render (bool $execute=true)
Show the underlying template page.
cssPrefix ()
{
Returns
string
}
Static Public Member Functions
static beforeUpdateRemoveUnchanged (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
This is a phpMyEdit before-SOMETHING trigger.
static suspendLoggingTrigger (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Disable PME logging if it was enabled.
static resumeLoggingTrigger (PHPMyEdit &$pme, string $op, string $step, array &$oldValues, ?array &$changed, ?array &$newValues)
Resume PME logging if it was enabled at all.
static joinTableMasterFieldName ($tableInfo)
The name of the master join table field which triggers PME to actually do the join.
static musicianPublicNameSql (string $tableAlias=' $table', bool $firstNameFirst=false)
Generate an SQL fragment which composes a display name from the available name-parts sur_name, first_name, nick_name, display_name.
static musicianInProjectSql (string $projectIdSql, string $musicianId='id', string $tableAlias=' $table')
Return an SQL filter fragment to ensure that a musician-id is only in the request project.
Data Fields
const TEMPLATE = 'project-payments'
const TABLE = self::COMPOSITE_PAYMENTS_TABLE
const DEBIT_NOTES_TABLE = self::SEPA_BULK_TRANSACTIONS_TABLE
const SPLIT_DATABASE_STORAGE_ENTRIES_TABLE
const COMPOSITE_DATABASE_STORAGE_ENTRIES_TABLE
const ROW_TAG_PREFIX = '0;'
const MUSICIANS_TABLE = 'Musicians'
const MUSICIAN_EMAILS_TABLE = 'MusicianEmailAddresses'
const PROJECTS_TABLE = 'Projects'
const FIELD_TRANSLATIONS_TABLE = 'TableFieldTranslations'
const SEPA_BANK_ACCOUNTS_TABLE = 'SepaBankAccounts'
const SEPA_DEBIT_MANDATES_TABLE = 'SepaDebitMandates'
const SEPA_BULK_TRANSACTIONS_TABLE = 'SepaBulkTransactions'
const SEPA_BULK_TRANSACTION_DATA_TABLE = 'SepaBulkTransactionData'
const PROJECT_PARTICIPANTS_TABLE = 'ProjectParticipants'
const PROJECT_PARTICIPANT_FIELDS_TABLE = 'ProjectParticipantFields'
const PROJECT_PARTICIPANT_FIELDS_DATA_TABLE = 'ProjectParticipantFieldsData'
const PROJECT_PARTICIPANT_FIELDS_OPTIONS_TABLE = 'ProjectParticipantFieldsDataOptions'
const DATABASE_STORAGES_TABLE = 'DatabaseStorages'
const DATABASE_STORAGE_DIR_ENTRIES_TABLE = 'DatabaseStorageDirEntries'
const INSTRUMENTS_TABLE = 'Instruments'
const INSTRUMENT_INSURANCES_TABLE = 'InstrumentInsurances'
const PROJECT_PAYMENTS_TABLE = 'ProjectPayments'
const COMPOSITE_PAYMENTS_TABLE = 'CompositePayments'
const PROJECT_INSTRUMENTS_TABLE = 'ProjectInstruments'
const PROJECT_INSTRUMENTATION_NUMBERS_TABLE = 'ProjectInstrumentationNumbers'
const MUSICIAN_INSTRUMENTS_TABLE = 'MusicianInstruments'
const MUSICIAN_PHOTO_JOIN_TABLE = 'MusicianPhoto'
const FILES_TABLE = 'Files'
const SENT_EMAILS_TABLE = 'SentEmails'
const VALUES_SEP = ','
const JOIN_FIELD_NAME_SEPARATOR = ':'
const JOIN_KEY_SEP = ':'
const COMP_KEY_SEP = '-'
const VALUES_TABLE_SEP = '@'
const MASTER_FIELD_SUFFIX = '__master_key_'
const CSS_TAG_PROJECT_PARTICIPANT_FIELDS_DISPLAY = 'project-participant-fields-display'
CSS tag for displaying participant fields.
const CSS_TAG_SHOW_HIDE_DISABLED = 'show-hide-disabled'
const CSS_TAG_DIRECT_CHANGE = 'direct-change'
Protected Member Functions
participantFieldMultiplicityNames ()
participantFieldDataTypeNames ()
setTemplate (string $template)
mergeDefaultOptions (array $opts)
debugPrintValues (array $oldValues, array $changed, array $newValues, ?array $onlyKeys=null, ?string $prefix=null)
legacyRecordToEntityId (array $pmeRecordId, ?string $table=null)
Convert the given legacy PHPMyEdit record id as given by the member variable PHPMyEdit::rec to something understood by Doctrine\ORM.
legacyRecordToEntity (array $pmeRecordId)
Convert the given legacy PHPMyEdit record id as given by the member variable PHPMyEdit::rec to something understood by Doctrine\ORM.
defineJoinStructure (array &$opts)
Define a basic join-structure for phpMyEdit by using the information from self::$joinStructure.
compositeKeySlice (array $keys, array $entityId)
Slice the given entity id by the given keys and return a composite key joined with self::COMP_KEY_SEP.
joinTableField (string $fieldName)
Inverse of self::joinTableFieldName().
fieldIndex (array $fieldDescriptionData, $tableInfo, string $column)
Compute the index into the phpMyEdit field-description data of the given $tableInfo and $column.
makeJoinTableField (array &$fieldDescriptionData, $tableInfo, string $column, array $fdd=[])
Generate a join-table field, given join-table and field name.
addSlug (string $slug, array &$fdd)
Add a "slug" as tooltips-index and css-class.
tooltipSlug (string $slug)
Generate a "unified" tooltip-slug in order to obtain tool-tips from the ToolTipsService.
queryFieldIndex (string $key, array $fdd)
queryField (string $key, array $fdd)
queryIndexField (string $key, array $fdd)
joinQueryField ($tableInfo, string $column, array $fdd)
joinQueryIndexField ($tableInfo, string $column, array $fdd)
getTranslationLanguage (?IL10N $l10n=null)
We have this Nextcloud convention that de means "German personal Du" and de_DE means "German formal Sie".
makeFieldTranslationsJoin (array $joinInfo, $fields, bool $onlyTranslated=false)
Join with an in-database translation table.
makeFieldTranslationFddValues (array $joinInfo, string $field)
debug (string $message, array $context=[], int $shift=0)
Be noisy if debugging is enabled.
Static Protected Member Functions
static joinTableFieldName ($joinInfo, string $column)
The name of the field-descriptor for a join-table field referencing a master-join-table.
static unsetRequestValue (string $tag, ?array &$oldValues, array &$changed, array &$newValues)
Unset a value in the input vars of legacy PME triggers.
static trivialDescription (string $singleField=PHPMyEdit::TRIVIAL_DESCRIPION)
Create a trivial description definition with no casts and no NULL coalescing.
Protected Attributes
$joinStructure
const SEQUENCE_TABLE = 'seq_0_to_100000_step_1'
Hard-coded sequence table name.
const JOIN_FLAGS_NONE = 0x00
const JOIN_MASTER = 0x01
This entry of self::$joinStructure refers to the "master" table.
const JOIN_READONLY = 0x02
Do not add/change/delete any joined entities.
const JOIN_GROUP_BY = 0x04
Adds an SQL GROUP BY using the configured join-key and the keys of the master table.
const JOIN_REMOVE_EMPTY = 0x08
Remove entities when the value of the join-column is changed to something for which empty() returns true.
const JOIN_SINGLE_VALUED = 0x10
Assume the join is (at most) single valued.
const PME_NAVIGATION_NO_MULTI = 'GUD'
const PME_NAVIGATION_MULTI = 'GUDM'
IL10N $l
$pmeBare
$pmeRecordId
$showDisabled
$expertMode
$financeMode
$filterVisibility
$pmeOptions
< default PHPMyEdit options
$musicianId
$projectId
$projectName
$membersProjectId
$recordsPerPage
$defaultFDD
$changeSetSize = -1
Number of affected entries, fields or rows.
$debugRequests = false
< Debug web requests
$reloadOuterForm = false
< Request reload of ambient form/table
$joinTables = null
flat TABLE_NAME -> PMEjoinXY lookup-table for the join-tables generated by self::defineJoinStructure().
string $template
Private Member Functions
isCompositeRow (array $row, PHPMyEdit $pme)
Decide whether the current row refers to the composite payment or to a "split" project-payment.
selectiveRowDisplay (string $where, mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme,)
createDefaultFDD ()
The following maybe does not belong her, but gives some outdated docs for the field definitions (fdd).
findJoinColumnPivot (array $joinInfo, string $key)
Find the recursion end-point for a nested join description.
Private Attributes
$compositePaymentExpanded = []
Entities Project $project
Detailed Description
Table generator for Instruments table.
Definition at line 55 of file ProjectPayments.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, RequestParameterService $requestParameters, EntityManager $entityManager, PHPMyEdit $phpMyEdit, ToolTipsService $toolTipsService, PageNavigation $pageNavigation, private ProjectService $projectService, private ProjectParticipantFieldsService $participantFieldsService, private FinanceService $financeService, private UserStorage $userStorage, private DatabaseStorageUtil $databaseStorageUtil)
{}
Definition at line 274 of file ProjectPayments.php.
Member Function Documentation
addOperation()
addOperation () inherited
Returns
bool Are we in add mode?
Definition at line 540 of file PMETableViewBase.php.
Referenced by SepaBulkTransactions\render(), InstrumentFamilies\shortTitle(), Instruments\shortTitle(), and Musicians\shortTitle().
addSlug()
addSlug (string $slug, array & $fdd) protected inherited
Add a "slug" as tooltips-index and css-class.
Parameters
string $slug The tag to add.
array $fdd The field-description-data. It is modified in-place.
Returns
void
Definition at line 2464 of file PMETableViewBase.php.
References PMETableViewBase\cssClass(), and PMETableViewBase\tooltipSlug().
Referenced by PMETableViewBase\makeJoinTableField(), ProjectInstrumentationNumbers\render(), and ProjectParticipantFields\render().
beforeAnythingTrimAnything()
beforeAnythingTrimAnything (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
The phpMyEdit instance calls the triggers (callbacks) with the following arguments:
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
This trigger trims any spaces from the new fields. In order to sanitize old data records this trigger function adds to $changed if trimming changes something. Otherwise self::beforeUpdateRemoveUnchanged() would silently ignore the sanitized values.
Definition at line 820 of file PMETableViewBase.php.
References Util\normalizeSpaces().
beforeDeleteDoDeleteSubPayments()
beforeDeleteDoDeleteSubPayments (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues)
Sub-payment aware delete.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 1388 of file ProjectPayments.php.
beforeDeleteSimplyDoDelete()
beforeDeleteSimplyDoDelete (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
This trigger simply deletes the given entity and prevents the legacy PHPMyEdit class to do the deletion in order to benefit from ORM.
No fancy things are done, simply the deletion.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 2059 of file PMETableViewBase.php.
References PMETableViewBase\legacyRecordToEntityId().
beforeInsertDoInsertAll()
beforeInsertDoInsertAll (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
Before insert-trigger which ideally should insert all data such that nothing remains to be done for phpMyEdit.
The idea is to eventually abandon phpMyEdit and for the time being do as much as possible with the Doctrine ORM.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Bug
This method is too large.
Definition at line 1569 of file PMETableViewBase.php.
References PMETableViewBase\$changeSetSize, PMETableViewBase\compositeKeySlice(), PMETableViewBase\debug(), PMETableViewBase\debugPrintValues(), Util\explode(), Util\explodeIndexed(), Util\explodeIndexedMulti(), PMETableViewBase\findJoinColumnPivot(), PMETableViewBase\joinTableField(), PMETableViewBase\joinTableFieldName(), PMETableViewBase\joinTableMasterFieldName(), and Util\unsetValue().
Referenced by ProjectInstrumentationNumbers\render(), and ProjectParticipantFields\render().
beforeInsertSanitizeFields()
beforeInsertSanitizeFields (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, array & $changed, array & $newValues)
Remap the input values in order to satisfy the data-model:
one receivable per ProjectPayment
CompositePaymnt amount must be sum of all partial payments
CompositePayment subject is constructed from individual payments
However, on insert we only add a single "split" transaction. Further parts have to be added afterwards.
Copying sub-transactions is supported.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 1620 of file ProjectPayments.php.
beforeUpdateDoUpdateAll()
beforeUpdateDoUpdateAll (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
Before update-trigger which ideally should update all data such that nothing remains to do for phpMyEdit.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Bug
This function is too hackish and too long.
Todo
Cleanup. In particular, quite a bit of code is shared with $this->beforeInsertDoInsertAll().
Todo
needs more logic: disabled things would need to be reenabled instead of adding new stuff. One possibility would be to add disabled things as hidden elements in order to keep them out of the way of the select boxes of the user interface.
Definition at line 967 of file PMETableViewBase.php.
References PMETableViewBase\$changeSetSize, PMETableViewBase\$joinStructure, PMETableViewBase\compositeKeySlice(), PMETableViewBase\debug(), PMETableViewBase\debugPrintValues(), Util\explode(), Util\explodeIndexed(), Util\explodeIndexedMulti(), PMETableViewBase\findJoinColumnPivot(), PMETableViewBase\joinTableField(), PMETableViewBase\joinTableFieldName(), PMETableViewBase\joinTableMasterFieldName(), Util\removeSpaces(), and Util\unsetValue().
Referenced by ProjectParticipantFields\render().
beforeUpdateRemoveUnchanged()
static beforeUpdateRemoveUnchanged (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) static inherited
This is a phpMyEdit before-SOMETHING trigger.
The phpMyEdit class calls the trigger (callback) with the following arguments:
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 745 of file PMETableViewBase.php.
beforeUpdateSanitizeFields()
beforeUpdateSanitizeFields (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, array & $changed, array & $newValues)
 Remap the input values in order to satisfy the data-model:
 - one receivable per ProjectPayment
 - CompositePayment amount must be sum of all partial payments
 - CompositePayment subject is constructed from individual payments
 However, on insert we only add a single "split" transaction. Further
 parts have to be added afterwards.
update for composite
 BEFORE OLDVALS Array (
 [id] => 514
 [musician_id] => 407
 [sepa_transaction_id] =>
 [ProjectPayments:row_tag] => 0;514
 [Musicians:id] => 407
 [amount] => 15.00
 [ProjectPayments:amount] => 55.17,45.00
 [date_of_receipt] => 2022-01-13
 [subject] => asfasfasfa
 [ProjectPayments:subject] => sadfgdsafasd,sdafdasfas
 [ProjectPayments:id] => 976,978
 [ProjectParticipantFieldsDataOptions:composite_key] => 18-224-82fad011-04a6-11ec-9e3f-04e261401ed5,18-224-82fb239c-04a6-11ec-9e3f-04e261401ed5 )
 BEFORE NEWVALS Array (
 [id] => 514
 [musician_id] => 407
 [sepa_transaction_id] =>
 [ProjectPayments:row_tag] => 0;514
 [Musicians:id] => 407
 [amount] => 15.00
 [ProjectPayments:amount] => 55.17,45.00
 [date_of_receipt] => 2022-01-13 00:00:00
 [subject] => asfasfasfa
 [ProjectPayments:subject] => sadfgdsafasd,sdafdasfas
 [ProjectPayments:id] => 976,978
 [ProjectParticipantFieldsDataOptions:composite_key] => 18-224-82fad011-04a6-11ec-9e3f-04e261401ed5,18-224-82fb239c-04a6-11ec-9e3f-04e261401ed5 )
 @param PHPMyEdit $pme The phpMyEdit instance.
 @param string $op The operation, 'insert', 'update' etc.
 @param string $step 'before' or 'after'.
 @param array $oldValues Self-explanatory.
 @param array $changed Set of changed fields, may be modified by the callback.
 @param null|array $newValues Set of new values, which may also be modified.
 @return bool If returning @c false the operation will be terminated
Definition at line 1462 of file ProjectPayments.php.
changeOperation()
changeOperation () inherited
Returns
bool Are we in change mode?
Definition at line 546 of file PMETableViewBase.php.
Referenced by InstrumentFamilies\shortTitle(), Instruments\shortTitle(), Musicians\shortTitle(), ProjectParticipants\shortTitle(), and SepaBankAccounts\shortTitle().
componentRowOnly()
componentRowOnly (mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme)
Print only the values for the component row.
Parameters
mixed $value Value passed on from PME.
string $action Curent PME-action.
int $k Current PME fdd index.
array $row Row data from PME.
array $recordId Record-id of current row.
PHPMyEdit $pme The phpMyEdit instance.
Returns
string HTML fragment.
Todo
: if the search results (e.g. for the amount) do not contain the composite row, then the missing data should also be printed.
Definition at line 1782 of file ProjectPayments.php.
compositeKeySlice()
compositeKeySlice (array $keys, array $entityId) protected inherited
Slice the given entity id by the given keys and return a composite key joined with self::COMP_KEY_SEP.
Parameters
array $keys
array $entityId
Returns
string
Definition at line 2258 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), and PMETableViewBase\beforeUpdateDoUpdateAll().
compositeRowOnly()
compositeRowOnly (mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme)
Print only the values for the composite row.
Parameters
mixed $value Value passed on from PME.
string $action Curent PME-action.
int $k Current PME fdd index.
array $row Row data from PME.
array $recordId Record-id of current row.
PHPMyEdit $pme The phpMyEdit instance.
Returns
string HTML fragment.
Todo
: if the search results (e.g. for the amount) do not contain the composite row, then the missing data should also be printed.
Definition at line 1751 of file ProjectPayments.php.
copyOperation()
copyOperation () inherited
Returns
bool Are we in copy mode?
Definition at line 552 of file PMETableViewBase.php.
Referenced by InstrumentFamilies\shortTitle(), Instruments\shortTitle(), and Musicians\shortTitle().
createDefaultFDD()
createDefaultFDD () private inherited
The following maybe does not belong her, but gives some outdated docs for the field definitions (fdd).
Field definitions
Fields will be displayed left to right on the screen in the order in which they appear in generated list. Here are some most used field options documented.
['name'] is the title used for column headings, etc.; ['maxlen'] maximum length to display add/edit/search input boxes ['trimlen'] maximum length of string content to display in row listing ['width'] is an optional display width specification for the column e.g. ['width'] = '100px'; ['mask'] a string that is used by sprintf() to format field output ['sort'] true or false; means the users may sort the display on this column ['strip_tags'] true or false; whether to strip tags from content ['nowrap'] true or false; whether this field should get a NOWRAP ['select'] T - text, N - numeric, D - drop-down, M - multiple selection ['options'] optional parameter to control whether a field is displayed L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view Another flags are: R - indicates that a field is read only W - indicates that a field is a password field H - indicates that a field is to be hidden and marked as hidden ['URL'] is used to make a field 'clickable' in the display e.g.: 'mailto:$value', 'http://$value' or '$page?stuff'; ['URLtarget'] HTML target link specification (for example: _blank) ['textarea']['rows'] and/or ['textarea']['cols'] specifies a textarea is to be used to give multi-line input e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10 ['values'] restricts user input to the specified constants, e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99) ['values']['table'] and ['values']['column'] restricts user input to the values found in the specified column of another table ['values']['description'] = 'desc_column' The optional ['values']['description'] field allows the value(s) displayed to the user to be different to those in the ['values']['column'] field. This is useful for giving more meaning to column values. Multiple descriptions fields are also possible. Check documentation for this.
Returns
Some default settings for the PME options.
Definition at line 648 of file PMETableViewBase.php.
Referenced by PMETableViewBase\__construct().
cssClass()
cssClass () inherited
Returns
null|string
Reimplemented from Renderer.
Reimplemented in Musicians.
Definition at line 515 of file PMETableViewBase.php.
Referenced by PMETableViewBase\addSlug(), InstrumentInsurances\render(), and PMETableViewBase\tooltipSlug().
cssPrefix()
cssPrefix () inherited
{
Returns
string
}
Implements IRenderer.
Definition at line 47 of file Renderer.php.
Referenced by TaxExemptionNotices\headerText().
debug()
debug (string $message, array $context = [], int $shift = 0) protected inherited
Be noisy if debugging is enabled.
Debug can be switched on and off in the user interface if export-mode is enabled.
Parameters
string $message
array $context
int $shift
Returns
void
Definition at line 2726 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), PMETableViewBase\debugPrintValues(), and PMETableViewBase\extractInstrumentRanking().
debugPrintValues()
debugPrintValues (array $oldValues, array $changed, array $newValues, ?array $onlyKeys = null, ?string $prefix = null) protected inherited
Parameters
array $oldValues
array $changed
array $newValues
null | array $onlyKeys
null | string $prefix
Returns
void
Definition at line 867 of file PMETableViewBase.php.
References Util\arraySliceKeys(), and PMETableViewBase\debug().
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), InstrumentInsurances\beforeUpdateOrInsertTrigger(), and PMETableViewBase\extractInstrumentRanking().
defaultOrdering()
defaultOrdering () inherited
Determine if we have the default ordering of rows.
Returns
bool
Definition at line 442 of file PMETableViewBase.php.
defineJoinStructure()
defineJoinStructure (array & $opts) protected inherited
Define a basic join-structure for phpMyEdit by using the information from self::$joinStructure.
The array self::$joinStructure has the following structure:
[
  SQL_TABLE_NAME = [
    'table' => SQL_TABLE_NAME, // optional, will be added if not present
    'entity' => ENTITY_CLASS_NAME,
    'sql' => OPTIONAL_SUBQUERY_OR_CALLABLE_RETURNING_SUBQUERY,
    'flags'  => self::JOIN_READONLY|self::JOIN_MASTER|self::JOIN_REMOVE_EMPTY|self::JOIN_GROUP_BY
    'identifier' => [
       COLUMN_NAME => ID_COLUMN_DESCRIPTION, // see below
       ...
    ],
    'filter' => [
       COLUMN_NAME => ID_COLUMN_DESCRIPTION, // see below
       ...
    ],
    'column' => COLUMN_TO_FETCH,
  ],
  ...
]
ID_COLUMN_DESCRIPTION is one of the following
string OTHER_COLUMN Just another column name of the main-table
false "incomplete" key for grouping
array
[ 'value' => VALUE ] where VALUE may be again an array of values which are used to form an IN condition, false or null for "IS NULL", true for "IS NOT NULL". Any other value as string or number depending on its value. Strings are properly escaped.
[ 'table' => OTHER_TABLE, 'column' => COLUMN_IN_OTHER_TABLE, ]
[ 'self' => true ] like 'table' but with the same table and just this COLUMN_NAME as column.
The difference between 'filter' and 'identifier' is that the 'identifier' section is also used to update entities, while the 'filter' section simply defines further join restrictions.
Parameters
array $opts phpMyEdit options.
Returns
array [ TABLE_NAME => phpMyEdit_alias ]
Definition at line 2118 of file PMETableViewBase.php.
References PMETableViewBase\$joinTables, and PMETableViewBase\joinTableMasterFieldName().
Referenced by InstrumentFamilies\render(), InstrumentInsurances\render(), Instruments\render(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), ProjectParticipants\render(), and SepaBulkTransactions\render().
deleteOperation()
deleteOperation () inherited
Returns
bool Are we in delete mode?
Definition at line 564 of file PMETableViewBase.php.
Referenced by InstrumentFamilies\shortTitle(), Instruments\shortTitle(), Musicians\shortTitle(), ProjectParticipants\shortTitle(), and SepaBankAccounts\shortTitle().
ensureUserIdSlug()
ensureUserIdSlug (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
Possibly regenerate the user-id slug.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Todo
This would rather belong to some service class.
Definition at line 2755 of file PMETableViewBase.php.
References PMETableViewBase\joinTableFieldName().
execute()
execute (array $opts = []) inherited
Run underlying table-manager (phpMyEdit for now).
Parameters
array $opts
Returns
void
Implements IPageRenderer.
Definition at line 469 of file PMETableViewBase.php.
Referenced by InstrumentFamilies\render(), InstrumentInsurances\render(), Instruments\render(), InsuranceBrokers\render(), InsuranceRates\render(), and ProjectInstrumentationNumbers\render().
export()
export ($cellFilter = false, $lineCallback = false, string $css = 'noescape') inherited
Quick and dirty general export.
On each cell a call-back function is invoked with the html-output of that cell.
This is just like list_table(), i.e. only the chosen range of data is displayed and in html-display order.
Parameters
bool | callable $cellFilter $line[] = Callback($i, $j, $celldata).
bool | callable $lineCallback Callback($i, $line).
string $css CSS-class to pass to cellDisplay().
Returns
void
Definition at line 497 of file PMETableViewBase.php.
extractInstrumentRanking()
extractInstrumentRanking (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) inherited
The ranking of the mussician's instruments is implicitly stored in the order of the instrument ids.
Change the coressponding field to include the ranking explicitly.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 894 of file PMETableViewBase.php.
References PMETableViewBase\debug(), PMETableViewBase\debugPrintValues(), Util\explode(), PMETableViewBase\joinTableFieldName(), and Util\removeSpaces().
fieldIndex()
fieldIndex (array $fieldDescriptionData, $tableInfo, string $column) protected inherited
Compute the index into the phpMyEdit field-description data of the given $tableInfo and $column.
Parameters
array $fieldDescriptionData See phpMyEdit source code and look-out for "fdd".
string | array $tableInfo
See also
joinTableFieldName().
Parameters
string $column
See also
joinTableFieldName().
Returns
bool|int Result of array_search().
Definition at line 2364 of file PMETableViewBase.php.
References PMETableViewBase\joinTableFieldName().
findJoinColumnPivot()
findJoinColumnPivot (array $joinInfo, string $key) private inherited
Find the recursion end-point for a nested join description.
Parameters
array $joinInfo
string $key
Returns
Just the key-info array of $key.
Definition at line 931 of file PMETableViewBase.php.
References PMETableViewBase\findJoinColumnPivot().
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), and PMETableViewBase\findJoinColumnPivot().
getProjectId()
getProjectId () inherited
Returns
null|int
Definition at line 509 of file PMETableViewBase.php.
getProjectName()
getProjectName () inherited
Returns
null|string
Definition at line 503 of file PMETableViewBase.php.
getTranslationLanguage()
getTranslationLanguage (?IL10N $l10n = null) protected inherited
We have this Nextcloud convention that de means "German personal Du" and de_DE means "German formal Sie".
Unfortunately, even IL10N::getLocaleCode() just returns the language ... This function makes sure that we have a locale id like de_DE.
Parameters
null | IL10N $l10n
Returns
string
Definition at line 2574 of file PMETableViewBase.php.
Referenced by PMETableViewBase\makeFieldTranslationFddValues(), PMETableViewBase\makeFieldTranslationsJoin(), InstrumentFamilies\render(), and Instruments\render().
headerText()
headerText () inherited
Returns
Header text informations.
Todo
Display in popup in order not to bloat the small header space.
Implements IPageRenderer.
Reimplemented in InstrumentFamilies, Instruments, InsuranceBrokers, Musicians, ProjectInstrumentationNumbers, and TaxExemptionNotices.
Definition at line 528 of file PMETableViewBase.php.
isCompositeRow()
isCompositeRow (array $row, PHPMyEdit $pme) private
Decide whether the current row refers to the composite payment or to a "split" project-payment.
Parameters
array $row
PHPMyEdit $pme
Returns
bool
Definition at line 1802 of file ProjectPayments.php.
isCompositeRowTag()
isCompositeRowTag (?string $rowTag)
Parameters
string $rowTag The tag to examine.
Returns
boolean
Definition at line 1726 of file ProjectPayments.php.
joinQueryField()
joinQueryField ($tableInfo, string $column, array $fdd) protected inherited
Definition at line 2542 of file PMETableViewBase.php.
joinQueryIndexField()
joinQueryIndexField ($tableInfo, string $column, array $fdd) protected inherited
Definition at line 2559 of file PMETableViewBase.php.
joinTableField()
joinTableField (string $fieldName) protected inherited
Inverse of self::joinTableFieldName().
Parameters
string $fieldName
Returns
array The argument $fieldName split into parsts
[ 'table' => TABLE, 'column' => COLUMN ]
.
Definition at line 2335 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), and PMETableViewBase\beforeUpdateDoUpdateAll().
joinTableFieldName()
static joinTableFieldName ($joinInfo, string $column) static protected inherited
The name of the field-descriptor for a join-table field referencing a master-join-table.
Parameters
string | array $joinInfo Table-description-data
[
  'table' => SQL_TABLE_NAME,
  'entity' => DOCTRINE_ORM_ENTITY_CLASS_NAME,
  'flags'  => self::JOIN_READONLY|self::JOIN_MASTER|self::JOIN_REMOVE_EMPTY|self::JOIN_GROUP_BY
  'column' => column used in select statements
  'identifier' => [
    TO_JOIN_TABLE_COLUMN => ALREADY_THERE_COLUMN_NAME,
    ...
  ]
]
.
string $column column to generate a query field for. This is another column different from $joinInfo['column'] in order to generate further query fields from an existing join-table.
Returns
string Cooked field-name composed of $joinInfo and $column.
Definition at line 2312 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), PMETableViewBase\ensureUserIdSlug(), PMETableViewBase\extractInstrumentRanking(), PMETableViewBase\fieldIndex(), PMETableViewBase\makeJoinTableField(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), ProjectParticipants\render(), and SepaBulkTransactions\render().
joinTableMasterFieldName()
static joinTableMasterFieldName ($tableInfo) static inherited
The name of the master join table field which triggers PME to actually do the join.
Parameters
string | array $tableInfo
See also
joinTableFieldName().
Returns
string
See also
OCA\CAFEVDB\Controller\SepaBulkTransactionsController::generateBulkTransaction()
Definition at line 2278 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), PMETableViewBase\beforeUpdateDoUpdateAll(), PMETableViewBase\defineJoinStructure(), and PMETableViewBase\makeJoinTableField().
legacyRecordToEntity()
legacyRecordToEntity (array $pmeRecordId) protected inherited
Convert the given legacy PHPMyEdit record id as given by the member variable PHPMyEdit::rec to something understood by Doctrine\ORM.
Parameters
array $pmeRecordId
Returns
object
Definition at line 2033 of file PMETableViewBase.php.
References PMETableViewBase\legacyRecordToEntityId().
Referenced by Musicians\beforeDeleteTrigger().
legacyRecordToEntityId()
legacyRecordToEntityId (array $pmeRecordId, ?string $table = null) protected inherited
Convert the given legacy PHPMyEdit record id as given by the member variable PHPMyEdit::rec to something understood by Doctrine\ORM.
Parameters
array $pmeRecordId
null | string $table
Returns
array
Definition at line 2002 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeDeleteSimplyDoDelete(), and PMETableViewBase\legacyRecordToEntity().
listOperation()
listOperation () inherited
Returns
bool Are we in list mode?
Definition at line 570 of file PMETableViewBase.php.
Referenced by Musicians\__construct(), and Projects\__construct().
makeFieldTranslationFddValues()
makeFieldTranslationFddValues (array $joinInfo, string $field) protected inherited
Parameters
string | array $joinInfo Table-description-data.
string $field
Returns
array
See also
joinTableFieldName()
Definition at line 2668 of file PMETableViewBase.php.
References PMETableViewBase\getTranslationLanguage().
makeFieldTranslationsJoin()
makeFieldTranslationsJoin (array $joinInfo, $fields, bool $onlyTranslated = false) protected inherited
Join with an in-database translation table.
The following fields are provided:
l10n_FIELD – translated field will fallback translation to original value
translated_FIELD – translated field without fallback to original value
original_FIELD – untranslated field with fallback to translated value
untranslated_FIELD – untranslated field without fallback to translated value
Parameters
array $joinInfo Join desciption, see PMETableViewBase::defineJoinStructure().
string | array $fields Single field-name as string or array of field-names.
bool $onlyTranslated Only fetch line with translation values.
Returns
string SQL fragment.
Definition at line 2602 of file PMETableViewBase.php.
References PMETableViewBase\getTranslationLanguage().
Referenced by InstrumentFamilies\render(), Instruments\render(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), and ProjectParticipants\render().
makeJoinTableField()
makeJoinTableField (array & $fieldDescriptionData, $tableInfo, string $column, array $fdd = []) protected inherited
Generate a join-table field, given join-table and field name.
Parameters
array $fieldDescriptionData See phpMyEdit source code and look-out for "fdd".
string | array $tableInfo
See also
joinTableFieldName().
Parameters
string $column SQL column.
array $fdd Override FDD, see phpMyEdit.
Returns
array
[ INDEX, FIELDNAME ]
Definition at line 2387 of file PMETableViewBase.php.
References PMETableViewBase\addSlug(), Util\arrayMergeRecursive(), PMETableViewBase\joinTableFieldName(), and PMETableViewBase\joinTableMasterFieldName().
Referenced by InstrumentFamilies\render(), InstrumentInsurances\render(), Instruments\render(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), ProjectParticipants\render(), and SepaBulkTransactions\render().
mergeDefaultOptions()
mergeDefaultOptions (array $opts) protected inherited
Parameters
array $opts Options to be merged in the default options.
Returns
array Merged options array.
Definition at line 580 of file PMETableViewBase.php.
musicianInProjectSql()
static musicianInProjectSql (string $projectIdSql, string $musicianId = 'id', string $tableAlias = '$table') static inherited
Return an SQL filter fragment to ensure that a musician-id is only in the request project.
Parameters
string $projectIdSql SQL to get the projects id.
string $musicianId Field holding the musician id.
string $tableAlias Table alias to use.
Returns
string SQL fragment.
Definition at line 2924 of file PMETableViewBase.php.
musicianPublicNameSql()
static musicianPublicNameSql (string $tableAlias = '$table', bool $firstNameFirst = false) static inherited
Generate an SQL fragment which composes a display name from the available name-parts sur_name, first_name, nick_name, display_name.
Parameters
string $tableAlias Table to refer to, refers to placeholder '$table'.
bool $firstNameFirst
Returns
string SQL fragment.
Definition at line 2887 of file PMETableViewBase.php.
navigation()
navigation (bool $enable) inherited
Set table-navigation enable/disable.
Parameters
bool $enable
Returns
void
Implements IPageRenderer.
Definition at line 457 of file PMETableViewBase.php.
operation()
operation () inherited
Returns
string Operation of underlying legacy PHPMyEdit.
Definition at line 534 of file PMETableViewBase.php.
participantFieldDataTypeNames()
participantFieldDataTypeNames () protected inherited
Returns
array The translated field-data-type names.
See also
DBTypes\EnumParticipantFieldDataType
Definition at line 410 of file PMETableViewBase.php.
Referenced by ProjectParticipantFields\render().
participantFieldMultiplicityNames()
participantFieldMultiplicityNames () protected inherited
Returns
array The translated field-multiplicity names.
See also
DBTypes\EnumParticipantFieldMultiplicity
Definition at line 394 of file PMETableViewBase.php.
Referenced by ProjectParticipantFields\render().
preTrigger()
preTrigger (PHPMyEdit & $pme, string $op, string $step) inherited
The PHPMyEdit instance calls the trigger (callback) with the following arguments:
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after' or 'pre'.
Returns
boolean If returning false the operation will be terminated.
Definition at line 2449 of file PMETableViewBase.php.
queryField()
queryField (string $key, array $fdd) protected inherited
Parameters
string $key
array $fdd
Returns
string 'qf'.N.
Definition at line 2513 of file PMETableViewBase.php.
Referenced by PMETableViewBase\queryIndexField(), InstrumentInsurances\render(), Instruments\render(), and ProjectParticipantFields\render().
queryFieldIndex()
queryFieldIndex (string $key, array $fdd) protected inherited
Parameters
string $key
array $fdd
Returns
bool|int Result from array_search().
Definition at line 2501 of file PMETableViewBase.php.
queryIndexField()
queryIndexField (string $key, array $fdd) protected inherited
Parameters
string $key
array $fdd
Returns
string 'qf'.N.'_idx'.
Definition at line 2525 of file PMETableViewBase.php.
References PMETableViewBase\queryField().
Referenced by InstrumentInsurances\render().
render()
render (bool $execute = true) inherited
Show the underlying template page.
This is supposed to echo html code to stdout. This is the default do-nothing implementation.
Parameters
bool $execute Kind of dry-run if set to false.
Returns
void
Implements IRenderer.
Reimplemented in InstrumentFamilies, InstrumentInsurances, Instruments, InsuranceBrokers, InsuranceRates, ProjectInstrumentationNumbers, ProjectParticipantFields, ProjectParticipants, and SepaBulkTransactions.
Definition at line 41 of file Renderer.php.
resumeLoggingTrigger()
static resumeLoggingTrigger (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) static inherited
Resume PME logging if it was enabled at all.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 791 of file PMETableViewBase.php.
selectiveRowDisplay()
selectiveRowDisplay (string $where, mixed $value, string $action, int $k, array $row, array $recordId, PHPMyEdit $pme) private
Parameters
string $where
mixed $value Value passed on from PME.
string $action Curent PME-action.
int $k Current PME fdd index.
array $row Row data from PME.
array $recordId Record-id of current row.
PHPMyEdit $pme The phpMyEdit instance.
Returns
null|string HTML fragment or null.
Definition at line 1825 of file ProjectPayments.php.
setTemplate()
setTemplate (string $template) protected inherited
Parameters
string $template Template name to set.
Returns
void
Definition at line 432 of file PMETableViewBase.php.
Referenced by Musicians\disableProjectMode(), and Musicians\enableProjectMode().
shortTitle()
shortTitle ()
{
Returns
string Short title for heading.
}
Reimplemented from PMETableViewBase.
Definition at line 297 of file ProjectPayments.php.
suspendLoggingTrigger()
static suspendLoggingTrigger (PHPMyEdit & $pme, string $op, string $step, array & $oldValues, ?array & $changed, ?array & $newValues) static inherited
Disable PME logging if it was enabled.
Parameters
PHPMyEdit $pme The phpMyEdit instance.
string $op The operation, 'insert', 'update' etc.
string $step 'before' or 'after'.
array $oldValues Self-explanatory.
array $changed Set of changed fields, may be modified by the callback.
null | array $newValues Set of new values, which may also be modified.
Returns
bool If returning false the operation will be terminated
Definition at line 768 of file PMETableViewBase.php.
template()
template () inherited
Returns
null|string $this->template.
Definition at line 422 of file PMETableViewBase.php.
tooltipSlug()
tooltipSlug (string $slug) protected inherited
Generate a "unified" tooltip-slug in order to obtain tool-tips from the ToolTipsService.
Parameters
string $slug
Returns
string
Definition at line 2489 of file PMETableViewBase.php.
References PMETableViewBase\cssClass().
Referenced by PMETableViewBase\addSlug().
trivialDescription()
static trivialDescription (string $singleField = PHPMyEdit::TRIVIAL_DESCRIPION) static protected inherited
Create a trivial description definition with no casts and no NULL coalescing.
Parameters
string $singleField
Returns
array Description array for 'values' FDD component.
Definition at line 2939 of file PMETableViewBase.php.
Referenced by InstrumentInsurances\render().
unsetRequestValue()
static unsetRequestValue (string $tag, ?array & $oldValues, array & $changed, array & $newValues) static protected inherited
Unset a value in the input vars of legacy PME triggers.
Parameters
string $tag
null | array $oldValues From database.
array $changed Computed change-set form legacy PME.
array $newValues New values from input form.
Returns
void
Definition at line 2705 of file PMETableViewBase.php.
References Util\unsetValue().
viewOperation()
viewOperation () inherited
Returns
bool Are we in view mode?
Definition at line 558 of file PMETableViewBase.php.
Referenced by InstrumentFamilies\shortTitle(), Instruments\shortTitle(), Musicians\shortTitle(), ProjectParticipants\shortTitle(), and SepaBankAccounts\shortTitle().
Field Documentation
$changeSetSize
int $changeSetSize = -1 protected inherited
Number of affected entries, fields or rows.
Context dependent, for generating messages.
Definition at line 206 of file PMETableViewBase.php.
Referenced by PMETableViewBase\beforeInsertDoInsertAll(), and PMETableViewBase\beforeUpdateDoUpdateAll().
$compositePaymentExpanded
array $compositePaymentExpanded = [] private
Definition at line 71 of file ProjectPayments.php.
$debugRequests
bool $debugRequests = false protected inherited
< Debug web requests
Definition at line 209 of file PMETableViewBase.php.
$defaultFDD
array $defaultFDD protected inherited
Definition at line 200 of file PMETableViewBase.php.
$expertMode
bool $expertMode protected inherited
Definition at line 172 of file PMETableViewBase.php.
$filterVisibility
bool $filterVisibility protected inherited
Definition at line 178 of file PMETableViewBase.php.
$financeMode
bool $financeMode protected inherited
Definition at line 175 of file PMETableViewBase.php.
$joinStructure
$joinStructure protected
Definition at line 76 of file ProjectPayments.php.
$joinTables
ArrayObject $joinTables = null protected inherited
flat TABLE_NAME -> PMEjoinXY lookup-table for the join-tables generated by self::defineJoinStructure().
Definition at line 241 of file PMETableViewBase.php.
Referenced by PMETableViewBase\defineJoinStructure(), InstrumentFamilies\render(), InstrumentInsurances\render(), Instruments\render(), ProjectInstrumentationNumbers\render(), ProjectParticipantFields\render(), and SepaBulkTransactions\render().
$l
IL10N $l protected inherited
Definition at line 160 of file PMETableViewBase.php.
$membersProjectId
int $membersProjectId protected inherited
Definition at line 194 of file PMETableViewBase.php.
$musicianId
int $musicianId protected inherited
Definition at line 185 of file PMETableViewBase.php.
$pmeBare
bool $pmeBare protected inherited
Definition at line 163 of file PMETableViewBase.php.
$pmeOptions
array $pmeOptions protected inherited
< default PHPMyEdit options
Definition at line 181 of file PMETableViewBase.php.
$pmeRecordId
array mixed $pmeRecordId protected inherited
Definition at line 166 of file PMETableViewBase.php.
$project
Entities Project $project private
Definition at line 74 of file ProjectPayments.php.
$projectId
int $projectId protected inherited
Definition at line 188 of file PMETableViewBase.php.
$projectName
string $projectName protected inherited
Definition at line 191 of file PMETableViewBase.php.
$recordsPerPage
int $recordsPerPage protected inherited
Definition at line 197 of file PMETableViewBase.php.
$reloadOuterForm
bool $reloadOuterForm = false protected inherited
< Request reload of ambient form/table
Definition at line 213 of file PMETableViewBase.php.
$showDisabled
bool $showDisabled protected inherited
Definition at line 169 of file PMETableViewBase.php.
$template
string $template protected inherited
Definition at line 31 of file Renderer.php.
COMP_KEY_SEP
const COMP_KEY_SEP = '-' inherited
Definition at line 141 of file PMETableViewBase.php.
COMPOSITE_DATABASE_STORAGE_ENTRIES_TABLE
const COMPOSITE_DATABASE_STORAGE_ENTRIES_TABLE
Initial value:
=
    self::DATABASE_STORAGE_DIR_ENTRIES_TABLE . self::VALUES_TABLE_SEP . 'composite'
Definition at line 65 of file ProjectPayments.php.
COMPOSITE_PAYMENTS_TABLE
const COMPOSITE_PAYMENTS_TABLE = 'CompositePayments' inherited
Definition at line 130 of file PMETableViewBase.php.
CSS_TAG_DIRECT_CHANGE
const CSS_TAG_DIRECT_CHANGE = 'direct-change' inherited
Definition at line 154 of file PMETableViewBase.php.
CSS_TAG_PROJECT_PARTICIPANT_FIELDS_DISPLAY
const CSS_TAG_PROJECT_PARTICIPANT_FIELDS_DISPLAY = 'project-participant-fields-display' inherited
CSS tag for displaying participant fields.
Definition at line 152 of file PMETableViewBase.php.
Referenced by ProjectParticipants\render().
CSS_TAG_SHOW_HIDE_DISABLED
const CSS_TAG_SHOW_HIDE_DISABLED = 'show-hide-disabled' inherited
Definition at line 153 of file PMETableViewBase.php.
DATABASE_STORAGE_DIR_ENTRIES_TABLE
const DATABASE_STORAGE_DIR_ENTRIES_TABLE = 'DatabaseStorageDirEntries' inherited
Definition at line 126 of file PMETableViewBase.php.
DATABASE_STORAGES_TABLE
const DATABASE_STORAGES_TABLE = 'DatabaseStorages' inherited
Definition at line 125 of file PMETableViewBase.php.
DEBIT_NOTES_TABLE
const DEBIT_NOTES_TABLE = self::SEPA_BULK_TRANSACTIONS_TABLE
Definition at line 62 of file ProjectPayments.php.
FIELD_TRANSLATIONS_TABLE
const FIELD_TRANSLATIONS_TABLE = 'TableFieldTranslations' inherited
Definition at line 116 of file PMETableViewBase.php.
FILES_TABLE
const FILES_TABLE = 'Files' inherited
Definition at line 135 of file PMETableViewBase.php.
INSTRUMENT_INSURANCES_TABLE
const INSTRUMENT_INSURANCES_TABLE = 'InstrumentInsurances' inherited
Definition at line 128 of file PMETableViewBase.php.
INSTRUMENTS_TABLE
const INSTRUMENTS_TABLE = 'Instruments' inherited
Definition at line 127 of file PMETableViewBase.php.
JOIN_FIELD_NAME_SEPARATOR
const JOIN_FIELD_NAME_SEPARATOR = ':' inherited
Definition at line 139 of file PMETableViewBase.php.
JOIN_FLAGS_NONE
const JOIN_FLAGS_NONE = 0x00 protected inherited
Definition at line 68 of file PMETableViewBase.php.
JOIN_GROUP_BY
const JOIN_GROUP_BY = 0x04 protected inherited
Adds an SQL GROUP BY using the configured join-key and the keys of the master table.
Definition at line 84 of file PMETableViewBase.php.
JOIN_KEY_SEP
const JOIN_KEY_SEP = ':' inherited
Definition at line 140 of file PMETableViewBase.php.
JOIN_MASTER
const JOIN_MASTER = 0x01 protected inherited
This entry of self::$joinStructure refers to the "master" table.
Definition at line 73 of file PMETableViewBase.php.
JOIN_READONLY
const JOIN_READONLY = 0x02 protected inherited
Do not add/change/delete any joined entities.
Definition at line 78 of file PMETableViewBase.php.
Referenced by Instruments\render(), and OCA\CAFEVDB\PageRenderer\FieldTraits\renderSepaAccounts().
JOIN_REMOVE_EMPTY
const JOIN_REMOVE_EMPTY = 0x08 protected inherited
Remove entities when the value of the join-column is changed to something for which empty() returns true.
Definition at line 90 of file PMETableViewBase.php.
JOIN_SINGLE_VALUED
const JOIN_SINGLE_VALUED = 0x10 protected inherited
Assume the join is (at most) single valued.
Otherwise the values are split by PMETableViewBase::VALUES_SEP (comma). If this flag is set, then the expected format of the data field is
JOIN_KEY:VALUES
and VALUES may contain self::VALUES_SEP (comma) and self::JOIN_KEY_SEP (colon). If this flag is not set then the expected format is
KEY1:VALUE1,KEY2:VALUE2,...
Consequently, the VALUEX must not contain commas and colons in the absence of this flag.
Definition at line 111 of file PMETableViewBase.php.
MASTER_FIELD_SUFFIX
const MASTER_FIELD_SUFFIX = '__master_key_' inherited
Definition at line 144 of file PMETableViewBase.php.
MUSICIAN_EMAILS_TABLE
const MUSICIAN_EMAILS_TABLE = 'MusicianEmailAddresses' inherited
Definition at line 114 of file PMETableViewBase.php.
MUSICIAN_INSTRUMENTS_TABLE
const MUSICIAN_INSTRUMENTS_TABLE = 'MusicianInstruments' inherited
Definition at line 133 of file PMETableViewBase.php.
MUSICIAN_PHOTO_JOIN_TABLE
const MUSICIAN_PHOTO_JOIN_TABLE = 'MusicianPhoto' inherited
Definition at line 134 of file PMETableViewBase.php.
MUSICIANS_TABLE
const MUSICIANS_TABLE = 'Musicians' inherited
Definition at line 113 of file PMETableViewBase.php.
PME_NAVIGATION_MULTI
const PME_NAVIGATION_MULTI = 'GUDM' protected inherited
Definition at line 157 of file PMETableViewBase.php.
PME_NAVIGATION_NO_MULTI
const PME_NAVIGATION_NO_MULTI = 'GUD' protected inherited
Definition at line 156 of file PMETableViewBase.php.
PROJECT_INSTRUMENTATION_NUMBERS_TABLE
const PROJECT_INSTRUMENTATION_NUMBERS_TABLE = 'ProjectInstrumentationNumbers' inherited
Definition at line 132 of file PMETableViewBase.php.
PROJECT_INSTRUMENTS_TABLE
const PROJECT_INSTRUMENTS_TABLE = 'ProjectInstruments' inherited
Definition at line 131 of file PMETableViewBase.php.
PROJECT_PARTICIPANT_FIELDS_DATA_TABLE
const PROJECT_PARTICIPANT_FIELDS_DATA_TABLE = 'ProjectParticipantFieldsData' inherited
Definition at line 123 of file PMETableViewBase.php.
PROJECT_PARTICIPANT_FIELDS_OPTIONS_TABLE
const PROJECT_PARTICIPANT_FIELDS_OPTIONS_TABLE = 'ProjectParticipantFieldsDataOptions' inherited
Definition at line 124 of file PMETableViewBase.php.
PROJECT_PARTICIPANT_FIELDS_TABLE
const PROJECT_PARTICIPANT_FIELDS_TABLE = 'ProjectParticipantFields' inherited
Definition at line 122 of file PMETableViewBase.php.
PROJECT_PARTICIPANTS_TABLE
const PROJECT_PARTICIPANTS_TABLE = 'ProjectParticipants' inherited
Definition at line 121 of file PMETableViewBase.php.
PROJECT_PAYMENTS_TABLE
const PROJECT_PAYMENTS_TABLE = 'ProjectPayments' inherited
Definition at line 129 of file PMETableViewBase.php.
PROJECTS_TABLE
const PROJECTS_TABLE = 'Projects' inherited
Definition at line 115 of file PMETableViewBase.php.
ROW_TAG_PREFIX
const ROW_TAG_PREFIX = '0;'
Definition at line 68 of file ProjectPayments.php.
SENT_EMAILS_TABLE
const SENT_EMAILS_TABLE = 'SentEmails' inherited
Definition at line 136 of file PMETableViewBase.php.
SEPA_BANK_ACCOUNTS_TABLE
const SEPA_BANK_ACCOUNTS_TABLE = 'SepaBankAccounts' inherited
Definition at line 117 of file PMETableViewBase.php.
SEPA_BULK_TRANSACTION_DATA_TABLE
const SEPA_BULK_TRANSACTION_DATA_TABLE = 'SepaBulkTransactionData' inherited
Definition at line 120 of file PMETableViewBase.php.
SEPA_BULK_TRANSACTIONS_TABLE
const SEPA_BULK_TRANSACTIONS_TABLE = 'SepaBulkTransactions' inherited
Definition at line 119 of file PMETableViewBase.php.
SEPA_DEBIT_MANDATES_TABLE
const SEPA_DEBIT_MANDATES_TABLE = 'SepaDebitMandates' inherited
Definition at line 118 of file PMETableViewBase.php.
SEQUENCE_TABLE
const SEQUENCE_TABLE = 'seq_0_to_100000_step_1' protected inherited
Hard-coded sequence table name.
This relies on
https://mariadb.com/kb/en/sequence-storage-engine/
Definition at line 66 of file PMETableViewBase.php.
SPLIT_DATABASE_STORAGE_ENTRIES_TABLE
const SPLIT_DATABASE_STORAGE_ENTRIES_TABLE
Initial value:
=
    self::DATABASE_STORAGE_DIR_ENTRIES_TABLE . self::VALUES_TABLE_SEP . 'split'
Definition at line 63 of file ProjectPayments.php.
TABLE
const TABLE = self::COMPOSITE_PAYMENTS_TABLE
Definition at line 61 of file ProjectPayments.php.
TEMPLATE
const TEMPLATE = 'project-payments'
Definition at line 60 of file ProjectPayments.php.
VALUES_SEP
const VALUES_SEP = ',' inherited
Definition at line 138 of file PMETableViewBase.php.
VALUES_TABLE_SEP
const VALUES_TABLE_SEP = '@' inherited
Definition at line 142 of file PMETableViewBase.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/PageRenderer/ProjectPayments.php