CamerataDB: AuthorizationService Class Reference
AuthorizationService Class Reference
Rudimentary service which just checks if a user belongs to the configured orchestra group and/or is a group admin.
Public Member Functions
__construct (private ?string $appName, private ?string $userId, protected IConfig $config, private IUserManager $userManager, private IGroupManager $groupManager, private IGroupSubAdminManager $groupSubAdminManager, protected ILogger $logger,)
getUserPermissions (?string $userId)
Compute the permission mask for the given or the currently logged-on user.
authorized (?string $userId, int $requestedPermissions=self::PERMISSION_ALL)
Basic check for authorization.
isAdmin (?string $userId)
Check whether the given user-id is a sub-admin for the configured orchestra group.
Data Fields
const MANAGEMENT = 'management'
const FRONTEND = 'frontend'
const ADDRESSBOOK = 'addressbook'
const FILESYSTEM = 'filesystem'
const CALENDAR = 'calendar'
const FINANCE = 'finance'
const EMAIL = 'email'
const ALL_GROUP_SUFFIX = ''
const MANAGEMENT_GROUP_SUFFIX = '-' . self::MANAGEMENT
const FRONTEND_GROUP_SUFFIX = '-' . self::FRONTEND
const ADDRESSBOOK_GROUP_SUFFIX = '-' . self::ADDRESSBOOK
const FILESYSTEM_GROUP_SUFFIX = '-' . self::FILESYSTEM
const CALENDAR_GROUP_SUFFIX = '-' . self::CALENDAR
const FINANCE_GROUP_SUFFIX = '-' . self::FINANCE
const EMAIL_GROUP_SUFFIX = '-' . self::EMAIL
const PERMISSION_NONE = 0
const PERMISSION_FRONTEND = (1 << 0)
const PERMISSION_ADDRESSBOOK = (1 << 1)
const PERMISSION_FILESYSTEM = (1 << 2)
const PERMISSION_CALENDAR = (1 << 3)
const PERMISSION_FINANCE = (1 << 4)
const PERMISSION_MANAGEMENT = (1 << 5)
const PERMISSION_EMAIL = (1 << 6)
const PERMISSION_ALL
Protected Member Functions
logPermissions (?string $userId, int $permissions, int $logLevel=\OCP\ILogger::INFO)
Log a textual description of the given permission bit-mask.
Private Attributes
$userGroupId
The group id of cloud users which are allowed to access the backend services like file-system etc.
Detailed Description
Rudimentary service which just checks if a user belongs to the configured orchestra group and/or is a group admin.
Also provide contact informations for the group-admins.
Definition at line 41 of file AuthorizationService.php.
Constructor & Destructor Documentation
__construct()
__construct (private ?string $appName, private ?string $userId, protected IConfig $config, private IUserManager $userManager, private IGroupManager $groupManager, private IGroupSubAdminManager $groupSubAdminManager, protected ILogger $logger)
Parameters
null | string $appName
null | string $userId Current logged on user id or null.
IConfig $config
IUserManager $userManager
IGroupManager $groupManager
IGroupSubAdminManager $groupSubAdminManager
ILogger $logger In order to satisfy LoggerTrait.
Definition at line 133 of file AuthorizationService.php.
Member Function Documentation
authorized()
authorized (?string $userId, int $requestedPermissions = self::PERMISSION_ALL)
Basic check for authorization.
Permissions are granted on the basis of group memberships.
Parameters
null | string $userId Id of the user to check.
int $requestedPermissions The permissions to check for. Defaults to everything.
Returns
bool Status of the check.
Definition at line 230 of file AuthorizationService.php.
References AuthorizationService\getUserPermissions().
Referenced by Application\boot().
getUserPermissions()
getUserPermissions (?string $userId)
Compute the permission mask for the given or the currently logged-on user.
Parameters
null | string $userId The user-id to check, if null use the user-id of the currently logged-on user.
Returns
int The bit-mask of permissions, based on the group-memberships of the user.
Definition at line 199 of file AuthorizationService.php.
Referenced by EncryptionService\__construct(), and AuthorizationService\authorized().
isAdmin()
isAdmin (?string $userId)
Check whether the given user-id is a sub-admin for the configured orchestra group.
Parameters
null | string $userId Id of the user to check.
Returns
bool Status of the check.
Definition at line 245 of file AuthorizationService.php.
logPermissions()
logPermissions (?string $userId, int $permissions, int $logLevel = \OCP\ILogger::INFO) protected
Log a textual description of the given permission bit-mask.
Parameters
null | string $userId The user-id to check, if null use the user-id of the currently logged-on user.
int $permissions
int $logLevel
Returns
void
Definition at line 157 of file AuthorizationService.php.
Field Documentation
$userGroupId
string $userGroupId private
Initial value:
=[,,,,,,,,]
  public const IMPLIED_PERMISSIONS
    self::PERMISSION_ALL => 0
    self::PERMISSION_MANAGEMENT => self::PERMISSION_ALL
    self::PERMISSION_FRONTEND => self::PERMISSION_ALL
    self::PERMISSION_ADDRESSBOOK => 0
    self::PERMISSION_FILESYSTEM => 0
    self::PERMISSION_CALENDAR => 0
    self::PERMISSION_FINANCE => self::PERMISSION_FILESYSTEM
    self::PERMISSION_EMAIL => 0
The group id of cloud users which are allowed to access the backend services like file-system etc.
Definition at line 116 of file AuthorizationService.php.
ADDRESSBOOK
const ADDRESSBOOK = 'addressbook'
Definition at line 47 of file AuthorizationService.php.
ADDRESSBOOK_GROUP_SUFFIX
const ADDRESSBOOK_GROUP_SUFFIX = '-' . self::ADDRESSBOOK
Definition at line 56 of file AuthorizationService.php.
ALL_GROUP_SUFFIX
const ALL_GROUP_SUFFIX = ''
Definition at line 53 of file AuthorizationService.php.
CALENDAR
const CALENDAR = 'calendar'
Definition at line 49 of file AuthorizationService.php.
CALENDAR_GROUP_SUFFIX
const CALENDAR_GROUP_SUFFIX = '-' . self::CALENDAR
Definition at line 58 of file AuthorizationService.php.
EMAIL
const EMAIL = 'email'
Definition at line 51 of file AuthorizationService.php.
EMAIL_GROUP_SUFFIX
const EMAIL_GROUP_SUFFIX = '-' . self::EMAIL
Definition at line 60 of file AuthorizationService.php.
FILESYSTEM
const FILESYSTEM = 'filesystem'
Definition at line 48 of file AuthorizationService.php.
FILESYSTEM_GROUP_SUFFIX
const FILESYSTEM_GROUP_SUFFIX = '-' . self::FILESYSTEM
Definition at line 57 of file AuthorizationService.php.
FINANCE
const FINANCE = 'finance'
Definition at line 50 of file AuthorizationService.php.
FINANCE_GROUP_SUFFIX
const FINANCE_GROUP_SUFFIX = '-' . self::FINANCE
Definition at line 59 of file AuthorizationService.php.
FRONTEND
const FRONTEND = 'frontend'
Definition at line 46 of file AuthorizationService.php.
FRONTEND_GROUP_SUFFIX
const FRONTEND_GROUP_SUFFIX = '-' . self::FRONTEND
Definition at line 55 of file AuthorizationService.php.
MANAGEMENT
const MANAGEMENT = 'management'
Definition at line 45 of file AuthorizationService.php.
MANAGEMENT_GROUP_SUFFIX
const MANAGEMENT_GROUP_SUFFIX = '-' . self::MANAGEMENT
Definition at line 54 of file AuthorizationService.php.
PERMISSION_ADDRESSBOOK
const PERMISSION_ADDRESSBOOK = (1 << 1)
Definition at line 64 of file AuthorizationService.php.
PERMISSION_ALL
const PERMISSION_ALL
Initial value:
= self::PERMISSION_FRONTEND
    | self::PERMISSION_ADDRESSBOOK
    | self::PERMISSION_FILESYSTEM
    | self::PERMISSION_CALENDAR
    | self::PERMISSION_FINANCE
    | self::PERMISSION_MANAGEMENT
    | self::PERMISSION_EMAIL
Definition at line 70 of file AuthorizationService.php.
PERMISSION_CALENDAR
const PERMISSION_CALENDAR = (1 << 3)
Definition at line 66 of file AuthorizationService.php.
PERMISSION_EMAIL
const PERMISSION_EMAIL = (1 << 6)
Definition at line 69 of file AuthorizationService.php.
PERMISSION_FILESYSTEM
const PERMISSION_FILESYSTEM = (1 << 2)
Definition at line 65 of file AuthorizationService.php.
PERMISSION_FINANCE
const PERMISSION_FINANCE = (1 << 4)
Definition at line 67 of file AuthorizationService.php.
PERMISSION_FRONTEND
const PERMISSION_FRONTEND = (1 << 0)
Definition at line 63 of file AuthorizationService.php.
PERMISSION_MANAGEMENT
const PERMISSION_MANAGEMENT = (1 << 5)
Definition at line 68 of file AuthorizationService.php.
PERMISSION_NONE
const PERMISSION_NONE = 0
Definition at line 62 of file AuthorizationService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/AuthorizationService.php