CamerataDB: PHPMyEdit Class Reference
PHPMyEdit Class Reference
Override phpMyEdit to use OCA\CAFEVDB\Wrapped\Doctrine DBAL.
Public Member Functions
__construct (EntityManager $entityManager, IOptions $options, RequestParameterService $request, ILogger $logger, IL10N $l10n, IDateTimeZone $dateTimeZone, IDateTimeFormatter $dateTimeFormatter,)
Override constructor, delay most of the actual work to the execute() method.
setOptions (array $options)
getOptions ()
setLogging (bool $enable)
Enable or disable writing to the change-log table.
setDebug (bool $enable)
Enable or disabled debugging.
beginTransaction ()
Forward transaction support of underlying Doctrine\Dbal connection.
commit ()
Forward transaction support of underlying Doctrine\Dbal connection.
rollBack ()
Forward transaction support of underlying Doctrine\Dbal connection.
overrideLabel (string $label, string $override)
Override the given label text with the provided override label.
execute ($opts=[])
{}
export ($cellFilter=false, $lineCallback=false, $css='noescape', $opts=[])
{}
sql_connect ()
{}
sql_disconnect ()
{}
resultValid (&$stmt)
{}
dbhValid ()
{}
sql_fetch (&$stmt, $type='a')
{}
sql_free_result (&$stmt)
{}
sql_affected_rows ()
{}
sql_field_len (&$stmt, $field)
{}
sql_insert_id ()
{}
myquery ($query, $line=0, $debug=false)
{}
error ($message, $additionalInfo='')
{}
make_language_labels ($lang)
{}
get_cgi_var ($name, $defaultValue=null)
{}
addPersistentCgi ($name, $value=null)
{}
getCGIRecordId ()
Decode the record idea from the CGI data, return -1 if none found.
cgiSysName (string $suffix='')
Get prefixed name for control variables.
cgiDataName (string $suffix='')
Get prefixed name for data variables, i.e.
makeUserTimeString ($k, $row)
{}
col_has_datemask ($k)
{}
doFetchToolTip ($cssClassName, $name, $label=false)
{}
queryLog ()
clearQueryLog ()
Protected Member Functions
determineOperation ()
makeTimeStampFromUser ($userInput)
{}
makeTimeStampFromDatabase ($databaseValue)
{}
timestampToDatabase ($timeStamp, $k)
{}
logQuery ($operation, $oldvals, $changed, $newvals)
{}
Private Attributes
$connection
$request
$dateTimeZone
$dateTimeFormatter
$defaultOptions
$affectedRows = 0
$errorCode = 0
$errorInfo = null
$overrideOptions
$debug
$queryLog
One entry for each query of the following format:
$disabledLogTable
$labelOverride
< Overrides for the translation table.
$queryHash
< Hash of most recent query
Detailed Description
Override phpMyEdit to use OCA\CAFEVDB\Wrapped\Doctrine DBAL.
Definition at line 53 of file PHPMyEdit.php.
Constructor & Destructor Documentation
__construct()
__construct (EntityManager $entityManager, IOptions $options, RequestParameterService $request, ILogger $logger, IL10N $l10n, IDateTimeZone $dateTimeZone, IDateTimeFormatter $dateTimeFormatter)
Override constructor, delay most of the actual work to the execute() method.
Parameters
EntityManager $entityManager
IOptions $options
We do also some construction thing s.t. add_operation() and friends does something useful.
Definition at line 117 of file PHPMyEdit.php.
References IOptions\getArrayCopy(), PHPMyEdit\queryLog(), and PHPMyEdit\setOptions().
Member Function Documentation
addPersistentCgi()
addPersistentCgi ($name, $value = null)
{}
Add an entry to the underlying persistent CGI values. The settings will overwrite all previous settings of the same name.
Definition at line 564 of file PHPMyEdit.php.
References PHPMyEdit\addPersistentCgi().
Referenced by PHPMyEdit\addPersistentCgi().
beginTransaction()
beginTransaction ()
Forward transaction support of underlying Doctrine\Dbal connection.
Returns
void
Definition at line 291 of file PHPMyEdit.php.
cgiDataName()
cgiDataName (string $suffix = '')
Get prefixed name for data variables, i.e.
table-field data.
Parameters
string $suffix
Returns
string
Definition at line 611 of file PHPMyEdit.php.
cgiSysName()
cgiSysName (string $suffix = '')
Get prefixed name for control variables.
Parameters
string $suffix
Returns
string
Definition at line 599 of file PHPMyEdit.php.
clearQueryLog()
clearQueryLog ()
Returns
void
See also
PHPMyEdit::$queryLog
Definition at line 874 of file PHPMyEdit.php.
References PHPMyEdit\queryLog().
col_has_datemask()
col_has_datemask ($k)
{}
"register" the date-time-format extension.
Definition at line 761 of file PHPMyEdit.php.
commit()
commit ()
Forward transaction support of underlying Doctrine\Dbal connection.
Returns
void
Definition at line 302 of file PHPMyEdit.php.
dbhValid()
dbhValid ()
{}
Definition at line 406 of file PHPMyEdit.php.
Referenced by PHPMyEdit\sql_affected_rows(), and PHPMyEdit\sql_insert_id().
determineOperation()
determineOperation () protected
Returns
void
Definition at line 190 of file PHPMyEdit.php.
Referenced by PHPMyEdit\setOptions().
doFetchToolTip()
doFetchToolTip ($cssClassName, $name, $label = false)
{}
Definition at line 838 of file PHPMyEdit.php.
error()
error ($message, $additionalInfo = '')
{}
Definition at line 520 of file PHPMyEdit.php.
execute()
execute ($opts = [])
{}
Call phpMyEdit::execute() with the given options. This function actually calls the constructor of the base-class and overrides its options with the given argument.
Parameters
array $opts
Bug:
Calling a CTOR elsewhere is really bad programming style.
Definition at line 346 of file PHPMyEdit.php.
export()
export ($cellFilter = false, $lineCallback = false, $css = 'noescape', $opts = [])
{}
Quick and dirty general export. On each cell a call-back function is invoked with the html-output of that cell.
This is just like list_table(), i.e. only the chosen range of data is displayed and in html-display order.
Parameters
$cellFilter $line[] = Callback($i, $j, $celldata)
$lineCallback($i,$line)
$css CSS-class to pass to cellDisplay().
Definition at line 373 of file PHPMyEdit.php.
get_cgi_var()
get_cgi_var ($name, $defaultValue = null)
{}
Override parent::get_cgi_var to use RequestParameterService
Definition at line 544 of file PHPMyEdit.php.
getCGIRecordId()
getCGIRecordId ()
Decode the record idea from the CGI data, return -1 if none found.
Returns
array
Definition at line 581 of file PHPMyEdit.php.
getOptions()
getOptions ()
Returns
array
Definition at line 246 of file PHPMyEdit.php.
logQuery()
logQuery ($operation, $oldvals, $changed, $newvals) protected
{}
Handle logging.
Definition at line 775 of file PHPMyEdit.php.
References PHPMyEdit\myquery().
make_language_labels()
make_language_labels ($lang)
{}
Definition at line 530 of file PHPMyEdit.php.
Referenced by PHPMyEdit\setOptions().
makeTimeStampFromDatabase()
makeTimeStampFromDatabase ($databaseValue) protected
{}
Create a Unix time-stamp from the data-base.
Strategy: if the date/time value in the data base does contain a time, then assume UTC and just convert to a time-stamp.
If the value in the data-base does not contain a time then adjust to 00:00 local-time by shifting with the time-zone offset of the local user.
Definition at line 662 of file PHPMyEdit.php.
Referenced by PHPMyEdit\makeUserTimeString().
makeTimeStampFromUser()
makeTimeStampFromUser ($userInput) protected
{}
Create a Unix time-stamp from user-input
Strategy: if the user-input does not contain a time, then convert to UTC time at midnight. Otherwise adjust by the time-zone offset of the user.
Definition at line 624 of file PHPMyEdit.php.
makeUserTimeString()
makeUserTimeString ($k, $row)
{}
Create a time-string for user display from a data-base value
Definition at line 692 of file PHPMyEdit.php.
References PHPMyEdit\makeTimeStampFromDatabase().
myquery()
myquery ($query, $line = 0, $debug = false)
{}
Definition at line 481 of file PHPMyEdit.php.
References PHPMyEdit\queryLog().
Referenced by PHPMyEdit\logQuery().
overrideLabel()
overrideLabel (string $label, string $override)
Override the given label text with the provided override label.
The given override will be translated by the standard cloud translator.
Parameters
string $label
string $override
Returns
void
Definition at line 329 of file PHPMyEdit.php.
queryLog()
queryLog ()
Returns
array The query-log array.
See also
PHPMyEdit::$queryLog
Definition at line 864 of file PHPMyEdit.php.
References PHPMyEdit\$queryLog.
Referenced by PHPMyEdit\__construct(), PHPMyEdit\clearQueryLog(), and PHPMyEdit\myquery().
resultValid()
resultValid (& $stmt)
{}
Definition at line 399 of file PHPMyEdit.php.
Referenced by PHPMyEdit\sql_fetch(), and PHPMyEdit\sql_free_result().
rollBack()
rollBack ()
Forward transaction support of underlying Doctrine\Dbal connection.
Returns
void
Definition at line 313 of file PHPMyEdit.php.
setDebug()
setDebug (bool $enable)
Enable or disabled debugging.
Parameters
bool $enable Flag value.
Returns
void
Definition at line 277 of file PHPMyEdit.php.
setLogging()
setLogging (bool $enable)
Enable or disable writing to the change-log table.
Parameters
bool $enable Flag value.
Returns
void
Definition at line 258 of file PHPMyEdit.php.
setOptions()
setOptions (array $options)
Parameters
array $options
Returns
void
Definition at line 159 of file PHPMyEdit.php.
References PHPMyEdit\determineOperation(), and PHPMyEdit\make_language_labels().
Referenced by PHPMyEdit\__construct().
sql_affected_rows()
sql_affected_rows ()
{}
Definition at line 457 of file PHPMyEdit.php.
References PHPMyEdit\dbhValid().
sql_connect()
sql_connect ()
{}
Definition at line 387 of file PHPMyEdit.php.
sql_disconnect()
sql_disconnect ()
{}
Definition at line 393 of file PHPMyEdit.php.
sql_fetch()
sql_fetch (& $stmt, $type = 'a')
{}
Definition at line 413 of file PHPMyEdit.php.
References PHPMyEdit\resultValid().
sql_field_len()
sql_field_len (& $stmt, $field)
{}
Definition at line 466 of file PHPMyEdit.php.
sql_free_result()
sql_free_result (& $stmt)
{}
Definition at line 448 of file PHPMyEdit.php.
References PHPMyEdit\resultValid().
sql_insert_id()
sql_insert_id ()
{}
Definition at line 472 of file PHPMyEdit.php.
References PHPMyEdit\dbhValid().
timestampToDatabase()
timestampToDatabase ($timeStamp, $k) protected
{}
Generate a data-base value from a timestamp.
Definition at line 743 of file PHPMyEdit.php.
Field Documentation
$affectedRows
$affectedRows = 0 private
Definition at line 72 of file PHPMyEdit.php.
$connection
Connection $connection private
Definition at line 59 of file PHPMyEdit.php.
$dateTimeFormatter
IDateTimeFormatter $dateTimeFormatter private
Definition at line 68 of file PHPMyEdit.php.
$dateTimeZone
IDateTimeZone $dateTimeZone private
Definition at line 65 of file PHPMyEdit.php.
$debug
$debug private
Definition at line 77 of file PHPMyEdit.php.
$defaultOptions
$defaultOptions private
Definition at line 70 of file PHPMyEdit.php.
$disabledLogTable
$disabledLogTable private
Definition at line 95 of file PHPMyEdit.php.
$errorCode
$errorCode = 0 private
Definition at line 73 of file PHPMyEdit.php.
$errorInfo
$errorInfo = null private
Definition at line 74 of file PHPMyEdit.php.
$labelOverride
array $labelOverride private
< Overrides for the translation table.
Definition at line 98 of file PHPMyEdit.php.
$overrideOptions
$overrideOptions private
Definition at line 75 of file PHPMyEdit.php.
$queryHash
string $queryHash private
< Hash of most recent query
Definition at line 102 of file PHPMyEdit.php.
$queryLog
array< int, array > $queryLog private
One entry for each query of the following format:
[
  'query' => STRING_OF_SQL_COMMANDS,
  'affectedRows' => NUM_ROWS,
  'errorCode' => ERROR_CODE,
  'errorInfo' => ERROR_INFO,
  'duration' => TIME_IN_MS
]
Definition at line 93 of file PHPMyEdit.php.
Referenced by PHPMyEdit\queryLog().
$request
RequestParameterService $request private
Definition at line 62 of file PHPMyEdit.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Legacy/PME/PHPMyEdit.php