CamerataDB: AnyToPdf Class Reference
AnyToPdf Class Reference
A class which can convert "any" (read: some) file-data to PDF format.
Public Member Functions
__construct (IMimeTypeDetector $mimeTypeDetector, ITempManager $tempManager, ExecutableFinder $executableFinder, ILogger $logger, IL10N $l,)
convertData (string $data, ?string $mimeType=null)
Try to convert the given data-block $data to PDF using any of the known converters.
Protected Member Functions
passthroughConvert (string $data)
unoconvConvert (string $data)
mhonarcConvert (string $data)
ps2pdfConvert (string $data)
wkhtmltopdfConvert (string $data)
tiff2pdfConvert (string $data)
findExecutable (string $program)
Try to find the given executable.
Protected Attributes
$mimeTypeDetector
$tempManager
$l
$paperSize = 'a4'
Paper size for converters which need it.
$executableFinder
$executables = []
Cache of found executables for the current request.
Detailed Description
A class which can convert "any" (read: some) file-data to PDF format.
Currently anything supported by LibreOffice via unoconv and .eml via mhonarc will work.
Definition at line 45 of file AnyToPdf.php.
Constructor & Destructor Documentation
__construct()
__construct (IMimeTypeDetector $mimeTypeDetector, ITempManager $tempManager, ExecutableFinder $executableFinder, ILogger $logger, IL10N $l)
Definition at line 90 of file AnyToPdf.php.
Member Function Documentation
convertData()
convertData (string $data, ?string $mimeType = null)
Try to convert the given data-block $data to PDF using any of the known converters.
If no converter can do the job provide an error-page with information in PDF format.
Parameters
string $data Data-block to be converted.
string | null $mimeType If null or 'application/octet-stream' the cloud's mime-type detector is used to detect the mime-type.
Returns
string
Definition at line 117 of file AnyToPdf.php.
findExecutable()
findExecutable (string $program) protected
Try to find the given executable.
Parameters
string $program The program to search for. This must be the basename of a Un*x program.
Returns
string The full path to $program.
Exceptions
Exceptions
\EnduserNotificationException
Definition at line 280 of file AnyToPdf.php.
Referenced by AnyToPdf\mhonarcConvert(), AnyToPdf\ps2pdfConvert(), AnyToPdf\tiff2pdfConvert(), AnyToPdf\unoconvConvert(), and AnyToPdf\wkhtmltopdfConvert().
mhonarcConvert()
mhonarcConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 196 of file AnyToPdf.php.
References AnyToPdf\findExecutable().
passthroughConvert()
passthroughConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 155 of file AnyToPdf.php.
ps2pdfConvert()
ps2pdfConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 213 of file AnyToPdf.php.
References AnyToPdf\findExecutable().
tiff2pdfConvert()
tiff2pdfConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 247 of file AnyToPdf.php.
References AnyToPdf\findExecutable().
unoconvConvert()
unoconvConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 165 of file AnyToPdf.php.
References AnyToPdf\findExecutable().
wkhtmltopdfConvert()
wkhtmltopdfConvert (string $data) protected
Parameters
string $data
Returns
string
Definition at line 230 of file AnyToPdf.php.
References AnyToPdf\findExecutable().
Field Documentation
$executableFinder
ExecutableFinder $executableFinder protected
Definition at line 81 of file AnyToPdf.php.
$executables
array $executables = [] protected
Cache of found executables for the current request.
Definition at line 87 of file AnyToPdf.php.
$l
IL10N $l protected
Definition at line 69 of file AnyToPdf.php.
$mimeTypeDetector
IMimeTypeDetector $mimeTypeDetector protected
Initial value:
=[[,[,,],],[,],[],[],[,],]
  const CONVERTERS
    'message/rfc822' =>  'mhonarc'  'wkhtmltopdf' 'unoconv'
    'application/postscript' =>  'ps2pdf'
    'image/tiff' =>  'tiff2pdf'
    'application/pdf' =>  'passthrough'
    'default' =>  'unoconv'
Definition at line 63 of file AnyToPdf.php.
$paperSize
string $paperSize = 'a4' protected
Paper size for converters which need it.
Todo:
Make it configurable
Definition at line 78 of file AnyToPdf.php.
$tempManager
ITempManager $tempManager protected
Definition at line 66 of file AnyToPdf.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Documents/AnyToPdf.php