CamerataDB: AbstractReadMeFactory Class Reference
AbstractReadMeFactory Class Reference
Abstract factory baseclass.
Public Member Functions
__construct (protected ContainerInterface $appContainer, protected IL10N $l, protected AppL10N $appL10n,)
isReadMe (string $path)
Check whether the given file is a ReadMe.md file.
generateReadMe (DatabaseStorageFolder|EmptyDirectoryNode $parent, string $dirName)
getReadMeFileNames ()
Possibly populate and return the array of possible "readMe" variations.
Data Fields
const MIME_TYPE = 'text/plain'
Protected Attributes
array $readMeFileNames = null
A cache for possible names of the Readme.md.
Detailed Description
Abstract factory baseclass.
Definition at line 41 of file AbstractReadMeFactory.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ContainerInterface $appContainer, protected IL10N $l, protected AppL10N $appL10n)
Parameters
ContainerInterface $appContainer
IL10N $l
AppL10N $appL10n
Definition at line 60 of file AbstractReadMeFactory.php.
Member Function Documentation
generateReadMe()
generateReadMe (DatabaseStorageFolder|EmptyDirectoryNode $parent, string $dirName) inherited
Parameters
DatabaseStorageFolder | EmptyDirectoryNode $parent
string $dirName
Returns
null|InMemoryFileNode
Implemented in ReadMeFactory.
getReadMeFileNames()
getReadMeFileNames () inherited
Possibly populate and return the array of possible "readMe" variations.
We try to recurse to the "text" app and come up with suitable fallback if that fails.
Returns
array<int, string>
Referenced by ReadMeFactory\generateReadMe(), and AbstractReadMeFactory\isReadMe().
isReadMe()
isReadMe (string $path)
Check whether the given file is a ReadMe.md file.
Parameters
string $path
Returns
bool
Implements ReadMeFactoryInterface.
Definition at line 102 of file AbstractReadMeFactory.php.
References AbstractReadMeFactory\$readMeFileNames, ReadMeFactoryInterface\getReadMeFileNames(), and StorageUtil\uploadBasename().
Field Documentation
$readMeFileNames
array $readMeFileNames = null protected
A cache for possible names of the Readme.md.
The first element is the preferred localized name.
Definition at line 51 of file AbstractReadMeFactory.php.
Referenced by AbstractReadMeFactory\isReadMe().
MIME_TYPE
const MIME_TYPE = 'text/plain'
Definition at line 43 of file AbstractReadMeFactory.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Storage/Database/AbstractReadMeFactory.php