CamerataDB: SepaDebitMandatesRepository Class Reference
SepaDebitMandatesRepository Class Reference
@method Entities\SepaDebitMandate find($id)
Public Member Functions
findOneBy ($idOrReference, array $orderBy=null)
Find a SEPA-mandate by either its primary key or its mandate reference; no-op if $idOrReference already is a SEPA-mandate entity.
persist (Entities\SepaDebitMandate $mandate)
Try to persist the given bank-account by first fetching the current sequence for its musician and then increasing it.
ban ($idOrReference)
Ban a SEPA-mandate (timeout, withdrawn, erroneous data etc.).
remove (mixed $idOrReference)
Delete the given mandate if it is not used.
findNewest (mixed $project, mixed $musician)
Find the sepa-mandate with the highest sequence number, if any.
usage (mixed $identifier, bool $brief=false)
Fetch usage information about the given identifier.
getEntityManager ()
Public export of parent function.
Detailed Description
@method Entities\SepaDebitMandate find($id)
Definition at line 38 of file SepaDebitMandatesRepository.php.
Member Function Documentation
ban()
ban ($idOrReference)
Ban a SEPA-mandate (timeout, withdrawn, erroneous data etc.).
This flags the mandate as deleted, but we have to keep the data for the book-keeping.
Parameters
string | array | Entities\\SepaDebitMandate $idOrReference Mandate-reference or primary key or entity instance.
Returns
?Entities\SepaDebitMandate
Definition at line 92 of file SepaDebitMandatesRepository.php.
References SepaDebitMandatesRepository\findOneBy(), and EntityRepository\getEntityManager().
Referenced by SepaDebitMandatesRepository\remove().
findNewest()
findNewest (mixed $project, mixed $musician)
Find the sepa-mandate with the highest sequence number, if any.
Deactivated mandates are ignored.
Parameters
mixed $project
mixed $musician
Returns
null|Entities\SepaDebitMandate
Todo:
Check that soft-delete behavior actually works as filter.
Definition at line 145 of file SepaDebitMandatesRepository.php.
References SepaDebitMandatesRepository\findOneBy().
findOneBy()
findOneBy ($idOrReference, array $orderBy = null)
Find a SEPA-mandate by either its primary key or its mandate reference; no-op if $idOrReference already is a SEPA-mandate entity.
Parameters
string | array | Entities\\SepaDebitMandate $idOrReference Mandate-reference or primary key or entity instance.
array $orderBy
Returns
mixed
Definition at line 54 of file SepaDebitMandatesRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), SepaDebitMandatesRepository\findNewest(), and SepaDebitMandatesRepository\remove().
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
persist()
persist (Entities\SepaDebitMandate $mandate)
Try to persist the given bank-account by first fetching the current sequence for its musician and then increasing it.
Parameters
Entities\\SepaDebitMandate $mandate
Returns
Entities\SepaDebitMandate
Exceptions
Doctrine
\DBAL\Exception\UniqueConstraintViolationException
Definition at line 77 of file SepaDebitMandatesRepository.php.
remove()
remove (mixed $idOrReference)
Delete the given mandate if it is not used.
Parameters
mixed $idOrReference
Returns
?Entities\SepaDebitMandate
Definition at line 109 of file SepaDebitMandatesRepository.php.
References SepaDebitMandatesRepository\ban(), SepaDebitMandatesRepository\findOneBy(), EntityRepository\getEntityManager(), and SepaDebitMandatesRepository\usage().
usage()
usage (mixed $identifier, bool $brief = false)
Fetch usage information about the given identifier.
Parameters
mixed $identifier Primary key(s), or an entity instance or the mandate reference.
boolean $brief Omit detailed usage time-stamps.
Returns
null|array
Definition at line 162 of file SepaDebitMandatesRepository.php.
Referenced by SepaDebitMandatesRepository\remove().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/SepaDebitMandatesRepository.php