CamerataDB: ProjectParticipantFieldDataRepository Class Reference
ProjectParticipantFieldDataRepository Class Reference
Repository for extra fields data.
Public Member Functions
optionKeys ($field)
Fetch all values stored for the given participant-field, e.g.
getEntityManager ()
Public export of parent function.
Data Fields
const ALIAS = 'pexfd'
Detailed Description
Repository for extra fields data.
Definition at line 32 of file ProjectParticipantFieldDataRepository.php.
Member Function Documentation
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
optionKeys()
optionKeys ($field)
Fetch all values stored for the given participant-field, e.g.
in order to recover or generate select boxes.
Parameters
int | Entities\\ProjectParticipantField $field
Returns
mixed
Definition at line 44 of file ProjectParticipantFieldDataRepository.php.
Field Documentation
ALIAS
const ALIAS = 'pexfd'
Definition at line 34 of file ProjectParticipantFieldDataRepository.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/ProjectParticipantFieldDataRepository.php