CamerataDB: AsymmetricKeyService Class Reference
AsymmetricKeyService Class Reference
Support functions encapsulating the underlying encryption framework (currently openssl)
Public Member Functions
__construct (string $appName, IAppContainer $appContainer, IUserSession $userSession, ICredentialsStore $credentialsStore, IConfig $cloudConfig, IEventDispatcher $eventDispatcher, IL10N $l10n, ILogger $logger, AsymmetricKeyStorageInterface $keyStorage, AsymmetricCryptorInterface $cryptorPrototype,)
initEncryptionKeyPair (?string $ownerId=null, ?string $keyPassphrase=null, bool $forceNewKeyPair=false)
Initialize a private/public key-pair by either retreiving it from the config-space or generating a new one.
deleteEncryptionKeyPair (string $ownerId)
Remove the key pair and all config-data for the given id.
restoreEncryptionKeyPair (string $ownerId)
Restore the key-pair from a potential backup e.g.
setSharedPrivateValue (string $ownerId, string $key, mixed $value)
Encrypt and set one private value.
getSharedPrivateValue (string $ownerId, string $key, mixed $default=null)
Fetch and decrypt one private value.
deleteSharedPrivateValue (string $ownerId, string $key)
Delete one private value.
getSharedPrivateData (string $ownerId)
Return the entire encrypted config-space.
removeSharedPrivateData (string $ownerId)
Remove all shared private values, e.g.
recryptSharedPrivateData (string $ownerId, array $oldKeyPair, array $newKeyPair)
Recrypt all shared private values with a new key.
getRecryptionRequests (?string $ownerId=null)
Fetch the list of all or a matching encryption request.
Data Fields
const PUBLIC_ENCRYPTION_KEY_CONFIG = AsymmetricKeyStorageInterface::PUBLIC_ENCRYPTION_KEY
const PRIVATE_ENCRYPTION_KEY_CONFIG = AsymmetricKeyStorageInterface::PRIVATE_ENCRYPTION_KEY
const CONFIG_KEY_PREFIX = 'private:'
const RECRYPTION_REQUEST_KEY = Notifier::RECRYPT_USER_SUBJECT
Private Member Functions
getSessionUserId ()
Fetch the user-id for the currently logged in user.
Private Attributes
$appName
$appContainer
$userSession
$credentialsStore
$eventDispatcher
$cloudConfig
$l
$keyStorage
$cryptorPrototype
Static Private Attributes
static $cryptors = []
static $keyPairs = []
Detailed Description
Support functions encapsulating the underlying encryption framework (currently openssl)
Definition at line 51 of file AsymmetricKeyService.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, IAppContainer $appContainer, IUserSession $userSession, ICredentialsStore $credentialsStore, IConfig $cloudConfig, IEventDispatcher $eventDispatcher, IL10N $l10n, ILogger $logger, AsymmetricKeyStorageInterface $keyStorage, AsymmetricCryptorInterface $cryptorPrototype)
Todo:
We might want to use the \OCP\IAppContainer instead and only fetch the needed service-classes on demand.
Definition at line 100 of file AsymmetricKeyService.php.
Member Function Documentation
deleteEncryptionKeyPair()
deleteEncryptionKeyPair (string $ownerId)
Remove the key pair and all config-data for the given id.
Parameters
string $ownerId
Returns
void
Definition at line 219 of file AsymmetricKeyService.php.
References AsymmetricKeyService\removeSharedPrivateData().
deleteSharedPrivateValue()
deleteSharedPrivateValue (string $ownerId, string $key)
Delete one private value.
This can also be achieved by passing an empty value to setSharedPrivateValue()
Parameters
string $ownerId
string $key
Returns
void
Definition at line 368 of file AsymmetricKeyService.php.
References AsymmetricKeyService\setSharedPrivateValue().
getRecryptionRequests()
getRecryptionRequests (?string $ownerId = null)
Fetch the list of all or a matching encryption request.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'. If null then the currently logged in user is used.
Returns
array<string, string> USER_ID => REQUEST_VALUE
Definition at line 457 of file AsymmetricKeyService.php.
getSessionUserId()
getSessionUserId () private
Fetch the user-id for the currently logged in user.
Returns
null|string
Definition at line 246 of file AsymmetricKeyService.php.
Referenced by AsymmetricKeyService\initEncryptionKeyPair().
getSharedPrivateData()
getSharedPrivateData (string $ownerId)
Return the entire encrypted config-space.
Parameters
string $ownerId
Returns
array<string, string> Configs as KEY => DECRYPTED_VALUE
Definition at line 380 of file AsymmetricKeyService.php.
References AsymmetricKeyService\getSharedPrivateValue().
Referenced by AsymmetricKeyService\recryptSharedPrivateData().
getSharedPrivateValue()
getSharedPrivateValue (string $ownerId, string $key, mixed $default = null)
Fetch and decrypt one private value.
Parameters
string $ownerId
string $key
mixed $default
Returns
string|null
Exceptions
Exceptions
\CannotDecryptException
Definition at line 344 of file AsymmetricKeyService.php.
Referenced by AsymmetricKeyService\getSharedPrivateData().
initEncryptionKeyPair()
initEncryptionKeyPair (?string $ownerId = null, ?string $keyPassphrase = null, bool $forceNewKeyPair = false)
Initialize a private/public key-pair by either retreiving it from the config-space or generating a new one.
If a new key-pair has to be generated the two events Events\BeforeEncryptionKeyPairChanged and Events\AfterEncryptionKeyPairChanged are fired. The old key-pair may be missing if the password used to secure the old private key is not available.
Parameters
null | string $ownerId The owner-id. If used for a group then it should be prefixed by '@'. If null then the currently logged in user is used.
null | string $keyPassphrase The passphrase used to protect the private key. If null then the currently logged in user's password is used if the cloud's credentials store is able to provide the password.
bool $forceNewKeyPair Generate a new key pair even if an old one is found.
Returns
array<string, string>
[
  self::PRIVATE_ENCRYPTION_KEY_CONFIG => PRIV_KEY,
  self::PUBLIC_ENCRYPTION_KEY_CONFIG => PUB_KEY,
]
Exceptions
Exceptions
\EncryptionKeyException
Definition at line 153 of file AsymmetricKeyService.php.
References AsymmetricKeyService\getSessionUserId().
recryptSharedPrivateData()
recryptSharedPrivateData (string $ownerId, array $oldKeyPair, array $newKeyPair)
Recrypt all shared private values with a new key.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'. If null then the currently logged in user is used.
array<string,string> $oldKeyPair
[
  self::PRIVATE_ENCRYPTION_KEY_CONFIG => PRIV_KEY,
  self::PUBLIC_ENCRYPTION_KEY_CONFIG => PUB_KEY,
]
array<string,string> $newKeyPair
[
  self::PRIVATE_ENCRYPTION_KEY_CONFIG => PRIV_KEY,
  self::PUBLIC_ENCRYPTION_KEY_CONFIG => PUB_KEY,
]
Returns
void
Definition at line 435 of file AsymmetricKeyService.php.
References AsymmetricKeyService\getSharedPrivateData(), and AsymmetricKeyService\setSharedPrivateValue().
removeSharedPrivateData()
removeSharedPrivateData (string $ownerId)
Remove all shared private values, e.g.
after a password was lost.
Parameters
string $ownerId
Returns
void
Definition at line 402 of file AsymmetricKeyService.php.
Referenced by AsymmetricKeyService\deleteEncryptionKeyPair().
restoreEncryptionKeyPair()
restoreEncryptionKeyPair (string $ownerId)
Restore the key-pair from a potential backup e.g.
in case of a failure while changing the key. This is desctructive, the current key is overwritten.
Parameters
string $ownerId
Returns
void
Definition at line 236 of file AsymmetricKeyService.php.
setSharedPrivateValue()
setSharedPrivateValue (string $ownerId, string $key, mixed $value)
Encrypt and set one private value.
Parameters
string $ownerId
string $key
mixed $value Must be convertible to string.
Returns
void
Exceptions
Exceptions
\CannotEncryptException
Definition at line 316 of file AsymmetricKeyService.php.
Referenced by AsymmetricKeyService\deleteSharedPrivateValue(), and AsymmetricKeyService\recryptSharedPrivateData().
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 66 of file AsymmetricKeyService.php.
$appName
string $appName private
Definition at line 63 of file AsymmetricKeyService.php.
$cloudConfig
IConfig $cloudConfig private
Definition at line 78 of file AsymmetricKeyService.php.
$credentialsStore
ICredentialsStore $credentialsStore private
Definition at line 72 of file AsymmetricKeyService.php.
$cryptorPrototype
AsymmetricCryptorInterface $cryptorPrototype private
Definition at line 87 of file AsymmetricKeyService.php.
$cryptors
array< string, AsymmetricCryptorInterface > $cryptors = [] static private
Definition at line 90 of file AsymmetricKeyService.php.
$eventDispatcher
IEventDispatcher $eventDispatcher private
Definition at line 75 of file AsymmetricKeyService.php.
$keyPairs
array< string, array > $keyPairs = [] static private
Definition at line 93 of file AsymmetricKeyService.php.
$keyStorage
AsymmetricKeyStorageInterface $keyStorage private
Definition at line 84 of file AsymmetricKeyService.php.
$l
IL10N $l private
Definition at line 81 of file AsymmetricKeyService.php.
$userSession
IUserSession $userSession private
Definition at line 69 of file AsymmetricKeyService.php.
CONFIG_KEY_PREFIX
const CONFIG_KEY_PREFIX = 'private:'
Definition at line 58 of file AsymmetricKeyService.php.
PRIVATE_ENCRYPTION_KEY_CONFIG
const PRIVATE_ENCRYPTION_KEY_CONFIG = AsymmetricKeyStorageInterface::PRIVATE_ENCRYPTION_KEY
Definition at line 56 of file AsymmetricKeyService.php.
PUBLIC_ENCRYPTION_KEY_CONFIG
const PUBLIC_ENCRYPTION_KEY_CONFIG = AsymmetricKeyStorageInterface::PUBLIC_ENCRYPTION_KEY
Definition at line 55 of file AsymmetricKeyService.php.
RECRYPTION_REQUEST_KEY
const RECRYPTION_REQUEST_KEY = Notifier::RECRYPT_USER_SUBJECT
Definition at line 60 of file AsymmetricKeyService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Crypto/AsymmetricKeyService.php