CamerataDB: InsuranceSpreadsheetExporter Class Reference
InsuranceSpreadsheetExporter Class Reference
Exporter for the instrument insurances.
Public Member Functions
__construct (PageRenderer\InstrumentInsurances $renderer, InstrumentInsuranceService $insuranceService, FuzzyInputService $fuzzyInputService, FontService $fontService,)
Construct a spread-sheet exporter for selected tables.
fillSheet (PhpSpreadsheet\Spreadsheet $spreadSheet, array $meta)
Implement parent::fillSheet() for exactly.
export (string $fileName, $format)
Write out the generated sheet(s) to the given file-name.
Data Fields
const FILE_TYPES
Array of supported file-types.
Protected Member Functions
generateHeader (Worksheet $sheet, array $meta, array $rate, array $broker, DateTimeInterface $nowDate,)
dumpMusicianNextTotal (Worksheet $sheet, int $row, int $offset, int &$rowCnt, float $musicianNextTotal, string $musician, DateTimeInterface $dueDate,)
Protected Attributes
const MUSICIAN_KEY = 'musician'
const OBJECT_KEY = 'object'
const START_KEY = 'start'
const DELETED_KEY = 'deleted'
const ACCESSORY_KEY = 'accessory'
const MANUFACTURER_KEY = 'manufacturer'
const YEAR_OF_CONSTRUCTION_KEY = 'year'
const AMOUNT_KEY = 'amount'
const TOTALS_KEY = 'totals'
const EXPORT_COLUMNS
const INPUT_INDEX_MUSICIAN = 0
const INPUT_INDEX_BILL_TO = self::INPUT_INDEX_MUSICIAN + 1
const INPUT_INDEX_OWNER = self::INPUT_INDEX_BILL_TO +1
const INPUT_INDEX_BROKER = self::INPUT_INDEX_OWNER + 1
const INPUT_INDEX_SCOPE = self::INPUT_INDEX_BROKER + 1
const INPUT_INDEX_OBJECT = self::INPUT_INDEX_SCOPE + 1
const INPUT_INDEX_IS_ACCESSORY = self::INPUT_INDEX_OBJECT + 1
const INPUT_INDEX_MANUFACTURER = self::INPUT_INDEX_IS_ACCESSORY + 1
const INPUT_INDEX_YEAR_OF_CONSTRUCTION = self::INPUT_INDEX_MANUFACTURER + 1
const INPUT_INDEX_INSURED_AMOUNT = self::INPUT_INDEX_YEAR_OF_CONSTRUCTION + 1
const INPUT_INDEX_INSURANCE_RATE = self::INPUT_INDEX_INSURED_AMOUNT + 1
const INPUT_INDEX_DUE_DATE = self::INPUT_INDEX_INSURANCE_RATE + 1
const INPUT_INDEX_INSURANCE_FEES = self::INPUT_INDEX_DUE_DATE + 1
const INPUT_INDEX_INSURANCE_START = self::INPUT_INDEX_INSURANCE_FEES + 1
const INPUT_INDEX_INSURANCE_END = self::INPUT_INDEX_INSURANCE_START + 1
$renderer
$insuranceService
$fuzzyInputService
$spreadSheetColumns
$lastColumnAddress
$preLastColumnAddress
const WIDTH_EXTRA_SPACE = 2
const MIN_WIDTH = 20
$fontService
Private Member Functions
dumpRow (array $exportData, Worksheet $sheet, int $row, int $offset, int &$rowCnt, bool $header=false,)
dumpMusicianTotal (Worksheet $sheet, int $row, int $offset, int &$rowCnt, float $musicianTotal, string $musician,)
dumpTotal (Worksheet $sheet, int $row, int $offset, int &$rowCnt, ?float $total,)
dumpNextTotal (Worksheet $sheet, int $row, int $offset, int &$rowCnt, float $total, DateTimeInterface $dueDate,)
Detailed Description
Exporter for the instrument insurances.
This is special as it must only contain official data and should be in a ready-to-send state in order to just hand it on to the insurance brokers.
Definition at line 47 of file InsuranceSpreadsheetExporter.php.
Constructor & Destructor Documentation
__construct()
__construct (PageRenderer\InstrumentInsurances $renderer, InstrumentInsuranceService $insuranceService, FuzzyInputService $fuzzyInputService, FontService $fontService)
Construct a spread-sheet exporter for selected tables.
Parameters
PageRenderer\\InstrumentInsurances $renderer Underlying renderer, see self::fillSheet().
InstrumentInsuranceService $insuranceService
FuzzyInputService $fuzzyInputService
FontService $fontService
Definition at line 120 of file InsuranceSpreadsheetExporter.php.
Member Function Documentation
dumpMusicianNextTotal()
dumpMusicianNextTotal (Worksheet $sheet, int $row, int $offset, int & $rowCnt, float $musicianNextTotal, string $musician, DateTimeInterface $dueDate) protected
Parameters
Worksheet $sheet
int $row
int $offset
int $rowCnt Mutable.
float $musicianNextTotal
string $musician
DateTimeInterface $dueDate
Returns
void
Definition at line 718 of file InsuranceSpreadsheetExporter.php.
dumpMusicianTotal()
dumpMusicianTotal (Worksheet $sheet, int $row, int $offset, int & $rowCnt, float $musicianTotal, string $musician) private
Parameters
Worksheet $sheet
int $row
int $offset
int $rowCnt Mutable.
float $musicianTotal
string $musician
Returns
void
Definition at line 675 of file InsuranceSpreadsheetExporter.php.
Referenced by InsuranceSpreadsheetExporter\fillSheet().
dumpNextTotal()
dumpNextTotal (Worksheet $sheet, int $row, int $offset, int & $rowCnt, float $total, DateTimeInterface $dueDate) private
Parameters
Worksheet $sheet
int $row
int $offset
int $rowCnt Mutable.
float $total
DateTimeInterface $dueDate
Returns
void
Definition at line 809 of file InsuranceSpreadsheetExporter.php.
Referenced by InsuranceSpreadsheetExporter\fillSheet().
dumpRow()
dumpRow (array $exportData, Worksheet $sheet, int $row, int $offset, int & $rowCnt, bool $header = false) private
Parameters
array $exportData
Worksheet $sheet
int $row
int $offset
int $rowCnt Mutable.
bool $header
Returns
void
Definition at line 567 of file InsuranceSpreadsheetExporter.php.
Referenced by InsuranceSpreadsheetExporter\fillSheet().
dumpTotal()
dumpTotal (Worksheet $sheet, int $row, int $offset, int & $rowCnt, ?float $total) private
Parameters
Worksheet $sheet
int $row
int $offset
int $rowCnt Mutable.
null | float $total
Returns
void
Definition at line 762 of file InsuranceSpreadsheetExporter.php.
Referenced by InsuranceSpreadsheetExporter\fillSheet().
export()
export (string $fileName, $format) inherited
Write out the generated sheet(s) to the given file-name.
Parameters
string $fileName TBD.
string | ExportFormat $format One of the keys of self::FILE_TYPES.
Returns
array
[
  'mimeType' => MIME_TYPE_STRING,
  'extension' => FILE_EXTENSION_EXCLUDING_DOT,
]
Todo:
move to namespace
Definition at line 122 of file AbstractSpreadsheetExporter.php.
References AbstractSpreadsheetExporter\fillSheet().
fillSheet()
fillSheet (PhpSpreadsheet\Spreadsheet $spreadSheet, array $meta)
Implement parent::fillSheet() for exactly.
template all-musicians, class PageRenderer\Musicians
template project-participants, class PageRenderer\ProjectParticipants
template sepa-bank-accounts, class PageRenderer\SepaBankAccounts
All other renderers are rejected by throwing an exception, although a couple of other tables should also work out of the box.
Parameters
PhpSpreadsheet\\Spreadsheet $spreadSheet Spread-sheet to be filled.
array $meta An array with at least the keys 'creator', 'email', 'date'.
Returns
array
[
  'creator' => STRING,
  'email' => STRING,
  'date' => STRING,
  'name' => STRING,
]
Todo:
Still quite messy.
Reimplemented from AbstractSpreadsheetExporter.
Definition at line 165 of file InsuranceSpreadsheetExporter.php.
References InsuranceSpreadsheetExporter\dumpMusicianTotal(), InsuranceSpreadsheetExporter\dumpNextTotal(), InsuranceSpreadsheetExporter\dumpRow(), InsuranceSpreadsheetExporter\dumpTotal(), and InsuranceSpreadsheetExporter\generateHeader().
generateHeader()
generateHeader (Worksheet $sheet, array $meta, array $rate, array $broker, DateTimeInterface $nowDate) protected
Parameters
Worksheet $sheet
array $meta Meta information like creator, its email etc.
array $rate Insurance rate data.
array $broker Broker data.
DateTimeInterface $nowDate
Returns
int The number generated header lines.
Definition at line 523 of file InsuranceSpreadsheetExporter.php.
Referenced by InsuranceSpreadsheetExporter\fillSheet().
Field Documentation
$fontService
FontService $fontService protected inherited
Definition at line 72 of file AbstractSpreadsheetExporter.php.
$fuzzyInputService
FuzzyInputService $fuzzyInputService protected
Definition at line 97 of file InsuranceSpreadsheetExporter.php.
$insuranceService
InstrumentInsuranceService $insuranceService protected
Definition at line 94 of file InsuranceSpreadsheetExporter.php.
$lastColumnAddress
string $lastColumnAddress protected
Definition at line 103 of file InsuranceSpreadsheetExporter.php.
$preLastColumnAddress
string $preLastColumnAddress protected
Definition at line 106 of file InsuranceSpreadsheetExporter.php.
$renderer
PageRenderer PMETableViewBase $renderer protected
Definition at line 91 of file InsuranceSpreadsheetExporter.php.
$spreadSheetColumns
array $spreadSheetColumns protected
Definition at line 100 of file InsuranceSpreadsheetExporter.php.
ACCESSORY_KEY
const ACCESSORY_KEY = 'accessory' protected
Definition at line 56 of file InsuranceSpreadsheetExporter.php.
AMOUNT_KEY
const AMOUNT_KEY = 'amount' protected
Definition at line 59 of file InsuranceSpreadsheetExporter.php.
DELETED_KEY
const DELETED_KEY = 'deleted' protected
Definition at line 55 of file InsuranceSpreadsheetExporter.php.
EXPORT_COLUMNS
const EXPORT_COLUMNS protected
Initial value:
= [
    self::MUSICIAN_KEY,
    self::OBJECT_KEY,
    self::START_KEY,
    self::DELETED_KEY,
    self::ACCESSORY_KEY,
    self::MANUFACTURER_KEY,
    self::YEAR_OF_CONSTRUCTION_KEY,
    self::AMOUNT_KEY,
    self::TOTALS_KEY,
  ]
Definition at line 62 of file InsuranceSpreadsheetExporter.php.
FILE_TYPES
const FILE_TYPES inherited
Initial value:
= [
    ExportFormat::EXCEL => [
      'writer' => 'Xlsx',
      'mimeType' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'extension' => 'xlsx',
    ],
    ExportFormat::ODS => [
      'writer' => 'Ods',
      'mimeType' => 'application/vnd.oasis.opendocument.spreadsheet',
      'extension' => 'ods',
    ],
    ExportFormat::CSV => [
      'writer' => 'Csv',
      'mimeType' => 'text/csv',
      'extension' => 'csv',
    ],
    ExportFormat::HTML => [
      'writer' => 'Html',
      'mimeType' => 'text/html',
      'extension' => 'html',
    ],
    ExportFormat::PDF => [
      'writer' => 'Pdf\\Mpdf',
      'mimeType' => 'application/pdf',
      'extension' => 'pdf',
    ],
  ]
Array of supported file-types.
Definition at line 43 of file AbstractSpreadsheetExporter.php.
INPUT_INDEX_BILL_TO
const INPUT_INDEX_BILL_TO = self::INPUT_INDEX_MUSICIAN + 1 protected
Definition at line 75 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_BROKER
const INPUT_INDEX_BROKER = self::INPUT_INDEX_OWNER + 1 protected
Definition at line 77 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_DUE_DATE
const INPUT_INDEX_DUE_DATE = self::INPUT_INDEX_INSURANCE_RATE + 1 protected
Definition at line 85 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_INSURANCE_END
const INPUT_INDEX_INSURANCE_END = self::INPUT_INDEX_INSURANCE_START + 1 protected
Definition at line 88 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_INSURANCE_FEES
const INPUT_INDEX_INSURANCE_FEES = self::INPUT_INDEX_DUE_DATE + 1 protected
Definition at line 86 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_INSURANCE_RATE
const INPUT_INDEX_INSURANCE_RATE = self::INPUT_INDEX_INSURED_AMOUNT + 1 protected
Definition at line 84 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_INSURANCE_START
const INPUT_INDEX_INSURANCE_START = self::INPUT_INDEX_INSURANCE_FEES + 1 protected
Definition at line 87 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_INSURED_AMOUNT
const INPUT_INDEX_INSURED_AMOUNT = self::INPUT_INDEX_YEAR_OF_CONSTRUCTION + 1 protected
Definition at line 83 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_IS_ACCESSORY
const INPUT_INDEX_IS_ACCESSORY = self::INPUT_INDEX_OBJECT + 1 protected
Definition at line 80 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_MANUFACTURER
const INPUT_INDEX_MANUFACTURER = self::INPUT_INDEX_IS_ACCESSORY + 1 protected
Definition at line 81 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_MUSICIAN
const INPUT_INDEX_MUSICIAN = 0 protected
Definition at line 74 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_OBJECT
const INPUT_INDEX_OBJECT = self::INPUT_INDEX_SCOPE + 1 protected
Definition at line 79 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_OWNER
const INPUT_INDEX_OWNER = self::INPUT_INDEX_BILL_TO +1 protected
Definition at line 76 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_SCOPE
const INPUT_INDEX_SCOPE = self::INPUT_INDEX_BROKER + 1 protected
Definition at line 78 of file InsuranceSpreadsheetExporter.php.
INPUT_INDEX_YEAR_OF_CONSTRUCTION
const INPUT_INDEX_YEAR_OF_CONSTRUCTION = self::INPUT_INDEX_MANUFACTURER + 1 protected
Definition at line 82 of file InsuranceSpreadsheetExporter.php.
MANUFACTURER_KEY
const MANUFACTURER_KEY = 'manufacturer' protected
Definition at line 57 of file InsuranceSpreadsheetExporter.php.
MIN_WIDTH
const MIN_WIDTH = 20 protected inherited
Definition at line 40 of file AbstractSpreadsheetExporter.php.
MUSICIAN_KEY
const MUSICIAN_KEY = 'musician' protected
Definition at line 52 of file InsuranceSpreadsheetExporter.php.
OBJECT_KEY
const OBJECT_KEY = 'object' protected
Definition at line 53 of file InsuranceSpreadsheetExporter.php.
START_KEY
const START_KEY = 'start' protected
Definition at line 54 of file InsuranceSpreadsheetExporter.php.
TOTALS_KEY
const TOTALS_KEY = 'totals' protected
Definition at line 60 of file InsuranceSpreadsheetExporter.php.
WIDTH_EXTRA_SPACE
const WIDTH_EXTRA_SPACE = 2 protected inherited
Definition at line 39 of file AbstractSpreadsheetExporter.php.
YEAR_OF_CONSTRUCTION_KEY
const YEAR_OF_CONSTRUCTION_KEY = 'year' protected
Definition at line 58 of file InsuranceSpreadsheetExporter.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/PageRenderer/Export/InsuranceSpreadsheetExporter.php