CamerataDB: HaliteSymmetricCryptor Class Reference
HaliteSymmetricCryptor Class Reference
Use libsodium through Halite.
Public Member Functions
__construct (?string $encryptionKey=null)
setEncryptionKey (?string $encryptionKey)
Set the encryption-key to use.
getEncryptionKey ()
Fetch the installed encryption key, if any.
encrypt (?string $data)
{
Parameters
null | string $data
Returns
null|string
}
canEncrypt ()
{
Returns
bool
}
canDecrypt ()
{
Returns
bool
}
decrypt (?string $data)
Private Attributes
$encryptionKey
$haliteEncryptionKey
Detailed Description
Use libsodium through Halite.
Definition at line 35 of file HaliteSymmetricCryptor.php.
Constructor & Destructor Documentation
__construct()
__construct (?string $encryptionKey = null)
Parameters
null | string $encryptionKey
Definition at line 52 of file HaliteSymmetricCryptor.php.
References HaliteSymmetricCryptor\setEncryptionKey().
Member Function Documentation
canDecrypt()
canDecrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 150 of file HaliteSymmetricCryptor.php.
canEncrypt()
canEncrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 144 of file HaliteSymmetricCryptor.php.
decrypt()
decrypt (?string $data) inherited
Parameters
null | string $data
Returns
null|string
Implemented in CloudSymmetricCryptor, HaliteSymmetricStreamCryptor, SealCryptor, and OpenSSLAsymmetricCryptor.
Referenced by SealService\unseal().
encrypt()
encrypt (?string $data)
{
Parameters
null | string $data
Returns
null|string
}
Implements ICryptor.
Definition at line 98 of file HaliteSymmetricCryptor.php.
getEncryptionKey()
getEncryptionKey ()
Fetch the installed encryption key, if any.
Returns
null|string
Implements SymmetricCryptorInterface.
Definition at line 92 of file HaliteSymmetricCryptor.php.
setEncryptionKey()
setEncryptionKey (?string $encryptionKey)
Set the encryption-key to use.
If left empty then the data will be left unencrypted and just be passed through.
Parameters
null | string $encryptionKey
Returns
null|string The old encryption get.
Implements SymmetricCryptorInterface.
Definition at line 65 of file HaliteSymmetricCryptor.php.
Referenced by HaliteSymmetricCryptor\__construct().
Field Documentation
$encryptionKey
null string $encryptionKey private
Initial value:
=
  private const HALITE_MAGIC  Halite\Halite::VERSION_PREFIX
Definition at line 44 of file HaliteSymmetricCryptor.php.
$haliteEncryptionKey
Halite Symmetric EncryptionKey $haliteEncryptionKey private
Definition at line 47 of file HaliteSymmetricCryptor.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Crypto/HaliteSymmetricCryptor.php