CamerataDB: OrganizationalRolesService Class Reference
OrganizationalRolesService Class Reference
Check for authorization and supply contact information for several administrative roles.
Public Member Functions
__construct (protected ConfigService $configService,)
executiveBoardProject ()
Return the project entity for the executive board.
executiveBoardMembers ()
Return an array with all members of the executive board.
dedicatedBoardMemberParticipant (string $role, int $musicianId=0)
treasurerSignature ()
secretarySignature ()
presidentSignature ()
getTreasurer ()
getSecretary ()
getPresident ()
isBoardMember (string $uid)
Check whether the given or currently logged in user is a member of the executive board.
getBoardMember (string $uid)
Get the database entity for the matching executive board member.
isDedicatedBoardMember (string $role, ?string $uid=null, bool $allowGroupAccess=false)
Return true if the logged in or given user has a dedicated administrative role for the orchestra.
isTreasurer (?string $uid=null, bool $allowGroupAccess=false)
Return true if the logged in user is the treasurer.
isSecretary (?string $uid=null, bool $allowGroupAccess=false)
Return true if the logged in user is the secretary.
isPresident (?string $uid=null, bool $allowGroupAccess=false)
Return true if the logged in user is the president.
inTreasurerGroup (?string $uid=null)
Return true if the logged in user is in the treasurer group.
inSecretaryGroup (?string $uid=null)
Return true if the logged in user is in the secretary group.
inPresidentGroup (?string $uid=null)
Return true if the logged in user is in the president group.
treasurerContact ()
Contact information for the treasurer.
secretaryContact ()
Contact information for the secretary.
presidentContact ()
Contact information for the president.
isCloudAdmin (?string $uid=null)
Check for overall-adminess.
cloudAdminContact (bool $implode=false)
Contact information for the overall admins.
adminContact (bool $implode=false)
isGroupAdmin (?string $uid=null)
Check for overall-adminess.
groupAdminContact ()
Contact information for the group admins.
getGroupAdmins ()
Get all the sub-admins of the dedicated group.
Data Fields
const CLOUD_ADMIN_ROLE = 'cloudAdmin'
const GROUP_ADMIN_ROLE = 'groupAdmin'
const TREASURER_ROLE = 'treasurer'
const SECRETARY_ROLE = 'secretary'
const PRESIDENT_ROLE = 'president'
const BOARD_MEMBER_ROLE = 'boardMember'
const ROLES
const BOARD_MEMBERS
Private Attributes
Entities Project $executiveBoardProjectEntity = null
Detailed Description
Check for authorization and supply contact information for several administrative roles.
Definition at line 45 of file OrganizationalRolesService.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ConfigService $configService)
Definition at line 76 of file OrganizationalRolesService.php.
Member Function Documentation
adminContact()
adminContact (bool $implode = false)
Parameters
bool $implode
Returns
array
Definition at line 482 of file OrganizationalRolesService.php.
References OrganizationalRolesService\cloudAdminContact().
cloudAdminContact()
cloudAdminContact (bool $implode = false)
Contact information for the overall admins.
Parameters
bool $implode
Returns
string|array
Definition at line 471 of file OrganizationalRolesService.php.
Referenced by OrganizationalRolesService\adminContact().
dedicatedBoardMemberParticipant()
dedicatedBoardMemberParticipant (string $role, int $musicianId = 0)
Parameters
string $role
int $musicianId
Returns
null|Entities\ProjectParticipant
Definition at line 198 of file OrganizationalRolesService.php.
References OrganizationalRolesService\executiveBoardMembers().
Referenced by OrganizationalRolesService\getPresident(), OrganizationalRolesService\getSecretary(), and OrganizationalRolesService\getTreasurer().
executiveBoardMembers()
executiveBoardMembers ()
Return an array with all members of the executive board.
Returns
Collection
Definition at line 186 of file OrganizationalRolesService.php.
References OrganizationalRolesService\executiveBoardProject().
Referenced by OrganizationalRolesService\dedicatedBoardMemberParticipant(), OrganizationalRolesService\getBoardMember(), and OrganizationalRolesService\isBoardMember().
executiveBoardProject()
executiveBoardProject ()
Return the project entity for the executive board.
Returns
null|Entities\Project
Definition at line 171 of file OrganizationalRolesService.php.
Referenced by OrganizationalRolesService\executiveBoardMembers().
getBoardMember()
getBoardMember (string $uid)
Get the database entity for the matching executive board member.
Parameters
string $uid
Returns
null|Entities\ProjectParticipant
Definition at line 307 of file OrganizationalRolesService.php.
References OrganizationalRolesService\executiveBoardMembers().
getGroupAdmins()
getGroupAdmins ()
Get all the sub-admins of the dedicated group.
Returns
IUser[]
Definition at line 522 of file OrganizationalRolesService.php.
getPresident()
getPresident ()
Returns
null|Entities\ProjectParticipant
Definition at line 282 of file OrganizationalRolesService.php.
References OrganizationalRolesService\dedicatedBoardMemberParticipant().
getSecretary()
getSecretary ()
Returns
null|Entities\ProjectParticipant
Definition at line 276 of file OrganizationalRolesService.php.
References OrganizationalRolesService\dedicatedBoardMemberParticipant().
getTreasurer()
getTreasurer ()
Returns
null|Entities\ProjectParticipant
Definition at line 270 of file OrganizationalRolesService.php.
References OrganizationalRolesService\dedicatedBoardMemberParticipant().
groupAdminContact()
groupAdminContact ()
Contact information for the group admins.
Returns
array
Definition at line 504 of file OrganizationalRolesService.php.
inPresidentGroup()
inPresidentGroup (?string $uid = null)
Return true if the logged in user is in the president group.
Parameters
null | string $uid
Returns
bool
Definition at line 416 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isPresident().
inSecretaryGroup()
inSecretaryGroup (?string $uid = null)
Return true if the logged in user is in the secretary group.
Parameters
null | string $uid
Returns
bool
Definition at line 404 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isSecretary().
inTreasurerGroup()
inTreasurerGroup (?string $uid = null)
Return true if the logged in user is in the treasurer group.
Parameters
null | string $uid
Returns
bool
Definition at line 392 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isTreasurer().
isBoardMember()
isBoardMember (string $uid)
Check whether the given or currently logged in user is a member of the executive board.
Parameters
string $uid
Returns
bool
Definition at line 295 of file OrganizationalRolesService.php.
References OrganizationalRolesService\executiveBoardMembers().
isCloudAdmin()
isCloudAdmin (?string $uid = null)
Check for overall-adminess.
Parameters
null | string $uid
Returns
bool
Definition at line 458 of file OrganizationalRolesService.php.
isDedicatedBoardMember()
isDedicatedBoardMember (string $role, ?string $uid = null, bool $allowGroupAccess = false)
Return true if the logged in or given user has a dedicated administrative role for the orchestra.
Parameters
string $role
null | string $uid
bool $allowGroupAccess
Returns
bool
Definition at line 324 of file OrganizationalRolesService.php.
Referenced by OrganizationalRolesService\isPresident(), OrganizationalRolesService\isSecretary(), and OrganizationalRolesService\isTreasurer().
isGroupAdmin()
isGroupAdmin (?string $uid = null)
Check for overall-adminess.
Parameters
null | string $uid
Returns
bool
Definition at line 494 of file OrganizationalRolesService.php.
isPresident()
isPresident (?string $uid = null, bool $allowGroupAccess = false)
Return true if the logged in user is the president.
Parameters
null | string $uid
bool $allowGroupAccess
Returns
bool
Definition at line 380 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isDedicatedBoardMember().
Referenced by OrganizationalRolesService\inPresidentGroup().
isSecretary()
isSecretary (?string $uid = null, bool $allowGroupAccess = false)
Return true if the logged in user is the secretary.
Parameters
null | string $uid
bool $allowGroupAccess
Returns
bool
Definition at line 366 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isDedicatedBoardMember().
Referenced by OrganizationalRolesService\inSecretaryGroup().
isTreasurer()
isTreasurer (?string $uid = null, bool $allowGroupAccess = false)
Return true if the logged in user is the treasurer.
Parameters
null | string $uid
bool $allowGroupAccess
Returns
bool
Definition at line 352 of file OrganizationalRolesService.php.
References OrganizationalRolesService\isDedicatedBoardMember().
Referenced by OrganizationalRolesService\inTreasurerGroup().
presidentContact()
presidentContact ()
Contact information for the president.
Returns
array [ 'name' => USER, 'email' => EMAIL ].
Definition at line 446 of file OrganizationalRolesService.php.
presidentSignature()
presidentSignature ()
Returns
null|Image
Definition at line 264 of file OrganizationalRolesService.php.
secretaryContact()
secretaryContact ()
Contact information for the secretary.
Returns
array [ 'name' => USER, 'email' => EMAIL ].
Definition at line 436 of file OrganizationalRolesService.php.
secretarySignature()
secretarySignature ()
Returns
null|Image
Definition at line 258 of file OrganizationalRolesService.php.
treasurerContact()
treasurerContact ()
Contact information for the treasurer.
Returns
array [ 'name' => USER, 'email' => EMAIL ].
Definition at line 426 of file OrganizationalRolesService.php.
treasurerSignature()
treasurerSignature ()
Returns
null|Image
Definition at line 252 of file OrganizationalRolesService.php.
Field Documentation
$executiveBoardProjectEntity
Entities Project $executiveBoardProjectEntity = null private
Definition at line 73 of file OrganizationalRolesService.php.
BOARD_MEMBER_ROLE
const BOARD_MEMBER_ROLE = 'boardMember'
Definition at line 56 of file OrganizationalRolesService.php.
BOARD_MEMBERS
const BOARD_MEMBERS
Initial value:
= [
    self::PRESIDENT_ROLE,
    self::SECRETARY_ROLE,
    self::TREASURER_ROLE,
  ]
Definition at line 67 of file OrganizationalRolesService.php.
CLOUD_ADMIN_ROLE
const CLOUD_ADMIN_ROLE = 'cloudAdmin'
Definition at line 51 of file OrganizationalRolesService.php.
GROUP_ADMIN_ROLE
const GROUP_ADMIN_ROLE = 'groupAdmin'
Definition at line 52 of file OrganizationalRolesService.php.
PRESIDENT_ROLE
const PRESIDENT_ROLE = 'president'
Definition at line 55 of file OrganizationalRolesService.php.
ROLES
const ROLES
Initial value:
= [
    self::CLOUD_ADMIN_ROLE,
    self::GROUP_ADMIN_ROLE,
    self::PRESIDENT_ROLE,
    self::SECRETARY_ROLE,
    self::TREASURER_ROLE,
    self::BOARD_MEMBER_ROLE,
  ]
Definition at line 58 of file OrganizationalRolesService.php.
SECRETARY_ROLE
const SECRETARY_ROLE = 'secretary'
Definition at line 54 of file OrganizationalRolesService.php.
TREASURER_ROLE
const TREASURER_ROLE = 'treasurer'
Definition at line 53 of file OrganizationalRolesService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/OrganizationalRolesService.php