CamerataDB: OC_Calendar_Object Class Reference
OC_Calendar_Object Class Reference
This class manages our calendar objects.
Public Member Functions
__construct (ConfigService $configService)
getDTEndFromVEvent (mixed $vevent)
Returns the DTEND of an $vevent object.
cleanByAccessClass (string $ownerId, mixed $vobject)
Remove all properties which should not be exported for the AccessClass Confidential.
getAccessClassOptions ()
Returns the options for the access class of an event.
getRepeatOptions ()
Returns the options for the repeat rule of an repeating event.
getEndOptions ()
Returns the options for the end of an repeating event.
getMonthOptions ()
Returns the options for an monthly repeating event.
getWeeklyOptions ()
Returns the options for an weekly repeating event.
getWeekofMonth ()
Returns the options for an monthly repeating event which occurs on specific weeks of the month.
getByYearDayOptions ()
Returns the options for an yearly repeating event which occurs on specific days of the year.
getByMonthDayOptions ()
Returns the options for an yearly or monthly repeating event which occurs on specific days of the month.
getByMonthOptions ()
Returns the options for an yearly repeating event which occurs on specific month of the year.
getYearOptions ()
Eeturns the options for an yearly repeating event.
getByWeekNoOptions ()
Returns the options for an yearly repeating event which occurs on specific week numbers of the year.
validateRequest (mixed $request)
Validates a request.
createVCalendarFromRequest (mixed $request)
Creates an VCalendar Object from the request data.
updateVCalendarFromRequest (mixed $request, mixed $vcalendar)
Updates an VCalendar Object from the request data.
Static Protected Member Functions
static checkTime (string $time)
Validates time.
Detailed Description
This class manages our calendar objects.
Reduced to a minimal working setup just providing VCalendar entries from the old Owncloud event form requests.
@SuppressWarnings(PHPMD.CamelCaseClassName)
Definition at line 87 of file OC_Calendar_Object.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService)
Definition at line 92 of file OC_Calendar_Object.php.
Member Function Documentation
checkTime()
static checkTime (string $time) static protected
Validates time.
Parameters
string $time
Returns
boolean
Definition at line 515 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
cleanByAccessClass()
cleanByAccessClass (string $ownerId, mixed $vobject)
Remove all properties which should not be exported for the AccessClass Confidential.
Parameters
string $ownerId The UID of the owner of the object.
mixed $vobject Sabre VObject.
Returns
mixed
Definition at line 141 of file OC_Calendar_Object.php.
createVCalendarFromRequest()
createVCalendarFromRequest (mixed $request)
Creates an VCalendar Object from the request data.
Parameters
mixed $request
Returns
object created $vcalendar
Definition at line 533 of file OC_Calendar_Object.php.
References OC_Calendar_Object\updateVCalendarFromRequest().
getAccessClassOptions()
getAccessClassOptions ()
Returns the options for the access class of an event.
Returns
array - valid inputs for the access class of an event
Definition at line 185 of file OC_Calendar_Object.php.
getByMonthDayOptions()
getByMonthDayOptions ()
Returns the options for an yearly or monthly repeating event which occurs on specific days of the month.
Returns
array - valid inputs for yearly or monthly repeating events
Definition at line 294 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getByMonthOptions()
getByMonthOptions ()
Returns the options for an yearly repeating event which occurs on specific month of the year.
Returns
array - valid inputs for yearly repeating events
Definition at line 308 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\updateVCalendarFromRequest(), and OC_Calendar_Object\validateRequest().
getByWeekNoOptions()
getByWeekNoOptions ()
Returns the options for an yearly repeating event which occurs on specific week numbers of the year.
Returns
array - valid inputs for yearly repeating events
Definition at line 346 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getByYearDayOptions()
getByYearDayOptions ()
Returns the options for an yearly repeating event which occurs on specific days of the year.
Returns
array - valid inputs for yearly repeating events
Definition at line 280 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getDTEndFromVEvent()
getDTEndFromVEvent (mixed $vevent)
Returns the DTEND of an $vevent object.
Parameters
mixed $vevent vevent object.
Returns
mixed
Definition at line 106 of file OC_Calendar_Object.php.
getEndOptions()
getEndOptions ()
Returns the options for the end of an repeating event.
Returns
array - valid inputs for the end of an repeating events
Definition at line 217 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getMonthOptions()
getMonthOptions ()
Returns the options for an monthly repeating event.
Returns
array - valid inputs for monthly repeating events
Definition at line 231 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getRepeatOptions()
getRepeatOptions ()
Returns the options for the repeat rule of an repeating event.
Returns
array - valid inputs for the repeat rule of an repeating event
Definition at line 199 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getWeeklyOptions()
getWeeklyOptions ()
Returns the options for an weekly repeating event.
Returns
array - valid inputs for weekly repeating events
Definition at line 244 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\updateVCalendarFromRequest(), and OC_Calendar_Object\validateRequest().
getWeekofMonth()
getWeekofMonth ()
Returns the options for an monthly repeating event which occurs on specific weeks of the month.
Returns
array - valid inputs for monthly repeating events
Definition at line 262 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
getYearOptions()
getYearOptions ()
Eeturns the options for an yearly repeating event.
Returns
array - valid inputs for yearly repeating events
Definition at line 331 of file OC_Calendar_Object.php.
Referenced by OC_Calendar_Object\validateRequest().
updateVCalendarFromRequest()
updateVCalendarFromRequest (mixed $request, mixed $vcalendar)
Updates an VCalendar Object from the request data.
Parameters
mixed $request
mixed $vcalendar
Returns
mixed Updated $vcalendar.
@SuppressWarnings(PHPMD.CamelCaseVariableName) @SuppressWarnings(PHPMD.ShortVariableName)
Definition at line 565 of file OC_Calendar_Object.php.
References OC_Calendar_Object\getByMonthOptions(), and OC_Calendar_Object\getWeeklyOptions().
Referenced by OC_Calendar_Object\createVCalendarFromRequest().
validateRequest()
validateRequest (mixed $request)
Validates a request.
Parameters
mixed $request
Returns
mixed (array / boolean)
@SuppressWarnings(PHPMD.CamelCaseVariableName)
Definition at line 360 of file OC_Calendar_Object.php.
References OC_Calendar_Object\checkTime(), OC_Calendar_Object\getByMonthDayOptions(), OC_Calendar_Object\getByMonthOptions(), OC_Calendar_Object\getByWeekNoOptions(), OC_Calendar_Object\getByYearDayOptions(), OC_Calendar_Object\getEndOptions(), OC_Calendar_Object\getMonthOptions(), OC_Calendar_Object\getRepeatOptions(), OC_Calendar_Object\getWeeklyOptions(), OC_Calendar_Object\getWeekofMonth(), and OC_Calendar_Object\getYearOptions().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Legacy/Calendar/OC_Calendar_Object.php