CamerataDB: ConfigCheckService Class Reference
ConfigCheckService Class Reference
Check for a usable configuration.
Public Member Functions
__construct (ConfigService $configService, EntityManager $entityManager, IRootFolder $rootFolder, IShareManager $shareManager, ICalendarManager $calendarManager, IContactsManager $contactsManager, CalDavService $calDavService, CardDavService $cardDavService, EventsService $eventsService, AddressBookProvider $addressBookProvider, MigrationsService $migrationsService, SimpleSharingService $sharingService,)
configured ()
Return an array with necessary configuration items, being either true or false, depending the checks performed.
checkImapServer (string $host, int $port, ?string $secure, string $user, string $password,)
checkSmtpServer (string $host, int $port, ?string $secure, string $user, string $password,)
groupSharedExists (int $id, string $group, string $type, ?string $shareOwner=null)
Check whether the shared object exists.
groupShareObject (int $id, string $groupId, string $type='calendar', ?string $shareOwner=null)
Share an object between the members of the specified group.
shareGroupExists ()
Return true if the share-group is set as application configuration option and exists.
shareOwnerExists (?string $shareOwnerId=null)
Return true if the share-owner exists and belongs to the orchestra user group (and only to this group).
checkShareOwner (string $shareOwnerId, ?string $shareOwnerPassword=null)
Make sure the "sharing" user exists, create it when necessary.
sharedFolderExists (?string $sharedFolder='')
We require that the share-owner owns a directory shared with the orchestra group.
checkSharedFolder (string $sharedFolder)
Check for the existence of the shared folder and create it when not found.
checkLinkSharedFolder (string $sharedFolder)
Check for the existence of the shared folder and create it when not found.
checkProjectFolder (string $projectFolder)
Check for existence of the project folder and create it when not found.
checkSharedCalendar (string $uri, ?string $displayName=null, ?int $id=null)
Check for existence of the given calendar.
checkSharedAddressBook (string $uri, ?string $displayName=null, ?int $id=null)
Check for existence of the given addressBook.
databaseAccessible ()
Check whether we have data-base access by connecting to the data-base server and selecting the configured data-base.
noUnappliedMigrations ()
Data Fields
const SHARE_PERMISSIONS
Private Member Functions
sharedAddressBooksExist ()
Private Attributes
$entityManager
$rootFolder
$shareManager
$calDavService
$cardDavService
$calendarManager
$contactsManager
$addressBookProvider
$migrationsService
$sharingService
Detailed Description
Check for a usable configuration.
Definition at line 50 of file ConfigCheckService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, EntityManager $entityManager, IRootFolder $rootFolder, IShareManager $shareManager, ICalendarManager $calendarManager, IContactsManager $contactsManager, CalDavService $calDavService, CardDavService $cardDavService, EventsService $eventsService, AddressBookProvider $addressBookProvider, MigrationsService $migrationsService, SimpleSharingService $sharingService)
Definition at line 93 of file ConfigCheckService.php.
Member Function Documentation
checkImapServer()
checkImapServer (string $host, int $port, ?string $secure, string $user, string $password)
Parameters
string $host
int $port
null | string $secure
string $user
string $password
Returns
bool
Definition at line 249 of file ConfigCheckService.php.
checkLinkSharedFolder()
checkLinkSharedFolder (string $sharedFolder)
Check for the existence of the shared folder and create it when not found.
Parameters
string $sharedFolder The name of the folder.
Returns
bool true on success.
Todo:
The sudo() stuff should no longer be neccessary.
Definition at line 680 of file ConfigCheckService.php.
checkProjectFolder()
checkProjectFolder (string $projectFolder)
Check for existence of the project folder and create it when not found.
Parameters
string $projectFolder The name of the folder. The name may be composed of several path components.
Returns
bool true on success.
Definition at line 752 of file ConfigCheckService.php.
checkSharedAddressBook()
checkSharedAddressBook (string $uri, ?string $displayName = null, ?int $id = null)
Check for existence of the given addressBook.
Create one if it could not be found. Make sure it is shared between the orchestra group.
Parameters
string $uri The local URI of the addressBook.
null | string $displayName The display-name of the addressBook.
null | int $id The id of the addressBook.
Returns
int -1 on error, addressBook id on success.
Definition at line 951 of file ConfigCheckService.php.
checkSharedCalendar()
checkSharedCalendar (string $uri, ?string $displayName = null, ?int $id = null)
Check for existence of the given calendar.
Create one if it could not be found. Make sure it is shared between the orchestra group.
Parameters
string $uri The local URI of the calendar.
null | string $displayName The display-name of the calendar.
null | int $id The id of the calendar.
Returns
int -1 on error, calendar id on success.
Definition at line 829 of file ConfigCheckService.php.
checkSharedFolder()
checkSharedFolder (string $sharedFolder)
Check for the existence of the shared folder and create it when not found.
Parameters
string $sharedFolder The name of the folder.
Returns
bool true on success.
Definition at line 597 of file ConfigCheckService.php.
checkShareOwner()
checkShareOwner (string $shareOwnerId, ?string $shareOwnerPassword = null)
Make sure the "sharing" user exists, create it when necessary.
May throw an exception.
Parameters
string $shareOwnerId The account id holding the shared resources.
null | string $shareOwnerPassword
Returns
bool true on success.
Definition at line 476 of file ConfigCheckService.php.
checkSmtpServer()
checkSmtpServer (string $host, int $port, ?string $secure, string $user, string $password)
Parameters
string $host
int $port
null | string $secure Enum, 'insecure', 'ssl', 'starttls'.
string $user
string $password
Returns
bool
Definition at line 276 of file ConfigCheckService.php.
configured()
configured ()
Return an array with necessary configuration items, being either true or false, depending the checks performed.
The summary component is just the logic and of all other items.
Returns
array
[ 'summary',
  'usergroup',
  'encryptionkey'
  'orchestra',
  'shareowner',
  'sharedfolder',
  'database',
]
where summary is a bool and everything else is array('status','message') where 'message' should be empty if status is true.
Definition at line 147 of file ConfigCheckService.php.
References ConfigCheckService\databaseAccessible(), ConfigCheckService\noUnappliedMigrations(), ConfigCheckService\sharedAddressBooksExist(), ConfigCheckService\sharedFolderExists(), ConfigCheckService\shareGroupExists(), and ConfigCheckService\shareOwnerExists().
databaseAccessible()
databaseAccessible ()
Check whether we have data-base access by connecting to the data-base server and selecting the configured data-base.
Returns
bool true on success.
Definition at line 1022 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
groupSharedExists()
groupSharedExists (int $id, string $group, string $type, ?string $shareOwner = null)
Check whether the shared object exists.
Note: this function has to be executed under the uid of the user the object belongs to. See ConfigService::sudo().
Parameters
int $id The numeric id of the object (not the name).
string $group The group to share the item with.
string $type The type of the item, for exmaple calendar, event, folder, file etc.
null | string $shareOwner
Returns
bool true for success, false on error.
Definition at line 337 of file ConfigCheckService.php.
groupShareObject()
groupShareObject (int $id, string $groupId, string $type = 'calendar', ?string $shareOwner = null)
Share an object between the members of the specified group.
Note: this function has to be executed under the uid of the user the object belongs to. See ConfigService::sudo().
Parameters
int $id The numeric id of the object (not the name).
string $groupId The group to share the item with.
string $type The type of the item, for exmaple calendar, event, folder, file etc.
null | string $shareOwner The user sharing the object.
Returns
bool true for success, false on error.
Definition at line 377 of file ConfigCheckService.php.
noUnappliedMigrations()
noUnappliedMigrations ()
Returns
bool
Definition at line 1058 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
sharedAddressBooksExist()
sharedAddressBooksExist () private
Returns
bool
Definition at line 898 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
sharedFolderExists()
sharedFolderExists (?string $sharedFolder = '')
We require that the share-owner owns a directory shared with the orchestra group.
Check whether this folder exists.
Parameters
null | string $sharedFolder Optional. If unset, the name is fetched from the application configuration options.
Returns
bool true on success.
Definition at line 551 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
shareGroupExists()
shareGroupExists ()
Return true if the share-group is set as application configuration option and exists.
Returns
bool
Definition at line 421 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
shareOwnerExists()
shareOwnerExists (?string $shareOwnerId = null)
Return true if the share-owner exists and belongs to the orchestra user group (and only to this group).
Parameters
null | string $shareOwnerId Optional. If unset, then the uid is fetched from the application configuration options.
Returns
bool true on success.
Definition at line 435 of file ConfigCheckService.php.
Referenced by ConfigCheckService\configured().
Field Documentation
$addressBookProvider
AddressBookProvider $addressBookProvider private
Definition at line 84 of file ConfigCheckService.php.
$calDavService
CalDavService $calDavService private
Definition at line 72 of file ConfigCheckService.php.
$calendarManager
OCP Calendar IManager $calendarManager private
Definition at line 78 of file ConfigCheckService.php.
$cardDavService
CardDavService $cardDavService private
Definition at line 75 of file ConfigCheckService.php.
$contactsManager
OCP Contacts IManager $contactsManager private
Definition at line 81 of file ConfigCheckService.php.
$entityManager
EntityManager $entityManager private
Definition at line 63 of file ConfigCheckService.php.
$migrationsService
MigrationsService $migrationsService private
Definition at line 87 of file ConfigCheckService.php.
$rootFolder
IRootFolder $rootFolder private
Definition at line 66 of file ConfigCheckService.php.
$shareManager
OCP Share IManager $shareManager private
Definition at line 69 of file ConfigCheckService.php.
$sharingService
SimpleSharingService $sharingService private
Definition at line 90 of file ConfigCheckService.php.
SHARE_PERMISSIONS
const SHARE_PERMISSIONS
Initial value:
= (
      \OCP\Constants::PERMISSION_CREATE
      | \OCP\Constants::PERMISSION_READ
      | \OCP\Constants::PERMISSION_UPDATE
      | \OCP\Constants::PERMISSION_DELETE
      | \OCP\Constants::PERMISSION_SHARE
  )
Definition at line 54 of file ConfigCheckService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/ConfigCheckService.php