CamerataDB: DatabaseProgressStatus Class Reference
DatabaseProgressStatus Class Reference
Progress-status via database table.
Public Member Functions
__construct (string $appName, ILogger $logger, IL10N $l10n, IDBConnection $db,)
delete ()
{Delete the underlying storage object.Afterwards any operation except $this->bind() will exhibit undefined behaviour.
Returns
void
}
bind (mixed $id)
{Bind to the given storage object.Create a new object if $id is null.
Parameters
mixed $id Opaque data identifying the progress status object.
Returns
void
}
getId ()
{Obtain a unique but opaque identifier (e.g.the id column in a database up to a serialized representation).
Returns
mixed
}
update (int $current, ?int $target=null, ?array $data=null)
{Update to the given values, where null arguments are simply ignored.This function has to write the given values through to the underlying storage.
Parameters
int $current
null | int $target If null the target remains unchanged.
null | array $data "user"-data stored in the progress-status object. Can be retrieved later via getData(). If null then the currently stored data remains unchanged.
Returns
bool true on success, false if the underlying storage has been deleted.
}
sync ()
{Synchronize with the underlying storage, i.e.read the data into this instance.
Returns
void
}
getCurrent ()
{Return the cached value of the current state.
Returns
int
}
getTarget ()
{Return the cached value of the target state.
Returns
int
}
getLastModified ()
{Return the cached value of the last modification time.
Returns
DateTimeInterface
}
getData ()
{Return the cached value of the custom data, i.e.the data previously passed to update().
Returns
null|array
}
increment (int $delta=1)
{Add the given amount to the progress-status counter.
Parameters
int $delta Amount to add, defaults to 1. Negative values are allowed.
Returns
bool|int Current value of the counter or false if the underlying storage has been deleted.
}
setCurrent (int $current)
{Set the current value and sync.
Parameters
int $current
Returns
void
}
setTarget (int $target)
{Set the target value and sync.
Parameters
int $target
Returns
void
}
setData (array $data)
{Set the data value and sync.
Parameters
array $data
Returns
void
}
Data Fields
const ENTITY_NAME = Entities\ProgressStatus::class
Protected Attributes
$mapper
$entity
Detailed Description
Progress-status via database table.
Definition at line 42 of file DatabaseProgressStatus.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, ILogger $logger, IL10N $l10n, IDBConnection $db)
Definition at line 55 of file DatabaseProgressStatus.php.
Member Function Documentation
bind()
bind (mixed $id)
{Bind to the given storage object.Create a new object if $id is null.
Parameters
mixed $id Opaque data identifying the progress status object.
Returns
void
}
Implements IProgressStatus.
Definition at line 78 of file DatabaseProgressStatus.php.
References DatabaseProgressStatus\sync().
delete()
delete ()
{Delete the underlying storage object.Afterwards any operation except $this->bind() will exhibit undefined behaviour.
Returns
void
}
Implements IProgressStatus.
Definition at line 69 of file DatabaseProgressStatus.php.
getCurrent()
getCurrent ()
{Return the cached value of the current state.
Returns
int
}
Implements IProgressStatus.
Definition at line 145 of file DatabaseProgressStatus.php.
getData()
getData ()
{Return the cached value of the custom data, i.e.the data previously passed to update().
Returns
null|array
}
Implements IProgressStatus.
Definition at line 163 of file DatabaseProgressStatus.php.
getId()
getId ()
{Obtain a unique but opaque identifier (e.g.the id column in a database up to a serialized representation).
Returns
mixed
}
Implements IProgressStatus.
Definition at line 114 of file DatabaseProgressStatus.php.
getLastModified()
getLastModified ()
{Return the cached value of the last modification time.
Returns
DateTimeInterface
}
Implements IProgressStatus.
Definition at line 157 of file DatabaseProgressStatus.php.
References DatabaseProgressStatus\getLastModified().
Referenced by DatabaseProgressStatus\getLastModified().
getTarget()
getTarget ()
{Return the cached value of the target state.
Returns
int
}
Implements IProgressStatus.
Definition at line 151 of file DatabaseProgressStatus.php.
increment()
increment (int $delta = 1) inherited
{Add the given amount to the progress-status counter.
Parameters
int $delta Amount to add, defaults to 1. Negative values are allowed.
Returns
bool|int Current value of the counter or false if the underlying storage has been deleted.
}
Implements IProgressStatus.
Definition at line 33 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), and IProgressStatus\update().
setCurrent()
setCurrent (int $current) inherited
{Set the current value and sync.
Parameters
int $current
Returns
void
}
Implements IProgressStatus.
Definition at line 42 of file AbstractProgressStatus.php.
References IProgressStatus\update().
setData()
setData (array $data) inherited
{Set the data value and sync.
Parameters
array $data
Returns
void
}
Implements IProgressStatus.
Definition at line 54 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), IProgressStatus\getTarget(), and IProgressStatus\update().
setTarget()
setTarget (int $target) inherited
{Set the target value and sync.
Parameters
int $target
Returns
void
}
Implements IProgressStatus.
Definition at line 48 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), and IProgressStatus\update().
sync()
sync ()
{Synchronize with the underlying storage, i.e.read the data into this instance.
Returns
void
}
Implements IProgressStatus.
Definition at line 139 of file DatabaseProgressStatus.php.
Referenced by DatabaseProgressStatus\bind().
update()
update (int $current, ?int $target = null, ?array $data = null)
{Update to the given values, where null arguments are simply ignored.This function has to write the given values through to the underlying storage.
Parameters
int $current
null | int $target If null the target remains unchanged.
null | array $data "user"-data stored in the progress-status object. Can be retrieved later via getData(). If null then the currently stored data remains unchanged.
Returns
bool true on success, false if the underlying storage has been deleted.
}
Implements IProgressStatus.
Definition at line 120 of file DatabaseProgressStatus.php.
Field Documentation
$entity
Entities ProgressStatus $entity protected
Definition at line 52 of file DatabaseProgressStatus.php.
$mapper
Mapper ProgressStatusMapper $mapper protected
Definition at line 49 of file DatabaseProgressStatus.php.
ENTITY_NAME
const ENTITY_NAME = Entities\ProgressStatus::class
Definition at line 46 of file DatabaseProgressStatus.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/DatabaseProgressStatus.php