CamerataDB: UndoableFolderRename Class Reference
UndoableFolderRename Class Reference
Rename the given paths.
Public Member Functions
__construct (protected string|Closure $oldName, protected string|Closure $newName, protected bool $gracefully=false, protected bool $mkdir=true,)
Undoable folder rename, optionally ignoring non-existing source folder.
undo ()
{Undo that what was done by do().
Returns
void
}
reset ()
{Reset initial state.
Returns
void
}
initialize (IAppContainer $appContainer)
{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}
do ()
Do something.
Protected Member Functions
renamedName (string $path)
Create a new unique name for renaming.
Static Protected Member Functions
static normalizePath (string $path)
Remove multipled slashes.
Protected Attributes
$undoAction
$doneInterval
IL10N $l
$timeFactory
$userStorage
$appContainer
Private Attributes
const UNDO_DELETE = 'delete'
const UNDO_RENAME = 'rename'
const UNDO_RESTORE = 'restore'
const UNDO_NOTHING = 'nothing'
Detailed Description
Rename the given paths.
The target path will be created if it does not exist. If the source path is empty the target folder will be created as empty folder.
If the target folder is empty, then the source folder will be deleted if it is empty. Non empty folders will bot be deleted.
@SuppressWarnings(PHPMD.ShortMethodName)
Definition at line 44 of file UndoableFolderRename.php.
Constructor & Destructor Documentation
__construct()
__construct (protected string|Closure $oldName, protected string|Closure $newName, protected bool $gracefully = false, protected bool $mkdir = true)
Undoable folder rename, optionally ignoring non-existing source folder.
Parameters
string | Closure $oldName
string | Closure $newName
bool $gracefully Do not throw if the source-folder given as $oldName does not exist.
bool $mkdir Create non-existing directories.
Definition at line 69 of file UndoableFolderRename.php.
Member Function Documentation
do()
do () inherited
Do something.
Returns
void
Implemented in GenericUndoable, UndoableFileRename, and UndoableFileReplace.
initialize()
initialize (IAppContainer $appContainer) inherited
{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}
Reimplemented from AbstractUndoable.
Reimplemented in UndoableFileReplace, UndoableFileSystemNodeRemove, UndoableFolderCreate, and UndoableTextFileUpdate.
Definition at line 49 of file AbstractFileSystemUndoable.php.
normalizePath()
static normalizePath (string $path) static protected inherited
Remove multipled slashes.
Parameters
string $path
Returns
string
Definition at line 65 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFileRename\do(), and UndoableFileReplace\do().
renamedName()
renamedName (string $path) protected inherited
Create a new unique name for renaming.
Parameters
string $path
Returns
string
Definition at line 79 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFolderCreate\reset(), UndoableTextFileUpdate\reset(), UndoableFolderCreate\undo(), and UndoableTextFileUpdate\undo().
reset()
reset ()
{Reset initial state.
Returns
void
}
Implements IUndoable.
Definition at line 167 of file UndoableFolderRename.php.
undo()
undo ()
{Undo that what was done by do().
Returns
void
}
Implements IUndoable.
Definition at line 151 of file UndoableFolderRename.php.
Field Documentation
$appContainer
IAppContainer $appContainer protected inherited
Definition at line 33 of file AbstractUndoable.php.
$doneInterval
array< int, int > $doneInterval protected
Definition at line 55 of file UndoableFolderRename.php.
$l
IL10N $l protected inherited
Definition at line 40 of file AbstractFileSystemUndoable.php.
$timeFactory
ITimeFactory $timeFactory protected inherited
Definition at line 43 of file AbstractFileSystemUndoable.php.
$undoAction
string $undoAction protected
Definition at line 52 of file UndoableFolderRename.php.
$userStorage
UserStorage $userStorage protected inherited
Definition at line 46 of file AbstractFileSystemUndoable.php.
UNDO_DELETE
const UNDO_DELETE = 'delete' private
Definition at line 46 of file UndoableFolderRename.php.
UNDO_NOTHING
const UNDO_NOTHING = 'nothing' private
Definition at line 49 of file UndoableFolderRename.php.
UNDO_RENAME
const UNDO_RENAME = 'rename' private
Definition at line 47 of file UndoableFolderRename.php.
UNDO_RESTORE
const UNDO_RESTORE = 'restore' private
Definition at line 48 of file UndoableFolderRename.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Common/UndoableFolderRename.php