CamerataDB: OC_Calendar_App Class Reference
OC_Calendar_App Class Reference
Wrapper to provide the hooks needed by the old OC calendar code.
Public Member Functions
__construct (ConfigService $configService, \OCP\Calendar\IManager $calendarManager, \OCP\ITagManager $tagManager,)
getCategoryOptions ()
returns the categories of the vcategories object
Private Member Functions
getDefaultCategories ()
returns the default categories of ownCloud
getVCategories ()
returns the vcategories object of the user
scanCategories (mixed $events=null)
Scan events for categories.
Private Attributes
$calendarManager
$tagManager
$categories
Detailed Description
Wrapper to provide the hooks needed by the old OC calendar code.
@SuppressWarnings(PHPMD.CamelCaseClassName)
Definition at line 44 of file OC_Calendar_App.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, \OCP\Calendar\IManager $calendarManager, \OCP\ITagManager $tagManager)
Definition at line 58 of file OC_Calendar_App.php.
Member Function Documentation
getCategoryOptions()
getCategoryOptions ()
returns the categories of the vcategories object
Returns
(array) $categories
Definition at line 73 of file OC_Calendar_App.php.
References OC_Calendar_App\getVCategories().
getDefaultCategories()
getDefaultCategories () private
returns the default categories of ownCloud
Returns
(array) $categories
Definition at line 88 of file OC_Calendar_App.php.
Referenced by OC_Calendar_App\getVCategories().
getVCategories()
getVCategories () private
returns the vcategories object of the user
Returns
(object) $vcategories
Definition at line 97 of file OC_Calendar_App.php.
References OC_Calendar_App\getDefaultCategories(), and OC_Calendar_App\scanCategories().
Referenced by OC_Calendar_App\getCategoryOptions().
scanCategories()
scanCategories (mixed $events = null) private
Scan events for categories.
Parameters
mixed $events VEVENTs to scan. null to check all events for the current user.
Returns
void
Definition at line 116 of file OC_Calendar_App.php.
Referenced by OC_Calendar_App\getVCategories().
Field Documentation
$calendarManager
OCP Calendar IManager $calendarManager private
Definition at line 49 of file OC_Calendar_App.php.
$categories
string[] $categories private
Definition at line 55 of file OC_Calendar_App.php.
$tagManager
OCP ITagManager $tagManager private
Definition at line 52 of file OC_Calendar_App.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Legacy/Calendar/OC_Calendar_App.php