CamerataDB: ProjectEventEntityListener Class Reference
ProjectEventEntityListener Class Reference
An entity listener for Entities\ProjectEvent.
Public Member Functions
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager,)
postPersist (Entities\ProjectEvent $project, ORMEvent\PostPersistEventArgs $eventArgs)
{}
preUpdate (Entities\ProjectEvent $project, ORMEvent\PreUpdateEventArgs $eventArgs)
{}
preRemove (Entities\ProjectEvent $project, ORMEvent\PreRemoveEventArgs $eventArgs)
{}
Protected Attributes
IL10N $l
$eventsService
$preCommitActions
Private Member Functions
registerPreCommitAction (Entities\ProjectEvent $projectEvent)
Detailed Description
An entity listener for Entities\ProjectEvent.
The task is to remove the absence category from the associated calendar event when removing the absence field entity from the event entity. The other way round (adding the absence field category when the absence field is set) need not be handled as the absence field is set as a reaction to setting the "record absence" category. However, the absence field itself may be removed through the UI in which case the absenceField property of the project-event is set to null. In this case we want also remove the absence category from the associated calendar event.
Definition at line 58 of file ProjectEventEntityListener.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager)
Definition at line 72 of file ProjectEventEntityListener.php.
Member Function Documentation
postPersist()
postPersist (Entities\ProjectEvent $project, ORMEvent\PostPersistEventArgs $eventArgs)
{}
Definition at line 83 of file ProjectEventEntityListener.php.
References ProjectEventEntityListener\registerPreCommitAction().
preRemove()
preRemove (Entities\ProjectEvent $project, ORMEvent\PreRemoveEventArgs $eventArgs)
{}
Definition at line 101 of file ProjectEventEntityListener.php.
References ProjectEventEntityListener\registerPreCommitAction().
preUpdate()
preUpdate (Entities\ProjectEvent $project, ORMEvent\PreUpdateEventArgs $eventArgs)
{}
Definition at line 91 of file ProjectEventEntityListener.php.
References ProjectEventEntityListener\registerPreCommitAction().
registerPreCommitAction()
registerPreCommitAction (Entities\ProjectEvent $projectEvent) private
Parameters
Entities\\ProjectEvent $projectEvent
Returns
void
Definition at line 111 of file ProjectEventEntityListener.php.
Referenced by ProjectEventEntityListener\postPersist(), ProjectEventEntityListener\preRemove(), and ProjectEventEntityListener\preUpdate().
Field Documentation
$eventsService
EventsService $eventsService protected
Definition at line 66 of file ProjectEventEntityListener.php.
$l
IL10N $l protected
Definition at line 63 of file ProjectEventEntityListener.php.
$preCommitActions
IUndoable[] $preCommitActions protected
Definition at line 69 of file ProjectEventEntityListener.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Listener/ProjectEventEntityListener.php