CamerataDB: ContactsAddressBook Class Reference
ContactsAddressBook Class Reference
Addressbook connection for musician database.
Public Member Functions
__construct (ConfigService $configService, ContactsService $contactsService, ICardBackend $cardBackend, ?string $uri=null,)
{}
getKey ()
{}
getUri ()
{}
getDisplayName ()
{}
search ($pattern, $searchProperties, $options)
{}
createOrUpdate ($properties)
{}
getPermissions ()
{}
delete ($id)
{}
isShared ()
{}
isSystemAddressBook ()
{}
Data Fields
const DAV_PROPERTY_SOURCE = 'X-CAFEVDB_CONTACTS_ID'
Private Member Functions
vCard2Array (string $cardUri, VCard $vCard, bool $withTypes)
The search() function has to return its result in a certain format, generate that for a single VCard instance.
Private Attributes
$cardBackend
$contactsService
$uri
Detailed Description
Addressbook connection for musician database.
Definition at line 45 of file ContactsAddressBook.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ContactsService $contactsService, ICardBackend $cardBackend, ?string $uri = null)
{}
Definition at line 61 of file ContactsAddressBook.php.
Member Function Documentation
createOrUpdate()
createOrUpdate ($properties)
{}
Definition at line 157 of file ContactsAddressBook.php.
delete()
delete ($id)
{}
Definition at line 169 of file ContactsAddressBook.php.
getDisplayName()
getDisplayName ()
{}
Definition at line 87 of file ContactsAddressBook.php.
getKey()
getKey ()
{}
Definition at line 75 of file ContactsAddressBook.php.
getPermissions()
getPermissions ()
{}
Definition at line 163 of file ContactsAddressBook.php.
getUri()
getUri ()
{}
Definition at line 81 of file ContactsAddressBook.php.
Referenced by ContactsAddressBook\vCard2Array().
isShared()
isShared ()
{}
Definition at line 175 of file ContactsAddressBook.php.
isSystemAddressBook()
isSystemAddressBook ()
{}
Definition at line 181 of file ContactsAddressBook.php.
search()
search ($pattern, $searchProperties, $options)
{}
Definition at line 93 of file ContactsAddressBook.php.
References ContactsAddressBook\vCard2Array().
vCard2Array()
vCard2Array (string $cardUri, VCard $vCard, bool $withTypes) private
The search() function has to return its result in a certain format, generate that for a single VCard instance.
Parameters
string $cardUri Card id.
VCard $vCard Sabre object.
bool $withTypes Passed on to flattenVCard of contacts-service.
Returns
array
Definition at line 137 of file ContactsAddressBook.php.
References ContactsAddressBook\getUri().
Referenced by ContactsAddressBook\search().
Field Documentation
$cardBackend
ICardBackend $cardBackend private
Definition at line 50 of file ContactsAddressBook.php.
$contactsService
ContactsService $contactsService private
Definition at line 53 of file ContactsAddressBook.php.
$uri
string $uri private
Definition at line 56 of file ContactsAddressBook.php.
DAV_PROPERTY_SOURCE
const DAV_PROPERTY_SOURCE = 'X-CAFEVDB_CONTACTS_ID'
Definition at line 58 of file ContactsAddressBook.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/AddressBook/ContactsAddressBook.php