CamerataDB: ProjectsRepository Class Reference
ProjectsRepository Class Reference
Entity repository for projects.
Public Member Functions
findAll ()
Sort by configured sorting column.
findById ($projectOrId)
Find a project by its Id.
ensureProject ($projectOrId)
Convenience function: just return the argument if it is already a project entity, otherwise fetch the project, repectively generate a reference.
shortDescription ()
Fetch a short description for all projects.
findYearRange ()
Return minimum and maximum year of all projects.
getEntityManager ()
Public export of parent function.
Data Fields
const ALIAS = 'proj'
Detailed Description
Entity repository for projects.
Definition at line 30 of file ProjectsRepository.php.
Member Function Documentation
ensureProject()
ensureProject ($projectOrId)
Convenience function: just return the argument if it is already a project entity, otherwise fetch the project, repectively generate a reference.
Parameters
int | Entities\\Project $projectOrId
Returns
null|Entities\Project
Definition at line 80 of file ProjectsRepository.php.
References ProjectsRepository\findById().
findAll()
findAll ()
Sort by configured sorting column.
Returns
iterable
Definition at line 41 of file ProjectsRepository.php.
Referenced by ProjectsRepository\shortDescription().
findById()
findById ($projectOrId)
Find a project by its Id.
Parameters
array | int $projectOrId This may either be an integer – the plain id – or "something" array-like with an 'id' index.
Returns
null|Entities\Project
Definition at line 57 of file ProjectsRepository.php.
Referenced by ProjectsRepository\ensureProject().
findYearRange()
findYearRange ()
Return minimum and maximum year of all projects.
Returns
array<string, int>
[
  'min' => MIN_YEAR,
  'max' => MAX_YEAR,
]
Definition at line 138 of file ProjectsRepository.php.
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
shortDescription()
shortDescription ()
Fetch a short description for all projects.
Returns
array
[
  'projects' => [ ID => [ 'name' => NAME, 'year' => YEAR ], ... ],
  'nameByName' => [ NAME => NAME, ... ],
  'yearByName' => [ NAME => YEAR, ... ],
]
nameByName is used by PME in order to construct select options etc.
Todo:
Could make this a custom hydrator.
Definition at line 107 of file ProjectsRepository.php.
References ProjectsRepository\findAll().
Field Documentation
ALIAS
const ALIAS = 'proj'
Definition at line 34 of file ProjectsRepository.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/ProjectsRepository.php