CamerataDB: LegacyEventsController Class Reference
LegacyEventsController Class Reference
Serves the requests issued by the old OC v8 event popups.
Public Member Functions
__construct (?string $appName, IRequest $request, ConfigService $configService, ConfigCheckService $configCheckService, RequestParameterService $parameterService, ProjectService $projectService, CalDavService $calDavService, VCalendarService $vCalendarService, ToolTipsService $toolTipsService, ISession $session,)
serviceSwitch (string $topic, string $subTopic)
exportEvent ()
Data Fields
const ERROR_TEMPLATE = "errorpage"
const READONLY_CATEGORIES = 1
const HIDDEN_CATEGORIES = 2
const SUBTOPIC_CLONE = 'clone'
const SUBTOPIC_NEW = 'new'
const SUBTOPIC_EDIT = 'edit'
const SUBTOPIC_DELETE = 'delete'
const SUBTOPIC_EXPORT = 'export'
Protected Attributes
$toolTipsService
Private Member Functions
newEventForm ()
editEventForm (string $subTopic)
Edit an existing event.
newEvent ()
editEvent ()
deleteEvent ()
generateEvent (string $uri, VCalendar $vObject, string $ownerId, int $permissions)
Exports an event and convert all times to UTC.
generateEventData (VCalendar $vObject, string $ownerId, int $permissions)
Serializes the VEVENT/VTODO/VJOURNAL with UTC dates.
accessClass (VCalendar $vObject)
fixLineBreaks (string $string)
Fixes new line breaks (fixes problems with Apple iCal).
Private Attributes
$session
$parameterService
$projectService
$configCheckService
$calDavService
$vCalendarService
$ocCalendarObject
Detailed Description
Serves the requests issued by the old OC v8 event popups.
Definition at line 50 of file LegacyEventsController.php.
Constructor & Destructor Documentation
__construct()
__construct (?string $appName, IRequest $request, ConfigService $configService, ConfigCheckService $configCheckService, RequestParameterService $parameterService, ProjectService $projectService, CalDavService $calDavService, VCalendarService $vCalendarService, ToolTipsService $toolTipsService, ISession $session)
Definition at line 91 of file LegacyEventsController.php.
Member Function Documentation
accessClass()
accessClass (VCalendar $vObject) private
Parameters
VCalendar $vObject
Returns
string
Definition at line 874 of file LegacyEventsController.php.
Referenced by LegacyEventsController\editEventForm(), and LegacyEventsController\exportEvent().
deleteEvent()
deleteEvent () private
Returns
Http\Response
Definition at line 760 of file LegacyEventsController.php.
Referenced by LegacyEventsController\serviceSwitch().
editEvent()
editEvent () private
Returns
Http\Response
Definition at line 727 of file LegacyEventsController.php.
Referenced by LegacyEventsController\serviceSwitch().
editEventForm()
editEventForm (string $subTopic) private
Edit an existing event.
If $subTopic equals self::SUBTOPIC_CLONE then a new event will be generated on save.
Parameters
string $subTopic
Returns
Http\Response
Definition at line 328 of file LegacyEventsController.php.
References LegacyEventsController\accessClass().
Referenced by LegacyEventsController\serviceSwitch().
exportEvent()
exportEvent ()
Returns
Http\Response
@NoAdminRequired
Definition at line 773 of file LegacyEventsController.php.
References LegacyEventsController\accessClass(), and LegacyEventsController\generateEvent().
Referenced by LegacyEventsController\serviceSwitch().
fixLineBreaks()
fixLineBreaks (string $string) private
Fixes new line breaks (fixes problems with Apple iCal).
Parameters
string $string to fix.
Returns
string
Definition at line 895 of file LegacyEventsController.php.
Referenced by LegacyEventsController\generateEvent().
generateEvent()
generateEvent (string $uri, VCalendar $vObject, string $ownerId, int $permissions) private
Exports an event and convert all times to UTC.
Parameters
string $uri
VCalendar $vObject
string $ownerId
int $permissions
Returns
string
Definition at line 830 of file LegacyEventsController.php.
References LegacyEventsController\fixLineBreaks(), and LegacyEventsController\generateEventData().
Referenced by LegacyEventsController\exportEvent().
generateEventData()
generateEventData (VCalendar $vObject, string $ownerId, int $permissions) private
Serializes the VEVENT/VTODO/VJOURNAL with UTC dates.
Parameters
VCalendar $vObject
string $ownerId
int $permissions
Returns
string
Definition at line 849 of file LegacyEventsController.php.
Referenced by LegacyEventsController\generateEvent().
newEvent()
newEvent () private
Returns
Http\Response
Definition at line 706 of file LegacyEventsController.php.
Referenced by LegacyEventsController\serviceSwitch().
newEventForm()
newEventForm () private
Returns
Http\Response
Definition at line 168 of file LegacyEventsController.php.
Referenced by LegacyEventsController\serviceSwitch().
serviceSwitch()
serviceSwitch (string $topic, string $subTopic)
Parameters
string $topic
string $subTopic
Returns
Http\Response
@NoAdminRequired @UseSession
Definition at line 129 of file LegacyEventsController.php.
References LegacyEventsController\deleteEvent(), LegacyEventsController\editEvent(), LegacyEventsController\editEventForm(), LegacyEventsController\exportEvent(), LegacyEventsController\newEvent(), and LegacyEventsController\newEventForm().
Field Documentation
$calDavService
CalDavService $calDavService private
Definition at line 79 of file LegacyEventsController.php.
$configCheckService
ConfigCheckService $configCheckService private
Definition at line 76 of file LegacyEventsController.php.
$ocCalendarObject
OC_Calendar_Object $ocCalendarObject private
Definition at line 85 of file LegacyEventsController.php.
$parameterService
RequestParameterService $parameterService private
Definition at line 70 of file LegacyEventsController.php.
$projectService
ProjectService $projectService private
Definition at line 73 of file LegacyEventsController.php.
$session
ISession $session private
Definition at line 67 of file LegacyEventsController.php.
$toolTipsService
ToolTipsService $toolTipsService protected
Definition at line 88 of file LegacyEventsController.php.
$vCalendarService
VCalendarService $vCalendarService private
Definition at line 82 of file LegacyEventsController.php.
ERROR_TEMPLATE
const ERROR_TEMPLATE = "errorpage"
Definition at line 55 of file LegacyEventsController.php.
HIDDEN_CATEGORIES
const HIDDEN_CATEGORIES = 2
Definition at line 58 of file LegacyEventsController.php.
READONLY_CATEGORIES
const READONLY_CATEGORIES = 1
Definition at line 57 of file LegacyEventsController.php.
SUBTOPIC_CLONE
const SUBTOPIC_CLONE = 'clone'
Definition at line 60 of file LegacyEventsController.php.
SUBTOPIC_DELETE
const SUBTOPIC_DELETE = 'delete'
Definition at line 63 of file LegacyEventsController.php.
SUBTOPIC_EDIT
const SUBTOPIC_EDIT = 'edit'
Definition at line 62 of file LegacyEventsController.php.
SUBTOPIC_EXPORT
const SUBTOPIC_EXPORT = 'export'
Definition at line 64 of file LegacyEventsController.php.
SUBTOPIC_NEW
const SUBTOPIC_NEW = 'new'
Definition at line 61 of file LegacyEventsController.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Controller/LegacyEventsController.php