CamerataDB: Navigation Class Reference
Navigation Class Reference
Support class to generate navigation buttons and the like.
Public Member Functions
__construct (string $appName, IL10N $l10n, ILogger $logger, ToolTipsService $toolTipsService, PMEOptions $pmeOptions,)
tableExportButton ()
Acutally rather a multi-select than a button, meant as drop-down menu.
prependTableButton (array $button, mixed $misc=false, bool $all=false)
Add a new button to the left of the already registered phpMyEdit buttons.
prependTableButtons (array $buttons, mixed $misc=false)
Add a new button to the left of the already registered phpMyEdit buttons.
buttonsFromArray (array $buttons)
htmlTagsFromArray (array $tags)
Generate some html tags.
pageControlElement (string $id='projects', string $projectName='', int $projectId=0,)
Generate a couple of standard buttons, identified by Ids.
Static Public Member Functions
static selectOptions (array $options, mixed $selectedValues=[])
Emit select options.
static simpleSelectOptions (array $options, ?string $selected=null)
Simple select option array from flat value array.
static persistentCGI (mixed $key, mixed $value=false)
Recursively emit hidden input elements to represent the given data.
Data Fields
const DISABLED = 1
const SELECTED = 2
Protected Attributes
$l
$toolTipsService
$pmeOptions
Detailed Description
Support class to generate navigation buttons and the like.
Definition at line 36 of file Navigation.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, IL10N $l10n, ILogger $logger, ToolTipsService $toolTipsService, PMEOptions $pmeOptions)
Definition at line 53 of file Navigation.php.
Member Function Documentation
buttonsFromArray()
buttonsFromArray (array $buttons)
Parameters
array $buttons
Returns
string HTML fragment
See also
htmlTagsFromArray
Definition at line 394 of file Navigation.php.
References Navigation\htmlTagsFromArray().
htmlTagsFromArray()
htmlTagsFromArray (array $tags)
Generate some html tags.
Up to now only buttons and option elements.
Parameters
array $tags
Returns
string HTML fragment.
Definition at line 407 of file Navigation.php.
Referenced by Navigation\buttonsFromArray().
pageControlElement()
pageControlElement (string $id = 'projects', string $projectName = '', int $projectId = 0)
Generate a couple of standard buttons, identified by Ids.
Parameters
string $id One of
projects Project Overview.
all Overview of all musicians.
email Mass-email dialog (obsolete).
emailhistory History of sent mass-emails (obsolete).
projectlabel A button which leads to an overview page of the current project, parameters $projectName and $projectId habe to be given.
detailed Instrumentation list for the project. Formerly there was also a "brief" instrumentation list, which is no longer there.
instruments List of all known instruments with cross-link to WikiPedia.
projectinstrumens Page with instrumentation number for the project.
debitmandates Page with debit mandates for the project.
insurances Page with instrument insurances.
insurancerates Page with knwon insurance rates.
insurancebrokers Page with knwon brokers, including (maybe) their address.
string $projectName name of the project if needed.
int $projectId Id of the project if needed form with submit button.
Returns
string The HTML form control requested.
Definition at line 553 of file Navigation.php.
persistentCGI()
static persistentCGI (mixed $key, mixed $value = false) static
Recursively emit hidden input elements to represent the given data.
$value may be a nested array.
Parameters
mixed $key
mixed $value
Returns
string HTML fragment.
Definition at line 210 of file Navigation.php.
References Navigation\persistentCGI().
Referenced by Navigation\persistentCGI().
prependTableButton()
prependTableButton (array $button, mixed $misc = false, bool $all = false)
Add a new button to the left of the already registered phpMyEdit buttons.
This is a dirty hack. But so what. Only the L and F (list and filter) views are augmented.
Parameters
array $button The new buttons.
bool | array $misc Whether or not to include the extra misc-button or a reordering of button positions.
bool $all Whether to add the button to non-list views.
Returns
array suitable to be plugged in $opts['buttons'].
Definition at line 284 of file Navigation.php.
References Navigation\prependTableButtons().
prependTableButtons()
prependTableButtons (array $buttons, mixed $misc = false)
Add a new button to the left of the already registered phpMyEdit buttons.
This is a dirty hack. But so what. Only the L and F (list and filter) views are augmented.
Parameters
array $buttons The new buttons.
bool | array $misc Whether or not to include the extra misc-button or a reordering of button positions.
Returns
array suitable to be plugged in $opts['buttons'].
Definition at line 301 of file Navigation.php.
Referenced by Navigation\prependTableButton().
selectOptions()
static selectOptions (array $options, mixed $selectedValues = []) static
Emit select options.
Parameters
array $options Array with option tags:
value => option value name => option name flags => optional or bit-wise or of self::DISABLED, self::SELECTED title => optional title label => optional label class => optional CSS class group => optional option group groupClass => optional css, only taken into account on group-change groupData => optional data array, only taken into account on group-change data => optional data for option data attributes
Optional fields need not be present.
Parameters
null | int | array $selectedValues Optional. Set Navigation::SELECTED for the given values. $selectedValues may be a single value or an array of values.
Returns
string HTML fragment.
Definition at line 91 of file Navigation.php.
Referenced by ProjectsController\changeInstrumentation(), and Navigation\simpleSelectOptions().
simpleSelectOptions()
static simpleSelectOptions (array $options, ?string $selected = null) static
Simple select option array from flat value array.
Parameters
array $options
null | string $selected Option to select by default.
Returns
HTML fragment.
Definition at line 189 of file Navigation.php.
References Navigation\selectOptions().
tableExportButton()
tableExportButton ()
Acutally rather a multi-select than a button, meant as drop-down menu.
Generates data which can be passed to prependTableButton() below.
Returns
array Return [ 'code' => HTML_FRAGMENT ]
Definition at line 237 of file Navigation.php.
Field Documentation
$l
OCP IL10N $l protected
Definition at line 44 of file Navigation.php.
$pmeOptions
OCA CAFEVDB Database Legacy PME IOptions $pmeOptions protected
Definition at line 50 of file Navigation.php.
$toolTipsService
OCA CAFEVDB Service ToolTipsService $toolTipsService protected
Definition at line 47 of file Navigation.php.
DISABLED
const DISABLED = 1
Definition at line 40 of file Navigation.php.
SELECTED
const SELECTED = 2
Definition at line 41 of file Navigation.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/PageRenderer/Util/Navigation.php