CamerataDB: MusicianService Class Reference
MusicianService Class Reference
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Public Member Functions
__construct (ConfigService $configService, EntityManager $entityManager, MailingListsService $listsService,)
ensureUserIdSlug (Entities\Musician $musician)
Ensure that the musicain indeed has a user-id-slug.
generateDisabledEmailAddress (Entities\Musician $musician, ?string $email=null)
As a last resort generate a "disabled" email address pointing back to the orchestra from the user-id and optionally an existing (broken) email address.
deleteMusician (Entities\Musician $musician)
Static Public Member Functions
static userIdSlugToFileName (string $userIdSlug)
Convert a user-id to a file-name-part avoiding "duplicate" extensions, i.e.
static getSlugPostfix (string $userIdSlug)
static slugifyFileName (string $base, string $userIdSlug, bool $ignoreExtension=false)
static isSlugifiedFileName (string $path, string $userIdSlug)
static unSlugifyFileName (string $path, string $userIdSlug, bool $keepExtension=true)
Data Fields
const DBTABLE = 'Musicians'
Private Attributes
$listsService
Detailed Description
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Definition at line 43 of file MusicianService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, EntityManager $entityManager, MailingListsService $listsService)
Definition at line 54 of file MusicianService.php.
Member Function Documentation
deleteMusician()
deleteMusician (Entities\Musician $musician)
Parameters
Entities\\Musician $musician
Returns
void
Definition at line 325 of file MusicianService.php.
ensureUserIdSlug()
ensureUserIdSlug (Entities\Musician $musician)
Ensure that the musicain indeed has a user-id-slug.
In principle this should never happen when the app runs in production mode ...
Parameters
Entities\\Musician $musician
Returns
string The user-id slug.
Definition at line 74 of file MusicianService.php.
generateDisabledEmailAddress()
generateDisabledEmailAddress (Entities\Musician $musician, ?string $email = null)
As a last resort generate a "disabled" email address pointing back to the orchestra from the user-id and optionally an existing (broken) email address.
Parameters
Entities\\Musician $musician
null | string $email
Returns
string
Definition at line 175 of file MusicianService.php.
getSlugPostfix()
static getSlugPostfix (string $userIdSlug) static
Parameters
string $userIdSlug
Returns
string
Definition at line 102 of file MusicianService.php.
References MusicianService\userIdSlugToFileName().
Referenced by MusicianService\slugifyFileName(), and MusicianService\unSlugifyFileName().
isSlugifiedFileName()
static isSlugifiedFileName (string $path, string $userIdSlug) static
Parameters
string $path
string $userIdSlug
Returns
bool
Definition at line 137 of file MusicianService.php.
slugifyFileName()
static slugifyFileName (string $base, string $userIdSlug, bool $ignoreExtension = false) static
Parameters
string $base
string $userIdSlug
bool $ignoreExtension
Returns
string
Definition at line 116 of file MusicianService.php.
References MusicianService\getSlugPostfix().
Referenced by ParticipantFieldCloudFolderListener\getOptionFromFileName(), and ProjectService\participantFilename().
unSlugifyFileName()
static unSlugifyFileName (string $path, string $userIdSlug, bool $keepExtension = true) static
Parameters
string $path
string $userIdSlug
bool $keepExtension
Returns
string
Definition at line 152 of file MusicianService.php.
References MusicianService\getSlugPostfix().
userIdSlugToFileName()
static userIdSlugToFileName (string $userIdSlug) static
Convert a user-id to a file-name-part avoiding "duplicate" extensions, i.e.
use ClausJustusHeine.pdf instead of claus-justus.heine.pdf
Parameters
string $userIdSlug
Returns
string
Definition at line 92 of file MusicianService.php.
Referenced by MusicianService\getSlugPostfix().
Field Documentation
$listsService
MailingListsService $listsService private
Definition at line 51 of file MusicianService.php.
DBTABLE
const DBTABLE = 'Musicians'
Definition at line 48 of file MusicianService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/MusicianService.php