CamerataDB: ProjectParticipantFieldEntityListener Class Reference
ProjectParticipantFieldEntityListener Class Reference
Perform infra-structure update on changes of a defined extra column in the instrumentation table.
Public Member Functions
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager,)
prePersist (Entities\ProjectParticipantField $entity, ORMEvent\PrePersistEventArgs $event)
{}
preRemove (Entities\ProjectParticipantField $entity, ORMEvent\PreRemoveEventArgs $event)
{}
preUpdate (Entities\ProjectParticipantField $entity, ORMEvent\PreUpdateEventArgs $event)
{}
Protected Attributes
$eventsService
Private Member Functions
getFieldsService ()
getTranslationChangeSet (Entities\ProjectParticipantField $entity, ORMEvent\PreUpdateEventArgs $event, string $field,)
Gedmo\Translatable hack-around: the actual change set sometimes has to be cleared.
Detailed Description
Perform infra-structure update on changes of a defined extra column in the instrumentation table.
Definition at line 43 of file ProjectParticipantFieldEntityListener.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager)
Definition at line 51 of file ProjectParticipantFieldEntityListener.php.
Member Function Documentation
getFieldsService()
getFieldsService () private
Returns
ProjectParticipantFieldsService
Definition at line 114 of file ProjectParticipantFieldEntityListener.php.
Referenced by ProjectParticipantFieldEntityListener\prePersist(), ProjectParticipantFieldEntityListener\preRemove(), and ProjectParticipantFieldEntityListener\preUpdate().
getTranslationChangeSet()
getTranslationChangeSet (Entities\ProjectParticipantField $entity, ORMEvent\PreUpdateEventArgs $event, string $field) private
Gedmo\Translatable hack-around: the actual change set sometimes has to be cleared.
The work around is to provide the translated changeset in an extra field which is populated on request by Gedmo\Translatable\TranslatableListener.
If the field is not present in the translation changeset, then fallback to the changes provided by the ORM event, so this function can also be used for non-translatable fields at the cost of a failing array lookup.
Parameters
Entities\\ProjectParticipantField $entity
ORMEvent\\PreUpdateEventArgs $event
string $field
Returns
null|array
Definition at line 138 of file ProjectParticipantFieldEntityListener.php.
Referenced by ProjectParticipantFieldEntityListener\preUpdate().
prePersist()
prePersist (Entities\ProjectParticipantField $entity, ORMEvent\PrePersistEventArgs $event)
{}
Definition at line 60 of file ProjectParticipantFieldEntityListener.php.
References ProjectParticipantFieldEntityListener\getFieldsService().
preRemove()
preRemove (Entities\ProjectParticipantField $entity, ORMEvent\PreRemoveEventArgs $event)
{}
Definition at line 71 of file ProjectParticipantFieldEntityListener.php.
References ProjectParticipantFieldEntityListener\getFieldsService().
preUpdate()
preUpdate (Entities\ProjectParticipantField $entity, ORMEvent\PreUpdateEventArgs $event)
{}
Definition at line 80 of file ProjectParticipantFieldEntityListener.php.
References ProjectParticipantFieldEntityListener\getFieldsService(), and ProjectParticipantFieldEntityListener\getTranslationChangeSet().
Field Documentation
$eventsService
EventsService $eventsService protected
Definition at line 48 of file ProjectParticipantFieldEntityListener.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Listener/ProjectParticipantFieldEntityListener.php