CamerataDB: PhoneNumberService Class Reference
PhoneNumberService Class Reference
Telephone number validation.
Public Member Functions
__construct (ConfigService $configService)
normalize (string $number)
Add the default area code if the number does not start with + or 0, and do some other normalization, strip spaces etc.
validate (string $number, ?string $region=null)
format (?string $number=null, ?string $region=null)
isMobile (?string $number=null, ?string $region=null)
metaData ($number=null, $region=null, string $newline="\n")
Return new-line formatted meta-data for the current or the given number and region.
Static Protected Member Functions
static translationHack ()
Inject some translations with a never called fake-function.
Private Member Functions
initializeDefaults ()
getBackend ()
getDefaultRegion ()
getDefaultPrefix ()
translateNumberType (int $type)
Lazy initializer for the number-type-to-locale conversion.
Private Attributes
$backend = false
$currentNumber = false
$currentObject = false
$currentRegion = false
$defaultPrefix = false
$defaultRegion = false
$numberTypes = false
Detailed Description
Telephone number validation.
Definition at line 35 of file PhoneNumberService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService)
Definition at line 50 of file PhoneNumberService.php.
Member Function Documentation
format()
format (?string $number = null, ?string $region = null)
Parameters
null | string $number
null | string $region
Returns
string
Definition at line 247 of file PhoneNumberService.php.
References PhoneNumberService\getBackend(), and PhoneNumberService\validate().
getBackend()
getBackend () private
Returns
PhoneNumberUtil
Definition at line 91 of file PhoneNumberService.php.
References PhoneNumberService\initializeDefaults().
Referenced by PhoneNumberService\format(), PhoneNumberService\isMobile(), PhoneNumberService\metaData(), and PhoneNumberService\validate().
getDefaultPrefix()
getDefaultPrefix () private
Returns
string
Definition at line 109 of file PhoneNumberService.php.
References PhoneNumberService\initializeDefaults().
Referenced by PhoneNumberService\normalize().
getDefaultRegion()
getDefaultRegion () private
Returns
string
Definition at line 100 of file PhoneNumberService.php.
References PhoneNumberService\initializeDefaults().
Referenced by PhoneNumberService\validate().
initializeDefaults()
initializeDefaults () private
Returns
void
Definition at line 58 of file PhoneNumberService.php.
Referenced by PhoneNumberService\getBackend(), PhoneNumberService\getDefaultPrefix(), and PhoneNumberService\getDefaultRegion().
isMobile()
isMobile (?string $number = null, ?string $region = null)
Parameters
null | string $number
null | string $region
Returns
bool
Definition at line 263 of file PhoneNumberService.php.
References PhoneNumberService\getBackend(), and PhoneNumberService\validate().
metaData()
metaData ($number = null, $region = null, string $newline = "\n")
Return new-line formatted meta-data for the current or the given number and region.
Parameters
string | null $number The number to parse.
string | null $region The region code if not included in the number.
string $newline The new-line delimiter.
Returns
string Empty string if the number cannot be validated, newline separated meta-data else.
Definition at line 285 of file PhoneNumberService.php.
References PhoneNumberService\getBackend(), PhoneNumberService\translateNumberType(), and PhoneNumberService\validate().
normalize()
normalize (string $number)
Add the default area code if the number does not start with + or 0, and do some other normalization, strip spaces etc.
Parameters
string $number
Returns
string
Definition at line 170 of file PhoneNumberService.php.
References PhoneNumberService\getDefaultPrefix().
Referenced by PhoneNumberService\validate().
translateNumberType()
translateNumberType (int $type) private
Lazy initializer for the number-type-to-locale conversion.
Parameters
int $type
Returns
string
Definition at line 124 of file PhoneNumberService.php.
Referenced by PhoneNumberService\metaData().
translationHack()
static translationHack () static protected
Inject some translations with a never called fake-function.
This has to be kept in sync with the constants of \libphonenumber\PhoneNumberType.
Returns
void
Definition at line 144 of file PhoneNumberService.php.
validate()
validate (string $number, ?string $region = null)
Parameters
string $number
null | string $region
Returns
bool
Definition at line 209 of file PhoneNumberService.php.
References PhoneNumberService\getBackend(), PhoneNumberService\getDefaultRegion(), and PhoneNumberService\normalize().
Referenced by PhoneNumberService\format(), PhoneNumberService\isMobile(), and PhoneNumberService\metaData().
Field Documentation
$backend
libphonenumber PhoneNumberUtil $backend = false private
Definition at line 41 of file PhoneNumberService.php.
$currentNumber
$currentNumber = false private
Definition at line 42 of file PhoneNumberService.php.
$currentObject
$currentObject = false private
Definition at line 43 of file PhoneNumberService.php.
$currentRegion
$currentRegion = false private
Definition at line 44 of file PhoneNumberService.php.
$defaultPrefix
$defaultPrefix = false private
Definition at line 45 of file PhoneNumberService.php.
$defaultRegion
$defaultRegion = false private
Definition at line 46 of file PhoneNumberService.php.
$numberTypes
$numberTypes = false private
Definition at line 47 of file PhoneNumberService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/PhoneNumberService.php