CamerataDB: ReadMeFactory Class Reference
ReadMeFactory Class Reference
Generate in-memory README nodes.
Public Member Functions
__construct (ContainerInterface $appContainer, IL10N $l, AppL10N $appL10n, protected string $appName, protected LoggerInterface $logger, protected IConfig $cloudConfig, protected ToolTipsService $toolTipsService,)
generateReadMe (DatabaseStorageFolder|EmptyDirectoryNode $parent, string $dirName)
isReadMe (string $path)
Check whether the given file is a ReadMe.md file.
getReadMeFileNames ()
Possibly populate and return the array of possible "readMe" variations.
Data Fields
const MIME_TYPE = 'text/plain'
Protected Member Functions
getReadMeTooltipsKey (string $storageId, string $dirName=null)
Compute a lookup key for a possible default readme content.
getDefaultReadMeContents (string $storageId, string $dirName=null)
Recurse to the tooltips service and see if there is a default text for the given storage.
Protected Attributes
array $readMeFileNames = null
A cache for possible names of the Readme.md.
Detailed Description
Generate in-memory README nodes.
Definition at line 44 of file ReadMeFactory.php.
Constructor & Destructor Documentation
__construct()
__construct (ContainerInterface $appContainer, IL10N $l, AppL10N $appL10n, protected string $appName, protected LoggerInterface $logger, protected IConfig $cloudConfig, protected ToolTipsService $toolTipsService)
Parameters
string $appName
LoggerInterface $logger
IConfig $cloudConfig
ContainerInterface $appContainer
ToolTipsService $toolTipsService
Definition at line 59 of file ReadMeFactory.php.
Member Function Documentation
generateReadMe()
generateReadMe (DatabaseStorageFolder|EmptyDirectoryNode $parent, string $dirName)
Parameters
DatabaseStorageFolder | EmptyDirectoryNode $parent
string $dirName
Returns
null|InMemoryFileNode
Implements ReadMeFactoryInterface.
Definition at line 78 of file ReadMeFactory.php.
References ReadMeFactory\getDefaultReadMeContents(), ReadMeFactoryInterface\getReadMeFileNames(), and EmptyDirectoryNode\getStorage().
getDefaultReadMeContents()
getDefaultReadMeContents (string $storageId, string $dirName = null) protected
Recurse to the tooltips service and see if there is a default text for the given storage.
Parameters
string $storageId
string $dirName
Returns
string
Definition at line 124 of file ReadMeFactory.php.
References ReadMeFactory\getReadMeTooltipsKey().
Referenced by ReadMeFactory\generateReadMe().
getReadMeFileNames()
getReadMeFileNames () inherited
Possibly populate and return the array of possible "readMe" variations.
We try to recurse to the "text" app and come up with suitable fallback if that fails.
Returns
array<int, string>
Referenced by ReadMeFactory\generateReadMe(), and AbstractReadMeFactory\isReadMe().
getReadMeTooltipsKey()
getReadMeTooltipsKey (string $storageId, string $dirName = null) protected
Compute a lookup key for a possible default readme content.
Parameters
string $storageId
string $dirName
Returns
string
Definition at line 103 of file ReadMeFactory.php.
Referenced by ReadMeFactory\getDefaultReadMeContents().
isReadMe()
isReadMe (string $path) inherited
Check whether the given file is a ReadMe.md file.
Parameters
string $path
Returns
bool
Implements ReadMeFactoryInterface.
Definition at line 102 of file AbstractReadMeFactory.php.
References AbstractReadMeFactory\$readMeFileNames, ReadMeFactoryInterface\getReadMeFileNames(), and StorageUtil\uploadBasename().
Field Documentation
$readMeFileNames
array $readMeFileNames = null protected inherited
A cache for possible names of the Readme.md.
The first element is the preferred localized name.
Definition at line 51 of file AbstractReadMeFactory.php.
Referenced by AbstractReadMeFactory\isReadMe().
MIME_TYPE
const MIME_TYPE = 'text/plain' inherited
Definition at line 43 of file AbstractReadMeFactory.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Storage/Database/ReadMeFactory.php