CamerataDB: MusicianCardBackend Class Reference
MusicianCardBackend Class Reference
Generate VCards from the musicians database.
Public Member Functions
__construct (ConfigService $configService, ContactsService $contactsService, EntityManager $entityManager,)
{}
getURI ()
{
Returns
string
}
getDisplayName ()
{
Returns
string
}
getCard (string $name)
{
Parameters
string $name
Returns
MusicianCard
Exceptions
\Sabre\DAV\Exception\NotFound}
searchCards (string $pattern, array $properties)
{
Parameters
string $pattern
array $properties
Returns
MusicianCard[]
}
getCards ()
{
Returns
MusicianCard[]
}
getUriFromUuid ($uuid)
{}
getLastModified (?string $uri=null)
{Get the time of the last modification for either the address-book or an individual entry.
Parameters
string | null $uri
Returns
int Seconds sinc 1970-0-0 of last modification.
}
Protected Member Functions
getUuidFromUri ($uri)
{}
entryToCard (Entities\Musician $musician, ?int $lastModified=null)
{}
Private Attributes
$musiciansRepository
$contactsService
Detailed Description
Generate VCards from the musicians database.
Definition at line 42 of file MusicianCardBackend.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ContactsService $contactsService, EntityManager $entityManager)
{}
Definition at line 54 of file MusicianCardBackend.php.
Member Function Documentation
entryToCard()
entryToCard (Entities\Musician $musician, ?int $lastModified = null) protected
{}
Definition at line 186 of file MusicianCardBackend.php.
References MusicianCardBackend\getUriFromUuid().
Referenced by MusicianCardBackend\getCard(), MusicianCardBackend\getCards(), and MusicianCardBackend\searchCards().
getCard()
getCard (string $name)
{
Parameters
string $name
Returns
MusicianCard
Exceptions
\Sabre\DAV\Exception\NotFound}
Exceptions
SabreNotFoundException
Implements ICardBackend.
Definition at line 89 of file MusicianCardBackend.php.
References MusicianCardBackend\entryToCard(), and MusicianCardBackend\getUuidFromUri().
getCards()
getCards ()
{
Returns
MusicianCard[]
}
Implements ICardBackend.
Definition at line 161 of file MusicianCardBackend.php.
References MusicianCardBackend\entryToCard().
getDisplayName()
getDisplayName ()
{
Returns
string
}
Implements ICardBackend.
Definition at line 75 of file MusicianCardBackend.php.
getLastModified()
getLastModified (?string $uri = null)
{Get the time of the last modification for either the address-book or an individual entry.
Parameters
string | null $uri
Returns
int Seconds sinc 1970-0-0 of last modification.
}
Implements ICardBackend.
Definition at line 199 of file MusicianCardBackend.php.
References MusicianCardBackend\getUuidFromUri().
getURI()
getURI ()
{
Returns
string
}
Implements ICardBackend.
Definition at line 69 of file MusicianCardBackend.php.
getUriFromUuid()
getUriFromUuid ($uuid)
{}
Definition at line 174 of file MusicianCardBackend.php.
Referenced by MusicianCardBackend\entryToCard().
getUuidFromUri()
getUuidFromUri ($uri) protected
{}
Definition at line 180 of file MusicianCardBackend.php.
Referenced by MusicianCardBackend\getCard(), and MusicianCardBackend\getLastModified().
searchCards()
searchCards (string $pattern, array $properties)
{
Parameters
string $pattern
array $properties
Returns
MusicianCard[]
}
Todo:
To support $searchProperties we would need the mapping from VCard properties to data-base properties.
Implements ICardBackend.
Definition at line 105 of file MusicianCardBackend.php.
References MusicianCardBackend\entryToCard().
Field Documentation
$contactsService
ContactsService $contactsService private
Definition at line 51 of file MusicianCardBackend.php.
$musiciansRepository
Repositories MusiciansRepository $musiciansRepository private
Definition at line 48 of file MusicianCardBackend.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/AddressBook/MusicianCardBackend.php