CamerataDB: InstrumentationService Class Reference
InstrumentationService Class Reference
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Public Member Functions
__construct (ConfigService $configService, ToolTipsService $toolTipsService, EntityManager $entityManager,)
tableTabId (string $idOrName)
defaultTableTabs (bool $useFinanceTab=false)
Export the default tabs family.
tableTabs (?array $participantFields=null, bool $useFinanceTab=false)
Export the description for the table tabs.
Protected Attributes
$entityManager
$toolTipsService
Detailed Description
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Definition at line 38 of file InstrumentationService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ToolTipsService $toolTipsService, EntityManager $entityManager)
Definition at line 50 of file InstrumentationService.php.
Member Function Documentation
defaultTableTabs()
defaultTableTabs (bool $useFinanceTab = false)
Export the default tabs family.
Parameters
bool $useFinanceTab
Returns
array
Todo:
This is almost nowhere used, but different to be joined other implementations exist.
Definition at line 166 of file InstrumentationService.php.
Referenced by InstrumentationService\tableTabId(), and InstrumentationService\tableTabs().
tableTabId()
tableTabId (string $idOrName)
Parameters
string $idOrName
Returns
string
Todo:
DetailedInstrumentationService? Maybe overkill
Definition at line 145 of file InstrumentationService.php.
References InstrumentationService\defaultTableTabs().
tableTabs()
tableTabs (?array $participantFields = null, bool $useFinanceTab = false)
Export the description for the table tabs.
Parameters
null | array $participantFields
bool $useFinanceTab
Returns
array
Definition at line 221 of file InstrumentationService.php.
References InstrumentationService\defaultTableTabs().
Field Documentation
$entityManager
EntityManager $entityManager protected
Definition at line 44 of file InstrumentationService.php.
$toolTipsService
ToolTipsService $toolTipsService protected
Definition at line 47 of file InstrumentationService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/InstrumentationService.php