CamerataDB: TaxExemptionNoticesRepository Class Reference
TaxExemptionNoticesRepository Class Reference
Database repository for CompositePayments entities.
Public Member Functions
getLatestValid (string|TaxType $taxType=TaxType::CORPORATE_INCOME, ?DateTimeInterface $dateOfUsage=null,)
Return the most recent valid tax exemption notice, or \null if no valid notice can be found.
getEntityManager ()
Public export of parent function.
Private Attributes
const ALIAS = 'ten'
Detailed Description
Database repository for CompositePayments entities.
Definition at line 34 of file TaxExemptionNoticesRepository.php.
Member Function Documentation
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), SepaBulkTransactionsRepository\isCalendarObjectUsed(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
getLatestValid()
getLatestValid (string|TaxType $taxType = TaxType::CORPORATE_INCOME, ?DateTimeInterface $dateOfUsage = null)
Return the most recent valid tax exemption notice, or \null if no valid notice can be found.
Valid means that the notice has been issued at or before $dateOfUsage und is still valid at $dateOfUsage. If there are more thatn 1 candidate notice, then the most recent is returned.
Parameters
string | TaxType $taxType Specify the tax-type, defaults to corporate income tax.
null | DateTimeInterface $dateOfUsage
Returns
null|Entity
Definition at line 53 of file TaxExemptionNoticesRepository.php.
Field Documentation
ALIAS
const ALIAS = 'ten' private
Definition at line 38 of file TaxExemptionNoticesRepository.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/TaxExemptionNoticesRepository.php