CamerataDB: FontService Class Reference
FontService Class Reference
Office font-file locator, in particular for PhpOffice.
Public Member Functions
__construct (string $appName, CloudConfig $cloudConfig, ILogger $logger, AppStorageDisclosure $appStorage,)
getFontsFolder ()
getFontsFolderName ()
getDefaultFontName ()
Return the chosen font-default if it is available and set, otherwise one of the installed fonts.
isFontAvailable (string $fontName)
Check whether the given font.
getFontFolderEntries ()
Obtain the cached contents of the font-folder, grouped by family.
scanFontsFolder ()
Scan the app's fonts folder and return the contents grouped by font family.
purgeFontsFolder ()
Delete all files in the app's font folder and clear all cache entries.
populateFontsFolder ()
Populate the true-type fonts folder with font-files from the system or from other sources (download?).
findOfficeFontFile (string $fontFileName, bool $useLocate=false)
Data Fields
const OFFICE_FONTS_FOLDER_CONFIG = 'officeFontsFolder'
const DEFAULT_OFFICE_FONT_CONFIG = 'defaultOfficeFont'
const FONT_FILE_NAMES = PhpSpreadsheet\Shared\Font::FONT_FILE_NAMES
const CARLITO = 'Carlito-Regular.ttf'
const CARLITO_BOLD = 'Carlito-Bold.ttf'
const CARLITO_ITALIC = 'Carlito-Italic.ttf'
const CARLITO_BOLD_ITALIC = 'Carlito-BoldItalic.ttf'
const FONT_STYLE_PLAIN = 'x'
const FONT_STYLE_BOLD = self::FONT_STYLE_PLAIN . 'b'
const FONT_STYLE_ITALIC = self::FONT_STYLE_PLAIN . 'i'
const FONT_STYLE_BOLD_ITALIC = self::FONT_STYLE_PLAIN . 'bi'
const FONT_STYLES
const FONT_ALIAS_NAMES
Protected Attributes
$appName
$cloudConfig
$appStorage
$fontsFolder
$fontsFolderLocalPath
$systemFontDataCache = []
Cache the found system font-files for this request.
$fontFolderEntries
Cache the contents of the app's font-data directory for this request.
$defaultFont
Private Attributes
const SYSTEM_FONT_DATA_DIR = '/usr/share/fonts/'
Detailed Description
Office font-file locator, in particular for PhpOffice.
Definition at line 43 of file FontService.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, CloudConfig $cloudConfig, ILogger $logger, AppStorageDisclosure $appStorage)
Definition at line 121 of file FontService.php.
Member Function Documentation
findOfficeFontFile()
findOfficeFontFile (string $fontFileName, bool $useLocate = false)
Parameters
string $fontFileName
bool $useLocate Use locate program to find font files in addition to searching in the default system font directory.
Returns
string The full path to the font file.
Definition at line 335 of file FontService.php.
References FontService\getFontsFolder(), and FontService\getFontsFolderName().
Referenced by FontService\populateFontsFolder().
getDefaultFontName()
getDefaultFontName ()
Return the chosen font-default if it is available and set, otherwise one of the installed fonts.
Returns
null|string
Definition at line 173 of file FontService.php.
References FontService\isFontAvailable().
getFontFolderEntries()
getFontFolderEntries ()
Obtain the cached contents of the font-folder, grouped by family.
Returns
array
Definition at line 226 of file FontService.php.
References FontService\$fontFolderEntries, and FontService\scanFontsFolder().
Referenced by FontService\isFontAvailable().
getFontsFolder()
getFontsFolder ()
Returns
string The name of the fonts-folder in the file-system.
Definition at line 135 of file FontService.php.
Referenced by FontService\findOfficeFontFile(), FontService\getFontsFolderName(), FontService\populateFontsFolder(), and FontService\purgeFontsFolder().
getFontsFolderName()
getFontsFolderName ()
Returns
string The name of the fonts-folder in the file-system.
Definition at line 144 of file FontService.php.
References FontService\getFontsFolder().
Referenced by FontService\findOfficeFontFile(), FontService\populateFontsFolder(), FontService\purgeFontsFolder(), and FontService\scanFontsFolder().
isFontAvailable()
isFontAvailable (string $fontName)
Check whether the given font.
Parameters
string $fontName A font name, like 'Arial'.
Returns
bool \true if the font is there, \false if not.
Definition at line 210 of file FontService.php.
References FontService\getFontFolderEntries().
Referenced by FontService\getDefaultFontName().
populateFontsFolder()
populateFontsFolder ()
Populate the true-type fonts folder with font-files from the system or from other sources (download?).
This is time-consuming and meant as action initiated by console commands or the admin settings page.
Returns
array Return the array of found font-files, grouped by family.
Definition at line 284 of file FontService.php.
References FontService\findOfficeFontFile(), FontService\getFontsFolder(), and FontService\getFontsFolderName().
purgeFontsFolder()
purgeFontsFolder ()
Delete all files in the app's font folder and clear all cache entries.
Returns
void
Definition at line 265 of file FontService.php.
References FontService\getFontsFolder(), and FontService\getFontsFolderName().
scanFontsFolder()
scanFontsFolder ()
Scan the app's fonts folder and return the contents grouped by font family.
Returns
array Return the array of found font-files, grouped by family.
Definition at line 240 of file FontService.php.
References FontService\$fontFolderEntries, and FontService\getFontsFolderName().
Referenced by FontService\getFontFolderEntries().
Field Documentation
$appName
string $appName protected
Definition at line 89 of file FontService.php.
$appStorage
AppStorageDisclosure $appStorage protected
Definition at line 95 of file FontService.php.
$cloudConfig
CloudConfig $cloudConfig protected
Definition at line 92 of file FontService.php.
$defaultFont
string $defaultFont protected
Definition at line 118 of file FontService.php.
$fontFolderEntries
array $fontFolderEntries protected
Cache the contents of the app's font-data directory for this request.
Definition at line 115 of file FontService.php.
Referenced by FontService\getFontFolderEntries(), and FontService\scanFontsFolder().
$fontsFolder
Folder $fontsFolder protected
Definition at line 98 of file FontService.php.
$fontsFolderLocalPath
string $fontsFolderLocalPath protected
Definition at line 101 of file FontService.php.
$systemFontDataCache
array $systemFontDataCache = [] protected
Cache the found system font-files for this request.
Definition at line 108 of file FontService.php.
CARLITO
const CARLITO = 'Carlito-Regular.ttf'
Definition at line 60 of file FontService.php.
CARLITO_BOLD
const CARLITO_BOLD = 'Carlito-Bold.ttf'
Definition at line 61 of file FontService.php.
CARLITO_BOLD_ITALIC
const CARLITO_BOLD_ITALIC = 'Carlito-BoldItalic.ttf'
Definition at line 63 of file FontService.php.
CARLITO_ITALIC
const CARLITO_ITALIC = 'Carlito-Italic.ttf'
Definition at line 62 of file FontService.php.
DEFAULT_OFFICE_FONT_CONFIG
const DEFAULT_OFFICE_FONT_CONFIG = 'defaultOfficeFont'
Definition at line 49 of file FontService.php.
FONT_ALIAS_NAMES
const FONT_ALIAS_NAMES
Initial value:
= [
    'Calibri' => [
      self::FONT_STYLE_PLAIN => self::CARLITO,
      self::FONT_STYLE_BOLD => self::CARLITO_BOLD,
      self::FONT_STYLE_ITALIC => self::CARLITO_ITALIC,
      self::FONT_STYLE_BOLD_ITALIC => self::CARLITO_BOLD_ITALIC,
    ],
  ]
Definition at line 77 of file FontService.php.
FONT_FILE_NAMES
const FONT_FILE_NAMES = PhpSpreadsheet\Shared\Font::FONT_FILE_NAMES
Definition at line 58 of file FontService.php.
FONT_STYLE_BOLD
const FONT_STYLE_BOLD = self::FONT_STYLE_PLAIN . 'b'
Definition at line 66 of file FontService.php.
FONT_STYLE_BOLD_ITALIC
const FONT_STYLE_BOLD_ITALIC = self::FONT_STYLE_PLAIN . 'bi'
Definition at line 68 of file FontService.php.
FONT_STYLE_ITALIC
const FONT_STYLE_ITALIC = self::FONT_STYLE_PLAIN . 'i'
Definition at line 67 of file FontService.php.
FONT_STYLE_PLAIN
const FONT_STYLE_PLAIN = 'x'
Definition at line 65 of file FontService.php.
FONT_STYLES
const FONT_STYLES
Initial value:
= [
    self::FONT_STYLE_PLAIN,
    self::FONT_STYLE_BOLD,
    self::FONT_STYLE_ITALIC,
    self::FONT_STYLE_BOLD_ITALIC,
  ]
Definition at line 70 of file FontService.php.
OFFICE_FONTS_FOLDER_CONFIG
const OFFICE_FONTS_FOLDER_CONFIG = 'officeFontsFolder'
Definition at line 47 of file FontService.php.
SYSTEM_FONT_DATA_DIR
const SYSTEM_FONT_DATA_DIR = '/usr/share/fonts/' private
Definition at line 86 of file FontService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/FontService.php