CamerataDB: VCalendarService Class Reference
VCalendarService Class Reference
Operation/Builder for VCalendar objects.
Public Member Functions
__construct (ConfigService $configService, OC_Calendar_Object $legacyCalendarObject,)
{}
validateRequest (mixed $eventData, string $kind=self::VEVENT)
Validate the given request-data which is an associative array.
createVCalendarFromRequest (mixed $vObjectData, string $kind=self::VEVENT)
addParticipants (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple participans to the given VTodo or VEvent.
addRelations (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple relations to the given VTodo or VEvent.
addVAlarmsFromRequest (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple alarms to the given VTodo or VEvent.
updateVCalendarFromRequest (VCalendar $vCalendar, mixed $objectData, string $kind=self::VEVENT)
legacyEventObject ()
Static Public Member Functions
static getVCalendar (mixed $stuff)
static getAllVObjects (VCalendar $vCalendar, string $type=self::VEVENT)
Get all components of a given type from a VCalendar object and return them as flat array.
static getVObject (VCalendar $vCalendar)
Return the "master" wrapped object, where the VCalendar object here is rather not an entire calendar, but one item from the database.
static getVObjectType (VCalendar $vCalendar)
Return the type of the respective calendar object.
static isEventRecurring (VComponent $vComponent)
Determine if the given event is recurring or not.
static getCategories (VComponent $vComponent)
Return the category list for the given object.
static setCategories (VComponent $vComponent, array $categories)
static getUid (VComponent $vComponent)
static setUid (VComponent $vComponent, string $uid)
static getSummary (VComponent $vComponent)
static setSummary (VComponent $vComponent, ?string $summary)
static getDescription (VComponent $vComponent)
static setDescription (VComponent $vComponent, ?string $description)
static getDTEnd (VComponent $vObject)
Data Fields
const VTODO = VCalendarType::VTODO
const VEVENT = VCalendarType::VEVENT
const VCARD = VCalendarType::VCARD
const VJOURNAL = VCalendarType::VJOURNAL
const ALARM_ACTION_DISPLAY = 'DISPLAY'
const ALARM_ACTION_AUDIO = 'AUDIO'
const ALARM_ACTION_EMAIL = 'EMAIL'
const ALARM_ACTION_PROCEDURE = 'PROCEDURE'
const VALARM_FROM_START = 'START'
const VALARM_FROM_END = 'END'
const VTODO_STATUS_IN_PROCESS = 'IN-PROCESS'
const VTODO_STATUS_COMPLETED = 'COMPLETED'
const VTODO_STATUS_NEEDS_ACTION = 'NEEDS-ACTION'
Private Member Functions
createVEventFromRequest (mixed $objectData)
updateVEventFromRequest (VCalendar $vCalendar, mixed $objectData)
validateVTodoRequest (array $todoData)
Validate the given request-data which is an associative array.
createVTodoFromRequest (array $todoData)
updateVTodoFromRequest (VCalendar $vCalendar, array $request)
Update task from request.
createVAlarmFromSeconds (VCalendar $vCalendar, int $seconds, ?string $related=null, ?string $description=null, string $action=self::ALARM_ACTION_DISPLAY,)
Private Attributes
$legacyCalendarObject
Detailed Description
Operation/Builder for VCalendar objects.
Definition at line 47 of file VCalendarService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, OC_Calendar_Object $legacyCalendarObject)
{}
Definition at line 72 of file VCalendarService.php.
Member Function Documentation
addParticipants()
addParticipants (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple participans to the given VTodo or VEvent.
Parameters
VCalendar $vRoot Root document of the $vComponent.
VComponent $vComponent A VTodo ar a VEvent.
mixed $objectData
[ ...
  'participants' => [
    'organizer' => [ 'name' => NAME, 'email' => EMAIL ],
    'attendees' => [
      [
        'name' => NAME,
        'email' => EMAIL,
        'role' => 'PARTICIPANT',
        'partstat' => 'NEEDS-ACTION',
        'language' => ...
      ], ...
    ],
  ], ...
]
Returns
void
Definition at line 206 of file VCalendarService.php.
Referenced by VCalendarService\createVEventFromRequest().
addRelations()
addRelations (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple relations to the given VTodo or VEvent.
Parameters
VCalendar $vRoot Root document of the $vComponent.
VComponent $vComponent A VTodo ar a VEvent.
mixed $objectData
[ ..., 'related' => [ UIDs, ... ], ... ]
[ ...,
  'related' => [
    'SIBLING' => [ UIDs, ... ],
    'CHILD' => [ UIDs, ... ],
    'PARENT' => [ UIDs, ... ],
  ], ...
]
Returns
void
Definition at line 254 of file VCalendarService.php.
Referenced by VCalendarService\createVEventFromRequest().
addVAlarmsFromRequest()
addVAlarmsFromRequest (VCalendar $vRoot, VComponent $vComponent, mixed $objectData)
Add one or multiple alarms to the given VTodo or VEvent.
Any existing alarms will be removed.
Parameters
VCalendar $vRoot Root document of the $vComponent.
VComponent $vComponent A VTodo ar a VEvent.
mixed $objectData Calendar object description from HTTP request. If it has an array element with key 'alarm' then this may be the number of alarm seconds or an array of seconds in which case multiple alarms will be added. Negative values are counted relative to the end of the event and reach to the feature (<- is that true?).
Returns
void
Definition at line 296 of file VCalendarService.php.
Referenced by VCalendarService\createVEventFromRequest().
createVAlarmFromSeconds()
createVAlarmFromSeconds (VCalendar $vCalendar, int $seconds, ?string $related = null, ?string $description = null, string $action = self::ALARM_ACTION_DISPLAY) private
Parameters
VCalendar $vCalendar CalDAV root document.
int $seconds Alarm seconds.
null | string $related Either START or END, if null negative seconds count from the end, positive from the start.
null | string $description Alarm description.
string $action What to do with the alarm.
Returns
null|VAlarm
Definition at line 844 of file VCalendarService.php.
createVCalendarFromRequest()
createVCalendarFromRequest (mixed $vObjectData, string $kind = self::VEVENT)
Parameters
mixed $vObjectData HTTP request submitted event data.
string $kind What kind of object to create. ``` $eventData = [ 'title' => 'Title', 'description' => 'Text', 'location' => 'Where', 'categories' => 'Cat1,Cat2', 'priority' => true, 'from' => '01-11-2020', 'fromtime' => '10:20:22', 'to' => '30-11-2020', 'totime' => '00:00:00', 'calendar' => 'calendarId', 'repeat' => 'doesnotrepeat', 'alarm' => [ [ 'START => -3600 ], [ 'END' => 1800 ], ] 'participants' => [ 'organizer' => [ 'name' => NAME, 'email' => EMAIL ], 'attendees' => [ [ 'name' => NAME, 'email' => EMAIL, 'role' => 'PARTICIPANT', 'partstat' => 'NEEDS-ACTION', 'language' => ... ], ... ] ];
$taskData = [ 'summary' => $title, // required 'related' => other VComponent's UID // optional 'due' => date('d-m-Y', $timeStamp), // required 'status' => 'TASK_NEEDS_ACTION ', // e.g. 'start' => date('d-m-Y'), // optional 'location' => 'Cyber-Space', // optional 'categories' => $categories, // optional 'description' => $description, // optional 'calendar' => $calendarId, // required 'allday' => true, // optional 'alarm' => $alarm, ]; // optional ```.
Returns
null|VCalendar
Definition at line 149 of file VCalendarService.php.
References VCalendarService\createVEventFromRequest(), and VCalendarService\createVTodoFromRequest().
createVEventFromRequest()
createVEventFromRequest (mixed $objectData) private
Parameters
mixed $objectData Calendar object description from HTTP request.
Returns
null|VCalendar
Definition at line 166 of file VCalendarService.php.
References VCalendarService\addParticipants(), VCalendarService\addRelations(), and VCalendarService\addVAlarmsFromRequest().
Referenced by VCalendarService\createVCalendarFromRequest().
createVTodoFromRequest()
createVTodoFromRequest (array $todoData) private
Parameters
array $todoData Calendar object description from HTTP request. ``` $taskData = [ 'summary' => $title, // required 'related' => other VComponent's UID // optional 'due' => date('d-m-Y', $timeStamp), // required 'status' => 'TASK_NEEDS_ACTION ', // e.g. 'start' => date('d-m-Y'), // optional 'location' => 'Cyber-Space', // optional 'categories' => $categories, // optional 'description' => $description, // optional 'calendar' => $calendarId, // required 'allday' => true, // optional 'alarm' => $alarm, ]; // optional ```.
Returns
VCalendar|null
Definition at line 719 of file VCalendarService.php.
Referenced by VCalendarService\createVCalendarFromRequest().
getAllVObjects()
static getAllVObjects (VCalendar $vCalendar, string $type = self::VEVENT) static
Get all components of a given type from a VCalendar object and return them as flat array.
Parameters
VCalendar $vCalendar VCalendar object.
string $type Defaults to 'VEVENT'
Returns
array
Definition at line 404 of file VCalendarService.php.
getCategories()
static getCategories (VComponent $vComponent) static
Return the category list for the given object.
Parameters
VComponent $vComponent Sabre VCalendar or VEvent object.
Returns
An array with the categories for the object.
Definition at line 504 of file VCalendarService.php.
getDescription()
static getDescription (VComponent $vComponent) static
Parameters
VComponent $vComponent Sabre calendar object.
Returns
null|string The summary comment of $vCalendar.
Definition at line 614 of file VCalendarService.php.
getDTEnd()
static getDTEnd (VComponent $vObject) static
Parameters
VComponent $vObject VEvent or anything else with DTEND or DTSTART
DURATION.
Returns
mixed DTEND property if set, otherwise DTSTART + duration.
Definition at line 653 of file VCalendarService.php.
getSummary()
static getSummary (VComponent $vComponent) static
Parameters
VComponent $vComponent Sabre calendar object.
Returns
null|string The summary comment of $vCalendar.
Definition at line 577 of file VCalendarService.php.
getUid()
static getUid (VComponent $vComponent) static
Parameters
VComponent $vComponent Sabre VCalendar or VEvent object.
Returns
null|string The UID of $vCalendar.
Definition at line 540 of file VCalendarService.php.
getVCalendar()
static getVCalendar (mixed $stuff) static
Parameters
mixed $stuff String or array or an VCalendar object.
Returns
VCalendar
Definition at line 375 of file VCalendarService.php.
getVObject()
static getVObject (VCalendar $vCalendar) static
Return the "master" wrapped object, where the VCalendar object here is rather not an entire calendar, but one item from the database.
Still it may contain more than one Component, e.g. for recurring events. In this case the "master" item is returned.
Parameters
VCalendar $vCalendar VCalendar object.
Returns
The inner object, or one of the inner objects.
Definition at line 431 of file VCalendarService.php.
getVObjectType()
static getVObjectType (VCalendar $vCalendar) static
Return the type of the respective calendar object.
Parameters
VCalendar $vCalendar Sabre DAV calendar object.
Returns
string Either VEVENT, VTODO, VJOURNAL or VCARD.
Definition at line 463 of file VCalendarService.php.
isEventRecurring()
static isEventRecurring (VComponent $vComponent) static
Determine if the given event is recurring or not.
Parameters
VComponent $vComponent Sabre VCalendar or VEvent object.
Returns
bool
Definition at line 486 of file VCalendarService.php.
legacyEventObject()
legacyEventObject ()
Returns
OC_Calendar_Object The old Owncloud inherited calendar object.
Todo:
Get rid of it.
Definition at line 365 of file VCalendarService.php.
setCategories()
static setCategories (VComponent $vComponent, array $categories) static
Parameters
VComponent $vComponent Sabre VCalendar or VEvent object.
array $categories Array of strings.
Returns
VComponent Pass through of $vComponent.
Definition at line 522 of file VCalendarService.php.
setDescription()
static setDescription (VComponent $vComponent, ?string $description) static
Parameters
VComponent $vComponent Object reference.
null | string $description The description to set.
Returns
VComponent Pass through of $vComponent.
Definition at line 633 of file VCalendarService.php.
setSummary()
static setSummary (VComponent $vComponent, ?string $summary) static
Parameters
VComponent $vComponent Object reference.
null | string $summary The summary to set.
Returns
VComponent Pass through of $vComponent.
Definition at line 596 of file VCalendarService.php.
setUid()
static setUid (VComponent $vComponent, string $uid) static
Parameters
VComponent $vComponent Sabre VCalendar or VEvent object.
string $uid The uid to set.
Returns
VCalendar Pass through of $vCalendar.
Definition at line 559 of file VCalendarService.php.
updateVCalendarFromRequest()
updateVCalendarFromRequest (VCalendar $vCalendar, mixed $objectData, string $kind = self::VEVENT)
Parameters
VCalendar $vCalendar Sabre calendar object.
mixed $objectData Calendar object description from HTTP request.
string $kind What kind of object to create.
Returns
null|VCalendar
Definition at line 328 of file VCalendarService.php.
updateVEventFromRequest()
updateVEventFromRequest (VCalendar $vCalendar, mixed $objectData) private
Parameters
VCalendar $vCalendar
mixed $objectData Calendar object description from HTTP request.
Returns
null|VCalendar
Definition at line 347 of file VCalendarService.php.
updateVTodoFromRequest()
updateVTodoFromRequest (VCalendar $vCalendar, array $request) private
Update task from request.
Parameters
VCalendar $vCalendar Sabre calendar object.
array $request HTTP request data. ``` $taskData = [ 'summary' => $title, // required 'related' => other VComponent's UID // optional 'due' => date('d-m-Y', $timeStamp), // required 'status' => 'TASK_NEEDS_ACTION ', // e.g. 'start' => date('d-m-Y'), // optional 'location' => 'Cyber-Space', // optional 'categories' => $categories, // optional 'description' => $description, // optional 'calendar' => $calendarId, // required 'allday' => true, // optional 'alarm' => $alarm, ]; // optional ```.
Returns
VCalendar|null
Definition at line 764 of file VCalendarService.php.
validateRequest()
validateRequest (mixed $eventData, string $kind = self::VEVENT)
Validate the given request-data which is an associative array.
Parameters
mixed $eventData Legacy request event data.
string $kind What kind of event to create.
Returns
array|false Array of error messages or false on success
Definition at line 89 of file VCalendarService.php.
References VCalendarService\validateVTodoRequest().
validateVTodoRequest()
validateVTodoRequest (array $todoData) private
Validate the given request-data which is an associative array.
Parameters
array $todoData Legacy request event data.
Returns
array|false Array of error messages or false on success
Definition at line 683 of file VCalendarService.php.
Referenced by VCalendarService\validateRequest().
Field Documentation
$legacyCalendarObject
OC_Calendar_Object $legacyCalendarObject private
Definition at line 52 of file VCalendarService.php.
ALARM_ACTION_AUDIO
const ALARM_ACTION_AUDIO = 'AUDIO'
Definition at line 60 of file VCalendarService.php.
ALARM_ACTION_DISPLAY
const ALARM_ACTION_DISPLAY = 'DISPLAY'
Definition at line 59 of file VCalendarService.php.
ALARM_ACTION_EMAIL
const ALARM_ACTION_EMAIL = 'EMAIL'
Definition at line 61 of file VCalendarService.php.
ALARM_ACTION_PROCEDURE
const ALARM_ACTION_PROCEDURE = 'PROCEDURE'
Definition at line 62 of file VCalendarService.php.
VALARM_FROM_END
const VALARM_FROM_END = 'END'
Definition at line 65 of file VCalendarService.php.
VALARM_FROM_START
const VALARM_FROM_START = 'START'
Definition at line 64 of file VCalendarService.php.
VCARD
const VCARD = VCalendarType::VCARD
Definition at line 56 of file VCalendarService.php.
VEVENT
const VEVENT = VCalendarType::VEVENT
Definition at line 55 of file VCalendarService.php.
VJOURNAL
const VJOURNAL = VCalendarType::VJOURNAL
Definition at line 57 of file VCalendarService.php.
VTODO
const VTODO = VCalendarType::VTODO
Definition at line 54 of file VCalendarService.php.
VTODO_STATUS_COMPLETED
const VTODO_STATUS_COMPLETED = 'COMPLETED'
Definition at line 68 of file VCalendarService.php.
VTODO_STATUS_IN_PROCESS
const VTODO_STATUS_IN_PROCESS = 'IN-PROCESS'
Definition at line 67 of file VCalendarService.php.
VTODO_STATUS_NEEDS_ACTION
const VTODO_STATUS_NEEDS_ACTION = 'NEEDS-ACTION'
Definition at line 69 of file VCalendarService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/VCalendarService.php