CamerataDB: ProgressStatusController Class Reference
ProgressStatusController Class Reference
AJAX end-point for progress status.
Public Member Functions
__construct (?string $appName, IRequest $request, ProgressStatusService $progressStatusService, ?string $userId, ILogger $logger, IL10N $l10n,)
get (string $id)
action (string $operation)
Static Private Member Functions
static progressResponse (IProgressStatus $progress)
Private Attributes
$progressStatusService
$userId
$l
$logger
Detailed Description
AJAX end-point for progress status.
Definition at line 41 of file ProgressStatusController.php.
Constructor & Destructor Documentation
__construct()
__construct (?string $appName, IRequest $request, ProgressStatusService $progressStatusService, ?string $userId, ILogger $logger, IL10N $l10n)
Definition at line 58 of file ProgressStatusController.php.
Member Function Documentation
action()
action (string $operation)
Parameters
string $operation
Returns
Http\Response
@NoAdminRequired
Definition at line 103 of file ProgressStatusController.php.
References ProgressStatusController\progressResponse().
get()
get (string $id)
Parameters
string $id
Returns
Http\Response
@NoAdminRequired
Definition at line 82 of file ProgressStatusController.php.
References ProgressStatusController\progressResponse().
progressResponse()
static progressResponse (IProgressStatus $progress) static private
Parameters
IProgressStatus $progress
Returns
DataResponse
Definition at line 170 of file ProgressStatusController.php.
References IProgressStatus\getCurrent(), IProgressStatus\getData(), IProgressStatus\getId(), and IProgressStatus\getTarget().
Referenced by ProgressStatusController\action(), and ProgressStatusController\get().
Field Documentation
$l
IL10N $l private
Definition at line 52 of file ProgressStatusController.php.
$logger
ILogger $logger private
Definition at line 55 of file ProgressStatusController.php.
$progressStatusService
ProgressStatusService $progressStatusService private
Definition at line 46 of file ProgressStatusController.php.
$userId
string $userId private
Definition at line 49 of file ProgressStatusController.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Controller/ProgressStatusController.php