CamerataDB: BankTransactionsStorage Class Reference
BankTransactionsStorage Class Reference
Storage implementation for data-base storage, including access to encrypted entities.
Public Member Functions
addDocument (Entities\SepaBulkTransaction $transaction, Entities\EncryptedFile $file, bool $flush=true,)
Add a new document to the storage.
removeDocument (Entities\SepaBulkTransaction $transaction, Entities\EncryptedFile $file, bool $flush=true,)
Remove a document from the storage.
getShortId ()
{
Returns
string The shot storage id without the base prefix.
}
getId ()
{}
fileFromFileName (string $name)
Fetch the file entity corresponding to file-name.
isReadable ($path)
{}
isUpdatable ($path)
{}
isSharable ($path)
{}
filemtime ($path)
{}
hasUpdated ($path, $time)
{}
filesize ($path)
{}
rmdir ($path)
{}
test ()
{}
stat ($path)
{}
file_exists ($path)
{}
unlink ($path)
{}
opendir ($path)
{}
mkdir ($path)
{}
is_dir ($path)
{}
is_file ($path)
{}
filetype ($path)
{}
fopen ($path, $mode)
{}
touch ($path, $mtime=null)
{}
rename ($path1, $path2)
{}
Static Public Member Functions
static checkDependencies ()
{}
Data Fields
const PATH_SEPARATOR = Constants::PATH_SEP
Protected Member Functions
findFiles (string $dirName, bool $ignored=false)
{}
getStorageModificationDateTime ()
{Return the overall modification time of the entire storage.
Returns
null|DateTimeInterface
}
getReadMeFactory ()
Extension point for sub-classes in order to provide their own ReadMe factory.
persistInMemoryFileNode (InMemoryFileNode $memoryNode, ?Entities\Musician $owner=null)
Persist an InMemoryFileNode to the database, kind of copy-on-write operation.
unsetFileNameCache (string $name)
Remove a "cache" entry.
setFileNameCache (string $name, Entities\DatabaseStorageDirEntry $node)
Insert a "cache" entry.
getDirectoryModificationTime (string $dirName)
getStorageModificationTime ()
Get the overall modification time of the entire storage as Unix time-stamp.
buildPath (?string $path)
Static Protected Member Functions
static normalizeDirectoryName (string $dirName)
Attach self::PATH_SEPARATOR to the dirname if it is not the root directory.
static pathInfo (string $path, int $flags=PATHINFO_ALL)
Slightly modified pathinfo() function which also normalized directories before computing the components.
Protected Attributes
$filesRepository
$files = []
$storageEntity = null
$rootFolder = null
ReadMeFactory $readMeFactory
Private Attributes
$transactionsRepository
Detailed Description
Storage implementation for data-base storage, including access to encrypted entities.
Definition at line 49 of file BankTransactionsStorage.php.
Member Function Documentation
addDocument()
addDocument (Entities\SepaBulkTransaction $transaction, Entities\EncryptedFile $file, bool $flush = true)
Add a new document to the storage.
Parameters
Entities\\SepaBulkTransaction $transaction
Entities\\EncryptedFile $file
bool $flush Whether to flush the changes to the db.
Returns
Entities\DatabaseStorageFile
Definition at line 114 of file BankTransactionsStorage.php.
buildPath()
buildPath (?string $path) protected inherited
Parameters
null | string $path The path to work on.
Returns
string
Definition at line 402 of file Storage.php.
Referenced by Storage\fileFromFileName(), Storage\setFileNameCache(), and Storage\unsetFileNameCache().
checkDependencies()
static checkDependencies () static inherited
{}
Definition at line 445 of file Storage.php.
file_exists()
file_exists ($path) inherited
{}
Definition at line 584 of file Storage.php.
References Storage\fileFromFileName(), and Storage\is_dir().
Referenced by Storage\fopen(), Storage\isReadable(), and ProjectBalanceSupportingDocumentsStorage\isUpdatable().
fileFromFileName()
fileFromFileName (string $name) inherited
Fetch the file entity corresponding to file-name.
If the entry is a directory, return the directory name.
Parameters
string $name The path-name to work on.
Returns
null|Entities\DatabaseStorageDirEntry|EmptyDirectoryNode
Definition at line 458 of file Storage.php.
References Storage\buildPath(), and Storage\pathInfo().
Referenced by Storage\file_exists(), Storage\filemtime(), Storage\filesize(), Storage\getDirectoryModificationTime(), ProjectBalanceSupportingDocumentsStorage\getRootFolder(), Storage\is_dir(), Storage\stat(), and Storage\unlink().
filemtime()
filemtime ($path) inherited
{}
Definition at line 503 of file Storage.php.
References Storage\fileFromFileName(), Storage\getDirectoryModificationTime(), Storage\getStorageModificationTime(), and Storage\is_dir().
Referenced by Storage\hasUpdated().
filesize()
filesize ($path) inherited
{}
Definition at line 540 of file Storage.php.
References Storage\fileFromFileName(), and Storage\is_dir().
Referenced by Storage\is_file().
filetype()
filetype ($path) inherited
{}
Definition at line 655 of file Storage.php.
References Storage\is_dir(), and Storage\is_file().
findFiles()
findFiles (string $dirName, bool $ignored = false) protected
{}
Definition at line 219 of file BankTransactionsStorage.php.
fopen()
fopen ($path, $mode) inherited
{}
Definition at line 667 of file Storage.php.
References Storage\file_exists(), Storage\fopen(), Storage\isUpdatable(), Storage\touch(), and Storage\unlink().
Referenced by Storage\fopen().
getDirectoryModificationTime()
getDirectoryModificationTime (string $dirName) protected inherited
Parameters
string $dirName The directory to work on.
Returns
DateTimeInterface
Definition at line 351 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\filemtime().
getId()
getId () inherited
{}
Definition at line 386 of file Storage.php.
References Storage\getShortId().
Referenced by Factory\getProjectParticipantsStorage().
getReadMeFactory()
getReadMeFactory () protected inherited
Extension point for sub-classes in order to provide their own ReadMe factory.
Returns
ReadMeFactoryInterface
Definition at line 238 of file Storage.php.
getShortId()
getShortId ()
{
Returns
string The shot storage id without the base prefix.
}
Reimplemented from Storage.
Definition at line 231 of file BankTransactionsStorage.php.
getStorageModificationDateTime()
getStorageModificationDateTime () protected
{Return the overall modification time of the entire storage.
Returns
null|DateTimeInterface
}
Reimplemented from Storage.
Definition at line 225 of file BankTransactionsStorage.php.
getStorageModificationTime()
getStorageModificationTime () protected inherited
Get the overall modification time of the entire storage as Unix time-stamp.
Returns
int
Definition at line 380 of file Storage.php.
References Storage\getStorageModificationDateTime().
Referenced by Storage\filemtime().
hasUpdated()
hasUpdated ($path, $time) inherited
{}
Parameters
string $path Directory-entry to check.
int $time The value of storage_mtime from the row of the filescache table for $path.
This function controls cache invalidation. We return \true if either the file is still there and its mtime is larger then the supplied storage_mtime of the $time argument, or if the file has vanished in which case it should be removed from the filescache table.
Definition at line 533 of file Storage.php.
References Storage\filemtime().
is_dir()
is_dir ($path) inherited
{}
Definition at line 633 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\file_exists(), Storage\filemtime(), Storage\filesize(), Storage\filetype(), and Storage\opendir().
is_file()
is_file ($path) inherited
{}
Definition at line 649 of file Storage.php.
References Storage\filesize().
Referenced by Storage\filetype().
isReadable()
isReadable ($path) inherited
{}
Definition at line 480 of file Storage.php.
References Storage\file_exists().
isSharable()
isSharable ($path) inherited
{}
Definition at line 495 of file Storage.php.
isUpdatable()
isUpdatable ($path) inherited
{}
Reimplemented in ProjectBalanceSupportingDocumentsStorage, and TaxExemptionNoticesStorage.
Definition at line 488 of file Storage.php.
Referenced by Storage\fopen().
mkdir()
mkdir ($path) inherited
{}
Definition at line 627 of file Storage.php.
normalizeDirectoryName()
static normalizeDirectoryName (string $dirName) static protected inherited
Attach self::PATH_SEPARATOR to the dirname if it is not the root directory.
Parameters
string $dirName The directory name to work on.
Returns
string
Definition at line 414 of file Storage.php.
Referenced by Storage\pathInfo().
opendir()
opendir ($path) inherited
{}
Definition at line 615 of file Storage.php.
References Storage\is_dir().
pathInfo()
static pathInfo (string $path, int $flags = PATHINFO_ALL) static protected inherited
Slightly modified pathinfo() function which also normalized directories before computing the components.
Parameters
string $path The path to work on.
int $flags As for the upstream pathinfo() function.
Returns
string|array
Definition at line 433 of file Storage.php.
References Storage\normalizeDirectoryName().
Referenced by Storage\fileFromFileName(), Storage\setFileNameCache(), and Storage\unsetFileNameCache().
persistInMemoryFileNode()
persistInMemoryFileNode (InMemoryFileNode $memoryNode, ?Entities\Musician $owner = null) protected inherited
Persist an InMemoryFileNode to the database, kind of copy-on-write operation.
Parameters
InMemoryFileNode $memoryNode
null | Entities\\Musician $owner
Returns
Entities\DatabaseStorageFile
Reimplemented in ProjectParticipantsStorage.
Definition at line 252 of file Storage.php.
References InMemoryFileNode\getFileData(), InMemoryFileNode\getMimeType(), InMemoryFileNode\getName(), InMemoryFileNode\getParent(), InMemoryFileNode\getUpdated(), and InMemoryFileNode\setParent().
removeDocument()
removeDocument (Entities\SepaBulkTransaction $transaction, Entities\EncryptedFile $file, bool $flush = true)
Remove a document from the storage.
Note that this does not remove the file from the transaction entity.
Parameters
Entities\\SepaBulkTransaction $transaction
Entities\\EncryptedFile $file
bool $flush Whether to actually flush the operations to th db.
Returns
void
Definition at line 172 of file BankTransactionsStorage.php.
rename()
rename ($path1, $path2) inherited
{}
Definition at line 803 of file Storage.php.
rmdir()
rmdir ($path) inherited
{}
Definition at line 553 of file Storage.php.
setFileNameCache()
setFileNameCache (string $name, Entities\DatabaseStorageDirEntry $node) protected inherited
Insert a "cache" entry.
Parameters
string $name Path-name.
Entities\\DatabaseStorageDirEntry $node File-system node.
Returns
void
Definition at line 333 of file Storage.php.
References Storage\buildPath(), and Storage\pathInfo().
stat()
stat ($path) inherited
{}
Definition at line 571 of file Storage.php.
References Storage\fileFromFileName().
test()
test () inherited
{}
Definition at line 559 of file Storage.php.
touch()
touch ($path, $mtime = null) inherited
{}
Definition at line 797 of file Storage.php.
Referenced by Storage\fopen().
unlink()
unlink ($path) inherited
{}
Definition at line 602 of file Storage.php.
References Storage\fileFromFileName().
Referenced by Storage\fopen().
unsetFileNameCache()
unsetFileNameCache (string $name) protected inherited
Remove a "cache" entry.
Parameters
string $name Path-name.
Returns
void
Definition at line 307 of file Storage.php.
References Storage\buildPath(), and Storage\pathInfo().
Field Documentation
$files
array $files = [] protected inherited
Definition at line 78 of file Storage.php.
$filesRepository
OCA CAFEVDB Wrapped Doctrine ORM EntityRepository $filesRepository protected inherited
Definition at line 75 of file Storage.php.
$readMeFactory
ReadMeFactory $readMeFactory protected inherited
Definition at line 87 of file Storage.php.
$rootFolder
null Entities DatabaseStorageFolder $rootFolder = null protected inherited
Definition at line 84 of file Storage.php.
$storageEntity
null Entities DatabaseStorage $storageEntity = null protected inherited
Definition at line 81 of file Storage.php.
$transactionsRepository
OCA CAFEVDB Database Doctrine ORM Repositories SepaBulkTransactionsRepository $transactionsRepository private
Definition at line 54 of file BankTransactionsStorage.php.
PATH_SEPARATOR
const PATH_SEPARATOR = Constants::PATH_SEP inherited
Definition at line 72 of file Storage.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Storage/Database/BankTransactionsStorage.php