CamerataDB: MusicianEmailAddress Class Reference
MusicianEmailAddress Class Reference
InstrumentInsurance.
Public Member Functions
__construct (string $address=null, Musician $musician=null)
getAddress ()
__toString ()
{}
setAddress (?string $address)
getMusician ()
setMusician ($musician)
isPrimaryAddress ()
Check whether this is the primary address of $this->musician.
preFlush (Event\PreFlushEventArgs $event)
{}
Static Public Member Functions
static validateAddress (string $address)
Validate the given email address.
Private Attributes
$address
@ORM\Column(type="string", length=254, nullable=false, options={"collation"="ascii_general_ci"}) @ORM\Id @ORM\GeneratedValue(strategy="NONE")
$musician
@ORM\ManyToOne(targetEntity="Musician", inversedBy="emailAddresses", fetch="EXTRA_LAZY") @ORM\Id
$doTriggerPreFlushRemoveEvent = false
Neither pre- nor post-remove events can cancel a remove, so we need to listen on pre-flush.
Detailed Description
InstrumentInsurance.
@ORM\Table(name="MusicianEmailAddresses") @ORM\Entity @ORM\HasLifecycleCallbacks
Definition at line 47 of file MusicianEmailAddress.php.
Constructor & Destructor Documentation
__construct()
__construct (string $address = null, Musician $musician = null)
Parameters
null | string $address
null | Musician $musician
Definition at line 74 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$address, MusicianEmailAddress\$musician, and MusicianEmailAddress\setAddress().
Member Function Documentation
__toString()
__toString ()
{}
Definition at line 90 of file MusicianEmailAddress.php.
getAddress()
getAddress ()
Returns
string
Definition at line 84 of file MusicianEmailAddress.php.
Referenced by Musician\setEmail(), and Musician\setPrincipalEmailAddress().
getMusician()
getMusician ()
Returns
Musician
Definition at line 115 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$musician.
isPrimaryAddress()
isPrimaryAddress ()
Check whether this is the primary address of $this->musician.
Returns
bool
Definition at line 136 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$address.
preFlush()
preFlush (Event\PreFlushEventArgs $event)
{}
@ORM\PreFlush
Definition at line 197 of file MusicianEmailAddress.php.
setAddress()
setAddress (?string $address)
Parameters
null | string $address
Returns
MusicianEmailAddress
Definition at line 100 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$address.
Referenced by MusicianEmailAddress\__construct().
setMusician()
setMusician ($musician)
Parameters
int | Musician $musician
Returns
MusicianEmailAddress
Definition at line 125 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$musician.
validateAddress()
static validateAddress (string $address) static
Validate the given email address.
Parameters
string $address
Returns
bool
Definition at line 148 of file MusicianEmailAddress.php.
References MusicianEmailAddress\$address.
Field Documentation
$address
string $address private
@ORM\Column(type="string", length=254, nullable=false, options={"collation"="ascii_general_ci"}) @ORM\Id @ORM\GeneratedValue(strategy="NONE")
Definition at line 59 of file MusicianEmailAddress.php.
Referenced by MusicianEmailAddress\__construct(), MusicianEmailAddress\isPrimaryAddress(), MusicianEmailAddress\setAddress(), and MusicianEmailAddress\validateAddress().
$doTriggerPreFlushRemoveEvent
bool $doTriggerPreFlushRemoveEvent = false private
Neither pre- nor post-remove events can cancel a remove, so we need to listen on pre-flush.
Definition at line 176 of file MusicianEmailAddress.php.
$musician
Musician $musician private
@ORM\ManyToOne(targetEntity="Musician", inversedBy="emailAddresses", fetch="EXTRA_LAZY") @ORM\Id
Definition at line 67 of file MusicianEmailAddress.php.
Referenced by MusicianEmailAddress\__construct(), MusicianEmailAddress\getMusician(), and MusicianEmailAddress\setMusician().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Entities/MusicianEmailAddress.php