CamerataDB: MailingListsService Class Reference
MailingListsService Class Reference
Handle participant mailing-list services.
Public Member Functions
__construct (ConfigService $configService)
isConfigured ()
isReachable ()
Check whether the mailing-lists server is configured and reachable.
getServerConfig ()
Obtain the server configuration, this is rather for testing in order to check the basic connectivity.
getServerVersions (?array &$coreVersion=null)
getListConfig (string $fqdnName, ?string $resource=null)
Fetch the list configuration from the server.
setListConfig (string $fqdnName, mixed $config, mixed $value=null)
Set the list config.
getListInfo (string $fqdnName)
createList (string $fqdnName, string $style='private-default')
Create a non-existing list.
deleteList (string $listId)
Delete an existing list.
renameList (string $listId, ?string $newFqdn=null, ?string $newDisplayName=null)
Rename an existing list.
configureAnnouncementsList (string $listId, $owners=[], $moderators=[], $posters=[])
Configure the given list as an announcements-only list.
setMessageTemplate (string $listId, string $template, ?string $uri)
Install a message template.
getListId (string $fqdnName)
Fetch the list-id of the given list.
getConfigurationUrl (string $listId)
getArchiveUrl (string $listId)
getSubscription (string $listId, string $subscriptionAddress, string $role=self::ROLE_MEMBER)
Find the basic information about a subscription for the given email.
getSubscriptionRequest (string $listId, string $subscriptionAddress)
Get or check for a pending invitation (=== email confirmation request) for the given subscription-address.
handleSubscriptionRequest (string $listId, string $subscriptionAddress, string $action, ?string $reason=null)
Dispose any pending subscription request with the given action.
getSubscriptionStatus (string $listId, string $subscriptionAddress)
Return a brief status for the requested list and email address.
subscribe (string $listId, ?string $email=null, ?string $displayName=null, ?string $role=null, array $subscriptionData=[])
Subscribe a victim to the email-list.
invite (string $listId, string $email, ?string $displayName=null)
Just send an invitation.
unsubscribe (string $listId, string $subscriber, string $role=self::ROLE_MEMBER, bool $silent=false)
Unsubscribe the given email-address.
getSubscriptionPreferences (string $listId, string $subscriber, string $role=self::ROLE_MEMBER)
Fetch the subscription preferences.
setSubscriptionPreferences (string $listId, string $subscriber, array $preferences=[], string $role=self::ROLE_MEMBER,)
Set the subscription preferences.
findMembers (string $listId, array $criteria=[], bool $flat=false)
Find members matching criteria.
patchMember (string $listId, string $subscriber, string $role, array $data)
Patch the membership config for the given email address.
templateFolderPath (string $leafDirectory)
Generate the full path to the given templates leaf-directory.
Data Fields
const ROLE = 'role'
const PRE_VERIFIED = 'pre_verified'
const PRE_CONFIRMED = 'pre_confirmed'
const PRE_APPROVED = 'pre_approved'
const SEND_WELCOME_MESSAGE = 'send_welcome_message'
const SEND_GOODBYE_MESSAGE = 'send_goodbye_message'
const TEMPLATE_DIR_MAILING_LISTS = 'mailing lists'
const TEMPLATE_DIR_AUTO_RESPONSES = 'auto responses'
const TEMPLATE_TYPE_UNSPECIFIC = ''
const TEMPLATE_TYPE_ANNOUNCEMENTS = 'announcements'
const TEMPLATE_TYPE_PROJECTS = 'projects'
const ROLE_MEMBER = 'member'
const ROLE_MODERATOR = 'moderator'
const ROLE_OWNER = 'owner'
const ROLES
const SUBSCRIBER_EMAIL = 'subscriber'
const MEMBER_DISPLAY_NAME = 'display_name'
const MEMBER_DELIVERY_STATUS = 'delivery_status'
const MEMBER_DELIVERY_MODE = 'delivery_mode'
const DELIVERY_STATUS_DISABLED_BY_USER = 'by_user'
const DELIVERY_STATUS_DISABLED_BY_MODERATOR = 'by_moderator'
const DELIVERY_STATUS_DISABLED_BY_BOUNCES = 'by_bounces'
const DELIVERY_STATUS_ENABLED = 'enabled'
const DELIVERY_MODE_REGULAR = 'regular'
const DELIVERY_MODE_PLAINTEXT_DIGESTS = 'plaintext_digests'
const DELIVERY_MODE_MIME_DIGESTS = 'mime_digests'
const DELIVERY_MODE_SUMMARY_DIGESTS = 'summary_digests'
const SUBSCRIPTION_SELF_LINK = 'self_link'
const TEMPLATE_FILE_PREFIX = 'list:'
const TEMPLATE_FILE_ADMIN = 'admin:'
const TEMPLATE_FILE_MEMBER = 'member:'
const TEMPLATE_FILE_USER = 'user'
const TEMPLATE_FILE_RCPTS
const STATUS_SUBSCRIBED = 'subscribed'
const STATUS_UNSUBSCRIBED = 'unsubscribed'
const STATUS_INVITED = 'invited'
const STATUS_WAITING = 'waiting'
const MODERATION_ACTION_ACCEPT = 'accept'
const MODERATION_ACTION_REJECT = 'reject'
const MODERATOIN_ACTOIN_DEFER = 'defer'
const MODERATION_ACTION_DISCARD = 'discard'
const MODERATION_ACTIONS
const MEMBER_MODERATION_KEY = 'moderation_action'
const MEMBER_MODERATION_ACCEPT = self::MODERATION_ACTION_ACCEPT
const MEMBER_MODERATION_HOLD = 'hold'
const MEMBER_MODERATION_REJECT = self::MODERATION_ACTION_REJECT
const MEMBER_MODERATION_DISCARD = self::MODERATION_ACTION_DISCARD
const MEMBER_MODERATIONS
const REQUEST_OWNER_MODERATOR = 'moderator'
const REQUEST_OWNER_SUBSCRIBER = 'subscriber'
const REQUEST_OWNERS
const LIST_CONFIG_DISPLAY_NAME = 'display_name'
const LIST_CONFIG_FQDN_LISTNAME = 'fqdn_listname'
const LIST_CONFIG_ACCEPTABLE_ALIASES = 'acceptabl_aliases'
const LIST_INFO_DISPLAY_NAME = self::LIST_CONFIG_DISPLAY_NAME
const LIST_INFO_FQDN_LISTNAME = self::LIST_CONFIG_FQDN_LISTNAME
const LIST_INFO_ADVERTISED = 'advertised'
const LIST_INFO_DESCRIPTION = 'description'
const LIST_INFO_LIST_NAME = 'list_name'
const LIST_INFO_MAIL_HOST = 'mail_host'
const LIST_INFO_MEMBER_COUNT = 'member_count'
const DEFAULT_MEMBER_SEARCH_CRITERIA
Private Member Functions
addEmailAlias (string $fromAddress, string $toAddress)
Somehow add an email alias to the mail system ...
ensureListId (string $identifier)
Ensure that the given string is a list-id, if it is a FQDN then try to retrieve the list-id.
Static Private Member Functions
static combinedVersion (int $major, int $minor, int $revision)
MAJOR.MINOR.REVISION.
Private Attributes
const DEFAULT_SUBSCRIPTION_DATA
$restClient
$restAuth
$listIdByFqdn = []
Cache the fqdn -> list-id mapping for the current request.
$selfLinkBySubscription = []
Cache the self-link for each subscription for the current request life-time.
Detailed Description
Handle participant mailing-list services.
Definition at line 40 of file MailingListsService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService)
Parameters
ConfigService $configService Global app configuration service.
Definition at line 195 of file MailingListsService.php.
Member Function Documentation
addEmailAlias()
addEmailAlias (string $fromAddress, string $toAddress) private
Somehow add an email alias to the mail system ...
Parameters
string $fromAddress Incoming email address.
string $toAddress Resulting email address.
Returns
void
Definition at line 475 of file MailingListsService.php.
Referenced by MailingListsService\renameList().
combinedVersion()
static combinedVersion (int $major, int $minor, int $revision) static private
MAJOR.MINOR.REVISION.
Parameters
int $major Major verion.
int $minor Minor version.
int $revision Revision.
Returns
int Combined integral version.
Definition at line 288 of file MailingListsService.php.
Referenced by MailingListsService\getServerVersions().
configureAnnouncementsList()
configureAnnouncementsList (string $listId, $owners = [], $moderators = [], $posters = [])
Configure the given list as an announcements-only list.
That is:
all postings are moderated
allow_list_posts set to false (no list-post header)
unsubscription is done without needing further confirmation from the user
subscription is unmoderated, but after user confirmation
$posters are added as list-members with the privilege to post to the list
the archive is public
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string | array $owners Array of owners or the single owner as string.
string | array $moderators Array of moderators or the single moderator as string.
string | array $posters Array of posters or the single posters as string. "posters" are the email addresses which are allowed to post to the list without moderation.
Returns
void
Definition at line 505 of file MailingListsService.php.
References MailingListsService\ensureListId(), MailingListsService\getSubscription(), MailingListsService\patchMember(), MailingListsService\setListConfig(), and MailingListsService\subscribe().
createList()
createList (string $fqdnName, string $style = 'private-default')
Create a non-existing list.
Parameters
string $fqdnName The list FQDN.
string $style The list-style.
Returns
bool Execution status.
Definition at line 385 of file MailingListsService.php.
deleteList()
deleteList (string $listId)
Delete an existing list.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
Returns
bool Execution status.
Definition at line 409 of file MailingListsService.php.
References MailingListsService\ensureListId().
ensureListId()
ensureListId (string $identifier) private
Ensure that the given string is a list-id, if it is a FQDN then try to retrieve the list-id.
Parameters
string $identifier List-id of list-FQDN.
Returns
null|string The List-id or null.
Definition at line 1281 of file MailingListsService.php.
References MailingListsService\getListId().
Referenced by MailingListsService\configureAnnouncementsList(), MailingListsService\deleteList(), MailingListsService\getArchiveUrl(), MailingListsService\getConfigurationUrl(), MailingListsService\getSubscription(), MailingListsService\getSubscriptionRequest(), MailingListsService\handleSubscriptionRequest(), MailingListsService\setMessageTemplate(), MailingListsService\subscribe(), and MailingListsService\unsubscribe().
findMembers()
findMembers (string $listId, array $criteria = [], bool $flat = false)
Find members matching criteria.
Default is to return all members.
Parameters
string $listId The mailing list id to get the information for.
array $criteria Search criteria in order to restrict the search.
bool $flat Return the result as flat array of just email addresses.
Returns
array The array of members.
Definition at line 1054 of file MailingListsService.php.
getArchiveUrl()
getArchiveUrl (string $listId)
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
Returns
The archive url.
Definition at line 643 of file MailingListsService.php.
References MailingListsService\ensureListId().
getConfigurationUrl()
getConfigurationUrl (string $listId)
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
Returns
The configuration URL.
Definition at line 631 of file MailingListsService.php.
References MailingListsService\ensureListId().
getListConfig()
getListConfig (string $fqdnName, ?string $resource = null)
Fetch the list configuration from the server.
Returns null if the lis does not exist.
Parameters
string $fqdnName The list FQDN.
null | string $resource A particular resource. If null the entire list config is returned.
Returns
null|mixed The list configuration. If a single resource is requested, then only the value of the resourfce.
Definition at line 305 of file MailingListsService.php.
Referenced by MailingListsService\renameList().
getListId()
getListId (string $fqdnName)
Fetch the list-id of the given list.
Normally it is just the email-address with @ replaced by a dot.
Parameters
string $fqdnName The list FQDN.
Returns
string The list id.
Definition at line 613 of file MailingListsService.php.
References MailingListsService\getListInfo().
Referenced by MailingListsService\ensureListId().
getListInfo()
getListInfo (string $fqdnName)
Parameters
string $fqdnName The list FQDN.
Returns
null|array The brief list-info.
Definition at line 360 of file MailingListsService.php.
Referenced by MailingListsService\getListId().
getServerConfig()
getServerConfig ()
Obtain the server configuration, this is rather for testing in order to check the basic connectivity.
Returns
null|array
Definition at line 245 of file MailingListsService.php.
Referenced by MailingListsService\isReachable().
getServerVersions()
getServerVersions (?array & $coreVersion = null)
Parameters
null | array $coreVersion Storage for detailed version information.
Returns
array Obtain the server versions.
Definition at line 259 of file MailingListsService.php.
References MailingListsService\combinedVersion().
Referenced by MailingListsService\subscribe().
getSubscription()
getSubscription (string $listId, string $subscriptionAddress, string $role = self::ROLE_MEMBER)
Find the basic information about a subscription for the given email.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriptionAddress The email address to query.
string $role Subscription role (member vs. moderator vs owner).
Returns
bool|array The subscription info.
Definition at line 662 of file MailingListsService.php.
References MailingListsService\ensureListId().
Referenced by MailingListsService\configureAnnouncementsList(), MailingListsService\getSubscriptionPreferences(), MailingListsService\getSubscriptionStatus(), MailingListsService\patchMember(), MailingListsService\setSubscriptionPreferences(), and MailingListsService\unsubscribe().
getSubscriptionPreferences()
getSubscriptionPreferences (string $listId, string $subscriber, string $role = self::ROLE_MEMBER)
Fetch the subscription preferences.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriber The email-address of the subscriber.
string $role Role of the subscription.
Returns
array The preferences data or null in case of error.
Definition at line 984 of file MailingListsService.php.
References MailingListsService\getSubscription().
getSubscriptionRequest()
getSubscriptionRequest (string $listId, string $subscriptionAddress)
Get or check for a pending invitation (=== email confirmation request) for the given subscription-address.
It is not possible to distinguish between an invitation and an email confirmation. The difference is that invitations are not moderated after the email address has been confirmed, but subscription requests may be moderated.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriptionAddress The email address to query.
Returns
array|bool Exectution status or the requested information.
Definition at line 709 of file MailingListsService.php.
References MailingListsService\ensureListId().
Referenced by MailingListsService\getSubscriptionStatus(), and MailingListsService\handleSubscriptionRequest().
getSubscriptionStatus()
getSubscriptionStatus (string $listId, string $subscriptionAddress)
Return a brief status for the requested list and email address.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriptionAddress The email address to query.
Returns
string One of self::STATUS_UNSUBSCRIBED, self::STATUS_SUBSCRIBED, self::STATUS_INVITED, self::STATUS_WAITING;
Exceptions
ConnectException
Definition at line 788 of file MailingListsService.php.
References MailingListsService\getSubscription(), and MailingListsService\getSubscriptionRequest().
handleSubscriptionRequest()
handleSubscriptionRequest (string $listId, string $subscriptionAddress, string $action, ?string $reason = null)
Dispose any pending subscription request with the given action.
In principle there should only be one pending request, so this should be ok.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriptionAddress The email address to query.
string $action The action to perform, see self::MODERATION_ACTIONS.
null | string $reason Optional reason to mail to the $subscriptionAddress.
Returns
bool Execution status.
Definition at line 748 of file MailingListsService.php.
References MailingListsService\ensureListId(), and MailingListsService\getSubscriptionRequest().
invite()
invite (string $listId, string $email, ?string $displayName = null)
Just send an invitation.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $email The subscriber email to send the invitation to.
null | string $displayName The subscribers display-name.
Returns
bool Execution status.
Definition at line 905 of file MailingListsService.php.
References MailingListsService\subscribe().
isConfigured()
isConfigured ()
Returns
bool Whether the mailing list service is configured.
Definition at line 211 of file MailingListsService.php.
Referenced by MailingListsService\isReachable().
isReachable()
isReachable ()
Check whether the mailing-lists server is configured and reachable.
Returns
bool
Definition at line 226 of file MailingListsService.php.
References MailingListsService\getServerConfig(), and MailingListsService\isConfigured().
patchMember()
patchMember (string $listId, string $subscriber, string $role, array $data)
Patch the membership config for the given email address.
In particular, it is possible to set the moderation action and the delivery address.
Parameters
string $listId The mailing list id to get the information for.
string $subscriber The email-address of the subscriber.
string $role The member-ship role.
array $data The to-be-patched-in data.
Returns
bool Execution status.
Definition at line 1101 of file MailingListsService.php.
References MailingListsService\getSubscription().
Referenced by MailingListsService\configureAnnouncementsList().
renameList()
renameList (string $listId, ?string $newFqdn = null, ?string $newDisplayName = null)
Rename an existing list.
Unfortunately, changing the fqdn (email address) is not supported or at least to exposed to the API by mm3. So we do not actually change the address of the list, but just the display name and add the desired email-address to the list of acceptable aliases and then: how to add an email-alias?
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
null | string $newFqdn The new name.
null | string $newDisplayName The new display name.
Returns
bool Execution status.
Definition at line 439 of file MailingListsService.php.
References MailingListsService\addEmailAlias(), and MailingListsService\getListConfig().
setListConfig()
setListConfig (string $fqdnName, mixed $config, mixed $value = null)
Set the list config.
Parameters
string $fqdnName The list FQDN.
string | array $config Configuration array or a particular configuraiton key.
mixed $value If $config is a string then this is the configuration value.
Returns
bool Execution status.
Definition at line 334 of file MailingListsService.php.
Referenced by MailingListsService\configureAnnouncementsList(), and MailingListsService\unsubscribe().
setMessageTemplate()
setMessageTemplate (string $listId, string $template, ?string $uri)
Install a message template.
Parameters
string $listId List-id or FQDN. If FQDN, an additional query is necessary to retrieve the list-id from the server.
string $template The name of the message template to set.
null | string $uri The url to the template.
Returns
bool Execution status.
Definition at line 573 of file MailingListsService.php.
References MailingListsService\ensureListId().
setSubscriptionPreferences()
setSubscriptionPreferences (string $listId, string $subscriber, array $preferences = [], string $role = self::ROLE_MEMBER)
Set the subscription preferences.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriber The email-address of the subscriber.
array $preferences Preferences data array.
string $role Role of the subscription.
Returns
bool Execution status.
Definition at line 1022 of file MailingListsService.php.
References MailingListsService\getSubscription().
Referenced by MailingListsService\subscribe().
subscribe()
subscribe (string $listId, ?string $email = null, ?string $displayName = null, ?string $role = null, array $subscriptionData = [])
Subscribe a victim to the email-list.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
null | string $email If given the data for the 'subscriber' key of the $subscriptionData.
null | string $displayName If given the data for the 'display_name' key of the $subscriptionData.
null | string $role If given the data for the self::ROLE key of the $subscriptionData.
array $subscriptionData The data array which at least the field 'subscriber' which is the email-address to subscribe. It should also contain a display name. All other parameters understood by the rest-API are passed on the the list-server. The 'list_id' is overridden by the first parameter.
Returns
bool Execution status.
Definition at line 832 of file MailingListsService.php.
References MailingListsService\ensureListId(), MailingListsService\getServerVersions(), and MailingListsService\setSubscriptionPreferences().
Referenced by MailingListsService\configureAnnouncementsList(), and MailingListsService\invite().
templateFolderPath()
templateFolderPath (string $leafDirectory)
Generate the full path to the given templates leaf-directory.
Parameters
string $leafDirectory Leaf-component, e.g. self::TEMPLATE_TYPE_ANNOUNCEMENTS or self::TEMPLATE_TYPE_PROJECTS.
Returns
string The full path for the given directory.
Definition at line 1126 of file MailingListsService.php.
unsubscribe()
unsubscribe (string $listId, string $subscriber, string $role = self::ROLE_MEMBER, bool $silent = false)
Unsubscribe the given email-address.
Parameters
string $listId The list-id or FQDN. If a list-fqdn, then an additional query is needed to retrieve the list-id from the server.
string $subscriber The email-address of the subscriber.
string $role Role of the subscription.
bool $silent If set to \true then disable sending for confirmation messages and the like.
Returns
bool Execution status.
Definition at line 931 of file MailingListsService.php.
References MailingListsService\ensureListId(), MailingListsService\getSubscription(), and MailingListsService\setListConfig().
Field Documentation
$listIdByFqdn
array $listIdByFqdn = [] private
Cache the fqdn -> list-id mapping for the current request.
Definition at line 183 of file MailingListsService.php.
$restAuth
array $restAuth private
Definition at line 176 of file MailingListsService.php.
$restClient
RestClient $restClient private
Initial value:
=
  private const DEFAULT_REST_URI  'http://localhost:8001'
Definition at line 173 of file MailingListsService.php.
$selfLinkBySubscription
array $selfLinkBySubscription = [] private
Cache the self-link for each subscription for the current request life-time.
Definition at line 190 of file MailingListsService.php.
DEFAULT_MEMBER_SEARCH_CRITERIA
const DEFAULT_MEMBER_SEARCH_CRITERIA
Initial value:
= [
    self::ROLE => self::ROLE_MEMBER,
  ]
Definition at line 163 of file MailingListsService.php.
DEFAULT_SUBSCRIPTION_DATA
const DEFAULT_SUBSCRIPTION_DATA private
Initial value:
= [
    self::PRE_VERIFIED => true,
    self::PRE_CONFIRMED => true,
    self::PRE_APPROVED => true,
    self::SEND_WELCOME_MESSAGE => true,
    self::ROLE => self::ROLE_MEMBER,
  ]
Definition at line 53 of file MailingListsService.php.
DELIVERY_MODE_MIME_DIGESTS
const DELIVERY_MODE_MIME_DIGESTS = 'mime_digests'
Definition at line 84 of file MailingListsService.php.
DELIVERY_MODE_PLAINTEXT_DIGESTS
const DELIVERY_MODE_PLAINTEXT_DIGESTS = 'plaintext_digests'
Definition at line 83 of file MailingListsService.php.
DELIVERY_MODE_REGULAR
const DELIVERY_MODE_REGULAR = 'regular'
Definition at line 82 of file MailingListsService.php.
DELIVERY_MODE_SUMMARY_DIGESTS
const DELIVERY_MODE_SUMMARY_DIGESTS = 'summary_digests'
Definition at line 85 of file MailingListsService.php.
DELIVERY_STATUS_DISABLED_BY_BOUNCES
const DELIVERY_STATUS_DISABLED_BY_BOUNCES = 'by_bounces'
Definition at line 80 of file MailingListsService.php.
DELIVERY_STATUS_DISABLED_BY_MODERATOR
const DELIVERY_STATUS_DISABLED_BY_MODERATOR = 'by_moderator'
Definition at line 79 of file MailingListsService.php.
DELIVERY_STATUS_DISABLED_BY_USER
const DELIVERY_STATUS_DISABLED_BY_USER = 'by_user'
Definition at line 78 of file MailingListsService.php.
DELIVERY_STATUS_ENABLED
const DELIVERY_STATUS_ENABLED = 'enabled'
Definition at line 81 of file MailingListsService.php.
LIST_CONFIG_ACCEPTABLE_ALIASES
const LIST_CONFIG_ACCEPTABLE_ALIASES = 'acceptabl_aliases'
Definition at line 138 of file MailingListsService.php.
LIST_CONFIG_DISPLAY_NAME
const LIST_CONFIG_DISPLAY_NAME = 'display_name'
Definition at line 136 of file MailingListsService.php.
LIST_CONFIG_FQDN_LISTNAME
const LIST_CONFIG_FQDN_LISTNAME = 'fqdn_listname'
Definition at line 137 of file MailingListsService.php.
LIST_INFO_ADVERTISED
const LIST_INFO_ADVERTISED = 'advertised'
Definition at line 143 of file MailingListsService.php.
LIST_INFO_DESCRIPTION
const LIST_INFO_DESCRIPTION = 'description'
Definition at line 144 of file MailingListsService.php.
LIST_INFO_DISPLAY_NAME
const LIST_INFO_DISPLAY_NAME = self::LIST_CONFIG_DISPLAY_NAME
Definition at line 141 of file MailingListsService.php.
LIST_INFO_FQDN_LISTNAME
const LIST_INFO_FQDN_LISTNAME = self::LIST_CONFIG_FQDN_LISTNAME
Definition at line 142 of file MailingListsService.php.
LIST_INFO_LIST_NAME
const LIST_INFO_LIST_NAME = 'list_name'
Definition at line 145 of file MailingListsService.php.
LIST_INFO_MAIL_HOST
const LIST_INFO_MAIL_HOST = 'mail_host'
Definition at line 146 of file MailingListsService.php.
LIST_INFO_MEMBER_COUNT
const LIST_INFO_MEMBER_COUNT = 'member_count'
Definition at line 147 of file MailingListsService.php.
MEMBER_DELIVERY_MODE
const MEMBER_DELIVERY_MODE = 'delivery_mode'
Definition at line 77 of file MailingListsService.php.
MEMBER_DELIVERY_STATUS
const MEMBER_DELIVERY_STATUS = 'delivery_status'
Definition at line 76 of file MailingListsService.php.
MEMBER_DISPLAY_NAME
const MEMBER_DISPLAY_NAME = 'display_name'
Definition at line 75 of file MailingListsService.php.
MEMBER_MODERATION_ACCEPT
const MEMBER_MODERATION_ACCEPT = self::MODERATION_ACTION_ACCEPT
Definition at line 116 of file MailingListsService.php.
MEMBER_MODERATION_DISCARD
const MEMBER_MODERATION_DISCARD = self::MODERATION_ACTION_DISCARD
Definition at line 119 of file MailingListsService.php.
MEMBER_MODERATION_HOLD
const MEMBER_MODERATION_HOLD = 'hold'
Definition at line 117 of file MailingListsService.php.
MEMBER_MODERATION_KEY
const MEMBER_MODERATION_KEY = 'moderation_action'
Definition at line 115 of file MailingListsService.php.
MEMBER_MODERATION_REJECT
const MEMBER_MODERATION_REJECT = self::MODERATION_ACTION_REJECT
Definition at line 118 of file MailingListsService.php.
MEMBER_MODERATIONS
const MEMBER_MODERATIONS
Initial value:
= [
    self::MEMBER_MODERATION_ACCEPT,
    self::MEMBER_MODERATION_HOLD,
    self::MEMBER_MODERATION_REJECT,
    self::MEMBER_MODERATION_DISCARD,
  ]
Definition at line 121 of file MailingListsService.php.
MODERATION_ACTION_ACCEPT
const MODERATION_ACTION_ACCEPT = 'accept'
Definition at line 104 of file MailingListsService.php.
MODERATION_ACTION_DISCARD
const MODERATION_ACTION_DISCARD = 'discard'
Definition at line 107 of file MailingListsService.php.
MODERATION_ACTION_REJECT
const MODERATION_ACTION_REJECT = 'reject'
Definition at line 105 of file MailingListsService.php.
MODERATION_ACTIONS
const MODERATION_ACTIONS
Initial value:
= [
    self::MODERATION_ACTION_ACCEPT,
    self::MODERATION_ACTION_DISCARD,
    self::MODERATION_ACTION_REJECT,
    self::MODERATOIN_ACTOIN_DEFER,
  ]
Definition at line 108 of file MailingListsService.php.
MODERATOIN_ACTOIN_DEFER
const MODERATOIN_ACTOIN_DEFER = 'defer'
Definition at line 106 of file MailingListsService.php.
PRE_APPROVED
const PRE_APPROVED = 'pre_approved'
Definition at line 49 of file MailingListsService.php.
PRE_CONFIRMED
const PRE_CONFIRMED = 'pre_confirmed'
Definition at line 48 of file MailingListsService.php.
PRE_VERIFIED
const PRE_VERIFIED = 'pre_verified'
Definition at line 47 of file MailingListsService.php.
REQUEST_OWNER_MODERATOR
const REQUEST_OWNER_MODERATOR = 'moderator'
Definition at line 128 of file MailingListsService.php.
REQUEST_OWNER_SUBSCRIBER
const REQUEST_OWNER_SUBSCRIBER = 'subscriber'
Definition at line 129 of file MailingListsService.php.
REQUEST_OWNERS
const REQUEST_OWNERS
Initial value:
= [
    self::REQUEST_OWNER_MODERATOR,
    self::REQUEST_OWNER_SUBSCRIBER,
  ]
Definition at line 130 of file MailingListsService.php.
ROLE
const ROLE = 'role'
Definition at line 45 of file MailingListsService.php.
ROLE_MEMBER
const ROLE_MEMBER = 'member'
Definition at line 67 of file MailingListsService.php.
ROLE_MODERATOR
const ROLE_MODERATOR = 'moderator'
Definition at line 68 of file MailingListsService.php.
ROLE_OWNER
const ROLE_OWNER = 'owner'
Definition at line 69 of file MailingListsService.php.
ROLES
const ROLES
Initial value:
= [
    self::ROLE_MEMBER, self::ROLE_MODERATOR, self::ROLE_OWNER,
  ]
Definition at line 70 of file MailingListsService.php.
SEND_GOODBYE_MESSAGE
const SEND_GOODBYE_MESSAGE = 'send_goodbye_message'
Definition at line 51 of file MailingListsService.php.
SEND_WELCOME_MESSAGE
const SEND_WELCOME_MESSAGE = 'send_welcome_message'
Definition at line 50 of file MailingListsService.php.
STATUS_INVITED
const STATUS_INVITED = 'invited'
Definition at line 101 of file MailingListsService.php.
STATUS_SUBSCRIBED
const STATUS_SUBSCRIBED = 'subscribed'
Definition at line 99 of file MailingListsService.php.
STATUS_UNSUBSCRIBED
const STATUS_UNSUBSCRIBED = 'unsubscribed'
Definition at line 100 of file MailingListsService.php.
STATUS_WAITING
const STATUS_WAITING = 'waiting'
Definition at line 102 of file MailingListsService.php.
SUBSCRIBER_EMAIL
const SUBSCRIBER_EMAIL = 'subscriber'
Definition at line 74 of file MailingListsService.php.
SUBSCRIPTION_SELF_LINK
const SUBSCRIPTION_SELF_LINK = 'self_link'
Definition at line 87 of file MailingListsService.php.
TEMPLATE_DIR_AUTO_RESPONSES
const TEMPLATE_DIR_AUTO_RESPONSES = 'auto responses'
Definition at line 62 of file MailingListsService.php.
TEMPLATE_DIR_MAILING_LISTS
const TEMPLATE_DIR_MAILING_LISTS = 'mailing lists'
Definition at line 61 of file MailingListsService.php.
TEMPLATE_FILE_ADMIN
const TEMPLATE_FILE_ADMIN = 'admin:'
Definition at line 90 of file MailingListsService.php.
TEMPLATE_FILE_MEMBER
const TEMPLATE_FILE_MEMBER = 'member:'
Definition at line 91 of file MailingListsService.php.
TEMPLATE_FILE_PREFIX
const TEMPLATE_FILE_PREFIX = 'list:'
Definition at line 89 of file MailingListsService.php.
TEMPLATE_FILE_RCPTS
const TEMPLATE_FILE_RCPTS
Initial value:
= [
    self::TEMPLATE_FILE_PREFIX . self::TEMPLATE_FILE_ADMIN,
    self::TEMPLATE_FILE_PREFIX . self::TEMPLATE_FILE_MEMBER,
    self::TEMPLATE_FILE_PREFIX . self::TEMPLATE_FILE_USER,
  ]
Definition at line 93 of file MailingListsService.php.
TEMPLATE_FILE_USER
const TEMPLATE_FILE_USER = 'user'
Definition at line 92 of file MailingListsService.php.
TEMPLATE_TYPE_ANNOUNCEMENTS
const TEMPLATE_TYPE_ANNOUNCEMENTS = 'announcements'
Definition at line 64 of file MailingListsService.php.
TEMPLATE_TYPE_PROJECTS
const TEMPLATE_TYPE_PROJECTS = 'projects'
Definition at line 65 of file MailingListsService.php.
TEMPLATE_TYPE_UNSPECIFIC
const TEMPLATE_TYPE_UNSPECIFIC = ''
Definition at line 63 of file MailingListsService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/MailingListsService.php