CamerataDB: PHPMailer Class Reference
PHPMailer Class Reference
Slightly enhanced version of PHPMailer.
Public Member Functions
getMailHeaders ()
Returns the complete headers, but not the body.
__construct (?bool $exceptions=null)
html2text ($html, $advanced=false)
{}
setProgressCallback (Closure $progressCallback)
send ()
Create a message and send it.
generateMessageId ()
Generate a messsage id just like it would be generated by PHPMailer.
addReference (string $messageId)
Add a referenced message id.
setReferences (array $references)
Set the referenced message ids.
clearReferences ()
Clear the referenced message ids.
getReferences ()
Get the referenced message ids.
createHeader ()
{}
getSentMIMEMessage ()
{}
failedRecipients (string $errorMessage)
Parse a failed-recipients error string and explode into a list of failed recipients.
Protected Attributes
const DEBUG_PREFIX = 'CLIENT -> SERVER: '
const DEBUG_DATA = 'DATA'
const DEBUG_QUIT = 'QUIT'
$mimeMessageTotalSize = 0
$mimeDataSent
Callable $progressCallback = null
$references = []
References message ids.
Detailed Description
Slightly enhanced version of PHPMailer.
return the message headers without body
Definition at line 34 of file PHPMailer.php.
Constructor & Destructor Documentation
__construct()
__construct (?bool $exceptions = null)
Definition at line 91 of file PHPMailer.php.
Member Function Documentation
addReference()
addReference (string $messageId)
Add a referenced message id.
Parameters
string $messageId
Returns
void
Definition at line 188 of file PHPMailer.php.
clearReferences()
clearReferences ()
Clear the referenced message ids.
Returns
void
Definition at line 210 of file PHPMailer.php.
References PHPMailer\setReferences().
createHeader()
createHeader ()
{}
Override the vanilla method as PHPMailerUpstream does not provide support for the References header.
Definition at line 231 of file PHPMailer.php.
failedRecipients()
failedRecipients (string $errorMessage)
Parse a failed-recipients error string and explode into a list of failed recipients.
Return null if $errorMessages does not refer to failed recipients.
Parameters
string $errorMessage Error message, e.g. from an exception.
Returns
array
Definition at line 259 of file PHPMailer.php.
generateMessageId()
generateMessageId ()
Generate a messsage id just like it would be generated by PHPMailer.
Returns
string
Definition at line 176 of file PHPMailer.php.
getMailHeaders()
getMailHeaders ()
Returns the complete headers, but not the body.
Only valid post preSend().
See also
PHPMailerUpstream::preSend()
Returns
string
Definition at line 81 of file PHPMailer.php.
Referenced by PHPMailer\getSentMIMEMessage(), and PHPMailer\send().
getReferences()
getReferences ()
Get the referenced message ids.
Returns
array
Definition at line 220 of file PHPMailer.php.
References PHPMailer\$references.
getSentMIMEMessage()
getSentMIMEMessage ()
{}
Add also the Bcc headers in order to get a useful preview and more useful sent messages.
Definition at line 246 of file PHPMailer.php.
References PHPMailer\getMailHeaders().
html2text()
html2text ($html, $advanced = false)
{}
Override the vanilla method to use a more decent html to text converter by default.
Definition at line 122 of file PHPMailer.php.
References Html2Text\convert().
send()
send ()
Create a message and send it.
Uses the sending method specified by $Mailer.
Exceptions
Exception
Returns
bool false on error - See the ErrorInfo property for details of the error
Definition at line 148 of file PHPMailer.php.
References PHPMailer\getMailHeaders().
setProgressCallback()
setProgressCallback (Closure $progressCallback)
Parameters
Closure $progressCallback
Returns
void
Definition at line 135 of file PHPMailer.php.
setReferences()
setReferences (array $references)
Set the referenced message ids.
Parameters
array $references
Returns
void
Definition at line 200 of file PHPMailer.php.
References PHPMailer\$references.
Referenced by PHPMailer\clearReferences().
Field Documentation
$mimeDataSent
$mimeDataSent protected
Definition at line 62 of file PHPMailer.php.
$mimeMessageTotalSize
$mimeMessageTotalSize = 0 protected
Definition at line 61 of file PHPMailer.php.
$progressCallback
Callable $progressCallback = null protected
Definition at line 64 of file PHPMailer.php.
$references
array $references = [] protected
References message ids.
Definition at line 71 of file PHPMailer.php.
Referenced by PHPMailer\getReferences(), and PHPMailer\setReferences().
DEBUG_DATA
const DEBUG_DATA = 'DATA' protected
Definition at line 58 of file PHPMailer.php.
DEBUG_PREFIX
const DEBUG_PREFIX = 'CLIENT -> SERVER: ' protected
Definition at line 57 of file PHPMailer.php.
DEBUG_QUIT
const DEBUG_QUIT = 'QUIT' protected
Definition at line 59 of file PHPMailer.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Common/PHPMailer.php