CamerataDB: BlogMapper Class Reference
BlogMapper Class Reference
Mapper for the blog entities.
Public Member Functions
__construct (IDBConnection $db, string $appName, protected IL10N $l, protected ILogger $logger,)
createNote (string $author, ?int $inReply, string $content, int $priority=0, bool $popup=false,)
Create a new note.
modifyNote (string $author, int $blogId, string $content='', mixed $priority=false, ?bool $popup=null, mixed $reader=false,)
Modify a note.
deleteNote (int $blogId, bool $drop=false)
Delete the given Note and the entire thread referring to it.
findThreadDisplay ()
Generate a complex tree structure reflecting the message threads.
notificationPending (string $userId)
Obtain "some popup notice is pending" for the given user / all users.
needPhpSession ()
find (int $id)
findAll ($limit=null, $offset=null)
Private Member Functions
findThread (int $id)
Fetch the array of messages referring to $id via inReplyTo.
findThreadTree (array $parent)
Generate a complex tree structure reflecting the message threads.
Detailed Description
Mapper for the blog entities.
Definition at line 39 of file BlogMapper.php.
Constructor & Destructor Documentation
__construct()
__construct (IDBConnection $db, string $appName, protected IL10N $l, protected ILogger $logger)
Definition at line 44 of file BlogMapper.php.
Member Function Documentation
createNote()
createNote (string $author, ?int $inReply, string $content, int $priority = 0, bool $popup = false)
Create a new note.
Parameters
string $author The author of this mess.
int $inReply The id of a previous note this one refers to. If $blogId > 0 then this parameter is ignored; only the message text is affected.
string $content The message text.
int $priority The priority, should be between 0 and
Only top-level notes may carry a priority (so if $inReply
‍0, then $priority is ignored).
bool $popup if true then the note will appear as one-time popup. We remeber the user-id of the reader in the db, after the user has clicked away the alert box. as a one-time popup.
Returns
bool true on success.
Definition at line 76 of file BlogMapper.php.
deleteNote()
deleteNote (int $blogId, bool $drop = false)
Delete the given Note and the entire thread referring to it.
There is intentionally no security.
Parameters
int $blogId The unique Id of the note to delete.
bool $drop If true then really delete the message, otherwise just mark them as deleted.
Returns
bool true on success.
Definition at line 176 of file BlogMapper.php.
References BlogMapper\deleteNote(), and BlogMapper\findThread().
Referenced by BlogMapper\deleteNote().
find()
find (int $id) inherited
Parameters
int $id
Returns
mixed
Exceptions
\OCP\AppFramework\Db\DoesNotExistException If not found.
Exceptions
\OCP\AppFramework\Db\MultipleObjectsReturnedException If more than one result.
Definition at line 57 of file Mapper.php.
Referenced by BlogMapper\modifyNote().
findAll()
findAll ($limit = null, $offset = null) inherited
Parameters
null | int $limit
null | int $offset
Returns
array
Todo
Maybe unused.
Definition at line 79 of file Mapper.php.
findThread()
findThread (int $id) private
Fetch the array of messages referring to $id via inReplyTo.
Parameters
int $id
Returns
array
Definition at line 202 of file BlogMapper.php.
Referenced by BlogMapper\deleteNote(), and BlogMapper\findThreadTree().
findThreadDisplay()
findThreadDisplay ()
Generate a complex tree structure reflecting the message threads.
This is the entry point for the template: fetch all notes in turn. If the function succeeds the return value has the following layout:
array('status' => 'success', 'data' => array([0] => array('head' => THREAD_HEAD, 'children' => array([0] => array('head' =>
and so on, i.e. a representatin of the message-thread tree. Data will be the empty array if there is not data. On error the following structure is returned:
array('status' => 'error', 'data' => ERROR_MESSAGE)
Thread-heads are sorted according to priority, then according to date (newest first). The dangling threads are sorted according to date (oldest first).
Returns
array Tree-like nested array structure modelling the message threads.
Definition at line 278 of file BlogMapper.php.
References BlogMapper\findThreadTree(), and BlogMapper\notificationPending().
findThreadTree()
findThreadTree (array $parent) private
Generate a complex tree structure reflecting the message threads.
This function calls itself recursively until all sub-threads have been fetched.
Parameters
array $parent
Returns
array
Definition at line 242 of file BlogMapper.php.
References BlogMapper\findThread(), and BlogMapper\findThreadTree().
Referenced by BlogMapper\findThreadDisplay(), and BlogMapper\findThreadTree().
modifyNote()
modifyNote (string $author, int $blogId, string $content = '', mixed $priority = false, ?bool $popup = null, mixed $reader = false)
Modify a note.
Parameters
string $author The author of this mess.
int $blogId The blog-Id of an existing entry.
string $content The message text. Ignored if empty.
bool | int $priority The priority in the range 0...255. Ignored if false.
null | bool $popup false: do not change. +1: Mark this as a one-time popup-note. -1: unmark as popup note. false: ignore.
mixed $reader Comma separated list of users for which the note is marked as read. If false, nothing changes. If < 0 remove all readers.
Returns
bool true on success.
Definition at line 115 of file BlogMapper.php.
References Mapper\find().
needPhpSession()
needPhpSession ()
Returns
bool
Todo
This does not seem to be used ...
Definition at line 329 of file BlogMapper.php.
notificationPending()
notificationPending (string $userId)
Obtain "some popup notice is pending" for the given user / all users.
Parameters
string $userId
Returns
bool
Definition at line 302 of file BlogMapper.php.
Referenced by BlogMapper\findThreadDisplay().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Database/Cloud/Mapper/BlogMapper.php