CamerataDB: SepaBulkTransactionEntityListener Class Reference
SepaBulkTransactionEntityListener Class Reference
An entity listener.
Public Member Functions
__construct (ILogger $logger, IL10N $l10n, EntityManager $entityManager, BankTransactionsStorage $storage, SepaBulkTransactionService $service, IAppContainer $appContainer,)
preUpdate (Entities\SepaBulkTransaction $transaction, ORMEvent\PreUpdateEventArgs $eventArgs)
{}
prePersist (Entities\SepaBulkTransaction $transaction, ORMEvent\LifecycleEventArgs $eventArgs)
{}
Protected Attributes
$l
$service
$storage
$lock = []
Private Member Functions
lockEntity (Entities\SepaBulkTransaction $transaction)
Protect against re-entrance when the preRemove() handler causes changes to the entity.
unlockEntity (Entities\SepaBulkTransaction $transaction)
Protect against re-entrance when the preRemove() handler causes changes to the entity.
Detailed Description
An entity listener.
The task is to update the export data of the bulk-transaction.
Definition at line 42 of file SepaBulkTransactionEntityListener.php.
Constructor & Destructor Documentation
__construct()
__construct (ILogger $logger, IL10N $l10n, EntityManager $entityManager, BankTransactionsStorage $storage, SepaBulkTransactionService $service, IAppContainer $appContainer)
Definition at line 60 of file SepaBulkTransactionEntityListener.php.
Member Function Documentation
lockEntity()
lockEntity (Entities\SepaBulkTransaction $transaction) private
Protect against re-entrance when the preRemove() handler causes changes to the entity.
Parameters
Entities\\SepaBulkTransaction $transaction
Returns
bool
Definition at line 83 of file SepaBulkTransactionEntityListener.php.
Referenced by SepaBulkTransactionEntityListener\preUpdate().
prePersist()
prePersist (Entities\SepaBulkTransaction $transaction, ORMEvent\LifecycleEventArgs $eventArgs)
{}
Definition at line 120 of file SepaBulkTransactionEntityListener.php.
Referenced by SepaBulkTransactionEntityListener\preUpdate().
preUpdate()
preUpdate (Entities\SepaBulkTransaction $transaction, ORMEvent\PreUpdateEventArgs $eventArgs)
{}
Definition at line 108 of file SepaBulkTransactionEntityListener.php.
References SepaBulkTransactionEntityListener\lockEntity(), SepaBulkTransactionEntityListener\prePersist(), and SepaBulkTransactionEntityListener\unlockEntity().
unlockEntity()
unlockEntity (Entities\SepaBulkTransaction $transaction) private
Protect against re-entrance when the preRemove() handler causes changes to the entity.
Parameters
Entities\\SepaBulkTransaction $transaction
Returns
void
Definition at line 100 of file SepaBulkTransactionEntityListener.php.
Referenced by SepaBulkTransactionEntityListener\preUpdate().
Field Documentation
$l
IL10N $l protected
Definition at line 48 of file SepaBulkTransactionEntityListener.php.
$lock
array $lock = [] protected
Definition at line 57 of file SepaBulkTransactionEntityListener.php.
$service
SepaBulkTransactionService $service protected
Definition at line 51 of file SepaBulkTransactionEntityListener.php.
$storage
BankTransactionsStorage $storage protected
Definition at line 54 of file SepaBulkTransactionEntityListener.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Listener/SepaBulkTransactionEntityListener.php