CamerataDB: GeoCodingService Class Reference
GeoCodingService Class Reference
Cache-service which fetches geo-coding information in the background in order to use them in autocompletion widgets and for validation of user input.
Public Member Functions
__construct (ConfigService $configService, EntityManager $entityManager,)
{}
localeCountryNames (?string $language=null)
Return an array of PHP-supported country-codes and localized names; this uses the PHP-internal locale support.
localeCountryName ($locale=null)
localeRegion ($locale=null)
localeLanguage ($locale=null)
updateCountries (bool $force=false)
Synchronize the countries- and continents table with the underlying backend.
getLanguages (?string $extraLang=null)
countryContinents (string $language=null)
Export the table of known countries w.r.t.
Data Fields
const DEFAULT_LANGUAGE = 'en'
const JSON = 1
const XML = 2
const RDF = 3
const DRY = 99
const GEONAMES_TAG = "geonames"
const POSTALCODESLOOKUP_TAG = "postalcodes"
const POSTALCODESSEARCH_TAG = "postalCodes"
const POSTAL_CODE_STATE_CODE_TAG = 'adminCode1'
const POSTAL_CODE_STATE_NAME_TAG = 'adminName1'
const PROVIDER_URL = 'http://api.geonames.org'
const NOMINATIM_URL = 'https://nominatim.openstreetmap.org/search'
const OVERPASS_URL = 'https://overpass-api.de/api/interpreter'
Protected Member Functions
debug (string $message, array $context=[], int $shift=0)
Issue a debug message.
Private Member Functions
request (string $command, array $parameters, int $type=self::JSON)
Recurse to the backend and place one single request.
translatePlaceName (string $name, string $country, ?string $language=null)
Try to find a native translation by pinging the remote provider.
stampPostalCode (string $postalCode, string $country)
Forcibly set the update-time-stamp for the given postal code.
Private Attributes
$userName = null
$countryNames = []
$continentNames = []
$countryContinents = []
$languages = []
$regionNames = []
$debug = false
Detailed Description
Cache-service which fetches geo-coding information in the background in order to use them in autocompletion widgets and for validation of user input.
Definition at line 45 of file GeoCodingService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, EntityManager $entityManager)
{}
Definition at line 74 of file GeoCodingService.php.
References GeoCodingService\debug().
Member Function Documentation
countryContinents()
countryContinents (string $language = null)
Export the table of known countries w.r.t.
to the current locale or the requested language, adding the continent as grouping information. This function returns the actual human readable continent names, not the two-letter codes.
Parameters
string $language Language to update.
Returns
array An array array(CountryCode => ContinentName)
Definition at line 1101 of file GeoCodingService.php.
debug()
debug (string $message, array $context = [], int $shift = 0) protected
Issue a debug message.
Parameters
string $message Message to write to the log.
array $context Message context with meta information.
int $shift Backtrace shift in order to get the position in the parent call-stack.
Returns
void
See also
ConfigService::logDebug()
ConfigService::logInfo()
Definition at line 99 of file GeoCodingService.php.
References GeoCodingService\debug().
Referenced by GeoCodingService\__construct(), GeoCodingService\debug(), and GeoCodingService\request().
getLanguages()
getLanguages (?string $extraLang = null)
Parameters
null | string $extraLang Extra language (one) to add if given.
Returns
array The languages supported in the database tables.
Definition at line 1064 of file GeoCodingService.php.
localeCountryName()
localeCountryName ($locale = null)
Parameters
null | string $locale If null the current user's locale.
Returns
string Return the country-code for the requested or current locale.
Definition at line 916 of file GeoCodingService.php.
localeCountryNames()
localeCountryNames (?string $language = null)
Return an array of PHP-supported country-codes and localized names; this uses the PHP-internal locale support.
Parameters
null | string $language The desired language for the returned country names.
Returns
array An array in the form array(CODE => NAME) where CODE is the two-letter ISO-code for the country and NAME the name of the locale in either the language requested by the $language parameter or the default Locale language deduced from the personal settings of the current user.
Definition at line 894 of file GeoCodingService.php.
localeLanguage()
localeLanguage ($locale = null)
Parameters
null | string $locale If null the current user's locale.
Returns
string The language for the requested or current locale.
Definition at line 944 of file GeoCodingService.php.
localeRegion()
localeRegion ($locale = null)
Parameters
null | string $locale If null the current user's locale.
Returns
string The two-letter region.
Definition at line 930 of file GeoCodingService.php.
request()
request (string $command, array $parameters, int $type = self::JSON) private
Recurse to the backend and place one single request.
This should be abstracted further, but should do for the moment.
Parameters
string $command
array $parameters
int $type
Returns
null|arrayz|string If $type == GeoCodingService::TYPE_DRY then the request URI, otherwise null on failure, array with results on success.
Definition at line 122 of file GeoCodingService.php.
References GeoCodingService\debug().
stampPostalCode()
stampPostalCode (string $postalCode, string $country) private
Forcibly set the update-time-stamp for the given postal code.
This is needed for the case where some data-base or remote queries fail in order to prevent starvation of the dynamic update procedure.
Note that this may affect more than one entry.
Parameters
string $postalCode Postal code to time-stamp.
string $country The country the postal code belongs to.
Returns
void
Definition at line 625 of file GeoCodingService.php.
translatePlaceName()
translatePlaceName (string $name, string $country, ?string $language = null) private
Try to find a native translation by pinging the remote provider.
Parameters
string $name Search term.
string $country Guess what.
null | string $language Given locale, if null the current user's locale is used.
Returns
null|array [ name => TRANSLATION, adminName1 => TRANSLATED_ADMIN1, adminCode1 => CODE ], null if not found.
Definition at line 579 of file GeoCodingService.php.
updateCountries()
updateCountries (bool $force = false)
Synchronize the countries- and continents table with the underlying backend.
This function tries to update all stored languages and the language from the current locale, and at the very least the English version of the name is obtained (as well a the native one for the countries). It also tries to add the primary language of the current locale to the tables.
Parameters
bool $force Passed on to updateCountriesForLanguage().
Returns
bool Execution status.
See also
updateCountriesForLanguage()
Definition at line 966 of file GeoCodingService.php.
Field Documentation
$continentNames
$continentNames = [] private
Definition at line 65 of file GeoCodingService.php.
$countryContinents
$countryContinents = [] private
Definition at line 66 of file GeoCodingService.php.
$countryNames
$countryNames = [] private
Definition at line 64 of file GeoCodingService.php.
$debug
bool $debug = false private
Definition at line 71 of file GeoCodingService.php.
$languages
$languages = [] private
Definition at line 67 of file GeoCodingService.php.
$regionNames
$regionNames = [] private
Definition at line 68 of file GeoCodingService.php.
$userName
$userName = null private
Definition at line 63 of file GeoCodingService.php.
DEFAULT_LANGUAGE
const DEFAULT_LANGUAGE = 'en'
Definition at line 50 of file GeoCodingService.php.
DRY
const DRY = 99
Definition at line 54 of file GeoCodingService.php.
GEONAMES_TAG
const GEONAMES_TAG = "geonames"
Definition at line 55 of file GeoCodingService.php.
JSON
const JSON = 1
Definition at line 51 of file GeoCodingService.php.
NOMINATIM_URL
const NOMINATIM_URL = 'https://nominatim.openstreetmap.org/search'
Definition at line 61 of file GeoCodingService.php.
OVERPASS_URL
const OVERPASS_URL = 'https://overpass-api.de/api/interpreter'
Definition at line 62 of file GeoCodingService.php.
POSTAL_CODE_STATE_CODE_TAG
const POSTAL_CODE_STATE_CODE_TAG = 'adminCode1'
Definition at line 58 of file GeoCodingService.php.
POSTAL_CODE_STATE_NAME_TAG
const POSTAL_CODE_STATE_NAME_TAG = 'adminName1'
Definition at line 59 of file GeoCodingService.php.
POSTALCODESLOOKUP_TAG
const POSTALCODESLOOKUP_TAG = "postalcodes"
Definition at line 56 of file GeoCodingService.php.
POSTALCODESSEARCH_TAG
const POSTALCODESSEARCH_TAG = "postalCodes"
Definition at line 57 of file GeoCodingService.php.
PROVIDER_URL
const PROVIDER_URL = 'http://api.geonames.org'
Definition at line 60 of file GeoCodingService.php.
RDF
const RDF = 3
Definition at line 53 of file GeoCodingService.php.
XML
const XML = 2
Definition at line 52 of file GeoCodingService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/GeoCodingService.php