CamerataDB: GroupFoldersService Class Reference
GroupFoldersService Class Reference
Toolkit forwarder service in order to have the app's L10N instance.
Public Member Functions
__construct (LoggerInterface $logger, IRootFolder $rootFolder, FolderManager $folderManager, MountProvider $mountProvider, IL10N $l10n,)
setL10N (IL10N $l10n)
Set the localization to use.
getFolder (string $mountPoint, bool $reload=false)
Obtain the shared folder data for the given mount-point.
searchFolders (string $regexp, string $topic=self::SEARCH_TOPIC_MOUNT)
Return all shared folders matching the given regexp.
deleteFolders (string $mountRegexp)
getFolderById (int $id)
Get the shared folder by its id.
createFolder (string $mountPoint, array $groups, array $manager=[])
Create a shared folder and set appropriate permissions.
addGroupToFolder (string $mountPoint, string $groupId, int $permissions=self::DEFAULT_PERMISSIONS, bool $canManage=false,)
Add a single group to the given shared folder.
removeGroupFromFolder (string $mountPoint, string $groupId)
Remove a group from the given shared folder.
addManagerToFolder (string $mountPoint, string $managerId, string $managerType)
removeManagerFromFolder (string $mountPoint, string $managerId, string $managerType)
setGroupPermissions (string $mountPoint, string $groupId, int $permissions)
changeMountPoint (string $mountPoint, string $targetMountPoint, bool $moveChildren=true)
Change the given group-shared folder – given by its old mount-point – to a new mount-point.
Data Fields
const GROUP_FOLDERS_APP = 'groupfolders'
const SEARCH_TOPIC_MOUNT = 'mount'
const SEARCH_TOPIC_GROUP = 'group'
const PERMISSION_WRITE = Constants::PERMISSION_READ|Constants::PERMISSION_UPDATE|Constants::PERMISSION_CREATE
const PERMISSION_READ = Constants::PERMISSION_READ
const PERMISSION_DELETE = Constants::PERMISSION_READ|Constants::PERMISSION_DELETE
const PERMISSION_SHARE = Constants::PERMISSION_READ|Constants::PERMISSION_SHARE
const PERMISSION_ALL = Constants::PERMISSION_ALL
const DEFAULT_PERMISSIONS = self::PERMISSION_ALL
const MANAGER_TYPE_GROUP = 'group'
const MANAGER_TYPE_USER = 'user'
Private Member Functions
fetchFolders ()
Fetch and cache all shared folders from the groupfolders app.
ensureFolders (bool $reload=false)
changeFolderManager (string $mountPoint, string $managerId, string $type, bool $canManage)
getRootFolderStorageId ()
Private Attributes
$sharedFolders = null
All shared folders.
Detailed Description
Toolkit forwarder service in order to have the app's L10N instance.
Definition at line 37 of file GroupFoldersService.php.
Constructor & Destructor Documentation
__construct()
__construct (LoggerInterface $logger, IRootFolder $rootFolder, FolderManager $folderManager, MountProvider $mountProvider, IL10N $l10n)
Definition at line 40 of file GroupFoldersService.php.
Member Function Documentation
addGroupToFolder()
addGroupToFolder (string $mountPoint, string $groupId, int $permissions = self::DEFAULT_PERMISSIONS, bool $canManage = false) inherited
Add a single group to the given shared folder.
This is a no-op if the group including matching permissions is already there.
Parameters
string $mountPoint
string $groupId
int $permissions
bool $canManage
Returns
void
Definition at line 279 of file GroupFoldersService.php.
Referenced by GroupFoldersService\createFolder().
addManagerToFolder()
addManagerToFolder (string $mountPoint, string $managerId, string $managerType) inherited
Parameters
string $mountPoint
string $managerId
string $managerType
Returns
void
Definition at line 384 of file GroupFoldersService.php.
Referenced by GroupFoldersService\createFolder().
changeFolderManager()
changeFolderManager (string $mountPoint, string $managerId, string $type, bool $canManage) private inherited
Parameters
string $mountPoint
string $managerId
string $type
bool $canManage
Returns
void
Definition at line 337 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logDebug().
changeMountPoint()
changeMountPoint (string $mountPoint, string $targetMountPoint, bool $moveChildren = true) inherited
Change the given group-shared folder – given by its old mount-point – to a new mount-point.
Parameters
string $mountPoint The old mount-point which determines the group-shared folder to act upon.
string $targetMountPoint The destination mount-point. If the parent-directories of the destination mount-point do not exist then the shared folder will be hidden.
bool $moveChildren If true and the old mount-point appears as prefix in other group-shared folders then change their respective mount-points as well.
Returns
void
Definition at line 444 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logException().
createFolder()
createFolder (string $mountPoint, array $groups, array $manager = []) inherited
Create a shared folder and set appropriate permissions.
Parameters
string $mountPoint Note the a nested mount-point will not create the parent folders.
array $groups Array $groupId => $groupPermissions
[ GROUP1_ID => PERMS1, GROUP2_ID => PERMS2 ]
.
array $manager ID => TYPE
[ USER_ID => 'user', GROUP_ID => 'group' ]
.
Returns
void
Definition at line 247 of file GroupFoldersService.php.
References GroupFoldersService\addGroupToFolder(), GroupFoldersService\addManagerToFolder(), GroupFoldersService\getFolder(), and GroupFoldersService\getFolderById().
deleteFolders()
deleteFolders (string $mountRegexp) inherited
Parameters
string $mountRegexp
Returns
void
Definition at line 196 of file GroupFoldersService.php.
References GroupFoldersService\searchFolders().
ensureFolders()
ensureFolders (bool $reload = false) private inherited
Parameters
bool $reload
Returns
void
Definition at line 130 of file GroupFoldersService.php.
References GroupFoldersService\fetchFolders().
Referenced by GroupFoldersService\getFolder().
fetchFolders()
fetchFolders () private inherited
Fetch and cache all shared folders from the groupfolders app.
Returns
void
Definition at line 115 of file GroupFoldersService.php.
References GroupFoldersService\getRootFolderStorageId(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\ensureFolders(), and GroupFoldersService\searchFolders().
getFolder()
getFolder (string $mountPoint, bool $reload = false) inherited
Obtain the shared folder data for the given mount-point.
Parameters
string $mountPoint
bool $reload
Returns
null|array Return the data requested from the groupfolders app or null if the folder is not found.
Definition at line 147 of file GroupFoldersService.php.
References GroupFoldersService\ensureFolders(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\createFolder().
getFolderById()
getFolderById (int $id) inherited
Get the shared folder by its id.
The folder must exist
Parameters
int $id
Returns
array
Definition at line 213 of file GroupFoldersService.php.
References GroupFoldersService\getRootFolderStorageId(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\createFolder().
getRootFolderStorageId()
getRootFolderStorageId () private inherited
Returns
null|int The storage id of the root folder.
Definition at line 476 of file GroupFoldersService.php.
Referenced by GroupFoldersService\fetchFolders(), and GroupFoldersService\getFolderById().
removeGroupFromFolder()
removeGroupFromFolder (string $mountPoint, string $groupId) inherited
Remove a group from the given shared folder.
Parameters
string $mountPoint
string $groupId
Returns
void
Definition at line 314 of file GroupFoldersService.php.
removeManagerFromFolder()
removeManagerFromFolder (string $mountPoint, string $managerId, string $managerType) inherited
Parameters
string $mountPoint
string $managerId
string $managerType
Returns
void
Definition at line 398 of file GroupFoldersService.php.
searchFolders()
searchFolders (string $regexp, string $topic = self::SEARCH_TOPIC_MOUNT) inherited
Return all shared folders matching the given regexp.
Parameters
string $regexp
string $topic
Returns
array
Definition at line 163 of file GroupFoldersService.php.
References GroupFoldersService\fetchFolders(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\deleteFolders().
setGroupPermissions()
setGroupPermissions (string $mountPoint, string $groupId, int $permissions) inherited
Parameters
string $mountPoint
string $groupId
int $permissions
Returns
void
Definition at line 412 of file GroupFoldersService.php.
setL10N()
setL10N (IL10N $l10n) inherited
Set the localization to use.
Parameters
IL10N $l10n
Returns
GroupFOldersService $this.
Definition at line 103 of file GroupFoldersService.php.
Field Documentation
$sharedFolders
array $sharedFolders = null private inherited
All shared folders.
[
  'id' => ID,
  'mount_point' => MOUNT_POINT,
  'groups' => [
    GROUP_ID => [
      'displayName' => GROUP_ID
      'permissions' => PERMISSIONS,
      'type' => 'group',
      ...
    ],
  ],
  'quota' => -3,
  'size' => SIZE,
  'acl' => true/false,
  'manage' => [
     [ 'type' => 'group'/'user', 'id' => MANAGER_ID, 'displayname' => DISPLAY_NAME ]
  ]
]
Definition at line 83 of file GroupFoldersService.php.
DEFAULT_PERMISSIONS
const DEFAULT_PERMISSIONS = self::PERMISSION_ALL inherited
Definition at line 53 of file GroupFoldersService.php.
GROUP_FOLDERS_APP
const GROUP_FOLDERS_APP = 'groupfolders' inherited
Definition at line 43 of file GroupFoldersService.php.
MANAGER_TYPE_GROUP
const MANAGER_TYPE_GROUP = 'group' inherited
Definition at line 55 of file GroupFoldersService.php.
MANAGER_TYPE_USER
const MANAGER_TYPE_USER = 'user' inherited
Definition at line 56 of file GroupFoldersService.php.
PERMISSION_ALL
const PERMISSION_ALL = Constants::PERMISSION_ALL inherited
Definition at line 52 of file GroupFoldersService.php.
PERMISSION_DELETE
const PERMISSION_DELETE = Constants::PERMISSION_READ|Constants::PERMISSION_DELETE inherited
Definition at line 50 of file GroupFoldersService.php.
PERMISSION_READ
const PERMISSION_READ = Constants::PERMISSION_READ inherited
Definition at line 49 of file GroupFoldersService.php.
PERMISSION_SHARE
const PERMISSION_SHARE = Constants::PERMISSION_READ|Constants::PERMISSION_SHARE inherited
Definition at line 51 of file GroupFoldersService.php.
PERMISSION_WRITE
const PERMISSION_WRITE = Constants::PERMISSION_READ|Constants::PERMISSION_UPDATE|Constants::PERMISSION_CREATE inherited
Definition at line 48 of file GroupFoldersService.php.
SEARCH_TOPIC_GROUP
const SEARCH_TOPIC_GROUP = 'group' inherited
Definition at line 46 of file GroupFoldersService.php.
SEARCH_TOPIC_MOUNT
const SEARCH_TOPIC_MOUNT = 'mount' inherited
Definition at line 45 of file GroupFoldersService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/GroupFoldersService.php