CamerataDB: GroupFoldersService Class Reference
GroupFoldersService Class Reference
Mis-use the internal routes of the groupfolders app in order to automatically generate group-shared folder structures.
Public Member Functions
__construct (LoggerInterface $logger, RequestService $requestService, ?IL10N $l10n=null,)
setL10N (IL10N $l10n)
Set the localization to use.
getFolder (string $mountPoint, bool $reload=false)
Obtain the shared folder data for the given mount-point.
searchFolders (string $regexp, string $topic=self::SEARCH_TOPIC_MOUNT)
Return all shared folders matching the given regexp.
deleteFolders (string $mountRegexp)
getFolderById (int $id)
createFolder (string $mountPoint, array $groups, array $manager=[])
Create a shared folder and set appropriate permissions.
addGroupToFolder (string $mountPoint, string $groupId, int $permissions=self::DEFAULT_PERMISSIONS, bool $canManage=false,)
Add a single group to the given shared folder.
removeGroupFromFolder (string $mountPoint, string $groupId)
Remove a group from the given shared folder.
addManagerToFolder (string $mountPoint, string $managerId, string $managerType)
removeManagerFromFolder (string $mountPoint, string $managerId, string $managerType)
setGroupPermissions (string $mountPoint, string $groupId, int $permissions)
changeMountPoint (string $mountPoint, string $targetMountPoint, bool $moveChildren=true)
Change the given group-shared folder – given by its old mount-point – to a new mount-point.
Data Fields
const GROUP_FOLDERS_APP = 'groupfolders'
const SEARCH_TOPIC_MOUNT = 'mount'
const SEARCH_TOPIC_GROUP = 'group'
const PERMISSION_WRITE = Constants::PERMISSION_READ|Constants::PERMISSION_UPDATE|Constants::PERMISSION_CREATE
const PERMISSION_READ = Constants::PERMISSION_READ
const PERMISSION_DELETE = Constants::PERMISSION_READ|Constants::PERMISSION_DELETE
const PERMISSION_SHARE = Constants::PERMISSION_READ|Constants::PERMISSION_SHARE
const PERMISSION_ALL = Constants::PERMISSION_ALL
const DEFAULT_PERMISSIONS = self::PERMISSION_ALL
const MANAGER_TYPE_GROUP = 'group'
const MANAGER_TYPE_USER = 'user'
Private Member Functions
fetchFolders ()
Fetch and cache all shared folders from the groupfolders app.
ensureFolders (bool $reload=false)
changeFolderManager (string $mountPoint, string $managerId, string $type, bool $canManage)
Private Attributes
$l
$requestService
$sharedFolders = null
All shared folders.
Detailed Description
Mis-use the internal routes of the groupfolders app in order to automatically generate group-shared folder structures.
Definition at line 35 of file GroupFoldersService.php.
Constructor & Destructor Documentation
__construct()
__construct (LoggerInterface $logger, RequestService $requestService, ?IL10N $l10n = null)
Definition at line 83 of file GroupFoldersService.php.
Member Function Documentation
addGroupToFolder()
addGroupToFolder (string $mountPoint, string $groupId, int $permissions = self::DEFAULT_PERMISSIONS, bool $canManage = false)
Add a single group to the given shared folder.
This is a no-op if the group including matching permissions is already there.
Parameters
string $mountPoint
string $groupId
int $permissions
bool $canManage
Returns
void
Definition at line 282 of file GroupFoldersService.php.
Referenced by GroupFoldersService\createFolder().
addManagerToFolder()
addManagerToFolder (string $mountPoint, string $managerId, string $managerType)
Parameters
string $mountPoint
string $managerId
string $managerType
Returns
void
Definition at line 395 of file GroupFoldersService.php.
Referenced by GroupFoldersService\createFolder().
changeFolderManager()
changeFolderManager (string $mountPoint, string $managerId, string $type, bool $canManage) private
Parameters
string $mountPoint
string $managerId
string $type
bool $canManage
Returns
void
Definition at line 342 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logDebug().
changeMountPoint()
changeMountPoint (string $mountPoint, string $targetMountPoint, bool $moveChildren = true)
Change the given group-shared folder – given by its old mount-point – to a new mount-point.
Parameters
string $mountPoint The old mount-point which determines the group-shared folder to act upon.
string $targetMountPoint The destination mount-point. If the parent-directories of the destination mount-point do not exist then the shared folder will be hidden.
bool $moveChildren If true and the old mount-point appears as prefix in other group-shared folders then change their respective mount-points as well.
Returns
void
Definition at line 461 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logException().
createFolder()
createFolder (string $mountPoint, array $groups, array $manager = [])
Create a shared folder and set appropriate permissions.
Parameters
string $mountPoint Note the a nested mount-point will not create the parent folders.
array $groups Array $groupId => $groupPermissions
[ GROUP1_ID => PERMS1, GROUP2_ID => PERMS2 ]
```.
@param array $manager ID => TYPE
[ USER_ID => 'user', GROUP_ID => 'group' ] ```.
Returns
void
Definition at line 246 of file GroupFoldersService.php.
References GroupFoldersService\addGroupToFolder(), GroupFoldersService\addManagerToFolder(), GroupFoldersService\getFolder(), and GroupFoldersService\getFolderById().
deleteFolders()
deleteFolders (string $mountRegexp)
Parameters
string $mountRegexp
Returns
void
Definition at line 195 of file GroupFoldersService.php.
References GroupFoldersService\searchFolders().
ensureFolders()
ensureFolders (bool $reload = false) private
Parameters
bool $reload
Returns
void
Definition at line 129 of file GroupFoldersService.php.
References GroupFoldersService\fetchFolders().
Referenced by GroupFoldersService\getFolder().
fetchFolders()
fetchFolders () private
Fetch and cache all shared folders from the groupfolders app.
Returns
void
Definition at line 113 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\ensureFolders(), and GroupFoldersService\searchFolders().
getFolder()
getFolder (string $mountPoint, bool $reload = false)
Obtain the shared folder data for the given mount-point.
Parameters
string $mountPoint
bool $reload
Returns
null|array Return the data requested from the groupfolders app or null if the folder is not found.
Definition at line 146 of file GroupFoldersService.php.
References GroupFoldersService\ensureFolders(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\createFolder().
getFolderById()
getFolderById (int $id)
Parameters
int $id
Returns
array
Definition at line 210 of file GroupFoldersService.php.
References OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\createFolder().
removeGroupFromFolder()
removeGroupFromFolder (string $mountPoint, string $groupId)
Remove a group from the given shared folder.
Parameters
string $mountPoint
string $groupId
Returns
void
Definition at line 314 of file GroupFoldersService.php.
removeManagerFromFolder()
removeManagerFromFolder (string $mountPoint, string $managerId, string $managerType)
Parameters
string $mountPoint
string $managerId
string $managerType
Returns
void
Definition at line 409 of file GroupFoldersService.php.
searchFolders()
searchFolders (string $regexp, string $topic = self::SEARCH_TOPIC_MOUNT)
Return all shared folders matching the given regexp.
Parameters
string $regexp
string $topic
Returns
array
Definition at line 162 of file GroupFoldersService.php.
References GroupFoldersService\fetchFolders(), and OCA\CAFEVDB\Toolkit\Traits\logDebug().
Referenced by GroupFoldersService\deleteFolders().
setGroupPermissions()
setGroupPermissions (string $mountPoint, string $groupId, int $permissions)
Parameters
string $mountPoint
string $groupId
int $permissions
Returns
void
Definition at line 423 of file GroupFoldersService.php.
setL10N()
setL10N (IL10N $l10n)
Set the localization to use.
Parameters
IL10N $l10n
Returns
RequestService $this.
Definition at line 101 of file GroupFoldersService.php.
Field Documentation
$l
IL10N $l private
Definition at line 55 of file GroupFoldersService.php.
$requestService
RequestService $requestService private
Definition at line 58 of file GroupFoldersService.php.
$sharedFolders
array $sharedFolders = null private
All shared folders.
[
  'id' => ID,
  'mount_point' => MOUNT_POINT,
  'groups' => [
    GROUP_ID => PERMISSIONS,
  ],
  'quota' => -3,
  'size' => SIZE,
  'acl' => true/false,
  'manage' => [
     [ 'type' => 'group'/'user', 'id' => MANAGER_ID, 'displayname' => DISPLAY_NAME ]
  ]
]
Definition at line 80 of file GroupFoldersService.php.
DEFAULT_PERMISSIONS
const DEFAULT_PERMISSIONS = self::PERMISSION_ALL
Definition at line 49 of file GroupFoldersService.php.
GROUP_FOLDERS_APP
const GROUP_FOLDERS_APP = 'groupfolders'
Definition at line 39 of file GroupFoldersService.php.
MANAGER_TYPE_GROUP
const MANAGER_TYPE_GROUP = 'group'
Definition at line 51 of file GroupFoldersService.php.
MANAGER_TYPE_USER
const MANAGER_TYPE_USER = 'user'
Definition at line 52 of file GroupFoldersService.php.
PERMISSION_ALL
const PERMISSION_ALL = Constants::PERMISSION_ALL
Definition at line 48 of file GroupFoldersService.php.
PERMISSION_DELETE
const PERMISSION_DELETE = Constants::PERMISSION_READ|Constants::PERMISSION_DELETE
Definition at line 46 of file GroupFoldersService.php.
PERMISSION_READ
const PERMISSION_READ = Constants::PERMISSION_READ
Definition at line 45 of file GroupFoldersService.php.
PERMISSION_SHARE
const PERMISSION_SHARE = Constants::PERMISSION_READ|Constants::PERMISSION_SHARE
Definition at line 47 of file GroupFoldersService.php.
PERMISSION_WRITE
const PERMISSION_WRITE = Constants::PERMISSION_READ|Constants::PERMISSION_UPDATE|Constants::PERMISSION_CREATE
Definition at line 44 of file GroupFoldersService.php.
SEARCH_TOPIC_GROUP
const SEARCH_TOPIC_GROUP = 'group'
Definition at line 42 of file GroupFoldersService.php.
SEARCH_TOPIC_MOUNT
const SEARCH_TOPIC_MOUNT = 'mount'
Definition at line 41 of file GroupFoldersService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Toolkit/Service/GroupFoldersService.php