CamerataDB: EncryptionService Class Reference
EncryptionService Class Reference
Handle some encryption tasks:
Public Member Functions
__construct (string $appName, AuthorizationService $authorization, IConfig $containerConfig, IUserSession $userSession, Crypto\AsymmetricKeyService $asymKeyService, Crypto\CryptoFactoryInterface $cryptoFactory, IHasher $hasher, ICredentialsStore $credentialsStore, IEventDispatcher $eventDispatcher, ILogger $logger, IL10N $l10n,)
{}
bind (string $userId, string $password)
Bind $this to the given userId and password, for instance during listeners for password-change etc.
bound ()
Test if we a bound to a user.
getUserId ()
getAppEncryptionKey ()
setAppEncryptionKey (?string $key)
getAppCryptor ()
getAppAsymmetricCryptor ()
initUserKeyPair (bool $forceNewKeyPair=false)
Initialize the per-user public/private key pair, which inparticular is used to propagate the app's encryption key to all relevant users.
initAppKeyPair (bool $forceNewKeyPair=false)
restoreAppKeyPair ()
Restore a potential backup e.g.
deleteUserKeyPair (string $userId)
Remove the SSL key-pair for the given login.
getUserEncryptionKey ()
setUserEncryptionKey (?string $key, ?string $userId=null)
Set the encryption key for the current or the given user.
initAppEncryptionKey ()
Initialize the global symmetric app encryption key used to encrypt shared data.
getSharedPrivateValue (string $key, mixed $default=null)
Get and decrypt an personal 'user' value encrypted with the public key of key-pair.
setSharedPrivateValue (string $key, mixed $value, ?string $userId=null)
Encrypt the given value with the user's public key.
encryptionKeyValid (?string $encryptionKey=null)
Check the validity of the encryption key.
getAppValue (string $key, mixed $default=null)
A short-cut, redirecting to the stock functions for the app.
setAppValue (string $key, mixed $value)
A short-cut, redirecting to the stock functions for the app.
getUserValue (string $userId, string $key, mixed $default=null)
setUserValue (string $userId, string $key, mixed $value)
deleteUserValue (string $userId, string $key)
getConfigValue (string $key, mixed $default=null, bool $ignoreLock=false)
Fetch the value for the given key and possibly decrypt it.
setConfigValue (string $key, mixed $value, bool $ignoreLock=false)
Encrypt the given value and store it in the application settings table of the Cloud.
verifyHash (?string $value, $hash)
computeHash (string $value)
Data Fields
const PUBLIC_ENCRYPTION_KEY = Crypto\AsymmetricKeyService::PUBLIC_ENCRYPTION_KEY_CONFIG
const PRIVATE_ENCRYPTION_KEY = Crypto\AsymmetricKeyService::PRIVATE_ENCRYPTION_KEY_CONFIG
const USER_ENCRYPTION_KEY_KEY = 'encryptionkey'
const APP_ENCRYPTION_KEY_HASH_KEY = 'encryptionkeyhash'
const CONFIG_LOCK_KEY = 'configlock'
const NEVER_ENCRYPT
const SHARED_PRIVATE_VALUES
Private Attributes
$appName
$containerConfig
$hasher
$eventDispatcher
$asymKeyService
$appCryptor
$appAsymmetricCryptor
$userId = null
$userPassword = null
$userAsymmetricCryptor
Detailed Description
Handle some encryption tasks:
shared encryption key
encrypted app config values with the shared encryption key
encrypted per-user config values where needed
asymmetric encryption for per-user encryption key
We only support the case where the password is available through the credential store of the emedding cloud instance.
Todo:
One could cache the decrypted configuration values given that encryption may be costly.
Definition at line 75 of file EncryptionService.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, AuthorizationService $authorization, IConfig $containerConfig, IUserSession $userSession, Crypto\AsymmetricKeyService $asymKeyService, Crypto\CryptoFactoryInterface $cryptoFactory, IHasher $hasher, ICredentialsStore $credentialsStore, IEventDispatcher $eventDispatcher, ILogger $logger, IL10N $l10n)
{}
Definition at line 135 of file EncryptionService.php.
References AuthorizationService\authorized(), and EncryptionService\bind().
Member Function Documentation
bind()
bind (string $userId, string $password)
Bind $this to the given userId and password, for instance during listeners for password-change etc.
Parameters
string $userId User id to bind.
string $password Userpassword for binding.
Returns
void
Definition at line 191 of file EncryptionService.php.
References EncryptionService\initAppEncryptionKey(), EncryptionService\initAppKeyPair(), and EncryptionService\initUserKeyPair().
Referenced by EncryptionService\__construct().
bound()
bound ()
Test if we a bound to a user.
Returns
bool
Definition at line 207 of file EncryptionService.php.
Referenced by EncryptionService\encryptionKeyValid(), EncryptionService\getUserId(), EncryptionService\initAppEncryptionKey(), and EncryptionService\setSharedPrivateValue().
computeHash()
computeHash (string $value)
Parameters
string $value The value to hash.
Returns
string The hash of $value.
Definition at line 675 of file EncryptionService.php.
deleteUserKeyPair()
deleteUserKeyPair (string $userId)
Remove the SSL key-pair for the given login.
This is needed if an administrator changes the password. This will make all other encrypted data unavailable, so as a side-effect all encrypted data is removed.
Parameters
string $userId
Returns
void
Definition at line 355 of file EncryptionService.php.
deleteUserValue()
deleteUserValue (string $userId, string $key)
Parameters
string $userId Use the current user if null.
string $key Config key.
Returns
mixed
Definition at line 574 of file EncryptionService.php.
encryptionKeyValid()
encryptionKeyValid (?string $encryptionKey = null)
Check the validity of the encryption key.
In order to do so we fetch an encrypted representation of the key from the OC config space and try to decrypt that key with the given key. If the decrypted key matches our key, then we accept the key.
Parameters
null | string $encryptionKey Key to check.
Returns
bool
Exceptions
Exceptions
\EncryptionKeyException
Definition at line 476 of file EncryptionService.php.
References EncryptionService\bound(), EncryptionService\getConfigValue(), and EncryptionService\verifyHash().
getAppAsymmetricCryptor()
getAppAsymmetricCryptor ()
Returns
null|Crypto\AsymmetricCryptorInterface
Definition at line 248 of file EncryptionService.php.
getAppCryptor()
getAppCryptor ()
Returns
Crypto\ICryptor
Definition at line 240 of file EncryptionService.php.
getAppEncryptionKey()
getAppEncryptionKey ()
Returns
string App encryption key
Definition at line 223 of file EncryptionService.php.
Referenced by EncryptionService\initAppKeyPair(), and EncryptionService\restoreAppKeyPair().
getAppValue()
getAppValue (string $key, mixed $default = null)
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $default Default value.
Returns
mixed
Definition at line 520 of file EncryptionService.php.
Referenced by EncryptionService\getConfigValue(), EncryptionService\initAppKeyPair(), EncryptionService\restoreAppKeyPair(), and EncryptionService\setConfigValue().
getConfigValue()
getConfigValue (string $key, mixed $default = null, bool $ignoreLock = false)
Fetch the value for the given key and possibly decrypt it.
Parameters
string $key
mixed $default
bool $ignoreLock
Returns
mixed
Exceptions
Exceptions
\ConfigLockedException
Definition at line 592 of file EncryptionService.php.
References EncryptionService\getAppValue().
Referenced by EncryptionService\encryptionKeyValid(), and EncryptionService\initAppEncryptionKey().
getSharedPrivateValue()
getSharedPrivateValue (string $key, mixed $default = null)
Get and decrypt an personal 'user' value encrypted with the public key of key-pair.
Throw an exception if $this is not bound to a user and password, see self::bind().
Parameters
string $key Config key.
mixed $default Default value.
Returns
string Decrypted config value.
Exceptions
Exceptions
\EncryptionKeyException
Definition at line 432 of file EncryptionService.php.
Referenced by EncryptionService\getUserEncryptionKey().
getUserEncryptionKey()
getUserEncryptionKey ()
Returns
null|string
Definition at line 362 of file EncryptionService.php.
References EncryptionService\getSharedPrivateValue().
Referenced by EncryptionService\initAppEncryptionKey(), and EncryptionService\initUserKeyPair().
getUserId()
getUserId ()
Returns
null|string Bound user id if any.
Definition at line 217 of file EncryptionService.php.
References EncryptionService\bound().
getUserValue()
getUserValue (string $userId, string $key, mixed $default = null)
Parameters
string $userId Use the current user if null.
string $key Config key.
mixed $default Default value.
Returns
mixed
Definition at line 548 of file EncryptionService.php.
initAppEncryptionKey()
initAppEncryptionKey ()
Initialize the global symmetric app encryption key used to encrypt shared data.
Returns
bool \true on success.
Exceptions
Exceptions
\EncryptionKeyException
Definition at line 390 of file EncryptionService.php.
References EncryptionService\bound(), EncryptionService\getConfigValue(), EncryptionService\getUserEncryptionKey(), and EncryptionService\verifyHash().
Referenced by EncryptionService\bind().
initAppKeyPair()
initAppKeyPair (bool $forceNewKeyPair = false)
Parameters
bool $forceNewKeyPair Whether to force regeneration.
Returns
void
Definition at line 298 of file EncryptionService.php.
References EncryptionService\getAppEncryptionKey(), and EncryptionService\getAppValue().
Referenced by EncryptionService\bind(), and EncryptionService\restoreAppKeyPair().
initUserKeyPair()
initUserKeyPair (bool $forceNewKeyPair = false)
Initialize the per-user public/private key pair, which inparticular is used to propagate the app's encryption key to all relevant users.
Parameters
bool $forceNewKeyPair Generate a new key pair even if an old one is found.
Returns
void
Exceptions
Exceptions
\EncryptionKeyException
Definition at line 265 of file EncryptionService.php.
References EncryptionService\getUserEncryptionKey().
Referenced by EncryptionService\bind().
restoreAppKeyPair()
restoreAppKeyPair ()
Restore a potential backup e.g.
after recryption failure.
Returns
void
Definition at line 331 of file EncryptionService.php.
References EncryptionService\getAppEncryptionKey(), EncryptionService\getAppValue(), and EncryptionService\initAppKeyPair().
setAppEncryptionKey()
setAppEncryptionKey (?string $key)
Parameters
null | string $key Install the given encryption key for the app.
Returns
void
Definition at line 233 of file EncryptionService.php.
setAppValue()
setAppValue (string $key, mixed $value)
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $value Value to set.
Returns
mixed
Definition at line 534 of file EncryptionService.php.
Referenced by EncryptionService\setConfigValue().
setConfigValue()
setConfigValue (string $key, mixed $value, bool $ignoreLock = false)
Encrypt the given value and store it in the application settings table of the Cloud.
Parameters
string $key Configuration key.
mixed $value Configuration value.
bool $ignoreLock
Returns
bool
Exceptions
Exceptions
\ConfigLockedException
Definition at line 634 of file EncryptionService.php.
References EncryptionService\getAppValue(), and EncryptionService\setAppValue().
setSharedPrivateValue()
setSharedPrivateValue (string $key, mixed $value, ?string $userId = null)
Encrypt the given value with the user's public key.
Parameters
string $key Configuration key.
mixed $value Value to be encrypted. Must be convertible to string.
null | string $userId Potentitally different than logged in user id.
Returns
void
Exceptions
Exceptions
\EncryptionKeyException
Exceptions
Exceptions
\EncryptionFailedException
Definition at line 453 of file EncryptionService.php.
References EncryptionService\bound().
Referenced by EncryptionService\setUserEncryptionKey().
setUserEncryptionKey()
setUserEncryptionKey (?string $key, ?string $userId = null)
Set the encryption key for the current or the given user.
Parameters
null | string $key Encryption key.
null | string $userId A potentially different than the currently logged in user.
Returns
void
Definition at line 377 of file EncryptionService.php.
References EncryptionService\setSharedPrivateValue().
setUserValue()
setUserValue (string $userId, string $key, mixed $value)
Parameters
string $userId Use the current user if null.
string $key Config key.
mixed $value Value to set.
Returns
mixed
Definition at line 562 of file EncryptionService.php.
verifyHash()
verifyHash (?string $value, $hash)
Parameters
null | string $value Value to verify.
null | string $hash Hash to verify against.
Returns
bool \true if either hash or value are empty or if the hash could be verified.
Definition at line 665 of file EncryptionService.php.
Referenced by EncryptionService\encryptionKeyValid(), and EncryptionService\initAppEncryptionKey().
Field Documentation
$appAsymmetricCryptor
Crypto AsymmetricCryptorInterface $appAsymmetricCryptor private
Definition at line 123 of file EncryptionService.php.
$appCryptor
Crypto CloudSymmetricCryptor $appCryptor private
Definition at line 120 of file EncryptionService.php.
$appName
string $appName private
Definition at line 105 of file EncryptionService.php.
$asymKeyService
Crypto AsymmetricKeyService $asymKeyService private
Definition at line 117 of file EncryptionService.php.
$containerConfig
IConfig $containerConfig private
Definition at line 108 of file EncryptionService.php.
$eventDispatcher
IEventDispatcher $eventDispatcher private
Definition at line 114 of file EncryptionService.php.
$hasher
IHasher $hasher private
Definition at line 111 of file EncryptionService.php.
$userAsymmetricCryptor
Crypto AsymmetricCryptorInterface $userAsymmetricCryptor private
Definition at line 132 of file EncryptionService.php.
$userId
string $userId = null private
Definition at line 126 of file EncryptionService.php.
$userPassword
string $userPassword = null private
Definition at line 129 of file EncryptionService.php.
APP_ENCRYPTION_KEY_HASH_KEY
const APP_ENCRYPTION_KEY_HASH_KEY = 'encryptionkeyhash'
Definition at line 83 of file EncryptionService.php.
CONFIG_LOCK_KEY
const CONFIG_LOCK_KEY = 'configlock'
Definition at line 85 of file EncryptionService.php.
NEVER_ENCRYPT
const NEVER_ENCRYPT
Initial value:
= [
    'enabled',
    'installed_version',
    'types',
    'usergroup',
    'wikinamespace',
    'cspfailuretoken',
    'configlock',
    'orchestra',
    'orchestraLocale',
    self::APP_ENCRYPTION_KEY_HASH_KEY,
  ]
Definition at line 87 of file EncryptionService.php.
PRIVATE_ENCRYPTION_KEY
const PRIVATE_ENCRYPTION_KEY = Crypto\AsymmetricKeyService::PRIVATE_ENCRYPTION_KEY_CONFIG
Definition at line 80 of file EncryptionService.php.
PUBLIC_ENCRYPTION_KEY
const PUBLIC_ENCRYPTION_KEY = Crypto\AsymmetricKeyService::PUBLIC_ENCRYPTION_KEY_CONFIG
Definition at line 79 of file EncryptionService.php.
SHARED_PRIVATE_VALUES
const SHARED_PRIVATE_VALUES
Initial value:
= [
    self::USER_ENCRYPTION_KEY_KEY,
  ]
Definition at line 100 of file EncryptionService.php.
USER_ENCRYPTION_KEY_KEY
const USER_ENCRYPTION_KEY_KEY = 'encryptionkey'
Definition at line 82 of file EncryptionService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/EncryptionService.php