CamerataDB: UndoableTextFileUpdate Class Reference
UndoableTextFileUpdate Class Reference
Update the content of the given text-file with the given content.
Public Member Functions
__construct (mixed $name, ?string $content, ?string $replacableContent=null, bool $gracefully=false, bool $mkdir=true)
initialize (IAppContainer $appContainer)
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
undo ()
{Undo that what was done by do().
Returns
void
}
reset ()
{Reset initial state.
Returns
void
}
do ()
Do something.
Protected Member Functions
renamedName (string $path)
Create a new unique name for renaming.
Static Protected Member Functions
static normalizePath (string $path)
Remove multipled slashes.
Protected Attributes
$dateTimeFormatter
$name
$content
The content to inject into the text-file.
$replacableContent
Optional content which is ok to replace.
$renamedName
$oldContent
$nothingToUndo
$gracefully
$mkdir
$l
$timeFactory
$userStorage
$appContainer
Detailed Description
Update the content of the given text-file with the given content.
The file is created if it does not exist.
@SuppressWarnings(PHPMD.ShortMethodName)
Definition at line 46 of file UndoableTextFileUpdate.php.
Constructor & Destructor Documentation
__construct()
__construct (mixed $name, ?string $content, ?string $replacableContent = null, bool $gracefully = false, bool $mkdir = true)
Parameters
string | callable $name
null | string $content Content to place into the text-file.
string | null $replacableContent Optional old known content from a previous run which is then simply replaced.
bool $gracefully Do not throw if folder already exists.
bool $mkdir Whether or not to create missing parent directories. However, even if set to \false a regular file which is in the way will be removed.
Definition at line 97 of file UndoableTextFileUpdate.php.
References UndoableTextFileUpdate\$content, UndoableTextFileUpdate\$replacableContent, and UndoableTextFileUpdate\reset().
Member Function Documentation
do()
do () inherited
Do something.
Returns
void
Implemented in GenericUndoable, UndoableFileRename, and UndoableFileReplace.
initialize()
initialize (IAppContainer $appContainer)
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
Reimplemented from AbstractFileSystemUndoable.
Definition at line 108 of file UndoableTextFileUpdate.php.
normalizePath()
static normalizePath (string $path) static protected inherited
Remove multipled slashes.
Parameters
string $path
Returns
string
Definition at line 65 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFileRename\do(), and UndoableFileReplace\do().
renamedName()
renamedName (string $path) protected inherited
Create a new unique name for renaming.
Parameters
string $path
Returns
string
Definition at line 79 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFolderCreate\reset(), UndoableTextFileUpdate\reset(), UndoableFolderCreate\undo(), and UndoableTextFileUpdate\undo().
reset()
reset ()
{Reset initial state.
Returns
void
}
Implements IUndoable.
Definition at line 219 of file UndoableTextFileUpdate.php.
References AbstractFileSystemUndoable\renamedName().
Referenced by UndoableTextFileUpdate\__construct().
undo()
undo ()
{Undo that what was done by do().
Returns
void
}
Implements IUndoable.
Definition at line 203 of file UndoableTextFileUpdate.php.
References AbstractFileSystemUndoable\renamedName().
Field Documentation
$appContainer
IAppContainer $appContainer protected inherited
Definition at line 33 of file AbstractUndoable.php.
$content
string $content protected
The content to inject into the text-file.
Definition at line 60 of file UndoableTextFileUpdate.php.
Referenced by UndoableTextFileUpdate\__construct().
$dateTimeFormatter
IDateTimeFormatter $dateTimeFormatter protected
Definition at line 51 of file UndoableTextFileUpdate.php.
$gracefully
bool $gracefully protected
Definition at line 78 of file UndoableTextFileUpdate.php.
$l
IL10N $l protected inherited
Definition at line 40 of file AbstractFileSystemUndoable.php.
$mkdir
bool $mkdir protected
Definition at line 81 of file UndoableTextFileUpdate.php.
$name
string callable $name protected
Definition at line 54 of file UndoableTextFileUpdate.php.
$nothingToUndo
bool $nothingToUndo protected
Definition at line 75 of file UndoableTextFileUpdate.php.
$oldContent
string $oldContent protected
Definition at line 72 of file UndoableTextFileUpdate.php.
$renamedName
string $renamedName protected
Definition at line 69 of file UndoableTextFileUpdate.php.
$replacableContent
string $replacableContent protected
Optional content which is ok to replace.
Definition at line 66 of file UndoableTextFileUpdate.php.
Referenced by UndoableTextFileUpdate\__construct().
$timeFactory
ITimeFactory $timeFactory protected inherited
Definition at line 43 of file AbstractFileSystemUndoable.php.
$userStorage
UserStorage $userStorage protected inherited
Definition at line 46 of file AbstractFileSystemUndoable.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/UndoableTextFileUpdate.php