CamerataDB: ProjectParticipantEntityListener Class Reference
ProjectParticipantEntityListener Class Reference
Entity listener for project participation.
Public Member Functions
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager,)
preUpdate (Entity $entity, ORMEvent\PreUpdateEventArgs $event)
{}
postUpdate (Entity $entity, ORMEvent\PostUpdateEventArgs $eventArgs)
{}
postPersist (Entity $entity, ORMEvent\PostPersistEventArgs $eventArgs)
{}
postRemove (Entity $entity, ORMEvent\PostRemoveEventArgs $eventArgs)
{}
Protected Attributes
$preCommitActions
IGroupManager $groupManager
IUserManager $userManager
Static Private Member Functions
static entityId (string|Entity $entity, ?string $suffix)
Generate a flattened id for the purpose of indexing PHP arrays.
Private Attributes
const ID_SEP = ':'
array $preUpdateValues = []
Array of the pre-update values, indexed by project- and musician-id.
Detailed Description
Entity listener for project participation.
fire a cloud event if the registration value changes
fire a cloud event if an entity is created, deleted, disabled
Definition at line 53 of file ProjectParticipantEntityListener.php.
Constructor & Destructor Documentation
__construct()
__construct (protected ILogger $logger, protected IAppContainer $appContainer, protected EntityManager $entityManager)
Definition at line 77 of file ProjectParticipantEntityListener.php.
Member Function Documentation
entityId()
static entityId (string|Entity $entity, ?string $suffix) static private
Generate a flattened id for the purpose of indexing PHP arrays.
Parameters
string | Entity $entity
null | string $suffix Additional string to append.
Returns
string
Definition at line 252 of file ProjectParticipantEntityListener.php.
Referenced by ProjectParticipantEntityListener\postUpdate(), and ProjectParticipantEntityListener\preUpdate().
postPersist()
postPersist (Entity $entity, ORMEvent\PostPersistEventArgs $eventArgs)
{}
Definition at line 132 of file ProjectParticipantEntityListener.php.
postRemove()
postRemove (Entity $entity, ORMEvent\PostRemoveEventArgs $eventArgs)
{}
Definition at line 144 of file ProjectParticipantEntityListener.php.
postUpdate()
postUpdate (Entity $entity, ORMEvent\PostUpdateEventArgs $eventArgs)
{}
Definition at line 108 of file ProjectParticipantEntityListener.php.
References ProjectParticipantEntityListener\entityId().
preUpdate()
preUpdate (Entity $entity, ORMEvent\PreUpdateEventArgs $event)
{}
Definition at line 88 of file ProjectParticipantEntityListener.php.
References ProjectParticipantEntityListener\entityId().
Field Documentation
$groupManager
IGroupManager $groupManager protected
Definition at line 71 of file ProjectParticipantEntityListener.php.
$preCommitActions
IUndoable[] $preCommitActions protected
Definition at line 68 of file ProjectParticipantEntityListener.php.
$preUpdateValues
array $preUpdateValues = [] private
Array of the pre-update values, indexed by project- and musician-id.
Currently we only need the pre-update value of the registration member.
Definition at line 65 of file ProjectParticipantEntityListener.php.
$userManager
IUserManager $userManager protected
Definition at line 74 of file ProjectParticipantEntityListener.php.
ID_SEP
const ID_SEP = ':' private
Definition at line 57 of file ProjectParticipantEntityListener.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Listener/ProjectParticipantEntityListener.php