CamerataDB: UndoableFolderRemove Class Reference
UndoableFolderRemove Class Reference
Remove the given node, which must be a folder.
Public Member Functions
__construct (mixed $name, bool $gracefully=false, bool $recursively=false, string $ignoredFiles='/^[0-9] *-?README(.*) $/i')
Undoable folder remove.
initialize (IAppContainer $appContainer)
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
undo ()
{Undo that what was done by do().
Returns
void
}
reset ()
{Reset initial state.
Returns
void
}
do ()
Do something.
Protected Member Functions
renamedName (string $path)
Create a new unique name for renaming.
Static Protected Member Functions
static normalizePath (string $path)
Remove multipled slashes.
Protected Attributes
$name
$ignoredFiles
$gracefully
$recursively
$nodeType
$nothingToUndo
$doneInterval
$l
$timeFactory
$userStorage
$appContainer
Detailed Description
Remove the given node, which must be a folder.
Definition at line 37 of file UndoableFolderRemove.php.
Constructor & Destructor Documentation
__construct()
__construct (mixed $name, bool $gracefully = false, bool $recursively = false, string $ignoredFiles = '/^[0-9]*-?README(.*)$/i')
Undoable folder remove.
Parameters
string | callable $name
bool $gracefully Do not complain if folders are non-empty or do not exist.
bool $recursively Recursively remove folders. If not set only non-empty folders will be removed.
string $ignoredFiles A regular expression masking out ignored files by their name in the decision whether a directory is empty or not. It defaults to ignoring all variants of README.
Definition at line 53 of file UndoableFolderRemove.php.
Member Function Documentation
do()
do () inherited
Do something.
Returns
void
Implemented in GenericUndoable, UndoableFileRename, and UndoableFileReplace.
initialize()
initialize (IAppContainer $appContainer) inherited
{{{Lazy initialization in order to have a more lightweight constructor for the actions and to inject the app-container if it is needed.
Parameters
IAppContainer $appContainer
Returns
void
}}}
Reimplemented from AbstractFileSystemUndoable.
Definition at line 90 of file UndoableFileSystemNodeRemove.php.
normalizePath()
static normalizePath (string $path) static protected inherited
Remove multipled slashes.
Parameters
string $path
Returns
string
Definition at line 65 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFileRename\do(), and UndoableFileReplace\do().
renamedName()
renamedName (string $path) protected inherited
Create a new unique name for renaming.
Parameters
string $path
Returns
string
Definition at line 79 of file AbstractFileSystemUndoable.php.
Referenced by UndoableFolderCreate\reset(), UndoableTextFileUpdate\reset(), UndoableFolderCreate\undo(), and UndoableTextFileUpdate\undo().
reset()
reset () inherited
{Reset initial state.
Returns
void
}
Implements IUndoable.
Definition at line 162 of file UndoableFileSystemNodeRemove.php.
Referenced by UndoableFileSystemNodeRemove\__construct().
undo()
undo () inherited
{Undo that what was done by do().
Returns
void
}
Implements IUndoable.
Definition at line 153 of file UndoableFileSystemNodeRemove.php.
Field Documentation
$appContainer
IAppContainer $appContainer protected inherited
Definition at line 33 of file AbstractUndoable.php.
$doneInterval
array< int, int > $doneInterval protected inherited
Definition at line 60 of file UndoableFileSystemNodeRemove.php.
$gracefully
bool $gracefully protected inherited
Definition at line 48 of file UndoableFileSystemNodeRemove.php.
$ignoredFiles
string $ignoredFiles protected inherited
Definition at line 45 of file UndoableFileSystemNodeRemove.php.
$l
IL10N $l protected inherited
Definition at line 40 of file AbstractFileSystemUndoable.php.
$name
callable $name protected inherited
Definition at line 42 of file UndoableFileSystemNodeRemove.php.
$nodeType
null string $nodeType protected inherited
Definition at line 54 of file UndoableFileSystemNodeRemove.php.
$nothingToUndo
bool $nothingToUndo protected inherited
Definition at line 57 of file UndoableFileSystemNodeRemove.php.
$recursively
bool $recursively protected inherited
Definition at line 51 of file UndoableFileSystemNodeRemove.php.
$timeFactory
ITimeFactory $timeFactory protected inherited
Definition at line 43 of file AbstractFileSystemUndoable.php.
$userStorage
UserStorage $userStorage protected inherited
Definition at line 46 of file AbstractFileSystemUndoable.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/UndoableFolderRemove.php