CamerataDB: ReservedWordQuoteStrategy Class Reference
ReservedWordQuoteStrategy Class Reference
A set of rules for determining the physical column, alias and table quotes.
Public Member Functions
getColumnName ($fieldName, ClassMetadata $class, AbstractPlatform $platform)
{}
getTableName (ClassMetadata $class, AbstractPlatform $platform)
{}
getSequenceName (array $definition, ClassMetadata $class, AbstractPlatform $platform)
{}
getJoinColumnName (array $joinColumn, ClassMetadata $class, AbstractPlatform $platform)
{}
getReferencedJoinColumnName (array $joinColumn, ClassMetadata $class, AbstractPlatform $platform)
{}
getJoinTableName (array $association, ClassMetadata $class, AbstractPlatform $platform)
{}
getIdentifierColumnNames (ClassMetadata $class, AbstractPlatform $platform)
{}
getColumnAlias ($columnName, $counter, AbstractPlatform $platform, ClassMetadata $class=null)
{}
Private Member Functions
getQuotedName (AbstractPlatform $platform, $name, $force=false)
Detailed Description
A set of rules for determining the physical column, alias and table quotes.
Since
2.6
Author
Maximilian Ruta mr@xt.nosp@m.ain..nosp@m.net
Definition at line 33 of file ReservedWordQuoteStrategy.php.
Member Function Documentation
getColumnAlias()
getColumnAlias ($columnName, $counter, AbstractPlatform $platform, ClassMetadata $class = null)
{}
Definition at line 188 of file ReservedWordQuoteStrategy.php.
getColumnName()
getColumnName ($fieldName, ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 59 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
Referenced by ReservedWordQuoteStrategy\getIdentifierColumnNames().
getIdentifierColumnNames()
getIdentifierColumnNames (ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 153 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getColumnName().
getJoinColumnName()
getJoinColumnName (array $joinColumn, ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 107 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
getJoinTableName()
getJoinTableName (array $association, ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 131 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
getQuotedName()
getQuotedName (AbstractPlatform $platform, $name, $force = false) private
Parameters
AbstractPlatform $platform
string $name
bool $force
Returns
string
Exceptions
\OCA\CAFEVDB\Wrapped\Doctrine\DBAL\DBALException
Definition at line 43 of file ReservedWordQuoteStrategy.php.
Referenced by ReservedWordQuoteStrategy\getColumnName(), ReservedWordQuoteStrategy\getJoinColumnName(), ReservedWordQuoteStrategy\getJoinTableName(), ReservedWordQuoteStrategy\getReferencedJoinColumnName(), ReservedWordQuoteStrategy\getSequenceName(), and ReservedWordQuoteStrategy\getTableName().
getReferencedJoinColumnName()
getReferencedJoinColumnName (array $joinColumn, ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 119 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
getSequenceName()
getSequenceName (array $definition, ClassMetadata $class, AbstractPlatform $platform)
{}
Definition at line 95 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
getTableName()
getTableName (ClassMetadata $class, AbstractPlatform $platform)
{}
Todo:
Table names should be computed in DBAL depending on the platform
Definition at line 73 of file ReservedWordQuoteStrategy.php.
References ReservedWordQuoteStrategy\getQuotedName().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Mapping/ReservedWordQuoteStrategy.php