CamerataDB: ClassMetadataDecorator Class Reference
ClassMetadataDecorator Class Reference
Counter part to the decorated entity manager.
Public Member Functions
__construct (ClassMetadata $metaData, EntityManager $entityManager, ILogger $logger, IL10N $l10n,)
{}
getName ()
{}
getIdentifier ()
{}
getReflectionClass ()
{}
isIdentifier ($fieldName)
{}
hasField ($fieldName)
{}
hasAssociation ($fieldName)
{}
isSingleValuedAssociation ($fieldName)
{}
isCollectionValuedAssociation ($fieldName)
{}
getFieldNames ()
{}
getIdentifierFieldNames ()
{}
getAssociationNames ()
{}
getTypeOfField ($fieldName)
{}
getAssociationTargetClass ($assocName)
{}
isAssociationInverseSide ($assocName)
{}
getAssociationMappedByTargetField ($assocName)
{}
getIdentifierValues ($object)
{}
__call ($method, $args)
{}
__get ($property)
{}
__set ($property, $value)
{}
extractKeyValues (array $columnValues, bool $ignoreMissing=false)
Generate ids for use with find and self::persist() from database column values.
setColumnValue (mixed $entity, string $column, mixed $value)
getColumnValue (mixed $entity, string $column)
Fetch the value of a column, recursing into associations.
identifierColumns ()
Compute the mapping between entity-properties ("field-name") and plain SQL column-names.
Private Member Functions
debug (string $message, array $context=[], bool $showTrace=false)
updateInverseSide (object $entity, array $association, object $targetEntity, ClassMetadataInterface $targetMeta,)
Update the inverse side of an association after auto-installing $targetEntity into $entity (the owning side).
columnAssociations ()
Compute a mapping which includes also hidden columns which are introduced through associations.
doSetFieldValue (mixed $meta, mixed $entity, string $field, mixed $value)
Private Attributes
$columnAssociationsCache = []
$temporaryColumnStorage = []
$entityManager
$metaData
$l
$debug = false
Detailed Description
Counter part to the decorated entity manager.
Definition at line 46 of file ClassMetadataDecorator.php.
Constructor & Destructor Documentation
__construct()
__construct (ClassMetadata $metaData, EntityManager $entityManager, ILogger $logger, IL10N $l10n)
{}
Definition at line 69 of file ClassMetadataDecorator.php.
Member Function Documentation
__call()
__call ($method, $args)
{}
Definition at line 202 of file ClassMetadataDecorator.php.
__get()
__get ($property)
{}
Definition at line 213 of file ClassMetadataDecorator.php.
__set()
__set ($property, $value)
{}
Definition at line 222 of file ClassMetadataDecorator.php.
columnAssociations()
columnAssociations () private
Compute a mapping which includes also hidden columns which are introduced through associations.
The mapped field is then the first found association field which references the column.
Returns
array A flat mapping column-name => entity-property
Definition at line 413 of file ClassMetadataDecorator.php.
debug()
debug (string $message, array $context = [], bool $showTrace = false) private
Parameters
string $message Message to print.
array $context Log context.
bool $showTrace Whether to show a call-stack.
Returns
void
Definition at line 90 of file ClassMetadataDecorator.php.
References ClassMetadataDecorator\debug().
Referenced by ClassMetadataDecorator\debug(), and ClassMetadataDecorator\updateInverseSide().
doSetFieldValue()
doSetFieldValue (mixed $meta, mixed $entity, string $field, mixed $value) private
Parameters
mixed $meta
mixed $entity
string $field
mixed $value
Returns
void
Definition at line 439 of file ClassMetadataDecorator.php.
extractKeyValues()
extractKeyValues (array $columnValues, bool $ignoreMissing = false)
Generate ids for use with find and self::persist() from database column values.
$columnValues is allowed to contain excess data which comes in handy when recursing into associations.
Parameters
array $columnValues The actual identifier values indexed by the database column names (read: not the entity-class-names, but the raw column names in the database).
bool $ignoreMissing Ignore missing key values, just continue and return an incomplete set of keys.
Returns
array
[
  PROPERTY => ELEMENTARY_FIELD_VALUE,
  ...
]
Todo:
$columnValues sometimes contains raw data-base values as it is passed down here from code using the legacy phpMyEdit stuff. ATM we hack around by converting string values to their proper PHP values, but this is an ugly hack.
Definition at line 375 of file ClassMetadataDecorator.php.
getAssociationMappedByTargetField()
getAssociationMappedByTargetField ($assocName)
{}
Definition at line 190 of file ClassMetadataDecorator.php.
getAssociationNames()
getAssociationNames ()
{}
Definition at line 166 of file ClassMetadataDecorator.php.
getAssociationTargetClass()
getAssociationTargetClass ($assocName)
{}
Definition at line 178 of file ClassMetadataDecorator.php.
getColumnValue()
getColumnValue (mixed $entity, string $column)
Fetch the value of a column, recursing into associations.
Parameters
mixed $entity
string $column
Returns
mixed
Definition at line 549 of file ClassMetadataDecorator.php.
getFieldNames()
getFieldNames ()
{}
Definition at line 154 of file ClassMetadataDecorator.php.
getIdentifier()
getIdentifier ()
{}
Definition at line 112 of file ClassMetadataDecorator.php.
getIdentifierFieldNames()
getIdentifierFieldNames ()
{}
Definition at line 160 of file ClassMetadataDecorator.php.
getIdentifierValues()
getIdentifierValues ($object)
{}
Definition at line 196 of file ClassMetadataDecorator.php.
getName()
getName ()
{}
Definition at line 106 of file ClassMetadataDecorator.php.
getReflectionClass()
getReflectionClass ()
{}
Definition at line 118 of file ClassMetadataDecorator.php.
getTypeOfField()
getTypeOfField ($fieldName)
{}
Definition at line 172 of file ClassMetadataDecorator.php.
hasAssociation()
hasAssociation ($fieldName)
{}
Definition at line 136 of file ClassMetadataDecorator.php.
hasField()
hasField ($fieldName)
{}
Definition at line 130 of file ClassMetadataDecorator.php.
identifierColumns()
identifierColumns ()
Compute the mapping between entity-properties ("field-name") and plain SQL column-names.
This is somewhat complicated when foreign keys are used.
Returns
array
[
  PROPERTY => SQL_COLUMN_NAME
  ...
]
Definition at line 596 of file ClassMetadataDecorator.php.
isAssociationInverseSide()
isAssociationInverseSide ($assocName)
{}
Definition at line 184 of file ClassMetadataDecorator.php.
isCollectionValuedAssociation()
isCollectionValuedAssociation ($fieldName)
{}
Definition at line 148 of file ClassMetadataDecorator.php.
isIdentifier()
isIdentifier ($fieldName)
{}
Definition at line 124 of file ClassMetadataDecorator.php.
isSingleValuedAssociation()
isSingleValuedAssociation ($fieldName)
{}
Definition at line 142 of file ClassMetadataDecorator.php.
setColumnValue()
setColumnValue (mixed $entity, string $column, mixed $value)
Parameters
mixed $entity
string $column
mixed $value
Returns
void
Definition at line 477 of file ClassMetadataDecorator.php.
updateInverseSide()
updateInverseSide (object $entity, array $association, object $targetEntity, ClassMetadataInterface $targetMeta) private
Update the inverse side of an association after auto-installing $targetEntity into $entity (the owning side).
This is only done if it does not produce reloads from the data-base, so only "real" entities, initialized proxies and initialized lazy collections are updated.
Parameters
object $entity The current $entity which must be the owning side of the association.
array $association The association mapping of the current field (the field itself is not needed here).
object $targetEntity The target-entity which must be the inverse side of the association.
ClassMetadata | ClassMetadataDecorator $targetMeta The class meta-data of the target-entity.
Returns
void
Definition at line 251 of file ClassMetadataDecorator.php.
References ClassMetadataDecorator\debug().
Field Documentation
$columnAssociationsCache
array $columnAssociationsCache = [] private
Definition at line 51 of file ClassMetadataDecorator.php.
$debug
bool $debug = false private
Definition at line 66 of file ClassMetadataDecorator.php.
$entityManager
EntityManager $entityManager private
Definition at line 57 of file ClassMetadataDecorator.php.
$l
IL10N $l private
Definition at line 63 of file ClassMetadataDecorator.php.
$metaData
ClassMetadata $metaData private
Definition at line 60 of file ClassMetadataDecorator.php.
$temporaryColumnStorage
array $temporaryColumnStorage = [] private
Definition at line 54 of file ClassMetadataDecorator.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Mapping/ClassMetadataDecorator.php