CamerataDB: ProjectService Class Reference
ProjectService Class Reference
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Public Member Functions
participantOptions (int $projectId, ?string $projectName=null, int $selectedMusicianId=-1)
Generate an option table with all participants, suitable to be staffed into Navigation::selectOptions().
findParticipant (mixed $projectOrId, mixed $musicianOrId)
Find the participant given by $projectOrId and $musicianOrId.
projectOptions (array $criteria=[], int $selectedProject=0)
Generate an selection options array.
instrumentationBalance (mixed $projectOrId, bool $sumVoices=false)
Fetch the instrumentation balance for the given project.
findById (int $projectId)
Find a project by its id.
findByName (string $projectName)
Find a project by its name.
persistProject (Entities\Project $project)
Persist and flush the database.
fetchName (int $projectId)
fetchAll ()
fetch (array $criteria, ?array $orderBy=[])
Fetch some project matching the specified criteria.
getProjectPathComponents (mixed $project)
Depending on the type of the project generate the partial project-folder path:
getProjectPathPrefix (mixed $project)
Depending on the type of the project generate the partial project-folder path:
getProjectFolder ($projectOrId, ?string $only=null)
Get the configured name of the or all or the specified folder.
getProjectSkeletonPaths ()
Return an array with the project skeleton paths, indexed by folder-type.
renameProjectFolder ($newProject, $oldProject)
Rename the associated project folders after project rename.
ensurePostersFolder ($projectOrId, bool $dry=false)
Make sure the per-project posters folder exists for the given project.
ensureDownloadsFolder ($projectOrId, bool $dry=false)
Make sure the per-project downloads folder exists for the given project and is shared via link.
ensureParticipantFolder (Entities\Project $project, Entities\Musician $musician, bool $dry=false)
Make sure the per-project per-participant folder exists for the given project and musician.
getParticipantFolder (Entities\Project $project, Entities\Musician $musician)
More leight-weight construction of the participant folder, assuming everything else is just is ok.
participantFilename (string $base, $musicianOrSlug, bool $ignoreExtension=false)
Avoid duplicated "extensions" in file-names, i.e.
getParticipantFieldFolderPath (Entities\ProjectParticipantField $field, bool $includeDeleted=false,)
Generatet the full path to the parent folder of the files attached to the given field data (if there are any)
projectWikiLink (string $pageName)
generateProjectWikiPage (int $projectId, string $projectName)
Generate an almost empty project page.
deleteProjectWikiPage ($project)
Delete the wiki page.
restoreProjectWikiPage ($project, ?int $version=null)
Restore the wiki page to the given or lastest version.
renameProjectWikiPage (mixed $newProject, mixed $oldProject)
Rename the associated wiki-pages after project rename.
webPageCMSURL (mixed $articleId, bool $editMode=false)
pingWebPages ()
fetchProjectWebPages (mixed $projectOrId)
Fetch fetch the article entities from the database.
projectWebPages (mixed $projectOrId)
Fetch all articles known to the system.
createProjectWebPage (mixed $projectOrId, string $kind=self::WEBPAGE_TYPE_CONCERT)
Create and add a new web-page.
deleteProjectWebPage (mixed $projectOrId, mixed $article, bool $hard=false)
Delete a web page.
restoreProjectWebPage (mixed $projectOrId, mixed $article)
Restore the web-pages previously deleted by deleteProjectWebPage()
detachProjectWebPage (mixed $projectOrId, int $articleId)
Detach a web page, but do not delete it.
attachProjectWebPage (mixed $projectOrId, array $article)
Attach an existing web page to the project.
nameProjectWebPages (mixed $projectOrId, ?string $projectName=null)
Set the name of all registered web-pages to the canonical name, project name given.
attachMatchingWebPages (mixed $projectOrId)
Search through the list of all projects and attach those with a matching name.
addMusicians (array $musicianIds, int $projectId)
Add the given musicians to the project.
yearFromName (string $projectName)
Extract the year from the project name if present.
sanitizeName (string $projectName, bool $requireYear=false)
Validate the name, no spaces, camel case, last four characters may be digits of the form 20XX.
Data Fields
const DBTABLE = 'Projects'
const FOLDER_TYPE_PROJECT = 'project'
const FOLDER_TYPE_PARTICIPANTS = 'participants'
const FOLDER_TYPE_PARTICIPANTS_TEMPLATE = self::FOLDER_TYPE_PARTICIPANTS . 'template'
const FOLDER_TYPE_POSTERS = 'posters'
const FOLDER_TYPE_DOWNLOADS = 'downloads'
const FOLDER_TYPE_BALANCE = 'balance'
const WEBPAGE_TYPE_CONCERT = 'concert'
const WEBPAGE_TYPE_REHEARSALS = 'rehearsals'
const PROJECT_FOLDER_CONFIG_KEYS
Private Member Functions
wikiRPC ()
Lazy getter for WikiRPC.
webPagesRPC ()
Lazy getter for WebPagesRPC.
systemTagManager ()
Lazy getter for ISystemTagManager.
restoreProjectFolders (Entities\Project $project, ?array $timeInterval=null)
Restore the folders for the given project in order to undelete or during error recovery.
Private Attributes
$skeletonPaths = null
Cached array of project folder skeleton paths.
$wikiRPCInstance
$webPagesRPCInstance
$repository
$systemTagManager
Detailed Description
General support service, kind of inconsequent glue between Doctrine\ORM and CAFEVDB\PageRenderer.
Definition at line 65 of file ProjectService.php.
Member Function Documentation
addMusicians()
addMusicians (array $musicianIds, int $projectId)
Add the given musicians to the project.
Parameters
array $musicianIds Flat array of the data-base keys for Entities\Musician.
int $projectId The project-id for the destination project.
Todo
Perhaps allow project-entities, i.e. "mixed $project" instead of "int $projectId".
Returns
array
[
  'failed' => [
    [ 'id' => ID, 'notice' => REMARK, ... ],
    ...
  ],
  'added'  => [
     [ id' => ID, 'notice' => REMARK, 'sqlerror' => OPTIONAL ],
  ],
]
Definition at line 2011 of file ProjectService.php.
attachMatchingWebPages()
attachMatchingWebPages (mixed $projectOrId)
Search through the list of all projects and attach those with a matching name.
Something which should go to the "expert" controls.
Parameters
int | Entities\\Project $projectOrId
Returns
bool Execution status.
Definition at line 1952 of file ProjectService.php.
attachProjectWebPage()
attachProjectWebPage (mixed $projectOrId, array $article)
Attach an existing web page to the project.
Parameters
mixed $projectOrId Project entity or its id.
array $article Article description from CMS system.
Returns
void
Definition at line 1863 of file ProjectService.php.
createProjectWebPage()
createProjectWebPage (mixed $projectOrId, string $kind = self::WEBPAGE_TYPE_CONCERT)
Create and add a new web-page.
The first one will have the name of the project, subsequent one have a number attached like Tango2014-5.
Parameters
mixed $projectOrId The project entity or its id.
string $kind One of self::WEBPAGE_TYPE_CONCERT or self::WEBPAGE_TYPE_REHEARSALS.
Returns
array
See also
WebPagesRPC::addArticle()
Definition at line 1684 of file ProjectService.php.
deleteProjectWebPage()
deleteProjectWebPage (mixed $projectOrId, mixed $article, bool $hard = false)
Delete a web page.
This is implemented by moving the page to the Trashbin category, leaving the real cleanup to a human being.
Parameters
mixed $projectOrId Project entity or its id.
mixed $article Either an array or Entities\ProjectWebPage.
bool $hard Whether to really delete the page.
Returns
void
Definition at line 1782 of file ProjectService.php.
deleteProjectWikiPage()
deleteProjectWikiPage ($project)
Delete the wiki page.
Parameters
array | Entities\\Project $project
Returns
int Page version deleted.
Definition at line 1500 of file ProjectService.php.
detachProjectWebPage()
detachProjectWebPage (mixed $projectOrId, int $articleId)
Detach a web page, but do not delete it.
Meant as utility routine for the UI (in order to correct wrong associations).
Parameters
mixed $projectOrId Entity or its id.
int $articleId CMS article id.
Returns
void
Definition at line 1837 of file ProjectService.php.
ensureDownloadsFolder()
ensureDownloadsFolder ($projectOrId, bool $dry = false)
Make sure the per-project downloads folder exists for the given project and is shared via link.
Parameters
int | Entities\\Project $projectOrId
bool $dry If true then just create the name, do not perform any file-system operations.
Returns
string Folder path.
Definition at line 899 of file ProjectService.php.
ensureParticipantFolder()
ensureParticipantFolder (Entities\Project $project, Entities\Musician $musician, bool $dry = false)
Make sure the per-project per-participant folder exists for the given project and musician.
If a skeleton folder exists then its contents is also copied over.
Parameters
Entities\\Project $project
Entities\\Musician $musician
bool $dry If true then just create the name, do not perform any file-system operations.
Returns
string Folder path.
Definition at line 1004 of file ProjectService.php.
ensurePostersFolder()
ensurePostersFolder ($projectOrId, bool $dry = false)
Make sure the per-project posters folder exists for the given project.
Parameters
int | Entities\\Project $projectOrId
bool $dry If true then just create the name, do not perform any file-system operations.
Returns
string Folder path.
Definition at line 883 of file ProjectService.php.
fetch()
fetch (array $criteria, ?array $orderBy = [])
Fetch some project matching the specified criteria.
Parameters
array $criteria
array $orderBy Sorting criteria. Default is to index by project id and sort descending by type, descending by year, ascending by name.
Returns
array<int, Entities\Project>
Definition at line 416 of file ProjectService.php.
fetchAll()
fetchAll ()
Returns
Just return the collection of all projects.
Definition at line 401 of file ProjectService.php.
fetchName()
fetchName (int $projectId)
Parameters
int $projectId Database entity id.
Returns
null|string Fetch the project-name name corresponding to $projectId.
Definition at line 389 of file ProjectService.php.
fetchProjectWebPages()
fetchProjectWebPages (mixed $projectOrId)
Fetch fetch the article entities from the database.
Parameters
mixed $projectOrId Entity or its id.
Returns
ArrayCollection
Definition at line 1602 of file ProjectService.php.
findById()
findById (int $projectId)
Find a project by its id.
Parameters
int $projectId
Returns
null|Entities\Project
Definition at line 349 of file ProjectService.php.
findByName()
findByName (string $projectName)
Find a project by its name.
Parameters
string $projectName
Returns
null|Entities\Project
Definition at line 361 of file ProjectService.php.
findParticipant()
findParticipant (mixed $projectOrId, mixed $musicianOrId)
Find the participant given by $projectOrId and $musicianOrId.
Parameters
int | Entities\\Project $projectOrId Database entity or id.
int | Entities\\Project $musicianOrId Database entity or id.
Returns
null|Entities\ProjectParticipant
Definition at line 243 of file ProjectService.php.
generateProjectWikiPage()
generateProjectWikiPage (int $projectId, string $projectName)
Generate an almost empty project page.
This spares people the need to click on "new page".
We insert a proper title heading
We insert a sub-title "Contacts"
We insert a sub-title "Financial Arrangements"
We insert a sub-title "Location"
Parameters
int $projectId Database entity id.
string $projectName Project name.
Returns
void
See also
WikiRPC::putPage()
Definition at line 1455 of file ProjectService.php.
getParticipantFieldFolderPath()
getParticipantFieldFolderPath (Entities\ProjectParticipantField $field, bool $includeDeleted = false)
Generatet the full path to the parent folder of the files attached to the given field data (if there are any)
Parameters
Entities\\ProjectParticipantField $field
bool $includeDeleted Include deleted entities in the result.
Returns
null|string
Definition at line 1083 of file ProjectService.php.
getParticipantFolder()
getParticipantFolder (Entities\Project $project, Entities\Musician $musician)
More leight-weight construction of the participant folder, assuming everything else is just is ok.
Parameters
Entities\\Project $project Database entity.
Entities\\Musician $musician Database entity.
Returns
string
Definition at line 1028 of file ProjectService.php.
getProjectFolder()
getProjectFolder ($projectOrId, ?string $only = null)
Get the configured name of the or all or the specified folder.
Parameters
int | Entities\\Project $projectOrId
string | null $only Get the name of only this folder if not null. $only can be one of the PROJECTS_..._FOLDER constants of the ConfigService class,
See also
ConfigService.
Returns
mixed Either the array of all paths or the path requested by $only.
Definition at line 528 of file ProjectService.php.
References ProjectService\getProjectPathPrefix().
getProjectPathComponents()
getProjectPathComponents (mixed $project)
Depending on the type of the project generate the partial project-folder path:
ProjectType::TEMPORARY – path is YEAR/PROJECT_NAME
ProjectType::PERMANENT – path is just PROJECT_NAME
ProjectType::TEMPLATE – path is L10N_TEMPLATE_NAME/PROJECT_NAME
Parameters
array | Entities\\Project $project
Returns
array
Definition at line 488 of file ProjectService.php.
Referenced by ProjectService\getProjectPathPrefix().
getProjectPathPrefix()
getProjectPathPrefix (mixed $project)
Depending on the type of the project generate the partial project-folder path:
ProjectType::TEMPORARY – path is YEAR/PROJECT_NAME
ProjectType::PERMANENT – path is just PROJECT_NAME
ProjectType::TEMPLATE – path is L10N_TEMPLATE_NAME/PROJECT_NAME
Parameters
array | Entities\\Project $project
Returns
string
Definition at line 512 of file ProjectService.php.
References ProjectService\getProjectPathComponents().
Referenced by ProjectService\getProjectFolder().
getProjectSkeletonPaths()
getProjectSkeletonPaths ()
Return an array with the project skeleton paths, indexed by folder-type.
Returns
array
See also
ensureProjectFolders()
Definition at line 570 of file ProjectService.php.
References ProjectService\$skeletonPaths.
instrumentationBalance()
instrumentationBalance (mixed $projectOrId, bool $sumVoices = false)
Fetch the instrumentation balance for the given project.
Parameters
int | Entities\\Project $projectOrId Database entity or id.
bool $sumVoices Sum-up all voices into a single instrument field.
Returns
array<string, array>
[
  INSTRUMENT:VOICE => [
    'instrument' => INSTRUMENT,
    'voice' => VOICE,
    'registered' => (REQUIRED - REGISTERED),
    'confirmed' => (REQUIRED - CONFIRMED),
  ]
]
If $sumVoices == true, the voice field is not present and the key consists of the instrument only.
See also
\OCA\CAFEVDB\Database\Doctrine\ORM\Repositories\ProjectInstrumentationNumbersRepository::fetchInstrumentationBalance()
Definition at line 305 of file ProjectService.php.
nameProjectWebPages()
nameProjectWebPages (mixed $projectOrId, ?string $projectName = null)
Set the name of all registered web-pages to the canonical name, project name given.
Parameters
mixed $projectOrId Database entity or its id.
null | string $projectName Name of the project.
Returns
bool Execution status.
Definition at line 1901 of file ProjectService.php.
participantFilename()
participantFilename (string $base, $musicianOrSlug, bool $ignoreExtension = false)
Avoid duplicated "extensions" in file-names, i.e.
use passport-ClausJustusHeine.pdf instead of passport-claus-justus.heine.pdf
Parameters
string $base Filename base.
string | Entities\\Musician $musicianOrSlug Entity or its user-id-slug.
bool $ignoreExtension If \false (the default) then an extension present in $base will be stripped from $base and appended to the resulting file-name. If \true any dots in $base will just be replaced by dashes.
Returns
string
Definition at line 1063 of file ProjectService.php.
References MusicianService\slugifyFileName().
participantOptions()
participantOptions (int $projectId, ?string $projectName = null, int $selectedMusicianId = -1)
Generate an option table with all participants, suitable to be staffed into Navigation::selectOptions().
This is a single select, only one musician may be preselected. The key is the musician id. The options are meant for a single-choice select box.
Parameters
int $projectId The id of the project to fetch the musician options from.
null | string $projectName Optional project name, will be queried from DB if not specified.
int $selectedMusicianId A pre-selected musician, defaults to -1.
Returns
array
Definition at line 218 of file ProjectService.php.
persistProject()
persistProject (Entities\Project $project)
Persist and flush the database.
Parameters
Entities\\Project $project Database entity.
Returns
void
See also
OCA\CAFEVDB\Controller\PersonalSettingsController::setApp()
Definition at line 378 of file ProjectService.php.
pingWebPages()
pingWebPages ()
Returns
bool Ping status.
See also
WebPagesRPC::ping()
Definition at line 1590 of file ProjectService.php.
projectOptions()
projectOptions (array $criteria = [], int $selectedProject = 0)
Generate an selection options array.
Parameters
array $criteria Filter criteria for the projects database.
int $selectedProject A pre-selected project-id.
Returns
array
See also
OCA\CAFEVDB\PageRenderer\Util\Navigation::selectOptions()
Definition at line 260 of file ProjectService.php.
projectWebPages()
projectWebPages (mixed $projectOrId)
Fetch all articles known to the system.
Parameters
mixed $projectOrId Entity or its id.
Returns
bool|array
[
  'projectPages' => WEBPAGES,
  'otherPages' => WEBPAGES,
]
Definition at line 1625 of file ProjectService.php.
projectWikiLink()
projectWikiLink (string $pageName)
Parameters
string $pageName The name of the wiki page without namespace.
Returns
string The namespaced wiki page name.
Definition at line 1340 of file ProjectService.php.
renameProjectFolder()
renameProjectFolder ($newProject, $oldProject)
Rename the associated project folders after project rename.
Parameters
array | Entities\\Project $newProject Array-like object, "id", "name" and "year" keys need to be present.
array | Entities\\Project $oldProject Array-like object, "id", "name" and "year" keys need to be present.
Returns
array Array with new paths.
Definition at line 809 of file ProjectService.php.
renameProjectWikiPage()
renameProjectWikiPage (mixed $newProject, mixed $oldProject)
Rename the associated wiki-pages after project rename.
Parameters
array | Entities\\Project $newProject Array-like object, "name" and "year" keys need to be present.
array | Entities\\Project $oldProject Array-like object, "name" and "year" keys need to be present.
Returns
void
See also
generateWikiOverview()
Definition at line 1559 of file ProjectService.php.
restoreProjectFolders()
restoreProjectFolders (Entities\Project $project, ?array $timeInterval = null) private
Restore the folders for the given project in order to undelete or during error recovery.
Parameters
Entities\\Project $project Project entity.
null | array $timeInterval Unfortunately the time-stamp in the trash bin is hard to get hold of. If $timeInterval is given, only try to restore folders in the given interval.
Returns
bool Status
Definition at line 770 of file ProjectService.php.
restoreProjectWebPage()
restoreProjectWebPage (mixed $projectOrId, mixed $article)
Restore the web-pages previously deleted by deleteProjectWebPage()
Parameters
mixed $projectOrId Entity or its id.
mixed $article Either an array or Entities\ProjectWebPage.
Returns
void
Definition at line 1819 of file ProjectService.php.
restoreProjectWikiPage()
restoreProjectWikiPage ($project, ?int $version = null)
Restore the wiki page to the given or lastest version.
Parameters
array | Entities\\Project $project Database entity or "DTO array".
null | int $version Page version.
Returns
bool Execution status.
Definition at line 1525 of file ProjectService.php.
sanitizeName()
sanitizeName (string $projectName, bool $requireYear = false)
Validate the name, no spaces, camel case, last four characters may be digits of the form 20XX.
Parameters
string $projectName The name to validate.
boolean $requireYear Year in last four characters is mandatory.
Returns
string
Definition at line 3132 of file ProjectService.php.
systemTagManager()
systemTagManager () private
Lazy getter for ISystemTagManager.
Returns
ISystemTagManager
Definition at line 194 of file ProjectService.php.
References ProjectService\systemTagManager().
Referenced by ProjectService\systemTagManager().
webPageCMSURL()
webPageCMSURL (mixed $articleId, bool $editMode = false)
Parameters
mixed $articleId Article id or null or a template string for later substitution.
bool $editMode Whether the CMS url refers to the editor for the page.
Returns
string The CMS url for the given articleid.
Definition at line 1580 of file ProjectService.php.
webPagesRPC()
webPagesRPC () private
Lazy getter for WebPagesRPC.
Returns
WebPagesRPC
Definition at line 180 of file ProjectService.php.
wikiRPC()
wikiRPC () private
Lazy getter for WikiRPC.
Returns
WikiRPC
Definition at line 166 of file ProjectService.php.
yearFromName()
yearFromName (string $projectName)
Extract the year from the project name if present.
Parameters
string $projectName The name of the project.
Returns
array
[ 'name' => NAME_WITHOUT_YEAR, 'year' => NULL_OR_YEAR ]
Definition at line 3110 of file ProjectService.php.
Field Documentation
$repository
ProjectsRepository $repository private
Definition at line 106 of file ProjectService.php.
$skeletonPaths
array< string, string > $skeletonPaths = null private
Cached array of project folder skeleton paths.
Definition at line 97 of file ProjectService.php.
Referenced by ProjectService\getProjectSkeletonPaths().
$systemTagManager
ISystemTagManager $systemTagManager private
Definition at line 109 of file ProjectService.php.
$webPagesRPCInstance
OCA Redaxo Service RPC $webPagesRPCInstance private
Definition at line 103 of file ProjectService.php.
$wikiRPCInstance
WikiRPC $wikiRPCInstance private
Definition at line 100 of file ProjectService.php.
DBTABLE
const DBTABLE = 'Projects'
Definition at line 72 of file ProjectService.php.
FOLDER_TYPE_BALANCE
const FOLDER_TYPE_BALANCE = 'balance'
Definition at line 79 of file ProjectService.php.
FOLDER_TYPE_DOWNLOADS
const FOLDER_TYPE_DOWNLOADS = 'downloads'
Definition at line 78 of file ProjectService.php.
FOLDER_TYPE_PARTICIPANTS
const FOLDER_TYPE_PARTICIPANTS = 'participants'
Definition at line 75 of file ProjectService.php.
FOLDER_TYPE_PARTICIPANTS_TEMPLATE
const FOLDER_TYPE_PARTICIPANTS_TEMPLATE = self::FOLDER_TYPE_PARTICIPANTS . 'template'
Definition at line 76 of file ProjectService.php.
FOLDER_TYPE_POSTERS
const FOLDER_TYPE_POSTERS = 'posters'
Definition at line 77 of file ProjectService.php.
FOLDER_TYPE_PROJECT
const FOLDER_TYPE_PROJECT = 'project'
Definition at line 74 of file ProjectService.php.
PROJECT_FOLDER_CONFIG_KEYS
const PROJECT_FOLDER_CONFIG_KEYS
Initial value:
= [
    ConfigService::PROJECTS_FOLDER,
    ConfigService::PROJECT_PARTICIPANTS_FOLDER,
    ConfigService::PROJECT_POSTERS_FOLDER,
    ConfigService::PROJECT_PUBLIC_DOWNLOADS_FOLDER,
    ConfigService::BALANCES_FOLDER,
  ]
Definition at line 84 of file ProjectService.php.
WEBPAGE_TYPE_CONCERT
const WEBPAGE_TYPE_CONCERT = 'concert'
Definition at line 81 of file ProjectService.php.
WEBPAGE_TYPE_REHEARSALS
const WEBPAGE_TYPE_REHEARSALS = 'rehearsals'
Definition at line 82 of file ProjectService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Service/ProjectService.php