CamerataDB: HistoryService Class Reference
HistoryService Class Reference
Page history via PHP session.
Public Member Functions
__construct (ISession $session, IL10N $l10n, ILogger $logger,)
push (array $data)
Add a history snapshot.
fetch (int $offset)
Fetch the history record at $offset.
position ()
Return the current position into the history.
size ()
Return the current position into the history.
empty ()
Return true if the recorded history is essentially empty.
store ()
Store the current state whereever.
Data Fields
const MAX_HISTORY_SIZE = 1
const SESSION_HISTORY_KEY = 'PageHistory'
const PME_ERROR_READONLY = 1
Protected Attributes
$l
$debug = false
Private Member Functions
default ()
Initialize a sane do-nothing record.
printRecords ()
Debugging utility.
load ()
Load the history state.
validate (?array $history)
Validate the given history records, return false on error.
validateRecord (array $record)
Validate one history entry.
validateRecords (array $history)
Validate all history records.
Private Attributes
$historyRecords
The data-contents.
$historyPosition
$historySize
$session
Detailed Description
Page history via PHP session.
Todo:
This now should be obsolete as the navigation history is handled by the Javascript code.
Definition at line 39 of file HistoryService.php.
Constructor & Destructor Documentation
__construct()
__construct (ISession $session, IL10N $l10n, ILogger $logger)
Definition at line 72 of file HistoryService.php.
Member Function Documentation
default()
default () private
Initialize a sane do-nothing record.
Returns
void
Definition at line 89 of file HistoryService.php.
empty()
empty ()
Return true if the recorded history is essentially empty.
Returns
bool
Definition at line 206 of file HistoryService.php.
fetch()
fetch (int $offset)
Fetch the history record at $offset.
The function will throw an exception if offset is out of bounds.
Parameters
int $offset
Returns
array
Definition at line 160 of file HistoryService.php.
References HistoryService\printRecords().
load()
load () private
Load the history state.
Initialize to default state in case of errors.
Returns
bool
Definition at line 231 of file HistoryService.php.
References HistoryService\validate().
position()
position ()
Return the current position into the history.
Returns
int
Definition at line 186 of file HistoryService.php.
printRecords()
printRecords () private
Debugging utility.
Returns
void
Definition at line 131 of file HistoryService.php.
Referenced by HistoryService\fetch(), and HistoryService\push().
push()
push (array $data)
Add a history snapshot.
Parameters
array $data
Returns
void
Definition at line 104 of file HistoryService.php.
References HistoryService\printRecords().
size()
size ()
Return the current position into the history.
Returns
int
Definition at line 196 of file HistoryService.php.
store()
store ()
Store the current state whereever.
Currently the PHP session data, but this is not guaranteed.
Returns
void
Definition at line 217 of file HistoryService.php.
References HistoryService\$historyRecords.
validate()
validate (?array $history) private
Validate the given history records, return false on error.
Parameters
null | array $history
Returns
bool
Definition at line 251 of file HistoryService.php.
References HistoryService\validateRecords().
Referenced by HistoryService\load().
validateRecord()
validateRecord (array $record) private
Validate one history entry.
Parameters
array $record
Returns
bool
Definition at line 270 of file HistoryService.php.
Referenced by HistoryService\validateRecords().
validateRecords()
validateRecords (array $history) private
Validate all history records.
Parameters
array $history
Returns
bool
Definition at line 288 of file HistoryService.php.
References HistoryService\validateRecord().
Referenced by HistoryService\validate().
Field Documentation
$debug
bool $debug = false protected
Definition at line 52 of file HistoryService.php.
$historyPosition
$historyPosition private
Definition at line 65 of file HistoryService.php.
$historyRecords
$historyRecords private
The data-contents.
A "cooked" array structure with the following components:
[ 'size' => NUMBER_OF_HISTORY_RECORDS,
  'position' => CURRENT_POSITION_INTO_HISTORY_RECORDS,
  'records' => array(# => clone of $_POST),
]
Definition at line 64 of file HistoryService.php.
Referenced by HistoryService\store().
$historySize
$historySize private
Definition at line 66 of file HistoryService.php.
$l
IL10N $l protected
Definition at line 49 of file HistoryService.php.
$session
ISession $session private
Definition at line 69 of file HistoryService.php.
MAX_HISTORY_SIZE
const MAX_HISTORY_SIZE = 1
Definition at line 44 of file HistoryService.php.
PME_ERROR_READONLY
const PME_ERROR_READONLY = 1
Definition at line 46 of file HistoryService.php.
SESSION_HISTORY_KEY
const SESSION_HISTORY_KEY = 'PageHistory'
Definition at line 45 of file HistoryService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/HistoryService.php