CamerataDB: PlainFileProgressStatus Class Reference
PlainFileProgressStatus Class Reference
Progress status with a plain local file as storage.
Public Member Functions
__construct (string $appName, ILogger $logger, IL10N $l10n, AppStorage $storage,)
delete ()
{Delete the underlying storage object.Afterwards any operation except $this->bind() will exhibit undefined behaviour.
Returns
void
}
bind (mixed $id=null)
{Bind to the given storage object.Create a new object if $id is null.
Parameters
mixed $id Opaque data identifying the progress status object.
Returns
void
}
getId ()
{Obtain a unique but opaque identifier (e.g.the id column in a database up to a serialized representation).
Returns
mixed
}
update (int $current, ?int $target=null, ?array $data=null)
{Update to the given values, where null arguments are simply ignored.This function has to write the given values through to the underlying storage.
Parameters
int $current
null | int $target If null the target remains unchanged.
null | array $data "user"-data stored in the progress-status object. Can be retrieved later via getData(). If null then the currently stored data remains unchanged.
Returns
bool true on success, false if the underlying storage has been deleted.
}
sync ()
{Synchronize with the underlying storage, i.e.read the data into this instance.
Returns
void
}
getCurrent ()
{Return the cached value of the current state.
Returns
int
}
getTarget ()
{Return the cached value of the target state.
Returns
int
}
getLastModified ()
{Return the cached value of the last modification time.
Returns
DateTimeInterface
}
getData ()
{Return the cached value of the custom data, i.e.the data previously passed to update().
Returns
null|array
}
increment (int $delta=1)
{Add the given amount to the progress-status counter.
Parameters
int $delta Amount to add, defaults to 1. Negative values are allowed.
Returns
bool|int Current value of the counter or false if the underlying storage has been deleted.
}
setCurrent (int $current)
{Set the current value and sync.
Parameters
int $current
Returns
void
}
setTarget (int $target)
{Set the target value and sync.
Parameters
int $target
Returns
void
}
setData (array $data)
{Set the data value and sync.
Parameters
array $data
Returns
void
}
Data Fields
const DATA_DIR = 'progress-status'
Protected Member Functions
reset ()
Reset the initial state.
flush ()
Flush the initial state to disk.
Protected Attributes
$storage
$folder
$file
$data
Private Attributes
const READ_RETRY_LIMIT = 10
Detailed Description
Progress status with a plain local file as storage.
Definition at line 40 of file PlainFileProgressStatus.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, ILogger $logger, IL10N $l10n, AppStorage $storage)
Definition at line 61 of file PlainFileProgressStatus.php.
Member Function Documentation
bind()
bind (mixed $id = null)
{Bind to the given storage object.Create a new object if $id is null.
Parameters
mixed $id Opaque data identifying the progress status object.
Returns
void
}
Implements IProgressStatus.
Definition at line 118 of file PlainFileProgressStatus.php.
References PlainFileProgressStatus\reset(), and PlainFileProgressStatus\sync().
delete()
delete ()
{Delete the underlying storage object.Afterwards any operation except $this->bind() will exhibit undefined behaviour.
Returns
void
}
Implements IProgressStatus.
Definition at line 109 of file PlainFileProgressStatus.php.
flush()
flush () protected
Flush the initial state to disk.
Returns
bool true on success, false if the data-file has been deleted.
Definition at line 97 of file PlainFileProgressStatus.php.
Referenced by PlainFileProgressStatus\update().
getCurrent()
getCurrent ()
{Return the cached value of the current state.
Returns
int
}
Implements IProgressStatus.
Definition at line 187 of file PlainFileProgressStatus.php.
getData()
getData ()
{Return the cached value of the custom data, i.e.the data previously passed to update().
Returns
null|array
}
Implements IProgressStatus.
Definition at line 205 of file PlainFileProgressStatus.php.
getId()
getId ()
{Obtain a unique but opaque identifier (e.g.the id column in a database up to a serialized representation).
Returns
mixed
}
Implements IProgressStatus.
Definition at line 154 of file PlainFileProgressStatus.php.
getLastModified()
getLastModified ()
{Return the cached value of the last modification time.
Returns
DateTimeInterface
}
Implements IProgressStatus.
Definition at line 199 of file PlainFileProgressStatus.php.
getTarget()
getTarget ()
{Return the cached value of the target state.
Returns
int
}
Implements IProgressStatus.
Definition at line 193 of file PlainFileProgressStatus.php.
increment()
increment (int $delta = 1) inherited
{Add the given amount to the progress-status counter.
Parameters
int $delta Amount to add, defaults to 1. Negative values are allowed.
Returns
bool|int Current value of the counter or false if the underlying storage has been deleted.
}
Implements IProgressStatus.
Definition at line 33 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), and IProgressStatus\update().
reset()
reset () protected
Reset the initial state.
Returns
void
Definition at line 81 of file PlainFileProgressStatus.php.
Referenced by PlainFileProgressStatus\bind().
setCurrent()
setCurrent (int $current) inherited
{Set the current value and sync.
Parameters
int $current
Returns
void
}
Implements IProgressStatus.
Definition at line 42 of file AbstractProgressStatus.php.
References IProgressStatus\update().
setData()
setData (array $data) inherited
{Set the data value and sync.
Parameters
array $data
Returns
void
}
Implements IProgressStatus.
Definition at line 54 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), IProgressStatus\getTarget(), and IProgressStatus\update().
setTarget()
setTarget (int $target) inherited
{Set the target value and sync.
Parameters
int $target
Returns
void
}
Implements IProgressStatus.
Definition at line 48 of file AbstractProgressStatus.php.
References IProgressStatus\getCurrent(), and IProgressStatus\update().
sync()
sync ()
{Synchronize with the underlying storage, i.e.read the data into this instance.
Returns
void
}
Implements IProgressStatus.
Definition at line 173 of file PlainFileProgressStatus.php.
Referenced by PlainFileProgressStatus\bind().
update()
update (int $current, ?int $target = null, ?array $data = null)
{Update to the given values, where null arguments are simply ignored.This function has to write the given values through to the underlying storage.
Parameters
int $current
null | int $target If null the target remains unchanged.
null | array $data "user"-data stored in the progress-status object. Can be retrieved later via getData(). If null then the currently stored data remains unchanged.
Returns
bool true on success, false if the underlying storage has been deleted.
}
Implements IProgressStatus.
Definition at line 160 of file PlainFileProgressStatus.php.
References PlainFileProgressStatus\flush().
Field Documentation
$data
array $data protected
Definition at line 58 of file PlainFileProgressStatus.php.
$file
ISimpleFile $file protected
Definition at line 55 of file PlainFileProgressStatus.php.
$folder
ISimpleFolder $folder protected
Definition at line 52 of file PlainFileProgressStatus.php.
$storage
AppStorage $storage protected
Definition at line 49 of file PlainFileProgressStatus.php.
DATA_DIR
const DATA_DIR = 'progress-status'
Definition at line 46 of file PlainFileProgressStatus.php.
READ_RETRY_LIMIT
const READ_RETRY_LIMIT = 10 private
Definition at line 42 of file PlainFileProgressStatus.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/PlainFileProgressStatus.php