CamerataDB: CloudAsymmetricKeyStorage Class Reference
CloudAsymmetricKeyStorage Class Reference
Key-storage base-class.
Public Member Functions
__construct (private string $appName, protected ILogger $logger, protected IL10N $l, private IConfig $cloudConfig, private SymmetricCryptorInterface $cryptor,)
getKeyPair (string $ownerId, string $keyPassphrase)
{Retrieve an existing private/public key pair from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
array<string, string>
[ 'privateEncryptionKey' => PRIV_KEY, 'publicEncryptionKey' => PUB_KEY ]
}
generateKeyPair (string $ownerId, string $keyPassphrase)
{Initialize a private/public key-pair by either retreiving it from the config-space or generating a new one.The returned private key is already unlocked.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
array<string, string>
[ 'privateEncryptionKey' => PRIV_KEY, 'publicEncryptionKey' => PUB_KEY ]
}
wipeKeyPair (string $ownerId)
{Remove the stored key-pair for the given owner.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
Returns
void
}
getPublicKey (string $ownerId)
{Retrieve an existing pulic key from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
Returns
mixed|null Public key or null if none is found.
}
setPrivateKeyPassphrase (string $ownerId, mixed $privateKey, string $newPassphrase)
{Change the the passphrase of the given unlocked private-key.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
mixed $privateKey Unlocked private key as returned by initializeKeyPair(), getPrivateKey(), generateKeyPair().
string $newPassphrase The new passphrase which protects the newly encrypted key in the storage backend.
Returns
void
}
backupKeyPair (string $ownerId, string $tag='old')
{Make a backup copy.Meant as safe-guard while changing the key and recrypting encrypted data.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $tag Named tag in case one needs more than one backup copy.
Returns
void
}
restoreKeyPair (string $ownerId, string $tag='old')
{Restores a backup previously generated by backupKeyPair().Overwrites the currently active key-pair with the backup copy.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $tag Named tag in case one needs more than one backup copy.
Returns
void
}
getPrivateKey (string $ownerId, string $keyPassphrase)
{Retrieve an existing private key from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
mixed Unlocked private key or null if not found.
}
Data Fields
const NAME_SEPARATOR = ';'
const PUBLIC_ENCRYPTION_KEY = 'publicEncryptionKey'
const PRIVATE_ENCRYPTION_KEY = 'privateEncryptionKey'
Static Public Attributes
static $name = null
Protected Member Functions
createKeyPair ()
Create a key-pair, but don't store it.
unserializeKey (string $rawKeyMaterial, string $which)
Decode the raw data fetch from whatever storage backend.
serializeKey (mixed $key, string $which)
Serialize key to string for storage in whatever storage backend.
Private Member Functions
getUserValue (string $ownerId, string $key, mixed $default=null)
setUserValue (string $ownerId, string $key, mixed $value)
Detailed Description
Key-storage base-class.
Definition at line 37 of file CloudAsymmetricKeyStorage.php.
Constructor & Destructor Documentation
__construct()
__construct (private string $appName, protected ILogger $logger, protected IL10N $l, private IConfig $cloudConfig, private SymmetricCryptorInterface $cryptor)
Definition at line 47 of file CloudAsymmetricKeyStorage.php.
Member Function Documentation
backupKeyPair()
backupKeyPair (string $ownerId, string $tag = 'old')
{Make a backup copy.Meant as safe-guard while changing the key and recrypting encrypted data.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $tag Named tag in case one needs more than one backup copy.
Returns
void
}
Implements AsymmetricKeyStorageInterface.
Definition at line 124 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\getUserValue(), and CloudAsymmetricKeyStorage\setUserValue().
createKeyPair()
createKeyPair () abstract protected
Create a key-pair, but don't store it.
Returns
null|array
Reimplemented in HaliteAsymmetricKeyStorage, and OpenSSLAsymmetricKeyStorage.
Referenced by CloudAsymmetricKeyStorage\generateKeyPair().
generateKeyPair()
generateKeyPair (string $ownerId, string $keyPassphrase)
{Initialize a private/public key-pair by either retreiving it from the config-space or generating a new one.The returned private key is already unlocked.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
array<string, string>
[ 'privateEncryptionKey' => PRIV_KEY, 'publicEncryptionKey' => PUB_KEY ]
}
Implements AsymmetricKeyStorageInterface.
Definition at line 82 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\createKeyPair(), CloudAsymmetricKeyStorage\serializeKey(), and CloudAsymmetricKeyStorage\setUserValue().
getKeyPair()
getKeyPair (string $ownerId, string $keyPassphrase)
{Retrieve an existing private/public key pair from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
array<string, string>
[ 'privateEncryptionKey' => PRIV_KEY, 'publicEncryptionKey' => PUB_KEY ]
}
Implements AsymmetricKeyStorageInterface.
Definition at line 58 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\getPublicKey(), CloudAsymmetricKeyStorage\getUserValue(), and CloudAsymmetricKeyStorage\unserializeKey().
getPrivateKey()
getPrivateKey (string $ownerId, string $keyPassphrase) inherited
{Retrieve an existing private key from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $keyPassphrase The passphrase used to protect the private key.
Returns
mixed Unlocked private key or null if not found.
}
Implements AsymmetricKeyStorageInterface.
Definition at line 31 of file AbstractAsymmetricKeyStorage.php.
References AsymmetricKeyStorageInterface\getKeyPair().
getPublicKey()
getPublicKey (string $ownerId)
{Retrieve an existing pulic key from the key-storage.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
Returns
mixed|null Public key or null if none is found.
}
Implements AsymmetricKeyStorageInterface.
Definition at line 109 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\getUserValue(), and CloudAsymmetricKeyStorage\unserializeKey().
Referenced by CloudAsymmetricKeyStorage\getKeyPair().
getUserValue()
getUserValue (string $ownerId, string $key, mixed $default = null) private
Parameters
string $ownerId
string $key
mixed $default
Returns
mixed
Definition at line 189 of file CloudAsymmetricKeyStorage.php.
Referenced by CloudAsymmetricKeyStorage\backupKeyPair(), CloudAsymmetricKeyStorage\getKeyPair(), CloudAsymmetricKeyStorage\getPublicKey(), and CloudAsymmetricKeyStorage\restoreKeyPair().
restoreKeyPair()
restoreKeyPair (string $ownerId, string $tag = 'old')
{Restores a backup previously generated by backupKeyPair().Overwrites the currently active key-pair with the backup copy.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
string $tag Named tag in case one needs more than one backup copy.
Returns
void
}
Implements AsymmetricKeyStorageInterface.
Definition at line 138 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\getUserValue(), and CloudAsymmetricKeyStorage\setUserValue().
serializeKey()
serializeKey (mixed $key, string $which) abstract protected
Serialize key to string for storage in whatever storage backend.
Parameters
mixed $key
string $which
Returns
string
Reimplemented in HaliteAsymmetricKeyStorage, and OpenSSLAsymmetricKeyStorage.
Referenced by CloudAsymmetricKeyStorage\generateKeyPair(), and CloudAsymmetricKeyStorage\setPrivateKeyPassphrase().
setPrivateKeyPassphrase()
setPrivateKeyPassphrase (string $ownerId, mixed $privateKey, string $newPassphrase)
{Change the the passphrase of the given unlocked private-key.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
mixed $privateKey Unlocked private key as returned by initializeKeyPair(), getPrivateKey(), generateKeyPair().
string $newPassphrase The new passphrase which protects the newly encrypted key in the storage backend.
Returns
void
}
Implements AsymmetricKeyStorageInterface.
Definition at line 116 of file CloudAsymmetricKeyStorage.php.
References CloudAsymmetricKeyStorage\serializeKey(), and CloudAsymmetricKeyStorage\setUserValue().
setUserValue()
setUserValue (string $ownerId, string $key, mixed $value) private
Parameters
string $ownerId
string $key
mixed $value
Returns
void
Definition at line 214 of file CloudAsymmetricKeyStorage.php.
Referenced by CloudAsymmetricKeyStorage\backupKeyPair(), CloudAsymmetricKeyStorage\generateKeyPair(), CloudAsymmetricKeyStorage\restoreKeyPair(), and CloudAsymmetricKeyStorage\setPrivateKeyPassphrase().
unserializeKey()
unserializeKey (string $rawKeyMaterial, string $which) abstract protected
Decode the raw data fetch from whatever storage backend.
Parameters
string $rawKeyMaterial
string $which
Returns
mixed
Reimplemented in HaliteAsymmetricKeyStorage, and OpenSSLAsymmetricKeyStorage.
Referenced by CloudAsymmetricKeyStorage\getKeyPair(), and CloudAsymmetricKeyStorage\getPublicKey().
wipeKeyPair()
wipeKeyPair (string $ownerId)
{Remove the stored key-pair for the given owner.
Parameters
string $ownerId The owner-id. If used for a group then it should be prefixed by '@'.
Returns
void
}
Implements AsymmetricKeyStorageInterface.
Definition at line 101 of file CloudAsymmetricKeyStorage.php.
Field Documentation
$name
string $name = null static
Definition at line 44 of file CloudAsymmetricKeyStorage.php.
NAME_SEPARATOR
const NAME_SEPARATOR = ';'
Definition at line 41 of file CloudAsymmetricKeyStorage.php.
PRIVATE_ENCRYPTION_KEY
const PRIVATE_ENCRYPTION_KEY = 'privateEncryptionKey' inherited
Definition at line 36 of file AsymmetricKeyStorageInterface.php.
PUBLIC_ENCRYPTION_KEY
const PUBLIC_ENCRYPTION_KEY = 'publicEncryptionKey' inherited
Definition at line 35 of file AsymmetricKeyStorageInterface.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Crypto/CloudAsymmetricKeyStorage.php