CamerataDB: SynchronizedProgressStatus Class Reference
SynchronizedProgressStatus Class Reference
Public Member Functions
__construct (IDBConnection $db, $appName, $id=null)
isAttached ()
entity ()
attach ()
Obtain object from database if it is "clean", if it is dirty or new (no id) then create or update the database entry.
detach ()
Remove the wrapped entity from the database.
merge (array $params=[])
Update multiple properties and write them through to the database if we are in $attached state.
__call ($methodName, $args)
{}
find (int $id)
Protected Attributes
$attached
$entity
Detailed Description
See also
OCA\CAFEVDB\Database\Cloud\Synchronized
Definition at line 34 of file SynchronizedProgressStatus.php.
Constructor & Destructor Documentation
__construct()
__construct (IDBConnection $db, $appName, $id = null)
Definition at line 37 of file SynchronizedProgressStatus.php.
Member Function Documentation
__call()
__call ($methodName, $args) inherited
{}
Definition at line 145 of file Synchronized.php.
References Synchronized\entity(), and Synchronized\find().
attach()
attach () inherited
Obtain object from database if it is "clean", if it is dirty or new (no id) then create or update the database entry.
Returns
void
Definition at line 91 of file Synchronized.php.
References Synchronized\entity(), and Synchronized\find().
Referenced by Synchronized\merge().
detach()
detach () inherited
Remove the wrapped entity from the database.
Returns
void
Definition at line 111 of file Synchronized.php.
References Synchronized\entity().
entity()
entity () inherited
Returns
mixed
Definition at line 80 of file Synchronized.php.
Referenced by Synchronized\__call(), Synchronized\attach(), Synchronized\detach(), and Synchronized\merge().
find()
find (int $id) inherited
Parameters
int $id
Returns
mixed
Exceptions
\OCP\AppFramework\Db\DoesNotExistException If not found.
Exceptions
\OCP\AppFramework\Db\MultipleObjectsReturnedException If more than one result.
Definition at line 174 of file Synchronized.php.
Referenced by Synchronized\__call(), and Synchronized\attach().
isAttached()
isAttached () inherited
Returns
bool
Definition at line 74 of file Synchronized.php.
merge()
merge (array $params = []) inherited
Update multiple properties and write them through to the database if we are in $attached state.
If called with no arguments read the entity back from the database, possibly attaching it first.
Parameters
array $params
Returns
void
Definition at line 128 of file Synchronized.php.
References Synchronized\attach(), and Synchronized\entity().
Field Documentation
$attached
bool $attached protected inherited
Definition at line 44 of file Synchronized.php.
$entity
Entity $entity protected inherited
Definition at line 47 of file Synchronized.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Cloud/Synchronized/SynchronizedProgressStatus.php