CamerataDB: ContactsService Class Reference
ContactsService Class Reference
Contacts handling.
Public Member Functions
__construct (ConfigService $configService, IContactsManager $contactsManager, IAppContainer $appContainer, EntityManager $entityManager,)
addressBookByName (string $displayName, bool $includeShared=false)
Find a matching addressbook by its displayname.
addEmailContact (array $emailContact, string $addressBookKey=null)
Add the given email address as possibly new entry to the address book.
flattenVCard (string $cardUri, VCard $vCard, bool $withTypes=true)
importVCard (VCard $vCard)
Import the given vCard into the musician data-base.
export (Musician $musician, string $version=self::VCARD_VERSION)
Export the stored data for one musician as vCard.
Data Fields
const VCARD_VERSION = '4.0'
Private Member Functions
geoCodingService ()
Private Attributes
$appContainer
$contactsManager
Detailed Description
Contacts handling.
Definition at line 50 of file ContactsService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, IContactsManager $contactsManager, IAppContainer $appContainer, EntityManager $entityManager)
Definition at line 64 of file ContactsService.php.
Member Function Documentation
addEmailContact()
addEmailContact (array $emailContact, string $addressBookKey = null)
Add the given email address as possibly new entry to the address book.
Parameters
array $emailContact Contact to be added ‘[ 'name’ => FN, 'email' => EMAIL ]`.
string $addressBookKey If set, the id of the address-book to add entries to. Otherwise the addressbookid config-value will be used. If none is set, return null.
Returns
null|array
Definition at line 192 of file ContactsService.php.
addressBookByName()
addressBookByName (string $displayName, bool $includeShared = false)
Find a matching addressbook by its displayname.
Parameters
string $displayName The display name.
bool $includeShared Include also shared addressbooks.
Returns
null|IAddressBook The address-book object (row of the database, i.e. an array).
Definition at line 93 of file ContactsService.php.
export()
export (Musician $musician, string $version = self::VCARD_VERSION)
Export the stored data for one musician as vCard.
Parameters
Musician $musician One row from the musician table.
string $version vCard version – which must be one supported by \\Sabre\\VObject. Defaults to 3.0 for compatibility reasons. Note that many (mobile) devices still only use the stone-age v2.1 format.
Returns
VCard
Definition at line 528 of file ContactsService.php.
References ContactsService\geoCodingService(), and Musician\getEmail().
flattenVCard()
flattenVCard (string $cardUri, VCard $vCard, bool $withTypes = true)
Parameters
string $cardUri
VCard $vCard
bool $withTypes
Returns
array
Definition at line 219 of file ContactsService.php.
Referenced by ContactsService\importVCard().
geoCodingService()
geoCodingService () private
Returns
GeoCodingService
Definition at line 79 of file ContactsService.php.
Referenced by ContactsService\export().
importVCard()
importVCard (VCard $vCard)
Import the given vCard into the musician data-base.
This is somewhat problematic: the CAFeV DB database does not support fancy fields. Other things: being a layman-orchestra, we prefer private entries for everything and just choose the first stuff available if no personal data is found.
We import the following properties
N, UID, LANG, EMAIL, TEL, REV, ADR, BDAY, CATEGORIES, PHOTO
CATEGORIES are used to code instruments and project membership.
Parameters
VCard $vCard Serialized vCard data.
Returns
null|Entities\Musician entity.
Bug:
Looks complicated like hell. Simplify?
Definition at line 294 of file ContactsService.php.
References ContactsService\flattenVCard().
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 58 of file ContactsService.php.
$contactsManager
IContactsManager $contactsManager private
Definition at line 61 of file ContactsService.php.
VCARD_VERSION
const VCARD_VERSION = '4.0'
Definition at line 55 of file ContactsService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/ContactsService.php