CamerataDB: InMemoryFileNode Class Reference
InMemoryFileNode Class Reference
Dummy file node which only resides in memory.
Public Member Functions
__construct (protected DatabaseStorageFolder|EmptyDirectoryNode $parent, protected string $name, protected string $data, protected string $mimeType, protected DateTimeInterface $updated,)
getName ()
setName (string $name)
getParent ()
setParent (DatabaseStorageFolder $parent)
getFileData ()
getData ()
setData (string $data)
getUpdated ()
setUpdated (DateTimeInterface $updated)
setSize ()
getSize ()
setMimeType (string $mimeType)
getMimeType ()
Detailed Description
Dummy file node which only resides in memory.
Its use currently is to provide automatically generated ReadMe files.
Definition at line 35 of file InMemoryFileNode.php.
Constructor & Destructor Documentation
__construct()
__construct (protected DatabaseStorageFolder|EmptyDirectoryNode $parent, protected string $name, protected string $data, protected string $mimeType, protected DateTimeInterface $updated)
Parameters
DatabaseStorageFolder | EmptyDirectoryNode $parent
string $name
string $data
string $mimeType
null | DateTimeInterface $updated
Definition at line 48 of file InMemoryFileNode.php.
References EmptyDirectoryNode\getUpdated(), and EmptyDirectoryNode\setUpdated().
Member Function Documentation
getData()
getData ()
Returns
string
Definition at line 111 of file InMemoryFileNode.php.
getFileData()
getFileData ()
Returns
InMemoryFileNode
Definition at line 103 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
getMimeType()
getMimeType ()
Returns
string
Definition at line 180 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
getName()
getName ()
Returns
string
Definition at line 63 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
getParent()
getParent ()
Returns
string
Definition at line 83 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
getSize()
getSize ()
Returns
int
Definition at line 160 of file InMemoryFileNode.php.
getUpdated()
getUpdated ()
Returns
DateTimeInterface
Definition at line 131 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
setData()
setData (string $data)
Parameters
string $data
Returns
InMemoryFileNode
Definition at line 121 of file InMemoryFileNode.php.
setMimeType()
setMimeType (string $mimeType)
Parameters
string $mimeType
Returns
InMemoryFileNode
Definition at line 170 of file InMemoryFileNode.php.
setName()
setName (string $name)
Parameters
string $name
Returns
InMemoryFileNode
Definition at line 73 of file InMemoryFileNode.php.
setParent()
setParent (DatabaseStorageFolder $parent)
Parameters
DatabaseStorageFolder $parent
Returns
InMemoryFileNode
Definition at line 93 of file InMemoryFileNode.php.
Referenced by Storage\persistInMemoryFileNode().
setSize()
setSize ()
Returns
InMemoryFileNode
Definition at line 151 of file InMemoryFileNode.php.
setUpdated()
setUpdated (DateTimeInterface $updated)
Parameters
DateTimeInterface $updated
Returns
InMemoryFileNode $this.
Definition at line 141 of file InMemoryFileNode.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Storage/Database/InMemoryFileNode.php