CamerataDB: HaliteAsymmetricCryptor Class Reference
HaliteAsymmetricCryptor Class Reference
Asymmetric encryption using the ParagonIE\Halite library.
Public Member Functions
__construct (?Halite\Asymmetric\SignatureSecretKey $privSignKey=null, ?string $password=null,)
setPrivateKey (mixed $privSignKey, ?string $password=null)
{
Parameters
mixed $privKey
null | string $password Maybe ignored depending on the implementation, i.e. the key may have to be unlocked or decrypted before passing it to the cryptor.
Returns
AsymmetricCryptorInterface $this
}
setPublicKey (mixed $pubSignKey)
{
Parameters
mixed $pubKey
Returns
AsymmetricCryptorInterface $this
}
getPublicKey ()
{
Returns
mixed Return the currently used public key.
}
encrypt (?string $decryptedData)
{
Parameters
null | string $data
Returns
null|string
}
sign ($data)
{}
verify ($data, string $signature)
{}
canEncrypt ()
{
Returns
bool
}
canDecrypt ()
{
Returns
bool
}
canSign ()
{
Returns
bool
}
canVerify ()
{
Returns
bool
}
sign (?string $data)
verify (?string $data, string $signature)
decrypt (?string $data)
Static Public Member Functions
static isEncrypted (?string $data)
{Determines if the given data has been encrypted by this cryptor instance.A returned null means "don't know".
Parameters
null||string $data
Returns
null|bool
}
Private Attributes
$privSignKey = null
$pubSignKey = null
$privEncKey = null
$pubEncKey = null
Detailed Description
Asymmetric encryption using the ParagonIE\Halite library.
Definition at line 33 of file HaliteAsymmetricCryptor.php.
Constructor & Destructor Documentation
__construct()
__construct (?Halite\Asymmetric\SignatureSecretKey $privSignKey = null, ?string $password = null)
Parameters
null | Halite\\Asymmetric\\SignatureSecretKey $privSignKey
null | string $password
Definition at line 52 of file HaliteAsymmetricCryptor.php.
References HaliteAsymmetricCryptor\setPrivateKey().
Member Function Documentation
canDecrypt()
canDecrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 152 of file HaliteAsymmetricCryptor.php.
Referenced by HaliteAsymmetricCryptor\canSign().
canEncrypt()
canEncrypt ()
{
Returns
bool
}
Implements ICryptor.
Definition at line 146 of file HaliteAsymmetricCryptor.php.
Referenced by HaliteAsymmetricCryptor\canVerify().
canSign()
canSign ()
{
Returns
bool
}
Implements AsymmetricCryptorInterface.
Definition at line 158 of file HaliteAsymmetricCryptor.php.
References HaliteAsymmetricCryptor\canDecrypt().
canVerify()
canVerify ()
{
Returns
bool
}
Implements AsymmetricCryptorInterface.
Definition at line 164 of file HaliteAsymmetricCryptor.php.
References HaliteAsymmetricCryptor\canEncrypt().
decrypt()
decrypt (?string $data) inherited
Parameters
null | string $data
Returns
null|string
Implemented in CloudSymmetricCryptor, HaliteSymmetricStreamCryptor, SealCryptor, and OpenSSLAsymmetricCryptor.
Referenced by SealService\unseal().
encrypt()
encrypt (?string $decryptedData)
{
Parameters
null | string $data
Returns
null|string
}
Implements ICryptor.
Definition at line 97 of file HaliteAsymmetricCryptor.php.
getPublicKey()
getPublicKey ()
{
Returns
mixed Return the currently used public key.
}
Implements AsymmetricCryptorInterface.
Definition at line 91 of file HaliteAsymmetricCryptor.php.
isEncrypted()
static isEncrypted (?string $data) static
{Determines if the given data has been encrypted by this cryptor instance.A returned null means "don't know".
Parameters
null||string $data
Returns
null|bool
}
Implements ICryptor.
Definition at line 170 of file HaliteAsymmetricCryptor.php.
setPrivateKey()
setPrivateKey (mixed $privSignKey, ?string $password = null)
{
Parameters
mixed $privKey
null | string $password Maybe ignored depending on the implementation, i.e. the key may have to be unlocked or decrypted before passing it to the cryptor.
Returns
AsymmetricCryptorInterface $this
}
The paramter $password is ignored and must be kept at null.
Implements AsymmetricCryptorInterface.
Definition at line 64 of file HaliteAsymmetricCryptor.php.
Referenced by HaliteAsymmetricCryptor\__construct().
setPublicKey()
setPublicKey (mixed $pubSignKey)
{
Parameters
mixed $pubKey
Returns
AsymmetricCryptorInterface $this
}
Implements AsymmetricCryptorInterface.
Definition at line 79 of file HaliteAsymmetricCryptor.php.
sign() [1/2]
sign ($data)
{}
Definition at line 125 of file HaliteAsymmetricCryptor.php.
sign() [2/2]
sign (?string $data) inherited
Parameters
null | string $data
Returns
string
verify() [1/2]
verify ($data, string $signature)
{}
Definition at line 135 of file HaliteAsymmetricCryptor.php.
verify() [2/2]
verify (?string $data, string $signature) inherited
Parameters
null | string $data
string $signature
Returns
string
Field Documentation
$privEncKey
Halite Asymmetric EncryptionSecretKey $privEncKey = null private
Definition at line 42 of file HaliteAsymmetricCryptor.php.
$privSignKey
Halite Asymmetric SignatureSecretKey $privSignKey = null private
Definition at line 36 of file HaliteAsymmetricCryptor.php.
$pubEncKey
Halite Asymmetric EncryptionPublicKey $pubEncKey = null private
Definition at line 45 of file HaliteAsymmetricCryptor.php.
$pubSignKey
Halite Asymmetric SignaturePublicKey $pubSignKey = null private
Definition at line 39 of file HaliteAsymmetricCryptor.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-28/apps/cafevdb/lib/Crypto/HaliteAsymmetricCryptor.php