CamerataDB: AppStorage Class Reference
AppStorage Class Reference
App-storage wrapper in order to have a common interface with the user-storage.
Public Member Functions
__construct (IAppData $appData, ILogger $logger, IL10N $l10n,)
ensureFolder (string $name)
Ensure a folder exists withtout throwing an exception.
newTemporaryFile (string $folderName)
Generate a random file.
fileExistsInFolder (string $dirName, string $fileName)
uploadExists (string $fileName)
draftExists (string $fileName)
newUploadFile ()
getUploadFile (string $name)
newDraftsFile ()
getDraftsFile (string $name)
moveFileSystemFile (string $srcFile, ISimpleFile $dstFile)
Move the contents of a "real" file to the given app-folder.
copyFileSystemFile (string $srcFile, ISimpleFile $dstFile)
Copy the contents of a "real" file to the given app-folder.
getFolder (string $name)
Get the folder with name $name.
getDirectoryListing ()
Get all the Folders.
newFolder (string $name)
Create a new folder named $name.
getTemporaryDirectory ()
Return a system-directory path to temporary storage.
Data Fields
const PATH_SEP = '/'
const UPLOAD_FOLDER = 'uploads'
const DRAFTS_FOLDER = 'drafts'
Private Attributes
$appData
$uploadFolder
$draftsFolder
Detailed Description
App-storage wrapper in order to have a common interface with the user-storage.
Todo:
Maybe this class should not exists. Check whether its methods are used.
Definition at line 46 of file AppStorage.php.
Constructor & Destructor Documentation
__construct()
__construct (IAppData $appData, ILogger $logger, IL10N $l10n)
Definition at line 64 of file AppStorage.php.
Member Function Documentation
copyFileSystemFile()
copyFileSystemFile (string $srcFile, ISimpleFile $dstFile)
Copy the contents of a "real" file to the given app-folder.
Parameters
string $srcFile
ISimpleFile $dstFile
Returns
ISimpleFile
Definition at line 285 of file AppStorage.php.
draftExists()
draftExists (string $fileName)
Parameters
string $fileName
Returns
bool
Definition at line 199 of file AppStorage.php.
References AppStorage\fileExistsInFolder().
ensureFolder()
ensureFolder (string $name)
Ensure a folder exists withtout throwing an exception.
Parameters
string $name Folder name.
Returns
ISimpleFolder
Definition at line 88 of file AppStorage.php.
References AppStorage\getFolder(), and AppStorage\newFolder().
Referenced by AppStorage\newTemporaryFile().
fileExistsInFolder()
fileExistsInFolder (string $dirName, string $fileName)
Parameters
string $dirName
string $fileName
Returns
bool
Definition at line 172 of file AppStorage.php.
Referenced by AppStorage\draftExists(), and AppStorage\uploadExists().
getDirectoryListing()
getDirectoryListing ()
Get all the Folders.
Returns
ISimpleFolder[]
Exceptions
NotFoundException
\RuntimeException
Definition at line 314 of file AppStorage.php.
getDraftsFile()
getDraftsFile (string $name)
Parameters
string $name
Returns
ISimpleFile
Definition at line 233 of file AppStorage.php.
getFolder()
getFolder (string $name)
Get the folder with name $name.
Parameters
string $name
Returns
ISimpleFolder
Exceptions
NotFoundException
\RuntimeException
Definition at line 301 of file AppStorage.php.
Referenced by AppStorage\ensureFolder().
getTemporaryDirectory()
getTemporaryDirectory ()
Return a system-directory path to temporary storage.
Returns
string
Definition at line 339 of file AppStorage.php.
getUploadFile()
getUploadFile (string $name)
Parameters
string $name
Returns
ISimpleFile
Definition at line 216 of file AppStorage.php.
moveFileSystemFile()
moveFileSystemFile (string $srcFile, ISimpleFile $dstFile)
Move the contents of a "real" file to the given app-folder.
Parameters
string $srcFile
ISimpleFile $dstFile
Returns
ISimpleFile
Definition at line 269 of file AppStorage.php.
newDraftsFile()
newDraftsFile ()
Returns
ISimpleFile
Definition at line 222 of file AppStorage.php.
newFolder()
newFolder (string $name)
Create a new folder named $name.
Parameters
string $name
Returns
ISimpleFolder
Exceptions
NotPermittedException
\RuntimeException
Definition at line 329 of file AppStorage.php.
Referenced by AppStorage\ensureFolder().
newTemporaryFile()
newTemporaryFile (string $folderName)
Generate a random file.
Parameters
string $folderName The name of the parent-folder of the new file. in.
Returns
ISimpleFile
Definition at line 106 of file AppStorage.php.
References AppStorage\ensureFolder().
newUploadFile()
newUploadFile ()
Returns
ISimpleFile
Definition at line 205 of file AppStorage.php.
uploadExists()
uploadExists (string $fileName)
Parameters
string $fileName
Returns
bool
Definition at line 189 of file AppStorage.php.
References AppStorage\fileExistsInFolder().
Field Documentation
$appData
IAppData $appData private
Definition at line 55 of file AppStorage.php.
$draftsFolder
IFolder $draftsFolder private
Definition at line 61 of file AppStorage.php.
$uploadFolder
IFolder $uploadFolder private
Definition at line 58 of file AppStorage.php.
DRAFTS_FOLDER
const DRAFTS_FOLDER = 'drafts'
Definition at line 52 of file AppStorage.php.
PATH_SEP
const PATH_SEP = '/'
Definition at line 50 of file AppStorage.php.
UPLOAD_FOLDER
const UPLOAD_FOLDER = 'uploads'
Definition at line 51 of file AppStorage.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Storage/AppStorage.php