CamerataDB: IProgressStatus Interface Reference
IProgressStatus Interface Reference
Simplistic progress-status interface.
Public Member Functions
delete ()
Delete the underlying storage object.
bind (mixed $id)
Bind to the given storage object.
getId ()
Obtain a unique but opaque identifier (e.g.
update (int $current, ?int $target=null, ?array $data=null)
Update to the given values, where null arguments are simply ignored.
increment (int $delta=1)
Add the given amount to the progress-status counter.
sync ()
Synchronize with the underlying storage, i.e.
getCurrent ()
Return the cached value of the current state.
setCurrent (int $current)
Set the current value and sync.
getTarget ()
Return the cached value of the target state.
setTarget (int $target)
Set the target value and sync.
getData ()
Return the cached value of the custom data, i.e.
setData (array $data)
Set the data value and sync.
getLastModified ()
Return the cached value of the last modification time.
Detailed Description
Simplistic progress-status interface.
Definition at line 32 of file IProgressStatus.php.
Member Function Documentation
bind()
bind (mixed $id)
Bind to the given storage object.
Create a new object if $id is null.
Parameters
mixed $id Opaque data identifying the progress status object.
Returns
void
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
delete()
delete ()
Delete the underlying storage object.
Afterwards any operation except $this->bind() will exhibit undefined behaviour.
Returns
void
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
getCurrent()
getCurrent ()
Return the cached value of the current state.
Returns
int
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
Referenced by AbstractProgressStatus\increment(), ProgressStatusController\progressResponse(), AbstractProgressStatus\setData(), and AbstractProgressStatus\setTarget().
getData()
getData ()
Return the cached value of the custom data, i.e.
the data previously passed to update().
Returns
null|array
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
Referenced by ProgressStatusController\progressResponse().
getId()
getId ()
Obtain a unique but opaque identifier (e.g.
the id column in a database up to a serialized representation).
Returns
mixed
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
Referenced by ProgressStatusController\progressResponse().
getLastModified()
getLastModified ()
Return the cached value of the last modification time.
Returns
DateTimeInterface
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
getTarget()
getTarget ()
Return the cached value of the target state.
Returns
int
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
Referenced by ProgressStatusController\progressResponse(), and AbstractProgressStatus\setData().
increment()
increment (int $delta = 1)
Add the given amount to the progress-status counter.
Parameters
int $delta Amount to add, defaults to 1. Negative values are allowed.
Returns
bool|int Current value of the counter or false if the underlying storage has been deleted.
Implemented in AbstractProgressStatus.
setCurrent()
setCurrent (int $current)
Set the current value and sync.
Parameters
int $current
Returns
void
Implemented in AbstractProgressStatus.
setData()
setData (array $data)
Set the data value and sync.
Parameters
array $data
Returns
void
Implemented in AbstractProgressStatus.
setTarget()
setTarget (int $target)
Set the target value and sync.
Parameters
int $target
Returns
void
Implemented in AbstractProgressStatus.
sync()
sync ()
Synchronize with the underlying storage, i.e.
read the data into this instance.
Returns
void
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
update()
update (int $current, ?int $target = null, ?array $data = null)
Update to the given values, where null arguments are simply ignored.
This function has to write the given values through to the underlying storage.
Parameters
int $current
null | int $target If null the target remains unchanged.
null | array $data "user"-data stored in the progress-status object. Can be retrieved later via getData(). If null then the currently stored data remains unchanged.
Returns
bool true on success, false if the underlying storage has been deleted.
Implemented in DatabaseProgressStatus, DoNothingProgressStatus, and PlainFileProgressStatus.
Referenced by AbstractProgressStatus\increment(), AbstractProgressStatus\setCurrent(), AbstractProgressStatus\setData(), and AbstractProgressStatus\setTarget().
The documentation for this interface was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/IProgressStatus.php