CamerataDB: OCA\CAFEVDB\Toolkit\Traits Namespace Reference
OCA\CAFEVDB\Toolkit\Traits Namespace Reference
A collection of reusable traits classes for Nextcloud apps.
Data Structures
class Constants
A couple of constants in order to avoid string literals.
Functions
isNonInteractiveRequest (IRequest $request, string $logLevel=LogLevel::DEBUG)
In order to avoid request ping-pong the auto-login should only be attempted for UI logins.
initializeAssets (string $classDir)
Read and parse the asset-meta information file.
getAsset (string $type, string $baseName)
getJSAsset (string $baseName)
getCSSAsset (string $baseName)
authenticate (InputInterface $input, OutputInterface $output)
{}
getAuthToken (string $cookieName, string $tokenName, int $tokenExpiry)
Fetch the login credentials from the credentials store and generate a login-token from it.
getAuthCookie (string $cookieName, int $expires)
Get or generate a cookie, e.g.
deleteAuthCookie (string $cookieName)
deleteAuthToken (string $passphrase)
Delete any auth token secured with the given passphrase.
getLoginCredentialsFromToken (string $passphrase)
Try to fetch the login-credentials contained in the auth token which is secured with the given password.
getCloudAdmins ()
Return all admin users.
getCloudAdminContacts (bool $implode=false)
Contact information for the overall admins.
logger ()
Return the stored logger class.
mapLogLevels (mixed $level)
Map PSR log-levels to ILogger log-levels as the PsrLoggerAdapter only understands those.
log (mixed $level, string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log the given message at the specified level.
logException (Throwable $exception, string $message=null, int $shift=0, bool $showTrace=false, mixed $level=LogLevel::ERROR,)
logError (string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log an error.
logDebug (string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log a debug message.
logInfo (string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log an informational message.
logWarn (string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log a warning message.
logFatal (string $message, array $context=[], int $shift=0, bool $showTrace=false)
Log a fatal error message.
formatNode (Node $node)
Stolen from the template-manager.
templateResponse (string $templateName, array $params=[], string $renderAs='blank', ?string $appName=null, ?IL10N $l10n=null,)
dataDownloadResponse (string $data, string $fileName, string $contentType,)
exceptionResponse (Throwable $throwable, string $renderAs, ?string $method=null,)
Return an HTML error page, populated with the exception data.
exceptionChainData (Throwable $throwable, bool $top=true)
Convert a potentially nested exception into a nested array to ease post-processing.
static dataResponse (array $data, int $status=Http::STATUS_OK)
static valueResponse (mixed $value, ?string $message='', int $status=Http::STATUS_OK,)
static response (mixed $message, int $status=Http::STATUS_OK)
static grumble (mixed $message, mixed $value=null, int $status=Http::STATUS_BAD_REQUEST,)
static getResponseMessages (DataResponse $response)
getUserFolder ()
getUserRootFolder ()
getUserAppFolder ()
getUserTopLevelFolder (string $name)
Return the name top-level folder as Folder instance.
getUserFolderPath (?string $userId=null)
static dashesToCamelCase (string $string, bool $capitalizeFirstCharacter=false, string $dashes='_-')
Take any dashed or "underscored" lower-case string and convert to camel-case.
static camelCaseToDashes (string $string, string $separator='-')
Take an camel-case string and convert to lower-case with dashes or underscores between the words.
getLocale ()
Return the locale as string, e.g.
transliterate (string $string, string $locale=null)
Transliterate the given string to the given or default locale.
floatValue (string $value, ?string $locale=null)
Try to parse a floating point value.
storageValue (?string $value, ?string $locale=null)
Parse a storage user input value and return its value in bytes.
formatStorageValue (int $bytes, string $format='binary', int $digits=2, ?string $locale=null)
static unsetValue (array &$hayStack, mixed $value)
Unset all array elements with value $value.
getCommonPath (array $paths, bool $leadingSlash=true)
getClassBaseName ($classOrClassName)
replaceBracedPlaceholders (string $template, array $templateValues, ?array $l10nTemplateKeys=null,)
Replace braced placeholders in a template string.
translateBracedTemplate (string $template, ?array $l10nTemplateKeys)
Translate the braced placeholders contained in the given $template to the array values supplied by the $l10nTemplateKeys, that is, the keys of $l10nTemplateKeys matching the braced placeholders contained in $template will be replaced by their respective array value.
untranslateBracedTemplate (string $template, ?array $l10nTemplateKeys)
Translate the braced placeholders contained in the given $template to the array keys supplied by the $l10nTemplateKeys, that is, the array values of $l10nTemplateKeys matching the braced placeholders contained in $template will be replaced by their respective array key.
rgbaStringToArray (string $rgbaString)
rgbaArrayToString (array $rgbaArray)
Variables
trait ApiRequestTrait
Trait with some helpers to deal with non-interactive requests.
trait AssetTrait
Return JavaScript- and CSS-assets names dealing with attached content hashes.
IL10N $l
$assets = []
trait AuthenticatedCommandTrait
Trait in order to handle authentication with the cloud.
IUserManager $userManager
IUserSession $userSession
string $userId
string $userPassword
trait AuthTokenTrait
Trait for obtaining a cookie secured auth-token.
TokenProvider $tokenProvider
CredentialsStore $credentialsStore
IRequest $request
ISecureRandom $secureRandom
trait CloudAdminTrait
Utitlity trait in order to get the addresses of the cloud admins.
trait LoggerTrait
Utitily trait to simplifiy logging somewhat.
trait NodeTrait
Helper trait for file-system nodes.
IPreview $previewManager
IRootFolder $rootFolder
trait ResponseTrait
Utility class to ease constructing HTTP responses.
const RENDER_AS_BLANK = 'blank'
const RENDER_AS_BASE = TemplateResponse::RENDER_AS_BASE
const RENDER_AS_USER = TemplateResponse::RENDER_AS_USER
const RENDER_AS_ERROR = TemplateResponse::RENDER_AS_ERROR
const RENDER_AS_PUBLIC = TemplateResponse::RENDER_AS_PUBLIC
const APPNAME_PREFIX = 'app-'
$appName
trait UserRootFolderTrait
The actual user folder is USER_ROOT/files/.
Folder $userRootFolder
Folder $userFolder
trait UtilTrait
Trait for some general nice-to-have functions.
Detailed Description
A collection of reusable traits classes for Nextcloud apps.
Some PHP utility functions for Nextcloud apps.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022, 2023 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022, 2023, 2024 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2023 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2024 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
authenticate()
authenticate (InputInterface $input, OutputInterface $output) protected
{}
See also
execute()
Definition at line 61 of file AuthenticatedCommandTrait.php.
camelCaseToDashes()
static camelCaseToDashes (string $string, string $separator = '-') static protected
Take an camel-case string and convert to lower-case with dashes or underscores between the words.
First letter may or may not be upper case.
Parameters
string $string String to work on.
string $separator Separator to use, defaults to '-'.
Returns
string
Definition at line 72 of file UtilTrait.php.
dashesToCamelCase()
static dashesToCamelCase (string $string, bool $capitalizeFirstCharacter = false, string $dashes = '_-') static protected
Take any dashed or "underscored" lower-case string and convert to camel-case.
Parameters
string $string the string to convert.
bool $capitalizeFirstCharacter self explaining.
string $dashes Characters to replace.
Returns
string
Definition at line 50 of file UtilTrait.php.
dataDownloadResponse()
dataDownloadResponse (string $data, string $fileName, string $contentType) protected
Parameters
string $data Data-blob.
string $fileName Proposed download filename.
string $contentType MIME-type of content.
Returns
Http\DataDownloadResponse
Definition at line 108 of file ResponseTrait.php.
dataResponse()
static dataResponse (array $data, int $status = Http::STATUS_OK) static protected
Parameters
array $data
int $status Default is Http::STATUS_OK.
Returns
DataResponse
Definition at line 193 of file ResponseTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\response().
deleteAuthCookie()
deleteAuthCookie (string $cookieName) protected
Parameters
string $cookieName Unset the cookie with the given name.
Returns
void
Definition at line 139 of file AuthTokenTrait.php.
deleteAuthToken()
deleteAuthToken (string $passphrase) protected
Delete any auth token secured with the given passphrase.
Parameters
string $passphrase Token passphrase.
Returns
void
Definition at line 157 of file AuthTokenTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\logException(), and OCA\CAFEVDB\Toolkit\Traits\logger().
Referenced by UserScopeService\deleteAuthCookie().
exceptionChainData()
exceptionChainData (Throwable $throwable, bool $top = true) protected
Convert a potentially nested exception into a nested array to ease post-processing.
Parameters
Throwable $throwable
bool $top If \true then this is the top-level invocation.
Returns
array
Definition at line 171 of file ResponseTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\exceptionChainData().
Referenced by OCA\CAFEVDB\Toolkit\Traits\exceptionChainData().
exceptionResponse()
exceptionResponse (Throwable $throwable, string $renderAs, ?string $method = null) protected
Return an HTML error page, populated with the exception data.
This only works if a traditional "errorpage.php" file exists in the templates/ directory.
Parameters
Throwable $throwable
string $renderAs
null | string $method
Returns
TemplateResponse
Definition at line 136 of file ResponseTrait.php.
floatValue()
floatValue (string $value, ?string $locale = null)
Try to parse a floating point value.
Parameters
string $value Input value. Maybe a percentage.
null | string $locale
Returns
bool|float
Definition at line 123 of file UtilTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getLocale().
Referenced by OCA\CAFEVDB\Toolkit\Traits\storageValue().
formatNode()
formatNode (Node $node) protected
Stolen from the template-manager.
Parameters
Node $node
Returns
array
Exceptions
NotFoundException
\OCP\Files\InvalidPathException
Definition at line 54 of file NodeTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getUserAppFolder(), and OCA\CAFEVDB\Toolkit\Traits\getUserFolder().
formatStorageValue()
formatStorageValue (int $bytes, string $format = 'binary', int $digits = 2, ?string $locale = null) protected
Parameters
int $bytes The size in bytes to format.
string $format If \true then binary prefixes are used (kib, mib, etc.).
int $digits Number of fractinal digits.
null | string $locale Locale to use to format fractional numbers.
Returns
null|string The human readable storage size.
See also
storageValue()
Definition at line 240 of file UtilTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getLocale().
getAsset()
getAsset (string $type, string $baseName) protected
Parameters
string $type js or css.
string $baseName
Returns
array
Definition at line 99 of file AssetTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\getCSSAsset(), and OCA\CAFEVDB\Toolkit\Traits\getJSAsset().
getAuthCookie()
getAuthCookie (string $cookieName, int $expires) protected
Get or generate a cookie, e.g.
to use it as a passphrase for a login token.
Parameters
string $cookieName
int $expires
Returns
string The value of the cookie.
Definition at line 108 of file AuthTokenTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\getAuthToken().
getAuthToken()
getAuthToken (string $cookieName, string $tokenName, int $tokenExpiry) protected
Fetch the login credentials from the credentials store and generate a login-token from it.
Parameters
string $cookieName The name of the client cookie providing the token password.
string $tokenName Fancy token name.
int $tokenExpiry Faked token activity to set in order to prevent expiry before that time. Unix timestamp.
Returns
array The generated or fetched auth token and token-passphrase as
[ 'token' => TOKEN, 'passphrase' => PASSPHRASE ]
Definition at line 71 of file AuthTokenTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getAuthCookie(), OCA\CAFEVDB\Toolkit\Traits\logException(), and OCA\CAFEVDB\Toolkit\Traits\logger().
getClassBaseName()
getClassBaseName ($classOrClassName) protected
Parameters
string | mixed $classOrClassName
Returns
string The "basename" of the given class or class-name.
Definition at line 350 of file UtilTrait.php.
Referenced by ArchiveService\getArchiveInfo().
getCloudAdminContacts()
getCloudAdminContacts (bool $implode = false) protected
Contact information for the overall admins.
Parameters
bool $implode
Returns
mixed
Definition at line 57 of file CloudAdminTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getCloudAdmins().
getCloudAdmins()
getCloudAdmins () protected
Return all admin users.
Returns
array<int, IUser>
Definition at line 44 of file CloudAdminTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\getCloudAdminContacts().
getCommonPath()
getCommonPath (array $paths, bool $leadingSlash = true) protected
Parameters
array $paths Array of path names.
bool $leadingSlash If \false the $paths array elements do not start with a slash.
Returns
string The common directory prefix. An empty string if the path-names do not share any common prefix.
Definition at line 326 of file UtilTrait.php.
Referenced by ArchiveService\getCommonDirectoryPrefix().
getCSSAsset()
getCSSAsset (string $baseName) protected
Parameters
string $baseName
Returns
array
Definition at line 126 of file AssetTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getAsset().
getJSAsset()
getJSAsset (string $baseName) protected
Parameters
string $baseName
Returns
array
Definition at line 116 of file AssetTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getAsset().
getLocale()
getLocale () protected
Return the locale as string, e.g.
de_DE.UTF-8.
Returns
string
Definition at line 82 of file UtilTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\floatValue(), OCA\CAFEVDB\Toolkit\Traits\formatStorageValue(), and OCA\CAFEVDB\Toolkit\Traits\transliterate().
getLoginCredentialsFromToken()
getLoginCredentialsFromToken (string $passphrase) protected
Try to fetch the login-credentials contained in the auth token which is secured with the given password.
Parameters
string $passphrase
Returns
array
[ 'loginUID' => LOGIN_UID, 'loginPassword' => LOGIN_PASSWORD ]
Definition at line 181 of file AuthTokenTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\logException(), and OCA\CAFEVDB\Toolkit\Traits\logger().
getResponseMessages()
static getResponseMessages (DataResponse $response) static protected
Parameters
DataResponse $response
Returns
array
Todo
Remove message/messages duplication.
Definition at line 300 of file ResponseTrait.php.
getUserAppFolder()
getUserAppFolder ()
Returns
Folder The app folder in the user's root-storage
Definition at line 77 of file UserRootFolderTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getUserTopLevelFolder().
Referenced by OCA\CAFEVDB\Toolkit\Traits\formatNode().
getUserFolder()
getUserFolder ()
Returns
Folder The user-folder
Definition at line 59 of file UserRootFolderTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\formatNode(), and OCA\CAFEVDB\Toolkit\Traits\getUserRootFolder().
getUserFolderPath()
getUserFolderPath (?string $userId = null)
Parameters
null | string $userId The user-id. If null then $this->userId is used.
Returns
string Just the name of the user folder without recursing to the file system. Thus the returned folder-name does not neccessarily point to an existing folder. The returned path is relative to the root-folder without a leading slash, e.g. "jane.doe/files".
Definition at line 109 of file UserRootFolderTrait.php.
getUserRootFolder()
getUserRootFolder ()
Returns
Folder The parent of the user-folder.
Definition at line 68 of file UserRootFolderTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getUserFolder().
Referenced by OCA\CAFEVDB\Toolkit\Traits\getUserTopLevelFolder().
getUserTopLevelFolder()
getUserTopLevelFolder (string $name)
Return the name top-level folder as Folder instance.
The folder is created if it does not exist.
Parameters
string $name
Returns
Folder
Definition at line 90 of file UserRootFolderTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getUserRootFolder().
Referenced by OCA\CAFEVDB\Toolkit\Traits\getUserAppFolder().
grumble()
static grumble (mixed $message, mixed $value = null, int $status = Http::STATUS_BAD_REQUEST) static protected
Parameters
null | string | array $message
mixed $value
int $status Default is Http::STATUS_BAD_REQUEST.
Returns
DataResponse
See also
dataResponse()
Todo
Remove message/messages duplication.
Definition at line 271 of file ResponseTrait.php.
initializeAssets()
initializeAssets (string $classDir) protected
Read and parse the asset-meta information file.
Its location is determined from $classDir.
Parameters
string $classDir The value of DIR of the using class.
Returns
void
Definition at line 66 of file AssetTrait.php.
isNonInteractiveRequest()
isNonInteractiveRequest (IRequest $request, string $logLevel = LogLevel::DEBUG) private
In order to avoid request ping-pong the auto-login should only be attempted for UI logins.
Parameters
IRequest $request
string $logLevel
Returns
bool
Definition at line 46 of file ApiRequestTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
log()
log (mixed $level, string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log the given message at the specified level.
Parameters
mixed $level
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 96 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\logger(), and OCA\CAFEVDB\Toolkit\Traits\mapLogLevels().
Referenced by OCA\CAFEVDB\Toolkit\Traits\isNonInteractiveRequest(), OCA\CAFEVDB\Toolkit\Traits\logDebug(), OCA\CAFEVDB\Toolkit\Traits\logError(), OCA\CAFEVDB\Toolkit\Traits\logFatal(), OCA\CAFEVDB\Toolkit\Traits\logInfo(), and OCA\CAFEVDB\Toolkit\Traits\logWarn().
logDebug()
logDebug (string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log a debug message.
Parameters
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 179 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
Referenced by GroupFoldersService\changeFolderManager(), GroupFoldersService\fetchFolders(), GroupFoldersService\getFolder(), GroupFoldersService\getFolderById(), and GroupFoldersService\searchFolders().
logError()
logError (string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log an error.
Parameters
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 164 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
Referenced by MimeTypeService\getSupportedArchiveMimeTypes().
logException()
logException (Throwable $exception, string $message = null, int $shift = 0, bool $showTrace = false, mixed $level = LogLevel::ERROR)
Parameters
\\Throwable $exception
string $message
int $shift
bool $showTrace
mixed $level
Returns
void
Todo
Remove the unused $shift and $showTrace parameters.
Definition at line 132 of file LoggerTrait.php.
Referenced by GroupFoldersService\changeMountPoint(), OCA\CAFEVDB\Toolkit\Traits\deleteAuthToken(), OCA\CAFEVDB\Toolkit\Traits\getAuthToken(), OCA\CAFEVDB\Toolkit\Traits\getLoginCredentialsFromToken(), and MimeTypeService\getMimeTypeMapping().
logFatal()
logFatal (string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log a fatal error message.
Parameters
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 224 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
logger()
logger ()
Return the stored logger class.
Returns
LoggerInterface
Definition at line 45 of file LoggerTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\deleteAuthToken(), OCA\CAFEVDB\Toolkit\Traits\getAuthToken(), OCA\CAFEVDB\Toolkit\Traits\getLoginCredentialsFromToken(), and OCA\CAFEVDB\Toolkit\Traits\log().
logInfo()
logInfo (string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log an informational message.
Parameters
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 194 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
Referenced by MimeTypeService\getMimeTypeMapping(), MimeTypeService\getSupportedArchiveMimeTypes(), and OCA\CAFEVDB\Toolkit\Traits\storageValue().
logWarn()
logWarn (string $message, array $context = [], int $shift = 0, bool $showTrace = false)
Log a warning message.
Parameters
string $message
array $context
int $shift
bool $showTrace
Returns
void
Definition at line 209 of file LoggerTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\log().
Referenced by MimeTypeService\getSupportedArchiveMimeTypes().
mapLogLevels()
mapLogLevels (mixed $level) protected
Map PSR log-levels to ILogger log-levels as the PsrLoggerAdapter only understands those.
Parameters
mixed $level
Returns
mixed
Definition at line 58 of file LoggerTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\log().
replaceBracedPlaceholders()
replaceBracedPlaceholders (string $template, array $templateValues, ?array $l10nTemplateKeys = null) protected
Replace braced placeholders in a template string.
The general syntax of a replacement is {[C[N]|]KEY[|M[D]][@FILTER]} where anything in square brackets is optional.
'C' is any character used for optional padding to the left.
'N' is the padding length. If ommitted, the value of 1 is assumed.
'KEY' is the replacement key
'FILTER' can be either
a single character which is used to replace occurences of '/' in the replacement for KEY
two characters, in which the first character is used as replacement for the second character in the replacement value of KEY
the hash-algo passed to the PHP hash($algo, $data) in which case the replacement value is the hash w.r.t. FILTER of the replacement data
'M' is a number of "path" components to include from the right from the expansion of KEY with path-delimiter 'D' (default: "/"). "{KEY|2}" for the value "foo/bar/foobar" would result in "bar/foobar".
Parameters
string $template
array $templateValues An array of replacement values:
[ KEY1 => VALUE1, KEY2 => [ 'value' => VALUE2, 'padding' => NUMBER|OTHER_KEY ], ... ]
where the second varian specifies a default padding either as number or implicitly as reference to another key in which case the default padding is the strlen() of the replacement value of the other key. If any value is a \DateTimeInterface then it will be formatted by interpreting any FILTER as format string with default 'c'.
Parameters
null | array $l10nTemplateKeys Optional translated keys as
[
   TRANSLATED_KEY => ORIGINAL_KEY
]
The template may contain translated keys, but the $templateValues replacement array must not contain translated keys.
Returns
string
See also
\DateTimeInterface::format()
Definition at line 403 of file UtilTrait.php.
response()
static response (mixed $message, int $status = Http::STATUS_OK) static protected
Parameters
mixed $message
int $status Default is Http::STATUS_OK.
Returns
DataResponse
See also
dataResponse()
Definition at line 238 of file ResponseTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\dataResponse().
rgbaArrayToString()
rgbaArrayToString (array $rgbaArray) protected
Parameters
array $rgbaArray RGB(A) data with values between 0 and 255 (8-bit color data). The "A" (opacity) value is optional. The input array is a flat number array with 3 or 4 components.
Returns
string Encoded RGB(A) color string in the format "#RRGGBBAA". The "AA" is only there if the input array has 4 components.
Definition at line 542 of file UtilTrait.php.
rgbaStringToArray()
rgbaStringToArray (string $rgbaString) protected
Parameters
string $rgbaString RGBA color value in the format "#RRGGBBAA". The "A" (opacity) value is optional.
Returns
array Decoded RGBA color array.
Definition at line 509 of file UtilTrait.php.
storageValue()
storageValue (?string $value, ?string $locale = null)
Parse a storage user input value and return its value in bytes.
Parameters
null | string $value Input value.
null | string $locale Locale or null for the user's default locale.
Returns
null|int|float
if the passed value is null or the empty string then the function returns null.
if otherwise an error occurs during parsing, null is returned
otherwise the storage value in bytes is returned
Definition at line 172 of file UtilTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\floatValue(), and OCA\CAFEVDB\Toolkit\Traits\logInfo().
templateResponse()
templateResponse (string $templateName, array $params = [], string $renderAs = 'blank', ?string $appName = null, ?IL10N $l10n = null) protected
Parameters
string $templateName
array $params
string $renderAs
null | string $appName
null | IL10N $l10n
Returns
TemplateResponse
Definition at line 73 of file ResponseTrait.php.
translateBracedTemplate()
translateBracedTemplate (string $template, ?array $l10nTemplateKeys) protected
Translate the braced placeholders contained in the given $template to the array values supplied by the $l10nTemplateKeys, that is, the keys of $l10nTemplateKeys matching the braced placeholders contained in $template will be replaced by their respective array value.
Parameters
string $template
null | array $l10nTemplateKeys If null, no replacement is performed and the $template argument is return unchanged.
Returns
string
Definition at line 478 of file UtilTrait.php.
Referenced by OCA\CAFEVDB\Toolkit\Traits\untranslateBracedTemplate().
transliterate()
transliterate (string $string, string $locale = null) protected
Transliterate the given string to the given or default locale.
Parameters
string $string
string $locale
Returns
string
Definition at line 104 of file UtilTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\getLocale().
unsetValue()
static unsetValue (array & $hayStack, mixed $value) static protected
Unset all array elements with value $value.
Parameters
array $hayStack The array to modify.
mixed $value The value to remove.
Returns
int The number of array slots that have been unset. As the values need not be unique this can be any non-negative integer.
Definition at line 307 of file UtilTrait.php.
untranslateBracedTemplate()
untranslateBracedTemplate (string $template, ?array $l10nTemplateKeys) protected
Translate the braced placeholders contained in the given $template to the array keys supplied by the $l10nTemplateKeys, that is, the array values of $l10nTemplateKeys matching the braced placeholders contained in $template will be replaced by their respective array key.
Parameters
string $template
null | array $l10nTemplateKeys If null, no replacement is performed and the $template argument is return unchanged.
Returns
string
Definition at line 498 of file UtilTrait.php.
References OCA\CAFEVDB\Toolkit\Traits\translateBracedTemplate().
valueResponse()
static valueResponse (mixed $value, ?string $message = '', int $status = Http::STATUS_OK) static protected
Parameters
mixed $value
null | string $message
int $status Default is Http::STATUS_OK.
Returns
DataResponse
See also
dataResponse()
Todo
Remove message/messages duplication.
Definition at line 214 of file ResponseTrait.php.
Variable Documentation
$appName
string $appName protected
Definition at line 58 of file ResponseTrait.php.
$assets
array $assets = [] protected
Definition at line 57 of file AssetTrait.php.
$credentialsStore
CredentialsStore $credentialsStore protected
Definition at line 46 of file AuthTokenTrait.php.
$l
IL10N $l protected
Definition at line 54 of file AssetTrait.php.
$previewManager
IPreview $previewManager protected
Definition at line 39 of file NodeTrait.php.
$request
IRequest $request protected
Definition at line 49 of file AuthTokenTrait.php.
$rootFolder
IRootFolder $rootFolder protected
Definition at line 42 of file NodeTrait.php.
$secureRandom
ISecureRandom $secureRandom protected
Definition at line 52 of file AuthTokenTrait.php.
$tokenProvider
TokenProvider $tokenProvider protected
Definition at line 43 of file AuthTokenTrait.php.
$userFolder
null Folder $userFolder protected
Definition at line 56 of file UserRootFolderTrait.php.
$userId
string $userId protected
Definition at line 51 of file AuthenticatedCommandTrait.php.
$userManager
IUserManager $userManager protected
Definition at line 45 of file AuthenticatedCommandTrait.php.
$userPassword
string $userPassword protected
Definition at line 54 of file AuthenticatedCommandTrait.php.
$userRootFolder
null Folder $userRootFolder protected
Definition at line 53 of file UserRootFolderTrait.php.
$userSession
IUserSession $userSession protected
Definition at line 48 of file AuthenticatedCommandTrait.php.
ApiRequestTrait
trait ApiRequestTrait
Initial value:
{
  use LoggerTrait
Trait with some helpers to deal with non-interactive requests.
Some hacks are just not needed for non-interactive request, like SSO etc.
Definition at line 32 of file ApiRequestTrait.php.
APPNAME_PREFIX
const APPNAME_PREFIX = 'app-' protected
Definition at line 52 of file ResponseTrait.php.
AssetTrait
trait AssetTrait
Initial value:
{
  use LoggerTrait
Return JavaScript- and CSS-assets names dealing with attached content hashes.
This needs some setup on the webpack build-system:
const HtmlWebpackPlugin = require('html-webpack-plugin');
...
webpackConfig.plugins = webpackConfig.plugins.concat([
  ...
  new HtmlWebpackPlugin({
    inject: false,
    filename: 'js/asset-meta.json',
    minify: false,
    templateContent(arg) {
      return JSON.stringify(arg.htmlWebpackPlugin.files, null, 2);
    },
  }),
  ...
]);
.
Definition at line 49 of file AssetTrait.php.
AuthenticatedCommandTrait
trait AuthenticatedCommandTrait
Initial value:
{
  use LoggerTrait
Trait in order to handle authentication with the cloud.
Definition at line 37 of file AuthenticatedCommandTrait.php.
AuthTokenTrait
trait AuthTokenTrait
Initial value:
{
  use LoggerTrait
Trait for obtaining a cookie secured auth-token.
Definition at line 38 of file AuthTokenTrait.php.
CloudAdminTrait
trait CloudAdminTrait
Initial value:
{
  protected $groupManager
Utitlity trait in order to get the addresses of the cloud admins.
Needed class members:
protected $groupManager
Definition at line 34 of file CloudAdminTrait.php.
LoggerTrait
trait LoggerTrait
Initial value:
{
  protected LoggerInterface $logger
Utitily trait to simplifiy logging somewhat.
Definition at line 35 of file LoggerTrait.php.
NodeTrait
trait NodeTrait
Initial value:
{
  use UserRootFolderTrait
Helper trait for file-system nodes.
Definition at line 31 of file NodeTrait.php.
RENDER_AS_BASE
const RENDER_AS_BASE = TemplateResponse::RENDER_AS_BASE protected
Definition at line 47 of file ResponseTrait.php.
RENDER_AS_BLANK
const RENDER_AS_BLANK = 'blank' protected
Definition at line 46 of file ResponseTrait.php.
RENDER_AS_ERROR
const RENDER_AS_ERROR = TemplateResponse::RENDER_AS_ERROR protected
Definition at line 49 of file ResponseTrait.php.
RENDER_AS_PUBLIC
const RENDER_AS_PUBLIC = TemplateResponse::RENDER_AS_PUBLIC protected
Definition at line 50 of file ResponseTrait.php.
RENDER_AS_USER
const RENDER_AS_USER = TemplateResponse::RENDER_AS_USER protected
Definition at line 48 of file ResponseTrait.php.
ResponseTrait
trait ResponseTrait
Initial value:
{
  protected const RENDER_AS_GUEST = TemplateResponse::RENDER_AS_GUEST
Utility class to ease constructing HTTP responses.
The consuming class has to define a translitate() method compatible to the one defined in the UtilTrait.
See also
UtilTrait::transliterate()
Definition at line 43 of file ResponseTrait.php.
UserRootFolderTrait
trait UserRootFolderTrait
Initial value:
{
  protected $appName
The actual user folder is USER_ROOT/files/.
This trait provides some convenience methods for the access of USER_ROOT. The consuming class must initialize the protected member $rootFooder with an instance of IRootFolder and the protected member $userId with the user id of the target user.
Definition at line 36 of file UserRootFolderTrait.php.
UtilTrait
trait UtilTrait
Initial value:
{
  protected IL10N $l
Trait for some general nice-to-have functions.
Definition at line 33 of file UtilTrait.php.