CamerataDB: OCA\CAFEVDB\Traits Namespace Reference
OCA\CAFEVDB\Traits Namespace Reference
Orchestra member, musician and project management application.
Functions
configService ()
Return the stored config-service for convenience.
cloudConfig ()
Return the stored config-service of the embedding cloud container.
l10n ()
appL10n ()
logger ()
appContainer ()
di (string $className)
Dependency injection of $className.
appName ()
appVersion ()
appConfig ()
userSession ()
urlGenerator ()
userManager ()
groupManager ()
subAdminManager ()
getUserValue (string $key, mixed $default=null, ?string $userId=null)
setUserValue (string $key, mixed $value, ?string $userId=null)
getAppValue (string $key, mixed $default=null)
A short-cut, redirecting to the stock functions for the app.
setAppValue (string $key, mixed $value)
A short-cut, redirecting to the stock functions for the app.
deleteAppValue (string $key)
A short-cut, redirecting to the stock functions for the app.
encryptionService ()
getAppEncryptionKey ()
setAppEncryptionKey (string $key)
encryptionKeyValid (?string $encryptionKey=null)
Check the validity of the encryption key.
encrypt ($value)
decrypt ($value)
verifyHash ($value, $hash)
computeHash (string $value)
getConfigValue (string $key, mixed $default=null)
Get a possibly encrypted config value.
setConfigValue (string $key, mixed $value)
deleteConfigValue (string $key)
Delete the value for the given key.
generateRandomBytes (int $length=30)
Would rather belong to the EncryptionService.
user (?string $userId=null)
userId ()
setUserId (string $userId)
Install a new user id.
setUser ($user)
Install a new user.
sudo (string $uid, callable $callback)
Fake execution with other user-id.
shareOwnerId ()
shareOwner ()
groupId ()
group (?string $groupId=null)
groupExists (?string $groupId=null)
inGroup (?string $userId=null, ?string $groupId=null)
isSubAdminOfGroup (?string $userId=null, ?string $groupId=null)
getGroupSubAdmins (?string $groupId=null)
Return all the sub-admins of the given or the configured orchestra group.
subAdminGroupId ()
Return the id of the dedicated admin-group which contains all sub-admins.
subAdminGroup ()
Return the dedicated admin-group if it exists.
inSubAdminGroup (?string $userId=null)
Check if the currently logged in or given user-id belongs to the dedicated sub-admin group.
defaultUserIdSlug (?string $surName, ?string $firstName, ?string $nickName)
getClubMembersProjectId ()
getClubMembersProjectName ()
getExecutiveBoardProjectId ()
getExcutiveBoardProjectName ()
getSharedFolderPath ()
getSharedSubFolderPath (string $configKey)
Create the full-path for the sub-folder corresponding to the given config key.
getDocumentTemplatesPath (string $templateName=null, bool $dirName=false)
Return the full path to the document templates folder.
getProjectsFolderPath ()
getFinanceFolderPath ()
getBankTransactionsPath ()
getFinancialBalancesPath ()
getProjectBalancesPath ()
getPostBoxFolderPath ()
getOutBoxFolderPath ()
getIcon ()
getDateTimeZone ($timeStamp=false)
Get the current timezone.
getTimezone ($timeStamp=false)
Return the current time-zone string.
dateTimeFormatter ()
formatDate ($timestamp, string $format='long', DateTimeZone $timeZone=null, IL10N $l=null)
Work around NC annoyingly not accepting \DateTimeInterface.
formatDateTime ($timestamp, string $formatDate='long', string $formatTime='medium', DateTimeZone $timeZone=null, IL10N $l=null)
Work around NC annoyingly not accepting \DateTimeInterface.
getLocale (?string $lang=null)
Return the locale.
appLocale ()
getLanguage (?string $locale=null)
localeCountryNames ($locale=null)
localeLanguageNames ($locale=null)
findAvailableLanguages (string $app='core')
findAvailableLocales ()
transliterate (string $string, ?string $locale=null)
Transliterate the given string to the given or default locale.
currencyCode ($locale=null)
Return the currency code for the locale.
currencySymbol (?string $locale=null)
Return the currency symbol for the locale.
moneyValue (mixed $value, ?string $locale=null)
Convert $value to a currency value in the given or default locale.
floatValue (mixed $value, int $decimals=2, ?string $locale=null)
Convert a float value in the given or default locale.
humanFileSize (int $bytes, ?string $locale=null, bool $binary=true, int $digits=2)
Format a bytes value with "readable" postfix.
timeStamp (?string $format=null, ?DateTimeZone $timeZone=null)
Call ConfigService::formatTimeStamp() with the current date and time.
formatTimeStamp ($date=null, ?string $format=null, ?DateTimeZone $timeZone=null)
Format the given date according to $format and $timeZone to a human readable time-stamp, providing defaults for $format and using the default time-zone if none is specified.
getTimeStamp ()
generateUUID ()
translationVariants (string $name)
Search for translation variants by trying several camel-case transformations.
toolTipsService ()
databaseConfigured ()
getSystemValue (string $key, mixed $default='')
Forward to OCP\IConfig::getSystemValue().
getSystemValueBool (string $key, mixed $default='')
Forward to OCP\IConfig::getSystemValueBool().
getSystemValueInt (string $key, mixed $default='')
Forward to OCP\IConfig::getSystemValueInt()
getSystemValueString (string $key, mixed $default='')
Forward to OCP\IConfig::getSystemValueString().
shouldDebug (int $flag)
Check whether the current config-setting for debug contains the provided flags.
clearDatabaseRepository ()
Clear the cache.
setDatabaseRepository (string $entityClassName)
Set the given name as the current database target entity.
getDatabaseRepository ($entityClassName=null)
Set and get the given name as the current database target entity.
createNamedQuery (string $name)
Creates a Query from a named query.
createQuery (string $dql)
Creates a new Query object.
queryBuilder ()
Create a QueryBuilder instance.
remove (mixed $entity, bool $flush=false, bool $hard=false, bool $soft=false)
Removes an entity instance.
getReference (string $entityClassName, mixed $key)
Gets a reference to the entity identified by the given type and identifier without actually loading it, if the entity is not yet loaded.
persist (mixed $entity)
Tells the EntityManager to make an instance managed and persistent.
flush ($entity=null)
Flushes all changes to objects that have been queued up to now to the database.
findAll ($entityClassName=null)
Finds all entities in the repository.
find (mixed $id, ?int $lockMode=null, ?int $lockVersion=null)
Finds an entity by its primary key / identifier.
findEntity (string $entityClassName, mixed $id, ?int $lockMode=null, ?int $lockVersion=null)
Finds an entity by its primary key / identifier.
findBy (array $criteria, array $orderBy=null, $limit=null, $offset=null)
Finds entities by a set of criteria.
findOneBy (array $criteria, array $orderBy=null)
Finds a single entity by a set of criteria.
containsEntity (mixed $entity)
Forward to EntityManager::contains().
refreshEntity (mixed $entity)
Forward to EntityManager::refresh(), return the refreshed entity in order to allow for "->" chaining.
enableFilter (string $filterName, bool $state=true)
Enable the given filter.
disableFilter (string $filterName)
Disable the given filter.
matching (Collections\Criteria $criteria, ?string $entityClassName=null)
Select all elements from a selectable that match the expression and return a new collection containing these elements.
static criteria ()
Convenience function to generate Collections\Criteria.
static criteriaExpr ()
Convenience function to generate Collections\ExpressionBuilder.
static criteriaWhere (array $arrayCriteria)
expr ()
count (array $criteria, string $entityClassName=null)
Counts entities by a set of criteria.
columnNames ($entityClassName=null)
Obtain the column names of the currently used database entity.
classMetadata (?string $entityClassName=null)
Obtain the class meta-data for the given or most recently used entity class.
property (string $columnName)
translate (mixed $entity, string $field, ?string $locale, mixed $value)
Convenience, forward potential translation attempts to the underlying translation backend.
publishInitialStateForUser (string $userId)
sessionStoreValue (string $key, mixed $value)
Store something in the session-data.
sessionRetrieveValue (string $key, mixed $default=null)
Fetch something from the session-data.
getDateTimeZone (mixed $timeStamp=false)
Get the current timezone.
Variables
trait ConfigTrait
Too big a traits class to forward most of the ConfigService methods to the using class.
$configService
$toolTipsService
$l
trait EntityManagerTrait
Database EntityManager short-cuts.
$entityClassName
$databaseRepository
trait EntityTranslationTrait
Translate data-base columns on the fly.
$translationRepository
trait InitialStateTrait
Provide an "initial state" for JavaScript.
$appName
$initialStateService
$historyService
trait SessionTrait
Session-store abstraction trait.
trait TimeStampTrait
Generate a time-stamp strings.
$appContainer
Detailed Description
Orchestra member, musician and project management application.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2016, 2020, 2021, 2022, 2023 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2016, 2020, 2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
appConfig()
appConfig () protected
Returns
IConfig
Definition at line 140 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
appContainer()
appContainer () protected
Returns
IAppContainer
Definition at line 110 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\di(), and OCA\CAFEVDB\Traits\getDateTimeZone().
appL10n()
appL10n () protected
Returns
IL10N
Definition at line 98 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
appLocale()
appLocale () protected
Returns
string
Definition at line 858 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
appName()
appName () protected
Returns
string
Definition at line 128 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\appVersion(), and OCA\CAFEVDB\Traits\publishInitialStateForUser().
appVersion()
appVersion () protected
Returns
string
Definition at line 134 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\appName(), and OCA\CAFEVDB\Traits\di().
classMetadata()
classMetadata (?string $entityClassName = null) protected
Obtain the class meta-data for the given or most recently used entity class.
Parameters
string | null $entityClassName The database entity to use.
Returns
array The class meta-data
Definition at line 463 of file EntityManagerTrait.php.
clearDatabaseRepository()
clearDatabaseRepository () protected
Clear the cache.
Returns
void
Definition at line 54 of file EntityManagerTrait.php.
cloudConfig()
cloudConfig ()
Return the stored config-service of the embedding cloud container.
Returns
IConfig
Definition at line 86 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\getSystemValue(), OCA\CAFEVDB\Traits\getSystemValueBool(), OCA\CAFEVDB\Traits\getSystemValueInt(), and OCA\CAFEVDB\Traits\getSystemValueString().
columnNames()
columnNames ($entityClassName = null) protected
Obtain the column names of the currently used database entity.
Parameters
string | null $entityClassName The database entity to use.
Returns
array The column names.
Definition at line 446 of file EntityManagerTrait.php.
computeHash()
computeHash (string $value) protected
Parameters
string $value The value to hash.
Returns
string The hash of $value.
Definition at line 322 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
configService()
configService ()
Return the stored config-service for convenience.
Returns
\OCA\CAFEVDB\Service\ConfigService
Definition at line 75 of file ConfigTrait.php.
Referenced by OCA\CAFEVDB\Traits\appConfig(), OCA\CAFEVDB\Traits\appContainer(), OCA\CAFEVDB\Traits\appL10n(), OCA\CAFEVDB\Traits\appLocale(), OCA\CAFEVDB\Traits\appName(), OCA\CAFEVDB\Traits\cloudConfig(), OCA\CAFEVDB\Traits\computeHash(), OCA\CAFEVDB\Traits\currencyCode(), OCA\CAFEVDB\Traits\currencySymbol(), OCA\CAFEVDB\Traits\dateTimeFormatter(), OCA\CAFEVDB\Traits\decrypt(), OCA\CAFEVDB\Traits\deleteAppValue(), OCA\CAFEVDB\Traits\deleteConfigValue(), OCA\CAFEVDB\Traits\encrypt(), OCA\CAFEVDB\Traits\encryptionKeyValid(), OCA\CAFEVDB\Traits\encryptionService(), OCA\CAFEVDB\Traits\findAvailableLanguages(), OCA\CAFEVDB\Traits\findAvailableLocales(), OCA\CAFEVDB\Traits\floatValue(), OCA\CAFEVDB\Traits\formatTimeStamp(), OCA\CAFEVDB\Traits\generateRandomBytes(), OCA\CAFEVDB\Traits\getAppEncryptionKey(), OCA\CAFEVDB\Traits\getAppValue(), OCA\CAFEVDB\Traits\getConfigValue(), OCA\CAFEVDB\Traits\getDateTimeZone(), OCA\CAFEVDB\Traits\getGroupSubAdmins(), OCA\CAFEVDB\Traits\getIcon(), OCA\CAFEVDB\Traits\getLanguage(), OCA\CAFEVDB\Traits\getLocale(), OCA\CAFEVDB\Traits\getTimeStamp(), OCA\CAFEVDB\Traits\getUserValue(), OCA\CAFEVDB\Traits\group(), OCA\CAFEVDB\Traits\groupExists(), OCA\CAFEVDB\Traits\groupId(), OCA\CAFEVDB\Traits\groupManager(), OCA\CAFEVDB\Traits\inGroup(), OCA\CAFEVDB\Traits\inSubAdminGroup(), OCA\CAFEVDB\Traits\isSubAdminOfGroup(), OCA\CAFEVDB\Traits\l10n(), OCA\CAFEVDB\Traits\localeCountryNames(), OCA\CAFEVDB\Traits\localeLanguageNames(), OCA\CAFEVDB\Traits\logger(), OCA\CAFEVDB\Traits\moneyValue(), OCA\CAFEVDB\Traits\setAppEncryptionKey(), OCA\CAFEVDB\Traits\setAppValue(), OCA\CAFEVDB\Traits\setConfigValue(), OCA\CAFEVDB\Traits\setUser(), OCA\CAFEVDB\Traits\setUserId(), OCA\CAFEVDB\Traits\setUserValue(), OCA\CAFEVDB\Traits\subAdminGroup(), OCA\CAFEVDB\Traits\subAdminGroupId(), OCA\CAFEVDB\Traits\subAdminManager(), OCA\CAFEVDB\Traits\sudo(), OCA\CAFEVDB\Traits\timeStamp(), OCA\CAFEVDB\Traits\transliterate(), OCA\CAFEVDB\Traits\urlGenerator(), OCA\CAFEVDB\Traits\user(), OCA\CAFEVDB\Traits\userId(), OCA\CAFEVDB\Traits\userManager(), OCA\CAFEVDB\Traits\userSession(), and OCA\CAFEVDB\Traits\verifyHash().
containsEntity()
containsEntity (mixed $entity) protected
Forward to EntityManager::contains().
Parameters
mixed $entity
Returns
bool
Definition at line 320 of file EntityManagerTrait.php.
count()
count (array $criteria, string $entityClassName = null) protected
Counts entities by a set of criteria.
Parameters
array $criteria
string $entityClassName The database entity to use.
Returns
int The cardinality of the objects that match the given criteria.
Definition at line 434 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
createNamedQuery()
createNamedQuery (string $name) protected
Creates a Query from a named query.
Parameters
string $name
Returns
Query
Definition at line 101 of file EntityManagerTrait.php.
createQuery()
createQuery (string $dql) protected
Creates a new Query object.
Parameters
string $dql The DQL string.
Returns
Query
Definition at line 113 of file EntityManagerTrait.php.
criteria()
static criteria () static protected
Convenience function to generate Collections\Criteria.
Returns
Collections\Criteria
Definition at line 392 of file EntityManagerTrait.php.
References Util\criteria().
criteriaExpr()
static criteriaExpr () static protected
Convenience function to generate Collections\ExpressionBuilder.
Returns
Collections\ExpressionBuilder
Definition at line 402 of file EntityManagerTrait.php.
References Util\criteriaExpr().
criteriaWhere()
static criteriaWhere (array $arrayCriteria) static protected
Parameters
array $arrayCriteria
Returns
Collections\Criteria
See also
DBUtil::criteriaWhere()
Definition at line 414 of file EntityManagerTrait.php.
References Util\criteriaWhere().
currencyCode()
currencyCode ($locale = null)
Return the currency code for the locale.
Parameters
null | string $locale
Returns
string
Definition at line 936 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\publishInitialStateForUser().
currencySymbol()
currencySymbol (?string $locale = null)
Return the currency symbol for the locale.
Parameters
null | string $locale
Returns
string
Definition at line 948 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\publishInitialStateForUser().
databaseConfigured()
databaseConfigured () protected
Returns
bool
Definition at line 1095 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
dateTimeFormatter()
dateTimeFormatter () protected
Returns
IDateTimeFormatter
Definition at line 784 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\formatDate(), and OCA\CAFEVDB\Traits\formatDateTime().
decrypt()
decrypt ($value) protected
Parameters
null | string $value Value to decrypt.
Returns
null|string Decrypted value.
Definition at line 299 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
defaultUserIdSlug()
defaultUserIdSlug (?string $surName, ?string $firstName, ?string $nickName)
Parameters
null | string $surName
null | string $firstName
null | string $nickName
Returns
string The default user-id slug.
Definition at line 563 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\transliterate().
deleteAppValue()
deleteAppValue (string $key) protected
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
Returns
void
Definition at line 238 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
deleteConfigValue()
deleteConfigValue (string $key)
Delete the value for the given key.
Parameters
string $key Config key.
Returns
void
Definition at line 364 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
di()
di (string $className) protected
Dependency injection of $className.
Parameters
string $className
Returns
mixed
Definition at line 122 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\appContainer().
Referenced by OCA\CAFEVDB\Traits\appVersion(), and OCA\CAFEVDB\Traits\toolTipsService().
disableFilter()
disableFilter (string $filterName) protected
Disable the given filter.
In contrast to the upstream-method does not throw an exception if the filter is not enabled.
Parameters
string $filterName
Returns
bool The previous isEnabled() state of the filter.
Definition at line 363 of file EntityManagerTrait.php.
enableFilter()
enableFilter (string $filterName, bool $state = true) protected
Enable the given filter.
Parameters
string $filterName
bool $state
Returns
\OCA\CAFEVDB\Wrapped\Doctrine\ORM\Query\Filter\SQLFilter The enabled filter.
Definition at line 348 of file EntityManagerTrait.php.
encrypt()
encrypt ($value) protected
Parameters
null | string $value Value to encrypt.
Returns
null|string Encrypted value.
Definition at line 289 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
encryptionKeyValid()
encryptionKeyValid (?string $encryptionKey = null) protected
Check the validity of the encryption key.
In order to do so we fetch an encrypted representation of the key from the OC config space and try to decrypt that key with the given key. If the decrypted key matches our key, then we accept the key.
Parameters
null | string $encryptionKey Key to check.
Returns
bool
Exceptions
Exceptions
\EncryptionKeyException
See also
EncryptionService::encryptionKeyValid()
Definition at line 279 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
encryptionService()
encryptionService () protected
Returns
EncryptionService
Definition at line 244 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
expr()
expr () protected
Returns
mixed
Definition at line 420 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\queryBuilder().
find()
find (mixed $id, ?int $lockMode = null, ?int $lockVersion = null) protected
Finds an entity by its primary key / identifier.
Parameters
mixed $id The identifier.
int | null $lockMode One of the \OCA\CAFEVDB\Wrapped\Doctrine\DBAL\LockMode::* constants or NULL if no specific lock mode should be used during the search.
int | null $lockVersion The lock version.
Returns
object|null The entity instance or NULL if the entity can not be found.
Definition at line 261 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
findAll()
findAll ($entityClassName = null) protected
Finds all entities in the repository.
Parameters
string | null $entityClassName
Returns
array The entities.
Definition at line 244 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
findAvailableLanguages()
findAvailableLanguages (string $app = 'core')
Parameters
string $app The app with the translations.
Returns
array
See also
IL10NFactory::findAvailableLanguages()
Definition at line 900 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
findAvailableLocales()
findAvailableLocales ()
Returns
array
See also
IL10NFactory::findAvailableLocales()
Definition at line 910 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
findBy()
findBy (array $criteria, array $orderBy = null, $limit = null, $offset = null) protected
Finds entities by a set of criteria.
Parameters
array $criteria
array | null $orderBy
int | null $limit
int | null $offset
Returns
array The objects.
Definition at line 295 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
findEntity()
findEntity (string $entityClassName, mixed $id, ?int $lockMode = null, ?int $lockVersion = null) protected
Finds an entity by its primary key / identifier.
Parameters
string $entityClassName
mixed $id The identifier.
int | null $lockMode One of the \OCA\CAFEVDB\Wrapped\Doctrine\DBAL\LockMode::* constants or NULL if no specific lock mode should be used during the search.
int | null $lockVersion The lock version.
Returns
object|null The entity instance or NULL if the entity can not be found.
Definition at line 280 of file EntityManagerTrait.php.
findOneBy()
findOneBy (array $criteria, array $orderBy = null) protected
Finds a single entity by a set of criteria.
Parameters
array $criteria
array | null $orderBy
Returns
object|null The entity instance or NULL if the entity can not be found.
Definition at line 308 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
floatValue()
floatValue (mixed $value, int $decimals = 2, ?string $locale = null)
Convert a float value in the given or default locale.
Parameters
mixed $value
int $decimals
null | string $locale
Returns
string
Definition at line 978 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
flush()
flush ($entity = null) protected
Flushes all changes to objects that have been queued up to now to the database.
This effectively synchronizes the in-memory state of managed objects with the database.
If an entity is explicitly passed to this method only this entity and the cascade-persist semantics + scheduled inserts/removals are synchronized.
Parameters
null | object | array $entity
Returns
void
Exceptions
\OCA\CAFEVDB\Wrapped\Doctrine\ORM\OptimisticLockException If a version check on an entity that makes use of optimistic locking fails.
Exceptions
ORMException
Definition at line 229 of file EntityManagerTrait.php.
Referenced by OCA\CAFEVDB\Traits\remove().
formatDate()
formatDate ($timestamp, string $format = 'long', DateTimeZone $timeZone = null, IL10N $l = null) protected
Work around NC annoyingly not accepting \DateTimeInterface.
Parameters
int | DateTimeInterface $timestamp
string $format
DateTimeZone $timeZone
IL10N $l
Returns
string
Definition at line 802 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\dateTimeFormatter().
formatDateTime()
formatDateTime ($timestamp, string $formatDate = 'long', string $formatTime = 'medium', DateTimeZone $timeZone = null, IL10N $l = null) protected
Work around NC annoyingly not accepting \DateTimeInterface.
Parameters
int | DateTimeInterface $timestamp
string $formatDate
string $formatTime
DateTimeZone $timeZone
IL10N $l
Returns
string
Definition at line 831 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\dateTimeFormatter().
formatTimeStamp()
formatTimeStamp ($date = null, ?string $format = null, ?DateTimeZone $timeZone = null) protected
Format the given date according to $format and $timeZone to a human readable time-stamp, providing defaults for $format and using the default time-zone if none is specified.
Parameters
null | int | \\DateTimeInterface $date
null | string $format
null | \\DateTimeZone $timeZone
Returns
string
Parameters
null | int | DateTimeInterface $date
null | string $format
null | DateTimeZone $timeZone
Returns
string
Definition at line 1029 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
generateRandomBytes()
generateRandomBytes (int $length = 30)
Would rather belong to the EncryptionService.
Parameters
int $length Length of random string.
Returns
string
Definition at line 376 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
generateUUID()
generateUUID () protected
Returns
string
Definition at line 1041 of file ConfigTrait.php.
getAppEncryptionKey()
getAppEncryptionKey () protected
Returns
null|string
Definition at line 250 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getAppValue()
getAppValue (string $key, mixed $default = null) protected
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $default Default value.
Returns
mixed
Definition at line 212 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getBankTransactionsPath()
getBankTransactionsPath () protected
Returns
null|string Return the full path to the bank-transactions folder
Definition at line 685 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue(), and OCA\CAFEVDB\Traits\getFinanceFolderPath().
getClubMembersProjectId()
getClubMembersProjectId () protected
Returns
int
Definition at line 574 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
getClubMembersProjectName()
getClubMembersProjectName () protected
Returns
string
Definition at line 580 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
getConfigValue()
getConfigValue (string $key, mixed $default = null)
Get a possibly encrypted config value.
Parameters
string $key
mixed $default
Returns
mixed
Exceptions
Exceptions
\ConfigLockedException
Definition at line 338 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\databaseConfigured(), OCA\CAFEVDB\Traits\getBankTransactionsPath(), OCA\CAFEVDB\Traits\getClubMembersProjectId(), OCA\CAFEVDB\Traits\getClubMembersProjectName(), OCA\CAFEVDB\Traits\getDocumentTemplatesPath(), OCA\CAFEVDB\Traits\getExcutiveBoardProjectName(), OCA\CAFEVDB\Traits\getExecutiveBoardProjectId(), OCA\CAFEVDB\Traits\getFinancialBalancesPath(), OCA\CAFEVDB\Traits\getProjectBalancesPath(), OCA\CAFEVDB\Traits\getSharedFolderPath(), OCA\CAFEVDB\Traits\getSharedSubFolderPath(), OCA\CAFEVDB\Traits\shareOwnerId(), and OCA\CAFEVDB\Traits\shouldDebug().
getDatabaseRepository()
getDatabaseRepository ($entityClassName = null) protected
Set and get the given name as the current database target entity.
Parameters
string | null $entityClassName
Returns
BaseEntityRepository The repository for the current target database entity.
Definition at line 81 of file EntityManagerTrait.php.
References EntityRepository\getEntityManager(), and OCA\CAFEVDB\Traits\setDatabaseRepository().
Referenced by OCA\CAFEVDB\Traits\count(), OCA\CAFEVDB\Traits\find(), OCA\CAFEVDB\Traits\findAll(), OCA\CAFEVDB\Traits\findBy(), OCA\CAFEVDB\Traits\findOneBy(), and OCA\CAFEVDB\Traits\matching().
getDateTimeZone() [1/2]
getDateTimeZone ($timeStamp = false) protected
Get the current timezone.
Parameters
bool | int $timeStamp
Returns
\DateTimeZone
Definition at line 759 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\getTimezone().
getDateTimeZone() [2/2]
getDateTimeZone (mixed $timeStamp = false)
Get the current timezone.
Parameters
bool | int $timeStamp
Returns
DateTimeZone
Definition at line 50 of file TimeStampTrait.php.
References OCA\CAFEVDB\Traits\appContainer().
getDocumentTemplatesPath()
getDocumentTemplatesPath (string $templateName = null, bool $dirName = false) protected
Return the full path to the document templates folder.
Parameters
string $templateName If given return the full path to the given document template which can be one of the array-keys of ConfigService::DOCUMENT_TEMPLATES.
bool $dirName If $templateName is given return only the dirname part of the path.
Returns
string Cloud file-system path as requested.
Definition at line 636 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue(), and OCA\CAFEVDB\Traits\getSharedFolderPath().
getExcutiveBoardProjectName()
getExcutiveBoardProjectName () protected
Returns
string
Definition at line 592 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
getExecutiveBoardProjectId()
getExecutiveBoardProjectId () protected
Returns
int
Definition at line 586 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
getFinanceFolderPath()
getFinanceFolderPath () protected
Returns
null|string Return the full path to the finance folder.
Definition at line 677 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getSharedSubFolderPath().
Referenced by OCA\CAFEVDB\Traits\getBankTransactionsPath(), and OCA\CAFEVDB\Traits\getFinancialBalancesPath().
getFinancialBalancesPath()
getFinancialBalancesPath () protected
Returns
null|string Return the full path to the financial balances folder
Definition at line 701 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue(), and OCA\CAFEVDB\Traits\getFinanceFolderPath().
Referenced by OCA\CAFEVDB\Traits\getProjectBalancesPath().
getGroupSubAdmins()
getGroupSubAdmins (?string $groupId = null) protected
Return all the sub-admins of the given or the configured orchestra group.
Parameters
null | string $groupId then Use orchestra group if null.
Returns
array
Definition at line 516 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getIcon()
getIcon ()
Returns
string Image web-path to the app-icon.
Definition at line 747 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getLanguage()
getLanguage (?string $locale = null) protected
Parameters
null | string $locale
Returns
string
Definition at line 868 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getLocale()
getLocale (?string $lang = null) protected
Return the locale.
Parameters
null | string $lang
Returns
string
Definition at line 852 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\humanFileSize().
getOutBoxFolderPath()
getOutBoxFolderPath () protected
Returns
null|string Return the full path to the outgoing postbox folder.
Definition at line 741 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getSharedSubFolderPath().
getPostBoxFolderPath()
getPostBoxFolderPath () protected
Returns
null|string Return the full path to incoming post-box folder.
Definition at line 733 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getSharedSubFolderPath().
getProjectBalancesPath()
getProjectBalancesPath () protected
Returns
null|string Return the full path to the financial balances folder
Definition at line 717 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue(), and OCA\CAFEVDB\Traits\getFinancialBalancesPath().
getProjectsFolderPath()
getProjectsFolderPath () protected
Returns
null|string Return the full path to the finance folder.
Definition at line 669 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getSharedSubFolderPath().
getReference()
getReference (string $entityClassName, mixed $key) protected
Gets a reference to the entity identified by the given type and identifier without actually loading it, if the entity is not yet loaded.
Parameters
string $entityClassName The name of the entity type.
mixed $key The entity reference.
Returns
mixed
Exceptions
ORMException
Definition at line 187 of file EntityManagerTrait.php.
getSharedFolderPath()
getSharedFolderPath () protected
Returns
null|string
Definition at line 598 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
Referenced by OCA\CAFEVDB\Traits\getDocumentTemplatesPath(), and OCA\CAFEVDB\Traits\getSharedSubFolderPath().
getSharedSubFolderPath()
getSharedSubFolderPath (string $configKey) protected
Create the full-path for the sub-folder corresponding to the given config key.
Parameters
string $configKey
Returns
null|string
Definition at line 611 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue(), and OCA\CAFEVDB\Traits\getSharedFolderPath().
Referenced by OCA\CAFEVDB\Traits\getFinanceFolderPath(), OCA\CAFEVDB\Traits\getOutBoxFolderPath(), OCA\CAFEVDB\Traits\getPostBoxFolderPath(), and OCA\CAFEVDB\Traits\getProjectsFolderPath().
getSystemValue()
getSystemValue (string $key, mixed $default = '') protected
Forward to OCP\IConfig::getSystemValue().
Parameters
string $key
mixed $default
Returns
mixed
Definition at line 1112 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\cloudConfig().
getSystemValueBool()
getSystemValueBool (string $key, mixed $default = '') protected
Forward to OCP\IConfig::getSystemValueBool().
Parameters
string $key
mixed $default
Returns
bool
Definition at line 1126 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\cloudConfig().
getSystemValueInt()
getSystemValueInt (string $key, mixed $default = '') protected
Forward to OCP\IConfig::getSystemValueInt()
Parameters
string $key
mixed $default
Returns
int
Definition at line 1140 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\cloudConfig().
getSystemValueString()
getSystemValueString (string $key, mixed $default = '') protected
Forward to OCP\IConfig::getSystemValueString().
Parameters
string $key
mixed $default
Returns
string
Definition at line 1154 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\cloudConfig().
getTimeStamp()
getTimeStamp () protected
Returns
int Return the current Unix timestamp.
Definition at line 1035 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
getTimezone()
getTimezone ($timeStamp = false) protected
Return the current time-zone string.
Parameters
bool | int $timeStamp
Returns
string
Definition at line 771 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getDateTimeZone().
getUserValue()
getUserValue (string $key, mixed $default = null, ?string $userId = null) protected
Parameters
string $key Config key.
mixed $default Default value.
null | string $userId Use the current user if null.
Returns
mixed
Definition at line 184 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\publishInitialStateForUser().
group()
group (?string $groupId = null) protected
Parameters
null | string $groupId
Returns
null|IGroup The group for the given id or the orchetra group.
Definition at line 470 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
groupExists()
groupExists (?string $groupId = null) protected
Parameters
null | string $groupId Use the orchestra group if null.
Returns
bool
Definition at line 480 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
groupId()
groupId () protected
Returns
string The orchestra orga-group id.
Definition at line 460 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
groupManager()
groupManager () protected
Returns
IGroupManager
Definition at line 164 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
humanFileSize()
humanFileSize (int $bytes, ?string $locale = null, bool $binary = true, int $digits = 2) protected
Format a bytes value with "readable" postfix.
Parameters
int $bytes
null | string $locale
bool $binary
int $digits
Returns
string
Definition at line 996 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getLocale().
inGroup()
inGroup (?string $userId = null, ?string $groupId = null) protected
Parameters
null | string $userId Use the current user if null.
null | string $groupId then Use orchestra group if null.
Returns
bool
Definition at line 492 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
inSubAdminGroup()
inSubAdminGroup (?string $userId = null) protected
Check if the currently logged in or given user-id belongs to the dedicated sub-admin group.
Parameters
null | string $userId
Returns
bool
Definition at line 549 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
isSubAdminOfGroup()
isSubAdminOfGroup (?string $userId = null, ?string $groupId = null) protected
Parameters
null | string $userId Use the current user if null.
null | string $groupId then Use orchestra group if null.
Returns
bool
Definition at line 504 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
l10n()
l10n () protected
Returns
IL10N
Definition at line 92 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
localeCountryNames()
localeCountryNames ($locale = null) protected
Parameters
null | string $locale
Returns
array
Definition at line 878 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
localeLanguageNames()
localeLanguageNames ($locale = null) protected
Parameters
null | string $locale
Returns
array
Definition at line 888 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
logger()
logger ()
Returns
LoggerInterface
Definition at line 104 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
matching()
matching (Collections\Criteria $criteria, ?string $entityClassName = null) protected
Select all elements from a selectable that match the expression and return a new collection containing these elements.
Parameters
Collections\\Criteria $criteria
string | null $entityClassName
Returns
Collections\Collection
Definition at line 382 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\getDatabaseRepository().
moneyValue()
moneyValue (mixed $value, ?string $locale = null)
Convert $value to a currency value in the given or default locale.
Parameters
mixed $value
null | string $locale
Returns
string
Definition at line 962 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
persist()
persist (mixed $entity) protected
Tells the EntityManager to make an instance managed and persistent.
The entity will be entered into the database at or before transaction commit or as a result of the flush operation.
NOTE: The persist operation always considers entities that are not yet known to this EntityManager as NEW. Do not pass detached entities to the persist operation.
Parameters
mixed $entity The instance to make managed and persistent.
Returns
mixed
Exceptions
ORMInvalidArgumentException
ORMException
Definition at line 208 of file EntityManagerTrait.php.
property()
property (string $columnName) protected
Parameters
string $columnName
Returns
string
See also
\OCA\CAFEVDB\Database\EntityManager::property
Definition at line 479 of file EntityManagerTrait.php.
publishInitialStateForUser()
publishInitialStateForUser (string $userId) protected
Parameters
string $userId
Returns
void
@SuppressWarnings(PHPMD.Superglobals)
Definition at line 61 of file InitialStateTrait.php.
References OCA\CAFEVDB\Traits\appName(), OCA\CAFEVDB\Traits\currencyCode(), OCA\CAFEVDB\Traits\currencySymbol(), and OCA\CAFEVDB\Traits\getUserValue().
queryBuilder()
queryBuilder () protected
Create a QueryBuilder instance.
Returns
QueryBuilder
Definition at line 123 of file EntityManagerTrait.php.
Referenced by OCA\CAFEVDB\Traits\expr().
refreshEntity()
refreshEntity (mixed $entity) protected
Forward to EntityManager::refresh(), return the refreshed entity in order to allow for "->" chaining.
Parameters
mixed $entity
Returns
mixed $entity
Definition at line 333 of file EntityManagerTrait.php.
remove()
remove (mixed $entity, bool $flush = false, bool $hard = false, bool $soft = false) protected
Removes an entity instance.
A removed entity will be removed from the database at or before transaction commit or as a result of the flush operation.
Parameters
mixed $entity The entity instance to remove.
bool $flush Initiate a flush if true.
bool $hard Issue a double remove: if $entity is managed by Gedmo\SoftDeleteable then this will "hard" (read: finally) delete the entity unless it is tagged as "in use" by other means.
bool $soft For entities managed by Gedmo\SoftDeleteable first check if this entity is already tagged as "soft deleted" and if so do nothing.
Returns
void
Exceptions
ORMInvalidArgumentException
ORMException
Definition at line 151 of file EntityManagerTrait.php.
References OCA\CAFEVDB\Traits\flush().
sessionRetrieveValue()
sessionRetrieveValue (string $key, mixed $default = null) protected
Fetch something from the session-data.
It is completely left open how this is done.
The methods sessionStoreValue() and sessionRetrieveValue() should be the only interface points to the PHP session.
Parameters
string $key The key tagging the desired data.
mixed $default What to return if the data is not available. Defaults to false.
Returns
mixed
Definition at line 68 of file SessionTrait.php.
sessionStoreValue()
sessionStoreValue (string $key, mixed $value) protected
Store something in the session-data.
It is completely left open how this is done.
The methods sessionStoreValue() and sessionRetrieveValue() should be the only interface points to the PHP session (except for, ahem, tweaks).
Parameters
string $key
mixed $value
Returns
void
Definition at line 49 of file SessionTrait.php.
setAppEncryptionKey()
setAppEncryptionKey (string $key) protected
Parameters
string $key Encryption key to set.
Returns
void
Definition at line 260 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
setAppValue()
setAppValue (string $key, mixed $value) protected
A short-cut, redirecting to the stock functions for the app.
Parameters
string $key Config key.
mixed $value Value to set.
Returns
mixed
Definition at line 226 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
setConfigValue()
setConfigValue (string $key, mixed $value)
Parameters
string $key
mixed $value
Returns
bool Success or not.
Exceptions
Exceptions
\ConfigLockedException
Definition at line 352 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
setDatabaseRepository()
setDatabaseRepository (string $entityClassName) protected
Set the given name as the current database target entity.
Parameters
string $entityClassName
Returns
void
Definition at line 67 of file EntityManagerTrait.php.
Referenced by OCA\CAFEVDB\Traits\getDatabaseRepository().
setUser()
setUser ($user) protected
Install a new user.
Parameters
null | IUser $user
Returns
null|IUser old user.
Definition at line 418 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
setUserId()
setUserId (string $userId) protected
Install a new user id.
Parameters
string $userId The user id to install.
Returns
null|IUser old user.
Definition at line 406 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
setUserValue()
setUserValue (string $key, mixed $value, ?string $userId = null) protected
Parameters
string $key Config key.
mixed $value Value to set.
null | string $userId Use the current user if null.
Returns
mixed
Definition at line 198 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
shareOwner()
shareOwner () protected
Returns
null|\OCP\IUSER
Definition at line 449 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\shareOwnerId(), and OCA\CAFEVDB\Traits\user().
shareOwnerId()
shareOwnerId () protected
Returns
null|string the User id of the share-owner, if configured.
Definition at line 441 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
Referenced by OCA\CAFEVDB\Traits\shareOwner().
shouldDebug()
shouldDebug (int $flag) protected
Check whether the current config-setting for debug contains the provided flags.
Parameters
int $flag
Returns
bool
Definition at line 1167 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\getConfigValue().
Referenced by OCA\CAFEVDB\Traits\toolTipsService().
subAdminGroup()
subAdminGroup () protected
Return the dedicated admin-group if it exists.
Returns
null|IGroup
Definition at line 536 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
subAdminGroupId()
subAdminGroupId () protected
Return the id of the dedicated admin-group which contains all sub-admins.
Returns
string
Definition at line 526 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
subAdminManager()
subAdminManager () protected
Returns
ISubAdmin
Definition at line 170 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
sudo()
sudo (string $uid, callable $callback) protected
Fake execution with other user-id.
Note that this function will catch any exception thrown while executing the callback-function and in case an exeption has been called will re-throw the exception.
Parameters
string $uid The "fake" uid.
callable $callback function.
Returns
mixed Whatever the callback-functoni returns.
Definition at line 435 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
timeStamp()
timeStamp (?string $format = null, ?DateTimeZone $timeZone = null) protected
Call ConfigService::formatTimeStamp() with the current date and time.
Parameters
null | string $format
null | \\DateTimeZone $timeZone
Returns
string
Definition at line 1011 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
toolTipsService()
toolTipsService () protected
Returns
ToolTipsService
Definition at line 1077 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\di(), OCA\CAFEVDB\Traits\shouldDebug(), and OCA\CAFEVDB\Traits\toolTipsService().
Referenced by OCA\CAFEVDB\Traits\toolTipsService().
translate()
translate (mixed $entity, string $field, ?string $locale, mixed $value)
Convenience, forward potential translation attempts to the underlying translation backend.
The idea is to hide the underlying backend.
Parameters
mixed $entity
string $field
string | null $locale If null the default locale is used.
mixed $value
Returns
EntityRepository $this
Definition at line 57 of file EntityTranslationTrait.php.
translationVariants()
translationVariants (string $name) protected
Search for translation variants by trying several camel-case transformations.
Parameters
string $name
Returns
string
Definition at line 1054 of file ConfigTrait.php.
transliterate()
transliterate (string $string, ?string $locale = null)
Transliterate the given string to the given or default locale.
Parameters
string $string
null | string $locale
Returns
string
Definition at line 924 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\defaultUserIdSlug().
urlGenerator()
urlGenerator () protected
Returns
IURLGenerator
Definition at line 152 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
user()
user (?string $userId = null) protected
Parameters
null | string $userId
Get the currently active user.
Returns
null|IUser
Definition at line 388 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Referenced by OCA\CAFEVDB\Traits\shareOwner().
userId()
userId () protected
Returns
null|string
Definition at line 394 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
userManager()
userManager () protected
Returns
IUserManager
Definition at line 158 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
userSession()
userSession () protected
Returns
IUserSession
Definition at line 146 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
verifyHash()
verifyHash ($value, $hash) protected
Parameters
null | string $value Value to verify.
null | string $hash Hash to verify against.
Returns
bool \true if either hash or value are empty or if the hash could be verified.
Definition at line 312 of file ConfigTrait.php.
References OCA\CAFEVDB\Traits\configService().
Variable Documentation
$appContainer
IAppContainer $appContainer protected
Definition at line 41 of file TimeStampTrait.php.
$appName
string $appName protected
Definition at line 43 of file InitialStateTrait.php.
$configService
ConfigService $configService protected
Definition at line 62 of file ConfigTrait.php.
$databaseRepository
BaseEntityRepository $databaseRepository protected
Definition at line 47 of file EntityManagerTrait.php.
$entityClassName
string $entityClassName protected
Definition at line 44 of file EntityManagerTrait.php.
$historyService
HistoryService $historyService private
Definition at line 52 of file InitialStateTrait.php.
$initialStateService
IInitialStateService $initialStateService private
Definition at line 49 of file InitialStateTrait.php.
$l
IL10N $l protected
Definition at line 68 of file ConfigTrait.php.
$toolTipsService
ToolTipsService $toolTipsService protected
Definition at line 65 of file ConfigTrait.php.
$translationRepository
TranslationRepository $translationRepository protected
Definition at line 41 of file EntityTranslationTrait.php.
ConfigTrait
trait ConfigTrait
Initial value:
{
  use \OCA\CAFEVDB\Toolkit\Traits\LoggerTrait
Too big a traits class to forward most of the ConfigService methods to the using class.
Definition at line 57 of file ConfigTrait.php.
EntityManagerTrait
trait EntityManagerTrait
Initial value:
{
  protected $entityManager
Database EntityManager short-cuts.
Definition at line 38 of file EntityManagerTrait.php.
EntityTranslationTrait
trait EntityTranslationTrait
Initial value:
{
  protected $entityManager
Translate data-base columns on the fly.
Definition at line 35 of file EntityTranslationTrait.php.
InitialStateTrait
trait InitialStateTrait
Initial value:
{
  use ConfigTrait
Provide an "initial state" for JavaScript.
Definition at line 38 of file InitialStateTrait.php.
SessionTrait
trait SessionTrait
Initial value:
{
  private $session
Session-store abstraction trait.
Definition at line 30 of file SessionTrait.php.
TimeStampTrait
trait TimeStampTrait
Initial value:
{
  protected $dateTimeZone
Generate a time-stamp strings.
Definition at line 35 of file TimeStampTrait.php.