CamerataDB: OCA\CAFEVDB\Database\Doctrine\ORM\Traits Namespace Reference
OCA\CAFEVDB\Database\Doctrine\ORM\Traits Namespace Reference
Orchestra member, musician and project management application.
Functions
arrayCTOR ()
Use reflection inspection to export all of the private keys; automatically called on post-load if the entity used lifecycle-callbacks.
__wakeup ()
{}
toArray ()
offsetExists (mixed $offset)
{}
offsetGet (mixed $offset)
{}
offsetSet (mixed $offset, mixed $value)
{}
offsetUnset (mixed $offset)
{}
static methodName (string $prefix, string $offset)
static offsetNormalize (string $offset)
setCreated ($created)
Sets created.
getCreated ()
Returns created.
findLike (array $criteria, ?array $orderBy=null, ?int $limit=null, ?int $offset=null,)
Find entities by given wild-card criteria.
findOneLike (array $criteria)
Find one or no entity by given wild-card criteria.
static addOrderBy (ORM\QueryBuilder $qb, ?array $orderBy=null, ?int $limit=null, ?int $offset=null, ?string $alias=null)
Adds an order-by phrase and limits to the given query-builder.
setDeleted (mixed $deleted=null)
Set or clear the deleted at timestamp.
getDeleted ()
Get the deleted at timestamp value.
isDeleted ()
Check if the entity has been soft deleted.
isExpired ()
Return whether this object is expired and is about to be deleted on the next call to delete.
setLocale (?string $locale)
Set the "locale" per-entity override locale for table field translations.
getLocale ()
Get the "locale" per-entity override locale for table field translations.
filterTranslatableFields (array $fields)
Tweak the set of translatable fields based on the current state of the entity.
setUpdated ($updated)
Sets updated.
getUpdated ()
Returns updated.
setUuid ($uuid)
Set uuid.
getUuid ()
Get uuid.
prePersistUuid ()
{}
preUpdateUuid ()
{}
ensureUuid ()
{}
Variables
trait ArrayTrait
Generic \ArrayAccess implementation for entities.
trait CreatedAt
Field $created and setter/getter.
$created
e
trait CreatedAtEntity
Add Gedmo annotations to the CreatedAt trait.
trait FindLikeTrait
Trait for entity repositories which adds kind of a symbolic query "language".
static $modifiers
static $comparisons
static $junctors
trait PerEntitySequenceTrait
A special trait for a repository for entities with one primary foreign key and a sequence wich forms a composite key together with the "primary" foreign key.
$nonSequenceNames = []
trait SoftDeleteableEntity
Helper for Gedmo soft-deleteable entities.
$deleted
@ORM\Column(type="datetime_immutable", nullable=true)
trait Timestampable
Union of UpdatedAt and CreatedAt traits.
trait TimestampableEntity
Union of CreatedAtEntity and UpdatedAtEntry traits.
trait TranslatableTrait
Helper for Gedmo "translatable" entities.
$translationChangeSet
Gedmo\Translatable (has to?) clean the changeset of the actual entity.
trait UpdatedAt
Field $updated and setter/getter.
$updated
e
trait UpdatedAtEntity
Add Gedmo annotations to UpdatedAt trait.
trait UuidTrait
Support trait for entities with an UUID field.
Detailed Description
Orchestra member, musician and project management application.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021, 2022, 2023 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/. Based on, with "At" removed from the names, i.e. updatedAt replaced by updated etc.
Timestampable Trait, usable with PHP >= 5.4
Author
Gediminas Morkevicius gedim.nosp@m.inas.nosp@m..mork.nosp@m.evic.nosp@m.ius@g.nosp@m.mail.nosp@m..com @license MIT License (http://www.opensource.org/licenses/mit-license.php)
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/. Based on, with "At" removed from the names, i.e. updatedAt replaced by updated etc.
Timestampable Trait, usable with PHP >= 5.4
Author
Gediminas Morkevicius gedim.nosp@m.inas.nosp@m..mork.nosp@m.evic.nosp@m.ius@g.nosp@m.mail.nosp@m..com @license MIT License (http://www.opensource.org/licenses/mit-license.php)
Function Documentation
__wakeup()
__wakeup ()
{}
Definition at line 69 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\arrayCTOR().
addOrderBy()
static addOrderBy (ORM\QueryBuilder $qb, ?array $orderBy = null, ?int $limit = null, ?int $offset = null, ?string $alias = null) static protected
Adds an order-by phrase and limits to the given query-builder.
Parameters
ORM\\QueryBuilder $qb The ORM query builder instance.
null | array $orderBy Order-by criteria.
int | null $limit Limit the number of results.
int | null $offset Offset into the result set.
string | null $alias Table alias to prepend to the field-names in $orderBy. The alias is not added if the field names already contain a field-separator.
Returns
ORM\QueryBuilder
Definition at line 131 of file FindLikeTrait.php.
arrayCTOR()
arrayCTOR () protected
Use reflection inspection to export all of the private keys; automatically called on post-load if the entity used lifecycle-callbacks.
Returns
void
@ORM\PostLoad
Definition at line 46 of file ArrayTrait.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\__wakeup(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetExists().
ensureUuid()
ensureUuid () private
{}
Support function which ensures that the uuid-field is set. It generates a new UUID if $this->uuid is empty.
Returns
void
Definition at line 106 of file UuidTrait.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\prePersistUuid(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\preUpdateUuid().
filterTranslatableFields()
filterTranslatableFields (array $fields)
Tweak the set of translatable fields based on the current state of the entity.
This can be used to remove fields. Addings fields would at least brake the tree-walker as it has to start with the default set of fields.
Parameters
array $fields
Returns
array
Definition at line 80 of file TranslatableTrait.php.
findLike()
findLike (array $criteria, ?array $orderBy = null, ?int $limit = null, ?int $offset = null)
Find entities by given wild-card criteria.
This is like findBy() but the criterias may contain '' or '*', in which case a LIKE comparison is used.
Parameters
array $criteria Search criteria.
array $orderBy Order-by criteria.
int | null $limit Limit on the number of results.
int | null $offset Offset into the result set.
Returns
array
Definition at line 69 of file FindLikeTrait.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\findOneLike().
findOneLike()
findOneLike (array $criteria)
Find one or no entity by given wild-card criteria.
This is like findOne() but the criterias may contain '' or '*', in which case a LIKE comparison is used.
Parameters
array $criteria Search criteria.
Returns
null|object
Definition at line 104 of file FindLikeTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\findLike().
getCreated()
getCreated ()
Returns created.
Returns
\DateTimeImmutable
Definition at line 55 of file CreatedAt.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$created.
getDeleted()
getDeleted ()
Get the deleted at timestamp value.
Will return null if the entity has not been soft deleted.
Returns
\DateTimeImmutable|null
Definition at line 63 of file SoftDeleteableEntity.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$deleted.
getLocale()
getLocale ()
Get the "locale" per-entity override locale for table field translations.
Returns
null|string
Definition at line 66 of file TranslatableTrait.php.
getUpdated()
getUpdated ()
Returns updated.
Returns
\DateTimeImmutable
Definition at line 66 of file UpdatedAt.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$updated.
getUuid()
getUuid ()
Get uuid.
Returns
\OCA\CAFEVDB\Wrapped\Ramsey\Uuid\UuidInterface
Definition at line 73 of file UuidTrait.php.
isDeleted()
isDeleted ()
Check if the entity has been soft deleted.
Returns
bool
Definition at line 73 of file SoftDeleteableEntity.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$deleted.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\isExpired().
isExpired()
isExpired ()
Return whether this object is expired and is about to be deleted on the next call to delete.
Returns
bool
Definition at line 84 of file SoftDeleteableEntity.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\isDeleted().
methodName()
static methodName (string $prefix, string $offset) static private
Parameters
string $prefix
string $offset
Returns
string
Definition at line 132 of file ArrayTrait.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetGet(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetSet().
offsetExists()
offsetExists (mixed $offset)
{}
Definition at line 85 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\arrayCTOR().
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetGet(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetSet().
offsetGet()
offsetGet (mixed $offset)
{}
Definition at line 94 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\methodName(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetExists().
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\toArray().
offsetNormalize()
static offsetNormalize (string $offset) static private
Parameters
string $offset
Returns
string
Definition at line 142 of file ArrayTrait.php.
offsetSet()
offsetSet (mixed $offset, mixed $value)
{}
Definition at line 107 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\methodName(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetExists().
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetUnset().
offsetUnset()
offsetUnset (mixed $offset)
{}
Definition at line 120 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetSet().
prePersistUuid()
prePersistUuid ()
{}
@ORM\prePersist
Definition at line 83 of file UuidTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\ensureUuid().
preUpdateUuid()
preUpdateUuid ()
{}
@ORM\preUpdate
Definition at line 93 of file UuidTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\ensureUuid().
setCreated()
setCreated ($created)
Sets created.
Parameters
string | int | \\DateTimeInterface $created
Returns
self
Definition at line 44 of file CreatedAt.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$created.
setDeleted()
setDeleted (mixed $deleted = null)
Set or clear the deleted at timestamp.
Parameters
string | int | \\DateTimeInterface $deleted
Returns
self
Definition at line 51 of file SoftDeleteableEntity.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$deleted.
setLocale()
setLocale (?string $locale)
Set the "locale" per-entity override locale for table field translations.
Parameters
null | string $locale
Returns
self
Definition at line 55 of file TranslatableTrait.php.
setUpdated()
setUpdated ($updated)
Sets updated.
Parameters
string | int | \\DateTimeInterface $updated
Returns
self
Definition at line 55 of file UpdatedAt.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\$updated.
setUuid()
setUuid ($uuid)
Set uuid.
Parameters
string | \\Ramsey\\Uuid\\UuidInterface $uuid
Returns
Musiker
Definition at line 55 of file UuidTrait.php.
toArray()
toArray ()
Returns
array
Definition at line 75 of file ArrayTrait.php.
References OCA\CAFEVDB\Database\Doctrine\ORM\Traits\offsetGet().
Variable Documentation
$comparisons
$comparisons static private
Initial value:
= [
    '<=' => 'lte',
    '>=' => 'gte',
    '=' => 'eq',
    '<' => 'lt',
    '>' => 'gt',
  ]
Definition at line 39 of file FindLikeTrait.php.
$created
DateTimeImmutable $created protected
e
@Gedmo\Timestampable(on="create") @ORM\Column(type="datetime_immutable", nullable=true)
Definition at line 35 of file CreatedAt.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\getCreated(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\setCreated().
$deleted
DateTimeImmutable nul $deleted protected
@ORM\Column(type="datetime_immutable", nullable=true)
l
Definition at line 42 of file SoftDeleteableEntity.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\getDeleted(), OCA\CAFEVDB\Database\Doctrine\ORM\Traits\isDeleted(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\setDeleted().
$junctors
$junctors static private
Initial value:
= [
    '(|' => [ 'orX' ],
    '(&' => [ 'andX' ],
    '!(|' => [ 'not', 'orX', ],
    '!(&' => [ 'not', 'andX', ],
    ')' => [ ')' ],
  ]
Definition at line 46 of file FindLikeTrait.php.
$modifiers
$modifiers static private
Initial value:
= [
    '!' => 'not',
  ]
Definition at line 36 of file FindLikeTrait.php.
$nonSequenceNames
arry $nonSequenceNames = [] protected
Definition at line 49 of file PerEntitySequenceTrait.php.
$translationChangeSet
$translationChangeSet private
Gedmo\Translatable (has to?) clean the changeset of the actual entity.
Unfortunately this also spoils the update listeners. We work around by remembering any old value.
@Gedmo\TranslationChangeSet
Definition at line 46 of file TranslatableTrait.php.
$updated
DateTimeImmutable $updated protected
e
@Gedmo\Timestampable(on="update") @ORM\Column(type="datetime_immutable", nullable=true)
Definition at line 46 of file UpdatedAt.php.
Referenced by OCA\CAFEVDB\Database\Doctrine\ORM\Traits\getUpdated(), and OCA\CAFEVDB\Database\Doctrine\ORM\Traits\setUpdated().
ArrayTrait
trait ArrayTrait
Initial value:
{
  private $keys
Generic \ArrayAccess implementation for entities.
Definition at line 34 of file ArrayTrait.php.
CreatedAt
trait CreatedAt
Initial value:
{
  use \OCA\CAFEVDB\Toolkit\Traits\DateTimeTrait
Field $created and setter/getter.
Definition at line 28 of file CreatedAt.php.
CreatedAtEntity
trait CreatedAtEntity
Initial value:
{
  use CreatedAt
Add Gedmo annotations to the CreatedAt trait.
Definition at line 40 of file CreatedAtEntity.php.
FindLikeTrait
trait FindLikeTrait
Initial value:
{
  use LogTrait
Trait for entity repositories which adds kind of a symbolic query "language".
Definition at line 33 of file FindLikeTrait.php.
PerEntitySequenceTrait
trait PerEntitySequenceTrait
Initial value:
{
  protected $sequenceFieldName
A special trait for a repository for entities with one primary foreign key and a sequence wich forms a composite key together with the "primary" foreign key.
Definition at line 43 of file PerEntitySequenceTrait.php.
SoftDeleteableEntity
trait SoftDeleteableEntity
Initial value:
{
  use UnusedTrait
Helper for Gedmo soft-deleteable entities.
Definition at line 32 of file SoftDeleteableEntity.php.
Timestampable
trait Timestampable
Initial value:
{
  use UpdatedAt
Union of UpdatedAt and CreatedAt traits.
Definition at line 39 of file Timestampable.php.
TimestampableEntity
trait TimestampableEntity
Initial value:
{
  use CreatedAtEntity
Union of CreatedAtEntity and UpdatedAtEntry traits.
Definition at line 39 of file TimestampableEntity.php.
TranslatableTrait
trait TranslatableTrait
Initial value:
{
  private $locale
Helper for Gedmo "translatable" entities.
Definition at line 30 of file TranslatableTrait.php.
UpdatedAt
trait UpdatedAt
Initial value:
{
  use \OCA\CAFEVDB\Toolkit\Traits\DateTimeTrait
Field $updated and setter/getter.
Definition at line 39 of file UpdatedAt.php.
UpdatedAtEntity
trait UpdatedAtEntity
Initial value:
{
  use UpdatedAt
Add Gedmo annotations to UpdatedAt trait.
Definition at line 40 of file UpdatedAtEntity.php.
UuidTrait
trait UuidTrait
Initial value:
{
  private $uuid
Support trait for entities with an UUID field.
See also
GetByUuidTrait
Definition at line 39 of file UuidTrait.php.