CamerataDB: OCA\CAFEVDB\Storage\Database Namespace Reference
OCA\CAFEVDB\Storage\Database Namespace Reference
Orchestra member, musician and project management application.
Data Structures
class AbstractReadMeFactory
Abstract factory baseclass.
class BankTransactionsStorage
Storage implementation for data-base storage, including access to encrypted entities.
class EmptyDirectoryNode
This is a placeholder which appears as top-level directory if the storage does not hold any entries.
class Factory
Utility class in order to hide the fancy CTOR pattern of the NC storage classes.
class InMemoryFileNode
Dummy file node which only resides in memory.
class MountProvider
Mount parts of the database-storage somewhere.
class ProjectBalanceSupportingDocumentsStorage
Storage implementation for data-base storage, including access to encrypted entities.
class ProjectParticipantsStorage
Storage implementation for data-base storage, including access to encrypted entities.
class ReadMeFactory
Generate in-memory README nodes.
interface ReadMeFactoryInterface
Factory interface for generating in-memory README nodes.
class Registration
Register some utiltiy services in order to ease dependency injection.
class Storage
Storage implementation for data-base storage, including access to encrypted entities.
class TaxExemptionNoticesStorage
Storage implementation for data-base storage, including access to encrypted entities.
Functions
getAppL10n ()
getDocumentsFolderName ()
Get the name of the per-participant document folder.
getSupportingDocumentsFolderName ()
getBankTransactionsFolderName ()
Get the name of the sub-folder containing supporting documents for bank-transactions.
getReceivablesFolderName ()
Get the name of the sub-folder containing supporting documents for bank-transactions.
getTaxAuthoritiesFolderName ()
Get the name of the folder containing tax office related stuff.
getTaxExemptionNoticesFolderName ()
Get the name of the folder containing tax exemption notices.
getLegacyPaymentRecordFileName (int $compositePaymentId, string $userIdSlug, ?string $extension=null,)
PME-legacy.
getPaymentRecordFileName (Entities\CompositePayment $compositePayment, ?string $extension=null,)
Generate a file-name for the given composite payment.
getDebitMandatesFolderName ()
Get the name of the sub-folder holding hard-copies of debit-mandates.
getLegacyDebitMandateFileName (string $debitMandateReference, ?string $extension=null)
PME-legacy.
getDebitMandateFileName (Entities\SepaDebitMandate $debitMandate, ?string $extension=null)
Generate a file-name for a hard-copy of the given debit-mandate.
getLegacyTaxExemptionNoticeFileName (string|Types\EnumTaxType $taxType, int $assessmentPeriodStart, int $assessmentPeriodEnd, ?string $extension=null,)
PME-legacy.
getTaxExemptionNoticeFileName (Entities\TaxExemptionNotice $taxExemptionNotice, ?string $extension=null,)
Generate a file-name for the given tax exemption notice.
Variables
trait DatabaseStorageNodeNameTrait
Actually just provide some path names, translated with the app's configured locale.
Detailed Description
Orchestra member, musician and project management application.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2024 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2014, 2016, 2020, 2021, 2022, Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2014, 2016, 2020, 2021, 2022, 2024, Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022, 2024 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022, 2024, Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2014, 2016, 2020, 2021, 2022, 2023, 2024, Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2014, 2016, 2020, 2021, 2022, 2024, Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2014, 2016, 2020, 2021, 2022, 2023, 2024, Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2022, 2024 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2024, Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
getAppL10n()
getAppL10n () protected
Returns
IL10N
Definition at line 49 of file DatabaseStorageNodeNameTrait.php.
References Application\get().
Referenced by OCA\CAFEVDB\Storage\Database\getBankTransactionsFolderName(), OCA\CAFEVDB\Storage\Database\getDebitMandatesFolderName(), OCA\CAFEVDB\Storage\Database\getDocumentsFolderName(), OCA\CAFEVDB\Storage\Database\getReceivablesFolderName(), OCA\CAFEVDB\Storage\Database\getSupportingDocumentsFolderName(), OCA\CAFEVDB\Storage\Database\getTaxAuthoritiesFolderName(), and OCA\CAFEVDB\Storage\Database\getTaxExemptionNoticesFolderName().
getBankTransactionsFolderName()
getBankTransactionsFolderName () protected
Get the name of the sub-folder containing supporting documents for bank-transactions.
Returns
string
Definition at line 84 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getDebitMandateFileName()
getDebitMandateFileName (Entities\SepaDebitMandate $debitMandate, ?string $extension = null) protected
Generate a file-name for a hard-copy of the given debit-mandate.
Parameters
Entities\\SepaDebitMandate $debitMandate
null | string $extension
Returns
string
Definition at line 203 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getLegacyDebitMandateFileName().
getDebitMandatesFolderName()
getDebitMandatesFolderName () protected
Get the name of the sub-folder holding hard-copies of debit-mandates.
Returns
string Translated name of the debit-mandates folder.
Definition at line 171 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getDocumentsFolderName()
getDocumentsFolderName () protected
Get the name of the per-participant document folder.
Returns
string Translated name of the documents sub-folder.
Definition at line 62 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getLegacyDebitMandateFileName()
getLegacyDebitMandateFileName (string $debitMandateReference, ?string $extension = null) protected
PME-legacy.
Parameters
string $debitMandateReference
null | string $extension
Returns
string
Definition at line 186 of file DatabaseStorageNodeNameTrait.php.
Referenced by OCA\CAFEVDB\Storage\Database\getDebitMandateFileName().
getLegacyPaymentRecordFileName()
getLegacyPaymentRecordFileName (int $compositePaymentId, string $userIdSlug, ?string $extension = null) protected
PME-legacy.
Parameters
int $compositePaymentId
string $userIdSlug
null | string $extension
Returns
string
Definition at line 133 of file DatabaseStorageNodeNameTrait.php.
getLegacyTaxExemptionNoticeFileName()
getLegacyTaxExemptionNoticeFileName (string|Types\EnumTaxType $taxType, int $assessmentPeriodStart, int $assessmentPeriodEnd, ?string $extension = null) protected
PME-legacy.
Parameters
string | Types\\EnumTaxType $taxType
int $assessmentPeriodStart
int $assessmentPeriodEnd
null | string $extension
Returns
string
Definition at line 221 of file DatabaseStorageNodeNameTrait.php.
Referenced by TaxExemptionNoticesStorage\parsePath().
getPaymentRecordFileName()
getPaymentRecordFileName (Entities\CompositePayment $compositePayment, ?string $extension = null) protected
Generate a file-name for the given composite payment.
Parameters
Entities\\CompositePayment $compositePayment
null | string $extension
Returns
string
Definition at line 158 of file DatabaseStorageNodeNameTrait.php.
getReceivablesFolderName()
getReceivablesFolderName () protected
Get the name of the sub-folder containing supporting documents for bank-transactions.
Returns
string
Definition at line 96 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getSupportingDocumentsFolderName()
getSupportingDocumentsFolderName () protected
Returns
string The name of the sub-folder containing supporting documents.
Definition at line 72 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getTaxAuthoritiesFolderName()
getTaxAuthoritiesFolderName () protected
Get the name of the folder containing tax office related stuff.
Returns
string
Definition at line 107 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
getTaxExemptionNoticeFileName()
getTaxExemptionNoticeFileName (Entities\TaxExemptionNotice $taxExemptionNotice, ?string $extension = null) protected
Generate a file-name for the given tax exemption notice.
Parameters
Entities\\TaxExemptionNotice $taxExemptionNotice
null | string $extension
Returns
string
Definition at line 248 of file DatabaseStorageNodeNameTrait.php.
getTaxExemptionNoticesFolderName()
getTaxExemptionNoticesFolderName () protected
Get the name of the folder containing tax exemption notices.
Returns
string
Definition at line 117 of file DatabaseStorageNodeNameTrait.php.
References OCA\CAFEVDB\Storage\Database\getAppL10n().
Variable Documentation
DatabaseStorageNodeNameTrait
trait DatabaseStorageNodeNameTrait
Initial value:
{
  protected $appL10n
Actually just provide some path names, translated with the app's configured locale.
Definition at line 40 of file DatabaseStorageNodeNameTrait.php.