#!/usr/bin/env php
<?php
/**
 * Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine <himself@claus-justus-heine.de>
 * @copyright 2020, 2021, 2022, 2023, 2024, 2025 Claus-Justus Heine
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB\DevScripts\PhpToTypeScript;

use ReflectionClass;
use UnexpectedValueException;

use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Output\ConsoleOutputInterface;
use Symfony\Component\Console\Output\ConsoleSectionOutput;
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception as ProcessExceptions;
use Symfony\Component\Console\Helper\ProgressBar;

use OCA\CAFEVDB\Common\Util;

/**
 * Generate enough meta-data for TypeScript to be able to define getters for
 * to-one and iterators for to-many associations.
 */
class GenerateEntityMetadata
{
  private array $entityMetaInfo = [];

  private string $entityNameSpace;

  const FIELD_TYPE_OWNED = 'owned';
  const FIELD_TYPE_TO_ONE = 'to-one';
  const FIELD_TYPE_TO_MANY = 'to-many';

  const FIELD_TYPES = [
    self::FIELD_TYPE_OWNED,
    self::FIELD_TYPE_TO_MANY,
    self::FIELD_TYPE_TO_ONE,
  ];

  const META_DATA_NAME = 'EntityMetadata';

  /**
   * CTOR.
   *
   * @param string $phpNameSpacePrefix PHP-Namespace prefix to strip from the
   * start. Output will go to subdirectories according to the
   * remaining namespace.
   *
   * @param string $outputPrefix Output will start at this directory into a
   * directory formed by the full class-name of each entity (after stripping
   * the PHP namespace prefix).
   *
   * @param ConsoleOutputInterface $output
   *
   * @param string $ormCliCmd The full path the ORM cli command which is used to
   * obtain the list of known databse entities and the meta-data information.
   */
  public function __construct(
    private string $phpNameSpacePrefix,
    private string $outputPrefix,
    private ConsoleOutputInterface $output,
    private string $ormCliCmd = __DIR__ . '/../orm-cmd.php',
  ) {
  }

  /**
   * The purpose of this function is to generate a TypeScript snippet which
   * enables the TypeScript-modules generator to resolve the EntityMap type
   * and generate appropriate import statements for that type.
   *
   * @return string
   */
  public function exportEntityMap(): string
  {
    $entityParentNameSpace = substr($this->entityNameSpace, 0, strrpos($this->entityNameSpace, '\\'));
    $entityParentNameSpace = str_replace('\\', '.', $entityParentNameSpace);

    return "declare namespace {$entityParentNameSpace }." . self::META_DATA_NAME . " {
  // Ignore me: this is just here in order to inject the type for the sake
  // of namespace / type resolution during auto-generation of the php -> typescript
  // definition.
  export interface EntityMap {}
}
";
  }

  /**
   * Generate TypeScript code. The return value is a TS dummy namespace which
   * enables the ts-modules-from-namespaces generator to resolve the
   * EntityMap interface.
   *
   * @return void
   */
  public function dumpTypeScriptData(): void
  {
    if (!($this->entityNameSpace ?? null)) {
      throw new UnexpectedValueException('Entity-namespace is null, did you call ' . __CLASS__ . '::generateSparseMetadata()?');
    }
    $entityParentNameSpace = substr($this->entityNameSpace, 0, strrpos($this->entityNameSpace, '\\'));
    $path  = $this->outputPrefix . '/' . str_replace('\\', '/', $entityParentNameSpace);
    $path = $path . '/' . self::META_DATA_NAME;
    mkdir($path, recursive: true);
    $metadataForwarder = '// Automatically generated by ' . __CLASS__ . ", do not edit

";

    $metadataExports = [];
    $entityNameExports = [];
    $entityTypeExports = [];
    $entityTypeMap = '';
    foreach ($this->entityMetaInfo as $entity => $entityInfo) {
      $upcaseEntity = strtoupper(Util::camelCaseToDashes($entity, '_'));

      $metadataForwarder .= "import {$entity}Metadata, { ENTITY_NAME as {$upcaseEntity}_ENTITY_NAME, type Entity as {$entity} } from './" . self::META_DATA_NAME . "/{$entity}Metadata.ts';
";
      $metadataExports[] = "  {$entity}Metadata,";
      $entityNameExports[] = "  {$upcaseEntity}_ENTITY_NAME,";
      $entityTypeExports[] = "  type {$entity},";
      $entityTypeMap .= "[{$upcaseEntity}_ENTITY_NAME]: {$entity},
";

      $metadata = '// Automatically generated by ' . __CLASS__ . ", do not edit

export { type {$entity} as Entity } from '../Entities.ts';

export const ENTITY_NAME = '{$entity}' as const;

const metadata = {
";
      foreach ($entityInfo as $field => $fieldInfo) {
        $metadata .= "  {$field}: {
";
        foreach ($fieldInfo as $key => $value) {
          if (is_string($value)) {
            $value = "'{$value}'";
          } elseif ($value === true) {
            $value= 'true';
          } elseif ($value === false) {
            $value = 'false';
          }
          $metadata .= "    {$key}: {$value},
";
        }
        $metadata .= '  },
';
      }
      $metadata .= '};

export default metadata;

';
      file_put_contents("{$path}/{$entity}Metadata.ts", $metadata);
    }
    // add a type map from entity names to entity types.
    $metadataForwarder .= "
export interface EntityMap {
{$entityTypeMap}}
";
    foreach ([$metadataExports, $entityNameExports, $entityTypeExports] as $exports) {
      sort($exports);
      $exports = implode("\n", $exports);
      $metadataForwarder .= "
export {
{$exports}}

";
    }

    file_put_contents(dirname($path) . '/' . self::META_DATA_NAME . '.ts', $metadataForwarder);
  }

  /**
   * Run the ORM cli commands and form an array of meta-data information.
   *
   * @return array
   */
  public function generateSparseMetadata(): array
  {
    $nameSpacePrefix = 'OCA\\CAFEVDB\\Database\\Doctrine\\ORM\\Entities\\';

    $entityNames = [];
    $this->entityMetaInfo = [];

    $headerSection = $this->output->section();
    $textSection = $this->output->section();
    $textSection->setMaxHeight(5);
    $progressSection = $this->output->section();
    $progressBar = new ProgressBar($progressSection);
    $warningsSection = $this->output->section();

    // --format=json not understood here.
    $ormCliProcess = new Process([
      $this->ormCliCmd,
      'orm:info',
    ]);

    $headerSection->writeln('<info>' . 'Fetching list of entities ...' . '</>');
    $ormCliProcess->run();
    $rawEntities = $ormCliProcess->getOutput();
    $numberOfLines = substr_count($rawEntities, "\n");
    $progressBar->start($numberOfLines);
    $ormFile = fopen('php://temp', 'r+');
    fputs($ormFile, $rawEntities);
    rewind($ormFile);
    /* discard */ fgets($ormFile, 4096);
    $line = fgets($ormFile, 4096);
    while ($line !== false) {
      $line = trim($line);
      if (str_starts_with($line, '[OK]')) {
        $entity = trim(substr($line, strlen('[OK]')));
        $textSection->writeln($entity);
        $entityNames[] = $entity;
      }
      $progressBar->advance();
      $line = fgets($ormFile, 4096);
    }
    sort($entityNames);

    $textSection->clear();
    $headerSection->writeln('<info>' . 'Obtaining metadata information ...' . '</>');
    $progressBar->start(count($entityNames));

    // Ok, now fetch the meta data. For implementing kind-of entity-repositories
    // (read-only) in the frontend we just need the information if a field is an
    // association, and if this is the case, whether it is to-on -- this yields a
    // simple getter -- or if it is to-may -- this yields an iterator.
    foreach ($entityNames as $entityName) {
      $ormCliProcess = new Process([
        $this->ormCliCmd,
        '--format=json',
        'orm:mapping:describe',
        $entityName,
      ]);
      $ormCliProcess->run();
      if (!$ormCliProcess->isSuccessful()) {
        throw new UnexpectedValueException('ORM CLI process failed: ' . $ormCliProcess->getErrorOuput());
      }

      $metadataJson = $ormCliProcess->getOutput();

      $metadata = json_decode($metadataJson, true);

      if (!str_starts_with($entityName, $this->phpNameSpacePrefix)
          || str_contains($entityName, 'Wrapped')) {
        $warningsSection->writeln('<error>' . "Entity {$entityName} has been skipped, not ours ..." . '</>');
        continue;
      }
      $shortName = new ReflectionClass($entityName)->getShortName();
      if (!($this->entityNameSpace ?? null)) {
        // just assume all entities live in the same namespace ...
        $this->entityNameSpace = trim(substr(substr($entityName, 0, -strlen($shortName) - 1), strlen($this->phpNameSpacePrefix)), '\\');
        $textSection->writeln('Entity-Namespace: ' . $this->entityNameSpace);
      }
      $entityName = $shortName;
      // echo $entityName . PHP_EOL;
      // print_r($metadata);
      $metaInfo = [];
      foreach ($metadata['fieldMappings'] as $fieldName => $ownField) {
        $metaInfo[$fieldName] = [
          'fieldName' => $fieldName,
          'type' => $ownField['type'],
          'id' => !!$ownField['id'],
          'mapping' => self::FIELD_TYPE_OWNED,
        ];
      }
      foreach ($metadata['associationMappings'] as $fieldName => $associationField) {
        $multiplicity = str_contains($associationField['class'], 'ToOne')
          ? self::FIELD_TYPE_TO_ONE
          : self::FIELD_TYPE_TO_MANY;
        $metaInfo[$fieldName] = [
          'fieldName' => $fieldName,
          'id' => !!$associationField['id'],
          'mapping' => $multiplicity,
        ];
      }
      $this->entityMetaInfo[$entityName] = $metaInfo;
      if ($this->output->getVerbosity() >= OutputInterface::VERBOSITY_VERBOSE) {
        $text = explode(PHP_EOL, $entityName . ': ' . print_r($metaInfo, true));
        foreach ($text as $line) {
          $textSection->writeln($line, options: OutputInterface::VERBOSITY_VERBOSE);
        }
      } else {
        $textSection->writeln($entityName);
      }
      $progressBar->advance();
    }

    return $this->entityMetaInfo;
  }
}
