<?php
/**Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine
 * @copyright 2011-2014 Claus-Justus Heine <himself@claus-justus-heine.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU GENERAL PUBLIC LICENSE
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */

/**CamerataDB namespace to prevent name-collisions.
 */
namespace CAFEVDB
{

/**Display all or selected musicians.
 */
class InstrumentInsurance
  extends Instrumentation
{
  const CSS_PREFIX = 'cafevdb-page';
  const RATE_TABLE = 'InsuranceRates';
  const MEMBER_TABLE = 'InstrumentInsurance';
  const TAXES = 0.19;
  protected $broker;
  protected $brokerNames;
  protected $scope;
  protected $scopeNames;
  protected $accessory;
  protected $accessoryNames;

  function __construct($execute = true) {
    parent::__construct($execute);

    $handle = mySQL::connect($this->opts);

    $this->broker = mySQL::multiKeys('InstrumentInsurance', 'Broker', $handle);
    // brokerNames ... maybe store an additional table with further
    // information about the brokers
    foreach ($this->broker as $tag) {
      $this->brokerNames[$tag] = $tag;
    }
    
    $this->scope = mySQL::multiKeys('InstrumentInsurance', 'GeographicalScope', $handle);
    $this->scopeNames = array();
    foreach ($this->scope as $tag) {
      $this->scopeNames[$tag] = strval(L::t($tag));
    }
    if (false) {
      // Dummies to keep the translation right.
      L::t('Germany');
      L::t('Europe');
      L::t('World');
    }

    $this->accessory = mySQL::multiKeys('InstrumentInsurance', 'Accessory', $handle);
    $this->accessoryNames = array();
    foreach ($this->accessory as $tag) {
      $this->accessoryNames[$tag] = strval(L::t($tag));
    }
    if (false) {
      // Dummies to keep the translation right.
      L::t('false');
      L::t('true');
    }

    mySQL::close($handle);
  }

  public function shortTitle()
  {
    return L::t('Overview over the Bulk Instrument Insurances');
  }
  
  public function headerText()
  {
    return $this->shortTitle();
  }

  /**Display the list of all musicians. If $projectMode == true,
   * filter out all musicians present in $projectId and add a
   * hyperlink which will add the Musician to the respective project.
   */
  public function display()
  {
    Config::init();

    global $debug_query;
    $debug_query = Util::debugMode('query');

    $template        = $this->template;
    $project         = $this->project;
    $projectId       = $this->projectId;
    $recordsPerPage  = $this->recordsPerPage;
    $opts            = $this->opts;
    $musicianId      = $this->musicianId;

    $headervisibility = Util::cgiValue('headervisibility','expanded');


    /*
     * IMPORTANT NOTE: This generated file contains only a subset of huge amount
     * of options that can be used with phpMyEdit. To get information about all
     * features offered by phpMyEdit, check official documentation. It is available
     * online and also for download on phpMyEdit project management page:
     *
     * http://platon.sk/projects/main_page.php?project_id=5
     *
     * This file was generated by:
     *
     *                    phpMyEdit version: 5.7.1
     *       phpMyEdit.class.php core class: 1.204
     *            phpMyEditSetup.php script: 1.50
     *              generating setup script: 1.50
     */

    $opts['tb'] = 'InstrumentInsurance';

    // Number of records to display on the screen
    // Value of -1 lists all records in a table
    $opts['inc'] = $recordsPerPage;

    $opts['cgi']['persist'] = array(
      'Project' => $project,
      'ProjectId' => $projectId,
      'MusicianId' => $musicianId,
      'Template' => 'instrument-insurance',
      'DisplayClass' => 'InstrumentInsurance',
      'Table' => $opts['tb'],
      'headervisibility' => $headervisibility);

    // Name of field which is the unique key
    $opts['key'] = 'Id';

    // Type of key field (int/real/string/date etc.)
    $opts['key_type'] = 'int';

    // Sorting field(s)
    $opts['sort_field'] = array('Broker','GeographicalScope','MusicianId','Accessory');

    // Options you wish to give the users
    // A - add,  C - change, P - copy, V - view, D - delete,
    // F - filter, I - initial sort suppressed
    $opts['options'] = 'ACVDFM';

    // Number of lines to display on multiple selection filters
    $opts['multiple'] = '5';

    // Navigation style: B - buttons (default), T - text links, G - graphic links
    // Buttons position: U - up, D - down (default)
    //$opts['navigation'] = 'DB';

    $export = Navigation::tableExportButton();
    $opts['buttons'] = Navigation::prependTableButton($export, true);

    // Display special page elements
    $opts['display'] =  array_merge($opts['display'],
                                    array(
                                      'form'  => true,
                                      'query' => true,
                                      'sort'  => true,
                                      'time'  => true,
                                      'tabs'  => true
                                      ));

    // Set default prefixes for variables
    $opts['js']['prefix']               = 'PME_js_';
    $opts['dhtml']['prefix']            = 'PME_dhtml_';
    $opts['cgi']['prefix']['operation'] = 'PME_op_';
    $opts['cgi']['prefix']['sys']       = 'PME_sys_';
    $opts['cgi']['prefix']['data']      = 'PME_data_';

    /* Get the user's default language and use it if possible or you can
       specify particular one you want to use. Refer to official documentation
       for list of available languages. */
    //  $opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

    /* Table-level filter capability. If set, it is included in the WHERE clause
       of any generated SELECT statement in SQL query. This gives you ability to
       work only with subset of data from table.

       $opts['filters'] = "column1 like '%11%' AND column2<17";
       $opts['filters'] = "section_id = 9";
       $opts['filters'] = "PMEtable0.sessions_count > 200";
    */

    if ($musicianId > 0) {
      $opts['filters'] = "`PMEtable0`.`MusicianId` = ".$musicianId;
    }

    /* Field definitions
   
       Fields will be displayed left to right on the screen in the order in which they
       appear in generated list. Here are some most used field options documented.

       ['name'] is the title used for column headings, etc.;
       ['maxlen'] maximum length to display add/edit/search input boxes
       ['trimlen'] maximum length of string content to display in row listing
       ['width'] is an optional display width specification for the column
       e.g.  ['width'] = '100px';
       ['mask'] a string that is used by sprintf() to format field output
       ['sort'] true or false; means the users may sort the display on this column
       ['strip_tags'] true or false; whether to strip tags from content
       ['nowrap'] true or false; whether this field should get a NOWRAP
       ['select'] T - text, N - numeric, D - drop-down, M - multiple selection
       ['options'] optional parameter to control whether a field is displayed
       L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
       Another flags are:
       R - indicates that a field is read only
       W - indicates that a field is a password field
       H - indicates that a field is to be hidden and marked as hidden
       ['URL'] is used to make a field 'clickable' in the display
       e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
       ['URLtarget']  HTML target link specification (for example: _blank)
       ['textarea']['rows'] and/or ['textarea']['cols']
       specifies a textarea is to be used to give multi-line input
       e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
       ['values'] restricts user input to the specified constants,
       e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
       ['values']['table'] and ['values']['column'] restricts user input
       to the values found in the specified column of another table
       ['values']['description'] = 'desc_column'
       The optional ['values']['description'] field allows the value(s) displayed
       to the user to be different to those in the ['values']['column'] field.
       This is useful for giving more meaning to column values. Multiple
       descriptions fields are also possible. Check documentation for this.
    */

    $opts['fdd']['Id'] = array(
      'name'     => 'Id',
      'select'   => 'T',
      'options'  => 'AVCPDR', // auto increment
      'maxlen'   => 5,
      'align'    => 'right',
      'default'  => '0',
      'sort'     => true
      );

    $opts['fdd']['MusicianId'] = array('name'     => strval(L::t('Musician')),
                                       'select'   => 'T',
                                       'maxlen'   => 11,
                                       'sort'     => true,
                                       //'options'  => 'LFADV', // no change allowed
                                       'default' => 0,
                                       'values' => array('table' => 'Musiker',
                                                         'column' => 'Id',
                                                         'description' => array('columns' => array('Name', 'Vorname'),
                                                                                'divs' => array(', ')
                                                           ))
      );
    $opts['fdd']['BillToParty'] = array('name'     => strval(L::t('Bill-to Party')),
                                        'select'   => 'T',
                                        'maxlen'   => 11,
                                        'sort'     => true,
                                        'default'  => 0,
                                        //'options'  => 'LFADV', // no change allowed
                                        'values' => array('table' => 'Musiker',
                                                          'column' => 'Id',
                                                          'description' => array('columns' => array('Name', 'Vorname'),
                                                                                 'divs' => array(', ')
                                                            ))
                                      );

    $opts['fdd']['Broker'] = array('name' => strval(L::t('Insurance Broker')),
                                   'select'   => 'D',
                                   'maxlen'   => 384,
                                   'sort'     => true,
                                   'default'  => '',
                                   'values2'  => $this->brokerNames);

    $opts['fdd']['GeographicalScope'] = array('name' => strval(L::t('Geographical Scope')),
                                              'select'   => 'D',
                                              'maxlen'   => 384,
                                              'sort'     => true,
                                              'default'  => '',
                                              'values2'  => $this->scopeNames);

    $opts['fdd']['Object'] = array('name'     => strval(L::t('Insured Object')),
                                   'select'   => 'T',
                                   'maxlen'   => 384,
                                   'sort'     => true);

    $opts['fdd']['Accessory'] = array('name' => strval(L::t('Accessory')),
                                      'select'   => 'D',
                                      'maxlen'   => 384,
                                      'sort'     => true,
                                      'default' => 'false',
                                      'values2'  => $this->accessoryNames);

    $opts['fdd']['Manufacturer'] = array('name'     => strval(L::t('Manufacturer')),
                                         'select'   => 'T',
                                         'maxlen'   => 384,
                                         'sort'     => true);

    $opts['fdd']['YearOfConstruction'] = array('name'     => strval(L::t('Year of Construction')),
                                              'select'   => 'T',
                                              'maxlen'   => 384,
                                              'sort'     => true);

    $opts['fdd']['InsuranceAmount'] = Config::$opts['money'];
    $opts['fdd']['InsuranceAmount']['name'] = strval(L::t('Insurance Amount'));

    $opts['fdd']['InsuranceTotal'] = array(
      'input' => 'V',
      'name' => L::t('Total Insurance'),
      'select' => 'T',
      'options' => 'ACPDV',
      'sql' => "MusicianId",
      'escape' => false,
      'nowrap' => true,
      'sort' =>false,
      'php' => array(
        'type' => 'function',
        'function' => 'CAFEVDB\InstrumentInsurance::instrumentInsurancePME',
        'parameters' => array('headervisibility' => $headervisibility)
        )
      );

    if ($this->pme_bare) {
      // disable all navigation buttons, probably for html export
      $opts['navigation'] = 'N'; // no navigation
      $opts['options'] = '';
      // Don't display special page elements
      $opts['display'] =  array_merge($opts['display'],
                                      array(
                                        'form'  => false,
                                        'query' => false,
                                        'sort'  => false,
                                        'time'  => false,
                                        'tabs'  => false
                                        ));
      // Disable sorting buttons
      foreach ($opts['fdd'] as $key => $value) {
        $opts['fdd'][$key]['sort'] = false;
      }
    }

    $opts['execute'] = $this->execute;

    $this->pme = new \phpMyEdit($opts);

    if (Util::debugMode('request')) {
      echo '<PRE>';
      print_r($_POST);
      echo '</PRE>';
    }

  } // display()

  //!Button redirect
  public static function instrumentInsurancePME($insuranceId, $opts, $action, $k, $fds, $fdd, $row)
  {
    return Musicians::instrumentInsurance($row['qf1_idx'], $opts);
  }

  /**Fetch the total insurance amount for one musician.
   */
  public static function insuranceAmount($musicianId, $handle = false)
  {
    $ownConnection = $handle === false;
    if ($ownConnection) {
      Config::init();
      $handle = mySQL::connect(Config::$pmeopts);
    }

    $amount = 0;
    $query = "SELECT SUM(`InsuranceAmount`) FROM `InstrumentInsurance` WHERE `MusicianId` = ".$musicianId;
    $result = mySQL::query($query, $handle);
    $result = mySQL::fetch($result, MYSQL_NUM);
    if (isset($result[0])) {
      $amount = $result[0];
    }
    
    if ($ownConnection) {
      mySQL::close($handle);
    }

    return $amount;
  }

  /**Compute the annual insurance fee for the respective
   * musician. Note that the relevant column is the "BillToParty".
   */
  public static function annualFee($musicianId, $handle = false)
  {
    $ownConnection = $handle === false;
    if ($ownConnection) {
      Config::init();
      $handle = mySQL::connect(Config::$pmeopts);
    }

    $rates = array();
    $query = "SELECT * FROM `".self::RATE_TABLE."` WHERE 1";
    $result = mySQL::query($query, $handle);
    while ($row = mySQL::fetch($result)) {
      $rateKey = $row['Broker'].$row['GeographicalScope'];
      $rates[$rateKey] = $row['Rate'];
    }

    //print_r($rates);

    $fee = 0.0;
    $query = "SELECT * FROM `".self::MEMBER_TABLE."` WHERE ("
      . " ( (ISNULL(`BillToParty`) OR `BillToParty` <= 0) AND `MusicianId` = ".$musicianId." ) "
      . " OR "
      . " `BillToParty` = ".$musicianId
      . " )";
    $result = mySQL::query($query, $handle);
    while ($row = mySQL::fetch($result)) {
      $rateKey = $row['Broker'].$row['GeographicalScope'];
      $amount = floatval($row['InsuranceAmount']);
      if (!isset($rates[$rateKey])) {
        Util::error(L::t("Invalid broker/geographical-scope combination: %s - %s",
                         array($row['Broker'], $row['GeographicalScope'])));
      }
      $fee += $amount * $rates[$rateKey];
    }
    $fee += $fee * self::TAXES;
    
    if ($ownConnection) {
      mySQL::close($handle);
    }

    return $fee;
  }

}; // class definition.

}

?>
