<?php

/**CamerataDB namespace to prevent name-collisions.
 */
namespace CAFEVDB
{

/** Helper class for displaying projects.
 */
class Projects
{
  const CSS_PREFIX = 'cafevdb-page';
  private $pme;
  private $pme_bare;
  private $execute;

  public function __construct($execute = true)
  {
    $this->execute = $execute;
    $this->pme = false;
    $this->pme_bare = false;

    Config::init();

    //Config::$debug_query = true;
    if (Config::$debug_query) {
      echo "<PRE>\n";
      print_r($_POST);
      print_r($_GET);
      echo "</PRE>\n";
    }    
  }

  public function deactivate() 
  {
    $this->execute = false;
  }

  public function activate() 
  {
    $this->execute = true;
  }

  public function execute()
  {
    if ($this->pme) {
      $this->pme->execute();
    }
  }

  /**Disable some extra stuff (image upload etc.) when displaying the entire table.
   */
  public function changeOperation()
  {
    if (!isset($this->pme)) {
      return false;
    } else {
      return $this->pme->change_operation() || $this->pme->add_operation();
    }
  }

  public function headerText()
  {
    $header =<<<__EOT__
Camerata Projekte<br/>
Bitte auf das Projekt-K&uuml;rzel
klicken, um die Besetzungliste zu editieren. F&uuml;r allgemeine
Eigenschaften bitte die "add", "change" etc. Buttons unten anklicken.
__EOT__;
    return $header;
  }

  public function display()
  {
    global $debug_query;
    //    $debug_query = true;

    //echo '<PRE>';
    /* print_r($_SERVER); */
    //print_r($_POST);
    //echo '</PRE>';

    $handle = mySQL::connect(Config::$pmeopts);

    $Instrumente = Instruments::fetch($handle);

    mySQL::close($handle);

    /*
     * IMPORTANT NOTE: This generated file contains only a subset of huge amount
     * of options that can be used with phpMyEdit. To get information about all
     * features offered by phpMyEdit, check official documentation. It is available
     * online and also for download on phpMyEdit project management page:
     *
     * http://platon.sk/projects/main_page.php?project_id=5
     *
     * This file was generated by:
     *
     *                    phpMyEdit version: 5.7.1
     *       phpMyEdit.class.php core class: 1.204
     *            phpMyEditSetup.php script: 1.50
     *              generating setup script: 1.50
     */

    // Inherit a bunch of default options
    $opts = Config::$pmeopts;

    $opts['cgi']['persist'] = array(
      'Template' => 'projects',
      'app' => Util::cgiValue('app'),
      'headervisibility' => Util::cgiValue('headervisibility','expanded'));

    $opts['tb'] = 'Projekte';

    // Name of field which is the unique key
    $opts['key'] = 'Id';

    // Type of key field (int/real/string/date etc.)
    $opts['key_type'] = 'int';

    // Sorting field(s)
    $opts['sort_field'] = array('Jahr', 'Id');

    // Number of records to display on the screen
    // Value of -1 lists all records in a table
    $opts['inc'] = -1;

    // Options you wish to give the users
    // A - add,  C - change, P - copy, V - view, D - delete,
    // F - filter, I - initial sort suppressed
    $opts['options'] = 'ACPVDF';

    // Number of lines to display on multiple selection filters
    $opts['multiple'] = '6';

    // Navigation style: B - buttons (default), T - text links, G - graphic links
    // Buttons position: U - up, D - down (default)
    //$opts['navigation'] = 'DB';

    // Display special page elements
    $opts['display'] = array(
                             'form'  => true,
                             'query' => true,
                             'sort'  => true,
                             'time'  => true,
                             'tabs'  => true
                             );

    /* Get the user's default language and use it if possible or you can
       specify particular one you want to use. Refer to official documentation
       for list of available languages. */
    //$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE']; // . '-UTF8';

    /* Table-level filter capability. If set, it is included in the WHERE clause
       of any generated SELECT statement in SQL query. This gives you ability to
       work only with subset of data from table.

       $opts['filters'] = "column1 like '%11%' AND column2<17";
       $opts['filters'] = "section_id = 9";
       $opts['filters'] = "PMEtable0.sessions_count > 200";
    */

    /* Field definitions
   
       Fields will be displayed left to right on the screen in the order in which they
       appear in generated list. Here are some most used field options documented.

       ['name'] is the title used for column headings, etc.;
       ['maxlen'] maximum length to display add/edit/search input boxes
       ['trimlen'] maximum length of string content to display in row listing
       ['width'] is an optional display width specification for the column
       e.g.  ['width'] = '100px';
       ['mask'] a string that is used by sprintf() to format field output
       ['sort'] true or false; means the users may sort the display on this column
       ['strip_tags'] true or false; whether to strip tags from content
       ['nowrap'] true or false; whether this field should get a NOWRAP
       ['select'] T - text, N - numeric, D - drop-down, M - multiple selection
       ['options'] optional parameter to control whether a field is displayed
       L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
       Another flags are:
       R - indicates that a field is read only
       W - indicates that a field is a password field
       H - indicates that a field is to be hidden and marked as hidden
       ['URL'] is used to make a field 'clickable' in the display
       e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
       ['URLtarget']  HTML target link specification (for example: _blank)
       ['textarea']['rows'] and/or ['textarea']['cols']
       specifies a textarea is to be used to give multi-line input
       e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
       ['values'] restricts user input to the specified constants,
       e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
       ['values']['table'] and ['values']['column'] restricts user input
       to the values found in the specified column of another table
       ['values']['description'] = 'desc_column'
       The optional ['values']['description'] field allows the value(s) displayed
       to the user to be different to those in the ['values']['column'] field.
       This is useful for giving more meaning to column values. Multiple
       descriptions fields are also possible. Check documentation for this.
    */

    $idIdx = 0;
    $opts['fdd']['Id'] = array(
                               'name'     => 'Id',
                               'select'   => 'T',
                               'options'  => 'AVCPDR', // auto increment
                               'maxlen'   => 11,
                               'default'  => '0',
                               'sort'     => true
                               );

    $opts['fdd']['Jahr'] = array(
                               'name'     => 'Jahr',
                               'select'   => 'N',
                               //'options'  => 'LAVCPDF'
                               'maxlen'   => 11,
                               'default'  => '0',
                               'sort'     => true
                               );

    $nameIdx = count($opts['fdd']);
    $opts['fdd']['Name'] = array(
        'name'     => 'Projekt-Name',
        /* 'php|VLF'      => array('type' => 'function', */
        /*                     'function' => 'CAFEVDB\Projects::projectButton', */
        /*                         'parameters' => array('keyIdx' => $idIdx, */
        /*                                               'template' => 'brief-instrumentation')), */
        'php|VLF'  => array('type' => 'function',
                            'function' => 'CAFEVDB\Projects::projectActionsPME',
                            'parameters' => array("idIndex" => $idIdx)),
        'select'   => 'D',
        'maxlen'   => 64,
        'css'      => array('postfix' => 'projectname'),
        'sort'     => true,
        );

    $opts['fdd']['Actions'] = array(
        'name'     => L::t('Actions'),
        'sql'      => 'Name',
        'php|C'    => array('type' => 'function',
                            'function' => 'CAFEVDB\Projects::projectActionsPME',
                            'parameters' => array("idIndex" => $idIdx,
                                                  "placeHolder" => L::t("Actions"))),
        'select'   => 'T',
        'options'  => 'LVCPDR',
        'maxlen'   => 11,
        'default'  => '0',
        'sort'     => false
      );

    $opts['fdd']['Programm'] = array(
                                     'name'     => 'Programm',
                                     'select'   => 'T',
                                     'maxlen'   => 65535,
                                     'textarea' => array('css' => Config::$opts['editor'],
                                                         'rows' => 5,
                                                         'cols' => 50),
                                     'sort'     => true,
                                     'escape' => false
                                     );

    if (false) {
    $opts['fdd']['Events'] = array(
        'name'     => L::t('Events'),
        'sql'      => 'Id',
        'php'      => array('type' => 'function',
                            'function' => 'CAFEVDB\Projects::eventButtonPME',
                            'parameters' => $nameIdx),
        'select'   => 'T',
        'options'  => 'LVCPDR',
        'maxlen'   => 11,
        'default'  => '0',
        'sort'     => false
      );
    }
    
    $opts['fdd']['Besetzung'] = array('name'     => 'Besetzung',
                                      'options'  => 'AVCPD',
                                      'nowrap'   => false,
                                      'select'   => 'C',
                                      'maxlen'   => 136,
                                      'sort'     => true);
    $opts['fdd']['Besetzung']['values'] = $Instrumente;

    $opts['fdd']['Bemerkungen'] = array(
                                        'name'     => 'Bemerkungen',
                                        'select'   => 'T',
                                        'maxlen'   => 65535,
                                        'css'      => array('postfix' => 'projectremarks'),
                                        'textarea' => array('css' => Config::$opts['editor'],
                                                            'rows' => 5,
                                                            'cols' => 50),
                                        'sort'     => true,
                                        'escape'   => false,
                                        'default'  => 'Kosten, Teilnahmebedingungen etc.'
                                        );

    $opts['fdd']['ExtraFelder'] = array('name'     => 'Extra Felder für Teilnehmer',
                                        'options'  => 'FLAVCPD',
                                        'select'   => 'T',
                                        'maxlen'   => 1024,
                                        'css'      => array('postfix' => 'projectextra'),
                                        'textarea' => array('css' => '',
                                                            'rows' => 1,
                                                            'cols' => 128),
                                        'sort'     => false,
                                        'escape' => false,
                                        'help' => false,
                                        'tooltip' => 'Komma-separierte Liste von Extra-Feldern, z.B.:

  DZ:1,Beitrag:2

oder

  DZ,Beitrag

Die Zahl nach dem Doppelpunkt (und der Doppelpunkt) ist optional,
falls vorhanden, gibt das die Zuordnung zu den Spalten in der
"Besetzungen"-Tabelle in der Datenbank. Dort heißen die Felder einfach
"ExtraFeld01" etc. Die Reihenfolge bei Anzeige der Tabelle entspricht
der angegebenen Reihenfolge. Falls man die ändert, sollte man die Zuordnung
zur Extra-Spalte in der Datenbank angeben, z.B. so:

  Beitrag:2,DZ:1

Dann wird die Reihenfolge bei der Anzeige der Tabelle geändert, aber die
Zuordnung zu den Informationen in der Datenbank bleibt erhalten.');

    $opts['triggers']['update']['after'] = Config::$triggers.'projects.TUA.inc.php';
    $opts['triggers']['insert']['after'] = Config::$triggers.'projects.TIA.inc.php';

    // Maybe we want to keep the view.
    // $opts['triggers']['delete']['after']  = 'Projekte.TDA.inc.php';

    $opts['execute'] = $this->execute;
    $this->pme = new \phpMyEdit($opts);
  }

  /**Generate an associative array of extra-fields. The key is the
   * field-name, the value the number of the extra-field in the
   * Besetzungen-table. We fetch and parse the "ExtraFelder"-field from
   * the "Projekte"-table. The following rules apply:
   *
   * - "ExtraFelder" contains a comma-seprarated field list of the form
   *   FIELD1[:NR1] ,     FIELD2[:NR2] etc.
   *
   * - the explicit association in square brackets is optional, if
   *   omitted than NR is the position of the token in the "ExtraFields"
   *   value. Of course, the square-brackets must not be present, they
   *   have the meaning: "hey, this is optional".
   *
   * Note: field names must be unique.
   */
  public static function extraFields($projectId, $handle = false)
  {
    Util::debugMsg(">>>>ProjektExtraFelder: Id = $projectId");

    $query = 'SELECT `ExtraFelder` FROM `Projekte` WHERE `Id` = '.$projectId;
    $result = mySQL::query($query, $handle);
    
    // Get the single line
    $line = mySQL::fetch($result) or Util::error("Couldn't fetch the result for '".$query."'");
    
    if (Util::debugMode()) {
      print_r($line);
    }
    
    if ($line['ExtraFelder'] == '') {
      return array();
    } else {
      Util::debugMsg("Extras: ".$line['ExtraFelder']);
    }
  
    // Build an array of name - size pairs
    $tmpfields = explode(',',$line['ExtraFelder']);
    if (Util::debugMode()) {
      print_r($tmpfields);
    }
    $fields = array();
    $fieldno = 1; // This time we start at ONE _NOT_ ZERO
    foreach ($tmpfields as $value) {
      $value = trim($value);
      $value = explode(':',$value);
      $fields[] = array('name' => $value[0],
                        'pos' => isset($value[1]) ? $value[1] : $fieldno);
      ++$fieldno;
    }

    Util::debugMsg("<<<<ProjektExtraFelder");

    return $fields;
  }

  public static function projectButton($projectName, $opts, $modify, $k, $fds, $fdd, $row)
  {
    $projectId = $row["qf".$opts['keyIdx']];
    $template  = $opts['template'];
    $bvalue    = $projectName;
    // Code the value in the name attribute (for java-script)
    $bname     = ""
."ProjectId=$projectId&"
."Project=$projectName&"
."Template=$template";
    $title     = Config::toolTips('projectinstrumentation-button');
    return <<<__EOT__
<span class="instrumentation-button">
<input type="button" class="instrumentation" title="$title" name="$bname" value="$bvalue" />
</span>
__EOT__;
  }

  public static function projectActionsPME($projectName, $opts, $modify, $k, $fds, $fdd, $row)
  {
    $projectId   = $row["qf".$opts["idIndex"]];
    $placeHolder = isset($opts['placeHolder']) ? isset($opts['placeHolder']) : false;
    return self::projectActions($projectId, $projectName, $placeHolder);
  }

  public static function projectActions($projectId, $projectName, $placeHolder = false)
  {
    $projectPaths = self::maybeCreateProjectFolder($projectId, $projectName);

    if ($placeHolder === false) {
      $placeHolder = $projectName;
    }

    // Code the value in the name attribute (for java-script)
    $params = ""
      ."ProjectId=$projectId"
      ."&Project=$projectName";
    $control = '
<span class="project-actions-block">
  <select data-placeholder="'.$placeHolder.'"
          class="project-actions"
          title="'.Config::toolTips('project-actions').'"
          name="'.$params.'">
    <option value=""></option>
    <option title="'.Config::toolTips('project-action-events').'" value="events">
      '.L::t('Events').'
    </option>
    <option title="'.Config::toolTips('project-action-brief-instrumentation').'" value="brief-instrumentation">
      '.L::t('Brief Instrumentation').'
    </option>
    <option title="'.Config::toolTips('project-action-detailed-instrumentation').'" value="detailed-instrumentation">
      '.L::t('Detailed Instrumentation').'
    </option>
    <option title="'.Config::toolTips('project-action-instrumentation-numbers').'" value="project-instruments">
      '.L::t('Instrumentation Numbers').'
    </option>
    <option title="'.Config::toolTips('project-action-files').'"
            value="project-files?'.$projectPaths['project'].'">
      '.L::t('Project Files').'
    </option>
    <option title="'.Config::toolTips('project-action-financial-balance').'"
              value="profit-and-loss?'.$projectPaths['balance'].'">
      '.L::t('Profit and Loss Account').'
    </option>
  </select>
</span>';
    return $control;
  }

  /**Check for the existence of the project folder
   */
  public static function maybeCreateProjectFolder($projectId, $projectName = false, $only = false)
  {
    $project = self::fetchProject($projectId);
    if (!$projectName) {
      $projectName = $project['Name'];
    } else if ($projectName != $project['Name']) {
      return false;
    }
    
    $sharedFolder   = Config::getSetting('sharedfolder','');
    $projectsFolder = Config::getSetting('projectsfolder','');
    $balanceFolder  = Config::getSetting('projectsbalancefolder','');

    $fileView = \OC\Files\Filesystem::getView();

    $paths = array('project' => '/Shared/'.$sharedFolder.'/'.$projectsFolder,
                   'balance' => '/Shared/'.$sharedFolder.'/'.$balanceFolder.'/'.$projectsFolder);
    $returnPaths = array();
    foreach($paths as $key => $path) {
      if ($only && $key != $only) {
        continue;
      }
      if (!$fileView->is_dir($path)) {
        $fileView->mkdir($path);
      }
      $path .= "/".$project['Jahr'];
      if (!$fileView->is_dir($path)) {
        $fileView->mkdir($path);
      }
      $path .= "/".$project['Name'];
      if (!$fileView->is_dir($path)) {
        $fileView->mkdir($path);
      }
      $returnPaths[$key] = $path;
    }
    return $returnPaths;
  }

  public static function renameProjectFolder($newProject, $oldProject)
  {
    $sharedFolder = Config::getSetting('sharedfolder','');
    $projectsFolder = Config::getSetting('projectsfolder','');
    $balanceFolder = Config::getSetting('projectsbalancefolder','');

    $prefixPath = array(
      'project' => '/Shared/'.$sharedFolder.'/'.$projectsFolder.'/',
      'balance' => '/Shared/'.$sharedFolder.'/'.$balanceFolder.'/'.$projectsFolder."/",
      );

    $fileView = \OC\Files\Filesystem::getView();

    $returnPaths = array();
    foreach($refixPath as $key => $prefix) {
                        
      $oldPath = $prefix.$oldProject['Jahr']."/".$oldProject['Name'];
      $newPrefixPath = $prefix.$newProject['Jahr'];
      
      $newPath = $newPrefixPath.'/'.$newProject['Name'];
      
      if ($fileView->is_dir($oldPath)) {
        // If the year has changed it may be necessary to create a new
        // directory.
        if (!$fileView->is_dir($newPrefixPath)) {
          if (!$fileView->mkdir($newPrefixPath)) {
            return false;
          }
        }
        if (!$fileView->rename($oldPath, $newPath)) {
          return false;
        }
        $returnPaths[$key] = $newPath;
      } else {
        // Otherwise there is nothing to move; we simply create the new directory.
        $returnPaths = array_merge($returnPaths,
                                   self::maybeCreateProjectFolder($projectId, $projectName, $only = $key));
      }
    }

    return $returnPaths;
  }

  public static function eventButtonPME($projectId, $opts, $modify, $k, $fds, $fdd, $row)
  {
    $projectName = $row["qf$opts"];
    return self::eventButton($projectId, $projectName);
  }

  public static function eventButton($projectId, $projectName, $value = false, $eventSelect = array())
  {
    if ($value === false) {
      $value = L::t('Events');
    }
    $bvalue      = $value;
    // Code the value in the name attribute (for java-script)
    $bname       = "ProjectId=$projectId&ProjectName=".$projectName;
    foreach ($eventSelect as $event) {
      $bname .= '&EventSelect[]='.$event;
    }
    $bname       = htmlspecialchars($bname);
    $title       = Config::toolTips('projectevents-button');
    $image = \OCP\Util::imagePath('calendar', 'calendar.svg');
    $button =<<<__EOT__
<span class="events">
  <button type="button" class="events" title="$title" name="$bname" value="$bvalue">
    <img class="svg events" src="$image" alt="$bvalue" />
  </button>
</span>
__EOT__;
    return $button;
  }

  /**Fetch the list of projects from the data base as a short id=>name
   * field.
   */
  public static function fetchProjects($handle = false, $year = false)
  {
    $projects = array();

    $ownConnection = $handle === false;
    if ($ownConnection) {
      Config::init();
      $handle = mySQL::connect(Config::$pmeopts);
    }
      
    $query = "SELECT `Id`,`Name`".($year === true ? ",`Jahr`" : "");
    $query .= " FROM `Projekte` WHERE 1 ORDER BY ";
    if ($year === true) {
      $query .= "`Jahr` ASC, `Name` ASC";
    } else {
      $query .= "`Name` ASC";
    }
    $result = mySQL::query($query, $handle);
    if ($year === false) {
      while ($line = mySQL::fetch($result)) {
        $projects[$line['Id']] = $line['Name'];
      }
    } else {
      while ($line = mySQL::fetch($result)) {
        $projects[$line['Id']] = array('Name' => $line['Name'], 'Jahr' => $line['Jahr']);
      }      
    }

    if ($ownConnection) {
      mySQL::close($handle);
    }

    return $projects;
  }

  /**Fetch the list of projects from the data base as a short id=>name
   * field.
   */
  public static function fetchProject($projectId, $handle = false)
  {
    $projects = array();

    $ownConnection = $handle === false;
    if ($ownConnection) {
      Config::init();
      $handle = mySQL::connect(Config::$pmeopts);
    }
      
    $query = "SELECT * FROM `Projekte` WHERE `Id` = $projectId";
    $result = mySQL::query($query, $handle);
    if ($result !== false && mysql_num_rows($result) == 1) {
      $row = mySQL::fetch($result);
      return $row;
    } else {
      return false;
    }
  }

  /** Fetch the project-name name corresponding to $projectId.
   */
  public static function fetchName($projectId, $handle = false)
  {
    $ownConnection = $handle === false;
    if ($ownConnection) {
      Config::init();
      $handle = mySQL::connect(Config::$pmeopts);
    }

    $query = 'SELECT `Name` FROM `Projekte` WHERE `Id` = '.$projectId;
    $result = mySQL::query($query, $handle);

    // Get the single line
    $line = mySQL::fetch($result) or Util::error("Couldn't fetch the result for '".$query."'");

    if ($ownConnection) {
      mySQL::close($handle);
    }

    return $line['Name'];
  }

  /**Make sure the "Besetzungen"-table has enough extra fields. All
   * extra-fields are text-fields.
   *
   */
  public static function createExtraFields($projectId, $handle = false)
  {
    Util::debugMsg(">>>> ProjektCreateExtraFelder");

    // Fetch the extra-fields.
    $extra = self::extraFields($projectId, $handle);
    if (Util::debugMode()) {
      print_r($extra);
    }

    /* Then walk the table and simply execute one "ALTER TABLE"
     * statement for each field, ignoring the result, but we check later
     * for a possible error.
     */

    foreach ($extra as $field) {
      // forget about $name, not an issue here.  

      $query = sprintf(
                       'ALTER TABLE `Besetzungen`
   ADD `ExtraFeld%02d` TEXT
   CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
                       $field['pos']);
      $result = @mySQL::query($query, $handle, false, true); // ignore the result, be silent
    }

    // Now make sure we have it ...
    $query = "SHOW COLUMNS FROM `Besetzungen` LIKE 'ExtraFeld%'";
    $result = mySQL::query($query, $handle);

    // See what we got ...
    $fields = array();
    while ($row = mySQL::fetch($result)) {
      if (Util::debugMode()) {
        print_r($row);
      }
      $fields[] = $row['Field'];
    }
    if (Util::debugMode()) {
      print_r($fields);
    }

    foreach ($extra as $field) {
      $name = sprintf('ExtraFeld%02d', $field['pos']);
      Util::debugMsg("Check ".$name);
      if (array_search($name, $fields) === false) {
        Util::error('Extra-Field '.$field['pos'].' not Found in Table Besetzungen');
      }
    }

    Util::debugMsg("<<<< ProjektCreateExtraFelder");

    return true; // if someone cares
  }

  // Create a sensibly sorted view, fit for being exported via
  // phpmyadmin. Take all extra-fields into account, add them at end.
  public static function createView($projectId, $project = false, $handle = false)
  {
    Util::debugMsg(">>>> ProjektCreateView");

    if (! $project) {
      // Get the name
      $project = self::fetchName($projectId, $handle);
    }

    // Make sure all extra-fields exist
    self::createExtraFields($projectId, $handle);

    // Fetch the extra-fields
    $extra = self::extraFields($projectId, $handle);

    // "Extra"'s will be added at end. Generate a suitable "SELECT"
    // string for that. Ordering of field in the table is just the
    // ordering in the "$extra" table.
    $extraquery = '';
    Util::debugMsg(">>>> ProjektCreateView before extra");
    foreach ($extra as $field) {
      $extraquery .= sprintf(', `Besetzungen`.`ExtraFeld%02d` AS `'.$field['name'].'`', $field['pos']);
    }
    Util::debugMsg(">>>> ProjektCreateView after extra");

    // Now do all the stuff, do not forget the proper sorting to satisfy
    // all dummies on earth
    $sqlquery = 'CREATE OR REPLACE VIEW `'.$project.'View` AS
 SELECT
   `Musiker`.`Id` AS `MusikerId`,
   `Besetzungen`.`Instrument`,`Besetzungen`.`Reihung`,
   `Besetzungen`.`Stimmführer`,`Instrumente`.`Familie`,`Instrumente`.`Sortierung`,
    `Name`,`Vorname`,
   `Email`,`Telefon`,`Telefon2`,
   `Strasse`,`Postleitzahl`,`Stadt`,`Land`,
   `Besetzungen`.`Unkostenbeitrag`,
   `Besetzungen`.`Bemerkungen` AS `ProjektBemerkungen`'.
      ($extraquery != '' ? $extraquery : '').','
      .' `Instrumente` AS `AlleInstrumente`,`Sprachpräferenz`,`Geburtstag`,
   `Musiker`.`MemberStatus`,`Musiker`.`Remarks`,`MemberPortraits`.`PhotoData`,`Aktualisiert`';

    // Now do the join
    $sqlquery .= ' FROM `Musiker`
   JOIN `Besetzungen`
     ON `Musiker`.`Id` = MusikerId AND '.$projectId.'= `ProjektId`
   LEFT JOIN `Instrumente`
     ON `Besetzungen`.`Instrument` = `Instrumente`.`Instrument`
   LEFT JOIN `MemberPortraits`
     ON `MemberPortraits`.`MemberId` = `Musiker`.`Id`';

    // And finally force a sensible default sorting:
    // 1: sort on the natural orchestral ordering defined in Instrumente
    // 2: sort (reverse) on the Stimmfuehrer attribute
    // 3: sort on the sur-name
    // 4: sort on the pre-name
    $sqlquery .= 'ORDER BY `Instrumente`.`Sortierung` ASC,
 `Besetzungen`.`Reihung` ASC,
 `Besetzungen`.`Stimmführer` DESC,
 `Musiker`.`Name` ASC,
 `Musiker`.`Vorname` ASC';
 
    mySQL::query($sqlquery, $handle);

    return true;
  }

}; // class Projects

}

/*
 * Local Variables: ***
 * c-basic-offset: 2 ***
 * End: ***
 */

?>
