<?php

/* Tool-tips for the phpmyadmin-forms.
 *
 */

$opts['tooltips'] =
  array('pme-sort' => '  Klick mich, um das Sortieren
nach diesem Feld ein-
oder auszuschalten!',

        'pme-sort-rvrt' => '  Klick mich, um die Sortierreihenfolge umzukehren!',

        'pme-misc' => '  Klick mich, um eine Em@il an die ausgewählten
Musiker zu versenden. Auf der folgenden Seite kann
die Auswahl dann noch modifiziert werden.
"angezeigt" bedeutet: nicht
nur die auf der aktuellen
Anzeige-Seite, sondern
alle, die den Such-Kriterien
entsprechen.',

        'pme-misc+' => '  Klick mich, um alle gerade
angezeigten Musiker zu der
Em@il-Auswahl hinzuzufügen.
"angezeigt" bedeutet: nicht
nur die auf der aktuellen
Anzeige-Seite, sondern
alle, die den Such-Kriterien
entsprechen.',

        'pme-misc-' => '  Klick mich, um alle gerade
angezeigten Musiker von der
Em@il-Auswahl zu entfernen',

        'pme-clear' => array('sfn' => '  Klick mich, um die
Sortierreihenfolge auf die
Voreinstellung zurückzusetzen.',
                             'sw' => '  Klick mich, um den
aktuellen Filter zu löschen.'),

        'pme-hide' => array('sw' => '  Klick mich, um die
Suchkriterien zu verstecken.'),

        'pme-search' => array('sw' => '  Klick mich, um die
Suchkriterien anzuzeigen.'),

        'pme-query' => '  Klick mich, um den
aktuellen Suchkriterien anzuwenden. Suchkriterien
können in den Feldern eingegeben werden.
Als Platzhalter verwendet man "%".',

        'pme-filtertext' => '  Feld für Suchkriterien.
Als Platzhalter verwendet man "%", z.B. "%Ste%an"
beim Vornamen. Bei numerischen Feldern ist links
eine Auswahlbox mit Vergleichsoperationen.',

        'pme-misc-check' => '  Click mich, um mich
Deinem Massenmail-Vorhaben
hinzuzufügen. Schäme Dich!',

        'pme-view-navigation' => array('operation' => 'Einzelnen Datensatz anzeigen'),
        'pme-change-navigation' => array('operation' => 'Einzelnen Datensatz anzeigen,
zeigt ein neues Formular mit
detaillierten Eingabefeldern
und Abbruchmöglichkeit.'),
        'pme-copy-navigation' => array('operation' => 'Einzelnen Datensatz kopieren,
zeigt ein neues Formular mit
detaillierten Eingabefeldern
und Abbruchmöglichkeit.'),
        'pme-delete-navigation' => array('operation' =>'Einzelnen Datensatz löschen,
zeigt den aktuellen Datensatz zunächst an.
Gelöscht wird der erst nach einer
weiteren Bestätigung. Trotzdem:
VORSICHT!.'),
        'pme-misc-check' => '  Adressaten in potentielle
Massenmail Adressliste aufnehmen.
Kann man (glücjlicherweise) 
vor dem Senden der Em@il noch
korrigieren. Trotzdem:
Think thrice about it.',
        

        'nothing' => 'nothing' // comma stop
        );

?>