<?php
/**
 * Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine <himself@claus-justus-heine.de>
 * @copyright 2011-2016, 2020, 2021, 2023, 2025, 2026 Claus-Justus Heine
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB;

use OCA\CAFEVDB\Common\Util;
use OCA\CAFEVDB\Controller\EmailFormController;
use OCA\CAFEVDB\Wrapped\Carbon\CarbonImmutable as DateTime;

if (empty($_[EmailFormController::DRAFT_EMAILS])) {
  \OCP\Server::get(\Psr\Log\LoggerInterface::class)->info('DRAFTS LIST EMPTY', [ 'app' => 'cafevdb', 'exception' => new \Exception('blah') ]);
}

$locale = $l->getLocaleCode();

foreach ($_[EmailFormController::DRAFT_EMAILS] as $draft) {
  $createdAt = ($draft['created']??(new DateTime)->setTimestamp(0))
    ->locale($locale)
    ->setTimezone($dateTimeZone);
  $updatedAt = ($draft['updated']??(new DateTime)->setTimestamp(0))
    ->locale($locale)
    ->setTimezone($dateTimeZone);
  $title = $l->t(
    "Subject: %s<br/>"
    . "Created by %s on %s<br/>"
    . "Updated by %s on %s",
    [ $draft['name'],
      $draft['createdBy']??$l->t('Anonymous'),
      $createdAt->isoFormat('lll'),
      $draft['updatedBy']??$l->t('Anonymous'),
      $updatedAt->isoFormat('lll'),
    ]);
  $name = $updatedAt->isoFormat('L LT').': '.$draft['name'];
  ?>
  <option value="<?php p($draft['id']); ?>"
          class="tooltip-auto"
          title="<?= Util::htmlEscape($title) ?>"
          data-auto-generated="<?= (int)$draft['autoGenerated'] ?>"
  >
    <?php p($name); ?>
  </option>
<?php } ?>
