<?php
/**
 * Orchestra member, musician and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine
 * @copyright 2011-2016, 2020, 2021 Claus-Justus Heine <himself@claus-justus-heine.de>
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB;

use OCA\CAFEVDB\Common\Util;
use OCA\CAFEVDB\Wrapped\Carbon\CarbonImmutable as DateTime;

$locale = $l->getLocaleCode();

?>

<optgroup label="<?php p($l->t('Drafts')); ?>">

<?php
foreach ($storedEmails['drafts'] as $draft) {
  $createdAt = ($draft['created']??(new DateTime)->setTimestamp(0))
    ->locale($locale)
    ->setTimezone($dateTimeZone);
  $updatedAt = ($draft['updated']??(new DateTime)->setTimestamp(0))
    ->locale($locale)
    ->setTimezone($dateTimeZone);
  $title = $l->t("Subject: %s<br/>"
                ."Created by %s on %s<br/>"
                ."Updated by %s on %s",
                 [ $draft['name'],
                   $draft['createdBy']??$l->t('Anonymous'),
                   $createdAt->isoFormat('lll'),
                   $draft['updatedBy']??$l->t('Anonymous'),
                               $updatedAt->isoFormat('lll'), ]);
  $name = $updatedAt->isoFormat('L LT').': '.$draft['name'];
?>
  <option value="__draft-<?php p($draft['id']); ?>"
          title="<?php echo Util::htmlEscape($title); ?>"
          data-auto-generated="<?php p($draft['autoGenerated']); ?>"
  >
    <?php p($name); ?>
  </option>
<?php } ?>
</optgroup>
<optgroup label="<?php p($l->t('Templates')); ?>">
<?php
foreach ($storedEmails['templates'] as $template) {
  $createdAt = ($template['created']??(new DateTime)->setTimestamp(0))->locale($locale);
  $updatedAt = ($template['updated']??(new DateTime)->setTimestamp(0))->locale($locale);
  $title = $l->t("Name: %s<br/>"
                . "Created by %s on %s<br/>"
                . "Updated by %s on %s",
                 [ $template['name'],
                   $template['createdBy']??$l->t('Anonymous'),
                   $createdAt->isoFormat('lll'),
                   $template['updatedBy']??$l->t('Anonymous'),
                   $updatedAt->isoFormat('lll'), ]);
?>
  <option value="<?php p($template['id']); ?>"
          title="<?php echo Util::htmlEscape($title); ?>"
  >
    <?php p($template['name']); ?>
  </option>
<?php } ?>
</optgroup>
