CamerataDB: CloudUserConnectorService Class Reference
CloudUserConnectorService Class Reference
Manage database-views and grants in order to selectively provide only the neccessary information to the ambient cloud system.
Public Member Functions
__construct (string $appName, IAppContainer $appContainer, ILogger $logger, IL10N $l10n, IConfig $cloudConfig, EncryptionService $encryptionService, IAppManager $appManager,)
checkRequirements (?string $dataBaseName)
Check the requirements for this affair, in particular whether the user_sql backend is enabled, and return an error with status and hints.
projectGroupId (int $projectId)
Return the group-id for the given numeric project-id.
updateUserSqlViews (?string $dataBaseName)
Update the views interacting with the Nextcloud user_sql backend and update their grants.
removeUserSqlViews (?string $dataBaseName)
Delete the user-sql views.
writeUserSqlConfig (?string $dataBaseName=null, bool $delete=false)
For the moment this just fills in our own app-config.
synchronizeCloud ()
In particular flush potential data-caches after changing data of the orchestra app.
haveCloudUserBackendConfig ()
updateMusicianPersonalizedViews (?string $dataBaseName)
Update the personalized one-row views which give individual orchestra members access to just their own data.
removeMusicianPersonalizedViews (?string $dataBaseName)
Delete the personalized one-row views which give individual orchestra members access to just their own data.
Data Fields
const REQUIREMENTS_OK = true
const REQUIREMENTS_MISSING = false
const CLOUD_USER_BACKEND = 'user_sql'
const CLOUD_USER_GROUP_ID = self::CLOUD_USER_BACKEND
const VIEW_POSTFIX = 'View'
const USER_SQL_PREFIX = 'Nextcloud'
const PERSONALIZED_PREFIX = 'Personalized'
const GROUP_ID_SEPARATOR = '_'
const GROUP_ID_PREFIX = '%2$s' . self::GROUP_ID_SEPARATOR
const USER_SQL_USER_GROUP_VIEW
const USER_SQL_VIEWS
const MUSICIAN_ID_TABLES
const PARTICIPANT_FIELD_ID_TABLES
const UNRESTRICTED_TABLES
const GRANT_SELECT = 'GRANT SELECT ON %1$s TO %2$s@\'localhost\''
const GRANT_FIELD_UPDATE = 'GRANT UPDATE (%3$s) ON %1$s TO %2$s@\'localhost\''
Private Member Functions
viewName (?string $dataBaseName, string $prefix, string $baseName)
personalizedViewName (?string $dataBaseName, string $baseName)
checkAndGetCloudDbUser ()
generateUserSqlConfig (?string $dataBaseName=null, bool $withDbAuth=true)
Generate a config array for the user_sql app "as of now".
generateMusicianPersonalizedViewsStatements (?string $dataBaseName)
Generate the (My-)SQL statements for defining the personalized single-row musician views.
Private Attributes
$appName
$appContainer
$l
$cloudConfig
$encryptionService
$connection
$appManager
$appDbHost
$appDbUser
$appDbName
Detailed Description
Manage database-views and grants in order to selectively provide only the neccessary information to the ambient cloud system.
Integrates with the cafevdbmembers and the user_sql app.
Definition at line 44 of file CloudUserConnectorService.php.
Constructor & Destructor Documentation
__construct()
__construct (string $appName, IAppContainer $appContainer, ILogger $logger, IL10N $l10n, IConfig $cloudConfig, EncryptionService $encryptionService, IAppManager $appManager)
Definition at line 210 of file CloudUserConnectorService.php.
Member Function Documentation
checkAndGetCloudDbUser()
checkAndGetCloudDbUser () private
Returns
string
Exceptions
Exceptions
\DatabaseCloudConnectorViewException
Definition at line 270 of file CloudUserConnectorService.php.
Referenced by CloudUserConnectorService\updateMusicianPersonalizedViews(), and CloudUserConnectorService\updateUserSqlViews().
checkRequirements()
checkRequirements (?string $dataBaseName)
Check the requirements for this affair, in particular whether the user_sql backend is enabled, and return an error with status and hints.
Parameters
null | string $dataBaseName
Returns
array
Definition at line 292 of file CloudUserConnectorService.php.
generateMusicianPersonalizedViewsStatements()
generateMusicianPersonalizedViewsStatements (?string $dataBaseName) private
Generate the (My-)SQL statements for defining the personalized single-row musician views.
Parameters
null | string $dataBaseName
Returns
array<string, string>
[
  VIEWNAME => SQL_STATEMENT
]
Definition at line 668 of file CloudUserConnectorService.php.
References CloudUserConnectorService\personalizedViewName().
Referenced by CloudUserConnectorService\removeMusicianPersonalizedViews(), and CloudUserConnectorService\updateMusicianPersonalizedViews().
generateUserSqlConfig()
generateUserSqlConfig (?string $dataBaseName = null, bool $withDbAuth = true) private
Generate a config array for the user_sql app "as of now".
Parameters
null | string $dataBaseName
bool $withDbAuth
Returns
array
Bug:
Uses the internal structure of an app which is not under our controle.
Definition at line 422 of file CloudUserConnectorService.php.
References CloudUserConnectorService\viewName().
Referenced by CloudUserConnectorService\writeUserSqlConfig().
haveCloudUserBackendConfig()
haveCloudUserBackendConfig ()
Returns
bool Check for cached cloud user-backend config
Definition at line 646 of file CloudUserConnectorService.php.
personalizedViewName()
personalizedViewName (?string $dataBaseName, string $baseName) private
Parameters
null | string $dataBaseName
string $baseName
Returns
string
Definition at line 260 of file CloudUserConnectorService.php.
References CloudUserConnectorService\viewName().
Referenced by CloudUserConnectorService\generateMusicianPersonalizedViewsStatements().
projectGroupId()
projectGroupId (int $projectId)
Return the group-id for the given numeric project-id.
Note that the display-name is just the project-name.
Parameters
int $projectId
Returns
string
Definition at line 333 of file CloudUserConnectorService.php.
removeMusicianPersonalizedViews()
removeMusicianPersonalizedViews (?string $dataBaseName)
Delete the personalized one-row views which give individual orchestra members access to just their own data.
Parameters
string | null $dataBaseName The name of the database where the views will be created. The cafevdb database user must have GRANT rights on the databse. If null the views are created in the standard databse.
Returns
void
Exceptions
Exceptions
\DatabaseCloudConnectorViewException
Definition at line 857 of file CloudUserConnectorService.php.
References CloudUserConnectorService\generateMusicianPersonalizedViewsStatements().
removeUserSqlViews()
removeUserSqlViews (?string $dataBaseName)
Delete the user-sql views.
Parameters
string | null $dataBaseName The name of the database where the views will be created. The cafevdb database user must have GRANT rights on the databse. If null the views are created in the standard databse.
Returns
void
Definition at line 391 of file CloudUserConnectorService.php.
References CloudUserConnectorService\viewName().
synchronizeCloud()
synchronizeCloud ()
In particular flush potential data-caches after changing data of the orchestra app.
Returns
void
Definition at line 614 of file CloudUserConnectorService.php.
updateMusicianPersonalizedViews()
updateMusicianPersonalizedViews (?string $dataBaseName)
Update the personalized one-row views which give individual orchestra members access to just their own data.
Parameters
string | null $dataBaseName The name of the database where the views will be created. The cafevdb database user must have GRANT rights on the databse. If null the views are created in the standard databse.
Returns
void
Exceptions
Exceptions
\DatabaseCloudConnectorViewException
Definition at line 817 of file CloudUserConnectorService.php.
References CloudUserConnectorService\checkAndGetCloudDbUser(), and CloudUserConnectorService\generateMusicianPersonalizedViewsStatements().
updateUserSqlViews()
updateUserSqlViews (?string $dataBaseName)
Update the views interacting with the Nextcloud user_sql backend and update their grants.
Parameters
string | null $dataBaseName The name of the database where the views will be created. The cafevdb database user must have GRANT rights on the databse. If null the views are created in the standard databse.
Returns
void
Exceptions
Exceptions
\DatabaseCloudConnectorViewException
Definition at line 350 of file CloudUserConnectorService.php.
References CloudUserConnectorService\checkAndGetCloudDbUser(), and CloudUserConnectorService\viewName().
viewName()
viewName (?string $dataBaseName, string $prefix, string $baseName) private
Parameters
null | string $dataBaseName
string $prefix
string $baseName
Returns
string
Definition at line 244 of file CloudUserConnectorService.php.
Referenced by CloudUserConnectorService\generateUserSqlConfig(), CloudUserConnectorService\personalizedViewName(), CloudUserConnectorService\removeUserSqlViews(), and CloudUserConnectorService\updateUserSqlViews().
writeUserSqlConfig()
writeUserSqlConfig (?string $dataBaseName = null, bool $delete = false)
For the moment this just fills in our own app-config.
Idea is to have the admin-settings actually flush this data to the config space, either directly or by using a call to set settings route of the user_sql app.
Parameters
null | string $dataBaseName
bool $delete
Returns
void
Definition at line 500 of file CloudUserConnectorService.php.
References CloudUserConnectorService\generateUserSqlConfig().
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 183 of file CloudUserConnectorService.php.
$appDbHost
string $appDbHost private
Definition at line 201 of file CloudUserConnectorService.php.
$appDbName
string $appDbName private
Definition at line 207 of file CloudUserConnectorService.php.
$appDbUser
string $appDbUser private
Definition at line 204 of file CloudUserConnectorService.php.
$appManager
IAppManager $appManager private
Definition at line 198 of file CloudUserConnectorService.php.
$appName
string $appName private
Definition at line 180 of file CloudUserConnectorService.php.
$cloudConfig
IConfig $cloudConfig private
Definition at line 189 of file CloudUserConnectorService.php.
$connection
Connection $connection private
Definition at line 195 of file CloudUserConnectorService.php.
$encryptionService
EncryptionService $encryptionService private
Definition at line 192 of file CloudUserConnectorService.php.
$l
IL10N $l private
Definition at line 186 of file CloudUserConnectorService.php.
CLOUD_USER_BACKEND
const CLOUD_USER_BACKEND = 'user_sql'
Definition at line 51 of file CloudUserConnectorService.php.
CLOUD_USER_GROUP_ID
const CLOUD_USER_GROUP_ID = self::CLOUD_USER_BACKEND
Definition at line 52 of file CloudUserConnectorService.php.
GRANT_FIELD_UPDATE
const GRANT_FIELD_UPDATE = 'GRANT UPDATE (%3$s) ON %1$s TO %2$s@\'localhost\''
Definition at line 177 of file CloudUserConnectorService.php.
GRANT_SELECT
const GRANT_SELECT = 'GRANT SELECT ON %1$s TO %2$s@\'localhost\''
Definition at line 176 of file CloudUserConnectorService.php.
GROUP_ID_PREFIX
const GROUP_ID_PREFIX = '%2$s' . self::GROUP_ID_SEPARATOR
Definition at line 61 of file CloudUserConnectorService.php.
GROUP_ID_SEPARATOR
const GROUP_ID_SEPARATOR = '_'
Definition at line 59 of file CloudUserConnectorService.php.
MUSICIAN_ID_TABLES
const MUSICIAN_ID_TABLES
Initial value:
= [
    'SepaBankAccounts' => 'musician_id',
    'SepaDebitMandates' => 'musician_id',
    'ProjectParticipants' => 'musician_id',
    'MusicianInstruments' => 'musician_id',
    'ProjectInstruments' => 'musician_id',
    'ProjectPayments' => 'musician_id',
    'CompositePayments' => 'musician_id',
    'MusicianPhoto' => 'owner_id',
    'EncryptedFileOwners' => 'musician_id',
    'MusicianEmailAddresses' => 'musician_id',
  ]
Definition at line 136 of file CloudUserConnectorService.php.
PARTICIPANT_FIELD_ID_TABLES
const PARTICIPANT_FIELD_ID_TABLES
Initial value:
= [
    'ProjectParticipantFields' => [
      'joinField' => 'id',
      'groupBy' => [
        'id',
      ],
    ],
    'ProjectParticipantFieldsDataOptions' => [
      'joinField' => 'field_id',
      'groupBy' => [
        'field_id', 'key',
      ],
    ],
  ]
Definition at line 149 of file CloudUserConnectorService.php.
PERSONALIZED_PREFIX
const PERSONALIZED_PREFIX = 'Personalized'
Definition at line 57 of file CloudUserConnectorService.php.
REQUIREMENTS_MISSING
const REQUIREMENTS_MISSING = false
Definition at line 49 of file CloudUserConnectorService.php.
REQUIREMENTS_OK
const REQUIREMENTS_OK = true
Definition at line 48 of file CloudUserConnectorService.php.
UNRESTRICTED_TABLES
const UNRESTRICTED_TABLES
Initial value:
= [
    'Instruments',
    'InstrumentFamilies',
    'instrument_instrument_family',
    'TableFieldTranslations',
    'GeoContinents',
    'GeoCountries',
    'GeoPostalCodes',
    'GeoPostalCodeTranslations',
    'InsuranceBrokers',
    'InsuranceRates',
  ]
Definition at line 163 of file CloudUserConnectorService.php.
USER_SQL_PREFIX
const USER_SQL_PREFIX = 'Nextcloud'
Definition at line 56 of file CloudUserConnectorService.php.
USER_SQL_USER_GROUP_VIEW
const USER_SQL_USER_GROUP_VIEW
Initial value:
= 'CREATE OR REPLACE
SQL SECURITY DEFINER
VIEW %1$s AS
SELECT m.user_id_slug AS uid,
       CONVERT((CONCAT(_ascii "%2$s' . self::GROUP_ID_SEPARATOR . '", p.id) COLLATE ascii_bin) USING utf8mb4) AS gid
FROM ProjectParticipants pp
LEFT JOIN Musicians m ON m.id = pp.musician_id
LEFT JOIN Projects p ON p.id = pp.project_id
WHERE pp.musician_id in
    (SELECT pp1.musician_id
     FROM ProjectParticipants pp1
     LEFT JOIN Projects p1 ON pp1.project_id = p1.id
     WHERE p1.type = "permanent")'
Definition at line 82 of file CloudUserConnectorService.php.
USER_SQL_VIEWS
const USER_SQL_VIEWS
Initial value:
= [
    'User' => self::USER_SQL_USER_VIEW,
    'Group' => self::USER_SQL_GROUP_VIEW,
    'UserGroup' => self::USER_SQL_USER_GROUP_VIEW,
  ]
Definition at line 130 of file CloudUserConnectorService.php.
VIEW_POSTFIX
const VIEW_POSTFIX = 'View'
Definition at line 54 of file CloudUserConnectorService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/CloudUserConnectorService.php