CamerataDB: UserStorage Class Reference
UserStorage Class Reference
Some tweaks to for the user-folder stuff.
Public Member Functions
__construct (IUserSession $userSession, IAppContainer $appContainer, IRootFolder $rootFolder, ILogger $logger, IL10N $l10n)
{}
setUser (?IUser $user)
user ()
userId ()
getUserPath (Node $node)
Return the path relative to user-folder.
get (?string $path, ?string $type=null, bool $useCache=false, bool $throw=false)
getFile (string $path, bool $useCache=false)
getFolder (string $path, bool $useCache=false)
getRoot ()
delete (string $path)
Gracefully try to delete $path.
rename (string $oldPath, string $newPath)
Rename $oldPath to $newPath which are interpreted as paths relative to the user's folder.
copy (string $oldPath, string $newPath)
Rename $oldPath to $newPath which are interpreted as paths relative to the user's folder.
ensureFolder (string $path)
Make sure the given directory exists.
ensureFolderChain (array $chain)
Make sure the all components of the given array exists where each following component is chained to the previous one.
getCacheFolder (string $subDirectory)
putContent (string $path, string $content)
Put file content by path.
getContent (string $path)
Get file content by path.
getDownloadLink ($pathOrNode)
Generate a DAV download-link for the given node or path-name.
getFilesAppLink ($pathOrNode, bool $subDir=false)
Generate a link to the files-app pointing to the parent folder if $pathOrNode is a file, or the node itself if it is a folder.
Static Public Member Functions
static pathCat ($first, ?string $second=null)
static stripParents (string $path, int $depth)
Strip the given number of directories from $path.
Data Fields
const PATH_SEP = Constants::PATH_SEP
const CACHE_DIRECTORY = self::PATH_SEP.'cache'
Protected Attributes
$user
$rootFolder
$userFolder
Private Attributes
$appContainer
$nodeCache = []
Detailed Description
Some tweaks to for the user-folder stuff.
Definition at line 59 of file UserStorage.php.
Constructor & Destructor Documentation
__construct()
__construct (IUserSession $userSession, IAppContainer $appContainer, IRootFolder $rootFolder, ILogger $logger, IL10N $l10n)
{}
Definition at line 82 of file UserStorage.php.
References UserStorage\setUser().
Member Function Documentation
copy()
copy (string $oldPath, string $newPath)
Rename $oldPath to $newPath which are interpreted as paths relative to the user's folder.
Parameters
string $oldPath The source path.
string $newPath The destination path.
Returns
void
Exceptions
Exception If something goes wrong.
Definition at line 497 of file UserStorage.php.
delete()
delete (string $path)
Gracefully try to delete $path.
If $path does not exist, a notice is written to the log but otherwise the error is ignored.
Parameters
string $path The path to the file to delete.
Returns
void
Definition at line 389 of file UserStorage.php.
ensureFolder()
ensureFolder (string $path)
Make sure the given directory exists.
If the given path existis and is not a directory, it will be moved out of the way or deleted.
Parameters
string $path The path the check and possibly create. The path is relative to the user storage base directory and may contain multiple components.
Returns
Folder The folder object pointing to the given path.
Exceptions
FileNotFoundException If something goes wrong.
Definition at line 522 of file UserStorage.php.
Referenced by UserStorage\ensureFolderChain(), UserStorage\getCacheFolder(), and UserStorage\putContent().
ensureFolderChain()
ensureFolderChain (array $chain)
Make sure the all components of the given array exists where each following component is chained to the previous one.
So the final path to construct is
'/'.implode('/', $chain)
Parameters
array $chain Path components.
Returns
Folder The folder object pointing to the resulting path.
Exceptions
Exceptionn If something goes wrong.
Definition at line 553 of file UserStorage.php.
References UserStorage\ensureFolder().
get()
get (?string $path, ?string $type = null, bool $useCache = false, bool $throw = false)
Parameters
string | null $path Path to lookup.
null | string $type Only consider nodes of this type, either FileInfo::TYPE_FOLDER or FileInfo::TYPE_FILE.
bool $useCache Use any previously cached value.
bool $throw Throw an exception instead of returning null if the file is not found.
Returns
null|Node The user-folder or the given sub-folder
Definition at line 158 of file UserStorage.php.
getCacheFolder()
getCacheFolder (string $subDirectory)
Parameters
string $subDirectory Folder name inside cache subdirectory.
Returns
\OCP\Files\Folder The requested cache folder
Definition at line 569 of file UserStorage.php.
References UserStorage\ensureFolder().
getContent()
getContent (string $path)
Get file content by path.
Parameters
string $path The file path.
Returns
The file content.
Definition at line 608 of file UserStorage.php.
getDownloadLink()
getDownloadLink ($pathOrNode)
Generate a DAV download-link for the given node or path-name.
The resulting node should look like
https://anaxagoras.home.claus-justus-heine.de/nextcloud-git/remote.php/webdav/camerata/projects/2020/Test2020/participants/claus-justus.heine/DateiUpload-ClausJustusHeine.zip?downloadStartSecret=uwq0q4j24sb
Folders seemingly are still piped through a legacy Ajax call, e.g.
https://anaxagoras.home.claus-justus-heine.de/nextcloud-git/index.php/apps/files/ajax/download.php?dir=%2Fcamerata%2Fprojects%2F1997%2FVereinsmitglieder%2Fparticipants%2Fclaus.heine%2FVersicherungsunterlagen&files=Blah&downloadStartSecret=yur5m66p6lm
Parameters
string | \\OCP\\Files\\Node $pathOrNode The file-system path or node.
Returns
null|string The download URL or null.
Exceptions
FileNotFoundException
Definition at line 676 of file UserStorage.php.
getFile()
getFile (string $path, bool $useCache = false)
Parameters
string | null $path Path to lookup.
bool $useCache Use any previously cached value.
Returns
null|File The user-folder or the given sub-folder
Definition at line 194 of file UserStorage.php.
getFilesAppLink()
getFilesAppLink ($pathOrNode, bool $subDir = false)
Generate a link to the files-app pointing to the parent folder if $pathOrNode is a file, or the node itself if it is a folder.
Example URL generated is
https://foo.bar.com/nextcloud/index.php/apps/files?dir=/camerata/projects/2020/Test2020/participants/claus-justus.heine
Parameters
string | Node $pathOrNode The file-system path or node.
bool $subDir If the $pathOrNode refers to a folder then open this folder. Otherwise open the parent.
Returns
string|null URL to the files app.
Definition at line 723 of file UserStorage.php.
getFolder()
getFolder (string $path, bool $useCache = false)
Parameters
string $path Path to lookup.
bool $useCache Use any previously cached value.
Returns
null|Folder
Definition at line 206 of file UserStorage.php.
getRoot()
getRoot ()
Returns
\OCP\Files\Folder The root-folder
Definition at line 376 of file UserStorage.php.
getUserPath()
getUserPath (Node $node)
Return the path relative to user-folder.
Parameters
Node $node The cloud FS node.
Returns
null|string
Definition at line 135 of file UserStorage.php.
pathCat()
static pathCat ($first, ?string $second = null) static
Parameters
string | array $first Paths to cat. May be an array.
null | string $second Optional second component.
Returns
string The concatenated paths.
Definition at line 340 of file UserStorage.php.
putContent()
putContent (string $path, string $content)
Put file content by path.
Create $path if it does not exists, otherwise replace its contents by the given data.
Parameters
string $path The file path.
string $content The file content.
Returns
File
Definition at line 584 of file UserStorage.php.
References UserStorage\ensureFolder().
rename()
rename (string $oldPath, string $newPath)
Rename $oldPath to $newPath which are interpreted as paths relative to the user's folder.
Parameters
string $oldPath The path to move.
string $newPath The path to move to.
Returns
void
Exceptions
Exception If renaming fails.
Definition at line 473 of file UserStorage.php.
setUser()
setUser (?IUser $user)
Parameters
IUser $user The current user.
Returns
UserStorage
Definition at line 101 of file UserStorage.php.
References UserStorage\user().
Referenced by UserStorage\__construct().
stripParents()
static stripParents (string $path, int $depth) static
Strip the given number of directories from $path.
Return the root-path self::PATH_SEP if $depth exceeds the number of path-components present.
Parameters
string $path The path to work on.
int $depth How many components to strip from the start.
Returns
string
Definition at line 368 of file UserStorage.php.
user()
user ()
Returns
null|IUser The current user
Definition at line 115 of file UserStorage.php.
Referenced by UserStorage\setUser(), and UserStorage\userId().
userId()
userId ()
Returns
string The current user-id
Definition at line 123 of file UserStorage.php.
References UserStorage\user().
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 70 of file UserStorage.php.
$nodeCache
array $nodeCache = [] private
Definition at line 79 of file UserStorage.php.
$rootFolder
Folder $rootFolder protected
Definition at line 73 of file UserStorage.php.
$user
IUser $user protected
Definition at line 67 of file UserStorage.php.
$userFolder
Folder $userFolder protected
Definition at line 76 of file UserStorage.php.
CACHE_DIRECTORY
const CACHE_DIRECTORY = self::PATH_SEP.'cache'
Definition at line 64 of file UserStorage.php.
PATH_SEP
const PATH_SEP = Constants::PATH_SEP
Definition at line 63 of file UserStorage.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Storage/UserStorage.php