CamerataDB: Uuid Class Reference
Uuid Class Reference
Customize with some defaults, like a random node.
Static Public Member Functions
static create ()
Create a default Uuid.
static uuid1 ($node=null, ?int $clockSeq=null)
{}
static asUuid (mixed $data)
Convert "anything" to a UuidInterface.
static nil ()
static uuidBytes (mixed $data)
Convert "anything" to a binary UUID representation.
Static Private Member Functions
static createNode ()
Internal helper function.
Static Private Attributes
static $nodeProvider
Detailed Description
Customize with some defaults, like a random node.
Definition at line 33 of file Uuid.php.
Member Function Documentation
asUuid()
static asUuid (mixed $data) static
Convert "anything" to a UuidInterface.
Parameters
mixed $data
Returns
null|UuitInterface
Definition at line 67 of file Uuid.php.
Referenced by Uuid\uuidBytes().
create()
static create () static
Create a default Uuid.
Currently a version 1 uuid with random node.
Returns
UuidInterface
Definition at line 44 of file Uuid.php.
References Uuid\uuid1().
createNode()
static createNode () static private
Internal helper function.
Returns
string Node for Uuid generation.
Definition at line 110 of file Uuid.php.
Referenced by Uuid\uuid1().
nil()
static nil () static
Returns
UuidInterface
Definition at line 84 of file Uuid.php.
uuid1()
static uuid1 ($node = null, ?int $clockSeq = null) static
{}
Definition at line 52 of file Uuid.php.
References Uuid\createNode().
Referenced by Uuid\create().
uuidBytes()
static uuidBytes (mixed $data) static
Convert "anything" to a binary UUID representation.
Parameters
mixed $data
Returns
null|string Binary string of length 16
Definition at line 96 of file Uuid.php.
References Uuid\asUuid().
Field Documentation
$nodeProvider
Ramsey Uuid Provider NodeProviderInterface $nodeProvider static private
Definition at line 36 of file Uuid.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Common/Uuid.php