CamerataDB: Encryption Class Reference
Encryption Class Reference
Handle transparent multi-user encryption/decryption.
Public Member Functions
__construct (Crypto\AsymmetricKeyService $keyService, string $managementGroupId, EncryptionService $encryptionService, Crypto\SealCryptor $sealCryptor, ILogger $logger,)
setAppCryptor (?Crypto\ICryptor $appCryptor)
Set the shared app-cryptor which is used to encrypt the database values.
getAppCryptor ()
Return the shared app-cryptor which is used to encrypt the database values.
setCachable (bool $isCachable)
transform (?string $value, mixed &$context=null)
Forward transform to data-base.
reverseTransform (?string $value, mixed &$context=null)
Decrypt.
isCachable ()
Disable caching while changing the encryption key.
isEncrypted ()
Private Member Functions
getSealCryptor (string $encryptionId)
manageEncryptionContext (?string $value, mixed $context)
Private Attributes
$keyService
$managementGroupId
$appCryptor
$sealCryptor
$sealService
$cachable
Detailed Description
Handle transparent multi-user encryption/decryption.
Definition at line 39 of file Encryption.php.
Constructor & Destructor Documentation
__construct()
__construct (Crypto\AsymmetricKeyService $keyService, string $managementGroupId, EncryptionService $encryptionService, Crypto\SealCryptor $sealCryptor, ILogger $logger)
Definition at line 62 of file Encryption.php.
Member Function Documentation
getAppCryptor()
getAppCryptor ()
Return the shared app-cryptor which is used to encrypt the database values.
Returns
null|Crypto\ICryptor
Definition at line 98 of file Encryption.php.
getSealCryptor()
getSealCryptor (string $encryptionId) private
Parameters
string $encryptionId
Returns
Crypto\ICryptor
Definition at line 192 of file Encryption.php.
Referenced by Encryption\reverseTransform(), and Encryption\transform().
isCachable()
isCachable ()
Disable caching while changing the encryption key.
Returns
bool
Definition at line 176 of file Encryption.php.
isEncrypted()
isEncrypted ()
Returns
bool
Definition at line 182 of file Encryption.php.
Referenced by Encryption\reverseTransform(), and Encryption\transform().
manageEncryptionContext()
manageEncryptionContext (?string $value, mixed $context) private
Parameters
null | string $value
mixed $context
Returns
array
Definition at line 208 of file Encryption.php.
Referenced by Encryption\reverseTransform(), and Encryption\transform().
reverseTransform()
reverseTransform (?string $value, mixed & $context = null)
Decrypt.
Parameters
string $value Encrypted data.
mixed $context
Returns
mixed Decrypted data.
Definition at line 151 of file Encryption.php.
References Encryption\getSealCryptor(), Encryption\isEncrypted(), and Encryption\manageEncryptionContext().
setAppCryptor()
setAppCryptor (?Crypto\ICryptor $appCryptor)
Set the shared app-cryptor which is used to encrypt the database values.
Parameters
null | Crypto\\ICryptor $appCryptor
Returns
void
Definition at line 88 of file Encryption.php.
setCachable()
setCachable (bool $isCachable)
Parameters
bool $isCachable Set cachable status of transformer.
Returns
void
Definition at line 108 of file Encryption.php.
transform()
transform (?string $value, mixed & $context = null)
Forward transform to data-base.
Parameters
string $value Unencrypted data.
mixed $context
Returns
mixed Encrypted data.
Definition at line 122 of file Encryption.php.
References Encryption\getSealCryptor(), Encryption\isEncrypted(), and Encryption\manageEncryptionContext().
Field Documentation
$appCryptor
Crypto ICryptor $appCryptor private
Definition at line 50 of file Encryption.php.
$cachable
bool $cachable private
Definition at line 59 of file Encryption.php.
$keyService
Crypto AsymmetricKeyService $keyService private
Definition at line 44 of file Encryption.php.
$managementGroupId
string $managementGroupId private
Definition at line 47 of file Encryption.php.
$sealCryptor
Crypto SealCryptor $sealCryptor private
Definition at line 53 of file Encryption.php.
$sealService
Crypto SealService $sealService private
Definition at line 56 of file Encryption.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Listeners/Transformable/Encryption.php