CamerataDB: MigrationsService Class Reference
MigrationsService Class Reference
Manage database migrations.
Public Member Functions
__construct (IL10N $l10n, ILogger $logger, IAppContainer $appContainer, EntityManager $entityManager,)
needsMigration ()
Check whether there need any migrations to be applied.
applyAll ()
Apply all found migrations, stop when one is failing.
getUnapplied ()
getAll ()
getLatest ()
apply (string $version)
Apply the migration with the given version.
Data Fields
const MIGRATIONS_FOLDER = __DIR__ . '/../Maintenance/Migrations/'
const MIGRATIONS_NAMESPACE = 'OCA\CAFEVDB\\Maintenance\\Migrations'
Protected Member Functions
ensureMigrationsAreLoaded ()
Ensure all unapplied migrations are loaded.
createMigrationsTable ()
sanitizeMigrationsTable ()
findUnappliedMigrations (string $directory)
Find all unapplied migrations.
findMigrations (string $directory)
Static Private Member Functions
static getBaseClassName (string $className)
Private Attributes
$appContainer
$unappliedMigrations = null
Detailed Description
Manage database migrations.
Definition at line 44 of file MigrationsService.php.
Constructor & Destructor Documentation
__construct()
__construct (IL10N $l10n, ILogger $logger, IAppContainer $appContainer, EntityManager $entityManager)
Definition at line 59 of file MigrationsService.php.
Member Function Documentation
apply()
apply (string $version)
Apply the migration with the given version.
Parameters
string $version
Returns
void
Definition at line 140 of file MigrationsService.php.
References MigrationsService\findMigrations().
applyAll()
applyAll ()
Apply all found migrations, stop when one is failing.
Returns
void
Definition at line 88 of file MigrationsService.php.
References MigrationsService\ensureMigrationsAreLoaded().
createMigrationsTable()
createMigrationsTable () protected
Returns
void
Definition at line 211 of file MigrationsService.php.
ensureMigrationsAreLoaded()
ensureMigrationsAreLoaded () protected
Ensure all unapplied migrations are loaded.
Returns
void
Definition at line 203 of file MigrationsService.php.
References MigrationsService\findUnappliedMigrations().
Referenced by MigrationsService\applyAll(), MigrationsService\getUnapplied(), and MigrationsService\needsMigration().
findMigrations()
findMigrations (string $directory) protected
Parameters
string $directory
Returns
array
Definition at line 296 of file MigrationsService.php.
Referenced by MigrationsService\apply(), and MigrationsService\findUnappliedMigrations().
findUnappliedMigrations()
findUnappliedMigrations (string $directory) protected
Find all unapplied migrations.
Parameters
string $directory
Returns
array
Definition at line 280 of file MigrationsService.php.
References MigrationsService\findMigrations().
Referenced by MigrationsService\ensureMigrationsAreLoaded().
getAll()
getAll ()
Returns
array Get all migration classes, instantiate all of them via dependency injection with the app-container.
Definition at line 119 of file MigrationsService.php.
getBaseClassName()
static getBaseClassName (string $className) static private
Parameters
string $className
Returns
string
Definition at line 340 of file MigrationsService.php.
getLatest()
getLatest ()
Returns
string The latest migration in the migrations folder.
Definition at line 128 of file MigrationsService.php.
getUnapplied()
getUnapplied ()
Returns
array All unapplied migrations. The migration classes are instatiated using depency injection with the app-container.
Definition at line 106 of file MigrationsService.php.
References MigrationsService\ensureMigrationsAreLoaded().
needsMigration()
needsMigration ()
Check whether there need any migrations to be applied.
Returns
bool
Definition at line 77 of file MigrationsService.php.
References MigrationsService\ensureMigrationsAreLoaded().
sanitizeMigrationsTable()
sanitizeMigrationsTable () protected
Returns
void
Definition at line 225 of file MigrationsService.php.
Field Documentation
$appContainer
IAppContainer $appContainer private
Definition at line 53 of file MigrationsService.php.
$unappliedMigrations
null array $unappliedMigrations = null private
Definition at line 56 of file MigrationsService.php.
MIGRATIONS_FOLDER
const MIGRATIONS_FOLDER = __DIR__ . '/../Maintenance/Migrations/'
Definition at line 49 of file MigrationsService.php.
MIGRATIONS_NAMESPACE
const MIGRATIONS_NAMESPACE = 'OCA\CAFEVDB\\Maintenance\\Migrations'
Definition at line 50 of file MigrationsService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/MigrationsService.php