CamerataDB: CalDavService Class Reference
CalDavService Class Reference
Service class in order to interface to the dav app of Nextcloud.
Public Member Functions
__construct (ConfigService $configService, CalendarManager $calendarManager, CalDavBackend $calDavBackend,)
{}
createCalendar (string $uri, ?string $displayName=null, ?string $userId=null)
Get or create a calendar.
deleteCalendar (int $id)
Delete the calendar with the given id.
groupShareCalendar (int $calendarId, string $groupId, bool $readOnly=false)
Share the given calendar with a group.
isGroupSharedCalendar (int $calendarId, string $groupId, bool $readOnly=false)
Test if the given calendar is shared with the given group.
displayName (int $calendarId, string $displayName)
Set the display name.
search (string $pattern, array $searchProperties=[], array $options=[], ?int $limit=null, ?int $offset=null)
calendarByName (string $displayName)
Get a calendar with the given display name.
calendarById (int $id)
Get a calendar with the given id.
calendarPrincipalUri (int $id)
Get the uri of the original calendar.
calendarUris (int $id)
Get principal, shared and original uri from the calendar id, as well as the owner-user-id.
getCalendars (bool $writable=false)
Get the list of all calendars.
createCalendarObject (int $calendarId, ?string $localUri, mixed $object)
Create an entry in the given calendar from either a VCalendar blob or a Sabre VCalendar object.
updateCalendarObject (int $calendarId, string $localUri, mixed $object)
Update an entry in the given calendar from either a VCalendar blob or a Sabre VCalendar object.
deleteCalendarObject (int $calendarId, string $objectIdentifier)
Remove the given calendar object.
getCalendarObject (int $calendarId, string $objectIdentifier)
Fetch an event object by its local URI.
Data Fields
const WRITE_PERMISSIONS = (Constants::PERMISSION_CREATE|Constants::PERMISSION_UPDATE)
const URI_SUFFIX = '.ics'
Private Member Functions
makeCalendar (int $calendarId)
Create a new calendar if the one with the given id does not exist.
calendarWritable (ICalendar $calendar)
getObjectUri (int $calendarId, string $objectIdentifier)
Convert an object UID to its local URI.
refreshCalendarManager ()
Force \OCA\DAV\CalDAV\CalendarManager to be refreshed.
Static Private Member Functions
static makeGroupShare (string $groupId, bool $readOnly=false)
Private Attributes
$calDavBackend
$calendarManager
$calendarUserId
Detailed Description
Service class in order to interface to the dav app of Nextcloud.
Missing: move/delete calendar
Todo:
: replace the stuff below by more persistent APIs. As it shows (Sep. 2020) the only option would be http calls to the dav service. Even the perhaps-forthcoming writable calendar API does not allow the creation of calendars or altering shring options.
Definition at line 49 of file CalDavService.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, CalendarManager $calendarManager, CalDavBackend $calDavBackend)
{}
Definition at line 66 of file CalDavService.php.
Member Function Documentation
calendarById()
calendarById (int $id)
Get a calendar with the given id.
Parameters
int $id Numeric calendar id.
Returns
ICalendar
Definition at line 282 of file CalDavService.php.
References CalDavService\refreshCalendarManager().
calendarByName()
calendarByName (string $displayName)
Get a calendar with the given display name.
Parameters
string $displayName Search criterion.
Returns
null|ICalendar
Definition at line 262 of file CalDavService.php.
References CalDavService\refreshCalendarManager().
calendarPrincipalUri()
calendarPrincipalUri (int $id)
Get the uri of the original calendar.
Parameters
int $id Numeric calendar id.
Returns
null|string Calendar URI.
Definition at line 302 of file CalDavService.php.
Referenced by CalDavService\getObjectUri().
calendarUris()
calendarUris (int $id)
Get principal, shared and original uri from the calendar id, as well as the owner-user-id.
Parameters
int $id Numeric calendar id.
Returns
null|array
[
  'principaluri' => principals/users/OWNER_ID,
  'owneruri' => URI_AS_SEEN_BY_OWNER,
  'shareuri' => URI_AS_SEEN_BY_CURRENT_USER,
  'ownerid' => OWNER_USER_ID,
  'userid' => CURRENT_USER_ID,
]
Bug:
Users inernal APIs. The NC PHP API is just too incomplete.
Definition at line 330 of file CalDavService.php.
calendarWritable()
calendarWritable (ICalendar $calendar) private
Parameters
ICalendar $calendar Cloud calendar instance.
Returns
bool Whether the calendar is writable.
Definition at line 354 of file CalDavService.php.
Referenced by CalDavService\getCalendars().
createCalendar()
createCalendar (string $uri, ?string $displayName = null, ?string $userId = null)
Get or create a calendar.
Parameters
string $uri Relative URI.
null | string $displayName Display-name of the calendar.
null | string $userId part of the principal name.
Returns
int Calendar id.
Bug:
This function uses internal APIs.
Definition at line 91 of file CalDavService.php.
References CalDavService\refreshCalendarManager().
createCalendarObject()
createCalendarObject (int $calendarId, ?string $localUri, mixed $object)
Create an entry in the given calendar from either a VCalendar blob or a Sabre VCalendar object.
Parameters
int $calendarId Numeric calendar id.
null | string $localUri Local URI to use or null.
mixed $object Calendar data.
Returns
string local URI of the calendar object, relative to the calendar's URI.
Bug:
This function uses internal APIs.
Definition at line 395 of file CalDavService.php.
deleteCalendar()
deleteCalendar (int $id)
Delete the calendar with the given id.
Parameters
int $id Calendar id.
Returns
void
Bug:
This function uses internal APIs.
Definition at line 123 of file CalDavService.php.
deleteCalendarObject()
deleteCalendarObject (int $calendarId, string $objectIdentifier)
Remove the given calendar object.
Parameters
int $calendarId Numeric calendar id.
string $objectIdentifier Either the URI or the UID of the object. If $objectIdentifier ends with '.ics' it is assumed to be an URI, other the UID.
Returns
void
Bug:
This function uses internal APIs.
Definition at line 443 of file CalDavService.php.
References CalDavService\getObjectUri().
displayName()
displayName (int $calendarId, string $displayName)
Set the display name.
Parameters
int $calendarId Numeric calendar id.
string $displayName The display name to set.
Returns
bool Whether the attempt succeeded.
Definition at line 220 of file CalDavService.php.
References CalDavService\refreshCalendarManager().
getCalendarObject()
getCalendarObject (int $calendarId, string $objectIdentifier)
Fetch an event object by its local URI.
The return value is an array with the following keys:
calendardata - The iCalendar-compatible calendar data
uri - a unique key which will be used to construct the uri. This can be any arbitrary string, but making sure it ends with '.ics' is a good idea. This is only the basename, or filename, not the full path.
lastmodified - a timestamp of the last modification time
etag - An arbitrary string, surrounded by double-quotes. (e.g.: '"abcdef"')
size - The size of the calendar objects, in bytes.
component - optional, a string containing the type of object, such as 'vevent' or 'vtodo'. If specified, this will be used to populate the Content-Type header.
calendarid - The passed argument $calendarId
Parameters
int $calendarId
string $objectIdentifier Either the URI or the UID of the object. If $objectIdentifier ends with '.ics' it is assumed to be an URI, other the UID.
Returns
array|null
Bug:
This function uses internal APIs. This could be changed to a CalDav call which would then only return the serialized data, respectively an arry/proxy object with calendarId, uri and the calendar data.
Definition at line 483 of file CalDavService.php.
References CalDavService\getObjectUri().
getCalendars()
getCalendars (bool $writable = false)
Get the list of all calendars.
Parameters
bool $writable If true return only calendars with write access.
Returns
ICalendar[]
Definition at line 366 of file CalDavService.php.
References CalDavService\calendarWritable().
getObjectUri()
getObjectUri (int $calendarId, string $objectIdentifier) private
Convert an object UID to its local URI.
Parameters
int $calendarId
string $objectIdentifier Either the URI or the UID of the object. If $objectIdentifier ends with '.ics' it is assumed to be an URI, other the UID.
Returns
string|null The local URI (basename).
Bug:
This function uses internal APIs.
Definition at line 509 of file CalDavService.php.
References CalDavService\calendarPrincipalUri().
Referenced by CalDavService\deleteCalendarObject(), and CalDavService\getCalendarObject().
groupShareCalendar()
groupShareCalendar (int $calendarId, string $groupId, bool $readOnly = false)
Share the given calendar with a group.
Parameters
int $calendarId Numeric calendar id.
string $groupId Cloud group id.
bool $readOnly Whether to share read-only.
Returns
bool Whether the group-share request succeeded.
Bug:
This function uses internal APIs.
Definition at line 174 of file CalDavService.php.
References CalDavService\isGroupSharedCalendar(), CalDavService\makeCalendar(), and CalDavService\makeGroupShare().
isGroupSharedCalendar()
isGroupSharedCalendar (int $calendarId, string $groupId, bool $readOnly = false)
Test if the given calendar is shared with the given group.
Parameters
int $calendarId Numeric calendar id.
string $groupId Cloud group id.
bool $readOnly Whether to share read-only.
Returns
bool Result of the test.
Definition at line 199 of file CalDavService.php.
References CalDavService\makeGroupShare().
Referenced by CalDavService\groupShareCalendar().
makeCalendar()
makeCalendar (int $calendarId) private
Create a new calendar if the one with the given id does not exist.
Parameters
int $calendarId
Returns
null|Calendar
Definition at line 152 of file CalDavService.php.
Referenced by CalDavService\groupShareCalendar().
makeGroupShare()
static makeGroupShare (string $groupId, bool $readOnly = false) static private
Parameters
string $groupId GID.
bool $readOnly Share read-only.
Returns
array
Definition at line 135 of file CalDavService.php.
Referenced by CalDavService\groupShareCalendar(), and CalDavService\isGroupSharedCalendar().
refreshCalendarManager()
refreshCalendarManager () private
Force \OCA\DAV\CalDAV\CalendarManager to be refreshed.
Returns
void
Bug:
This function uses internal APIs.
Definition at line 535 of file CalDavService.php.
Referenced by CalDavService\calendarById(), CalDavService\calendarByName(), CalDavService\createCalendar(), and CalDavService\displayName().
search()
search (string $pattern, array $searchProperties = [], array $options = [], ?int $limit = null, ?int $offset = null)
Parameters
string $pattern which should match within the $searchProperties.
array $searchProperties defines the properties within the query pattern should match.
array $options - optional parameters: ['timerange' => ['start' => new DateTime(...), 'end' => new DateTime(...)]].
integer | null $limit - limit number of search results.
integer | null $offset - offset for paging of search results.
Returns
array an array of events/journals/todos which are arrays of key-value-pairs.
See also
CalendarManager::search()
Definition at line 250 of file CalDavService.php.
updateCalendarObject()
updateCalendarObject (int $calendarId, string $localUri, mixed $object)
Update an entry in the given calendar from either a VCalendar blob or a Sabre VCalendar object.
Parameters
int $calendarId Numeric calendar id.
null | string $localUri Local URI to use or null.
mixed $object Calendar data.
Returns
void
Bug:
This function uses internal APIs.
Definition at line 421 of file CalDavService.php.
Field Documentation
$calDavBackend
CalDavBackend $calDavBackend private
Definition at line 57 of file CalDavService.php.
$calendarManager
CalendarManager $calendarManager private
Definition at line 60 of file CalDavService.php.
$calendarUserId
int $calendarUserId private
Definition at line 63 of file CalDavService.php.
URI_SUFFIX
const URI_SUFFIX = '.ics'
Definition at line 54 of file CalDavService.php.
WRITE_PERMISSIONS
const WRITE_PERMISSIONS = (Constants::PERMISSION_CREATE|Constants::PERMISSION_UPDATE)
Definition at line 53 of file CalDavService.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Service/CalDavService.php