CamerataDB: ScanFiles Class Reference
ScanFiles Class Reference
Class ScanFiles is a background job used to run the file scanner over the user accounts to ensure integrity of the file cache.
Public Member Functions
__construct (IConfig $config, IEventDispatcher $dispatcher, LoggerInterface $logger, IDBConnection $connection,)
run ($argument)
{}
Data Fields
const USERS_PER_SESSION = 500
Amount of users that should get scanned per execution.
Protected Member Functions
runScanner (string $user)
Private Member Functions
getUserToScan ()
Find a storage which have unindexed files and return a user with access to the storage.
Private Attributes
$config
$dispatcher
LoggerInterface $logger
$connection
Detailed Description
Class ScanFiles is a background job used to run the file scanner over the user accounts to ensure integrity of the file cache.
This is a copy of
OCA\Files\BackgroundJob\ScanFiles
which is triggered by a JS timer via Ajax from the front-end in order to get authenticated background jobs.
Definition at line 43 of file ScanFiles.php.
Constructor & Destructor Documentation
__construct()
__construct (IConfig $config, IEventDispatcher $dispatcher, LoggerInterface $logger, IDBConnection $connection)
Parameters
IConfig $config
IEventDispatcher $dispatcher
LoggerInterface $logger
IDBConnection $connection
Definition at line 61 of file ScanFiles.php.
Member Function Documentation
getUserToScan()
getUserToScan () private
Find a storage which have unindexed files and return a user with access to the storage.
Returns
string|false
Definition at line 102 of file ScanFiles.php.
Referenced by ScanFiles\run().
run()
run ($argument)
{}
Definition at line 116 of file ScanFiles.php.
References ScanFiles\getUserToScan(), and ScanFiles\runScanner().
runScanner()
runScanner (string $user) protected
Parameters
string $user
Returns
void
Definition at line 81 of file ScanFiles.php.
Referenced by ScanFiles\run().
Field Documentation
$config
IConfig $config private
Definition at line 46 of file ScanFiles.php.
$connection
$connection private
Definition at line 50 of file ScanFiles.php.
$dispatcher
IEventDispatcher $dispatcher private
Definition at line 48 of file ScanFiles.php.
$logger
LoggerInterface $logger private
Definition at line 49 of file ScanFiles.php.
USERS_PER_SESSION
const USERS_PER_SESSION = 500
Amount of users that should get scanned per execution.
Definition at line 53 of file ScanFiles.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/BackgroundJob/ScanFiles.php