CamerataDB: AddressBook Class Reference
AddressBook Class Reference
Cloud- and CardDAV address-book integration.
Public Member Functions
__construct (ConfigService $configService, ICardBackend $cardBackend, string $principalUri,)
createFile ($name, $data=null)
{}
getChild ($name)
{}
getChildren ()
{}
childExists ($name)
{}
delete ()
{}
getLastModified ()
{}
propPatch (PropPatch $propPatch)
{}
getProperties ($properties)
{}
Private Attributes
$cardBackend
$principalUri
Detailed Description
Cloud- and CardDAV address-book integration.
Definition at line 39 of file AddressBook.php.
Constructor & Destructor Documentation
__construct()
__construct (ConfigService $configService, ICardBackend $cardBackend, string $principalUri)
Definition at line 50 of file AddressBook.php.
Member Function Documentation
childExists()
childExists ($name)
{}
Definition at line 90 of file AddressBook.php.
References AddressBook\getChild().
createFile()
createFile ($name, $data = null)
{}
Definition at line 64 of file AddressBook.php.
delete()
delete ()
{}
Definition at line 102 of file AddressBook.php.
getChild()
getChild ($name)
{}
Exceptions
RecordNotFound
Definition at line 74 of file AddressBook.php.
Referenced by AddressBook\childExists().
getChildren()
getChildren ()
{}
Definition at line 81 of file AddressBook.php.
getLastModified()
getLastModified ()
{}
Definition at line 108 of file AddressBook.php.
Referenced by AddressBook\getProperties().
getProperties()
getProperties ($properties)
{}
Definition at line 120 of file AddressBook.php.
References AddressBook\getLastModified().
propPatch()
propPatch (PropPatch $propPatch)
{}
Definition at line 114 of file AddressBook.php.
Field Documentation
$cardBackend
ICardBackend $cardBackend private
Definition at line 44 of file AddressBook.php.
$principalUri
string $principalUri private
Definition at line 47 of file AddressBook.php.
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/AddressBook/AddressBook.php