CamerataDB: MusiciansRepository Class Reference
MusiciansRepository Class Reference
Repository for musicians.
Public Member Functions
findByName (string $firstName, string $surName)
fetchIds (array $criteria=[])
findIdByUUID (mixed $uuid)
findIdByUserId (string $userId)
findByUUID (mixed $uuid)
findByUserId (string $userId)
findStreetAddress (int $musicianId)
Fetch the street address of the respected musician.
findName (int $musicianId)
Fetch the name and email of the respective musician.
fetchLastModifiedDate (array $criteria=[], string $indexBy='uuid')
Fetch the latest modification date of the given or all musicians.
findByInstruments (array $instrumentIds, ?array $orderBy=null, ?int $limit=null, ?int $offset=null, string $indexBy='id',)
Find musicians by their instruments, identified by the instrument ids.
getEntityManager ()
Public export of parent function.
Static Public Member Functions
static createInstrumentsCriteria (array $instrumentIds, ?string $alias=null)
Create search criteria by instrument ids.
Detailed Description
Repository for musicians.
Definition at line 32 of file MusiciansRepository.php.
Member Function Documentation
createInstrumentsCriteria()
static createInstrumentsCriteria (array $instrumentIds, ?string $alias = null) static
Create search criteria by instrument ids.
The search field is "instrument" and generally is a collection of Entities\Instrument.
Parameters
array<int,int> $instrumentIds
string | null $alias Optional alias to add to the field.
Returns
Criteria
Definition at line 274 of file MusiciansRepository.php.
fetchIds()
fetchIds (array $criteria = [])
Parameters
array $criteria
Returns
array
Definition at line 74 of file MusiciansRepository.php.
fetchLastModifiedDate()
fetchLastModifiedDate (array $criteria = [], string $indexBy = 'uuid')
Fetch the latest modification date of the given or all musicians.
Parameters
array $criteria Criteria as for findBy(). However, wild-cards like '*' and '' are allowed and internally converted to '' in a LIKE comparison.
string $indexBy
Returns
null|array
Definition at line 192 of file MusiciansRepository.php.
findByInstruments()
findByInstruments (array $instrumentIds, ?array $orderBy = null, ?int $limit = null, ?int $offset = null, string $indexBy = 'id')
Find musicians by their instruments, identified by the instrument ids.
Parameters
array<int,int> $instrumentIds
array | null $orderBy [ KEY => ORDERING ].
int | null $limit Result-set limit.
int | null $offset Result-set offset.
string $indexBy Result by default are indexed by id.
Returns
array<int, Entities\Musician>
Definition at line 252 of file MusiciansRepository.php.
findByName()
findByName (string $firstName, string $surName)
Parameters
string $firstName First-name or display-name.
string | null $surName
Returns
array of \OCA\CAFEVDB\Database\Doctrine\ORM\Entities\Musician
Definition at line 43 of file MusiciansRepository.php.
findByUserId()
findByUserId (string $userId)
Parameters
string $userId
Returns
Entities\Musician
Definition at line 120 of file MusiciansRepository.php.
findByUUID()
findByUUID (mixed $uuid)
Parameters
mixed $uuid
Returns
Entities\Musician
Definition at line 110 of file MusiciansRepository.php.
findIdByUserId()
findIdByUserId (string $userId)
Parameters
string $userId
Returns
null|Entities\Musician
Definition at line 97 of file MusiciansRepository.php.
findIdByUUID()
findIdByUUID (mixed $uuid)
Parameters
mixed $uuid
Returns
Entities\Musician
Definition at line 86 of file MusiciansRepository.php.
findName()
findName (int $musicianId)
Fetch the name and email of the respective musician.
Parameters
int $musicianId
Returns
array Return value is a flat array: ``‘ array('firstName’ => ..., 'surName' => ..., 'email' => ...); ```.
Definition at line 169 of file MusiciansRepository.php.
findStreetAddress()
findStreetAddress (int $musicianId)
Fetch the street address of the respected musician.
Needed in order to generate automated snail-mails.
Parameters
int $musicianId
Returns
array Return value is a flat array: ``‘ array('firstName’ => ..., 'surName' => ..., 'street' => ..., 'city' => ..., 'ZIP' => ...); ```.
Definition at line 141 of file MusiciansRepository.php.
getEntityManager()
getEntityManager () inherited
Public export of parent function.
Returns
EntityManagerInterface
Definition at line 39 of file EntityRepository.php.
Referenced by SepaDebitMandatesRepository\ban(), ImagesRepository\findForEntity(), OCA\CAFEVDB\Traits\getDatabaseRepository(), ProjectWebPagesRepository\mergeAttributes(), and SepaDebitMandatesRepository\remove().
The documentation for this class was generated from the following file:
/var/www/dev1/htdocs/nextcloud-git-25/apps/cafevdb/lib/Database/Doctrine/ORM/Repositories/MusiciansRepository.php