CamerataDB: OCA\CAFEVDB\PageRenderer\FieldTraits Namespace Reference
OCA\CAFEVDB\PageRenderer\FieldTraits Namespace Reference
Orchestra member, musician and project management application.
Functions
renderAllProjectsField (string $musicianIdField, string $tableTab, array $css=[],)
initCrypto ()
ormEncrypt (string $value)
Use the encryption machine also used by the entity-manager.
ormDecrypt (string $value)
Use the encryption machine also used by the entity-manager.
getListsService ()
announcementsSubscriptionControls (string $emailSql=' $table.email', array $columnTabs=[], array $override=[],)
Return fdd for controlling the global announcements subscription.
projectListSubscriptionControls (string $emailSql=' $table.email', array $columnTabs=[], array $override=[],)
allowedOptionLabel (string $label, mixed $value, string $dataType, ?string $css=null, array $data=[])
Create a label for a multi-value option (multiple, parallel, recurring).
recurringChangeRowHtml (?string $optionValue, Entities\ProjectParticipantField $field, Entities\ProjectParticipantFieldDataOption $fieldOption, array $invoices, int $optionIdx, Entities\Musician $musician, int $uiFlags,)
Generate one row for Multiplicity::RECURRING in Change/Add/Paste mode.
cloudFileUploadRowHtml (mixed $optionValue, int $fieldId, ?string $optionKey, ?string $subDir, ?string $fileBase, Entities\Musician $musician)
Generate one HTML input row for a cloud-file field.
getFilesAppLink (?Entities\ProjectParticipantField $field, Entities\Musician $musician, ?Entities\Project $project=null, ?string $subFolder=null,)
Generate a link to the files-app if appropriate.
getFilesAppAnchor (?Entities\ProjectParticipantField $field, Entities\Musician $musician, ?Entities\Project $project=null, ?string $subFolder=null, ?string $toolTip=null,)
makeTotalFeesFields (array &$fdd, array $subTotals, string $financeTab)
Generate three distinct columns for the total invoice amount, the amount already transferred and the open amount which still needs to be transferred.
totalFeesPreFilterTrigger (PHPMyEdit $pme, string $op, string $step)
Move the search request from the summary to the respective detail field.
renderSepaAccounts (string $musicianIdField='id', ?int $projectId=null, ?int $membersProjectId=null, string $financeTab='finance',)
Generate join-structure and field-descriptions for the SEPA information.
substituteSQLFragment (array $fdd, string $fieldName, string $sql, ?int $fieldIndex=null)
Replace $join_table etc.
Variables
trait AllProjectsTrait
Add for fun a field with all projects the musician already participated in.
trait CryptoTrait
Helper function for directing PME legacy decrypt/encrypt to then functions used by the ORM.
$encryptionTransformer
trait MailingListsTrait
Field-trait for reusable field definitions.
$expertMode
$listsService
$project
trait ParticipantFieldsTrait
Participant-fields.
$userStorage = null
$participantFieldsService
$projectService
$toolTipsService
static $toolTipsPrefix = 'page-renderer:participant-fields:display'
$pme
function renderParticipantFields iterable $participantFields
For each extra field add one dedicated join table entry which is pinned to the respective field-id.
function renderParticipantFields iterable mixed $projectIdField = 'project_id'
function renderParticipantFields iterable mixed string $financeTab = 'finance'
foreach($participantFields as $field) $generator
return [ $joinStructure, $generator]
trait ParticipantFileFieldsTrait
File related per-participant-fields.
static $toolTipsPrefix = 'page-renderer:participant-fields:display'
trait ParticipantTotalFeesTrait
Field definition for total fees and salaries for participants.
$l
static $toolTipsPrefix = 'page-renderer:participant-fields:display'
trait SepaAccountsTrait
SEPA bank account.
trait SubstituteSQLFragmentTrait
Substitue some legacy PME placeholder.
Detailed Description
Orchestra member, musician and project management application.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021, 2022, 2023 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
Copyright (c) 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
Copyright (c) 2022 Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2020, 2021, 2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2011-2023 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
CAFEVDB – Camerata Academica Freiburg e.V. DataBase.
Author
Claus-Justus Heine himse.nosp@m.lf@c.nosp@m.laus-.nosp@m.just.nosp@m.us-he.nosp@m.ine..nosp@m.de
Copyright
2022 Claus-Justus Heine @license AGPL-3.0-or-later
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
allowedOptionLabel()
allowedOptionLabel (string $label, mixed $value, string $dataType, ?string $css = null, array $data = []) protected
Create a label for a multi-value option (multiple, parallel, recurring).
Parameters
string $label Label of the option.
mixed $value Value of the per-participant data.
string $dataType String-value of the FieldType.
null | string $css Optional css-class.
array $data Optional data for data-attributes of the container-span/div.
Returns
string The html-string for rendering the option value.
Definition at line 2102 of file ParticipantFieldsTrait.php.
announcementsSubscriptionControls()
announcementsSubscriptionControls (string $emailSql = '$table.email', array $columnTabs = [], array $override = []) protected
Return fdd for controlling the global announcements subscription.
Parameters
string $emailSql SQL table field with the email address.
array $columnTabs Table-tabs definitions.
array $override Generic override FDD fields.
Returns
array The merge field definitions.
Definition at line 68 of file MailingListsTrait.php.
cloudFileUploadRowHtml()
cloudFileUploadRowHtml (mixed $optionValue, int $fieldId, ?string $optionKey, ?string $subDir, ?string $fileBase, Entities\Musician $musician) protected
Generate one HTML input row for a cloud-file field.
Parameters
mixed $optionValue
int $fieldId
null | string $optionKey
null | string $subDir
null | string $fileBase
Entities\\Musician $musician
Returns
string HTML fragment.
Definition at line 88 of file ParticipantFileFieldsTrait.php.
getFilesAppAnchor()
getFilesAppAnchor (?Entities\ProjectParticipantField $field, Entities\Musician $musician, ?Entities\Project $project = null, ?string $subFolder = null, ?string $toolTip = null) private
Parameters
null | Entities\\ProjectParticipantField $field
Entities\\Musician $musician
null | Entities\\Project $project
null | string $subFolder
null | string $toolTip
Returns
string HTML fragment.
Definition at line 359 of file ParticipantFileFieldsTrait.php.
getFilesAppLink()
getFilesAppLink (?Entities\ProjectParticipantField $field, Entities\Musician $musician, ?Entities\Project $project = null, ?string $subFolder = null) private
Generate a link to the files-app if appropriate.
The link is always a link to a folder, so for FieldMultiplicity::SIMPLE the documents folder is used.
Parameters
null | Entities\\ProjectParticipantField $field
Entities\\Musician $musician
null | Entities\\Project $project
null | string $subFolder
Returns
null|array
Definition at line 290 of file ParticipantFileFieldsTrait.php.
getListsService()
getListsService () protected
Returns
MailingListsService
Definition at line 49 of file MailingListsTrait.php.
initCrypto()
initCrypto () private
Returns
void
Definition at line 41 of file CryptoTrait.php.
Referenced by OCA\CAFEVDB\PageRenderer\FieldTraits\renderSepaAccounts().
makeTotalFeesFields()
makeTotalFeesFields (array & $fdd, array $subTotals, string $financeTab) protected
Generate three distinct columns for the total invoice amount, the amount already transferred and the open amount which still needs to be transferred.
Parameters
array $fdd Field description data, will be modified in place.
array $subTotals Array of SQL selectable expressions as returned by the renderer-callback returned by ParticipantFieldsTrait::renderParticipantFields().
string $financeTab The tab to move the field to.
Returns
void
Definition at line 159 of file ParticipantTotalFeesTrait.php.
References OCA\CAFEVDB\PageRenderer\FieldTraits\substituteSQLFragment().
ormDecrypt()
ormDecrypt (string $value) private
Use the encryption machine also used by the entity-manager.
Parameters
string $value
Returns
string
Definition at line 66 of file CryptoTrait.php.
Referenced by OCA\CAFEVDB\PageRenderer\FieldTraits\renderSepaAccounts().
ormEncrypt()
ormEncrypt (string $value) private
Use the encryption machine also used by the entity-manager.
Parameters
string $value
Returns
string
Definition at line 53 of file CryptoTrait.php.
Referenced by OCA\CAFEVDB\PageRenderer\FieldTraits\renderSepaAccounts().
projectListSubscriptionControls()
projectListSubscriptionControls (string $emailSql = '$table.email', array $columnTabs = [], array $override = []) protected
Parameters
string $emailSql SQL table field with the email address.
array $columnTabs Table-tabs definitions.
array $override Generic override FDD fields.
Returns
array The merge field definitions.
Definition at line 131 of file MailingListsTrait.php.
recurringChangeRowHtml()
recurringChangeRowHtml (?string $optionValue, Entities\ProjectParticipantField $field, Entities\ProjectParticipantFieldDataOption $fieldOption, array $invoices, int $optionIdx, Entities\Musician $musician, int $uiFlags) protected
Generate one row for Multiplicity::RECURRING in Change/Add/Paste mode.
Parameters
string $optionValue Value of the option.
Entities\\ProjectParticipantField $field The respective field.
Entities\\ProjectParticipantFieldDataOption $fieldOption The associated field-option.
array $invoices Potential supporting documents.
int $optionIdx Consecutive index of the active options.
Entities\\Musician $musician
int $uiFlags
Returns
string HTML fragment.
Definition at line 2164 of file ParticipantFieldsTrait.php.
renderAllProjectsField()
renderAllProjectsField (string $musicianIdField, string $tableTab, array $css = [])
Parameters
string $musicianIdField The field name of the column with the musician id. If null assume that the musicians table is the master table in the join and the column name is 'id'.
string $tableTab The id of the column-group the fields should be attached to.
array $css Additional css-classes to add to the field definition HTML entities.
Returns
array
Definition at line 50 of file AllProjectsTrait.php.
renderSepaAccounts()
renderSepaAccounts (string $musicianIdField = 'id', ?int $projectId = null, ?int $membersProjectId = null, string $financeTab = 'finance')
Generate join-structure and field-descriptions for the SEPA information.
Parameters
string $musicianIdField
null | int $projectId
null | int $membersProjectId
string $financeTab
Returns
array
[ JOIN_STRUCTURE_FRAGMENT, GENERATOR(&$fdd) ]
Definition at line 53 of file SepaAccountsTrait.php.
References OCA\CAFEVDB\PageRenderer\FieldTraits\initCrypto(), PMETableViewBase\JOIN_READONLY, OCA\CAFEVDB\PageRenderer\FieldTraits\ormDecrypt(), and OCA\CAFEVDB\PageRenderer\FieldTraits\ormEncrypt().
substituteSQLFragment()
substituteSQLFragment (array $fdd, string $fieldName, string $sql, ?int $fieldIndex = null) protected
Replace $join_table etc.
replacements by their proper table and column aliases, base on the ordering defined in $fdd.
Parameters
array $fdd Field description data.
string $fieldName The field name which defines the pivot for the replacements.
string $sql SQL fragment with replacements.
null | int $fieldIndex Field index if known, if not given array_search() is used.
Returns
The result of the substitutions.
Exceptions
UnexpectedValueException Thrown if $fieldName is not found in $fdd.
Definition at line 54 of file SubstituteSQLFragmentTrait.php.
Referenced by OCA\CAFEVDB\PageRenderer\FieldTraits\makeTotalFeesFields().
totalFeesPreFilterTrigger()
totalFeesPreFilterTrigger (PHPMyEdit $pme, string $op, string $step)
Move the search request from the summary to the respective detail field.
Parameters
PHPMyEdit $pme
string $op
string $step
Returns
bool
Definition at line 247 of file ParticipantTotalFeesTrait.php.
Variable Documentation
$encryptionTransformer
Transformable Transformer TransformerInterface $encryptionTransformer protected
Definition at line 38 of file CryptoTrait.php.
$expertMode
bool $expertMode protected
Definition at line 40 of file MailingListsTrait.php.
$financeTab
function renderParticipantFields iterable mixed string $financeTab = 'finance'
Definition at line 137 of file ParticipantFieldsTrait.php.
$generator
foreach ($participantFields as $field) $generator
Definition at line 174 of file ParticipantFieldsTrait.php.
$l
IL10N $l protected
Definition at line 47 of file ParticipantTotalFeesTrait.php.
$listsService
MailingListsService $listsService private
Definition at line 43 of file MailingListsTrait.php.
$participantFields
array $participantFields
For each extra field add one dedicated join table entry which is pinned to the respective field-id.
Parameters
iterable $participantFields
string | array $projectIdField
string $financeTab
Returns
array
[
  JOIN_STRUCTURE_FRAGMENT,
  callable(array &$fdd, array &subTotals = []),
]
After merging JOIN_STRUCTURE_FRAGMENT to the rest of using class's join-structure the generator callback has to be called and augments the given field-description-data with columns for all participant fields. The $subTotals array is filled with SQL-fragments which collect the service-fee amounts of the respective monetary fields with data-type field-type FieldType::RECEIVABLES, FieldType::LIABILITIES, it is indexed by field-name. Steps to perform:
merge the returned join-structure into $this->joinStructure
call PMETableViewBase::defineJoinStructure()
call the returned generator function generator($fdd, $subTotals) which will then augment the given field-descriptor array and fill the sub-totals array.
Note
Joining many tables with multiple rows per join key is a performance hit. Therefore there is only a single join and the respective field is selected by an IF-clause inside the group functions. The problem with the multiple joins is that they form a tensor-product of the tables wich rather quickly leads to a memory blow-up.
See also
PMETableViewBase::defineJoinStructure()
PMETableViewBase::$joinTables
Definition at line 135 of file ParticipantFieldsTrait.php.
$participantFieldsService
ProjectParticipantFieldsService $participantFieldsService protected
Definition at line 70 of file ParticipantFieldsTrait.php.
$pme
PHPMyEdit $pme protected
Definition at line 85 of file ParticipantFieldsTrait.php.
$project
Entities Project $project private
Definition at line 46 of file MailingListsTrait.php.
$projectIdField
function renderParticipantFields iterable mixed $projectIdField = 'project_id'
Definition at line 136 of file ParticipantFieldsTrait.php.
$projectService
ProjectService $projectService protected
Definition at line 73 of file ParticipantFieldsTrait.php.
$toolTipsPrefix [1/3]
string $toolTipsPrefix = 'page-renderer:participant-fields:display' static protected
Definition at line 79 of file ParticipantFieldsTrait.php.
$toolTipsPrefix [2/3]
string $toolTipsPrefix = 'page-renderer:participant-fields:display' static protected
Definition at line 69 of file ParticipantFileFieldsTrait.php.
$toolTipsPrefix [3/3]
string $toolTipsPrefix = 'page-renderer:participant-fields:display' static protected
Definition at line 56 of file ParticipantTotalFeesTrait.php.
$toolTipsService
ToolTipsService $toolTipsService protected
Definition at line 76 of file ParticipantFieldsTrait.php.
$userStorage
UserStorage $userStorage = null protected
Definition at line 67 of file ParticipantFieldsTrait.php.
AllProjectsTrait
trait AllProjectsTrait
Initial value:
{
  protected static $allProjectsTable = BaseRenderer::PROJECT_PARTICIPANTS_TABLE . BaseRenderer::VALUES_TABLE_SEP . 'allProjects'
Add for fun a field with all projects the musician already participated in.
Definition at line 33 of file AllProjectsTrait.php.
CryptoTrait
trait CryptoTrait
Initial value:
{
  protected $entityManager
Helper function for directing PME legacy decrypt/encrypt to then functions used by the ORM.
Definition at line 32 of file CryptoTrait.php.
MailingListsTrait
trait MailingListsTrait
Initial value:
{
  use \OCA\CAFEVDB\Traits\ConfigTrait
Field-trait for reusable field definitions.
Definition at line 35 of file MailingListsTrait.php.
ParticipantFieldsTrait
trait ParticipantFieldsTrait
Initial value:
{
  use \OCA\CAFEVDB\Traits\ConfigTrait
Participant-fields.
Definition at line 57 of file ParticipantFieldsTrait.php.
ParticipantFileFieldsTrait
trait ParticipantFileFieldsTrait
Initial value:
{
  use \OCA\CAFEVDB\Traits\ConfigTrait
File related per-participant-fields.
Definition at line 46 of file ParticipantFileFieldsTrait.php.
ParticipantTotalFeesTrait
trait ParticipantTotalFeesTrait
Initial value:
{
  use ParticipantFieldsCgiNameTrait
Field definition for total fees and salaries for participants.
Definition at line 41 of file ParticipantTotalFeesTrait.php.
return
return[$joinStructure, $generator]
Definition at line 2084 of file ParticipantFieldsTrait.php.
SepaAccountsTrait
trait SepaAccountsTrait
Initial value:
{
  use CryptoTrait
SEPA bank account.
Definition at line 33 of file SepaAccountsTrait.php.
SubstituteSQLFragmentTrait
trait SubstituteSQLFragmentTrait
Initial value:
{
  protected $pme
Substitue some legacy PME placeholder.
Definition at line 32 of file SubstituteSQLFragmentTrait.php.