<?php
/**
 * Orchestra member, musicion and project management application.
 *
 * CAFEVDB -- Camerata Academica Freiburg e.V. DataBase.
 *
 * @author Claus-Justus Heine <himself@claus-justus-heine.de>
 * @copyright 2025 Claus-Justus Heine <himself@claus-justus-heine.de>
 * @license AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\CAFEVDB\Database\Doctrine\ORM\Entities;

use OCA\CAFEVDB\Common\RationalNumber;
use OCA\CAFEVDB\Database\Doctrine\ORM as CAFEVDB;
use OCA\CAFEVDB\Wrapped\Doctrine\ORM\Mapping as ORM;
use OCA\CAFEVDB\Wrapped\Gedmo\Mapping\Annotation as Gedmo;

/**
 * InvoiceItems - very similar to ProjectPayment. In the case of a successful
 * debit mandate there could/should be a 1-1 correspondence.
 */
#[ORM\Table(name: 'InvoiceItems')]
#[ORM\Entity(repositoryClass: \OCA\CAFEVDB\Database\Doctrine\ORM\Repositories\InvoiceItemsRepository::class)]
#[ORM\HasLifecycleCallbacks]
class InvoiceItem implements \ArrayAccess, \JsonSerializable
{
  use CAFEVDB\Traits\ArrayTrait;
  use CAFEVDB\Traits\TimestampableEntity;

  /**
   * @var int
   */
  #[ORM\Column(type: 'integer', nullable: false)]
  #[ORM\Id]
  #[ORM\GeneratedValue(strategy: 'IDENTITY')]
  private $id;

  /**
   * @var string
   *
   * The amount invoice corresponding to this itme. Typically equal to the
   * amount of the associated receivable.
   */
  #[ORM\Column(type: 'decimal_rational_monetary', nullable: false, options: ['default' => '0.00'])]
  private RationalNumber $amount;

  /**
   * @var string
   *
   * Typically auto-generated by the descriptive texts of the associated receivables.
   */
  #[ORM\Column(type: 'string', length: 1024, nullable: false)]
  private $subject;

  /**
   * @var ProjectParticipantFieldDatum
   *
   * Each invoice item must be backed by a "receivable". As invoices may be
   * superseded by other invoices and the over-all scenario can be chaotic
   * depending on the habits of the debitor there may be more than one invoice
   * for each receivable.
   *
   * A more serious scenario are separate invoices for deposits and the final
   * amount, e.g.
   */
  #[ORM\ManyToOne(targetEntity: ProjectParticipantFieldDatum::class, inversedBy: 'invoiceItems')]
  #[ORM\JoinColumn(name: 'field_id', referencedColumnName: 'field_id', nullable: false)]
  #[ORM\JoinColumn(name: 'project_id', referencedColumnName: 'project_id', nullable: false)]
  #[ORM\JoinColumn(name: 'debitor_id', referencedColumnName: 'musician_id', nullable: false)]
  #[ORM\JoinColumn(name: 'receivable_key', referencedColumnName: 'option_key', nullable: false)]
  private $receivable;

  /**
   * @var ProjectParticipantFieldDataOption
   */
  #[ORM\ManyToOne(targetEntity: ProjectParticipantFieldDataOption::class, inversedBy: 'invoiceItems')]
  #[ORM\JoinColumn(name: 'field_id', referencedColumnName: 'field_id', nullable: false)]
  #[ORM\JoinColumn(name: 'receivable_key', referencedColumnName: 'key', nullable: false)]
  private $receivableOption;

  /**
   * @var Invoice
   *
   * An Invoice entity groups several (at least one) InvoiceItem entity.
   */
  #[ORM\JoinColumn(nullable: false)]
  #[ORM\ManyToOne(targetEntity: Invoice::class, inversedBy: 'invoiceItems', fetch: 'EXTRA_LAZY')]
  #[Gedmo\Timestampable(on: ['update', 'create', 'delete'], timestampField: 'updated')]
  private $invoice;

  /**
   * @var Project
   */
  #[ORM\ManyToOne(targetEntity: Project::class, cascade: ['persist'], fetch: 'EXTRA_LAZY')]
  private $project;

  /**
   * @var Musician
   */
  #[ORM\ManyToOne(targetEntity: Musician::class, fetch: 'EXTRA_LAZY')]
  private $debitor;

  #[ORM\JoinColumn(name: 'project_id', referencedColumnName: 'project_id', nullable: false)]
  #[ORM\JoinColumn(name: 'debitor_id', referencedColumnName: 'musician_id', nullable: false)]
  #[ORM\ManyToOne(targetEntity: ProjectParticipant::class, fetch: 'EXTRA_LAZY')]
  private $projectParticipant;

  /**
   * @var DatabaseStorageFolder
   *
   * Invoice items may be supported by documents below the project balance, or
   * by individual supporting documents which are tied to the receivables.
   */
  #[ORM\ManyToOne(targetEntity: DatabaseStorageFolder::class, fetch: 'EXTRA_LAZY')]
  private $balanceDocumentsFolder;

  /** {@inheritdoc} */
  public function __construct()
  {
    $this->arrayCTOR();
    $this->setAmount(0);
  }

  /**
   * Set id.
   *
   * @param null|int $id
   *
   * @return InvoiceItem
   */
  public function setId(?int $id):InvoiceItem
  {
    if (empty($id)) {
      $this->id = null; // flag auto-increment on insert
    }
    return $this;
  }

  /**
   * Get id.
   *
   * @return int
   */
  public function getId():?int
  {
    return $this->id;
  }

  /**
   * Set invoice.
   *
   * @param null|int|Invoice $invoice
   *
   * @return InvoiceItem
   */
  public function setInvoice(mixed $invoice):InvoiceItem
  {
    $this->invoice = $invoice;

    return $this;
  }

  /**
   * Get invoice.
   *
   * @return Invoice
   */
  public function getInvoice():?Invoice
  {
    return $this->invoice;
  }

  /**
   * Set projectParticipant.
   *
   * @param null|ProjectParticipant $projectParticipant
   *
   * @return InvoiceItem
   */
  public function setProjectParticipant(?ProjectParticipant $projectParticipant):InvoiceItem
  {
    $this->projectParticipant = $projectParticipant;

    return $this;
  }

  /**
   * Get projectParticipant.
   *
   * @return ProjectParticipant
   */
  public function getProjectParticipant():?ProjectParticipant
  {
    return $this->projectParticipant;
  }

  /**
   * Set project.
   *
   * @param null|int|Project $project
   *
   * @return InvoiceItem
   */
  public function setProject(mixed $project):InvoiceItem
  {
    $this->project = $project;

    return $this;
  }

  /**
   * Get project.
   *
   * @return Project
   */
  public function getProject():?Project
  {
    return $this->project;
  }

  /**
   * Set debitor.
   *
   * @param null|int|Musician $debitor
   *
   * @return InvoiceItem
   */
  public function setDebitor(mixed $debitor):InvoiceItem
  {
    $this->debitor = $debitor;

    return $this;
  }

  /**
   * Get debitor.
   *
   * @return Musician
   */
  public function getDebitor():?Musician
  {
    return $this->debitor;
  }

  /**
   * Set amount.
   *
   * @param int|float|string|RationalNumber $amount
   *
   * @return ProjectPayment
   */
  public function setAmount(int|float|string|RationalNumber $amount):InvoiceItem
  {
    $this->amount = RationalNumber::create($amount);

    return $this;
  }

  /**
   * Get amount.
   *
   * @return RationalNumber
   */
  public function getAmount():RationalNumber
  {
    return $this->amount;
  }

  /**
   * Set subject.
   *
   * @param null|string $subject
   *
   * @return InvoiceItem
   */
  public function setSubject(?string $subject):InvoiceItem
  {
    $this->subject = $subject;

    return $this;
  }

  /**
   * Get subject.
   *
   * @return string
   */
  public function getSubject():?string
  {
    return $this->subject;
  }

  /**
   * Set isDonation.
   *
   * @param bool $isDonation
   *
   * @return InvoiceItem
   */
  public function setIsDonation(bool $isDonation):InvoiceItem
  {
    $this->isDonation = $isDonation;

    return $this;
  }

  /**
   * Get isDonation.
   *
   * @return bool
   */
  public function getIsDonation():?bool
  {
    return $this->isDonation;
  }

  /**
   * Set receivable.
   *
   * @param ProjectParticipantFieldDatum $receivable
   *
   * @return InvoiceItem
   */
  public function setReceivable(ProjectParticipantFieldDatum $receivable):InvoiceItem
  {
    if (!empty($this->balanceDocumentsFolder) && !empty($this->receivable)) {
      $supportingDocument = $this->receivable->getSupportingDocument();
      if (!empty($supportingDocument)) {
        $this->balanceDocumentsFolder->removeDocument($supportingDocument->getFile(), $supportingDocument->getName());
      }
    }

    $this->receivable = $receivable;

    if (!empty($this->balanceDocumentsFolder) && !empty($this->receivable)) {
      $supportingDocument = $this->receivable->getSupportingDocument();
      if (!empty($supportingDocument)) {
        $this->balanceDocumentsFolder->addDirEntry($supportingDocument);
      }
    }

    return $this;
  }

  /**
   * Get receivable.
   *
   * @return ProjectParticipantFieldDatum
   */
  public function getReceivable():?ProjectParticipantFieldDatum
  {
    return $this->receivable;
  }

  /**
   * Set receivableOption.
   *
   * @param null|ProjectParticipantFieldDataOption $receivableOption
   *
   * @return InvoiceItem
   */
  public function setReceivableOption(?ProjectParticipantFieldDataOption $receivableOption):InvoiceItem
  {
    $this->receivableOption = $receivableOption;

    return $this;
  }

  /**
   * Get receivableOption.
   *
   * @return ProjectParticipantFieldDataOption
   */
  public function getReceivableOption():?ProjectParticipantFieldDataOption
  {
    return $this->receivableOption;
  }

  /**
   * Set balanceDocumentsFolder.
   *
   * @param DatabaseStorageFolder $balanceDocumentsFolder
   *
   * @return InvoiceItem
   */
  public function setBalanceDocumentsFolder(?DatabaseStorageFolder $balanceDocumentsFolder):InvoiceItem
  {
    if (!empty($this->balanceDocumentsFolder) && !empty($this->receivable)) {
      $supportingDocument = $this->receivable->getSupportingDocument();
      if (!empty($supportingDocument)) {
        $this->balanceDocumentsFolder->removeDocument($supportingDocument->getFile(), $supportingDocument->getName());
      }
    }

    $this->balanceDocumentsFolder = $balanceDocumentsFolder;

    if (!empty($this->balanceDocumentsFolder) && !empty($this->receivable)) {
      $supportingDocument = $this->receivable->getSupportingDocument();
      if (!empty($supportingDocument)) {
        $this->balanceDocumentsFolder->addDocument($supportingDocument->getFile(), $supportingDocument->getName());
      }
    }

    return $this;
  }

  /**
   * Get balanceDocumentsFolder.
   *
   * @return ?DatabaseStorageFolder
   */
  public function getBalanceDocumentsFolder():?DatabaseStorageFolder
  {
    return $this->balanceDocumentsFolder;
  }

  /** {@inheritdoc} */
  public function jsonSerialize():array
  {
    return $this->toArray();
  }
}
